Repository istio/istio.io, pull requests merged in 2018-11, with the labels that each got.

#2832 zh: Update translation for task rate-limiting
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes, lgtm, translation/chinese

#2828 zh: fix typo
  content_zh/docs/concepts/what-is-istio/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2822 zh: announcing-1.0.3
  content_zh/blog/2018/announcing-1.0.3/index.md
Labels: cla: yes, lgtm, translation/chinese

#2773 zh: content_zh/about/notes/_index.md
  content_zh/about/notes/1.1/index.md
  content_zh/about/notes/_index.md
Labels: cla: yes, lgtm, translation/chinese

#2827 grab_charts.sh: Fix istio/cni repo location and helm repo add for istio/istio helm dependencies
  scripts/grab_charts.sh
  static/charts/index.yaml
  static/charts/istio-1.1.0.tgz
  static/charts/istio-cni-0.1.0.tgz
  static/charts/istio-remote-1.1.0.tgz
Labels: cla: yes

#2461 Use port 8000 for httpbin service everywhere
  content/docs/tasks/security/mutual-tls/index.md
  content/docs/tasks/traffic-management/mirroring/index.md
  content/help/faq/security/check-policy.md
  content_zh/docs/tasks/traffic-management/mirroring/index.md
  content_zh/help/faq/security/check-policy.md
Labels: cla: yes, lgtm

#2793 zh: sync docs/tasks/traffic-management/mirrorDing/index.md
  content_zh/docs/tasks/traffic-management/mirroring/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2671 zh： content/docs/reference/config/policy-and-telemetry/adapters/circ…
  content_zh/docs/reference/config/policy-and-telemetry/adapters/circonus/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2656 zh： content/docs/reference/config/policy-and-telemetry/adapters/denier
  content_zh/docs/reference/config/policy-and-telemetry/adapters/denier/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2835 add note for authz permissive mode documentation
  content/docs/concepts/security/index.md
  content/docs/tasks/security/authz-http/index.md
Labels: cla: yes, lgtm

#2842 Remove static charts.
  scripts/grab_charts.sh
  static/charts/index.yaml
  static/charts/istio-1.1.0.tgz
  static/charts/istio-cni-0.1.0.tgz
  static/charts/istio-remote-1.1.0.tgz
Labels: cla: yes

#2703 Edit and clean the multicluster installation.
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
Labels: approved, cla: yes, lgtm

#2836 Fixing curl command to set debug mode for proxy
  content/help/ops/security/debugging-authorization/index.md
Labels: cla: yes

#2850 Improvements to egress examples
  content/docs/examples/advanced-gateways/egress-gateway-tls-origination/index.md
  content/docs/examples/advanced-gateways/egress-gateway/index.md
  content/docs/examples/advanced-gateways/egress-tls-origination/index.md
  content/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
  content/docs/examples/advanced-gateways/wildcard-https-egress-gateway/index.md
Labels: approved, cla: yes

#2853 Fixed authentication example command
  content/docs/tasks/security/authn-policy/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2855 Add a 'How to join Slack' FAQ entry
  content/help/faq/general/how-to-join-slack.md
  i18n/en.toml
Labels: approved, cla: yes, lgtm

#2857 Improve style guide to clarify common issues.
  content/about/contribute/style-guide/index.md
Labels: approved, cla: yes

#2859 fix mixer attributes descriptions
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content_zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: cla: yes, needs-ok-to-test

#2858 zh: sync content/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2860 Fix redundant number - 2317
  content/docs/tasks/telemetry/tcp-metrics/index.md
  content_zh/docs/tasks/telemetry/tcp-metrics/index.md
Labels: cla: yes

#2861 Add baseURL for develop mode
  Makefile
Labels: cla: yes

#2863 Minimal installation: Fix mixer flags
  content/docs/setup/kubernetes/minimal-install/index.md
Labels: cla: yes

#2862 merge changes from 1.1 for egress tls origination
  content/docs/examples/advanced-egress/egress-tls-origination/index.md
Labels: cla: yes

#2846 kiali task - do not rely on the gateway - use port-forward
  content/docs/tasks/telemetry/kiali/index.md
Labels: approved, cla: yes, lgtm

#2864 Add trulia.com to our exception list, since it is causing a lot of fa…
  scripts/lint_site.sh
Labels: approved, cla: yes, lgtm

#2847 updating multicluster over gateways
  .spelling
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/multicluster-with-gateways.svg
Labels: approved, cla: yes, lgtm

#2869 Correct Kiali URL
  content/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes, needs-ok-to-test

#2868 Delete Servicegraph
  content/docs/tasks/telemetry/servicegraph/index.md
  content/docs/tasks/telemetry/servicegraph/servicegraph-example.png
  content_zh/docs/tasks/telemetry/servicegraph/index.md
Labels: cla: yes, needs-ok-to-test

#2871 Revert "Delete Servicegraph"
  content/docs/tasks/telemetry/servicegraph/index.md
  content/docs/tasks/telemetry/servicegraph/servicegraph-example.png
  content_zh/docs/tasks/telemetry/servicegraph/index.md
Labels: approved, cla: yes, lgtm

#2865 docs: add a task for weighted TCP routing
  content/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: cla: yes, lgtm

#2856 zh:content/docs/tasks/security/authz-http/
  content_zh/docs/tasks/security/authz-http/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2874 Delete Service Graph
  content/about/feature-stages/index.md
  content/about/notes/0.6/index.md
  content/blog/2018/soft-multitenancy/index.md
  content/docs/reference/config/installation-options/index.md
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/tasks/security/https-overlay/index.md
  content/docs/tasks/telemetry/servicegraph/index.md
  content/docs/tasks/telemetry/servicegraph/servicegraph-example.png
  content_zh/about/feature-stages/index.md
  content_zh/about/notes/0.6/index.md
  content_zh/blog/2018/soft-multitenancy/index.md
  content_zh/docs/reference/config/installation-options/index.md
  content_zh/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content_zh/docs/tasks/security/https-overlay/index.md
  content_zh/docs/tasks/telemetry/servicegraph/index.md
Labels: approved, cla: yes, lgtm

#2841 Remove the canned credentials in Kiali Task instructions.
  content/docs/tasks/telemetry/kiali/index.md
Labels: approved, cla: yes, lgtm

#2878 [Kiali] the API changed - this reflects that change
  content/docs/tasks/telemetry/kiali/index.md
Labels: approved, cla: yes, lgtm

#2880 zh: /docs/setup/kubernetes/multicluster-install/_index.md
  content_zh/docs/setup/kubernetes/multicluster-install/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2883 zh/sync: content_zh/docs/examples/multicluster/_index.md
  content_zh/docs/examples/multicluster/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2882 zh/sync: content_zh/docs/examples/advanced-gateways/_index.md
  content_zh/docs/examples/advanced-gateways/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2347 Consuming External MongoDB Services
  .spelling
  content/blog/2018/egress-mongo/bookinfo-ratings-v2-mongodb-external.svg
  content/blog/2018/egress-mongo/errorFetchingBookRating.png
  content/blog/2018/egress-mongo/externalDBRatings.png
  content/blog/2018/egress-mongo/index.md
Labels: cla: yes, lgtm

#2872 Clarify scope of consul install
  content/docs/setup/consul/install/index.md
  content/docs/setup/consul/quick-start/index.md
Labels: cla: yes

#2885 [Kiali] change in the root context path
  content/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes

#2844 Add LightStep tracing docs
  .spelling
  content/docs/tasks/telemetry/distributed-tracing-lightstep/index.md
  content/docs/tasks/telemetry/distributed-tracing-lightstep/istio-tracing-details-lightstep.png
  content/docs/tasks/telemetry/distributed-tracing-lightstep/istio-tracing-list-lightstep.png
  content/docs/tasks/telemetry/distributed-tracing/index.md
Labels: cla: yes, lgtm

#2830 Remove confusing cleaning up step for circuit-breaking and mirroring
  content/docs/tasks/traffic-management/circuit-breaking/index.md
  content/docs/tasks/traffic-management/mirroring/index.md
  content_zh/docs/tasks/traffic-management/circuit-breaking/index.md
  content_zh/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes

#2867 correct the issues in istio-dashboard page
  content/docs/tasks/telemetry/using-istio-dashboard/index.md
  content_zh/docs/tasks/telemetry/using-istio-dashboard/index.md
Labels: cla: yes

#2888 Clarify 1.0.3 ServiceEntry patch notes
  content/about/notes/1.0.3/index.md
Labels: approved, lgtm

#2894 Fix Warning icon showing invalidation
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
Labels: approved, cla: yes, lgtm

#2892 rewrite the note about ingress gateway secret access
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: approved, cla: yes, lgtm

#2899 Wildcard egress example clarifications and improvements
  content/docs/examples/advanced-gateways/_index.md
  content/docs/examples/advanced-gateways/egress-gateway/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/EgressGatewayWithSNIProxy.svg
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes

#2901 Fix wildcard example description
  content/blog/2018/egress-mongo/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
Labels: approved, cla: yes

#2889 Add initial istioctl and galley release notes
  .spelling
  content/about/notes/1.1/index.md
Labels: approved, cla: yes, lgtm

#2906 Update Wavefront latest release tag
  content/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
Labels: cla: yes

#2896 change the name of the Envoy's container in egress gateway
  content/docs/examples/advanced-gateways/egress-gateway-tls-origination/index.md
  content/docs/examples/advanced-gateways/egress-gateway/index.md
  content_zh/docs/examples/advanced-gateways/egress-gateway/index.md
Labels: cla: yes, lgtm

#2908 zh: content/docs/examples/multicluster/iks-icp/index.md
  content_zh/docs/examples/multicluster/iks-icp/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2909 zh: content/docs/setup/kubernetes/multicluster-install/gateways
  content_zh/docs/setup/kubernetes/multicluster-install/gateways/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2913 Fix typo: oppenssl -> openssl
  content/docs/tasks/security/mutual-tls/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2915 zh: delete content_zh/docs/examples/advanced-gateways/wildcard-https-egress-gateway
  content_zh/docs/examples/advanced-gateways/wildcard-https-egress-gateway/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2680 zh:add docker for desktop url for k8s
  content_zh/docs/setup/kubernetes/helm-install/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2879 new blog post on incremental istio usage for traffic management
  content/blog/2018/incremental-traffic-management/fifty-fifty-ingress-gateway.png
  content/blog/2018/incremental-traffic-management/fifty-fifty.png
  content/blog/2018/incremental-traffic-management/index.md
Labels: approved, cla: yes, lgtm

#2919 Compensate for a Hugo bug when running on Windows.
  layouts/shortcodes/relnote_links.html
Labels: approved, cla: yes

#2904 documentation for end-user authencation on ingress-gateway (#2243)
  content/docs/tasks/security/authn-policy/index.md
Labels: approved, cla: yes, lgtm

#2651 pointing to proper grafana dashboard
  content/docs/setup/kubernetes/quick-start-gke-dm/dm_grafana.png
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
Labels: approved, cla: yes

#2920 Fix some mishandling of path separators, leading to problems on Windows.
  layouts/shortcodes/relnote_links.html
  layouts/shortcodes/template_table.html
Labels: approved, cla: yes

#2921 Update to Hugo 0.51
  .circleci/config.yml
  Makefile
  netlify.toml
  scripts/Dockerfile
Labels: approved, cla: yes

#2925 new blog post on traffic mgmt, approved on master
  content/blog/2018/incremental-traffic-management/fifty-fifty-ingress-gateway.png
  content/blog/2018/incremental-traffic-management/fifty-fifty.png
  content/blog/2018/incremental-traffic-management/index.md
Labels: cla: yes, needs-ok-to-test

#2876 update chart requirements
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: no, lgtm

#2927 fix issue with dollar sign and curly brackets
  content/docs/tasks/security/authn-policy/index.md
  content_zh/docs/tasks/security/authn-policy/index.md
Labels: cla: yes, lgtm, ok-to-test

#2926 remove irrelevant output line from auth policy task
  content/docs/tasks/security/authn-policy/index.md
Labels: cla: yes, needs-ok-to-test

#2910 release notes 1.0.4
  content/about/notes/1.0.4/index.md
  content/blog/2018/announcing-1.0.4/index.md
Labels: approved, cla: yes, lgtm

#2929 zh: content_zh/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content_zh/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2933 Fix a bunch of absolute links that should have been relative.
  content/about/contribute/github/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
  content/docs/setup/kubernetes/advanced-install/index.md
  content/docs/setup/kubernetes/platform-setup/docker-for-desktop/index.md
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/setup/kubernetes/quick-start/index.md
  content/help/faq/telemetry/disabling-zipkin.md
  content/help/ops/setup/validation/index.md
  content/help/ops/setup/webhook/index.md
  content/help/ops/telemetry/missing-metrics/index.md
  content_zh/about/contribute/github/index.md
  content_zh/docs/setup/kubernetes/platform-setup/docker-for-desktop/index.md
  content_zh/help/ops/telemetry/missing-metrics/index.md
  scripts/lint_site.sh
Labels: cla: yes

#2934 Fix a typo in mTLS tutorial
  content/docs/tasks/security/mutual-tls/index.md
Labels: approved, cla: yes, lgtm
