Repository istio/istio.io, pull requests merged in 2018-06, with the labels that each got.

#1401 update limitation of converter tool
  content/about/notes/0.8.md
Labels: approved, cla: yes, lgtm

#1406 fix image missing issue.
  content/docs/concepts/traffic-management/request-routing.md
Labels: cla: yes, lgtm

#1408 Couple site fixes.
  content/about/notes/0.8.md
  layouts/_default/baseof.html
  layouts/partials/header.html
  src/js/styleSwitcher.js
  static/js/styleSwitcher.min.js
  static/js/styleSwitcher.min.js.map
Labels: approved, cla: yes

#1407 fix doc issues for rule configuration.
  content/docs/concepts/traffic-management/rules-configuration.md
Labels: cla: yes

#1405 #1324 fix: logs exposed by istio-telemetry and not by istio-mixer for now.
  content/docs/tasks/telemetry/metrics-logs.md
Labels: cla: yes, needs-ok-to-test

#1413 update cluster version to 1.9.7-gke.1
  content/docs/setup/kubernetes/quick-start.md
Labels: cla: yes, needs-ok-to-test

#1412 helm install - write output to file
  content/docs/setup/kubernetes/helm-install.md
Labels: cla: yes, needs-ok-to-test

#1414 Add migration guide for mtls annotation.
  content/docs/setup/kubernetes/upgrading-istio.md
Labels: cla: yes

#1403 add data plane update step
  content/docs/setup/kubernetes/upgrading-istio.md
Labels: approved, cla: yes

#1419 Add TOC to reference pages.
  layouts/partials/primary-bottom.html
  layouts/partials/primary-top.html
  layouts/partials/toc.html
Labels: approved, cla: yes

#1417 Cleanup the style guide and fix random formatting errors.
  .spelling
  content/about/contribute/style-guide.md
  content/about/release-cadence.md
  content/docs/setup/kubernetes/quick-start.md
  content/docs/setup/kubernetes/upgrading-istio.md
  content/docs/tasks/security/https-overlay.md
  content/docs/tasks/security/mutual-tls.md
  content/help/faq/general/what-deployment-environment.md
Labels: approved, cla: yes

#1420 Fix Istio version variable in quick start
  content/docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes, lgtm

#1422 use html encoding for the forward slash in CIDR blocks
  content/docs/tasks/traffic-management/egress.md
Labels: approved, cla: yes

#1425 adding a quick url to show user how to obtain GATEWAY_URL
  content/docs/tasks/traffic-management/request-routing.md
Labels: approved, cla: yes, lgtm

#1426 annotation in metadata not directly in template
  content/docs/setup/kubernetes/upgrading-istio.md
Labels: approved, cla: yes, lgtm

#1434 IBM Container Service Should be IBM Kubernetes Service.
  content/docs/tasks/traffic-management/egress.md
Labels: cla: yes

#1415 Update distributed tracing doc to reflect changes in 0.8.0
  content/docs/setup/kubernetes/img/dm-tracing.png
  content/docs/setup/kubernetes/img/dm_zipkin.png
  content/docs/setup/kubernetes/quick-start-gke-dm.md
  content/docs/setup/kubernetes/quick-start.md
  content/docs/tasks/telemetry/distributed-tracing.md
  content/docs/tasks/telemetry/img/istio-tracing-details.png
  content/docs/tasks/telemetry/img/istio-tracing-list.png
  content/docs/tasks/telemetry/img/jaeger_dashboard.png
  content/docs/tasks/telemetry/img/jaeger_trace.png
  content/docs/tasks/telemetry/img/zipkin_dashboard.png
  content/docs/tasks/telemetry/img/zipkin_span.png
Labels: cla: yes, needs-ok-to-test

#1430 Adjust format for request-timeouts.md.
  content/docs/tasks/traffic-management/request-timeouts.md
Labels: cla: yes

#1431 put links to the previous docs (0.7) in the 0.8 documents
  content/docs/tasks/traffic-management/circuit-breaking.md
  content/docs/tasks/traffic-management/egress-tcp.md
  content/docs/tasks/traffic-management/egress.md
  content/docs/tasks/traffic-management/fault-injection.md
  content/docs/tasks/traffic-management/ingress.md
  content/docs/tasks/traffic-management/mirroring.md
  content/docs/tasks/traffic-management/request-routing.md
  content/docs/tasks/traffic-management/request-timeouts.md
  content/docs/tasks/traffic-management/traffic-shifting.md
Labels: approved, cla: yes, lgtm

#1435 update httpbin deployment steps.
  content/docs/tasks/traffic-management/ingress.md
Labels: approved, cla: yes, lgtm

#1423 unite all the ingress cleanup steps in one step
  content/docs/tasks/traffic-management/ingress.md
Labels: approved, cla: yes, lgtm

#1429 Capitalize NodePort and make a link to Kubernetes documentation
  content/docs/tasks/traffic-management/ingress.md
Labels: approved, cla: yes

#1356 Some cleanup for mesh expansion.
  .spelling
  content/docs/setup/kubernetes/mesh-expansion.md
Labels: cla: yes

#1439 Correct package naming.
  content/docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes

#1440 Fix a couple issues around code blocks.
  src/js/misc.js
  src/js/prism.js
  static/js/all.min.js
  static/js/all.min.js.map
Labels: approved, cla: yes

#1445 fix wrong key of DestnationRule from name to host
  content/blog/2018/v1alpha3-routing.md
Labels: cla: yes, lgtm

#1444 fix admissionregistration API version
  content/docs/setup/kubernetes/sidecar-injection.md
Labels: cla: yes, needs-ok-to-test

#1421 use HTTPS egress instead of HTTP + TLS origination
  content/docs/tasks/traffic-management/egress.md
Labels: cla: yes

#1449 Doc corrections and improvements
  content/docs/guides/bookinfo.md
  content/docs/setup/kubernetes/quick-start.md
  content/docs/tasks/traffic-management/egress.md
  content/docs/tasks/traffic-management/request-routing.md
Labels: cla: yes

#1450 Use global.proxy.includeIPRanges instead of --includeIPRanges
  content/docs/setup/kubernetes/helm-install.md
  content/docs/tasks/traffic-management/egress.md
Labels: cla: yes

#1437 Update GCP DM docs for istio08 release
  content/docs/setup/kubernetes/img/dm_kubernetes_workloads.png
  content/docs/setup/kubernetes/quick-start-gke-dm.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1392 Update svc and pod after installation on k8s
  content/docs/setup/kubernetes/quick-start.md
Labels: cla: yes

#1454 Add setting host in requests to ingress and explanation about the browser access
  content/docs/tasks/traffic-management/ingress.md
Labels: cla: yes, lgtm

#1443 Introduce better linking support to github.com/istio/istio
  content/about/contribute/writing-a-new-topic.md
  content/about/feature-stages.md
  content/blog/2017/0.1-auth.md
  content/blog/2017/0.1-canary.md
  content/blog/2017/adapter-model.md
  content/blog/2018/egress-https.md
  content/blog/2018/egress-tcp.md
  content/blog/2018/soft-multitenancy.md
  content/docs/concepts/security/rbac.md
  content/docs/guides/bookinfo.md
  content/docs/guides/integrating-vms.md
  content/docs/performance-and-scalability/microbenchmarks.md
  content/docs/performance-and-scalability/scenarios.md
  content/docs/setup/consul/install.md
  content/docs/setup/consul/quick-start.md
  content/docs/setup/eureka/install.md
  content/docs/setup/eureka/quick-start.md
  content/docs/setup/kubernetes/helm-install.md
  content/docs/setup/kubernetes/mesh-expansion.md
  content/docs/setup/kubernetes/multicluster-install.md
  content/docs/setup/kubernetes/quick-start-gke-dm.md
  content/docs/setup/kubernetes/quick-start.md
  content/docs/setup/kubernetes/sidecar-injection.md
  content/docs/setup/kubernetes/upgrading-istio.md
  content/docs/tasks/policy-enforcement/rate-limiting.md
  content/docs/tasks/security/authn-policy.md
  content/docs/tasks/security/basic-access-control.md
  content/docs/tasks/security/health-check.md
  content/docs/tasks/security/https-overlay.md
  content/docs/tasks/security/mutual-tls.md
  content/docs/tasks/security/plugin-ca-cert.md
  content/docs/tasks/security/role-based-access-control.md
  content/docs/tasks/security/secure-access-control.md
  content/docs/tasks/telemetry/servicegraph.md
  content/docs/tasks/telemetry/tcp-metrics.md
  content/docs/tasks/telemetry/using-istio-dashboard.md
  content/docs/tasks/traffic-management/circuit-breaking.md
  content/docs/tasks/traffic-management/egress-tcp.md
  content/docs/tasks/traffic-management/egress.md
  content/docs/tasks/traffic-management/fault-injection.md
  content/docs/tasks/traffic-management/ingress.md
  content/docs/tasks/traffic-management/mirroring.md
  content/docs/tasks/traffic-management/request-routing.md
  content/docs/tasks/traffic-management/request-timeouts.md
  content/docs/tasks/traffic-management/traffic-shifting.md
  data/args.yml
  layouts/_default/baseof.html
  layouts/shortcodes/branch_name.html
  src/js/misc.js
  static/js/all.min.js
  static/js/all.min.js.map
Labels: approved, cla: yes

#1456 Add route rule troubleshooting entry
  content/help/troubleshooting.md
Labels: cla: yes

#1457 Remove the deprecated --debug in istioctl
  content/docs/guides/bookinfo.md
  content/docs/tasks/security/https-overlay.md
  content/docs/tasks/security/mutual-tls.md
  content/docs/tasks/traffic-management/circuit-breaking.md
  content/help/troubleshooting.md
Labels: cla: yes, lgtm

#1453 Updated OpenShift section to match the new list of service accounts
  content/docs/setup/kubernetes/quick-start.md
Labels: cla: yes

#1400 Update the Istio security tasks for V0.8.
  content/docs/tasks/security/authn-policy.md
  content/docs/tasks/security/health-check.md
  content/docs/tasks/security/https-overlay.md
  content/docs/tasks/security/mutual-tls.md
  content/docs/tasks/security/plugin-ca-cert.md
Labels: cla: yes, lgtm

#1468 Format the output of curl to json.
  content/docs/tasks/traffic-management/mirroring.md
Labels: cla: yes

#1472 Basic auth clean.
  content/docs/tasks/security/authn-policy.md
Labels: cla: yes

#1459 Update route rules for mtls
  content/docs/tasks/traffic-management/request-routing.md
Labels: approved, cla: yes, lgtm

#1474 use html encoding for the forward slash.
  content/docs/setup/kubernetes/sidecar-injection.md
Labels: cla: yes

#1471 Updated maxConnections to 1.
  content/docs/tasks/traffic-management/circuit-breaking.md
Labels: cla: yes, lgtm

#1476 Use route rules from samples/bookinfo/routing.
  content/docs/tasks/security/secure-access-control.md
Labels: cla: yes

#1462 Updated features list based on 0.8 release
  content/about/feature-stages.md
Labels: cla: yes

#1473 Added cleanup for mtls.
  content/docs/tasks/security/mutual-tls.md
Labels: cla: yes

#1469 Add sidecar auto injection for circuit break example.
  content/docs/tasks/traffic-management/circuit-breaking.md
Labels: cla: yes

#1483 Fix indent in fault injection task
  content/docs/tasks/traffic-management/fault-injection.md
Labels: cla: yes

#1480 Using virutalservice for rate limit.
  content/docs/tasks/policy-enforcement/rate-limiting.md
Labels: cla: yes

#1479 Correct some errors in mutual tls over https.
  content/docs/tasks/security/https-overlay.md
Labels: cla: yes

#1475 Use virtualservices for basic access control.
  content/docs/tasks/security/basic-access-control.md
Labels: cla: yes

#1478 Remove global.mtls.mtlsExcludedServices.
  content/docs/setup/kubernetes/helm-install.md
  content/help/faq/security/accessing-control-services.md
Labels: cla: yes

#1487 Remove source.principal attribute since it did not make the 0.8 cut
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary.md
Labels: cla: yes

#1489 plain -> command for helm template commands
  content/docs/tasks/traffic-management/egress.md
Labels: cla: yes

#1494 redirect default netlify subdomain to our primary domain
  static/_redirects
Labels: cla: yes

#1499 Add Frank while I'm out
  OWNERS
Labels: approved, cla: yes

#1485 Add documentation for default metrics exported by Istio
  .spelling
  content/docs/reference/config/policy-and-telemetry/metrics.md
Labels: approved, cla: yes, lgtm

#1492 add egress-tls-origination task
  .spelling
  content/docs/tasks/traffic-management/egress-tls-origination.md
Labels: cla: yes, lgtm

#1500 add Chinese translation with index pages
  config.toml
  content_cn/_index.md
  content_cn/about/_index.md
  content_cn/blog/_index.md
  content_cn/community/_index.md
  content_cn/docs/_index.md
  content_cn/feed.md
  content_cn/help/_index.md
  content_cn/search/_index.md
Labels: cla: yes, lgtm

#1504 Update to ingress name
  content/docs/setup/kubernetes/quick-start-gke-dm.md
Labels: cla: yes, needs-ok-to-test

#1386 Add documentation about exporting logs from stackdriver to different sinks like bigquery
  .spelling
  content/blog/2018/export-logs-through-stackdriver.md
  content/blog/2018/img/istio-analytics-using-stackdriver.png
Labels: cla: yes

#1503 Update for installations with mTLS auth enabled
  content/docs/tasks/traffic-management/mirroring.md
Labels: approved, cla: yes, needs-ok-to-test

#1513 Removed link annotations
  content/docs/setup/kubernetes/quick-start.md
Labels: cla: yes

#1514 Potential typo in rules-configuration.yml
  content/docs/concepts/traffic-management/rules-configuration.md
Labels: cla: no, needs-ok-to-test

#1508 Update security faq
  content/help/faq/security/istio-to-not-istio.md
Labels: approved, cla: yes, lgtm

#1517 Clarify bookinfo instructions
  content/docs/guides/bookinfo.md
Labels: approved, cla: yes

#1518 docker image to run website linters
  Dockerfile
Labels: approved, cla: yes, lgtm

#1484 Update remote cluster RBAC instructions for kubernetes multicluster setup
  content/docs/setup/kubernetes/multicluster-install.md
Labels: cla: yes, lgtm

#1520 fix format issue for access control doc.
  content/docs/tasks/security/basic-access-control.md
Labels: cla: yes

#1521 Add option when auto injection is enabled.
  content/docs/tasks/security/mutual-tls.md
Labels: cla: yes

#1511 remove egress TCP task
  content/about/feature-stages.md
  content/blog/2018/egress-tcp.md
  content/docs/tasks/traffic-management/egress-tcp.md
Labels: cla: yes, lgtm

#1525 Update Makefile to leverage new docker-based stuff.
  Makefile
  README.md
  scripts/build_site.sh
  scripts/gen_site.sh
  scripts/lint_site.sh
Labels: approved, cla: yes

#1527 Remove all target since Netlify has been updated.
  Makefile
Labels: approved, cla: yes

#1524 fix command to get INGRESS_POD_NAME
  content/help/troubleshooting.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1529 Bunch 'o fixes
  Makefile
  layouts/partials/footer.html
  layouts/partials/primary-top.html
  scripts/serve_site.sh
Labels: approved, cla: yes

#1490 Fixed default values
  content/docs/setup/kubernetes/helm-install.md
Labels: cla: yes, needs-ok-to-test

#1532 Add a netlify.toml file to control options.
  Makefile
  netlify.toml
Labels: approved, cla: yes

#1496 Add egress gateway traffic management task
  .spelling
  content/docs/tasks/traffic-management/egress-gateway.md
Labels: cla: yes, lgtm

#1523 quick start doc translation
  content_zh/_index.md
  content_zh/docs/setup/kubernetes/_index.md
  content_zh/docs/setup/kubernetes/img/dm-tracing.png
  content_zh/docs/setup/kubernetes/img/dm_bookinfo.png
  content_zh/docs/setup/kubernetes/img/dm_gcp_iam.png
  content_zh/docs/setup/kubernetes/img/dm_gcp_iam_role.png
  content_zh/docs/setup/kubernetes/img/dm_grafana.png
  content_zh/docs/setup/kubernetes/img/dm_kubernetes_workloads.png
  content_zh/docs/setup/kubernetes/img/dm_launcher.png
  content_zh/docs/setup/kubernetes/img/dm_prometheus.png
  content_zh/docs/setup/kubernetes/img/dm_servicegraph.png
  content_zh/docs/setup/kubernetes/quick-start.md
  content_zh/help/_index.md
  scripts/lint_site.sh
Labels: cla: yes, needs-ok-to-test

#1531 Link to bookinfo.sidecars.yaml is broken
  content/docs/guides/bookinfo.md
Labels: cla: yes, needs-ok-to-test

#1530 Remove the limitation of accessing service mesh via browser.
  content/docs/tasks/traffic-management/ingress.md
Labels: cla: yes

#1543 Update security faq (#1508)
  content/help/faq/security/istio-to-not-istio.md
Labels: cla: yes

#1544 Update sidecar injector docs
  .spelling
  content/docs/setup/kubernetes/sidecar-injection.md
Labels: cla: yes, lgtm

#1546 Update HTTPRoute timeout doc
  content/docs/reference/config/istio.networking.v1alpha3.html
Labels: approved, cla: yes, lgtm

#1541 Add gotchas to the doc authoring notes.
  .spelling
  content/about/contribute/writing-a-new-topic.md
Labels: approved, cla: yes

#1548 Remove egress tcp task
  content/about/feature-stages.md
  content/blog/2018/egress-tcp.md
  content/docs/tasks/traffic-management/egress-tcp.md
Labels: cla: yes

#1542 Add documentation for default metrics exported by Istio (#1485)
  .spelling
  content/docs/reference/config/policy-and-telemetry/metrics.md
Labels: cla: yes

#1550 blog: mixer-spof-myth (Chinese version)
  content_zh/blog/2017/img/mixer-spof-myth-1.svg
  content_zh/blog/2017/img/mixer-spof-myth-2.svg
  content_zh/blog/2017/mixer-spof-myth.md
Labels: cla: yes, needs-ok-to-test

#1554 RSS Feed update
  layouts/feed/single.rss.xml
Labels: approved, cla: yes

#1555 add zh i18n yaml file
  i18n/zh.toml
Labels: cla: yes, needs-ok-to-test

#1553 Fix issue #6399
  content/docs/tasks/traffic-management/ingress.md
Labels: cla: yes

#1558 fix format
  content/docs/guides/bookinfo.md
Labels: approved, cla: yes

#1557 make reference generation work with golang vendor directory
  content/docs/reference/commands/istioctl.html
  content/docs/reference/commands/pilot-agent.html
  content/docs/reference/commands/pilot-discovery.html
  content/docs/reference/config/istio.networking.v1alpha3.html
  content/docs/reference/config/policy-and-telemetry/adapters/signalfx.html
  content/docs/reference/config/policy-and-telemetry/templates/kubernetes.html
  content/docs/reference/config/policy-and-telemetry/templates/tracespan.html
  scripts/grab_reference_docs.sh
Labels: cla: yes

#1562 Update quick-start-gke-dm.md
  content/docs/setup/kubernetes/quick-start-gke-dm.md
Labels: cla: yes, needs-ok-to-test

#1567 Add support for snippets and file content insertion.
  content/about/contribute/writing-a-new-topic.md
  examples/snippet_example.txt
  layouts/shortcodes/fetch_content.html
  layouts/shortcodes/file_content.html
  scripts/grab_reference_docs.sh
Labels: approved, cla: yes

#1549 Added more ep for istio remote chart.
  content/docs/setup/kubernetes/multicluster-install.md
Labels: cla: yes

#1552 translating what is istio - overview into Chinese
  .spelling
  content_zh/docs/concepts/what-is-istio/overview.md
Labels: cla: yes, needs-ok-to-test

#1566 translating traffic management overview into Chinese
  content_zh/docs/_index.md
  content_zh/docs/concepts/traffic-management/_index.md
  content_zh/docs/concepts/traffic-management/overview.md
Labels: approved, cla: yes, lgtm

#1572 configuration for prometheus has changed
  content/help/troubleshooting.md
Labels: cla: yes, needs-ok-to-test

#1573 add indexes for sections in docs and other fix
  content_zh/docs/_index.md
  content_zh/docs/concepts/_index.md
  content_zh/docs/guides/_index.md
  content_zh/docs/performance-and-scalability/_index.md
  content_zh/docs/reference/_index.md
  content_zh/docs/setup/_index.md
  content_zh/docs/setup/kubernetes/quick-start.md
  content_zh/docs/tasks/_index.md
Labels: cla: yes, needs-ok-to-test

#1569 Ingress task clarifications
  content/docs/tasks/traffic-management/ingress.md
Labels: approved, cla: yes

#1570 Monitoring and access control for egress traffic
  .spelling
  content/blog/2018/egress-monitoring-access-control.md
  content/blog/2018/img/dashboard-egress-gateway.png
  content/blog/2018/img/egress-adapters-monitoring-policy.svg
  content/blog/2018/img/egress-adapters-monitoring.svg
  content/blog/2018/img/http-to-gateway.svg
  content/blog/2018/img/https-to-gateway.svg
Labels: approved, cla: yes, lgtm

#1582 Improve linting script
  scripts/lint_site.sh
Labels: approved, cla: yes

#1581 Use route rules in istio file directly.
  content/docs/tasks/policy-enforcement/rate-limiting.md
  content/docs/tasks/security/basic-access-control.md
Labels: approved, cla: yes, lgtm

#1571 Add health check task
  content/docs/tasks/traffic-management/app-health-check.md
Labels: approved, cla: yes, lgtm

#1587 fix cluster names in circuit breaker docs
  content/docs/tasks/traffic-management/circuit-breaking.md
Labels: approved, cla: yes, lgtm

#1578 translating pilot into Chinese
  content_zh/docs/concepts/traffic-management/pilot.md
Labels: cla: yes

#1594 add istio.io/tools to golang vanity redirects
  static/_redirects
  static/golang/tools.html
Labels: cla: yes

#1595 add istio.io/tools to golang vanity redirects (#1594)
  static/_redirects
  static/golang/tools.html
Labels: cla: yes

#1596 Adding myself as OWNERS for Chinese Content.
  content_zh/OWNERS
Labels: cla: yes

#1597 translating discovery & load balancing into Chinese
  content_zh/docs/concepts/traffic-management/load-balancing.md
Labels: approved, cla: yes, lgtm

#1584 Chinese: request-routing.md
  content_zh/docs/concepts/traffic-management/request-routing.md
Labels: approved, cla: yes, lgtm

#1606 Update picture links in Chinese content, use the absURL instead
  content_zh/docs/concepts/policies-and-telemetry/overview/index.md
  content_zh/docs/concepts/traffic-management/load-balancing/index.md
  content_zh/docs/concepts/traffic-management/overview/index.md
  content_zh/docs/concepts/traffic-management/pilot/index.md
  content_zh/docs/concepts/traffic-management/request-routing/index.md
Labels: approved, cla: yes, lgtm

#1604 Use correct syntax with NodePort configuration
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes, lgtm

#1608 Mention kube service restrictions for routing
  content/docs/tasks/traffic-management/request-routing/index.md
Labels: approved, cla: yes, lgtm

#1609 Remove http: from command
  content/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: approved, cla: yes

#1611 fix the kubectl logs command usage
  content/docs/tasks/telemetry/metrics-logs/index.md
  content/help/faq/mixer/mixer-self-monitoring.md
  content/help/troubleshooting/index.md
Labels: cla: yes, needs-ok-to-test

#1607 update URLs which have been moved to other places
  content/about/notes/0.2/index.md
  content/blog/2017/0.1-auth/index.md
  content/blog/2017/0.2-announcement/index.md
  content/blog/2018/soft-multitenancy/index.md
  content/docs/setup/kubernetes/quick-start/index.md
  content/help/faq/mixer/seeing-mixer-config.md
  content/help/faq/security/use-k8s-secrets.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes, lgtm

#1613 attributes: update desitnation name and namespace definitions
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: cla: yes

#1618 make MacOS lower case, macOS(c) it is a trademark of Apple
  .spelling
  content/docs/setup/consul/quick-start/index.md
  content/docs/setup/eureka/quick-start/index.md
  content/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes, lgtm

#1621 add make gen for linting
  README.md
Labels: cla: yes

#1619 Update documentation with latest Ansible changes
  content/docs/setup/kubernetes/ansible-install/index.md
Labels: approved, cla: yes, lgtm

#1590 Add secure ingress task
  .spelling
  content/docs/examples/endpoints/index.md
  content/docs/tasks/traffic-management/ingress/index.md
  content/docs/tasks/traffic-management/secure-ingress/index.md
  content/help/faq/security/secure-ingress.md
Labels: approved, cla: yes

#1625 Finalize secure gateways task
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: approved, cla: yes, lgtm

#1551 translation: soft multitenancy
  content_zh/blog/2018/soft-multitenancy/index.md
Labels: approved, cla: yes, lgtm

#1623 Chinese: rules-configuration
  content_zh/docs/concepts/traffic-management/rules-configuration/index.md
Labels: approved, cla: yes, lgtm

#1634 translating security index into Chinese
  content_zh/docs/concepts/security/_index.md
Labels: approved, cla: yes, lgtm

#1630 fixed: url to mysql shell
  content/blog/2018/egress-tcp/index.md
Labels: cla: yes, needs-ok-to-test

#1506 Adapt servicegraph task description to istio
  content/docs/tasks/telemetry/servicegraph.md
Labels: cla: no

#1614 Updated image link for overview.
  content_zh/docs/concepts/what-is-istio/overview/index.md
Labels: approved, cla: yes

#1615 Translate V1alpha3 routing introduction blog to Chinese
  content_zh/blog/2018/v1alpha3-routing/index.md
Labels: approved, cla: yes

#1627 attributes: replace reporter local with reporter type
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: cla: yes

#1626 A few rendering fixes.
  content/about/_index.md
  content/help/_index.md
  layouts/partials/footer.html
  layouts/shortcodes/idea_icon.html
  src/sass/base/_common.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
  static/img/bulb.svg
Labels: approved, cla: yes

#1629 Concept handling failures
  content_zh/docs/concepts/traffic-management/handling-failures/index.md
Labels: approved, cla: yes, lgtm

#1510 Add step to set up GOOGLE_APPLICATION_CREDENTIALS
  content/blog/2018/export-logs-through-stackdriver/index.md
Labels: cla: yes

#1639 Update authn policy tasks with global policy.
  content/docs/tasks/security/authn-policy/index.md
Labels: approved, cla: yes, lgtm

#1643 Improve how we render section index pages.
  content/about/_index.md
  content/about/notes/_index.md
  content/docs/_index.md
  content/docs/setup/_index.md
  content/help/_index.md
  content/help/bugs/index.md
  content_zh/about/_index.md
  content_zh/docs/_index.md
  content_zh/help/_index.md
  layouts/partials/section-index-level.html
  layouts/section-index/list.html
  src/sass/layouts/_section-index.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: approved, cla: yes

#1628 Concept fault injection
  content_zh/docs/concepts/traffic-management/fault-injection/index.md
Labels: approved, cla: yes, lgtm
