Repository istio/istio.io, pull requests merged in 2018-08, with the labels that each got.

#2097 Add section to tracing task to cover sampling.
  content/about/feature-stages/index.md
  content/docs/tasks/telemetry/distributed-tracing/index.md
Labels: approved, cla: yes, lgtm

#2110 Translate Istio 1.0 canary into Chinese
  content_zh/blog/2017/0.1-canary/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2106 Move egress tasks to examples
  content/docs/examples/advanced-egress/_index.md
  content/docs/examples/advanced-egress/egress-gateway/index.md
  content/docs/examples/advanced-egress/egress-tls-origination/index.md
Labels: approved, cla: yes, lgtm

#2090 remove unnecessary mesh gateway specification
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#2098 Add documentation for redisquota adapter in rate limiting doc
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes

#2102 Fix typo in "Delayering Istio" blog post
  .spelling
  content/blog/2018/delayering-istio/delayering-istio.md
Labels: cla: yes

#2104 fix multicluster doc issues.
  content/docs/setup/kubernetes/multicluster-install/index.md
Labels: approved, cla: yes, lgtm

#2091 remove unnecessary gateway spec from release 1.0
  content/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes

#2082 Minikube settings
  .spelling
  content/docs/setup/kubernetes/platform-setup/minikube/index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes

#2112 Fix single word in command
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
Labels: cla: yes

#2113 add initial galley intro to "what is istio" concept page
  content/docs/concepts/what-is-istio/index.md
Labels: cla: yes

#2115 Clarify and correct distributed tracing task
  content/docs/tasks/telemetry/distributed-tracing/index.md
Labels: approved, cla: yes

#2117 make cmd/result match
  content/docs/tasks/security/authn-policy/index.md
Labels: cla: yes

#2119 Add Rigs to the English content owners file.
  content/OWNERS
Labels: approved, cla: yes

#2114 Add Istio security vulnerabilities disclosure and handling page
  content/about/security-vulnerabilities/index.md
  content/help/bugs/index.md
Labels: cla: yes

#2120 Fix an error in faq page
  content/help/faq/security/cert-lifetime-config.md
Labels: cla: yes

#2123 More work to fix use of the site in a subdirectory.
  config.toml
  layouts/_default/baseof.html
  layouts/feed/single.rss.xml
  layouts/partials/header.html
Labels: approved, cla: yes

#2124 More work to fix use of the site in a subdirectory. (#2123)
  config.toml
  layouts/_default/baseof.html
  layouts/feed/single.rss.xml
  layouts/partials/header.html
Labels: approved, cla: yes

#2101 Translate attribute-vocabulary
  content_zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2109 fix the virtual-services fault injection error in the YAML
  content_zh/docs/concepts/traffic-management/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2062 Add an item to check whether mTLS is enabled for a service
  content/help/faq/security/check-policy.md
Labels: cla: yes

#2126 Chinese content was aliasing English content.
  content_zh/about/community/index.md
  content_zh/about/contribute/_index.md
  content_zh/about/contribute/github/index.md
  content_zh/about/contribute/style-guide/index.md
  content_zh/about/feature-stages/index.md
  content_zh/about/notes/0.1/index.md
  content_zh/about/notes/0.2/index.md
  content_zh/about/notes/0.3/index.md
  content_zh/about/notes/0.4/index.md
  content_zh/about/notes/_index.md
  content_zh/blog/2017/0.1-canary/index.md
  content_zh/blog/2017/adapter-model/index.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/blog/_index.md
  content_zh/docs/concepts/performance-and-scalability/index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/examples/_index.md
  content_zh/docs/examples/bookinfo/index.md
  content_zh/docs/examples/endpoints/index.md
  content_zh/docs/examples/integrating-vms/index.md
  content_zh/docs/examples/intelligent-routing/index.md
  content_zh/docs/examples/telemetry/index.md
  content_zh/docs/reference/config/policy-and-telemetry/_index.md
  content_zh/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content_zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content_zh/docs/reference/config/policy-and-telemetry/templates/_index.md
  content_zh/docs/setup/kubernetes/helm-install/index.md
  content_zh/docs/setup/kubernetes/sidecar-injection/index.md
  content_zh/docs/tasks/policy-enforcement/denial-and-list/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/tasks/security/authn-policy/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/index.md
  content_zh/docs/tasks/telemetry/metrics-logs/index.md
  content_zh/docs/tasks/traffic-management/fault-injection/index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
  content_zh/docs/tasks/traffic-management/request-routing/index.md
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
  content_zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: approved, cla: yes

#2128 Cherry-pick latest changes from master
  content/about/contribute/style-guide/index.md
  content/help/faq/security/check-policy.md
  content_zh/about/community/index.md
  content_zh/about/contribute/_index.md
  content_zh/about/contribute/github/index.md
  content_zh/about/contribute/style-guide/index.md
  content_zh/about/feature-stages/index.md
  content_zh/about/notes/0.1/index.md
  content_zh/about/notes/0.2/index.md
  content_zh/about/notes/0.3/index.md
  content_zh/about/notes/0.4/index.md
  content_zh/about/notes/_index.md
  content_zh/blog/2017/0.1-canary/index.md
  content_zh/blog/2017/adapter-model/index.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/blog/_index.md
  content_zh/docs/concepts/performance-and-scalability/index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/examples/_index.md
  content_zh/docs/examples/bookinfo/index.md
  content_zh/docs/examples/endpoints/index.md
  content_zh/docs/examples/integrating-vms/index.md
  content_zh/docs/examples/intelligent-routing/index.md
  content_zh/docs/examples/telemetry/index.md
  content_zh/docs/reference/config/policy-and-telemetry/_index.md
  content_zh/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content_zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content_zh/docs/reference/config/policy-and-telemetry/templates/_index.md
  content_zh/docs/setup/kubernetes/helm-install/index.md
  content_zh/docs/setup/kubernetes/sidecar-injection/index.md
  content_zh/docs/tasks/policy-enforcement/denial-and-list/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/tasks/security/authn-policy/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/index.md
  content_zh/docs/tasks/telemetry/metrics-logs/index.md
  content_zh/docs/tasks/traffic-management/fault-injection/index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
  content_zh/docs/tasks/traffic-management/request-routing/index.md
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
  content_zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: approved, cla: no

#2129 Translate into Chinese: docs/examples/multicluster/icp/index.md
  content_zh/docs/examples/multicluster/icp/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2078 Initial checkin of the setup ops guide.
  .spelling
  content/help/ops/setup/_index.md
  content/help/ops/setup/injection/index.md
  content/help/ops/setup/validation/index.md
  content/help/ops/setup/webhook/index.md
Labels: cla: yes

#2132 Add an icon for the reporting security vulnerabilities page
  content/about/security-vulnerabilities/index.md
  static/img/vulnerabilities.svg
Labels: cla: yes

#2087 Fix security concept figure captions etc.
  content/docs/concepts/security/index.md
Labels: cla: yes

#2130 Translate into Chinese: blog/2018/aws-nlb/index.md
  content_zh/blog/2018/aws-nlb/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2138 Cherry pick latest changes from master
  content/about/security-vulnerabilities/index.md
  content/docs/concepts/security/index.md
  content_zh/about/community/index.md
  content_zh/about/contribute/github/index.md
  content_zh/about/contribute/style-guide/index.md
  content_zh/about/contribute/terms/index.md
  content_zh/blog/2017/0.1-canary/index.md
  content_zh/blog/2017/adapter-model/index.md
  content_zh/blog/2018/aws-nlb/index.md
  content_zh/blog/2018/egress-https/index.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/blog/2018/soft-multitenancy/index.md
  content_zh/blog/2018/traffic-mirroring/index.md
  content_zh/blog/2018/v1alpha3-routing/index.md
  content_zh/docs/concepts/performance-and-scalability/index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/examples/integrating-vms/index.md
  content_zh/docs/examples/intelligent-routing/index.md
  content_zh/docs/examples/multicluster/gke/index.md
  content_zh/docs/examples/multicluster/icp/index.md
  content_zh/docs/examples/telemetry/index.md
  content_zh/docs/setup/kubernetes/mesh-expansion/index.md
  content_zh/docs/setup/kubernetes/multicluster-install/index.md
  content_zh/docs/setup/kubernetes/sidecar-injection/index.md
  content_zh/docs/setup/kubernetes/upgrading-istio/index.md
  content_zh/docs/tasks/policy-enforcement/denial-and-list/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/tasks/security/authn-policy/index.md
  content_zh/docs/tasks/security/health-check/index.md
  content_zh/docs/tasks/security/https-overlay/index.md
  content_zh/docs/tasks/security/mtls-migration/index.md
  content_zh/docs/tasks/security/mutual-tls/index.md
  content_zh/docs/tasks/security/plugin-ca-cert/index.md
  content_zh/docs/tasks/security/role-based-access-control/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/index.md
  content_zh/docs/tasks/telemetry/fluentd/index.md
  content_zh/docs/tasks/telemetry/metrics-logs/index.md
  content_zh/docs/tasks/telemetry/querying-metrics/index.md
  content_zh/docs/tasks/telemetry/servicegraph/index.md
  content_zh/docs/tasks/telemetry/tcp-metrics/index.md
  content_zh/docs/tasks/telemetry/using-istio-dashboard/index.md
  content_zh/docs/tasks/traffic-management/app-health-check/index.md
  content_zh/docs/tasks/traffic-management/circuit-breaking/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/fault-injection/index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
  content_zh/docs/tasks/traffic-management/mirroring/index.md
  content_zh/docs/tasks/traffic-management/request-routing/index.md
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
  content_zh/docs/tasks/traffic-management/secure-ingress/index.md
  content_zh/docs/tasks/traffic-management/traffic-shifting/index.md
  content_zh/help/ops/traffic-management/debugging-pilot-envoy/index.md
  static/img/vulnerabilities.svg
Labels: approved, cla: no

#2139 Initial checkin of the setup ops guide. (#2078)
  .spelling
  content/help/ops/setup/_index.md
  content/help/ops/setup/injection/index.md
  content/help/ops/setup/validation/index.md
  content/help/ops/setup/webhook/index.md
Labels: approved, cla: yes

#2131 Document DestinationRule mTLS conflict
  content/help/ops/traffic-management/deploy-guidelines/index.md
Labels: approved, cla: yes, lgtm

#2140 Add twitch livestream blog post
  content/blog/2018/istio-twitch-stream/index.md
Labels: approved, cla: yes

#2144 Fix broken Mixer Adapter Dev Guide links
  content/about/notes/0.2/index.md
  content/blog/2017/0.2-announcement/index.md
  content/blog/2017/adapter-model/index.md
  content/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content_zh/about/notes/0.2/index.md
  content_zh/blog/2017/adapter-model/index.md
  content_zh/docs/reference/config/policy-and-telemetry/adapters/_index.md
Labels: cla: yes, needs-ok-to-test

#2145 Fix some more stale wiki links.
  content/about/feature-stages/index.md
  content/about/notes/1.0/index.md
  content/help/faq/mixer/writing-custom-adapters.md
Labels: approved, cla: yes

#2146 translate tasks/traffic-management/egress-gateway to Chinese
  content_zh/docs/tasks/traffic-management/egress-gateway/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2148 Improve linting
  .circleci/config.yml
  content/about/contribute/writing-a-new-topic/index.md
  content/blog/2017/0.1-announcement/index.md
  content/blog/2017/0.1-auth/index.md
  content/blog/2017/0.1-canary/index.md
  content/blog/2017/0.1-using-network-policy/index.md
  content/blog/2017/0.2-announcement/index.md
  content/blog/2017/_index.md
  content/blog/2017/adapter-model/index.md
  content/blog/2017/mixer-spof-myth/index.md
  content/blog/2018/_index.md
  content/blog/2018/aws-nlb/index.md
  content/blog/2018/delayering-istio/delayering-istio.md
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-tcp/index.md
  content/blog/2018/istio-twitch-stream/index.md
  content/blog/2018/soft-multitenancy/index.md
  content/blog/2018/traffic-mirroring/index.md
  content/docs/concepts/_index.md
  content/docs/concepts/security/index.md
  content/docs/examples/advanced-egress/egress-gateway/index.md
  content/docs/examples/advanced-egress/egress-tls-origination/index.md
  content/docs/reference/_index.md
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/tasks/_index.md
  content/docs/tasks/security/role-based-access-control/index.md
  content/docs/tasks/telemetry/distributed-tracing/index.md
  content/docs/tasks/telemetry/fluentd/index.md
  content/docs/tasks/traffic-management/fault-injection/index.md
  content/help/bugs/index.md
  content/help/faq/general/index.md
  content/help/faq/mixer/index.md
  content/help/faq/security/index.md
  content/help/faq/setup/index.md
  content/help/faq/telemetry/index.md
  content/help/faq/traffic-management/index.md
  content/help/ops/traffic-management/deploy-guidelines/index.md
  content/help/ops/traffic-management/observing/index.md
  content/help/ops/traffic-management/troubleshooting/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/tasks/traffic-management/egress-gateway/index.md
  layouts/_default/baseof.html
  layouts/shortcodes/image.html
  layouts/shortcodes/text.html
  scripts/gen_site.sh
  scripts/lint_site.sh
Labels: approved, cla: yes

#2150 Translate into Chinese: blog/2017/0.2-announcement/index.md
  content_zh/blog/2017/0.2-announcement/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2153 Translate into Chinese: content/blog/2018/aws-nlb/index.md Sync/Update
  content_zh/blog/2018/aws-nlb/index.md
  content_zh/docs/tasks/_index.md
Labels: approved, cla: yes, lgtm

#2151 re translate /zh/blog/2018/egress-tcp/ page
  content_zh/blog/2018/egress-tcp/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2161 Merge changes from the release-1.0 branch
  content/about/feature-stages/index.md
  content/blog/2018/announcing-1.0/index.md
  content/blog/2018/hp/index.md
  content/docs/setup/kubernetes/multicluster-install/index.md
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
  content/docs/tasks/security/authn-policy/index.md
  content/docs/tasks/telemetry/distributed-tracing/index.md
  content/help/ops/traffic-management/deploy-guidelines/index.md
Labels: approved, cla: no

#2142 Refresh the glossary and attribute vocabulary based on current reality.
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/help/glossary/adapters.md
  content/help/glossary/attribute.md
  content/help/glossary/secure-naming.md
  content/help/glossary/service-endpoint.md
  content/help/glossary/service-mesh.md
  content/help/glossary/workload-id.md
  content/help/glossary/workload-instance-principal.md
  content/help/glossary/workload-instance.md
  content/help/glossary/workload-name.md
  content/help/glossary/workload-principal.md
  content/help/glossary/workload.md
  src/sass/base/_common.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: approved, cla: yes

#2162 Refresh the glossary and attribute vocabulary based on current reality
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/help/glossary/adapters.md
  content/help/glossary/attribute.md
  content/help/glossary/secure-naming.md
  content/help/glossary/service-endpoint.md
  content/help/glossary/service-mesh.md
  content/help/glossary/workload-id.md
  content/help/glossary/workload-instance-principal.md
  content/help/glossary/workload-instance.md
  content/help/glossary/workload-name.md
  content/help/glossary/workload-principal.md
  content/help/glossary/workload.md
  src/sass/base/_common.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: approved, cla: yes

#2163 translate /help/glossary/ page
  content_zh/help/glossary/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2165 Translate to chinese: content/help/faq/_index.md #189
  content_zh/help/faq/_index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2167 Translate help/ops/traffic-management/index.md into Chinese
  content_zh/help/ops/traffic-management/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2164 translate /help/glossary/#attribute
  content_zh/help/glossary/attributes.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2170 Translate 0.1-Auth into Chinese
  content_zh/blog/2017/0.1-auth/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2157 Translate installation options
  content_zh/docs/reference/config/installation-options/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2171 translate /help/glossary/#adapter
  content_zh/help/glossary/adapter.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2174 Fix up some aliases.
  content/about/contribute/writing-a-new-topic/index.md
  content/docs/concepts/policies-and-telemetry/index.md
  content/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/help/ops/_index.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/help/faq/_index.md
  content_zh/help/glossary/index.md
Labels: approved, cla: yes

#2176 Sidecar upgrade needs kubectl apply not replace
  content/docs/setup/kubernetes/upgrading-istio/index.md
Labels: approved, cla: yes, lgtm

#2179 fix 0.1 auth lint issues
  content_zh/blog/2017/0.1-auth/index.md
Labels: approved, cla: yes, lgtm

#2183 translate /help/glossary/#micro-segmentation
  content_zh/help/glossary/micro-segmentation.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2125 add alicloud
  .spelling
  content/docs/setup/kubernetes/platform-setup/alicloud/csconsole.png
  content/docs/setup/kubernetes/platform-setup/alicloud/index.md
  content/docs/setup/kubernetes/quick-start-alicloud-ack/app-catalog-istio-1.0.0.png
  content/docs/setup/kubernetes/quick-start-alicloud-ack/index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes

#2187 Translate into Chinese: Multiple files Sync & update
  content_zh/docs/setup/kubernetes/platform-setup/aws/index.md
  content_zh/docs/setup/kubernetes/platform-setup/gke/index.md
  content_zh/docs/setup/kubernetes/platform-setup/minikube/index.md
  content_zh/docs/setup/kubernetes/quick-start-gke-dm/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2178 translate /help/glossary/#mutual-tls
  content_zh/help/glossary/mutual-tls.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2188 translate content/help/ops/security/_index.md
  content_zh/help/ops/security/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2184 Translate help/ops/traffic-management into Chinese
  content_zh/help/ops/traffic-management/_index.md
  content_zh/help/ops/traffic-management/deploy-guidelines/index.md
  content_zh/help/ops/traffic-management/introduction/index.md
  content_zh/help/ops/traffic-management/observing/index.md
  content_zh/help/ops/traffic-management/proxy-cmd/index.md
  content_zh/help/ops/traffic-management/troubleshooting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2191 Revise the health check faq
  content/help/faq/security/k8s-health-checks.md
Labels: approved, cla: yes, lgtm

#2190 update spec-requirements doc page
  content/docs/setup/kubernetes/spec-requirements/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2172 translate /help/glossary/#workload
  content_zh/help/glossary/workload.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2189 Translate into Chinese: Add Terms
  content_zh/about/contribute/terms/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2192 fix typo
  content/blog/2018/v1alpha3-routing/index.md
Labels: cla: yes

#2177 Sidecar upgrade needs kubectl apply not replace
  content/docs/setup/kubernetes/upgrading-istio/index.md
Labels: cla: yes, lgtm

#2169 add IKS-ICP hybrid multicluster example
  .spelling
  content/docs/examples/multicluster/iks-icp/index.md
Labels: cla: yes

#2195 Couple FAQ fixes
  .spelling
  content/help/faq/general/how-do-i-contribute.md
  content/help/faq/general/what-deployment-environment.md
Labels: cla: yes

#2182 Translate reference istioctl
  content_zh/docs/reference/commands/istioctl/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2194 translate /help/glossary/#mixer-instance /help/glossary/#mixer-handler
  content_zh/help/glossary/mixer-handler.md
  content_zh/help/glossary/mixer-instance.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2197 Trans help glossary mixer and more
  content_zh/help/glossary/envoy.md
  content_zh/help/glossary/mixer.md
  content_zh/help/glossary/service-endpoint.md
  content_zh/help/glossary/service-mesh.md
  content_zh/help/glossary/service-name.md
  content_zh/help/glossary/service-version.md
  content_zh/help/glossary/service.md
  content_zh/help/glossary/workload-instance-principal.md
  content_zh/help/glossary/workload-instance.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2200 fix typesetting error
  content_zh/docs/tasks/traffic-management/ingress/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2198 Remove misplaced "the"
  content/docs/concepts/traffic-management/index.md
Labels: cla: yes

#2206 Work around Hugo bug with GitHub last modification times.
  layouts/partials/footer.html
Labels: cla: yes

#2207 Move the Reporting Bugs page next to Reporting Security Vulnerabilites, under About
  content/about/bugs/index.md
  content/about/security-vulnerabilities/index.md
  content/help/faq/general/istio-doesnt-work.md
  content/help/ops/security/debugging-authorization/index.md
Labels: cla: yes

#2208 Fix scroll offset when linking to a FAQ entry
  src/sass/layouts/_faq.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: cla: yes

#2209 remove the word 'global' as it adds confusion
  content/docs/concepts/traffic-management/index.md
Labels: cla: yes

#2212 Translate:faq/security/use-k8s-secrets
  content_zh/help/faq/security/use-k8s-secrets.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2213 Translate:ops/telemetry/_index
  content_zh/help/ops/telemetry/_index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2202 Translate into Chinese: Multiple files Sync/update
  content_zh/docs/setup/kubernetes/_index.md
  content_zh/docs/setup/kubernetes/ansible-install/index.md
  content_zh/docs/setup/kubernetes/download-release/index.md
  content_zh/docs/setup/kubernetes/platform-setup/_index.md
  content_zh/docs/tasks/security/role-based-access-control/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2211 Translate: help/ops/misc
  content_zh/help/ops/misc/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2214 Translate:ops/telemetry/grafana
  content_zh/help/ops/telemetry/grafana/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2216 Translate:faq/general/how-was-istio-started
  content_zh/help/faq/general/how-was-istio-started.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2217 Translate:faq/general/license
  content_zh/help/faq/general/what-is-the-license.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2222 Translate:faq/general/doesnt-work
  content_zh/help/faq/general/istio-doesnt-work.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2223 Translate:faq/general/doc
  content_zh/help/faq/general/where-is-the-documentation.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2215 Translate:/faq/general
  content_zh/help/faq/general/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2103 Full text RSS feeds
  layouts/feed/single.rss.xml
Labels: cla: yes

#2224 Translate: Add zh-CN version of controlz index page: /help/ops/controlz/index
  content_zh/help/ops/controlz/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2225 remove redundant slash
  content/docs/tasks/security/role-based-access-control/index.md
Labels: cla: yes

#2229 CSS fixes
  src/sass/base/_common.scss
  src/sass/layouts/_faq.scss
  src/sass/modules/_header.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: cla: yes

#2228 translate: reference galley, fixed outline in istioctl reference
  content_zh/docs/reference/commands/galley/index.md
  content_zh/docs/reference/commands/istioctl/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2230 Update page authoring guide.
  content/about/contribute/writing-a-new-topic/index.md
Labels: cla: yes

#2201 fixed typo
  content_zh/about/notes/0.1/index.md
  content_zh/blog/2017/0.1-auth/index.md
  content_zh/blog/2017/0.2-announcement/index.md
  content_zh/blog/2018/egress-https/index.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/tasks/telemetry/querying-metrics/index.md
  content_zh/docs/tasks/telemetry/servicegraph/index.md
  content_zh/docs/tasks/telemetry/using-istio-dashboard/index.md
  content_zh/docs/tasks/traffic-management/egress-gateway/index.md
  content_zh/docs/tasks/traffic-management/egress-tls-origination/index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2210 translate /help/glossary/#pilot #destination #mutual-tls #secure-nami…
  content_zh/help/glossary/destination.md
  content_zh/help/glossary/mutual-tls.md
  content_zh/help/glossary/pilot.md
  content_zh/help/glossary/secure-naming.md
  content_zh/help/glossary/service-consumer.md
  content_zh/help/glossary/service-operator.md
  content_zh/help/glossary/service-producer.md
  content_zh/help/glossary/service-registry.md
  content_zh/help/glossary/source.md
  content_zh/help/glossary/tls-origination.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2219 Translate:faq/general/what-is-istio
  content_zh/help/faq/general/what-is-istio.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2233 Chinese: add ops index
  content_zh/help/ops/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2221 Translate: faq/general/partners-and-vendors
  content_zh/help/faq/general/istio-partners-and-vendors.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2235 Translation: fix translation for faq/general/partners
  content_zh/help/faq/general/istio-partners-and-vendors.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2218 Translate:faq/general/deploy-environ
  content_zh/help/faq/general/what-deployment-environment.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2237 Translate:faq/roadmap
  content_zh/help/faq/general/roadmap.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2231 translate report bug
  content_zh/about/bugs/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2181 Added host header to curl command
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: cla: yes

#2236 Translate: faq/general/contribute
  content_zh/help/faq/general/how-do-i-contribute.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2241 translated authorization-permissive
  content_zh/help/ops/security/authorization-permissive/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2240 translate debug authorization
  content_zh/help/ops/security/debugging-authorization/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2244 translation:/content/docs/concepts/index.md #154
  content_zh/docs/concepts/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2234 Trans help/ops/setup into Chinese
  content_zh/help/ops/setup/_index.md
  content_zh/help/ops/setup/injection/index.md
  content_zh/help/ops/setup/validation/index.md
  content_zh/help/ops/setup/webhook/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2251 Translate into Chinese: /help/faq/telemetry/prometheus-for-non-k8s.md
  content_zh/docs/setup/kubernetes/platform-setup/azure/index.md
  content_zh/help/faq/telemetry/prometheus-for-non-k8s.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2249 translated content_zh/help/ops/security/authorization-restrictive/ind…
  content_zh/help/ops/security/authorization-restrictive/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2246 Translate:faq/why-use-istio
  content_zh/help/faq/general/why-use-istio.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2247 Translate:faq/how-do-i-get-started
  content_zh/help/faq/general/how-do-i-get-started.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2248 Translate help/ops/component-logging into Chinese
  content_zh/help/ops/component-logging/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2257 Remove recovation from security concept doc
  content/docs/concepts/security/index.md
Labels: approved, cla: yes, lgtm

#2242 fixed: outdated reference to the field `httpReqTimeout`
  content/docs/tasks/traffic-management/request-timeouts/index.md
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
Labels: approved, cla: yes, lgtm

#2259 Add a missing link.
  content/docs/setup/kubernetes/upgrading-istio/index.md
Labels: cla: yes

#2263 Fix extra brace
  content/docs/setup/kubernetes/multicluster-install/index.md
Labels: cla: no, needs-ok-to-test

#2255 Translate help/ops/component-debugging into Chinese
  content_zh/help/ops/component-debugging/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2267 Translate help/faq/traffic-management into Chinese
  content_zh/help/faq/traffic-management/index.md
  content_zh/help/faq/traffic-management/ingress-with-no-route-rules.md
  content_zh/help/faq/traffic-management/naming-port-convention.md
  content_zh/help/faq/traffic-management/viewing-current-rules.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2269 Translate help/faq/telemery into Chinese
  content_zh/help/faq/telemetry/accessing-telemetry-via-rest.md
  content_zh/help/faq/telemetry/disabling-zipkin.md
  content_zh/help/faq/telemetry/external-zipkin.md
  content_zh/help/faq/telemetry/index.md
  content_zh/help/faq/telemetry/initial-zipkin-header.md
  content_zh/help/faq/telemetry/prometheus-for-non-k8s.md
  content_zh/help/faq/telemetry/vert.x.md
  content_zh/help/faq/telemetry/zipkin-and-x-request-id.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2265 translate /help/ops/missing-metrics
  content_zh/help/ops/telemetry/missing-metrics/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2238 Extend the secure ingress task with multiple ingress certificates/hosts
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: cla: yes

#2226 add 'location: MESH_EXTERNAL' to the service entries
  content/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes

#2261 Add DestinationRule to example
  content/blog/2017/0.1-canary/index.md
Labels: cla: yes

#2253 fix sample RbacConfig in concept page.
  content/docs/concepts/security/index.md
Labels: cla: yes

#2196 Highlight "Istio multicluster" in example document.
  content/docs/examples/multicluster/gke/index.md
  content/docs/examples/multicluster/icp/index.md
  content/docs/examples/multicluster/iks-icp/index.md
Labels: cla: yes

#2270 fix mistranslate of /zh/docs/setup/kubernetes/helm-install
  content_zh/docs/setup/kubernetes/helm-install/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2272 Translate into Chinese: help/faq/security/https-overlay.md
  content_zh/help/faq/security/https-overlay.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2276 Translate into Chinese: help/faq/security/check-policy.md
  content_zh/help/faq/security/check-policy.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2274 adding schedule to istio twich live stream page
  content/blog/2018/istio-twitch-stream/index.md
Labels: approved, cla: yes, lgtm

#2279 Spell Lisa's name correctly
  content/blog/2018/istio-twitch-stream/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2286 Update reference docs.
  content/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/docs/reference/config/policy-and-telemetry/templates/analytics/index.html
Labels: cla: yes

#2288 Switch to Hugo 0.47
  .circleci/config.yml
  Makefile
  content/_index.md
  content/docs/concepts/security/index.md
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/concepts/security/index.md
  netlify.toml
  scripts/Dockerfile
  scripts/gen_site.sh
Labels: cla: yes

#2283 suggest a more recent gke minor version
  content/docs/setup/kubernetes/platform-setup/gke/index.md
Labels: cla: yes

#2282 translate update setup requirement
  content_zh/docs/setup/kubernetes/spec-requirements/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2292 Delete special chars and turn on HTML checking
  content/docs/examples/multicluster/iks-icp/index.md
  content_zh/docs/examples/multicluster/icp/index.md
  scripts/lint_site.sh
Labels: cla: yes

#2305 remove extra space before dot
  content/docs/setup/kubernetes/download-release/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#2294 TLS ingress gateway for HTTPS
  content/docs/examples/ingress-for-https/index.md
Labels: approved, cla: yes, lgtm

#2307 Use apply rather than create for rolling upgrades
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/setup/kubernetes/multicluster-install/index.md
Labels: cla: yes

#2301 Update grab_reference_docs.sh to add Alibaba Cloud Adapter documentation
  scripts/grab_reference_docs.sh
Labels: cla: yes, needs-ok-to-test

#2311 translate /help/faq/security/#accessing-non-istio-services
  content_zh/help/faq/security/accessing-non-istio-services.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2303 translate:faq-auth-mix-and-match
  content_zh/help/faq/security/auth-mix-and-match.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2313 translate /help/faq/security/#non-istio-to-istio
  content_zh/help/faq/security/non-istio-to-istio.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2299 translate: faq-secret-encryption
  content_zh/help/faq/security/secret-encryption.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2298 translate: faq-security-secure-ingress
  content_zh/help/faq/security/secure-ingress.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2297 translate: faq-security-does-istio-support-authorization
  content_zh/help/faq/security/does-istio-support-authorization.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2296 translate: faq-security-enabling-disabling-mtls
  content_zh/help/faq/security/enabling-disabling-mtls.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2295 translate: faq-security-index
  content_zh/help/faq/security/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2315 Chineses: update Docs concepts security
  content_zh/docs/concepts/security/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2256 Translate:reference traffic control
  content_zh/docs/reference/config/istio.networking.v1alpha3/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2293 Translation:k8s health checks
  content_zh/help/faq/security/k8s-health-checks.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2317 Get the ServiceMesher community logo back
  layouts/partials/community/servicemesher.svg
Labels: cla: yes
