Repository istio/istio.io, pull requests merged in 2018-05, with the labels that each got.

#1226 Fix naming collision
  _help/troubleshooting.md
Labels: cla: yes

#1218 adding the recommended namespace
  _docs/setup/kubernetes/helm-install.md
Labels: approved, cla: yes, lgtm

#1224 Introduce support for new fangled PRE blocks.
  _config.yml
  _docs/setup/kubernetes/sidecar-injection.md
  _sass/base/_common.scss
  _sass/themes/_dark.scss
  _sass/themes/_light.scss
  js/misc.js
  js/misc.min.js
  mdl_style.rb
Labels: cla: yes

#1223 0.8 release notes.
  .spelling
  _about/notes/0.8.md
Labels: cla: yes

#1229 Fix incorrect behavior of the sidenav when dealing with long non-wrapping page titles
  _sass/modules/_sidebar.scss
Labels: cla: yes

#1217 Improves multicluster documentation
  _docs/setup/kubernetes/multicluster-install.md
  mdl_style.rb
Labels: approved, cla: yes, lgtm

#1227 Improve the doc to apply istio-auth.yaml
  _docs/setup/kubernetes/quick-start.md
Labels: cla: yes

#1228 Fix doc
  _docs/tasks/security/per-service-mtls.md
Labels: cla: yes

#1231 Task/guide updates for v1alpha3
  _docs/guides/bookinfo.md
  _docs/tasks/traffic-management-v1alpha3/egress-tcp.md
  _docs/tasks/traffic-management-v1alpha3/egress.md
  _docs/tasks/traffic-management-v1alpha3/ingress.md
Labels: cla: yes

#1240 Hopefully finally really fix the issues with the sidenav on small screens.
  _sass/modules/_sidebar.scss
Labels: cla: yes

#1211 fix manual sidecar injection docs for helm template changes
  _docs/setup/kubernetes/sidecar-injection.md
Labels: cla: yes

#1244 Sidecar-injector doc review fixes
  README.md
  _docs/setup/kubernetes/sidecar-injection.md
Labels: approved, cla: yes

#1237 update format of a tcp ServiceEntry
  _docs/tasks/traffic-management-v1alpha3/egress-tcp.md
Labels: approved, cla: yes

#1250 Remove broken link.
  _docs/setup/consul/install.md
Labels: cla: yes

#1247 WIP PR for v1alpha3 task corrections
  _docs/tasks/traffic-management-v1alpha3/fault-injection.md
  _docs/tasks/traffic-management-v1alpha3/ingress.md
Labels: cla: yes

#1254 update samples to align with latest destination rule proto definition
  _docs/tasks/traffic-management-v1alpha3/mirroring.md
Labels: cla: yes, lgtm

#1259 Traffic Shifting Review - Fixed wrong links
  _docs/tasks/traffic-management-v1alpha3/traffic-shifting.md
  _docs/tasks/traffic-management/traffic-shifting.md
Labels: cla: yes

#1243 Create istio namespace before install remote cluster.
  _docs/setup/kubernetes/multicluster-install.md
Labels: approved, cla: yes

#1260 update instructions for gke-iam
  _docs/setup/kubernetes/img/dm_gcp_iam.png
  _docs/setup/kubernetes/img/dm_gcp_iam_role.png
  _docs/setup/kubernetes/quick-start-gke-dm.md
Labels: cla: yes, needs-ok-to-test

#1263 Remove a broken link.
  _faq/mixer/seeing-mixer-config.md
Labels: cla: yes

#1265 Try to unwedge CircleCi
  .spelling
  _docs/setup/eureka/install.md
Labels: cla: yes

#1258 Create a namespace before installing the helm generated istio.yaml
  _docs/setup/kubernetes/sidecar-injection.md
Labels: cla: yes

#1234 Added namespace when create helm template.
  _docs/setup/kubernetes/multicluster-install.md
Labels: approved, cla: yes

#1267 Add istioctl proxy-config to the troubleshooting section
  _help/troubleshooting.md
Labels: approved, cla: yes, lgtm

#1269 Fix istioctl proxy-config link to not point at prelim docs
  _help/troubleshooting.md
Labels: approved, cla: yes, lgtm

#1275 Update how we insert images to make a transition from Jekyll to Hugo easier
  .spelling
  _about/contribute/writing-a-new-topic.md
  _blog/2017/0.1-announcement.md
  _blog/2017/0.1-auth.md
  _blog/2017/0.1-using-network-policy.md
  _blog/2017/adapter-model.md
  _blog/2017/mixer-spof-myth.md
  _blog/2018/aws-nlb.md
  _blog/2018/egress-https.md
  _blog/2018/egress-tcp.md
  _blog/2018/v1alpha3-routing.md
  _docs/concepts/policy-and-control/mixer-config.md
  _docs/concepts/policy-and-control/mixer.md
  _docs/concepts/security/authn-policy.md
  _docs/concepts/security/mutual-tls.md
  _docs/concepts/security/rbac.md
  _docs/concepts/traffic-management/load-balancing.md
  _docs/concepts/traffic-management/overview.md
  _docs/concepts/traffic-management/pilot.md
  _docs/concepts/traffic-management/request-routing.md
  _docs/concepts/what-is-istio/overview.md
  _docs/guides/bookinfo.md
  _docs/guides/integrating-vms.md
  _docs/setup/kubernetes/quick-start-gke-dm.md
  _docs/tasks/telemetry/distributed-tracing.md
  _docs/tasks/telemetry/querying-metrics.md
  _docs/tasks/telemetry/servicegraph.md
  _docs/tasks/telemetry/tcp-metrics.md
  _docs/tasks/telemetry/using-istio-dashboard.md
  _includes/figure.html
  _includes/image.html
Labels: cla: yes

#1276 Change publish_date front-matter to publishdate to aid in the Jekyll to Hugo migration.
  _about/contribute/writing-a-new-topic.md
  _blog/2017/0.1-announcement.md
  _blog/2017/0.1-auth.md
  _blog/2017/0.1-canary.md
  _blog/2017/0.1-using-network-policy.md
  _blog/2017/0.2-announcement.md
  _blog/2017/adapter-model.md
  _blog/2017/mixer-spof-myth.md
  _blog/2018/aws-nlb.md
  _blog/2018/egress-https.md
  _blog/2018/egress-tcp.md
  _blog/2018/soft-multitenancy.md
  _blog/2018/traffic-mirroring.md
  _blog/2018/v1alpha3-routing.md
  _includes/primary.html
  feed.xml
Labels: cla: yes

#1278 Shorten long titles and descriptions.
  _docs/tasks/security/authn-policy.md
  _docs/tasks/security/basic-access-control.md
  _docs/tasks/security/health-check.md
  _docs/tasks/security/https-overlay.md
  _docs/tasks/security/mutual-tls.md
  _docs/tasks/security/per-service-mtls.md
  _docs/tasks/security/plugin-ca-cert.md
  _docs/tasks/security/role-based-access-control.md
  _docs/tasks/security/secure-access-control.md
Labels: approved, cla: yes, lgtm

#1277 Fix aspect ratio of a couple images.
  _blog/2018/img/gateways.png
  _blog/2018/img/gateways.svg
  _blog/2018/img/virtualservices-destrules.png
  _blog/2018/v1alpha3-routing.md
Labels: cla: yes

#1280 Add missing feature links
  _about/feature-stages.md
Labels: approved, cla: yes, lgtm

#1284 Update multi-paragraph list layout to facilitate migration from Jekyll to Hugo
  _about/contribute/writing-a-new-topic.md
  _docs/concepts/security/mutual-tls.md
  _docs/guides/integrating-vms.md
  _docs/setup/kubernetes/mesh-expansion.md
  _docs/setup/kubernetes/multicluster-install.md
  _docs/setup/kubernetes/quick-start-gke-dm.md
  _docs/setup/kubernetes/quick-start.md
  _docs/tasks/policy-enforcement/rate-limiting.md
  _docs/tasks/security/authn-policy.md
  _docs/tasks/security/basic-access-control.md
  _docs/tasks/security/health-check.md
  _docs/tasks/security/per-service-mtls.md
  _docs/tasks/security/plugin-ca-cert.md
  _docs/tasks/security/role-based-access-control.md
  _docs/tasks/security/secure-access-control.md
  _docs/tasks/telemetry/distributed-tracing.md
  _docs/tasks/telemetry/fluentd.md
  _docs/tasks/telemetry/metrics-logs.md
  _docs/tasks/telemetry/querying-metrics.md
  _docs/tasks/telemetry/servicegraph.md
  _docs/tasks/telemetry/tcp-metrics.md
  _docs/tasks/telemetry/using-istio-dashboard.md
  _docs/tasks/traffic-management-v1alpha3/circuit-breaking.md
  _docs/tasks/traffic-management/circuit-breaking.md
  _docs/tasks/traffic-management/egress-tcp.md
  _docs/tasks/traffic-management/egress.md
  _docs/tasks/traffic-management/fault-injection.md
  _docs/tasks/traffic-management/ingress.md
  _docs/tasks/traffic-management/mirroring.md
  _docs/tasks/traffic-management/request-routing.md
  _docs/tasks/traffic-management/request-timeouts.md
  _docs/tasks/traffic-management/traffic-shifting.md
  mdl_style.rb
Labels: cla: yes

#1251 "Configuring Request Routing" fixes
  _docs/setup/kubernetes/helm-install.md
  _docs/tasks/traffic-management-v1alpha3/request-routing.md
  _docs/tasks/traffic-management/request-routing.md
Labels: approved, cla: yes, lgtm

#1287 Finish updating the formatting of multi-paragraph lists.
  _about/contribute/style-guide.md
  _blog/2018/egress-tcp.md
  _blog/2018/soft-multitenancy.md
  _blog/2018/v1alpha3-routing.md
  _docs/guides/bookinfo.md
  _docs/guides/endpoints.md
  _docs/setup/consul/quick-start.md
  _docs/setup/eureka/quick-start.md
  _docs/setup/kubernetes/helm-install.md
  _docs/setup/kubernetes/quick-start.md
  _docs/setup/kubernetes/upgrading-istio.md
  _docs/tasks/security/mutual-tls.md
  _docs/tasks/telemetry/fluentd.md
  _docs/tasks/telemetry/metrics-logs.md
  _docs/tasks/telemetry/querying-metrics.md
  _docs/tasks/telemetry/servicegraph.md
  _docs/tasks/traffic-management-v1alpha3/egress-tcp.md
  _docs/tasks/traffic-management-v1alpha3/egress.md
  _docs/tasks/traffic-management-v1alpha3/fault-injection.md
  _docs/tasks/traffic-management-v1alpha3/ingress.md
  _docs/tasks/traffic-management-v1alpha3/mirroring.md
  _docs/tasks/traffic-management-v1alpha3/request-routing.md
  _docs/tasks/traffic-management-v1alpha3/request-timeouts.md
  _docs/tasks/traffic-management-v1alpha3/traffic-shifting.md
  _help/troubleshooting.md
Labels: cla: yes

#1290 Update canary blog to use v1alpha3 rules
  _blog/2017/0.1-canary.md
Labels: approved, cla: yes, lgtm

#1268 Add a release cadence page.
  _about/release-cadence.md
Labels: cla: yes

#1293 Delete
  _docs/setup/kubernetes/quick-start.md
Labels: cla: yes

#1296 Update reference docs.
  _docs/reference/config/policy-and-telemetry/adapters/circonus.html
  _docs/reference/config/policy-and-telemetry/adapters/cloudwatch.html
  _docs/reference/config/policy-and-telemetry/adapters/datadog.html
  _docs/reference/config/policy-and-telemetry/adapters/denier.html
  _docs/reference/config/policy-and-telemetry/adapters/fluentd.html
  _docs/reference/config/policy-and-telemetry/adapters/kubernetesenv.html
  _docs/reference/config/policy-and-telemetry/adapters/list.html
  _docs/reference/config/policy-and-telemetry/adapters/memquota.html
  _docs/reference/config/policy-and-telemetry/adapters/opa.html
  _docs/reference/config/policy-and-telemetry/adapters/rbac.html
  _docs/reference/config/policy-and-telemetry/adapters/redisquota.html
  _docs/reference/config/policy-and-telemetry/adapters/servicecontrol.html
  _docs/reference/config/policy-and-telemetry/adapters/solarwinds.html
  _docs/reference/config/policy-and-telemetry/adapters/stackdriver.html
  _docs/reference/config/policy-and-telemetry/adapters/statsd.html
  _docs/reference/config/policy-and-telemetry/adapters/stdio.html
  _docs/reference/config/policy-and-telemetry/istio.policy.v1beta1.html
  _docs/reference/config/policy-and-telemetry/templates/apikey.html
  _docs/reference/config/policy-and-telemetry/templates/authorization.html
  _docs/reference/config/policy-and-telemetry/templates/checknothing.html
  _docs/reference/config/policy-and-telemetry/templates/kubernetes.html
  _docs/reference/config/policy-and-telemetry/templates/listentry.html
  _docs/reference/config/policy-and-telemetry/templates/logentry.html
  _docs/reference/config/policy-and-telemetry/templates/metric.html
  _docs/reference/config/policy-and-telemetry/templates/quota.html
  _docs/reference/config/policy-and-telemetry/templates/reportnothing.html
  _docs/reference/config/policy-and-telemetry/templates/servicecontrolreport.html
Labels: cla: yes

#1295 Add an idempotent warning around sidecar injection
  .spelling
  _docs/setup/kubernetes/sidecar-injection.md
Labels: approved, cla: yes, lgtm

#1297 Remove old routing api version of tasks
  _about/notes/0.8.md
  _docs/guides/bookinfo.md
  _docs/guides/endpoints.md
  _docs/tasks/traffic-management-v1alpha3/circuit-breaking.md
  _docs/tasks/traffic-management-v1alpha3/egress-tcp.md
  _docs/tasks/traffic-management-v1alpha3/egress.md
  _docs/tasks/traffic-management-v1alpha3/fault-injection.md
  _docs/tasks/traffic-management-v1alpha3/index.md
  _docs/tasks/traffic-management-v1alpha3/ingress.md
  _docs/tasks/traffic-management-v1alpha3/mirroring.md
  _docs/tasks/traffic-management-v1alpha3/request-routing.md
  _docs/tasks/traffic-management-v1alpha3/request-timeouts.md
  _docs/tasks/traffic-management-v1alpha3/traffic-shifting.md
  _docs/tasks/traffic-management/circuit-breaking.md
  _docs/tasks/traffic-management/egress-tcp.md
  _docs/tasks/traffic-management/egress.md
  _docs/tasks/traffic-management/fault-injection.md
  _docs/tasks/traffic-management/index.md
  _docs/tasks/traffic-management/ingress.md
  _docs/tasks/traffic-management/mirroring.md
  _docs/tasks/traffic-management/request-routing.md
  _docs/tasks/traffic-management/request-timeouts.md
  _docs/tasks/traffic-management/traffic-shifting.md
Labels: cla: yes

#1301 fix command in docs so it can be copied
  _docs/setup/kubernetes/quick-start-gke-dm.md
  _docs/setup/kubernetes/quick-start.md
Labels: cla: yes

#1084 additional permission steps in openshift for running applications
  _docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes, lgtm

#1300 Fix the command for getting Citadel pod.
  _docs/tasks/security/mutual-tls.md
Labels: cla: yes

#1304 Update to install pre-requisites
  _docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes

#1307 fix format issue in install options
  _docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes

#1305 ServiceEntry works for more than just HTTP/HTTPS
  _docs/tasks/traffic-management/egress.md
Labels: cla: yes

#1309 update helm instruction
  _docs/setup/kubernetes/helm-install.md
Labels: approved, cla: yes, lgtm

#1285 Updated mc document for secret register.
  _docs/setup/kubernetes/multicluster-install.md
Labels: cla: yes

#1289 Add privacy policy link to the footer.
  _includes/footer.html
Labels: cla: yes

#1286 finalize the ingressgateway instructions
  .spelling
  _docs/guides/endpoints.md
  _docs/tasks/traffic-management/ingress.md
  _faq/security/secure-ingress.md
Labels: cla: yes

#1308 Remove ilb from istio setup.
  _docs/setup/kubernetes/quick-start.md
Labels: cla-manual, cla: no

#1310 Updated IBM related bookinfo test for Bookinfo.
  _docs/guides/bookinfo.md
Labels: cla: yes

#1313 Some cleanup for kubernetes setup.
  _docs/setup/kubernetes/quick-start.md
Labels: cla: yes

#1316 Fix rendering issues on search results page.
  _layouts/search-results.html
Labels: approved, cla: yes

#1318 Add Prometheus as Grafana prerequisite
  _docs/tasks/telemetry/using-istio-dashboard.md
Labels: cla: yes

#1319 Use kubectl jsonpath for `export GATEWAY_URL`
  _docs/guides/bookinfo.md
Labels: cla: yes

#1314 more update to helm instruction
  _docs/setup/kubernetes/helm-install.md
Labels: approved, cla: yes, lgtm

#1323 Update index.md
  _docs/setup/cloudfoundry/index.md
Labels: approved, cla: yes, lgtm

#1322 Update index.md
  _docs/setup/mesos/index.md
Labels: approved, cla: yes, lgtm

#1327 Add a bunch of redirects
  _about/contribute/creating-a-pull-request.md
  _about/contribute/editing.md
  _about/contribute/index.md
  _about/contribute/reviewing-doc-issues.md
  _about/contribute/staging-your-changes.md
  _about/contribute/style-guide.md
  _about/contribute/writing-a-new-topic.md
  _about/feature-stages.md
  _about/notes/0.1.md
  _about/notes/0.2.md
  _about/notes/0.3.md
  _about/notes/0.4.md
  _about/notes/index.md
  _blog/2017/0.1-announcement.md
  _blog/2017/0.1-auth.md
  _blog/2017/0.1-canary.md
  _blog/2017/0.1-using-network-policy.md
  _blog/2017/0.2-announcement.md
  _blog/2017/adapter-model.md
  _blog/2017/mixer-spof-myth.md
  _blog/2018/aws-nlb.md
  _blog/2018/egress-https.md
  _blog/2018/egress-tcp.md
  _blog/2018/soft-multitenancy.md
  _blog/2018/traffic-mirroring.md
  _blog/2018/v1alpha3-routing.md
  _docs/concepts/security/authn-policy.md
  _docs/concepts/traffic-management/pilot.md
  _docs/guides/bookinfo.md
  _docs/guides/index.md
  _docs/reference/config/policy-and-telemetry/attribute-vocabulary.md
  _docs/reference/config/policy-and-telemetry/expression-language.md
  _docs/reference/config/policy-and-telemetry/index.md
  _docs/setup/kubernetes/helm-install.md
  _docs/setup/kubernetes/index.md
  _docs/setup/kubernetes/sidecar-injection.md
  _docs/tasks/policy-enforcement/rate-limiting.md
  _docs/tasks/security/authn-policy.md
  _docs/tasks/security/basic-access-control.md
  _docs/tasks/security/index.md
  _docs/tasks/telemetry/distributed-tracing.md
  _docs/tasks/telemetry/metrics-logs.md
  _docs/tasks/traffic-management/egress.md
  _docs/tasks/traffic-management/fault-injection.md
  _docs/tasks/traffic-management/ingress.md
  _docs/tasks/traffic-management/mirroring.md
  _docs/tasks/traffic-management/request-timeouts.md
  _docs/tasks/traffic-management/traffic-shifting.md
  _help/bugs.md
  _help/faq/general.html
  _help/faq/index.md
  _help/faq/mixer.html
  _help/faq/security.html
  _help/faq/setup.html
  _help/faq/traffic-management.html
  _help/troubleshooting.md
  _layouts/redirect.html
  community.md
Labels: approved, cla: yes

#1329 Use envoryv2 for bookinfo example.
  _docs/guides/bookinfo.md
Labels: approved, cla: yes, lgtm

#1328 Updated ilb access mode.
  _docs/guides/bookinfo.md
Labels: approved, cla: yes, lgtm

#1288 securityEnabled flag was removed
  _docs/setup/kubernetes/helm-install.md
Labels: cla: yes

#1266 Explain that the 10s mentioned timeout is hardcoded. Fixes #1213.
  _docs/tasks/traffic-management/fault-injection.md
Labels: approved, cla: yes

#1339 Remove WIP installation docs (mesos / cloud foundry)
  _docs/setup/cloudfoundry/index.md
  _docs/setup/cloudfoundry/install.md
  _docs/setup/mesos/index.md
  _docs/setup/mesos/install.md
Labels: approved, cla: yes, lgtm

#1334 Remove repeated "1."
  _docs/setup/kubernetes/helm-install.md
Labels: approved, cla: yes, lgtm

#1333 Remove redundant words in Grafana prerequisites
  _docs/tasks/telemetry/using-istio-dashboard.md
Labels: approved, cla: yes, lgtm

#1312 Major update to the Mixer docs.
  _blog/2017/adapter-model.md
  _blog/2017/mixer-spof-myth.md
  _docs/concepts/concept.md.template
  _docs/concepts/policies-and-telemetry/config.md
  _docs/concepts/policies-and-telemetry/img/adapters.svg
  _docs/concepts/policies-and-telemetry/img/machine.svg
  _docs/concepts/policies-and-telemetry/img/topology-with-cache.svg
  _docs/concepts/policies-and-telemetry/img/topology-without-cache.svg
  _docs/concepts/policies-and-telemetry/index.md
  _docs/concepts/policies-and-telemetry/overview.md
  _docs/concepts/policy-and-control/attributes.md
  _docs/concepts/policy-and-control/img/mixer/phases.svg
  _docs/concepts/policy-and-control/img/mixer/traffic.svg
  _docs/concepts/policy-and-control/index.md
  _docs/concepts/policy-and-control/mixer-config.md
  _docs/concepts/policy-and-control/mixer.md
  _docs/concepts/security/authn-policy.md
  _docs/concepts/security/mutual-tls.md
  _docs/concepts/security/rbac.md
  _docs/concepts/traffic-management/request-routing.md
  _docs/concepts/what-is-istio/overview.md
  _docs/guides/guide.md.template
  _docs/reference/config/policy-and-telemetry/attribute-vocabulary.md
  _docs/reference/config/policy-and-telemetry/expression-language.md
  _docs/reference/reference.md.template
  _docs/setup/setup.md.template
  _docs/tasks/policy-enforcement/index.md
  _docs/tasks/policy-enforcement/rate-limiting.md
  _docs/tasks/security/basic-access-control.md
  _docs/tasks/security/index.md
  _docs/tasks/security/secure-access-control.md
  _docs/tasks/task.md.template
  _docs/tasks/telemetry/fluentd.md
  _docs/tasks/telemetry/index.md
  _docs/tasks/telemetry/metrics-logs.md
  _docs/tasks/telemetry/tcp-metrics.md
  _glossary/adapters.md
  _glossary/mixer.md
  index.html
Labels: approved, cla: yes, lgtm

#1344 Added route rule to virtual service in Egress task
  _docs/tasks/traffic-management/egress.md
Labels: cla: yes, needs-ok-to-test

#1342 Renamed the VirtualService's destination name to host
  _docs/concepts/traffic-management/rules-configuration.md
  _docs/reference/config/istio.networking.v1alpha3.html
  _docs/tasks/traffic-management/circuit-breaking.md
  _docs/tasks/traffic-management/fault-injection.md
  _docs/tasks/traffic-management/request-routing.md
  _docs/tasks/traffic-management/request-timeouts.md
  _docs/tasks/traffic-management/traffic-shifting.md
Labels: cla: yes

#1346 use a specific host instead of "*" wildcard in a virtual service of ingress
  _docs/tasks/traffic-management/ingress.md
Labels: cla: yes, lgtm

#1350 A few corrections and improvements
  _about/notes/0.8.md
  _docs/tasks/traffic-management/ingress.md
Labels: approved, cla: yes, lgtm

#1330 change doc to reflect proxyv2
  _docs/setup/kubernetes/helm-install.md
Labels: approved, cla: yes, lgtm

#1353 Rename firewall-rules in "Control Ingress Traffic"
  _docs/tasks/traffic-management/ingress.md
Labels: cla: yes

#1343 Fix markdown code blocks using "```command"
  js/misc.js
  js/misc.min.js
Labels: approved, cla: yes, lgtm

#1351 egress task corrections
  _docs/tasks/traffic-management/egress-tcp.md
  _docs/tasks/traffic-management/egress.md
Labels: approved, cla: yes, lgtm

#1349 Match doc to recent webhook updates
  _docs/setup/kubernetes/helm-install.md
  _docs/setup/kubernetes/sidecar-injection.md
Labels: approved, cla: yes

#1357 Fix link to wrong task
  _docs/concepts/traffic-management/rules-configuration.md
Labels: cla: yes

#1358 Only trim for command check
  js/misc.js
  js/misc.min.js
Labels: cla: yes

#1331 update instruction for control plane
  _docs/setup/kubernetes/upgrading-istio.md
Labels: approved, cla: yes, lgtm

#1363 Cleanup
  .spelling
  config.toml
  content/_index.md
  content/about/_index.md
  content/about/contribute/writing-a-new-topic.md
  content/about/feature-stages.md
  content/about/notes/0.1.md
  content/about/notes/0.4.md
  content/about/notes/_index.md
  content/blog/2017/0.2-announcement.md
  content/blog/2018/aws-nlb.md
  content/docs/concepts/traffic-management/pilot.md
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/helm-install.md
  content/docs/setup/kubernetes/multicluster-install.md
  content/docs/setup/kubernetes/quick-start-gke-dm.md
  content/docs/tasks/telemetry/tcp-metrics.md
  content/help/faq/_index.md
  layouts/index.html
  layouts/partials/footer.html
  layouts/shortcodes/idea_icon.html
  layouts/shortcodes/inline_image.html
  layouts/shortcodes/site_suffix.html
  layouts/shortcodes/warning_icon.html
Labels: approved, cla: yes

#1372 Workaround Hugo formatting bug with indented code blocks that have lines that start with -
  content/blog/2018/egress-tcp.md
  content/docs/guides/endpoints.md
  content/docs/tasks/policy-enforcement/rate-limiting.md
  content/docs/tasks/security/basic-access-control.md
  content/docs/tasks/security/role-based-access-control.md
  content/docs/tasks/telemetry/metrics-logs.md
  content/docs/tasks/telemetry/tcp-metrics.md
  content/docs/tasks/traffic-management/egress.md
  content/docs/tasks/traffic-management/fault-injection.md
  content/docs/tasks/traffic-management/ingress.md
  content/docs/tasks/traffic-management/mirroring.md
  content/docs/tasks/traffic-management/request-routing.md
  content/docs/tasks/traffic-management/request-timeouts.md
  content/docs/tasks/traffic-management/traffic-shifting.md
  content/help/troubleshooting.md
  src/js/misc.js
  static/js/all.min.js
Labels: approved, cla: yes, lgtm

#1373 Updated cleanup section for bookinfo.
  content/docs/guides/bookinfo.md
Labels: approved, cla: yes, lgtm

#1371 Updated doc as proxyv2 is now the default global proxy image
  content/docs/guides/bookinfo.md
  content/docs/setup/kubernetes/helm-install.md
Labels: approved, cla: yes, lgtm

#1374 Update installation page to include istio-demo-auth story
  content/docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes, lgtm

#1366 A number of visual improvements.
  layouts/partials/header.html
  src/js/styleSwitcher.js
  src/sass/base/_common.scss
  src/sass/modules/_footer.scss
  src/sass/modules/_header.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
  static/js/styleSwitcher.min.js
Labels: approved, cla: yes, lgtm

#1076 [0.8] layout and initial content for perf and scalability section
  .spelling
  _docs/performance-and-scalability/microbenchmarks.md
  _docs/performance-and-scalability/overview.md
  _docs/performance-and-scalability/performance-testing-automation.md
  _docs/performance-and-scalability/realistic-app-benchmark.md
  _docs/performance-and-scalability/scalability.md
  _docs/performance-and-scalability/scenarios.md
  _docs/performance-and-scalability/synthetic-benchmarks.md
  content/docs/_index.md
  content/docs/performance-and-scalability/_index.md
  content/docs/performance-and-scalability/microbenchmarks.md
  content/docs/performance-and-scalability/overview.md
  content/docs/performance-and-scalability/performance-testing-automation.md
  content/docs/performance-and-scalability/realistic-app-benchmark.md
  content/docs/performance-and-scalability/scalability.md
  content/docs/performance-and-scalability/scenarios.md
  content/docs/performance-and-scalability/synthetic-benchmarks.md
Labels: approved, cla: yes, lgtm

#1367 Change `details` to container but not VM for mesh expansion.
  content/docs/guides/img/mesh-expansion.svg
Labels: cla: yes

#1365 Add structured data to help Google do a better job at indexing the site.
  content/_index.md
  static/img/logo.png
Labels: approved, cla: yes

#1378 Fix commands for authn policy tutorial.
  content/docs/tasks/security/authn-policy.md
Labels: approved, cla: yes, lgtm

#1383 remove optional webhook since we recommend 1.9
  content/docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes, lgtm

#1385 Update reference docs.
  content/docs/reference/commands/istio_ca.html
  content/docs/reference/commands/istioctl.html
  content/docs/reference/commands/mixc.html
  content/docs/reference/commands/mixs.html
  content/docs/reference/commands/node_agent.html
  content/docs/reference/commands/pilot-agent.html
  content/docs/reference/commands/pilot-discovery.html
  content/docs/reference/commands/sidecar-injector.html
  content/docs/reference/config/istio.networking.v1alpha3.html
  content/docs/reference/config/istio.rbac.v1alpha1.html
  content/docs/reference/config/istio.routing.v1alpha1.html
  content/docs/reference/config/policy-and-telemetry/adapters/circonus.html
  content/docs/reference/config/policy-and-telemetry/adapters/cloudwatch.html
  content/docs/reference/config/policy-and-telemetry/adapters/datadog.html
  content/docs/reference/config/policy-and-telemetry/adapters/denier.html
  content/docs/reference/config/policy-and-telemetry/adapters/fluentd.html
  content/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv.html
  content/docs/reference/config/policy-and-telemetry/adapters/list.html
  content/docs/reference/config/policy-and-telemetry/adapters/memquota.html
  content/docs/reference/config/policy-and-telemetry/adapters/opa.html
  content/docs/reference/config/policy-and-telemetry/adapters/prometheus.html
  content/docs/reference/config/policy-and-telemetry/adapters/rbac.html
  content/docs/reference/config/policy-and-telemetry/adapters/redisquota.html
  content/docs/reference/config/policy-and-telemetry/adapters/servicecontrol.html
  content/docs/reference/config/policy-and-telemetry/adapters/solarwinds.html
  content/docs/reference/config/policy-and-telemetry/adapters/stackdriver.html
  content/docs/reference/config/policy-and-telemetry/adapters/statsd.html
  content/docs/reference/config/policy-and-telemetry/adapters/stdio.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1.html
  content/docs/reference/config/policy-and-telemetry/templates/apikey.html
  content/docs/reference/config/policy-and-telemetry/templates/authorization.html
  content/docs/reference/config/policy-and-telemetry/templates/checknothing.html
  content/docs/reference/config/policy-and-telemetry/templates/kubernetes.html
  content/docs/reference/config/policy-and-telemetry/templates/listentry.html
  content/docs/reference/config/policy-and-telemetry/templates/logentry.html
  content/docs/reference/config/policy-and-telemetry/templates/metric.html
  content/docs/reference/config/policy-and-telemetry/templates/quota.html
  content/docs/reference/config/policy-and-telemetry/templates/reportnothing.html
  content/docs/reference/config/policy-and-telemetry/templates/servicecontrolreport.html
  scripts/grab_reference_docs.sh
Labels: approved, cla: yes

#1391 Delete stale files.
  _docs/performance-and-scalability/microbenchmarks.md
  _docs/performance-and-scalability/overview.md
  _docs/performance-and-scalability/performance-testing-automation.md
  _docs/performance-and-scalability/realistic-app-benchmark.md
  _docs/performance-and-scalability/scalability.md
  _docs/performance-and-scalability/scenarios.md
  _docs/performance-and-scalability/synthetic-benchmarks.md
Labels: approved, cla: yes

#1376 Fixes to the upgrade and sidecar docs
  content/docs/setup/kubernetes/sidecar-injection.md
  content/docs/setup/kubernetes/upgrading-istio.md
Labels: cla-manual

#1387 format change only on quick start install section
  content/docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes, lgtm

#1394 merge #1387 to 0.8 branch
  content/docs/setup/kubernetes/quick-start.md
Labels: approved, cla: yes

#1393 Add FAQ section regarding naming port convention
  content/help/faq/traffic-management/naming-port-convention.md
Labels: cla: yes, needs-ok-to-test

#1395 Add instructions for waiting for secure ingress
  content/docs/tasks/traffic-management/ingress.md
Labels: cla: yes

#1396 Fix the table format in expression-language.md
  content/docs/reference/config/policy-and-telemetry/expression-language.md
Labels: cla: yes

#1398 Release 0.8
  .spelling
  content/docs/reference/config/policy-and-telemetry/expression-language.md
  content/help/faq/traffic-management/naming-port-convention.md
  layouts/shortcodes/image.html
Labels: approved, cla: no

#1389 Add SNI support in release notes for 0.8
  content/about/notes/0.8.md
Labels: approved, cla: yes, lgtm

#1397 need to use replace vs create
  content/docs/setup/kubernetes/upgrading-istio.md
Labels: approved, cla: yes, lgtm
