Repository istio/istio.io, pull requests merged in 2018-07, with the labels that each got.

#1646 Chinese: about - contribute -writing a new topic
  content_zh/about/contribute/writing-a-new-topic/index.md
Labels: approved, cla: yes, lgtm

#1645 Simplify contribution instructions.
  content/about/contribute/creating-a-pull-request/index.md
  content/about/contribute/editing/index.md
  content/about/contribute/github/index.md
  content/about/contribute/reviewing-doc-issues/index.md
  content/about/contribute/staging-your-changes/index.md
  content/about/contribute/writing-a-new-topic/index.md
  content/docs/_index.md
Labels: approved, cla: yes

#1647 remove something only relating to 0.5 from the 1.0 docs
  content/help/troubleshooting/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1668 Adding rootsongjc and fleeto to OWNERS for Chinese.
  content_zh/OWNERS
Labels: approved, cla: yes

#1617 Adding Alpha status SolarWinds adapter
  content/about/feature-stages/index.md
Labels: cla: yes

#1669 Simplify linking to GitHub content.
  content/about/contribute/github/index.md
  content/about/contribute/style-guide/index.md
  content/about/contribute/writing-a-new-topic/index.md
  content/about/feature-stages/index.md
  content/blog/2017/0.1-announcement/index.md
  content/blog/2017/0.1-auth/index.md
  content/blog/2017/0.1-canary/index.md
  content/blog/2017/adapter-model/index.md
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-tcp/index.md
  content/blog/2018/export-logs-through-stackdriver/index.md
  content/docs/examples/integrating-vms/index.md
  content/docs/performance-and-scalability/microbenchmarks/index.md
  content/docs/performance-and-scalability/scenarios/index.md
  content/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/docs/setup/consul/install/index.md
  content/docs/setup/eureka/install/index.md
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/setup/kubernetes/mesh-expansion/index.md
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/tasks/security/authn-policy/index.md
  content/docs/tasks/security/mutual-tls/index.md
  content/docs/tasks/security/role-based-access-control/index.md
  content/docs/tasks/telemetry/servicegraph/index.md
  content/docs/tasks/traffic-management/app-health-check/index.md
  content/docs/tasks/traffic-management/circuit-breaking/index.md
  content/docs/tasks/traffic-management/egress-tls-origination/index.md
  content/docs/tasks/traffic-management/egress/index.md
  content/docs/tasks/traffic-management/ingress/index.md
  content/docs/tasks/traffic-management/mirroring/index.md
  content/docs/tasks/traffic-management/secure-ingress/index.md
  layouts/partials/toc.html
  layouts/shortcodes/github_blob.html
  layouts/shortcodes/github_file.html
  layouts/shortcodes/github_tree.html
  layouts/shortcodes/text.html
Labels: approved, cla: yes

#1661 edit reviews virtualservice yaml output
  content/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: cla: yes, needs-ok-to-test

#1662 fix broken link (./public/docs/tasks/telemetry/using-istio-dashboard/index.html)
  content/docs/tasks/telemetry/using-istio-dashboard/index.md
Labels: cla: yes, needs-ok-to-test

#1676 Fix missing Gateway apiVersion in egress-gateway.md
  content/docs/tasks/traffic-management/egress-gateway.md
Labels: cla: yes, needs-ok-to-test

#1675 make istio installation yaml file consistent
  content/docs/tasks/security/https-overlay/index.md
Labels: cla: yes, lgtm

#1683 Move the community page into the About section.
  content/about/community/index.md
  content/about/feature-stages/index.md
  content/help/_index.md
  content/help/faq/general/how-do-i-contribute.md
  content_zh/help/_index.md
  layouts/partials/header.html
Labels: approved, cla: yes

#1642 503 and Gateway troubleshooting
  content/help/troubleshooting/index.md
Labels: approved, cla: no

#1690 Remove link annotations from command paths
  content/blog/2018/soft-multitenancy/index.md
  content/docs/setup/consul/quick-start/index.md
  content/docs/setup/eureka/quick-start/index.md
  content/docs/setup/kubernetes/sidecar-injection/index.md
  content/docs/setup/kubernetes/upgrading-istio/index.md
  content/docs/tasks/security/health-check/index.md
  content/docs/tasks/security/https-overlay/index.md
  content/docs/tasks/security/plugin-ca-cert/index.md
  content/docs/tasks/telemetry/servicegraph/index.md
  content/docs/tasks/telemetry/using-istio-dashboard/index.md
  content/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes

#1680 Add download & print buttons to all PRE blocks.
  content/about/contribute/writing-a-new-topic/index.md
  layouts/partials/primary-bottom.html
  layouts/shortcodes/text.html
  layouts/shortcodes/text_dynamic.html
  layouts/shortcodes/text_file.html
  src/js/misc.js
  src/sass/base/_common.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
  static/js/all.min.js
  static/js/all.min.js.map
Labels: approved, cla: yes

#1691 Revert "503 and Gateway troubleshooting"
  content/help/troubleshooting/index.md
Labels: approved, cla: yes

#1692 Fix broken links
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/tasks/security/mutual-tls/index.md
  content_zh/blog/2018/soft-multitenancy/index.md
Labels: cla: yes

#1694 Generate Helm config options from values.md
  content/docs/setup/kubernetes/helm-install/index.md
  scripts/tablegen.py
Labels: cla: yes

#1686 Create hidden links for the special @@ references.
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/tasks/traffic-management/egress/index.md
  layouts/shortcodes/text.html
Labels: approved, cla: yes

#1695 Revert one small change that added a link
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes

#1696 Change all references to istio-demo-*.yaml
  content/docs/setup/kubernetes/quick-start/index.md
  content/docs/tasks/security/authn-policy/index.md
  content/docs/tasks/security/health-check/index.md
  content/docs/tasks/security/https-overlay/index.md
  content/docs/tasks/security/mutual-tls/index.md
  content/docs/tasks/security/plugin-ca-cert/index.md
  content/docs/tasks/telemetry/distributed-tracing/index.md
  content/docs/tasks/telemetry/querying-metrics/index.md
  content/docs/tasks/traffic-management/app-health-check/index.md
  content_zh/blog/2018/soft-multitenancy/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes

#1693 Improve name selection process for the new PRE block download feature.
  layouts/_default/baseof.html
  layouts/shortcodes/text.html
  layouts/shortcodes/text_dynamic.html
  layouts/shortcodes/text_file.html
  src/js/misc.js
  src/sass/base/_common.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_normal.css
  static/css/dark_theme_preliminary.css
  static/css/light_theme_archive.css
  static/css/light_theme_normal.css
  static/css/light_theme_preliminary.css
  static/js/all.min.js
  static/js/all.min.js.map
Labels: approved, cla: yes

#1701 Various site fixes.
  layouts/partials/primary-bottom.html
  layouts/partials/toc.html
  layouts/section-index/list.html
  layouts/shortcodes/idea_icon.html
  layouts/shortcodes/warning_icon.html
  scripts/build_site.sh
  src/js/misc.js
  src/js/utils.js
  src/sass/base/_common.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
  static/js/all.min.js
  static/js/all.min.js.map
Labels: approved, cla: yes

#1652 Chinese:task-security-plugin-ca-cert
  content_zh/docs/tasks/security/plugin-ca-cert/index.md
Labels: approved, cla: yes, translation-chinese

#1688 Translate: task egress
  content_zh/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, translation-chinese

#1685 Chineses: update content
  content_zh/docs/concepts/policies-and-telemetry/_index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/policies-and-telemetry/overview/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1684 translate-zh: task-telemetry-index.
  content_zh/docs/tasks/telemetry/_index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1682 Chinese: Translation fault-injection
  content_zh/docs/tasks/traffic-management/fault-injection/index.md
Labels: cla: yes, ok-to-test, translation-chinese

#1681 Chinese: Translation control ingress traffic
  content_zh/docs/tasks/traffic-management/_index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
Labels: cla: yes, needs-ok-to-test, translation-chinese

#1660 Chinese: concepts-mutual-tls
  content_zh/docs/concepts/security/mutual-tls/index.md
Labels: approved, cla: yes, translation-chinese

#1648 Chinese: task-security, task-security-mutual-tls
  content_zh/docs/tasks/security/_index.md
  content_zh/docs/tasks/security/mutual-tls/index.md
Labels: approved, cla: yes, translation-chinese

#1664 Translate performance-and-scalability/scenarios into Chinese
  content_zh/docs/performance-and-scalability/scenarios/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1658 Translate performance-and-scalability/realistic-app-benchmark into Chinese
  content_zh/docs/performance-and-scalability/performance-testing-automation/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1655 translate performance-and-scalability/overview into Chinese
  content_zh/docs/performance-and-scalability/overview/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1656 Translate performance-and-scalability/mrobenchmarks into Chinese
  content_zh/docs/performance-and-scalability/microbenchmarks/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1704 Change name of Policy and DestinationRule in task "docs/tasks/security/authn-policy/index.md"
  content/docs/tasks/security/authn-policy/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1710 Put back reverted new troubleshooting material
  .spelling
  content/help/troubleshooting/index.md
Labels: approved, cla: no

#1713 Document rename context reporter type to context reporter kind
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: approved, cla: yes, lgtm

#1709 Edit Collaboration Guide to include forking info.
  content/about/contribute/github/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1726 In the GKE section, changed <project-name> to <project-id>.
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes, needs-ok-to-test

#1722 principal attributes
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: approved, cla: yes, lgtm

#1730 Copy edit for Setting Request Timeouts.
  content/docs/tasks/traffic-management/request-timeouts/index.md
Labels: cla: yes, needs-ok-to-test

#1728 Fix spec port name used to obtain ingress gateway port
  content/docs/tasks/traffic-management/ingress/index.md
Labels: cla: yes

#1732 Copy edit for Control Ingress Traffic.
  content/docs/tasks/traffic-management/ingress/index.md
Labels: cla: yes, needs-ok-to-test

#1731 Consolidate perf & scalability pages into a single page.
  content/docs/concepts/performance-and-scalability/index.md
  content/docs/performance-and-scalability/_index.md
  content/docs/performance-and-scalability/microbenchmarks/index.md
  content/docs/performance-and-scalability/overview/index.md
  content/docs/performance-and-scalability/performance-testing-automation/index.md
  content/docs/performance-and-scalability/realistic-app-benchmark/index.md
  content/docs/performance-and-scalability/scalability/index.md
  content/docs/performance-and-scalability/scenarios/index.md
  content/docs/performance-and-scalability/synthetic-benchmarks/index.md
Labels: approved, cla: yes

#1716 routing concept doc improvements
  content/docs/concepts/traffic-management/index.md
Labels: approved, cla: yes

#1705 In task "security/https-overlay/index.md", replace hard coded pod-id by command substitution.
  content/docs/tasks/security/https-overlay/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1733 Copy edit of Securing Gateways with HTTPS.
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: cla: yes, needs-ok-to-test

#1738 New architecture diagram
  content/docs/concepts/what-is-istio/arch.svg
Labels: cla: no, needs-ok-to-test

#1715 Create service subsets and move routing/route-rule* to networking/virtual-service*
  content/about/contribute/writing-a-new-topic/index.md
  content/blog/2018/egress-tcp/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/examples/integrating-vms/index.md
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
  content/docs/tasks/security/basic-access-control/index.md
  content/docs/tasks/security/secure-access-control/index.md
  content/docs/tasks/telemetry/tcp-metrics/index.md
  content/docs/tasks/traffic-management/fault-injection/index.md
  content/docs/tasks/traffic-management/request-routing/index.md
  content/docs/tasks/traffic-management/request-timeouts/index.md
  content/docs/tasks/traffic-management/traffic-shifting/index.md
  content_zh/about/contribute/writing-a-new-topic/index.md
  content_zh/docs/tasks/traffic-management/fault-injection/index.md
  content_zh/docs/tasks/traffic-management/request-routing/index.md
  data/args.yml
Labels: cla: yes

#1737 Edit the What is Istio file for clarity.
  content/docs/concepts/what-is-istio/index.md
Labels: cla: yes, needs-ok-to-test

#1740 Update default metrics page
  content/docs/reference/config/policy-and-telemetry/metrics/index.md
Labels: cla: yes

#1717 Remove Eureka references
  content/about/feature-stages/index.md
  content/blog/2017/0.2-announcement/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/setup/eureka/_index.md
  content/docs/setup/eureka/install/index.md
  content/docs/setup/eureka/quick-start/index.md
  content/help/faq/setup/eureka-app-not-working.md
  content/help/faq/setup/eureka-unset-context.md
Labels: cla: yes

#1698 Add debugging Istio task
  content/help/ops/traffic-management/debugging-pilot-envoy/index.md
Labels: cla: yes

#1565 Document PERMISSIVE mode for incremental mTLS adoption.
  content/docs/tasks/security/mtls-migration/index.md
Labels: cla: yes

#1712 add description of connection.requested_server_name
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: cla: yes

#1734 Experiment with arrows in section index pages.
  layouts/partials/primary-bottom.html
  layouts/section-index/list.html
  src/sass/layouts/_section-index.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: approved, cla: yes

#1759 Fix references to bookinfo sample files
  content/about/contribute/writing-a-new-topic/index.md
  content/blog/2017/adapter-model/index.md
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-tcp/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/examples/integrating-vms/index.md
  content/docs/tasks/security/basic-access-control/index.md
  content/docs/tasks/security/role-based-access-control/index.md
  content/docs/tasks/security/secure-access-control/index.md
  content/docs/tasks/telemetry/tcp-metrics/index.md
Labels: approved, cla: yes

#1743 Update basic-access-control and request-routing.
  content/docs/tasks/security/basic-access-control/index.md
  content/docs/tasks/traffic-management/request-routing/index.md
Labels: cla: yes

#1741 Minor edit in last paragraph of What is Istio.
  content/docs/concepts/what-is-istio/index.md
Labels: cla: yes, needs-ok-to-test

#1754 Copy edit for Control Egress Traffic.
  content/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes, needs-ok-to-test

#1756 Copy edit for the TLS Origination for Egress Traffic topic.
  content/docs/tasks/traffic-management/egress-tls-origination/index.md
Labels: cla: yes, needs-ok-to-test

#1758 Copy edits for Health Checking of Istio Services.
  content/docs/tasks/traffic-management/app-health-check/index.md
Labels: cla: yes, needs-ok-to-test

#1748 First round of edits.
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes, needs-ok-to-test

#1760 Translate task secure access control
  content_zh/docs/tasks/security/secure-access-control/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1767 translate: tasks/trafic-management/circuit-breaking
  content_zh/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1755 Translate: task/security/basic-access-control
  content_zh/docs/tasks/security/basic-access-control/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1725 Chinese: Translation blog 2018 index
  content_zh/blog/2018/_index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1729 Translate: setup/expansion
  content_zh/docs/setup/kubernetes/mesh-expansion/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1753 Blog 2018 egress https index
  content_zh/blog/2018/egress-https/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1769 Translate: tasks/policy-enforcement/rate-limiting
  content_zh/docs/tasks/policy-enforcement/_index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1771 Translate task security health check
  content_zh/docs/tasks/security/health-check/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1708 Translated setup/kubernetes/multicluster into Chinese
  content_zh/docs/setup/kubernetes/multicluster-install/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1707 Translate "docs/tasks/security/authn-policy/index.md" into Chinese
  content_zh/docs/tasks/security/authn-policy/index.md
Labels: cla: yes, needs-ok-to-test, translation-chinese

#1714 Update multicluster doc with latest helm chart changes
  .spelling
  content/docs/setup/kubernetes/multicluster-install/index.md
Labels: cla: yes

#1773 Chinese: /docs/concepts/what-is-istio/index.md
  content_zh/docs/concepts/what-is-istio/_index.md
  content_zh/docs/concepts/what-is-istio/goals/index.md
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/concepts/what-is-istio/overview/index.md
Labels: approved, cla: yes, lgtm, translation-chinese

#1765 istio.yaml > istio-demo.yaml
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes, lgtm

#1770 fixed: references to sleep.yaml
  content/docs/setup/kubernetes/sidecar-injection/index.md
  content/docs/tasks/security/https-overlay/index.md
  content/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes

#1772 Copy edits for Traffic Management.
  content/docs/concepts/traffic-management/index.md
Labels: cla: yes, needs-ok-to-test

#1774 Extend secure ingress troubleshooting
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: approved, cla: yes, lgtm

#1776 Remove sidecar injection instructions and ingress
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes

#1775 Fix typo in Kubernetes Quick Start Guide
  content/docs/setup/kubernetes/quick-start/index.md
Labels: approved, cla: yes, lgtm

#1777 Edit file for consitency, grammar, style
  content/docs/tasks/traffic-management/fault-injection/index.md
Labels: cla: yes, needs-ok-to-test

#1764 Edit file for readability, style, grammar.
  content/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: approved, cla: yes

#1763 Edit file for readability, style, grammar.
  content/docs/tasks/traffic-management/request-routing/index.md
Labels: approved, cla: yes, needs-ok-to-test

#1782 TLS Origination glossary entry
  content/help/glossary/tls-origination.md
Labels: approved, cla: yes, lgtm

#1780 Delete "basic access control" and "secure access control" pages.
  content/docs/tasks/security/_index.md
  content/docs/tasks/security/basic-access-control/index.md
  content/docs/tasks/security/secure-access-control/index.md
Labels: cla: yes

#1762 Edit Kubernetes Quick Start for clarity.
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: approved, cla: yes, lgtm

#1632 Translate traffic-shifting task to Chinese
  content_zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: approved, cla: yes, translation-chinese

#1796 Add link to new TLS Origination glossary entry.
  content/docs/tasks/traffic-management/egress-tls-origination/index.md
Labels: cla: yes, needs-ok-to-test

#1794 fixed: index file for concepts/security
  content_zh/docs/concepts/security/_index.md
  content_zh/docs/concepts/security/rbac/index.md
Labels: approved, cla: yes, translation-chinese

#1797 Remove warnings that are no longer relevant
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes, lgtm

#1801 Start of 1.0 release notes
  content/about/notes/1.0/index.md
Labels: approved, cla: yes, lgtm

#1803 Service registry glossary entry
  content/help/glossary/service-registry.md
  content/help/glossary/tls-origination.md
Labels: approved, cla: yes, lgtm

#1791 2nd round of edits on rate limiting.
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: approved, cla: yes, lgtm

#1808 Updated link to vm drivers link to list names of drivers
  content/docs/setup/kubernetes/quick-start/index.md
Labels: approved, cla: yes, lgtm

#1785 Edit mirroring topic for style, clarity, grammar.
  content/docs/tasks/traffic-management/mirroring/index.md
Labels: approved, cla: yes, lgtm

#1799 Rewrite Rule configuration intro and some minor copy edits.
  content/docs/concepts/traffic-management/index.md
Labels: approved, cla: yes, lgtm

#1809 Update istio-auth.yaml to istio-demo-auth.yaml
  content/docs/setup/kubernetes/upgrading-istio/index.md
  content/docs/tasks/security/health-check/index.md
  content/docs/tasks/security/https-overlay/index.md
  content/docs/tasks/security/mutual-tls/index.md
  content/docs/tasks/security/plugin-ca-cert/index.md
  content/docs/tasks/telemetry/distributed-tracing/index.md
  content/docs/tasks/telemetry/querying-metrics/index.md
  content/help/faq/security/cert-lifetime-config.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/tasks/security/health-check/index.md
  content_zh/docs/tasks/security/plugin-ca-cert/index.md
Labels: approved, cla: yes, lgtm

#1810 remove v1alph1 routing references
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-tcp/index.md
  content/blog/2018/soft-multitenancy/index.md
  content/docs/concepts/traffic-management/index.md
  content_zh/blog/2018/egress-https/index.md
  content_zh/blog/2018/soft-multitenancy/index.md
  content_zh/docs/concepts/traffic-management/handling-failures/index.md
  content_zh/docs/concepts/traffic-management/pilot/index.md
Labels: approved, cla: yes, lgtm

#1811 Refactor About section in traffic-shifting document.
  content/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: approved, cla: yes, lgtm

#1812 Update reference docs.
  content/blog/2018/v1alpha3-routing/index.md
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/docs/reference/config/istio.networking.v1alpha3/index.html
  content/docs/reference/config/istio.routing.v1alpha1/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
  content/docs/reference/config/policy-and-telemetry/templates/kubernetes/index.html
  content_zh/blog/2018/v1alpha3-routing/index.md
  scripts/grab_reference_docs.sh
Labels: approved, cla: yes

#1784 Edit for consistency, clarity, grammar, style
  content/docs/tasks/traffic-management/circuit-breaking/index.md
  content/docs/tasks/traffic-management/fault-injection/index.md
Labels: cla: yes

#1813 Deleted/replaced deprecated items, and some minor edits.
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes, needs-ok-to-test

#1815 Remove innacurate text about extra RBAC files
  content/docs/tasks/security/role-based-access-control/index.md
Labels: approved, cla: yes, lgtm

#1814 Task "docs/tasks/telemetry/tcp-metrics/index.md" is missing creation of DestinationRules used by "reviews" and "ratings" VirtualServices
  content/docs/tasks/telemetry/tcp-metrics/index.md
Labels: cla: yes, needs-ok-to-test

#1804 Add a platform setup section and link it in helm install page
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: approved, cla: yes, lgtm

#1816 Newlines to display lists correctly
  content/docs/tasks/security/role-based-access-control/index.md
Labels: cla: yes

#1744 Fix the non-existent file in the test description of Citadel health checking
  content/docs/tasks/security/health-check/index.md
Labels: approved, cla: yes

#1821 Update to latest Hugo
  .circleci/config.yml
  Makefile
  mdl_style.rb
  netlify.toml
  scripts/Dockerfile
Labels: approved, cla: yes

#1819 Documents in concept/security had been joined together.
  content_zh/docs/concepts/security/_index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/concepts/security/mutual-tls/index.md
  content_zh/docs/concepts/security/rbac/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1824 Enable more linting rules
  .spelling
  content/about/contribute/writing-a-new-topic/index.md
  content/about/notes/0.5/index.md
  content/about/notes/0.6/index.md
  content/blog/2018/egress-https/index.md
  content/blog/2018/export-logs-through-stackdriver/index.md
  content/blog/2018/soft-multitenancy/index.md
  content/blog/2018/v1alpha3-routing/index.md
  content/docs/concepts/performance-and-scalability/index.md
  content/docs/concepts/security/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/reference/config/policy-and-telemetry/expression-language/index.md
  content/docs/setup/consul/quick-start/index.md
  content/docs/setup/kubernetes/mesh-expansion/index.md
  content/docs/setup/kubernetes/multicluster-install/index.md
  content/docs/setup/kubernetes/quick-start/index.md
  content/docs/setup/kubernetes/sidecar-injection/index.md
  content/docs/tasks/security/mtls-migration/index.md
  content/docs/tasks/security/role-based-access-control/index.md
  content/docs/tasks/telemetry/distributed-tracing/index.md
  content/docs/tasks/telemetry/fluentd/index.md
  content/docs/tasks/traffic-management/egress-tls-origination/index.md
  content/docs/tasks/traffic-management/egress/index.md
  content/docs/tasks/traffic-management/secure-ingress/index.md
  content/help/faq/traffic-management/ingress-with-no-route-rules.md
  content/help/glossary/service-registry.md
  content/help/troubleshooting/index.md
  content_zh/about/contribute/writing-a-new-topic/index.md
  content_zh/blog/2018/egress-https/index.md
  content_zh/blog/2018/soft-multitenancy/index.md
  content_zh/blog/2018/v1alpha3-routing/index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/concepts/traffic-management/rules-configuration/index.md
  content_zh/docs/performance-and-scalability/microbenchmarks/index.md
  content_zh/docs/setup/kubernetes/mesh-expansion/index.md
  content_zh/docs/setup/kubernetes/multicluster-install/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/tasks/security/basic-access-control/index.md
  content_zh/docs/tasks/security/secure-access-control/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
  mdl_style.rb
  scripts/lint_site.sh
Labels: approved, cla: yes

#1823 Update Realistic Benchmark section on docs
  .spelling
  content/docs/concepts/performance-and-scalability/index.md
Labels: cla: no

#1826 Edit minor issue in fault-injection document.
  content/docs/tasks/traffic-management/fault-injection/index.md
Labels: cla: yes, needs-ok-to-test

#1828 Task traffic management egress tls origination
  content_zh/docs/tasks/traffic-management/egress-tls-origination/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1795 Translation blog 2018 egress tcp
  content_zh/blog/2018/egress-tcp/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1778 Translate setup kubernetes sidecar injection
  content_zh/docs/setup/kubernetes/sidecar-injection/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1837 Switch bookinfo install to use kubectl apply instead of istioctl create for ingress
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm

#1835 clarify ingress host instructions
  content/docs/tasks/traffic-management/ingress/index.md
Labels: approved, cla: yes

#1807 Update Istio Authorization Concept.
  content/about/feature-stages/index.md
  content/about/notes/0.5/index.md
  content/docs/concepts/security/IstioRBAC.svg
  content/docs/concepts/security/authz.svg
  content/docs/concepts/security/index.md
  content/docs/concepts/what-is-istio/index.md
  content/docs/reference/config/authorization/constraints-and-properties/index.md
  content/docs/tasks/security/role-based-access-control/index.md
  content/help/faq/security/does-istio-support-authorization.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/concepts/what-is-istio/index.md
Labels: approved, cla: yes, lgtm

#1789 Update RBAC task for Istio 1.0.
  content/docs/tasks/security/role-based-access-control/index.md
Labels: approved, cla: yes

#1832 Add a Media Resources page.
  content/about/media-resources/index.md
  src/sass/_common.scss
  src/sass/layouts/_media-resources.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
  static/img/istio-blue-logo-social-white-background.svg
  static/img/istio-blue-logo-social.svg
  static/img/istio-blue-logo-white-background.svg
  static/img/istio-blue-logo.svg
Labels: approved, cla: yes

#1829 Translation using-istio-dashboard
  content_zh/docs/tasks/telemetry/using-istio-dashboard/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#1751 Updating 3 diagrams
  content/docs/concepts/traffic-management/LoadBalancing.svg
  content/docs/concepts/traffic-management/PilotAdapters.svg
  content/docs/concepts/traffic-management/ServiceModel_Versions.svg
  content/docs/concepts/traffic-management/TrafficManagementOverview.svg
  content/docs/concepts/what-is-istio/arch.svg
Labels: cla: yes

#1699 Move Helm customization section to the references category
  content/about/notes/0.8/index.md
  content/docs/reference/config/installation-options/index.md
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
  scripts/tablegen.py
Labels: cla: yes, lgtm

#1849 add envoy version info into troubleshooting guide
  content/help/troubleshooting/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1844 add a sentence: When prompted, select `y` for all the questions to the Securing Gateways task
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: approved, cla: yes, lgtm

#1845 add a check of Envoy's certificates to the troubleshooting section
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: approved, cla: yes, lgtm

#1838 Translate task tcp metrics
  content_zh/docs/tasks/telemetry/tcp-metrics/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1850 Translate task metrics logs
  content_zh/docs/tasks/telemetry/metrics-logs/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1852 translate:tasks/telemetry/distributed-tracing
  content_zh/docs/tasks/telemetry/distributed-tracing/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1746 add instruction to label the default ns for bookinfo example
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm

#1856 workaround for hugo bug
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes

#1861 fix typo
  content/docs/setup/kubernetes/ansible-install/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#1830 Translation querying-metrics
  content_zh/docs/tasks/telemetry/querying-metrics/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1831 fix egress tcp _
  content_zh/blog/2018/egress-tcp/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1839 Merge traffic-management
  content_zh/docs/concepts/traffic-management/_index.md
  content_zh/docs/concepts/traffic-management/fault-injection/index.md
  content_zh/docs/concepts/traffic-management/handling-failures/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/concepts/traffic-management/load-balancing/index.md
  content_zh/docs/concepts/traffic-management/overview/index.md
  content_zh/docs/concepts/traffic-management/pilot/index.md
  content_zh/docs/concepts/traffic-management/request-routing/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1633 Translate docs/tasks/traffic-management/app-health-check/index.md into chinese
  content_zh/docs/tasks/traffic-management/app-health-check/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1855 translate: guides/telemetry
  content_zh/docs/examples/telemetry/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1834 Extract platform prerequisites
  content/blog/2018/export-logs-through-stackdriver/index.md
  content/docs/examples/endpoints/index.md
  content/docs/setup/kubernetes/download-release/index.md
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/setup/kubernetes/platform-setup/index.md
  content/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/setup/kubernetes/sidecar-injection/index.md
Labels: approved, cla: yes, lgtm

#1650 translate content_zh/docs/setup/kubernetes/upgrading-istio into chinese
  content_zh/docs/setup/kubernetes/upgrading-istio/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1864 translate: guides/intelligent-routing
  content_zh/docs/examples/intelligent-routing/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1653 translate setup/kubernetes/ansible-install/index.md into Chinese
  content_zh/docs/setup/kubernetes/ansible-install/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1651 translate content_zh/docs/setup/kubernetes/helm-install into Chinese
  content_zh/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1827 Translate concepts/performance-and-scalability into Chinese.
  content_zh/docs/concepts/performance-and-scalability/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1858 translate:tasks/traffic-management/request-timeout
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1865 Translate guides integrating vm
  content_zh/docs/examples/integrating-vms/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1853 translate:guides/bookinfo
  content_zh/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#1689 Translate reference/config/policy-and-telemetry/metrics into Chinese
  content_zh/docs/reference/config/policy-and-telemetry/metrics/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#1860 Update TCP Report diagram
  content/docs/tasks/telemetry/tcp-metrics/istio-tcp-attribute-flow.svg
Labels: cla: yes, lgtm

#1854 Update Mixer FAQ Entries
  .spelling
  content/help/faq/mixer/mixer-self-monitoring.md
  content/help/faq/mixer/seeing-mixer-config.md
  content/help/faq/mixer/writing-custom-adapters.md
Labels: cla: yes, lgtm
