Repository istio/istio.io, pull requests merged in 2018-10, with the labels that each got.

#2709 zh: sync help ops observing
  content_zh/help/ops/traffic-management/observing/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2692 authn: add task for per-path jwt authentication
  content/docs/concepts/security/index.md
  content/docs/tasks/security/authn-policy/index.md
Labels: area/security, cla: yes, lgtm

#2657 zh： content/docs/tasks/security/plugin-ca-cert/
  content_zh/docs/tasks/security/plugin-ca-cert/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2676 zh: reference adapter apigee
  content_zh/docs/reference/config/policy-and-telemetry/adapters/apigee/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2639 zh: content/docs/concept/security/index.md
  content_zh/docs/concepts/security/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2705 update helm instruct for 2.10 and uninstall
  content/docs/setup/kubernetes/quick-start-ibm/index.md
Labels: approved, cla: yes, lgtm

#2712 sync latest IBM Cloud change from master to 1.0
  content/docs/setup/kubernetes/quick-start-ibm/index.md
Labels: cla: yes

#2652 Add a user guide for config group-based authorization and list-typed claims authorization
  content/docs/tasks/security/rbac-groups/index.md
Labels: cla: yes, lgtm

#2716 Add logo_link to Wavefront ref docs
  content/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
Labels: cla: yes

#2612 rbac: update concept and reference for RBAC tcp.
  content/docs/concepts/security/index.md
  content/docs/reference/config/authorization/constraints-and-properties/index.md
  content/help/faq/security/does-istio-support-authorization.md
  content/help/ops/security/authorization-restrictive/index.md
Labels: approved, cla: yes

#2710 zh: sync /help/ops/traffic-management/troubleshooting/
  content_zh/help/ops/traffic-management/troubleshooting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2719 zh: sync /help/ops/traffic-management/introduction/index.md
  content_zh/help/ops/traffic-management/introduction/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2723 Add Wavefront by VMware to adapters table
  content/docs/reference/config/policy-and-telemetry/adapters/_index.md
Labels: cla: yes

#2724 Add support for logos in partner components
  content/docs/reference/config/istio.networking.v1alpha3/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/prometheus/index.html
  i18n/en.toml
  layouts/_default/partner-component.html
  src/sass/base/_common.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: cla: yes

#2725 IBM Cloud: switch to the new helm chart location
  content/docs/setup/kubernetes/quick-start-ibm/index.md
Labels: cla: yes, lgtm

#2726 IBM Cloud: switch to the new helm chart location (#2725)
  content/docs/setup/kubernetes/quick-start-ibm/index.md
Labels: cla: yes

#2588 rbac: add rbac tcp task.
  content/blog/2018/istio-authorization/index.md
  content/docs/tasks/security/authz-http/index.md
  content/docs/tasks/security/authz-tcp/index.md
  content/docs/tasks/security/mtls-migration/index.md
Labels: cla: yes

#2728 More context in example fragments
  content/docs/concepts/traffic-management/index.md
Labels: cla: yes

#2740 Fixed #2739
  content_zh/docs/reference/config/policy-and-telemetry/adapters/cloudmonitor/index.md
Labels: cla: yes, translation/chinese

#2736 Clarify task wording
  content/docs/tasks/traffic-management/ingress/index.md
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: cla: yes

#2721 Fix life of a request
  content/help/faq/telemetry/life-of-a-request.md
Labels: cla: yes

#2742 Auto-generate tables of template->adapters and adapter->templates
  README.md
  content/about/contribute/writing-a-new-topic/index.md
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/config/istio.networking.v1alpha3/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content/docs/reference/config/policy-and-telemetry/adapters/circonus/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/cloudwatch/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/datadog/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/denier/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/list/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/memquota/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/opa/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/prometheus/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/rbac/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/redisquota/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/servicecontrol/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/statsd/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/stdio/index.html
  content/docs/reference/config/policy-and-telemetry/templates/_index.md
  content_zh/about/contribute/writing-a-new-topic/index.md
  content_zh/docs/reference/config/policy-and-telemetry/adapters/_index.md
  data/args.yml
  i18n/en.toml
  i18n/zh.toml
  layouts/_default/baseof.html
  layouts/_default/partner-component.html
  layouts/partials/adapter_list.html
  layouts/partials/header.html
  layouts/partials/sidebar-multicard.html
  layouts/partials/template_list.html
  layouts/section-index/list.html
  layouts/shortcodes/adapter_table.html
  layouts/shortcodes/branch_name.html
  layouts/shortcodes/github_blob.html
  layouts/shortcodes/github_file.html
  layouts/shortcodes/github_tree.html
  layouts/shortcodes/source_branch_name.html
  layouts/shortcodes/template_table.html
  layouts/shortcodes/text.html
Labels: cla: yes

#2746 Update to Hugo 0.49
  .circleci/config.yml
  Makefile
  content_zh/_index.md
  netlify.toml
  scripts/Dockerfile
  scripts/gen_site.sh
Labels: cla: yes

#2748 Move inline images to a more sane location.
  assets/inline_images/istio-whitelogo-bluebackground-rounded.svg
  assets/inline_images/landing/istio-logo.svg
  assets/inline_images/landing/policy-enforcement.svg
  assets/inline_images/landing/resiliency.svg
  assets/inline_images/landing/routing-and-load-balancing.svg
  assets/inline_images/landing/telemetry-and-reporting.svg
  layouts/partials/header.html
  layouts/shortcodes/inline_image.html
Labels: cla: yes

#2689 Add open source OIDC providers to security page
  .spelling
  content/docs/concepts/security/index.md
Labels: cla: yes

#2717 zh: sync /docs/tasks/traffic-management/circuit-breaking
  content_zh/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: cla: yes, lgtm, translation/chinese

#2734 zh: sync /docs/setup/kubernetes/quick-start-ibm/index.md
  content_zh/docs/setup/kubernetes/quick-start-ibm/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2718 zh: sync /docs/tasks/traffic-management/mirroring/index.md
  content_zh/docs/tasks/traffic-management/mirroring/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2711 zh: sync /help/ops/component-debugging/index.md
  content_zh/help/ops/component-debugging/index.md
Labels: cla: yes, lgtm, translation/chinese

#2752 Improve spell checking command so we get colorized output.
  .circleci/config.yml
  Makefile
  scripts/lint_site.sh
Labels: cla: yes

#2753 Update reference docs
  content/docs/reference/commands/mixc/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
Labels: cla: yes

#2755 Fix feature status of multicluster mesh
  content/about/feature-stages/index.md
Labels: cla: yes

#2754 Fix typo
  i18n/en.toml
Labels: cla: yes

#2707 zh: sync task authn-policy
  content_zh/docs/tasks/security/authn-policy/index.md
Labels: cla: yes, lgtm, translation/chinese

#2673 zh:reference adapter servicecontrol
  content_zh/docs/reference/config/policy-and-telemetry/adapters/servicecontrol/index.md
Labels: cla: yes, lgtm, translation/chinese

#2760 refs: add Wavefront to adapters list
  content/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes

#2757 feat: reflect option name chage for kubernetes 1.10
  content/docs/setup/kubernetes/platform-setup/aws/index.md
  content_zh/docs/setup/kubernetes/platform-setup/aws/index.md
Labels: cla: yes, needs-ok-to-test

#2749 zh: Translate some strings in i18n
  i18n/zh.toml
Labels: cla: yes, lgtm, translation/chinese

#2756 zh: fix errors in rate limiting
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2720 zh: sync help/faq/telemetry/life-of-a-request.md
  content_zh/help/faq/telemetry/life-of-a-request.md
Labels: cla: yes, lgtm, translation/chinese

#2713 multi-cluster over gateways
  .spelling
  content/docs/examples/multicluster/_index.md
  content/docs/examples/multicluster/gke/index.md
  content/docs/examples/multicluster/icp/index.md
  content/docs/examples/multicluster/iks-icp/index.md
  content/docs/setup/kubernetes/multicluster-install/_index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/multicluster-with-gateways.svg
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
  content/docs/setup/kubernetes/multicluster-install/vpn/multicluster-with-vpn.svg
Labels: cla: no

#2715 Add Kiali Task to istio.io
  content/about/notes/1.1/index.md
  content/about/notes/_index.md
  content/docs/tasks/telemetry/kiali/index.md
  content/docs/tasks/telemetry/kiali/kiali-app.png
  content/docs/tasks/telemetry/kiali/kiali-graph.png
  content/docs/tasks/telemetry/kiali/kiali-overview.png
  content/docs/tasks/telemetry/kiali/kiali-service-graph.png
  content/docs/tasks/telemetry/kiali/kiali-services.png
  content/docs/tasks/telemetry/kiali/kiali-versionedapp.png
  content/docs/tasks/telemetry/kiali/kiali-workload.png
  content/docs/tasks/telemetry/servicegraph/index.md
Labels: cla: yes

#2743 Revise the description of istio-demo
  content/docs/concepts/security/index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes

#2769 There is no chapter for Cloud Foundry
  content/about/feature-stages/index.md
Labels: cla: yes

#2661 zh： content/help/ops/traffic-management/deploy-guidelines
  content_zh/help/ops/traffic-management/deploy-guidelines/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2772 Fix minor typo in multicluster doc
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
Labels: cla: yes, lgtm

#2776 Revert circleci config from 2.1 back to 2
  .circleci/config.yml
  content/docs/setup/kubernetes/platform-setup/aws/index.md
  content_zh/docs/setup/kubernetes/platform-setup/aws/index.md
Labels: cla: yes

#2764 Fix cleanup step
  content/docs/tasks/traffic-management/ingress/index.md
Labels: cla: yes

#2777 Update grab_charts for istio-cni chart.
  scripts/grab_charts.sh
  static/charts/index.yaml
  static/charts/istio-1.1.0.tgz
  static/charts/istio-cni-0.1.0.tgz
  static/charts/istio-remote-1.1.0.tgz
Labels: cla: yes

#2783 Add selector to Gateway example
  content/docs/concepts/traffic-management/index.md
Labels: cla: yes

#2781 Fix logo hover state rotation
  assets/inline_images/istio-whitelogo-bluebackground-rounded.svg
  src/sass/modules/_header.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: cla: yes, needs-ok-to-test

#2786 Clearly indicate which version of k8s we support.
  content/about/contribute/writing-a-new-topic/index.md
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/platform-setup/_index.md
  content/docs/setup/kubernetes/quick-start/index.md
  data/args.yml
  layouts/shortcodes/info_icon.html
  layouts/shortcodes/supported_kubernetes_versions.html
  src/icons/info.svg
  static/img/icons.svg
Labels: cla: yes, lgtm

#2789 Fix 404 of subcharts
  content/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/tasks/telemetry/kiali/index.md
  content/help/ops/telemetry/missing-metrics/index.md
  content_zh/docs/reference/config/policy-and-telemetry/metrics/index.md
  content_zh/docs/setup/kubernetes/helm-install/index.md
  content_zh/help/ops/telemetry/missing-metrics/index.md
Labels: cla: yes

#2792 zh: /docs/tasks/telemetry/kiali
  content_zh/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes, lgtm, translation/chinese

#2767 Instructions apply productpage, but deletes ratings yaml
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes

#2708 Remove extra-config for cert-manager
  content/docs/setup/kubernetes/platform-setup/minikube/index.md
Labels: cla: yes

#2768 zh: sync /about/feature-stages/
  content_zh/about/feature-stages/index.md
Labels: cla: yes, lgtm, translation/chinese

#2750 Update index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes

#2794 fix(content/docs/setup/kubernetes/minimal-install) filename typo
  content/docs/setup/kubernetes/minimal-install/index.md
Labels: cla: no

#2778 zh: Update content_zh/docs/examples/multicluster/_index.md
  content_zh/docs/examples/multicluster/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2683 zh:zh/docs/reference/commands/pilot-discovery
  content_zh/docs/reference/commands/pilot-discovery/index.md
Labels: cla: yes, lgtm, translation/chinese

#2791 Update Task/Enabling rate limits for redisquota
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes

#2785 zh: docs/tasks/security/authz-tcp
  content_zh/docs/tasks/security/authz-tcp/index.md
Labels: cla: yes, lgtm, translation/chinese

#2801 Add reminder to apply destination rules
  content/docs/tasks/traffic-management/request-routing/index.md
Labels: cla: yes, lgtm

#2797 zh: Update _index.md
  content_zh/_index.md
Labels: cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2796 Remove text about istioctl creating routing rules and policy
  content/docs/setup/kubernetes/download-release/index.md
Labels: cla: yes

#2798 Updating Instructions with Latest Ansible Installer
  content/docs/setup/kubernetes/ansible-install/index.md
Labels: approved, cla: yes, lgtm

#2761 rbac: deprecate RbacConfig with ClusterRbacConfig
  .spelling
  content/about/notes/1.1/index.md
  content/docs/concepts/security/index.md
  content/docs/setup/kubernetes/upgrading-istio/index.md
  content/docs/tasks/security/authz-http/index.md
  content/docs/tasks/security/rbac-groups/index.md
  content/help/ops/security/debugging-authorization/index.md
Labels: cla: yes, lgtm

#2806 zh:sync sidecar-injection
  content_zh/docs/setup/kubernetes/sidecar-injection/index.md
Labels: cla: yes, lgtm, translation/chinese

#2805 zh: about/contribute/writing-a-new-topic/index.md
  content_zh/about/contribute/writing-a-new-topic/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2804 zh: Add supported k8s versions
  content_zh/docs/setup/kubernetes/_index.md
  content_zh/docs/setup/kubernetes/platform-setup/_index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2817 Turn on Chinese support
  layouts/partials/header.html
  static/_redirects
Labels: cla: yes, lgtm

#2818 Fix service format
  content/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes, needs-ok-to-test

#1984 Wildcard https egress gateway
  .spelling
  content/docs/examples/advanced-gateways/wildcard-https-egress-gateway/EgressGatewayWithSNIProxy.svg
  content/docs/examples/advanced-gateways/wildcard-https-egress-gateway/index.md
Labels: cla: yes, lgtm

#2807 Add 1.0.3 release notes
  content/about/notes/1.0.3/index.md
  content/blog/2018/announcing-1.0.3/index.md
Labels: cla: yes

#2824 Updating consistency in capitalization
  content/help/ops/setup/webhook/index.md
Labels: cla: yes, needs-ok-to-test

#2823 Improve egress examples
  content/docs/examples/advanced-gateways/_index.md
  content/docs/examples/advanced-gateways/egress-tls-origination/index.md
  content/docs/examples/multicluster/_index.md
Labels: cla: yes, lgtm

#2821 zh: added-istio 1.0.3 release note
  content_zh/about/notes/1.0.3/index.md
Labels: cla: yes, lgtm, translation/chinese

#2808 zh: update content
  content_zh/docs/setup/kubernetes/multicluster-install/index.md
Labels: cla: yes, lgtm, translation/chinese

#2825 fix typo in helm install instructions
  content/docs/setup/kubernetes/helm-install/index.md
Labels: cla: yes, lgtm

#2826 A few more improvements to TLS origination example
  content/docs/examples/advanced-gateways/egress-tls-origination/index.md
  content/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes
