Repository istio/istio.io, pull requests merged in 2018-03, with the labels that each got.

#1048 Notes for 0.6
  _about/notes/0.6.md
Labels: cla-manual

#1112 Fix a small grammar issue
  _docs/concepts/what-is-istio/overview.md
Labels: needs-ok-to-test

#1086 Make non-manifest based installers have similar titles and overviews
  _docs/setup/kubernetes/ansible-install.md
  _docs/setup/kubernetes/helm-install.md
  _docs/setup/kubernetes/quick-start.md
Labels: cla-manual, cla: yes

#1124 Cherrypick #1074 into 0.6.0
  _docs/tasks/telemetry/img/servicegraph-example.png
  _docs/tasks/telemetry/servicegraph.md
Labels: cla: yes

#1117 Fix inconsistent header use in this doc.
  _includes/footer.html
  _includes/header.html
  _layouts/docs.html
  _sass/base/_common.scss
  _sass/base/_constants.scss
  _sass/modules/_header.scss
  index.html
Labels: cla: yes

#1121 Add Istio mTLS support for https service demo
  _docs/tasks/security/https-overlay.md
Labels: cla: yes, lgtm

#1126 Fix more headers.
  _docs/setup/kubernetes/sidecar-injection.md
Labels: cla: yes, lgtm
