Repository istio/istio.io, pull requests merged in 2018-12, with the labels that each got.

#2937 zh: tasks/tcp-traffic-shifting
  content_zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2935 change user group to the newly created
  content_zh/about/community/join/index.md
Labels: approved, cla: yes, lgtm

#2940 Add 1337 uid requirement
  .spelling
  content/docs/setup/kubernetes/spec-requirements/index.md
Labels: cla: yes

#2938 FAQ telemetry: why can't istio implicitly propagate headers
  content/help/faq/telemetry/istio-copy-headers.md
Labels: cla: yes

#2939 FAQ telemetry: requests are not being traced
  content/help/faq/telemetry/no-tracing.md
Labels: cla: yes

#2930 zh:relase-notes-1.0.4
  content_zh/about/notes/1.0.4/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2931 zh:sync notes-1.0.1
  content_zh/about/notes/1.0.1/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2943 zh: update two docs
  content_zh/docs/examples/advanced-gateways/_index.md
  content_zh/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2949 zh:blog-announcing-1.0.4
  content_zh/blog/2018/announcing-1.0.4/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2951 Fix typo in command
  content/docs/tasks/security/mtls-migration/index.md
Labels: approved, cla: yes, lgtm

#2948 Gateway service support externalIps in helm charts #2947
  content/docs/reference/config/installation-options/index.md
  content_zh/docs/reference/config/installation-options/index.md
Labels: approved, cla: yes, lgtm

#2957 fix mc install step
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
Labels: cla: yes, ok-to-test

#2958 fix capitalization
  content/docs/setup/kubernetes/quick-start-ibm/index.md
Labels: cla: yes, ok-to-test

#2956 fix delete CRD step
  content/docs/setup/kubernetes/minimal-install/index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes, ok-to-test

#2941 update kiali screenshots for the kiali task documentation
  content/docs/tasks/telemetry/kiali/index.md
  content/docs/tasks/telemetry/kiali/kiali-overview.png
  content/docs/tasks/telemetry/kiali/kiali-services.png
  content_zh/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes

#2967 Incrementality -> Extensibility
  content/docs/concepts/what-is-istio/index.md
Labels: approved, cla: yes

#2968 Update citadel description
  content/docs/concepts/what-is-istio/index.md
Labels: cla: yes

#2960 An example of configuring access to an external legacy HTTPS proxy
  content/docs/examples/advanced-gateways/http-proxy/index.md
Labels: approved, cla: yes, lgtm

#2974 attribute: document lowercased keys in headers
  content/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/docs/reference/config/policy-and-telemetry/expression-language/index.md
Labels: approved, cla: yes, lgtm

#2884 Add initial doc changes related to tracing provider and support for z…
  content/about/feature-stages/index.md
  content/about/notes/1.0.3/index.md
  content/docs/concepts/what-is-istio/index.md
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/tasks/telemetry/distributed-tracing/_index.md
  content/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
  content/docs/tasks/telemetry/distributed-tracing/jaeger/istio-tracing-details.png
  content/docs/tasks/telemetry/distributed-tracing/jaeger/istio-tracing-list.png
  content/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
  content/docs/tasks/telemetry/distributed-tracing/lightstep/istio-tracing-details-lightstep.png
  content/docs/tasks/telemetry/distributed-tracing/lightstep/istio-tracing-list-lightstep.png
  content/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content/docs/tasks/telemetry/distributed-tracing/zipkin/index.md
  content/docs/tasks/telemetry/distributed-tracing/zipkin/istio-tracing-details-zipkin.png
  content/docs/tasks/telemetry/distributed-tracing/zipkin/istio-tracing-list-zipkin.png
  content_zh/docs/tasks/telemetry/distributed-tracing/index.md
Labels: approved, cla: yes, lgtm

#2986 Fix typo: alicloud->alibaba cloud
  content/docs/reference/config/policy-and-telemetry/adapters/cloudmonitor/index.html
  content/docs/setup/kubernetes/quick-start-alicloud-ack/index.md
Labels: cla: yes, needs-ok-to-test

#2989 Fix CI errors.
  content/about/contribute/style-guide/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/concepts/what-is-istio/index.md
  content/docs/examples/advanced-gateways/http-proxy/index.md
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixc/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/istio.networking.v1alpha3/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/cloudmonitor/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/docs/reference/config/policy-and-telemetry/templates/edge/index.html
  content/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
  content/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content/docs/tasks/telemetry/kiali/index.md
  content/help/faq/telemetry/disabling-zipkin.md
  content/help/faq/telemetry/istio-copy-headers.md
  content/help/faq/telemetry/no-tracing.md
  content_zh/about/contribute/style-guide/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/reference/config/istio.networking.v1alpha3/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing-lightstep/index.md
  content_zh/docs/tasks/telemetry/kiali/index.md
  scripts/grab_reference_docs.sh
  static/js/all.min.js.map
Labels: approved, cla: yes, lgtm

#2945 Improve `curl` command for testing the application
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm

#2990 zh: sync with the English docs
  content_zh/docs/setup/kubernetes/minimal-install/index.md
  content_zh/docs/setup/kubernetes/spec-requirements/index.md
  content_zh/docs/tasks/security/authn-policy/index.md
  content_zh/docs/tasks/telemetry/tcp-metrics/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2988 #2987 Issue with doc /docs/tasks/telemetry/kiali/
  content/docs/tasks/telemetry/kiali/index.md
  content_zh/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes

#2970 Document browser connection reuse problem
  content/help/ops/traffic-management/deploy-guidelines/index.md
Labels: approved, cla: yes

#2993 zh: sync 3 docs with English version
  content_zh/about/notes/0.8/index.md
  content_zh/docs/examples/multicluster/gke/index.md
  content_zh/docs/setup/kubernetes/download-release/index.md
  content_zh/docs/setup/kubernetes/platform-setup/minikube/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2973 Improve the HTTPS proxy example
  content/docs/examples/advanced-gateways/http-proxy/index.md
Labels: approved, cla: yes, lgtm

#2866 Correct telemetry for Prometheus doc
  content/docs/tasks/telemetry/querying-metrics/index.md
  content_zh/docs/tasks/telemetry/metrics-logs/index.md
  content_zh/docs/tasks/telemetry/querying-metrics/index.md
  content_zh/docs/tasks/telemetry/tcp-metrics/index.md
Labels: cla: yes, lgtm

#2965 add more protocol
  content/docs/setup/kubernetes/spec-requirements/index.md
  content/help/faq/traffic-management/naming-port-convention.md
  content_zh/docs/setup/kubernetes/spec-requirements/index.md
  content_zh/help/faq/traffic-management/naming-port-convention.md
Labels: cla: yes

#2999 zh: sync with the English docs
  content_zh/about/contribute/writing-a-new-topic/index.md
  content_zh/about/notes/1.0.3/index.md
  content_zh/about/security-vulnerabilities/index.md
  content_zh/docs/examples/multicluster/icp/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/tasks/traffic-management/request-routing/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3000 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/istio.networking.v1alpha3/index.html
Labels: approved, cla: yes

#2969 zh: content_zh/blog/2018/egress-mongo/index.md
  content_zh/blog/2018/egress-mongo/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3003 Release notes for 1.0.5
  content/about/notes/1.0.5/index.md
  content/blog/2018/announcing-1.0.5/index.md
Labels: approved, cla: yes, lgtm

#3005 Add support for boilerplate text.
  .spelling
  boilerplates/en/example.md
  content/about/contribute/writing-a-new-topic/index.md
  layouts/shortcodes/boilerplate.html
Labels: approved, cla: yes
