Repository istio/istio.io, pull requests merged in 2019-01, with the labels that each got.

#3012 Fix the typo on the secure ingress page
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: cla: yes, ok-to-test

#3016 move helm update instructions before helm template and helm install
  content/docs/setup/kubernetes/helm-install/index.md
Labels: cla: yes

#3017 add targetAverageUtilization to deployment of egress gateway with SNI proxy
  content/blog/2018/egress-mongo/index.md
Labels: cla: yes

#3010 Updates for DM installer for 1.1 part2
  content/docs/setup/kubernetes/quick-start-gke-dm/dm_kiali.png
  content/docs/setup/kubernetes/quick-start-gke-dm/dm_kubernetes_workloads.png
  content/docs/setup/kubernetes/quick-start-gke-dm/dm_launcher.png
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
Labels: cla: yes

#3019 Improve boilerplates so they can now contain shortcodes
  .spelling
  boilerplates/en/example.md
  content/about/contribute/writing-a-new-topic/index.md
  content/boilerplates/example.md
  content/boilerplates/index.md
  layouts/shortcodes/boilerplate.html
Labels: approved, cla: yes

#3008 zh: sync 4 docs
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
  content_zh/docs/examples/bookinfo/index.md
  content_zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content_zh/help/faq/general/why-use-istio.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2971 zh: add content_zh/help/faq/telemetry/no-tracing.md
  content_zh/help/faq/telemetry/no-tracing.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3024 zh: fix an error on checkversion-rule.yaml
  content_zh/docs/tasks/policy-enforcement/denial-and-list/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2954 zh: add help/faq/telemetry/istio-copy-headers.md
  content_zh/help/faq/telemetry/istio-copy-headers.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3023 zh: update content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/concepts/traffic-management/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#3021 Simplify use of the image shortcode.
  content/about/contribute/writing-a-new-topic/index.md
  content/blog/2017/0.1-announcement/index.md
  content/blog/2017/0.1-auth/index.md
  content/blog/2017/mixer-spof-myth/index.md
  content/blog/2018/aws-nlb/index.md
  content/blog/2018/delayering-istio/delayering-istio.md
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-mongo/index.md
  content/blog/2018/egress-tcp/index.md
  content/blog/2018/export-logs-through-stackdriver/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/docs/concepts/performance-and-scalability/index.md
  content/docs/concepts/policies-and-telemetry/index.md
  content/docs/concepts/security/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/examples/integrating-vms/index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
  content/docs/setup/kubernetes/platform-setup/alicloud/index.md
  content/docs/setup/kubernetes/platform-setup/docker-for-desktop/index.md
  content/docs/setup/kubernetes/quick-start-alicloud-ack/index.md
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/setup/kubernetes/quick-start-ibm/index.md
  content/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
  content/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
  content/docs/tasks/telemetry/distributed-tracing/zipkin/index.md
  content/docs/tasks/telemetry/kiali/index.md
  content/docs/tasks/telemetry/querying-metrics/index.md
  content/docs/tasks/telemetry/tcp-metrics/index.md
  content/docs/tasks/telemetry/using-istio-dashboard/index.md
  content/help/ops/controlz/index.md
  content_zh/blog/2017/0.1-announcement/index.md
  content_zh/blog/2017/0.1-auth/index.md
  content_zh/blog/2017/mixer-spof-myth/index.md
  content_zh/blog/2018/aws-nlb/index.md
  content_zh/blog/2018/delayering-istio/delayering-istio.md
  content_zh/blog/2018/egress-https/index.md
  content_zh/blog/2018/egress-mongo/index.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/blog/2018/export-logs-through-stackdriver/index.md
  content_zh/docs/concepts/performance-and-scalability/index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content_zh/docs/setup/kubernetes/multicluster-install/gateways/index.md
  content_zh/docs/setup/kubernetes/multicluster-install/vpn/index.md
  content_zh/docs/setup/kubernetes/platform-setup/alicloud/index.md
  content_zh/docs/setup/kubernetes/platform-setup/docker-for-desktop/index.md
  content_zh/docs/setup/kubernetes/quick-start-alicloud-ack/index.md
  content_zh/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content_zh/docs/setup/kubernetes/quick-start-ibm/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing-lightstep/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/index.md
  content_zh/docs/tasks/telemetry/kiali/index.md
  content_zh/docs/tasks/telemetry/querying-metrics/index.md
  content_zh/docs/tasks/telemetry/tcp-metrics/index.md
  content_zh/docs/tasks/telemetry/using-istio-dashboard/index.md
  content_zh/help/ops/controlz/index.md
  layouts/shortcodes/image.html
Labels: approved, cla: yes

#3015 Allow the site static content to be built on netlify
  .gitignore
  package-lock.json
  package.json
  scripts/Dockerfile
  scripts/build_site.sh
Labels: approved, cla: yes, lgtm

#3022 Replace before you begin egress with boilerplate
  content/boilerplates/before-you-begin-egress.md
  content/docs/examples/advanced-gateways/egress-gateway/index.md
  content/docs/examples/advanced-gateways/http-proxy/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3020 Remove GCP DM Quickstart servicegraph Image for 1.1
  content/docs/setup/kubernetes/quick-start-gke-dm/dm_servicegraph.png
Labels: approved, cla: yes, lgtm

#3011 Add info about grafana add-on
  .spelling
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/tasks/telemetry/using-istio-dashboard/index.md
Labels: approved, cla: yes, lgtm

#3013 Update index.md
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3018 replace the statistics of Envoy with Envoy's log for TCP
  content/blog/2018/egress-mongo/index.md
  content/docs/examples/advanced-gateways/egress-gateway/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
Labels: approved, cla: yes, lgtm

#3009 zh: fix link issues for chinese documents
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/examples/advanced-gateways/egress-gateway/index.md
  content_zh/docs/examples/advanced-gateways/egress-tls-origination/index.md
  content_zh/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content_zh/docs/examples/bookinfo/index.md
  content_zh/docs/reference/config/policy-and-telemetry/adapters/fluentd/index.md
  content_zh/docs/reference/config/policy-and-telemetry/metrics/index.md
  content_zh/docs/reference/config/policy-and-telemetry/templates/authorization/index.md
  content_zh/docs/reference/config/policy-and-telemetry/templates/servicecontrolreport/index.md
  content_zh/docs/setup/kubernetes/ansible-install/index.md
  content_zh/docs/setup/kubernetes/multicluster-install/gateways/index.md
  content_zh/docs/setup/kubernetes/upgrading-istio/index.md
  content_zh/docs/tasks/policy-enforcement/denial-and-list/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/tasks/security/mtls-migration/index.md
  content_zh/docs/tasks/security/role-based-access-control/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing-lightstep/index.md
  content_zh/docs/tasks/traffic-management/circuit-breaking/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
  content_zh/docs/tasks/traffic-management/request-routing/index.md
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
  content_zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3027 zh: content_zh/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#3030 zh: add content_zh/help/faq/general/how-to-join-slack.md
  content_zh/help/faq/general/how-to-join-slack.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#2679 zh: content/docs/reference/config/policy-and-telemetry/adapters/sign…
  content_zh/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3032 zh: content/docs/reference/config/policy-and-telemetry/templates/_index
  content_zh/docs/reference/config/policy-and-telemetry/templates/_index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#3007 zh: content_zh/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/overview/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2991 Multicluster concept doc
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/concepts/multicluster-deployments/multicluster-split-horizon-eds.svg
  content/docs/concepts/multicluster-deployments/multicluster-with-gateways.svg
  content/docs/concepts/multicluster-deployments/multicluster-with-vpn.svg
  content/docs/setup/kubernetes/multicluster-install/_index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
Labels: approved, cla: yes, do-not-merge/hold

#3026 Fix GKE cluster create command (platform setup)
  content/docs/setup/kubernetes/platform-setup/gke/index.md
Labels: approved, cla: yes, lgtm

#3033 Add OCI platform setup to documentation
  content/docs/setup/kubernetes/platform-setup/oci/index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: approved, cla: yes, lgtm

#3031 zh: update content_zh/docs/concepts/security/index.md
  content_zh/docs/concepts/security/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3038 fix typo
  content_zh/docs/tasks/security/mtls-migration/index.md
Labels: approved, cla: yes, lgtm, ok-to-test

#3036 zh: update docs/concepts/security/index.md
  content_zh/docs/concepts/security/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3041 zh: update traffic-shifting and tcp-traffic-shifting
  content_zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content_zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3043 zh: fixed: telemetry/distributed-tracing-lightstep->telemetry/distributed…
  content_zh/about/feature-stages/index.md
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/_index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content_zh/help/faq/_index.md
  content_zh/help/faq/telemetry/controlling-what-the-sidecar-reports.md
  content_zh/help/faq/telemetry/disabling-zipkin.md
  content_zh/help/faq/telemetry/index.md
  content_zh/help/faq/telemetry/initial-zipkin-header.md
  content_zh/help/faq/telemetry/istio-copy-headers.md
  content_zh/help/faq/telemetry/zipkin-and-x-request-id.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2916 An example for configuring and verifying split horizon EDS
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/examples/multicluster/_index.md
  content/docs/examples/multicluster/split-horizon-eds/diagram.svg
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes, lgtm

#3034 add OCI OKE to platform setup section of docs
  content/docs/setup/kubernetes/platform-setup/aws/index.md
  content/docs/setup/kubernetes/platform-setup/azure/index.md
  content/docs/setup/kubernetes/platform-setup/gke/index.md
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
  content/docs/setup/kubernetes/platform-setup/minikube/index.md
  content/docs/setup/kubernetes/platform-setup/oci/index.md
  content/docs/setup/kubernetes/platform-setup/openshift/index.md
  content/docs/setup/kubernetes/quick-start/index.md
Labels: cla: yes

#3050 shift platform page weights to maintain alphabetized sidebar
  content/docs/setup/kubernetes/platform-setup/aws/index.md
  content/docs/setup/kubernetes/platform-setup/azure/index.md
  content/docs/setup/kubernetes/platform-setup/docker-for-desktop/index.md
  content/docs/setup/kubernetes/platform-setup/gke/index.md
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
  content/docs/setup/kubernetes/platform-setup/minikube/index.md
  content/docs/setup/kubernetes/platform-setup/oci/index.md
  content/docs/setup/kubernetes/platform-setup/openshift/index.md
Labels: approved, cla: yes, lgtm

#3046 New option: Let linter ignore the external links
  Makefile
  README.md
  scripts/lint_site.sh
Labels: approved, cla: yes, kind/site infra, lgtm

#2891 Specify the requirement for the NET_ADMIN capability
  content/docs/setup/kubernetes/spec-requirements/index.md
  content/help/ops/setup/required-pod-capabilities/index.md
Labels: approved, cla: yes, lgtm

#2964 add istioctl inject
  content/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
Labels: approved, cla: yes, lgtm

#3047 zh: update docs/tasks/traffic-management/egress/index.md, etc
  content_zh/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/mirroring/index.md
  content_zh/docs/tasks/traffic-management/secure-ingress/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3054 zh: update authn-policy/index.md and mutual-tls/index.md
  content_zh/docs/tasks/security/authn-policy/index.md
  content_zh/docs/tasks/security/mutual-tls/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#3052 zh: content_zh/docs/tasks/security/rbac-group
  content_zh/docs/tasks/security/rbac-groups/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#3059 Multicluster examples improvements
  content/docs/examples/advanced-gateways/_index.md
  content/docs/examples/multicluster/gke/index.md
  content/docs/examples/multicluster/icp/index.md
  content/docs/examples/multicluster/iks-icp/index.md
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes

#3064 simplify the platform setup notes in helm install
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes, lgtm, ok-to-test

#3049 zh: update /content/docs/examples/advanced-gateways/http-proxy/index.md
  content_zh/docs/examples/advanced-gateways/http-proxy/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3069 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/istio.networking.v1alpha3/index.html
  content/docs/reference/config/policy-and-telemetry/templates/listentry/index.html
  data/args.yml
Labels: approved, cla: yes

#3060 Organize the setup/kubernetes sidebar
  content/docs/setup/kubernetes/advanced-install/index.md
  content/docs/setup/kubernetes/ansible-install/index.md
  content/docs/setup/kubernetes/download-release/index.md
  content/docs/setup/kubernetes/helm-install/index.md
  content/docs/setup/kubernetes/mesh-expansion/index.md
  content/docs/setup/kubernetes/minimal-install/index.md
  content/docs/setup/kubernetes/multicluster-install/_index.md
  content/docs/setup/kubernetes/platform-setup/_index.md
  content/docs/setup/kubernetes/quick-start-alicloud-ack/index.md
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/setup/kubernetes/quick-start-ibm/index.md
  content/docs/setup/kubernetes/quick-start/index.md
  content/docs/setup/kubernetes/sidecar-injection/index.md
  content/docs/setup/kubernetes/spec-requirements/index.md
  content/docs/setup/kubernetes/upgrading-istio/index.md
Labels: approved, cla: yes, lgtm

#3067 No need to specify namespace in kubectl apply
  content/docs/setup/kubernetes/sidecar-injection/index.md
  content/docs/setup/kubernetes/upgrading-istio/index.md
  content_zh/docs/setup/kubernetes/quick-start/index.md
  content_zh/docs/setup/kubernetes/sidecar-injection/index.md
  content_zh/docs/setup/kubernetes/upgrading-istio/index.md
Labels: approved, cla: yes, lgtm

#3062 [Kiali] [Istio 1.0] add kiali task to the release 1.0 docs
  content/docs/tasks/telemetry/kiali/index.md
  content/docs/tasks/telemetry/kiali/kiali-app.png
  content/docs/tasks/telemetry/kiali/kiali-graph.png
  content/docs/tasks/telemetry/kiali/kiali-overview.png
  content/docs/tasks/telemetry/kiali/kiali-service-graph.png
  content/docs/tasks/telemetry/kiali/kiali-services.png
  content/docs/tasks/telemetry/kiali/kiali-versionedapp.png
  content/docs/tasks/telemetry/kiali/kiali-workload.png
Labels: cla: yes

#3057 Updated mesh expansion guide
  content/docs/setup/kubernetes/mesh-expansion/index.md
Labels: approved, cla: yes, lgtm

#3066 zh: update docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3042 zh: update docs/tasks/traffic-management/ingress/index.md
  content_zh/docs/tasks/traffic-management/ingress/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3040 zh: update docs/tasks/traffic-management/fault-injection/index.md
  content_zh/docs/tasks/traffic-management/fault-injection/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3071 Switch to discuss.istio.io
  .spelling
  content/about/community/join/discourse.svg
  content/about/community/join/index.md
  content/about/community/join/mailing-list.svg
  content/about/community/join/rocket-chat.svg
  content/blog/2017/0.1-announcement/index.md
  content/blog/2019/_index.md
  content/blog/2019/announcing-discuss.istio.io/index.md
  content/help/ops/security/debugging-authorization/index.md
  content_zh/about/community/join/index.md
  content_zh/help/ops/security/debugging-authorization/index.md
  data/args.yml
  i18n/en.toml
  i18n/zh.toml
  layouts/partials/footer.html
  src/icons/discourse.svg
  src/icons/mailing-list.svg
  src/icons/rocket-chat.svg
  static/img/icons.svg
Labels: approved, cla: yes

#3073 zh: update docs/setup/kubernetes/upgrading-istio/index.md
  content_zh/docs/setup/kubernetes/upgrading-istio/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3076 Add blog entry blog post for custom ingress gateway with cert manager…
  content/blog/2019/custom-ingress-gateway/deployment-custom-ingress.yaml
  content/blog/2019/custom-ingress-gateway/index.md
Labels: approved, cla: no

#3051 update permissive resp code value due to envoy change
  content/docs/tasks/security/authz-http/index.md
Labels: approved, cla: yes, lgtm

#3077 Multicluster via gateways example
  content/docs/examples/multicluster/gateways/index.md
  content/docs/examples/multicluster/split-horizon-eds/index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
Labels: approved, cla: yes, lgtm

#2928 [Blog post] Sidestepping dependency ordering with AppSwitch
  .spelling
  content/blog/2019/appswitch/index.md
Labels: approved, cla: yes, lgtm

#3079 zh: switch to discuss.istio.io
  content_zh/_index.md
  content_zh/about/community/join/index.md
  content_zh/about/contribute/terms/index.md
  content_zh/about/feature-stages/index.md
  content_zh/about/notes/0.2/index.md
  content_zh/about/notes/1.0.3/index.md
  content_zh/blog/2017/0.1-announcement/index.md
  content_zh/blog/2018/delayering-istio/delayering-istio.md
  content_zh/blog/2018/hp/index.md
  content_zh/blog/2019/_index.md
  content_zh/blog/2019/announcing-discuss.istio.io/index.md
  content_zh/docs/concepts/performance-and-scalability/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/examples/intelligent-routing/index.md
  content_zh/docs/examples/telemetry/index.md
  content_zh/docs/reference/commands/istio_ca/index.md
  content_zh/docs/reference/commands/mixc/index.md
  content_zh/docs/reference/commands/mixs/index.md
  content_zh/docs/reference/commands/node_agent/index.md
  content_zh/docs/reference/config/istio.networking.v1alpha3/index.md
  content_zh/docs/reference/config/policy-and-telemetry/templates/tracespan/index.md
  content_zh/docs/setup/kubernetes/advanced-install/index.md
  content_zh/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content_zh/docs/setup/kubernetes/spec-requirements/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/_index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
  content_zh/help/faq/general/what-is-istio.md
  content_zh/help/faq/mixer/mixer-self-monitoring.md
  content_zh/help/faq/telemetry/disabling-zipkin.md
  content_zh/help/faq/telemetry/life-of-a-request.md
  content_zh/help/ops/component-logging/index.md
  content_zh/help/ops/security/debugging-authorization/index.md
  content_zh/help/ops/traffic-management/observing/index.md
  content_zh/help/ops/traffic-management/proxy-cmd/index.md
  i18n/zh.toml
Labels: approved, cla: yes, lgtm, translation/chinese

#3075 Add egress sni monitoring policies example
  content/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies/index.md
Labels: approved, cla: yes, lgtm

#3082 [Blog post] Sidestepping dependency ordering with AppSwitch (#2928)
  .spelling
  content/blog/2019/appswitch/index.md
Labels: approved, cla: no

#3084 Missing Space
  content/docs/setup/kubernetes/platform-setup/aws/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3058 Update egress gateway configuration for wildcard hosts with SNI handling filters
  content/blog/2018/egress-mongo/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
Labels: approved, cla: yes, lgtm

#3086 Add IP-based white/blacklisting instructions to the task.
  content/docs/tasks/policy-enforcement/denial-and-list/index.md
Labels: approved, cla: yes

#3088 Updated reference docs.
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/docs/reference/config/istio.networking.v1alpha3/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/cloudwatch/index.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
Labels: approved, cla: yes

#3085 Multicluster gateways uninstall instructions
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
Labels: approved, cla: yes, lgtm

#3091 Fix incorrect favicon dimensions.
  layouts/_default/baseof.html
  static/favicons/android-96x96.png
Labels: approved, cla: yes

#2774 zh: content_zh/about/notes/1.1/index.md
  content_zh/about/notes/1.1/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3092 Fix a few issues.
  content/about/community/join/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/examples/multicluster/gke/index.md
  content/docs/examples/multicluster/icp/index.md
  content/docs/examples/multicluster/iks-icp/index.md
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
  content_zh/docs/setup/kubernetes/multicluster-install/vpn/index.md
  src/sass/layouts/_blog.scss
  static/css/dark_theme_archive.css
  static/css/dark_theme_archive.css.map
  static/css/dark_theme_normal.css
  static/css/dark_theme_normal.css.map
  static/css/dark_theme_preliminary.css
  static/css/dark_theme_preliminary.css.map
  static/css/light_theme_archive.css
  static/css/light_theme_archive.css.map
  static/css/light_theme_normal.css
  static/css/light_theme_normal.css.map
  static/css/light_theme_preliminary.css
  static/css/light_theme_preliminary.css.map
Labels: approved, cla: yes

#3095 issue 3094 - update reference doc for kiali defaults
  content/docs/reference/config/installation-options/index.md
Labels: approved, cla: yes, lgtm

#3096 use -l options directly in kubectl logs
  content/blog/2018/egress-mongo/index.md
  content/docs/examples/advanced-gateways/egress-gateway-tls-origination/index.md
  content/docs/examples/advanced-gateways/egress-gateway/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content_zh/blog/2018/egress-mongo/index.md
  content_zh/docs/examples/advanced-gateways/egress-gateway-mtls-origination/index.md
  content_zh/docs/examples/advanced-gateways/egress-gateway/index.md
  content_zh/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
Labels: cla: yes, lgtm

#2980 Add a review process to our contribution guide.
  content/about/contribute/github/index.md
Labels: approved, cla: yes, lgtm

#3097 Update aws NLB blog with correct instructions
  content/blog/2018/aws-nlb/index.md
Labels: approved, cla: yes, lgtm

#3063 Updates multicluster gateway doc to support node ports
  content/docs/examples/multicluster/gateways/index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
Labels: approved, cla: yes, lgtm

#3090 documentation for enable/use SDS in 1.1
  content/docs/concepts/security/index.md
  content/docs/tasks/security/auth-sds/index.md
Labels: approved, cla: yes, lgtm

#2966 zh:Update set up consul
  content_zh/docs/setup/consul/install/index.md
  content_zh/docs/setup/consul/quick-start/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3103 curl kubeapiserver shell error.
  content/docs/tasks/security/authn-policy/index.md
Labels: cla: yes

#3099 Add the formal process to become a member of an Istio repo.
  content/about/contribute/github/index.md
Labels: approved, cla: yes, lgtm

#3098 Add a user guide for Istio Vault CA integration
  content/docs/tasks/security/vault-ca/index.md
Labels: approved, cla: yes, lgtm

#3105 Fix a URL in the user guide for Istio Vault CA
  content/docs/tasks/security/vault-ca/index.md
Labels: approved, cla: yes, lgtm

#2902 Add new setup instructions about istio-cni
  content/about/feature-stages/index.md
  content/docs/setup/kubernetes/istio-cni-install/index.md
  content/docs/setup/kubernetes/platform-setup/gke/index.md
Labels: approved, cla: yes, lgtm

#3108 Fix a bunch of capitalization and spacing errors.
  .spelling
  content/blog/2018/export-logs-through-stackdriver/index.md
  content/blog/2018/soft-multitenancy/index.md
  content/blog/2019/custom-ingress-gateway/index.md
  content/docs/concepts/performance-and-scalability/index.md
  content/docs/examples/advanced-gateways/http-proxy/index.md
  content/docs/setup/consul/quick-start/index.md
  content/docs/setup/kubernetes/multicluster-install/_index.md
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
  content/docs/setup/kubernetes/multicluster-install/vpn/index.md
  content/docs/setup/kubernetes/platform-setup/docker-for-desktop/index.md
  content/docs/setup/kubernetes/sidecar-injection/index.md
  content/docs/tasks/policy-enforcement/denial-and-list/index.md
  content/docs/tasks/security/auth-sds/index.md
  content/docs/tasks/security/authz-http/index.md
  content/docs/tasks/security/authz-tcp/index.md
  content/docs/tasks/security/health-check/index.md
  content/docs/tasks/security/plugin-ca-cert/index.md
  content/docs/tasks/security/rbac-groups/index.md
  content/help/glossary/service-registry.md
  content/help/ops/misc/index.md
  content/help/ops/setup/validation/index.md
  content_zh/docs/reference/commands/mixs/index.md
  content_zh/help/glossary/service-registry.md
Labels: approved, cla: yes

#3102 fix from non-Istio services to Istio service
  content/docs/tasks/security/authn-policy/index.md
Labels: approved, cla: yes, lgtm

#3109 Updates to the Split Horizon EDS example
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes, lgtm

#3110 Update helm installation doc to separate the CRDs deployment step.
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes, lgtm

#3117 Minor changes following #3109
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes, lgtm

#3115 add Security note to egress traffic control task
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3112 clarify secure ingress gateway troubleshooting regarding killing the pod to reload certificates
  content/docs/tasks/traffic-management/secure-ingress/index.md
Labels: approved, cla: yes, lgtm

#3106 Add attribute-based cleanup commands.
  content/docs/tasks/policy-enforcement/denial-and-list/index.md
Labels: approved, cla: yes, lgtm

#3119 zh: replace host with hosts
  content_zh/docs/concepts/traffic-management/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3123 make the test curl command for bookinfo clearer
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm

#3121 add a security note to egress traffic task, to istio 1.0
  content/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes

#3118 Multicluster example improvements
  content/docs/examples/multicluster/gateways/index.md
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes, lgtm

#3126 Correcting the IP ranges used in IKS
  content/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3130 Correcting IP Range
  content/docs/tasks/traffic-management/egress/index.md
  content_zh/docs/tasks/traffic-management/egress/index.md
Labels: cla: yes, lgtm

#2998 Add prometheus application metrics faq entry
  content/help/faq/telemetry/prometheus-application-metrics.md
Labels: approved, cla: yes, lgtm

#3125 add a step to confirm that Bookinfo is running without ingress
  content/blog/2018/egress-https/index.md
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm

#3127 Clarify IP choice for global services
  .spelling
  content/docs/examples/multicluster/gateways/index.md
Labels: approved, cla: yes, lgtm

#3134 remove duplicate install
  content/docs/setup/kubernetes/helm-install/index.md
Labels: approved, cla: yes, lgtm

#3135 Install CRDs in multicluster instructions
  content/docs/setup/kubernetes/multicluster-install/gateways/index.md
Labels: approved, cla: yes, lgtm

#3136 Generalize handling of text blocks with <<EOF syntax.
  layouts/shortcodes/text.html
Labels: approved, cla: yes, lgtm

#3142 Remove stale references to Rocket Chat.
  content/_index.md
  content/blog/2018/announcing-1.0/index.md
  content/help/faq/general/how-to-join-slack.md
  content_zh/_index.md
  content_zh/help/faq/general/how-to-join-slack.md
  static/img/logo.png
Labels: approved, cla: yes

#3129 zh: update /help/ops/setup/webhook/index.md
  content_zh/help/ops/setup/webhook/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#2997 Initial Distributed Tracing FAQ section
  .spelling
  content/help/faq/distributed-tracing/control-sampling.md
  content/help/faq/distributed-tracing/disabling-tracing.md
  content/help/faq/distributed-tracing/external-zipkin.md
  content/help/faq/distributed-tracing/how-distributed-tracing-works.md
  content/help/faq/distributed-tracing/how-envoy-based-tracing-works.md
  content/help/faq/distributed-tracing/how-mixer-based-tracing-works.md
  content/help/faq/distributed-tracing/how-to-support-tracing.md
  content/help/faq/distributed-tracing/index.md
  content/help/faq/distributed-tracing/initial-zipkin-header.md
  content/help/faq/distributed-tracing/istio-copy-headers.md
  content/help/faq/distributed-tracing/minimal-requirements.md
  content/help/faq/distributed-tracing/mixer-role.md
  content/help/faq/distributed-tracing/no-tracing.md
  content/help/faq/distributed-tracing/vert.x.md
  content/help/faq/distributed-tracing/why-mixer-spans.md
  content/help/faq/metrics-and-logs/accessing-telemetry-via-rest.md
  content/help/faq/metrics-and-logs/controlling-what-the-sidecar-reports.md
  content/help/faq/metrics-and-logs/index.md
  content/help/faq/metrics-and-logs/life-of-a-request.md
  content/help/faq/metrics-and-logs/prometheus-for-non-k8s.md
  content/help/faq/telemetry/external-zipkin.md
  content/help/faq/telemetry/index.md
  content/help/faq/telemetry/initial-zipkin-header.md
  content/help/faq/telemetry/zipkin-and-x-request-id.md
Labels: approved, cla: yes, lgtm

#3148 Update the authoring guide.
  content/about/contribute/creating-and-editing-pages/index.md
Labels: approved, cla: yes

#3155 added GCP and CNI into .spelling
  .spelling
Labels: cla: yes, kind/docs

#3164 Moved a stray FAQ file.
  content/help/faq/metrics-and-logs/prometheus-application-metrics.md
Labels: approved, cla: no

#3166 Update the Creating and Editing pages guide.
  content/about/contribute/creating-and-editing-pages/index.md
Labels: approved, cla: yes

#3168 Add containerPort requirement documentation
  content/docs/setup/kubernetes/spec-requirements/index.md
Labels: approved, cla: yes, lgtm

#3172 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/istio.networking.v1alpha3/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/servicecontrol/index.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/docs/reference/config/policy-and-telemetry/templates/servicecontrolreport/index.html
Labels: approved, cla: yes

#3149 Deprecate Deployment Manager install, point to Istio on GKE
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/setup/kubernetes/quick-start-gke/dm-tracing.png
  content/docs/setup/kubernetes/quick-start-gke/dm_bookinfo.png
  content/docs/setup/kubernetes/quick-start-gke/dm_gcp_iam.png
  content/docs/setup/kubernetes/quick-start-gke/dm_gcp_iam_role.png
  content/docs/setup/kubernetes/quick-start-gke/dm_grafana.png
  content/docs/setup/kubernetes/quick-start-gke/dm_kiali.png
  content/docs/setup/kubernetes/quick-start-gke/dm_kubernetes_workloads.png
  content/docs/setup/kubernetes/quick-start-gke/dm_launcher.png
  content/docs/setup/kubernetes/quick-start-gke/dm_prometheus.png
  content/docs/setup/kubernetes/quick-start-gke/index.md
  content_zh/docs/setup/kubernetes/quick-start-gke-dm/index.md
Labels: approved, cla: yes, lgtm

#2961 Document the liveness health check rewrite.
  content/help/faq/security/k8s-health-checks.md
  content/help/ops/setup/app-health-check/index.md
Labels: cla: yes

#3175 Replace deployment manager with Istio on GKE
  content/docs/setup/kubernetes/quick-start-gke-dm/index.md
  content/docs/setup/kubernetes/quick-start-gke/dm-tracing.png
  content/docs/setup/kubernetes/quick-start-gke/dm_bookinfo.png
  content/docs/setup/kubernetes/quick-start-gke/dm_gcp_iam.png
  content/docs/setup/kubernetes/quick-start-gke/dm_gcp_iam_role.png
  content/docs/setup/kubernetes/quick-start-gke/dm_grafana.png
  content/docs/setup/kubernetes/quick-start-gke/dm_kiali.png
  content/docs/setup/kubernetes/quick-start-gke/dm_kubernetes_workloads.png
  content/docs/setup/kubernetes/quick-start-gke/dm_launcher.png
  content/docs/setup/kubernetes/quick-start-gke/dm_prometheus.png
  content/docs/setup/kubernetes/quick-start-gke/dm_servicegraph.png
  content/docs/setup/kubernetes/quick-start-gke/index.md
  content_zh/docs/setup/kubernetes/quick-start-gke-dm/index.md
Labels: cla: yes

#3177 Add image ratio
  content/docs/setup/kubernetes/quick-start-gke/index.md
Labels: cla: yes

#2978 Egress gateway performance blog
  content/blog/2019/egress-performance/acmeair_regpatrol3.png
  content/blog/2019/egress-performance/case1_sidecar_bypass3.png
  content/blog/2019/egress-performance/case2_sidecar_passthru3.png
  content/blog/2019/egress-performance/case3_egressgw3.png
  content/blog/2019/egress-performance/case4_egressgw_mtls3.png
  content/blog/2019/egress-performance/case5_egressgw_sni_proxy3.png
  content/blog/2019/egress-performance/cpu_usage3.png
  content/blog/2019/egress-performance/index.md
  content/blog/2019/egress-performance/response_times3.png
  content/blog/2019/egress-performance/throughput3.png
Labels: approved, cla: yes, lgtm, ok-to-test

#3171 Remove progress bars from curl (occuring on Mac)
  content/docs/examples/bookinfo/index.md
Labels: cla: yes, ok-to-test

#2984 Blog Content: Demystifying Istio's Sidecar Injection Model
  content/blog/2019/data-plane-setup/arch-2.svg
  content/blog/2019/data-plane-setup/index.md
  static/js/all.min.js.map
Labels: cla: no

#3185 Fix Tracing FAQ typo
  content/help/faq/distributed-tracing/how-distributed-tracing-works.md
Labels: approved, cla: yes, lgtm
