Repository istio/istio.io, pull requests merged in 2019-12, with the labels that each got.

#5891 zh-translation: /boilerplates/security-vulnerability.md
  content/zh/boilerplates/security-vulnerability.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5912 zh-translation:/docs/reference/config/security/_index.md
  content/zh/docs/reference/config/security/_index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5913 zh-translation:/docs/reference/glossary/annotation.md
  content/zh/docs/reference/glossary/annotation.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5940 Update index.md to fix broken link to Zipkin
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
Labels: cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#5917 zh-translation: /docs/tasks/security/authorization/authz-td-migration…
  content/zh/docs/tasks/security/authorization/authz-td-migration/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5942 [release-1.4] Update index.md to fix broken link to Zipkin
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
Labels: cla: yes, size/XS

#5911 zh-translation:/docs/examples/virtual-machines/multi-network/index.md
  content/zh/docs/examples/virtual-machines/multi-network/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#5914 zh-translation: /docs/examples/platform/endpoints/index.md
  content/zh/docs/examples/platform/endpoints/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5938 zh-translation: /docs/tasks/security/authorization/authz-tcp/index.md and some _index.md
  content/zh/docs/examples/virtual-machines/_index.md
  content/zh/docs/tasks/security/authorization/_index.md
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
  content/zh/docs/tasks/security/authz-tcp/index.md
  content/zh/docs/tasks/security/citadel-config/_index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5862 zh-translation: /news/support/announcing-1.1-eol/index.md
  content/zh/news/support/announcing-1.1-eol/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5873 zh-translation:content/zh/news/security/istio-security-2019-005/index.md
  content/zh/news/security/istio-security-2019-005/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5846 zh-translation:zh/blog/2019/evolving-istios-apis/index.md
  content/zh/blog/2019/evolving-istios-apis/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5941 zh-translation: /docs/examples/platform/icp/index.md
  content/zh/docs/examples/platform/icp/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5636 zh-translation:docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#5945 zh-translation: /docs/reference/glossary/trust-domain-migration.md and some more
  content/zh/docs/reference/glossary/trust-domain-migration.md
  content/zh/faq/applications/index.md
  content/zh/faq/traffic-management/controlling-inbound-ports.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5939 Site improvements.
  .spelling
  content/en/docs/setup/additional-setup/customize/index.md
  content/en/news/releases/1.1.x/announcing-1.1/upgrade-notes/index.md
  content/en/news/releases/1.2.x/announcing-1.2/upgrade-notes/index.md
  content/en/news/releases/1.3.x/announcing-1.3.5/index.md
  content/en/news/releases/1.3.x/announcing-1.3/upgrade-notes/index.md
  content/en/news/releases/1.4.x/announcing-1.4/upgrade-notes/index.md
  content/en/news/releases/1.5.x/_index.md
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
  content/en/news/security/incorrect-sidecar-image-1.2.4/index.md
  content/en/news/security/istio-security-2019-001/index.md
  content/en/news/security/istio-security-2019-002/index.md
  content/en/news/security/istio-security-2019-003/index.md
  content/en/news/security/istio-security-2019-004/index.md
  content/en/news/security/istio-security-2019-005/index.md
  content/en/news/security/istio-security-2019-006/index.md
  i18n/en.toml
  layouts/_default/list.html
  layouts/_default/security-grid.html
  layouts/partials/sidebar_level.html
  layouts/shortcodes/change_log.html
  layouts/shortcodes/security_bulletin.html
  src/sass/_all.scss
  src/sass/base/_base.scss
  src/sass/misc/_security-grid.scss
Labels: cla: yes, size/L

#5947 [release-1.4] Site improvements.
  .spelling
  content/en/docs/setup/additional-setup/customize/index.md
  content/en/news/releases/1.1.x/announcing-1.1/upgrade-notes/index.md
  content/en/news/releases/1.2.x/announcing-1.2/upgrade-notes/index.md
  content/en/news/releases/1.3.x/announcing-1.3.5/index.md
  content/en/news/releases/1.3.x/announcing-1.3/upgrade-notes/index.md
  content/en/news/releases/1.4.x/announcing-1.4/upgrade-notes/index.md
  content/en/news/security/incorrect-sidecar-image-1.2.4/index.md
  content/en/news/security/istio-security-2019-001/index.md
  content/en/news/security/istio-security-2019-002/index.md
  content/en/news/security/istio-security-2019-003/index.md
  content/en/news/security/istio-security-2019-004/index.md
  content/en/news/security/istio-security-2019-005/index.md
  content/en/news/security/istio-security-2019-006/index.md
  i18n/en.toml
  layouts/_default/list.html
  layouts/_default/security-grid.html
  layouts/partials/sidebar_level.html
  layouts/shortcodes/change_log.html
  layouts/shortcodes/security_bulletin.html
  src/sass/_all.scss
  src/sass/base/_base.scss
  src/sass/misc/_security-grid.scss
Labels: cla: yes, size/L

#5949 Replace cookies with local storage.
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/blog/2018/egress-mongo/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/test/tabs/index.md
  content/en/test/tabs_and_lists/index.md
  content/zh/about/contribute/creating-and-editing-pages/index.md
  content/zh/blog/2018/egress-mongo/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
  content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/install/multicluster/gateways/index.md
  content/zh/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/test/tabs/index.md
  content/zh/test/tabs_and_lists/index.md
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabset.html
  src/ts/codeBlocks.ts
  src/ts/readTracking.ts
  src/ts/tabset.ts
  src/ts/themes.ts
  src/ts/themes_init.ts
Labels: cla: yes, size/L

#5952 Replace cookies with local storage. (#5949)
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/blog/2018/egress-mongo/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/test/tabs/index.md
  content/en/test/tabs_and_lists/index.md
  content/zh/blog/2018/egress-mongo/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
  content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/install/multicluster/gateways/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/test/tabs/index.md
  content/zh/test/tabs_and_lists/index.md
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabset.html
  src/ts/codeBlocks.ts
  src/ts/readTracking.ts
  src/ts/tabset.ts
  src/ts/themes.ts
  src/ts/themes_init.ts
Labels: cla: yes, size/L

#5943 zh-translation: /faq/security/use-k8s-secrets.md
  content/zh/faq/security/use-k8s-secrets.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5725 zh-translation:/docs/reference/glossary/workload-instance.md
  content/zh/docs/reference/glossary/workload-instance.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5948 [release-1.4] lack of indentation
  content/en/docs/ops/common-problems/injection/index.md
Labels: cla: yes, size/XS

#5960 Fix bug preventing theme switching from working properly.
  src/ts/themes.ts
Labels: cherrypick/release-1.4, cla: yes, size/XS

#5946 zh-translation:/blog/2019/istio1.1_perf/index.md
  content/zh/blog/2019/istio1.1_perf/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5957 zh-translation:/docs/reference/config/security/constraints-and-properties/index.md
  content/zh/docs/reference/config/security/constraints-and-properties/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5944 zh-translation: /blog/2018/series
  content/zh/blog/2018/aws-nlb/index.md
  content/zh/blog/2018/delayering-istio/index.md
  content/zh/blog/2018/egress-monitoring-access-control/index.md
  content/zh/blog/2018/incremental-traffic-management/index.md
  content/zh/blog/2018/istio-twitch-stream/index.md
  content/zh/blog/2018/traffic-mirroring/index.md
  content/zh/blog/2018/v1alpha3-routing/index.md
  content/zh/docs/ops/common-problems/observability-issues/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XL, translation/chinese

#5956 zh-translation:content/zh/news/security/istio-security-2019-006/index.md
  content/zh/news/security/istio-security-2019-006/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5968 zh-translation: content/zh/news/security/istio-security-2019-003/index.md
  content/zh/news/security/istio-security-2019-003/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5969 zh-translation: blog series
  content/zh/blog/2017/0.1-canary/index.md
  content/zh/blog/2017/0.1-using-network-policy/index.md
  content/zh/blog/2017/adapter-model/index.md
  content/zh/blog/2017/mixer-spof-myth/index.md
  content/zh/blog/2019/appswitch/index.md
  content/zh/blog/2019/custom-ingress-gateway/index.md
  content/zh/blog/2019/egress-performance/index.md
  content/zh/blog/2019/multicluster-version-routing/index.md
Labels: cla: yes, ok-to-test, size/XL, translation/chinese

#5964 remove leftover CRD
  content/en/news/releases/1.4.x/announcing-1.4/upgrade-notes/index.md
Labels: area/environments, area/security, cherrypick/release-1.4, cla: yes, size/S

#5973 [release-1.4] remove leftover CRD
  content/en/news/releases/1.4.x/announcing-1.4/upgrade-notes/index.md
Labels: cla: yes, size/S

#5962 Clarify workload glossary entry
  content/en/docs/reference/glossary/workload.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#5963 Add section on external charts
  content/en/docs/setup/install/istioctl/index.md
Labels: cherrypick/master, cla: yes, size/S

#5951 Adding an entry for Zookeeper
  content/en/faq/applications/zookeeper.md
Labels: cherrypick/release-1.4, cla: yes, size/S

#5978 Address #5902 add 1-liner description to CVEs
  content/en/news/security/istio-security-2019-001/index.md
  content/en/news/security/istio-security-2019-002/index.md
  content/en/news/security/istio-security-2019-003/index.md
  content/en/news/security/istio-security-2019-004/index.md
  content/en/news/security/istio-security-2019-005/index.md
  content/en/news/security/istio-security-2019-006/index.md
Labels: area/security, cla: yes, kind/docs, size/S

#5981 [release-1.4] Address #5902 add 1-liner description to CVEs
  content/en/news/security/istio-security-2019-001/index.md
  content/en/news/security/istio-security-2019-002/index.md
  content/en/news/security/istio-security-2019-003/index.md
  content/en/news/security/istio-security-2019-004/index.md
  content/en/news/security/istio-security-2019-005/index.md
  content/en/news/security/istio-security-2019-006/index.md
Labels: cla: yes, size/S

#5983 Delete a useless shortcode.
  data/args.yml
  layouts/shortcodes/istio_full_version_release_year.html
Labels: cla: yes, size/XS

#5863 zh-translation: /news/support/announcing-1.1-eol-final/index.md
  content/zh/news/support/announcing-1.1-eol-final/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5985 zh-translation: fix schema error when translating
  content/zh/docs/concepts/traffic-management/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5979 1.4.1 release notes [1.4 branch]
  content/en/news/releases/1.4.x/announcing-1.4.1/index.md
  data/args.yml
Labels: cla: yes, size/S

#5982 Leverage new description strings on the security bulletin page.
  layouts/_default/security-grid.html
Labels: cherrypick/release-1.4, cla: yes, size/S

#5980 Now collect additional info when a user says a page is not helpful.
  i18n/en.toml
  layouts/partials/primary_bottom.html
  src/sass/misc/_feedback.scss
  src/ts/feedback.ts
Labels: cherrypick/release-1.4, cla: yes, size/M

#5950 1.4.1 Release Notes
  content/en/news/releases/1.4.x/announcing-1.4.1/index.md
Labels: cla: yes, size/S

#5975 [master] Add section on external charts
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#5992 Couple cherry picks.
  i18n/en.toml
  layouts/_default/security-grid.html
  layouts/partials/primary_bottom.html
  src/sass/misc/_feedback.scss
  src/ts/feedback.ts
Labels: cla: yes, size/M

#5991 Update index.md
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5993 Content changes to prepare to switch to the new Hugo.
  content/en/_index.html
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/about/contribute/style-guide/index.md
  content/en/about/release-cadence/index.md
  content/en/blog/2018/egress-mongo/index.md
  content/en/blog/2018/istio-authorization/index.md
  content/en/boilerplates/example.md
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/ops/common-problems/injection/index.md
  content/en/docs/ops/common-problems/validation/index.md
  content/en/docs/ops/configuration/mesh/secret-creation/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
  content/en/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/en/docs/reference/config/policy-and-telemetry/expression-language/index.md
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
  content/en/news/releases/1.1.x/announcing-1.1.3/index.md
  content/en/news/releases/1.1.x/announcing-1.1.8/index.md
  content/en/news/releases/1.2.x/announcing-1.2/upgrade-notes/index.md
  content/zh/_index.html
  layouts/shortcodes/boilerplate.html
Labels: cla: yes, size/L

#5976 [release-1.4] Adding an entry for Zookeeper
  content/en/faq/applications/zookeeper.md
Labels: cla: yes, size/S

#5987 fix istioctl instruction install instruction on gke
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#5995 Fix rendering issues with banners and stickers.
  layouts/partials/events.html
  src/sass/misc/_banners.scss
  src/sass/misc/_stickers.scss
  src/sass/themes/_dark-theme.scss
  src/sass/themes/_light-theme.scss
  src/sass/themes/_vars.scss
Labels: cherrypick/release-1.4, cla: yes, size/M

#5997 [release-1.4] Fix rendering issues with banners and stickers.
  layouts/partials/events.html
  src/sass/misc/_banners.scss
  src/sass/misc/_stickers.scss
  src/sass/themes/_dark-theme.scss
  src/sass/themes/_light-theme.scss
  src/sass/themes/_vars.scss
Labels: cla: yes, size/M

#5998 Fixes to the release note action buttons. (#5701)
  content/zh/docs/setup/getting-started/index.md
  layouts/shortcodes/relnote.html
  src/sass/misc/_relnote-actions.scss
Labels: cla: yes, size/M

#5999 Improve the "latest releaae" banner.
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/events/banners/latest-release.md
  layouts/partials/events.html
Labels: cherrypick/release-1.4, cla: yes, size/S

#6000 [release-1.4] Improve the "latest releaae" banner.
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/events/banners/latest-release.md
  layouts/partials/events.html
Labels: cla: yes, size/S

#6001 Improve hugo perf a bit.
  config.toml
  content/en/blog/_index.md
  content/en/news/_index.md
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
  layouts/partials/events.html
  layouts/partials/header.html
  layouts/shortcodes/gloss.html
  layouts/shortcodes/relnote.html
Labels: cherrypick/release-1.4, cla: yes, size/M

#6002 Improve hugo perf a bit. (#6001)
  config.toml
  content/en/blog/_index.md
  content/en/news/_index.md
  layouts/partials/events.html
  layouts/partials/header.html
  layouts/shortcodes/gloss.html
  layouts/shortcodes/relnote.html
Labels: cla: yes, size/M

#5986 zh-translation: /docs/tasks/security/authorization/authz-http/index.md
  content/zh/docs/tasks/security/authorization/authz-http/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5984 zh-translation: /docs/reference/config/policy-and-telemetry/mixer-ove…
  content/zh/docs/reference/config/policy-and-telemetry/mixer-overview/index.md
Labels: cla: yes, size/L, translation/chinese

#6003 Site improvements.
  Makefile
  SUPPORT.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
  config.toml
  content/en/blog/2018/egress-mongo/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/test/tabs_and_lists/index.md
  content/zh/blog/2018/egress-mongo/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/test/tabs_and_lists/index.md
  layouts/shortcodes/text_hack.html
  netlify.toml
Labels: cla: yes, size/L

#6010 Fix setting up Automatic mutual TLS example
  content/en/docs/tasks/security/authentication/auto-mtls/index.md
Labels: area/user experience, cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#5974 [release-1.4] Clarify workload glossary entry
  content/en/docs/reference/glossary/workload.md
Labels: cla: yes, size/XS

#6006 Document subzon topology key for Kubernetes
  content/en/docs/ops/configuration/traffic-management/locality-load-balancing/index.md
Labels: area/networking, cla: yes, kind/docs, size/XS

#5994 Warn helm 3 is not supported
  content/en/docs/setup/install/helm/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6012 add a note to known problems about node autoscaler
  content/en/docs/ops/common-problems/injection/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6014 [release-1.4] add a note to known problems about node autoscaler
  content/en/docs/ops/common-problems/injection/index.md
Labels: cla: yes, size/XS

#6013 [release-1.4] Warn helm 3 is not supported
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS

#6015 Stop collecting written feedback from users.
  layouts/partials/primary_bottom.html
  src/sass/misc/_feedback.scss
  src/ts/feedback.ts
Labels: cherrypick/release-1.4, cla: yes, size/M

#6016 [release-1.4] Stop collecting written feedback from users.
  layouts/partials/primary_bottom.html
  src/sass/misc/_feedback.scss
  src/ts/feedback.ts
Labels: cla: yes, size/M

#6008 zh-translation:content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6011 [release-1.4] Fix setting up Automatic mutual TLS example
  content/en/docs/tasks/security/authentication/auto-mtls/index.md
Labels: cla: yes, size/XS

#5988 zh-translation: Accessing External Services
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6024 zh-translation:content/zh/events/*
  content/zh/events/banners/kubecon-america-2019.md
  content/zh/events/banners/kubecon-europe-2020.md
  content/zh/events/banners/latest-release.md
  content/zh/events/index.md
  content/zh/events/stickers/1.5.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5958 zh-translation:/docs/reference/config/security/conditions/index.md
  content/zh/docs/reference/config/security/conditions/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6025 zh-translation:content/zh/docs/tasks/traffic-management/circuit-breaking/index.md
  content/zh/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6026 zh-translation:/docs/reference/config/analysis/message-format/index.md
  content/zh/docs/reference/config/analysis/message-format/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6004 zh-translation: content/zh/news/releases/1.4.x/announcing-1.4/upgrade-notes/index.md
  content/zh/news/releases/1.4.x/announcing-1.4/upgrade-notes/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6023 zh-translation:content/zh/docs/tasks/security/dns-cert/index.md
  content/zh/docs/tasks/security/dns-cert/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6022 zh-translation:/docs/tasks/security/authentication/authn-policy/index.md
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
  content/zh/docs/tasks/security/authentication/mutual-tls/index.md
  content/zh/faq/security/accessing-non-istio-services.md
Labels: area/security, cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6020 zh-translation: /docs/ops/deployment/performance-and-scalability/index.md
  content/zh/docs/ops/deployment/performance-and-scalability/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6019 zh-translation: /docs/ops/configuration/telemetry/in-proxy-service-telemetry/index.md
  content/zh/docs/ops/configuration/telemetry/in-proxy-service-telemetry/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6017 zh-translation: /docs/concepts/security/index.md
  content/zh/docs/concepts/security/index.md
  content/zh/docs/tasks/security/citadel-config/ca-namespace-targeting/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5970 zh-translation:content/zh/news/security/istio-security-2019-004/index.md
  content/zh/news/security/istio-security-2019-004/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6018 zh-translation: /docs/ops/common-problems/network-issues/index.md
  content/zh/docs/ops/common-problems/network-issues/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6021 fix image path invalid on windows
  layouts/shortcodes/image.html
Labels: cla: yes, ok-to-test, size/XS

#6041 many prs can't pass lint check , due to the kubernetes new release 1.17 url changes
  content/en/docs/ops/configuration/traffic-management/locality-load-balancing/index.md
  content/zh/docs/ops/configuration/traffic-management/locality-load-balancing/index.md
Labels: cla: yes, size/XS

#6042 Fix broken link for Configure Citadel Service Account Secret Generation
  content/en/docs/tasks/security/citadel-config/ca-namespace-targeting/index.md
Labels: area/user experience, cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#6047 ISTIO-SECURITY-2019-007 announcement
  .spelling
  content/en/news/releases/1.2.x/announcing-1.2.10/index.md
  content/en/news/releases/1.3.x/announcing-1.3.6/index.md
  content/en/news/releases/1.4.x/announcing-1.4.2/index.md
  content/en/news/security/istio-security-2019-007/index.md
Labels: area/security, area/test and release, cherrypick/release-1.4, cla: yes, kind/docs, size/L

#6048 [release-1.4] ISTIO-SECURITY-2019-007 announcement
  .spelling
  content/en/news/releases/1.2.x/announcing-1.2.10/index.md
  content/en/news/releases/1.3.x/announcing-1.3.6/index.md
  content/en/news/releases/1.4.x/announcing-1.4.2/index.md
  content/en/news/security/istio-security-2019-007/index.md
  data/args.yml
Labels: cla: yes, size/L

#6049 Correct date
  content/en/news/security/istio-security-2019-007/index.md
Labels: area/security, area/test and release, cherrypick/release-1.4, cla: yes, kind/docs, size/XS

#6044 [release-1.4] many prs can't pass lint check , due to the kubernetes new release 1.17 url changes
  content/en/docs/ops/configuration/traffic-management/locality-load-balancing/index.md
  content/zh/docs/ops/traffic-management/locality-load-balancing/index.md
Labels: cla: no, size/XS

#6050 [release-1.4] Correct date
  content/en/news/security/istio-security-2019-007/index.md
Labels: cla: yes, size/XS

#6038 Update reference docs.
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stdio/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/security/istio.rbac.v1alpha1/index.html
  data/analysis.yaml
Labels: cla: yes, size/XL

#6035 Improve Mutual TLS migration example
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#6005 Simplify istioctl diff command
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#6034 zh-translation: /news/releases/1.0.x/_index.md #1527
  content/zh/news/releases/1.0.x/_index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6031 zh-translation:content/zh/boilerplates/*
  content/zh/boilerplates/example.md
  content/zh/boilerplates/index.md
  content/zh/boilerplates/trace-generation.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6040 zh-translation:/docs/ops/diagnostic-tools/istioctl-describe/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6039 zh-translation:/docs/setup/additional-setup/cni/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6030 zh-translation: content/zh/news/releases/1.4.x/announcing-1.4.1/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.1/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6055 zh-translation:content/zh/docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/istioctl/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6053 zh-translation:/docs/tasks/security/authentication/_index.md
  content/zh/docs/tasks/security/authentication/_index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6051 Add CVE-2019-18838
  .spelling
  content/en/news/releases/1.2.x/announcing-1.2.10/index.md
  content/en/news/releases/1.3.x/announcing-1.3.6/index.md
  content/en/news/releases/1.4.x/announcing-1.4.2/index.md
  content/en/news/security/istio-security-2019-007/index.md
Labels: area/security, area/test and release, cherrypick/release-1.4, cla: yes, kind/docs, size/S

#5780 zh-translation:/faq/metrics-and-logs/life-of-a-request.md
  content/zh/faq/metrics-and-logs/life-of-a-request.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6058 zh-translation: content/zh/faq/applications/zookeeper.md
  content/zh/faq/applications/zookeeper.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5972 zh-translation:/blog/2018/egress-mongo/index.md
  content/zh/blog/2018/egress-mongo/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6029 zh-translation: 2018 blog series
  content/zh/blog/2018/egress-https/index.md
  content/zh/blog/2018/soft-multitenancy/index.md
  content/zh/docs/examples/virtual-machines/multi-network/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6054 zh-translation: /docs/reference/config/installation-options/index.md
  content/zh/docs/reference/config/installation-options/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6057 zh-translation: content/news/*
  content/zh/news/_index.md
  content/zh/news/releases/1.2.x/announcing-1.2.10/index.md
  content/zh/news/releases/1.3.x/announcing-1.3.6/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.2/index.md
  content/zh/news/security/incorrect-sidecar-image-1.2.4/index.md
  content/zh/news/security/istio-security-2019-007/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6032 zh-translation: /news/releases/0.x/announcing-0.1/index.md #1519
  content/zh/news/releases/0.x/announcing-0.1/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6060 [release-1.4] Add CVE-2019-18838
  .spelling
  content/en/news/releases/1.2.x/announcing-1.2.10/index.md
  content/en/news/releases/1.3.x/announcing-1.3.6/index.md
  content/en/news/releases/1.4.x/announcing-1.4.2/index.md
  content/en/news/security/istio-security-2019-007/index.md
Labels: cla: no, size/S

#6063 Bookinfo getting started clarification
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/setup/getting-started/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6064 [release-1.4] Bookinfo getting started clarification
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/XS

#6052 Document MTLSPolicyConflict analyzer messages
  content/en/docs/reference/config/analysis/ist0113/index.md
Labels: cla: yes, kind/docs, size/L

#6043 zh-translation:content/zh/docs/tasks/observability/logs/collecting-logs/index.md
  content/zh/docs/tasks/observability/logs/collecting-logs/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6068 zh-translation: /faq/general/istio-doesnt-work.md
  content/zh/faq/general/istio-doesnt-work.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#6067 zh-translation:/docs/reference/config/analysis/ist0101/index.md
  content/zh/docs/reference/config/analysis/ist0101/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6066 zh-translation:/docs/reference/config/analysis/ist0103/index.md
  content/zh/docs/reference/config/analysis/ist0103/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6033 zh-translation: /news/releases/0.x/announcing-0.2/index.md #1520
  content/zh/news/releases/0.x/announcing-0.2/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6070 zh-translation: docs/ops/common-problem/injection/index.md
  content/zh/docs/ops/common-problems/injection/index.md
  content/zh/docs/tasks/security/authorization/authz-http/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6076 zh-translation: /blog/_index.md
  content/zh/blog/_index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6072 zh-translation: /docs/reference/config/analysis/ist0001/index.md
  content/zh/docs/reference/config/analysis/ist0001/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6085 1.2 EOL Final
  content/en/news/support/announcing-1.2-eol-final/index.md
Labels: area/test and release, cherrypick/release-1.4, cla: yes, kind/docs, size/S

#6086 [release-1.4] 1.2 EOL Final
  content/en/news/support/announcing-1.2-eol-final/index.md
Labels: cla: yes, size/S

#6061 Update docs to reflect graduating istioctl analyze from experimental
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/analysis/_index.md
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/security/istio.authentication.v1alpha1/index.html
  data/analysis.yaml
Labels: cla: yes, kind/docs, size/XXL

#6065 update doc for multi cluster
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
Labels: area/environments, cherrypick/release-1.4, cla: yes, size/XS

#6088 Remove virtual service from glossary
  content/en/docs/reference/glossary/routing-rules.md
  content/en/docs/reference/glossary/virtual-service.md
Labels: cla: yes, size/S

#6077 zh-translation: content/zh/docs/reference/config/analysis/ist0107/index.md
  content/zh/docs/reference/config/analysis/ist0107/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6059 zh-translation:/docs/tasks/observability/distributed-tracing/overview…
  content/zh/docs/tasks/observability/distributed-tracing/overview/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6056 zh-translation:/blog/2019/announcing-istio-client-go/index.md
  content/zh/blog/2019/announcing-istio-client-go/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6092 zh-translation: docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/zh/docs/tasks/observability/distributed-tracing/zipkin/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6091 trans distributed-tracing/lightstep
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#6080 zh-translation: /faq/mixer/header-rules.md #1415
  content/zh/faq/mixer/header-rules.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6081 zh-translation: /faq/security/accessing-non-istio-services.md #1421
  content/zh/faq/security/accessing-non-istio-services.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6082 zh-translation: /faq/security/https-overlay.md #1425
  content/zh/faq/security/https-overlay.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6083 zh-translation: /faq/security/index.md #1426
  content/zh/faq/security/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6101 zh-translation:/zh/blog/2019/dns-cert/index.md
  content/zh/blog/2019/dns-cert/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6100 zh-translation:/zh/blog/2019/webhook/index.md
  content/zh/blog/2019/webhook/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6104 Update reference docs.
  Makefile.core.mk
  content/en/boilerplates/verify-crds.md
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  data/analysis.yaml
Labels: cla: yes, size/L

#6106 zh-translation: content/zh/about/contribute/github/index.md
  content/zh/about/contribute/github/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6095 zh-translation: content/en/docs/tasks/policy-enforcement/control-headers/index.md
  content/zh/docs/tasks/policy-enforcement/control-headers/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6084 zh-translation:/blog/2018/hp/index.md
  content/zh/blog/2018/hp/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6105 Switch Hugo back to the blackfriday markdown generator.
  Makefile.core.mk
  config.toml
  netlify.toml
Labels: cla: yes, size/S

#6093 zh-translation: docs/reference/glossary/multi-mesh.md
  content/zh/docs/reference/glossary/multi-mesh.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6102 zh-translation: some references update from previous translation.
  content/zh/docs/reference/config/networking/_index.md
  content/zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/zh/docs/reference/config/policy-and-telemetry/expression-language/index.md
  content/zh/docs/reference/glossary/index.md
  content/zh/docs/reference/glossary/trust-domain.md
  content/zh/docs/reference/glossary/workload.md
  content/zh/docs/setup/install/multicluster/_index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6108 zh-translation:/news/releases/1.4.x/_index.md
  content/zh/news/releases/1.4.x/_index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#6109 zh-translation:/zh/news/releases/1.4.x/announcing-1.4/_index.md
  content/zh/news/releases/1.4.x/announcing-1.4/_index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6098 zh-translation: /docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6073 zh-translation:/docs/reference/config/analysis/ist0104/index.md
  content/zh/docs/reference/config/analysis/ist0104/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6103 zh-translation: docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
  content/zh/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6110 zh-translation:/zh/news/releases/1.4.x/announcing-1.4/change-notes/in…
  content/zh/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese
