Repository istio/istio.io, pull requests merged in 2019-11, with the labels that each got.

#5312 Fix broken link in Chinese translations.
  i18n/en.toml
  layouts/shortcodes/relnote.html
Labels: cla: yes, size/M

#5316 Fix another bug blocking the Chinese translation work.
  layouts/shortcodes/relnote.html
Labels: cla: yes, size/XS

#5185 update authorization for HTTP task for v1beta1 policy
  content/en/docs/tasks/security/authz-http/index.md
Labels: area/security, cla: yes, kind/docs, size/L

#5320 1.3.4 release notes
  content/en/news/2019/announcing-1.3.4/index.md
Labels: cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, size/M

#5322 [release-1.3] 1.3.4 release notes
  content/en/news/2019/announcing-1.3.4/index.md
  data/args.yml
Labels: cla: yes, size/M

#5326 zh-translation: /docs/tasks/traffic-management/ingress/_index.md
  content/zh/docs/tasks/traffic-management/ingress/_index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5327 zh-translation: /docs/tasks/traffic-management/request-routing/index.md
  content/zh/docs/tasks/traffic-management/request-routing/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5328 zh-translation:/docs/reference/glossary/mixer-instance.md
  content/zh/docs/reference/glossary/mixer-instance.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5331 zh-translation: content/zh/about/community/_index.md
  content/zh/about/community/_index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#5334 fix invalid operator example.
  content/en/docs/setup/install/operator/index.md
Labels: area/environments, cla: yes, size/XS

#5319 Address rendering glitch on the istioctl reference page.
  src/sass/_all.scss
  src/sass/misc/_command-flags.scss
  src/sass/misc/_primary.scss
Labels: cla: yes, size/S

#5339 Fix date, which fixes sorting order.
  content/en/news/2019/announcing-1.3.4/index.md
Labels: cherrypick/master, cla: yes, size/XS

#5315 issue 5314 - OpenShift 4.2+ requires customized CNI settings.
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, kind/docs, size/XS

#5340 [master] Fix date, which fixes sorting order.
  content/en/news/2019/announcing-1.3.4/index.md
Labels: cla: yes, size/XS

#5348 Fix 134 announce link bug
  content/en/news/2019/announcing-1.3.4/index.md
Labels: cherrypick/release-1.3, cherrypick/release-1.4, cla: yes

#5337 zh-translation: /faq/setup
  content/zh/faq/setup/consul-unset-context.md
  content/zh/faq/setup/index.md
  content/zh/faq/setup/k8s-migrating.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5338 zh-translations: almost of _index.md
  content/zh/about/_index.md
  content/zh/about/contribute/_index.md
  content/zh/blog/2017/_index.md
  content/zh/blog/2018/_index.md
  content/zh/blog/2019/_index.md
  content/zh/blog/_index.md
  content/zh/docs/_index.md
  content/zh/docs/concepts/_index.md
  content/zh/docs/examples/_index.md
  content/zh/docs/examples/mesh-expansion/_index.md
  content/zh/docs/examples/microservices-istio/_index.md
  content/zh/docs/examples/multicluster/_index.md
  content/zh/docs/ops/_index.md
  content/zh/docs/ops/common-problems/_index.md
  content/zh/docs/ops/diagnostic-tools/_index.md
  content/zh/docs/ops/security/_index.md
  content/zh/docs/ops/setup/_index.md
  content/zh/docs/ops/telemetry/_index.md
  content/zh/docs/ops/traffic-management/_index.md
  content/zh/docs/reference/_index.md
  content/zh/docs/reference/commands/_index.md
  content/zh/docs/reference/config/_index.md
  content/zh/docs/reference/config/analysis/_index.md
  content/zh/docs/reference/config/authorization/_index.md
  content/zh/docs/reference/config/networking/_index.md
  content/zh/docs/reference/config/policy-and-telemetry/_index.md
  content/zh/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content/zh/docs/reference/config/policy-and-telemetry/templates/_index.md
  content/zh/docs/setup/additional-setup/_index.md
  content/zh/docs/setup/install/_index.md
  content/zh/docs/setup/install/multicluster/_index.md
  content/zh/docs/setup/platform-setup/_index.md
  content/zh/docs/setup/upgrade/_index.md
  content/zh/docs/tasks/_index.md
  content/zh/docs/tasks/observability/_index.md
  content/zh/docs/tasks/observability/distributed-tracing/_index.md
  content/zh/docs/tasks/observability/logs/_index.md
  content/zh/docs/tasks/observability/metrics/_index.md
  content/zh/docs/tasks/policy-enforcement/_index.md
  content/zh/docs/tasks/security/_index.md
  content/zh/docs/tasks/traffic-management/_index.md
  content/zh/docs/tasks/traffic-management/egress/_index.md
  content/zh/docs/tasks/traffic-management/ingress/_index.md
  content/zh/faq/_index.md
  content/zh/news/2017/_index.md
  content/zh/news/2018/_index.md
  content/zh/news/2019/_index.md
  content/zh/news/_index.md
  content/zh/test/_index.md
Labels: cla: yes, kind/docs, size/L, translation/chinese

#5349 [release-1.3] Fix 134 announce link bug
  content/en/news/2019/announcing-1.3.4/index.md
Labels: cla: yes, size/XS

#5350 Updated Helm options for protocol sniffing
  content/en/docs/reference/config/installation-options/index.md
Labels: cla: yes, kind/docs, size/XS

#5359 zh-translation:/docs/reference/glossary/operator.md
  content/zh/docs/reference/glossary/operator.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5345 zh-translation:/content/zh/faq/security/secure-ingress.md
  content/zh/faq/security/secure-ingress.md
Labels: area/security, cla: yes, ok-to-test, size/XS, translation/chinese

#5329 zh-translation:docs/tasks/observability/logs/collecting-logs/index.md
  content/zh/docs/tasks/observability/logs/collecting-logs/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5361 zh-translation: /docs/tasks/traffic-management/traffic-shifting/index.md
  content/zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5351 zh-translation: faq/traffic-management/viewing-current-rules.md
  content/zh/faq/traffic-management/viewing-current-rules.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5354 zh-translation:/docs/ops/setup/validation/index.md
  content/zh/docs/ops/setup/validation/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5365 zh-translation:/docs/reference/glossary/index.md
  content/zh/docs/reference/glossary/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5373 zh-translation:/docs/setup/platform-setup/docker/index.md
  content/zh/docs/setup/platform-setup/docker/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5367 zh-translation: /docs/tasks/traffic-management/request-timeouts/index.md
  content/zh/docs/tasks/traffic-management/request-timeouts/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5368 zh-translation:/faq/metrics-and-logs/prometheus-application-metrics.md
  content/zh/faq/metrics-and-logs/prometheus-application-metrics.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5358 zh-translation:/faq/mixer/mixer-self-monitoring.md
  content/zh/faq/mixer/mixer-self-monitoring.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5360 trans content/zh/faq/setup/k8s-sidecar-injection-not-working.md
  content/zh/faq/setup/k8s-sidecar-injection-not-working.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5362 zh-translation: /boilerplates/kubectl-multicluster-contexts.md
  content/zh/boilerplates/kubectl-multicluster-contexts.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5366 zh-translation:/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5370 zh-translation:/faq/distributed-tracing/how-mixer-based-tracing-works.md
  content/zh/faq/distributed-tracing/how-mixer-based-tracing-works.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5347 zh-translation:content/zh/docs/ops/telemetry/envoy-stats/index.md
  content/zh/docs/ops/telemetry/envoy-stats/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5341 zh-translation: /faq/setup/consul-app-not-working.md
  content/zh/faq/setup/consul-app-not-working.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5336 zh-translation:/faq/distributed-tracing/istio-copy-headers.md
  content/zh/faq/distributed-tracing/istio-copy-headers.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5379 Workaround for sudden Netlify errors
  scripts/build_site.sh
Labels: cla: yes, size/XS

#5380 Clean up build logic.
  Makefile.core.mk
  content/zh/about/contribute/creating-and-editing-pages/index.md
  data/args.yml
  scripts/build_archive_site.sh
  scripts/build_site.sh
  scripts/gen_site.sh
  scripts/grab_examples.sh
  scripts/grab_operator_yamls.sh
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/L

#5388 Update instructions for CNI on OpenShift
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/XS

#5392 Update reference docs.
  Makefile.core.mk
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/authorization/authorization-policy/index.html
  content/en/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  data/analysis.yaml
  examples/examples__bookinfo.snippets.txt
  examples/tasks__security__mututal_tls_migration.snippets.txt
  examples/tasks__traffic_management__mirroring.snippets.txt
  scripts/grab_examples.sh
  static/operator.yaml
Labels: cla: yes, size/L

#5390 Fix directory structure/heading for istioctl install
  content/en/about/feature-stages/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/ops/security/harden-docker-images/index.md
  content/en/docs/ops/setup/app-health-check/index.md
  content/en/docs/reference/config/installation-options/index.md
  content/en/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/en/docs/reference/glossary/index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/kubernetes/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/en/docs/setup/upgrade/istioctl-upgrade/index.md
  content/en/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/en/docs/tasks/observability/gateways/index.md
  content/en/docs/tasks/security/auth-sds/index.md
  content/en/docs/tasks/security/ca-namespace-targeting/index.md
  content/en/docs/tasks/security/health-check/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/faq/security/cert-lifetime-config.md
  content/en/news/2019/announcing-1.3/change-notes/index.md
  content/zh/about/feature-stages/index.md
  content/zh/blog/2019/performance-best-practices/index.md
  content/zh/docs/concepts/observability/index.md
  content/zh/docs/ops/security/harden-docker-images/index.md
  content/zh/docs/ops/setup/app-health-check/index.md
  content/zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/zh/docs/setup/additional-setup/config-profiles/index.md
  content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/install/kubernetes/index.md
  content/zh/docs/setup/install/multicluster/gateways/index.md
  content/zh/docs/setup/install/multicluster/shared-gateways/index.md
  content/zh/docs/setup/upgrade/istioctl-upgrade/index.md
  content/zh/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/zh/docs/tasks/observability/distributed-tracing/overview/index.md
  content/zh/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/zh/docs/tasks/observability/gateways/index.md
  content/zh/docs/tasks/security/auth-sds/index.md
  content/zh/docs/tasks/security/ca-namespace-targeting/index.md
  content/zh/docs/tasks/security/health-check/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/news/2019/announcing-1.3/change-notes/index.md
Labels: cla: yes, kind/docs, size/L

#5317 Istio operator blog
  .spelling
  content/en/blog/2019/introducing-istio-operator/index.md
Labels: cla: yes, size/L

#5393 zh-translation:/faq/security/secret-encryption.md
  content/zh/faq/security/secret-encryption.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5353 zh-translation: /docs/tasks/traffic-management/fault-injection/index.md
  content/zh/docs/tasks/traffic-management/fault-injection/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5391 Fix references to samples/operator files
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#5333 zh-translation: content/zh/docs/tasks/traffic-management/ingress/secu…
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#5330 zh-translation: /docs/concepts/security/index.md
  content/zh/docs/concepts/security/index.md
Labels: cla: yes, ok-to-test, size/XL, translation/chinese

#5363 zh-translation:/docs/tasks/observability/metrics/tcp-metrics/index.md
  content/zh/docs/tasks/observability/metrics/tcp-metrics/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5409 Zh trans 1303: /docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/zh/docs/tasks/observability/distributed-tracing/jaeger/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5400 zh-translation: /faq/security
  content/zh/docs/concepts/security/index.md
  content/zh/faq/security/auth-mix-and-match.md
  content/zh/faq/security/non-istio-to-istio.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5396 zh-translation:/news/2019/announcing-1.3.4/index.md
  content/zh/news/2019/announcing-1.3.4/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5426 Added a bunch of release note aliases to make things consistent over time.
  content/en/news/2017/announcing-0.1/index.md
  content/en/news/2017/announcing-0.2/index.md
  content/en/news/2017/announcing-0.3/index.md
  content/en/news/2017/announcing-0.4/index.md
  content/en/news/2018/announcing-0.5/index.md
  content/en/news/2018/announcing-0.6/index.md
  content/en/news/2018/announcing-0.7/index.md
  content/en/news/2018/announcing-0.8/index.md
  content/en/news/2018/announcing-1.0.1/index.md
  content/en/news/2018/announcing-1.0.2/index.md
  content/en/news/2018/announcing-1.0.3/index.md
  content/en/news/2018/announcing-1.0.4/index.md
  content/en/news/2018/announcing-1.0.5/index.md
  content/en/news/2018/announcing-1.0/index.md
  content/en/news/2019/announcing-1.0.6/index.md
  content/en/news/2019/announcing-1.0.7/index.md
  content/en/news/2019/announcing-1.0.8/index.md
  content/en/news/2019/announcing-1.0.9/index.md
  content/en/news/2019/announcing-1.1.1/index.md
  content/en/news/2019/announcing-1.1.10/index.md
  content/en/news/2019/announcing-1.1.11/index.md
  content/en/news/2019/announcing-1.1.12/index.md
  content/en/news/2019/announcing-1.1.13/index.md
  content/en/news/2019/announcing-1.1.14/index.md
  content/en/news/2019/announcing-1.1.15/index.md
  content/en/news/2019/announcing-1.1.16/index.md
  content/en/news/2019/announcing-1.1.2/index.md
  content/en/news/2019/announcing-1.1.3/index.md
  content/en/news/2019/announcing-1.1.4/index.md
  content/en/news/2019/announcing-1.1.5/index.md
  content/en/news/2019/announcing-1.1.6/index.md
  content/en/news/2019/announcing-1.1.7/index.md
  content/en/news/2019/announcing-1.1.8/index.md
  content/en/news/2019/announcing-1.1.9/index.md
  content/en/news/2019/announcing-1.1/index.md
  content/en/news/2019/announcing-1.2.1/index.md
  content/en/news/2019/announcing-1.2.2/index.md
  content/en/news/2019/announcing-1.2.3/index.md
  content/en/news/2019/announcing-1.2.4/index.md
  content/en/news/2019/announcing-1.2.5/index.md
  content/en/news/2019/announcing-1.2.6/index.md
  content/en/news/2019/announcing-1.2.7/index.md
  content/en/news/2019/announcing-1.2/index.md
  content/en/news/2019/announcing-1.3.1/index.md
  content/en/news/2019/announcing-1.3.2/index.md
  content/en/news/2019/announcing-1.3.3/index.md
  content/en/news/2019/announcing-1.3/index.md
  scripts/build_site.sh
Labels: cla: yes, size/M

#5428 Update istioctl setup docs
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/M

#5430 - 1.2.9 release notes
  content/en/news/2019/announcing-1.2.9/index.md
Labels: cla: yes, size/S

#5313 Auto mTLS user guide doc on istio.io
  content/en/docs/tasks/security/automtls/index.md
Labels: cla: yes, size/L

#5407 zh-translation:/docs/setup/additional-setup/customize/index.md
  content/zh/docs/setup/additional-setup/customize/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5398 zh-translation: /docs/tasks/observability/log/access-log/index.md
  content/zh/docs/tasks/observability/logs/access-log/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5438 zh-translation:/docs/setup/platform-setup/oci/index.md
  content/zh/docs/setup/platform-setup/oci/index.md
Labels: cla: yes, ok-to-test, size/S

#5437 Update install text
  content/en/docs/setup/install/kubernetes/index.md
Labels: cla: yes, size/XS

#5422 zh-translation: /docs/tasks/security/health-check/index.md
  content/zh/docs/tasks/security/health-check/index.md
Labels: area/security, cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5445 zh-translation:/faq/mixer/index.md
  content/zh/faq/mixer/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5410 zh-translation:/docs/setup/additional-setup/sidecar-injection/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#5441 zh-translation:/docs/ops/traffic-management/protocol-selection/index.md
  content/zh/docs/ops/traffic-management/protocol-selection/index.md
  content/zh/faq/security/does-istio-support-authorization.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5402 fix: content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/zh/about/contribute/creating-and-editing-pages/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5399 zh-translation: /docs/tasks/security/plugin-ca-cert/index.md
  content/zh/docs/tasks/security/plugin-ca-cert/index.md
Labels: area/security, cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5423 zh-translation: docs/setup/platform-setup/openshift/index.md
  content/zh/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5403 zh-translation:/docs/setup/platform-setup/alicloud/index.md
  content/zh/docs/setup/platform-setup/alicloud/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5453 zh-translation: /docs/reference/glossary/envoy.md
  content/zh/docs/reference/glossary/envoy.md
Labels: cla: yes, needs-ok-to-test, size/XS, translation/chinese

#5404 zh-translation: /docs/setup/platform-setup/minikube/index.md
  content/zh/docs/setup/platform-setup/minikube/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5381 zh-translation: /docs/setup/install/helm/index.md
  content/zh/docs/setup/install/helm/index.md
Labels: area/environments, cla: yes, ok-to-test, size/L, translation/chinese

#5435 update authz group task for 1.4
  content/en/docs/tasks/security/authn-policy/index.md
  content/en/docs/tasks/security/authz-http/index.md
  content/en/docs/tasks/security/authz-tcp/index.md
  content/en/docs/tasks/security/rbac-groups/index.md
Labels: area/security, cla: yes, size/L

#5442 zh-translation:/content/zh/faq/security/check-policy.md
  content/zh/faq/security/check-policy.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5443 zh-translation:/content/zh/faq/security/enabling-disabling-mtls.md
  content/zh/faq/security/enabling-disabling-mtls.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5449 zh-translation:/docs/setup/platform-setup/ibm/index.md
  content/zh/docs/setup/platform-setup/ibm/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5412 zh-translation:/docs/setup/platform-setup/gke/index.md
  content/zh/docs/setup/platform-setup/gke/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5455 zh-translation:/content/zh/faq/metrics-and-logs/index.md
  content/zh/faq/metrics-and-logs/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5461 zh-translation:/docs/setup/platform-setup/MicroK8s/index.md
  content/zh/docs/setup/platform-setup/MicroK8s/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5248 Initial 1.4.0 release notes
  content/en/news/2019/announcing-1.4/change-notes/index.md
Labels: cla: yes, lifecycle/needs-triage, size/M

#5436 Split up install to separate CRs
  static/default-cr.yaml
  static/demo-cr.yaml
  static/minimal-cr.yaml
  static/operator-profile-demo-auth.yaml
  static/operator.yaml
  static/sds-cr.yaml
Labels: cla: yes, size/M

#5476 1.4.0 release notes for operator
  content/en/news/2019/announcing-1.4/change-notes/index.md
Labels: cla: yes, size/XS

#5478 Revert "Split up install to separate CRs (#5436)"
  SUPPORT.md
  static/operator-profile-default.yaml
  static/operator-profile-demo-auth.yaml
  static/operator-profile-demo.yaml
  static/operator-profile-minimal.yaml
  static/operator-profile-sds.yaml
  static/operator.yaml
Labels: cla: yes, size/M

#5429 Mention OpenShift specific instructions on Bookinfo tutorial
  content/en/docs/examples/bookinfo/index.md
Labels: cla: yes, size/XS

#5257 Add podAnnotations param for cni helm chart
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5291 istioctl analyze messages documentation
  content/en/docs/reference/config/analysis/ist0001/index.md
  content/en/docs/reference/config/analysis/ist0101/index.md
  content/en/docs/reference/config/analysis/ist0102/index.md
  content/en/docs/reference/config/analysis/ist0103/index.md
  content/en/docs/reference/config/analysis/ist0104/index.md
  content/en/docs/reference/config/analysis/ist0105/index.md
  content/en/docs/reference/config/analysis/ist0106/index.md
  content/en/docs/reference/config/analysis/ist0107/index.md
  content/en/docs/reference/config/analysis/ist0108/index.md
  content/en/docs/reference/config/analysis/ist0109/index.md
  content/en/docs/reference/config/analysis/message-format/index.md
  content/en/docs/reference/glossary/annotation.md
Labels: cla: yes, kind/docs, size/L

#5484 - 1.2.9 release notes (#5430)
  content/en/news/2019/announcing-1.2.9/index.md
Labels: cla: yes, size/S

#5452 zh-translation: /docs/reference/glossary/mixer-handler.md
  content/zh/docs/reference/glossary/mixer-handler.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5465 zh-translation:/faq/mixer/seeing-mixer-config.md
  content/zh/faq/mixer/seeing-mixer-config.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5454 zh-translation: /docs/reference/glossary/mixer.md
  content/zh/docs/reference/glossary/mixer.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5458 zh-translation:/docs/examples/endpoints/index.md
  content/zh/docs/examples/endpoints/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5401 zh-translation:/docs/tasks/observability/metrics/using-istio-dashboard/index.md
  content/zh/docs/tasks/observability/metrics/using-istio-dashboard/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5496 zh-translation:/content/zh/faq/general/index.md
  content/zh/faq/general/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5471 zh-translation:/faq/mixer/attribute-expressions.md
  content/zh/faq/mixer/attribute-expressions.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5511 zh-translation:/faq/general/how-was-istio-started.md
  content/zh/faq/general/how-was-istio-started.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5493 zh-translation: /faq/distributed-tracing/no-tracing.md
  content/zh/faq/distributed-tracing/no-tracing.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5506 zh-translation: /docs/reference/glossary/control-plane.md
  content/zh/docs/reference/glossary/control-plane.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5492 zh-translation:/docs/concepts/policies/index.md
  content/zh/docs/concepts/policies/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5468 zh-translation: istio.io/content/zh/boilerplates/index.md
  content/zh/boilerplates/helm-security-warning.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5469 zh-translation:/docs/ops/architecture/index.md
  content/zh/docs/ops/architecture/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5152 User guide for Istio DNS certificates
  content/en/docs/tasks/security/dns-cert/index.md
Labels: cla: yes, size/L

#5162 User guide for istioctl managing webhooks
  content/en/docs/tasks/security/webhook/index.md
Labels: cla: yes, size/L

#5287 Blog for Istio DNS certificate management
  content/en/blog/2019/dns-cert/architecture.png
  content/en/blog/2019/dns-cert/index.md
Labels: area/environments, area/networking, area/security, cla: yes, size/M

#5285 Blog for secure webhook management
  content/en/blog/2019/webhook/example_attack.png
  content/en/blog/2019/webhook/index.md
Labels: area/environments, area/networking, area/security, cla: yes, size/M

#5483 More updates to istioctl install
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/M

#5521 Fix bug istioctl manifest command does not read from standard input
  content/en/docs/tasks/security/dns-cert/index.md
  content/en/docs/tasks/security/webhook/index.md
Labels: cla: yes, kind/docs, size/XS

#5481 - ISTIO-SECURITY-2019-006
  .spelling
  content/en/news/2019/istio-security-2019-006/index.md
Labels: area/security, cherrypick/release-1.3, cla: yes, kind/docs, size/M

#5524 Remove CR from base operator manifest
  scripts/grab_operator_yamls.sh
  static/operator.yaml
Labels: cla: yes, size/S

#5525 - ISTIO-SECURITY-2019-006 (#5481)
  .spelling
  content/en/news/2019/istio-security-2019-006/index.md
Labels: cla: yes, size/M

#5482 Fix auth installation and its references.
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/tasks/security/authorization/authz-http/index.md
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
  content/en/docs/tasks/security/authorization/rbac-groups/index.md
  content/en/docs/tasks/security/citadel-config/auth-sds/index.md
  content/en/docs/tasks/security/citadel-config/ca-namespace-targeting/index.md
  content/en/docs/tasks/security/citadel-config/health-check/index.md
  content/en/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
Labels: area/security, cla: yes, kind/docs, size/M

#5527 Update helm mtls enablement instructions
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/M

#5526 Update reference docs.
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html
  content/en/news/2018/announcing-1.0/index.md
  content/zh/news/2018/announcing-1.0/index.md
  data/analysis.yaml
  examples/examples__bookinfo.snippets.txt
  examples/tasks__security__authorization_for_http_services.snippets.txt
  examples/tasks__security__mututal_tls_migration.snippets.txt
  examples/tasks__traffic_management__mirroring.snippets.txt
Labels: cla: yes, size/XL

#5433 Standalone operator
  content/en/about/feature-stages/index.md
  content/en/blog/2019/introducing-istio-operator/index.md
  content/en/docs/ops/setup/standalone-operator/index.md
  content/en/docs/setup/install/standalone-operator/index.md
  content/en/news/2019/announcing-1.4/change-notes/index.md
  content/zh/about/feature-stages/index.md
Labels: cla: yes, size/L

#5499 Improve the root transition doc.
  content/en/docs/ops/security/root-transition/index.md
Labels: area/security, cherrypick/release-1.3, cherrypick/release-1.4, cla: yes, kind/docs, size/L

#5529 Change the config names to be consistent with istioctl installation
  content/en/docs/tasks/security/webhook/index.md
Labels: cla: yes, kind/docs, size/M

#5504 fix incorrect content
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/zh/docs/setup/install/multicluster/gateways/index.md
Labels: cla: yes, size/XS

#5502 zh-translation: /docs/reference/glossary/destination.md
  content/zh/docs/reference/glossary/destination.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5503 zh-translation:/faq/general/what-is-the-license.md
  content/zh/faq/general/what-is-the-license.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5500 zh-translation: /docs/tasks/security/health-check/index.md
  content/zh/docs/tasks/security/health-check/index.md
Labels: area/security, cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#5513 zh-translation:content/zh/docs/tasks/security/authz-tcp/index.md (#1066)
  content/zh/docs/tasks/security/authz-tcp/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5417 zh-translation:/docs/setup/platform-setup/azure/index.md
  content/zh/docs/setup/platform-setup/azure/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5424 zh-translation: /docs/setup/install/operator/index.md
  content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/operator/index.md
  content/zh/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/zh/docs/tasks/security/health-check/index.md
Labels: area/environments, cla: yes, ok-to-test, size/XL, translation/chinese

#5165 update authz concept page for the new v1beta1 policy
  content/en/docs/concepts/security/authz.svg
  content/en/docs/concepts/security/index.md
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/reference/config/authorization/conditions/index.md
  content/en/docs/reference/config/authorization/constraints-and-properties/index.md
  content/zh/docs/ops/common-problems/security-issues/index.md
Labels: cla: yes, size/XXL

#5533 [release-1.3] Improve the root transition instructions.
  content/en/docs/ops/security/root-transition/index.md
Labels: cla: yes, size/L

#5523 Update the egrep and service accounts.
  content/en/docs/tasks/security/authentication/auto-mtls/index.md
Labels: cla: yes, size/M

#5530 Update docs for Shared control plane (single-network)
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
Labels: cla: yes, kind/docs, size/M

#5531 Update to use istio-reader-service-account
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
Labels: cla: yes, kind/docs, size/XS

#5539 Fix several istio.io tasks.
  content/en/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
Labels: area/security, cla: yes, kind/docs, size/XS

#5540 zh-translation:/docs/tasks/security/mutual-tls/index.md
  content/zh/docs/tasks/security/mutual-tls/index.md
  content/zh/faq/security/check-policy.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5550 zh-translation: /docs/ops/security/root-transition/index.md
  content/zh/docs/ops/security/root-transition/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5561 zh-translation:/boilerplates/example.md
  content/zh/boilerplates/example.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5480 Refinements to the operator blog post
  content/en/blog/2019/introducing-istio-operator/index.md
Labels: cla: yes, size/L

#5567 zh-translation:/docs/setup/additional-setup/config-profiles/index.md
  content/zh/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5408 zh-translation:/docs/reference/glossary/source.md
  content/zh/docs/reference/glossary/source.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5374 zh-translation: /about/bugs/index.md
  content/zh/about/bugs/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5501 zh-translation: /faq/security/k8s-health-checks.md
  content/zh/faq/security/k8s-health-checks.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#5498 zh-translation:/content/zh/faq/distributed-tracing/index.md
  content/zh/faq/distributed-tracing/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5505 zh-translation: /docs/reference/glossary/cluster.md
  content/zh/docs/reference/glossary/cluster.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5568 zh-translation:content/zh/faq/general/how-do-i-contribute.md
  content/zh/faq/general/how-do-i-contribute.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5507 zh-translation: /docs/reference/glossary/data-plane.md
  content/zh/docs/reference/glossary/data-plane.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5413 zh-translation: docs/examples/microservices-istio/single/index.md
  content/zh/docs/examples/microservices-istio/single/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5570 zh-translation: /docs/reference/glossary/pod.md
  content/zh/docs/reference/glossary/pod.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5546 zh-translation:content/zh/docs/reference/glossary/crds.md
  content/zh/docs/reference/glossary/crds.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#5548 zh-translation: /docs/setup/install/standalone-operator/index.md
  content/zh/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5549 zh-translation: /docs/ops/security/harden-docker-images/index.md
  content/zh/docs/ops/security/harden-docker-images/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5558 zh-translation:/docs/ops/traffic-management/locality-load-balancing/i…
  content/zh/docs/ops/traffic-management/locality-load-balancing/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#5569 zh-translation: /docs/reference/glossary/managed-control-plane.md
  content/zh/docs/reference/glossary/managed-control-plane.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#5553 zh-translation:/docs/tasks/security/auth-sds/index.md
  content/zh/docs/tasks/security/auth-sds/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#5573 zh-translation:/docs/ops/diagnostic-tools/istioctl/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5490 zh-translation: /docs/reference/config/policy-and-telemetry/metrics/index.md
  content/zh/docs/reference/config/policy-and-telemetry/metrics/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#5559 zh-translation:/docs/tasks/policy-enforcement/denial-and-list/index.md
  content/zh/docs/tasks/policy-enforcement/denial-and-list/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese
