Repository istio/istio.io, pull requests merged in 2019-10, with the labels that each got.

#4776 Blog post about using Istio multi-mesh for isolation and boundary protection
  .spelling
  content/en/blog/2019/isolated-clusters/index.md
Labels: area/networking, cherrypick/release-1.3, cla: yes, size/L

#5092 Remove mention of Istio managed certmanager
  content/en/docs/tasks/observability/gateways/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
Labels: cla: yes, size/M

#5090 Clarify protocol enablement
  content/en/docs/ops/traffic-management/protocol-selection/index.md
  content/en/news/2019/announcing-1.1/index.md
Labels: cla: yes, size/S

#5040 Adding Tip not to enable global sds
  content/en/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
Labels: cherrypick/master, cla: yes, ok-to-test, size/XS

#5094 Use same bookinfo version on both clusters of MC example
  content/en/docs/examples/multicluster/gke/index.md
Labels: cla: yes, size/M

#5095 Improve concepts organization
  content/en/blog/2018/egress-https/index.md
  content/en/blog/2019/app-identity-and-access-adapter/index.md
  content/en/blog/2019/data-plane-setup/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/concepts/architecture/arch.svg
  content/en/docs/concepts/architecture/discovery.svg
  content/en/docs/concepts/architecture/index.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/concepts/policies/index.md
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/traffic-management/gateways-1.svg
  content/en/docs/concepts/traffic-management/gateways-2.svg
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/concepts/traffic-management/pilot-arch.svg
  content/en/docs/concepts/traffic-management/routing-overview.svg
  content/en/docs/concepts/traffic-management/service-entries-1.svg
  content/en/docs/concepts/traffic-management/virtual-services-1.svg
  content/en/docs/concepts/traffic-management/virtual-services-2.svg
  content/en/docs/concepts/traffic-management/virtual-services-3.svg
  content/en/docs/concepts/traffic-management/virtual-services-4.svg
  content/en/docs/concepts/traffic-management/virtual-services-5.svg
  content/en/docs/concepts/traffic-management/virtual-services-6.svg
  content/en/docs/concepts/what-is-istio/index.md
  content/en/docs/examples/mesh-expansion/multi-network/index.md
  content/en/docs/examples/mesh-expansion/single-network/index.md
  content/en/docs/ops/traffic-management/introduction/index.md
  content/en/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
  content/en/news/2019/announcing-1.1/index.md
Labels: cla: yes, size/XL

#5048 manual cherrypick of 5025 to release-1.3 branch
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
  content/en/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: cla: yes, size/S

#5099 Erroneous spelling of 'erroneous'
  content/en/news/2019/incorrect-sidecar-image-1.2.4/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5100 [release-1.3] Erroneous spelling of 'erroneous'
  content/en/news/2019/incorrect-sidecar-image-1.2.4/index.md
Labels: cla: no, size/XS

#5104 release note and announcement for 1.3.2/1.1.16/1.2.7
  .spelling
  content/en/news/2019/announcing-1.1.16/index.md
  content/en/news/2019/announcing-1.2.7/index.md
  content/en/news/2019/announcing-1.3.2/index.md
  content/en/news/2019/istio-security-003-004/index.md
  content/en/news/2019/istio-security-2019-005/index.md
Labels: cla: yes, size/L

#5105 release note and announcement for 1.3.2/1.1.16/1.2.7
  .spelling
  content/en/news/2019/announcing-1.1.16/index.md
  content/en/news/2019/announcing-1.2.7/index.md
  content/en/news/2019/announcing-1.3.2/index.md
  content/en/news/2019/istio-security-003-004/index.md
  content/en/news/2019/istio-security-2019-005/index.md
  data/args.yml
Labels: cla: no, needs-rebase, size/L

#5103 Add microk8s.io to the list of link checking exceptions.
  content/en/docs/setup/platform-setup/MicroK8s/index.md
Labels: cla: yes, size/XS

#5107 [release-1.3] Fix link for microk8s.io
  content/en/docs/setup/platform-setup/MicroK8s/index.md
Labels: cla: yes, size/XS

#5110 Update reference docs.
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istio_ca/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/networking/v1alpha3/service-entry/index.html
  content/en/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/opa/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/redisquota/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/security/v1beta1/authorization-policy/index.html
  data/analysis.yaml
Labels: cla: yes, size/XL

#5108 Ensure consistent use of 'multicluster'.
  content/en/blog/2019/isolated-clusters/index.md
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/concepts/deployment-models/index.md
  content/en/docs/reference/glossary/multicluster.md
  content/en/docs/reference/glossary/service-mesh.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/en/news/2018/announcing-1.0/index.md
  content/en/news/2019/istio-security-2019-005/index.md
Labels: cla: yes, kind/docs, size/M

#4971 Task describing new experimental 'describe pod' sub-command
  content/en/docs/ops/troubleshooting/istioctl-describe/index.md
Labels: cla: yes, size/L

#5106 Fix lint in the announcement
  .spelling
  content/en/docs/ops/troubleshooting/istioctl-describe/index.md
  content/en/news/2019/istio-security-2019-005/index.md
Labels: cherrypick/release-1.3, cla: yes, size/L

#5115 fix link issue
  content/en/news/2019/istio-security-2019-005/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5116 [release-1.3] fix link issue
  content/en/news/2019/istio-security-2019-005/index.md
Labels: cla: no, size/XS

#5117 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/L

#5119 Update subcommand for dashboard controlz
  content/en/docs/ops/troubleshooting/controlz/index.md
Labels: cla: yes, ok-to-test, size/XS

#5123 Remove incorrect warning
  content/en/docs/setup/upgrade/notice/index.md
Labels: cherrypick/master, cla: yes, size/XS

#5124 [master] Remove incorrect warning
  content/en/docs/setup/upgrade/notice/index.md
Labels: cla: yes, size/XS

#5121 Istioctl describe entry for op guide
  content/en/docs/ops/troubleshooting/istioctl-describe/index.md
Labels: cherrypick/release-1.3, cla: yes, size/L

#5128 [release-1.3] Istioctl describe entry for op guide
  content/en/docs/ops/troubleshooting/istioctl-describe/index.md
Labels: cla: no, size/L

#5129 Add missing word(s)
  content/en/docs/ops/traffic-management/introduction/index.md
Labels: cherrypick/release-1.3, cla: yes, ok-to-test, size/XS

#5132 SCC policies are not specific to BookInfo
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, size/S

#5130 Clarify relationship between pods and workloads
  content/en/docs/reference/glossary/pod.md
  content/en/docs/reference/glossary/workload-instance.md
  content/en/docs/reference/glossary/workload.md
Labels: cherrypick/release-1.3, cla: yes, size/S

#5135 [release-1.3] Clarify relationship between pods and workloads
  content/en/docs/reference/glossary/pod.md
  content/en/docs/reference/glossary/workload-instance.md
  content/en/docs/reference/glossary/workload.md
Labels: cla: no, size/S

#5136 Update reference docs.
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/en/docs/reference/config/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/en/docs/reference/config/networking/v1alpha3/envoy-filter/index.html
  content/en/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/en/docs/reference/config/networking/v1alpha3/service-entry/index.html
  content/en/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/en/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/circonus/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/cloudwatch/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/datadog/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/denier/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/list/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/memquota/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/opa/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/prometheus/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/redisquota/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/statsd/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stdio/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/zipkin/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/apikey/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/authorization/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/edge/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/kubernetes/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/listentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/logentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/metric/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/quota/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/tracespan/index.html
  content/en/docs/reference/config/security/v1beta1/authorization-policy/index.html
  data/analysis.yaml
Labels: cla: yes, size/XXL

#5131 The current global hub and tag defaults are only for dev
  content/en/docs/reference/config/installation-options/index.md
Labels: cla: yes, size/XS

#5143 Added references to glossary
  content/en/docs/reference/glossary/routing-rules.md
  content/en/docs/reference/glossary/virtual-service.md
  content/en/docs/reference/glossary/workload.md
Labels: cla: yes, ok-to-test, size/XS

#5144 Adds missing serial comma to README.md
  README.md
Labels: cla: yes, needs-ok-to-test, size/XS

#5122 1.3.3 release notes
  content/en/news/2019/announcing-1.3.3/index.md
Labels: cla: yes, size/S

#5150 1.3.3 release notes
  content/en/news/2019/announcing-1.3.3/index.md
  data/args.yml
Labels: area/test and release, cla: yes, size/S

#5148 update reference docs
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/en/docs/reference/config/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/en/docs/reference/config/networking/v1alpha3/envoy-filter/index.html
  content/en/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/en/docs/reference/config/networking/v1alpha3/service-entry/index.html
  content/en/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/en/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/en/docs/reference/config/security/v1beta1/authorization-policy/index.html
Labels: cla: yes, size/L

#5147 Add doc page for 'istioctl analyze'
  content/en/docs/ops/troubleshooting/istioctl-analyze/index.md
Labels: cla: yes, size/L

#5141 Document standalone operator as alpha
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/XS

#4710 add a task about Kubernetes Services for egress
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: area/networking, cherrypick/release-1.3, cla: yes, size/L

#5139 Update fault injection percentage syntax
  content/en/docs/tasks/traffic-management/fault-injection/index.md
Labels: cla: yes, ok-to-test, size/XS

#3180 blog post: Istio as a proxy for external services
  content/en/blog/2019/proxy/index.md
Labels: cherrypick/release-1.3, cla: yes, size/L

#5138 Consolidate release-specific material into the news section.
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/blog/2017/_index.md
  content/en/blog/2018/_index.md
  content/en/blog/2019/_index.md
  content/en/docs/_index.md
  content/en/docs/ops/security/root-transition/index.md
  content/en/docs/reference/config/installation-options/index.md
  content/en/docs/setup/_index.md
  content/en/docs/setup/upgrade/_index.md
  content/en/docs/setup/upgrade/index.md
  content/en/news/2017/_index.md
  content/en/news/2017/announcing-0.3/index.md
  content/en/news/2017/announcing-0.4/index.md
  content/en/news/2018/_index.md
  content/en/news/2018/announcing-0.5/index.md
  content/en/news/2018/announcing-0.6/index.md
  content/en/news/2018/announcing-0.7/index.md
  content/en/news/2018/announcing-0.8/index.md
  content/en/news/2019/_index.md
  content/en/news/2019/announcing-1.1/_index.md
  content/en/news/2019/announcing-1.1/change-notes/index.md
  content/en/news/2019/announcing-1.1/helm-changes/index.md
  content/en/news/2019/announcing-1.1/upgrade-notes/index.md
  content/en/news/2019/announcing-1.2/_index.md
  content/en/news/2019/announcing-1.2/change-notes/index.md
  content/en/news/2019/announcing-1.2/helm-changes/index.md
  content/en/news/2019/announcing-1.2/upgrade-notes/index.md
  content/en/news/2019/announcing-1.3/_index.md
  content/en/news/2019/announcing-1.3/change-notes/index.md
  content/en/news/2019/announcing-1.3/helm-changes/index.md
  content/en/news/2019/announcing-1.3/upgrade-notes/index.md
  content/en/news/2019/announcing-1.4/_index.md
  content/en/news/2019/announcing-1.4/change-notes/index.md
  content/en/news/2019/announcing-1.4/helm-changes/index.md
  content/en/news/2019/announcing-1.4/upgrade-notes/index.md
  content/en/news/2019/istio-security-2019-005/index.md
  content/zh/docs/setup/kubernetes/_index.md
  data/args.yml
  i18n/en.toml
  layouts/_default/list.html
  layouts/partials/sidebar_level.html
  layouts/shortcodes/istio_full_version_release_year.html
  layouts/shortcodes/relnote.html
  src/sass/_all.scss
  src/sass/misc/_call-to-action.scss
  src/sass/misc/_relnote-actions.scss
  src/sass/misc/_section-index.scss
  src/sass/misc/_see-also.scss
  src/ts/overlays.ts
Labels: cla: yes, size/XXL

#5160 manual merge of https://github.com/istio/istio.io/pull/3180 into 1.3
  content/en/blog/2019/proxy/index.md
Labels: cla: yes, size/L

#5146 A compromise PR of a long original work
  Makefile.core.mk
  content/en/docs/setup/install/standalone-operator/index.md
  scripts/grab_operator_yamls.sh
  static/operator-profile-default.yaml
  static/operator-profile-demo-auth.yaml
  static/operator-profile-demo.yaml
  static/operator-profile-minimal.yaml
  static/operator-profile-sds.yaml
  static/operator.yaml
Labels: cla: yes, size/XL

#5134 Automatically add a warning to older blog posts about them being potentially out of date
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/blog/2017/0.1-auth/index.md
  content/en/blog/2017/0.1-canary/index.md
  content/en/blog/2017/0.1-using-network-policy/index.md
  content/en/blog/2017/adapter-model/index.md
  content/en/blog/2017/mixer-spof-myth/index.md
  content/en/blog/2018/aws-nlb/index.md
  content/en/blog/2018/delayering-istio/index.md
  content/en/blog/2018/egress-https/index.md
  content/en/blog/2018/egress-mongo/index.md
  content/en/blog/2018/egress-monitoring-access-control/index.md
  content/en/blog/2018/egress-tcp/index.md
  content/en/blog/2018/export-logs-through-stackdriver/index.md
  content/en/blog/2018/hp/index.md
  content/en/blog/2018/incremental-traffic-management/index.md
  content/en/blog/2018/istio-authorization/index.md
  content/en/blog/2018/istio-twitch-stream/index.md
  content/en/blog/2018/soft-multitenancy/index.md
  content/en/blog/2018/traffic-mirroring/index.md
  content/en/blog/2018/v1alpha3-routing/index.md
  content/en/blog/2019/app-identity-and-access-adapter/index.md
  content/en/blog/2019/appswitch/index.md
  content/en/blog/2019/custom-ingress-gateway/index.md
  content/en/blog/2019/data-plane-setup/index.md
  content/en/blog/2019/egress-performance/index.md
  content/en/blog/2019/egress-traffic-control-in-istio-part-1/index.md
  content/en/blog/2019/egress-traffic-control-in-istio-part-2/index.md
  content/en/blog/2019/egress-traffic-control-in-istio-part-3/index.md
  content/en/blog/2019/evolving-istios-apis/index.md
  content/en/blog/2019/isolated-clusters/index.md
  content/en/blog/2019/istio1.1_perf/index.md
  content/en/blog/2019/knative-activator-adapter/index.md
  content/en/blog/2019/monitoring-external-service-traffic/index.md
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/blog/2019/root-transition/index.md
  content/en/blog/2019/sail-the-blog/index.md
  content/en/blog/2019/trustworthy-jwt-sds/index.md
  i18n/en.toml
  layouts/partials/primary_top.html
Labels: cla: yes, size/M

#5159 migrate Deployment apiVersion from extensions/v1beta1 to apps/v1 to support k8s 1.16
  content/en/docs/ops/app-health-check/index.md
  content/en/docs/ops/troubleshooting/validation/index.md
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
  content/en/docs/tasks/observability/logs/fluentd/index.md
  content/en/docs/tasks/security/auth-sds/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
  content/en/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes, ok-to-test, size/M

#5111 Add microservices tutorial - first modules
  .spelling
  content/en/boilerplates/work-in-progress.md
  content/en/docs/examples/microservices-istio/_index.md
  content/en/docs/examples/microservices-istio/prereq/index.md
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/en/docs/examples/microservices-istio/setup-local-computer/index.md
  content/en/docs/examples/microservices-istio/single/index.md
Labels: cla: yes, size/L

#5153 Add initial 1.4 upgrade notice
  content/en/news/2019/announcing-1.4/upgrade-notes/index.md
Labels: cla: yes, size/S

#5164 Workaround Hugo bug where it gets confused about directory parentage.
  layouts/_default/list.html
  layouts/partials/breadcrumbs.html
  layouts/partials/sidebar_level.html
  layouts/shortcodes/relnote.html
Labels: cla: yes, size/M

#5163 Better organize operations guide material
  content/en/blog/2019/data-plane-setup/index.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/ops/common-problems/_index.md
  content/en/docs/ops/common-problems/injection/index.md
  content/en/docs/ops/common-problems/network-issues/index.md
  content/en/docs/ops/common-problems/observability-issues/index.md
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/ops/common-problems/validation/index.md
  content/en/docs/ops/diagnostic-tools/_index.md
  content/en/docs/ops/diagnostic-tools/component-logging/index.md
  content/en/docs/ops/diagnostic-tools/controlz/ctrlz.png
  content/en/docs/ops/diagnostic-tools/controlz/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
  content/en/docs/ops/security/_index.md
  content/en/docs/ops/setup/_index.md
  content/en/docs/ops/setup/app-health-check/index.md
  content/en/docs/ops/telemetry/_index.md
  content/en/docs/ops/telemetry/envoy-stats/index.md
  content/en/docs/ops/traffic-management/_index.md
  content/en/docs/ops/traffic-management/deploy-guidelines/index.md
  content/en/docs/ops/troubleshooting/grafana/index.md
  content/en/docs/ops/troubleshooting/missing-traces/index.md
  content/en/docs/ops/troubleshooting/repairing-citadel/index.md
  content/en/docs/ops/troubleshooting/tcpdump-notes/index.md
  content/en/docs/setup/_index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/faq/security/k8s-health-checks.md
  content/en/news/2018/announcing-1.0.3/index.md
  content/en/news/2019/announcing-1.2/change-notes/index.md
  content/en/news/2019/announcing-1.3/_index.md
  content/en/news/2019/announcing-1.3/change-notes/index.md
  content/zh/docs/ops/security/authorization-permissive/index.md
Labels: cla: yes, size/L

#5168 Remove warning from referenced blogs
  content/en/blog/2017/0.1-canary/index.md
  content/en/blog/2019/egress-traffic-control-in-istio-part-1/index.md
  content/en/blog/2019/performance-best-practices/index.md
  i18n/en.toml
Labels: cla: yes, size/XS

#5175 Correct secure ingress task cleanup
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
Labels: cla: yes, size/S

#5173 Update reference docs.
  content/en/about/feature-stages/index.md
  content/en/blog/2018/egress-https/index.md
  content/en/blog/2018/egress-mongo/index.md
  content/en/blog/2018/egress-tcp/index.md
  content/en/blog/2018/v1alpha3-routing/index.md
  content/en/blog/2019/custom-ingress-gateway/index.md
  content/en/blog/2019/evolving-istios-apis/index.md
  content/en/blog/2019/monitoring-external-service-traffic/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/concepts/performance-and-scalability/index.md
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/examples/mesh-expansion/multi-network/index.md
  content/en/docs/examples/mesh-expansion/single-network/index.md
  content/en/docs/ops/traffic-management/locality-load-balancing/index.md
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/networking/_index.md
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/v1alpha3/_index.md
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/tasks/policy-enforcement/control-headers/index.md
  content/en/docs/tasks/security/mtls-migration/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/news/2018/announcing-1.0.3/index.md
  content/en/news/2018/announcing-1.0/index.md
  content/en/news/2019/announcing-1.1.4/index.md
  content/en/news/2019/announcing-1.2/change-notes/index.md
  content/en/news/2019/announcing-1.3/change-notes/index.md
  content/en/news/2019/announcing-1.3/upgrade-notes/index.md
  data/analysis.yaml
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XL

#5177 Fix order of entries in docs/reference.
  content/en/docs/reference/commands/_index.md
  content/en/docs/reference/config/_index.md
  content/en/docs/reference/glossary/index.md
Labels: cla: yes, size/XS

#5176 Simplify CRD check step
  content/en/boilerplates/verify-crds.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: yes, size/XS

#5181 Fix the breadcrumb studdering.
  layouts/partials/breadcrumbs.html
Labels: cla: yes, size/S

#5179 Fix typos in blog
  content/en/blog/2019/monitoring-external-service-traffic/index.md
  content/en/blog/2019/multicluster-version-routing/index.md
Labels: cla: yes, size/XS

#5182 Fix breadcrumb studdering.
  layouts/partials/breadcrumbs.html
Labels: cla: yes, size/S

#5024 Get rid of demo-auth
  content/en/docs/reference/config/installation-options/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/kubernetes/index.md
  content/en/docs/tasks/observability/kiali/index.md
  content/en/docs/tasks/security/authz-http/index.md
  content/en/docs/tasks/security/authz-permissive/index.md
  content/en/docs/tasks/security/authz-tcp/index.md
  content/en/docs/tasks/security/ca-namespace-targeting/index.md
  content/en/docs/tasks/security/health-check/index.md
  content/en/docs/tasks/security/https-overlay/index.md
  content/en/docs/tasks/security/plugin-ca-cert/index.md
  content/en/faq/security/cert-lifetime-config.md
  content/zh/docs/setup/kubernetes/additional-setup/config-profiles/index.md
  content/zh/docs/setup/kubernetes/install/helm/index.md
  content/zh/docs/setup/kubernetes/install/kubernetes/index.md
  content/zh/docs/tasks/security/health-check/index.md
  content/zh/docs/tasks/security/https-overlay/index.md
  content/zh/docs/tasks/security/plugin-ca-cert/index.md
  content/zh/docs/tasks/telemetry/metrics/querying-metrics/index.md
  content/zh/faq/security/cert-lifetime-config.md
  content/zh/faq/telemetry/disabling-zipkin.md
Labels: cherrypick/release-1.3, cla: yes, kind/docs, size/L

#5186 Update stats filter instruction to use config from istio/proxy 1.3 branch
  content/en/docs/ops/telemetry/in-proxy-service-telemetry/index.md
Labels: cla: yes, size/XS

#5178 Fix FAQ for UDP is supported
  content/en/faq/traffic-management/naming-port-convention.md
Labels: cla: yes, size/XS

#5189 Update stats filter instruction to versioned config
  content/en/docs/ops/telemetry/in-proxy-service-telemetry/index.md
Labels: cla: yes, size/XS

#5157 [release-1.3] add a task about Kubernetes Services for egress
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: cla: no, size/L

#5161 Document analyzer code IST0105
  content/en/docs/reference/config/analysis/ist0105/index.md
Labels: cla: yes, size/S

#5172 [master] The current global hub and tag defaults are only for dev
  content/en/docs/reference/config/installation-options/index.md
Labels: cla: yes, size/XS

#5187 Add year-free aliases for release announcements.
  content/en/news/2017/announcing-0.1/index.md
  content/en/news/2017/announcing-0.2/index.md
  content/en/news/2017/announcing-0.3/index.md
  content/en/news/2017/announcing-0.4/index.md
  content/en/news/2018/announcing-0.5/index.md
  content/en/news/2018/announcing-0.6/index.md
  content/en/news/2018/announcing-0.7/index.md
  content/en/news/2018/announcing-0.8/index.md
  content/en/news/2018/announcing-1.0.1/index.md
  content/en/news/2018/announcing-1.0.2/index.md
  content/en/news/2018/announcing-1.0.3/index.md
  content/en/news/2018/announcing-1.0.4/index.md
  content/en/news/2018/announcing-1.0.5/index.md
  content/en/news/2018/announcing-1.0/index.md
  content/en/news/2019/announcing-1.0.6/index.md
  content/en/news/2019/announcing-1.0.7/index.md
  content/en/news/2019/announcing-1.0.8/index.md
  content/en/news/2019/announcing-1.0.9/index.md
  content/en/news/2019/announcing-1.1.1/index.md
  content/en/news/2019/announcing-1.1.10/index.md
  content/en/news/2019/announcing-1.1.11/index.md
  content/en/news/2019/announcing-1.1.12/index.md
  content/en/news/2019/announcing-1.1.13/index.md
  content/en/news/2019/announcing-1.1.14/index.md
  content/en/news/2019/announcing-1.1.15/index.md
  content/en/news/2019/announcing-1.1.16/index.md
  content/en/news/2019/announcing-1.1.2/index.md
  content/en/news/2019/announcing-1.1.3/index.md
  content/en/news/2019/announcing-1.1.4/index.md
  content/en/news/2019/announcing-1.1.5/index.md
  content/en/news/2019/announcing-1.1.6/index.md
  content/en/news/2019/announcing-1.1.7/index.md
  content/en/news/2019/announcing-1.1.8/index.md
  content/en/news/2019/announcing-1.1.9/index.md
  content/en/news/2019/announcing-1.1/_index.md
  content/en/news/2019/announcing-1.2.1/index.md
  content/en/news/2019/announcing-1.2.2/index.md
  content/en/news/2019/announcing-1.2.3/index.md
  content/en/news/2019/announcing-1.2.4/index.md
  content/en/news/2019/announcing-1.2.5/index.md
  content/en/news/2019/announcing-1.2.6/index.md
  content/en/news/2019/announcing-1.2.7/index.md
  content/en/news/2019/announcing-1.2/_index.md
  content/en/news/2019/announcing-1.3.1/index.md
  content/en/news/2019/announcing-1.3.2/index.md
  content/en/news/2019/announcing-1.3.3/index.md
  content/en/news/2019/announcing-1.3/_index.md
  content/en/news/2019/announcing-1.4/_index.md
Labels: cla: yes, size/M

#5190 Fixed pinned branch references.
  content/en/blog/2017/adapter-model/index.md
  content/en/docs/ops/security/root-transition/index.md
  content/en/docs/reference/config/policy-and-telemetry/expression-language/index.md
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/S

#5026 update doc for http prob annotation
  content/en/docs/ops/app-health-check/index.md
Labels: cherrypick/master, cla: yes, size/XS

#5192 [master] update doc for http prob annotation
  content/en/docs/ops/setup/app-health-check/index.md
Labels: cla: no, size/XS

#5193 update logging-stack.yaml in Logging with Fluentd documentation
  content/en/docs/tasks/telemetry/logs/fluentd/index.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/S

#5194 [master] update logging-stack.yaml in Logging with Fluentd documentation
  content/en/docs/tasks/observability/logs/fluentd/index.md
Labels: cla: no, size/S

#5174 update upgrade notes with CRD schema instructions
  .spelling
  content/en/news/2019/announcing-1.4/upgrade-notes/index.md
Labels: cla: yes, size/S

#5191 remove deprecated authz permissive task
  content/en/docs/tasks/security/_index.md
  content/en/docs/tasks/security/authz-permissive/index.md
Labels: area/security, cla: yes, size/L

#5195 Remove experimental from istioctl manifest and profile commands
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/M

#5201 Added references to glossary
  content/en/docs/reference/glossary/adapters.md
  content/en/docs/reference/glossary/service-registry.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5002 Update index.md
  content/en/docs/tasks/observability/kiali/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5202 [release-1.3] Update index.md
  content/en/docs/tasks/telemetry/kiali/index.md
Labels: cla: no, size/XS

#5203 Update reference docs.
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
Labels: cla: yes, size/L

#5206 Remove unnecessary backslashes from example SVID
  content/en/docs/concepts/security/index.md
Labels: cherrypick/release-1.3, cla: yes, kind/docs, ok-to-test, size/XS

#5207 Add missing backticks to display example DNS name
  content/en/docs/examples/mesh-expansion/multi-network/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5208 Added references to glossary
  content/en/docs/reference/glossary/service-mesh.md
  content/en/docs/reference/glossary/workload.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5209 Updated formatting of Virtual Service in docs
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5183 modify watch namespace to only Istio-operator
  content/en/docs/setup/install/standalone-operator/index.md
  scripts/grab_operator_yamls.sh
  static/operator.yaml
Labels: cla: yes, size/L

#5205 Improve snippet logic.
  Makefile.core.mk
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/docs/tasks/security/authz-http/index.md
  examples/TestAuthorizationForHTTPServices.txt
  layouts/partials/code_block.html
  scripts/grab_examples.sh
Labels: cla: yes, size/L

#5210 Prevent lint failures for web sites that are timing out.
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#5113 Upgrade SidecarAPI to Beta
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/XS

#5156 Revert port back to 9411
  content/en/docs/tasks/observability/distributed-tracing/jaeger/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5211 Quote jsonpath to support zsh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5212 [release-1.3] Revert port back to 9411
  content/en/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
Labels: cla: no, size/XS

#5204 Operator docs fixes
  content/en/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, kind/docs, size/S

#5169 1.1.17 release notes and final EOL announcement
  content/en/news/2019/announcing-1.1-eol-final/index.md
  content/en/news/2019/announcing-1.1.17/index.md
Labels: cherrypick/release-1.3, cla: yes, size/M

#5213 [release-1.3] 1.1.17 release notes and final EOL announcement
  content/en/news/2019/announcing-1.1-eol-final/index.md
  content/en/news/2019/announcing-1.1.17/index.md
Labels: cla: yes, size/M

#5217 Fix broken Helm links
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, kind/docs, size/XS

#4811 Update docs for CoreDNS newer than 1.3.2
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: area/environments, cla: yes, kind/docs, size/M

#5227 Clean up config profiles page
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, size/S

#5225 Clean up pod requirement around protocol naming
  content/en/docs/setup/additional-setup/requirements/index.md
Labels: cla: yes, size/S

#5229 Fix ordering between setup and prereq pages
  content/en/docs/examples/microservices-istio/prereq/index.md
Labels: cla: yes, kind/docs, size/XS

#5228 Put text into a text box
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: cla: yes, kind/docs, size/XS

#5226 Fix protocol sniffing docs
  content/en/docs/ops/traffic-management/protocol-selection/index.md
Labels: cla: yes, size/S

#5230 update user guide
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: area/security, cla: yes, kind/docs, size/M

#5232 Add link to enabling policy enforcement
  content/en/docs/concepts/policies/index.md
Labels: cla: yes, kind/docs, size/XS

#5223 Remove links to istio-ecosystem.
  content/en/blog/2019/isolated-clusters/index.md
  content/en/news/2019/announcing-1.2/change-notes/index.md
Labels: cla: yes, size/S

#5235 Update index.md
  content/en/blog/2019/proxy/index.md
Labels: cla: yes, kind/docs, size/XS

#5216 Add documentation for galley.enableAnalysis
  .spelling
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: yes, kind/docs, size/M

#5236 Remove one last mention of demo-auth
  content/en/docs/setup/install/helm/index.md
  content/en/docs/tasks/security/health-check/index.md
Labels: cla: yes, size/M

#5238 Add warning for kubectl rollout restart
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, size/XS

#5237 - 1.2.8 release notes
  .spelling
  content/en/news/2019/announcing-1.2.8/index.md
Labels: area/test and release, cherrypick/release-1.3, cla: yes, size/M

#5219 Update istioctl auth tls-check example to reflect https://github.com/istio/istio/pull/17720
  content/en/docs/tasks/security/mutual-tls/index.md
  content/en/faq/security/check-policy.md
Labels: area/security, cla: yes, size/S

#5242 Fill in the script to grab example snippets from GCS buckets.
  scripts/grab_examples.sh
Labels: cla: yes, size/M

#5244 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/M

#5246 remove kubectl explain in upgrade notes
  content/en/news/2019/announcing-1.4/upgrade-notes/index.md
Labels: cla: yes, kind/docs, size/XS

#5241 [release-1.3] - 1.2.8 release notes
  .spelling
  content/en/news/2019/announcing-1.2.8/index.md
Labels: cla: yes, size/M

#5247 [release-1.3] Fix broken Helm links
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS

#5240 Fix istioctl analyze example
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: yes, kind/docs, size/XS

#5251 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/check_clean_repo.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/S

#5233 update user guide for workload SDS
  content/en/docs/tasks/security/auth-sds/index.md
Labels: area/security, cla: yes, kind/docs, size/XS

#5252 Fix formatting issues.
  content/en/docs/setup/install/kubernetes/index.md
Labels: cla: yes, size/S

#5254 Revert "[release-1.3] add a task about Kubernetes Services for egress"
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: cla: yes, size/L

#5253 Add `and` to description
  content/en/docs/concepts/what-is-istio/index.md
Labels: cla: yes, kind/docs, size/XS

#5256 Move pages out from the Concepts section
  content/en/blog/2018/egress-https/index.md
  content/en/blog/2019/app-identity-and-access-adapter/index.md
  content/en/blog/2019/data-plane-setup/index.md
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/examples/mesh-expansion/multi-network/index.md
  content/en/docs/examples/mesh-expansion/single-network/index.md
  content/en/docs/examples/multicluster/_index.md
  content/en/docs/examples/multicluster/gke/index.md
  content/en/docs/examples/multicluster/icp/index.md
  content/en/docs/ops/architecture/arch.svg
  content/en/docs/ops/architecture/discovery.svg
  content/en/docs/ops/architecture/index.md
  content/en/docs/ops/performance-and-scalability/index.md
  content/en/docs/ops/performance-and-scalability/latency_p90.svg
  content/en/docs/ops/traffic-management/introduction/index.md
  content/en/docs/reference/glossary/mesh-federation.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/deployment-models/cluster-iso.svg
  content/en/docs/setup/deployment-models/cluster-ns.svg
  content/en/docs/setup/deployment-models/exp-ns.svg
  content/en/docs/setup/deployment-models/failover.svg
  content/en/docs/setup/deployment-models/index.md
  content/en/docs/setup/deployment-models/iso-ns.svg
  content/en/docs/setup/deployment-models/multi-cluster.svg
  content/en/docs/setup/deployment-models/multi-control.svg
  content/en/docs/setup/deployment-models/multi-mesh.svg
  content/en/docs/setup/deployment-models/multi-net.svg
  content/en/docs/setup/deployment-models/multi-trust.svg
  content/en/docs/setup/deployment-models/shared-control.svg
  content/en/docs/setup/deployment-models/single-cluster.svg
  content/en/docs/setup/deployment-models/single-net.svg
  content/en/docs/setup/deployment-models/single-trust.svg
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/en/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
  content/en/news/2019/announcing-1.1/_index.md
  content/en/news/2019/announcing-1.1/change-notes/index.md
  content/en/news/2019/announcing-1.3/_index.md
Labels: cla: yes, kind/docs, size/L

#5269 Update reference docs.
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/en/docs/reference/config/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/circonus/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/cloudwatch/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/datadog/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/denier/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/list/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/memquota/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/prometheus/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/redisquota/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/statsd/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stdio/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/apikey/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/authorization/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/edge/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/kubernetes/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/listentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/logentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/metric/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/quota/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/tracespan/index.html
  content/en/docs/reference/config/security/v1beta1/authorization-policy/index.html
  content/en/docs/setup/install/operator/index.md
  content/en/news/2019/announcing-1.3/change-notes/index.md
  data/analysis.yaml
  examples/tasks__security__authorization_for_http_services.snippets.txt
  examples/tasks__traffic_management__mirroring.snippets.txt
  static/operator-profile-default.yaml
  static/operator-profile-demo.yaml
  static/operator-profile-minimal.yaml
  static/operator-profile-sds.yaml
  static/operator.yaml
Labels: cla: yes, size/XXL

#5271 Update reference docs.
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istio_ca/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/node_agent/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
Labels: cla: yes, size/XS

#5274 Experiment with improved istioctl TOC layout.
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  layouts/partials/toc.html
Labels: cla: yes, size/XXL

#5268 Remove kubectl from the spelling dictionary.
  .spelling
  content/en/docs/examples/microservices-istio/setup-local-computer/index.md
Labels: cla: yes, size/XS

#5273 Change multicluster and CNI instructions to use istioctl
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
Labels: cla: yes, size/L

#5276 fix operator doc.
  content/en/docs/setup/install/standalone-operator/index.md
Labels: area/environments, cla: yes, size/XS

#5270 Deprecate helm install
  content/en/blog/2018/egress-https/index.md
  content/en/blog/2018/egress-mongo/index.md
  content/en/blog/2018/egress-tcp/index.md
  content/en/docs/concepts/security/index.md
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/en/docs/ops/common-problems/validation/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
  content/en/docs/ops/security/harden-docker-images/index.md
  content/en/docs/ops/setup/app-health-check/index.md
  content/en/docs/ops/telemetry/in-proxy-service-telemetry/index.md
  content/en/docs/ops/traffic-management/locality-load-balancing/index.md
  content/en/docs/ops/traffic-management/protocol-selection/index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/kubernetes/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/en/docs/setup/install/operator/index.md
  content/en/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/en/docs/tasks/observability/gateways/index.md
  content/en/docs/tasks/observability/kiali/index.md
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/index.md
  content/en/docs/tasks/policy-enforcement/enabling-policy/index.md
  content/en/docs/tasks/security/auth-sds/index.md
  content/en/docs/tasks/security/authn-policy/index.md
  content/en/docs/tasks/security/ca-namespace-targeting/index.md
  content/en/docs/tasks/security/health-check/index.md
  content/en/docs/tasks/security/https-overlay/index.md
  content/en/docs/tasks/security/mtls-migration/index.md
  content/en/docs/tasks/security/plugin-ca-cert/index.md
  content/en/docs/tasks/security/rbac-groups/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
  layouts/shortcodes/istioctl.html
Labels: cla: yes, size/L

#5277 Move standalone-operator install to ops section
  content/en/docs/ops/setup/standalone-operator/index.md
Labels: cla: yes, size/XS

#5264 add a cleanup subsection to set desired outbound traffic policy mode
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: cla: yes, kind/docs, size/M

#5279 Make quick-start quicker
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/install/kubernetes/index.md
Labels: cla: yes, size/XS

#5261 add port name "tls" to both Service and Endpoints in Kubernetes Services for Egress task
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: cla: yes, kind/docs, size/XS

#5263 Fix certificates generation in secure gateways
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
Labels: cla: yes, kind/docs, size/L

#5280 Standalone operator update
  scripts/grab_operator_yamls.sh
  static/operator-profile-default.yaml
  static/operator-profile-demo.yaml
  static/operator-profile-minimal.yaml
  static/operator-profile-sds.yaml
  static/operator.yaml
Labels: cla: yes, size/M

#5284 Improvements to install with istioctl guide
  content/en/docs/setup/install/kubernetes/index.md
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/L

#5245 istioctl upgrade feature docs
  content/en/docs/setup/upgrade/_index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/docs/setup/upgrade/istioctl-upgrade/index.md
  content/en/news/2019/istio-security-2019-005/index.md
Labels: cla: yes, kind/docs, size/L

#5290 Update reference docs.
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istio_ca/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/node_agent/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
Labels: cla: yes, size/XXL

#5288 Fix broken links
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/examples/multicluster/_index.md
  content/en/docs/examples/multicluster/gke/index.md
  content/en/docs/examples/multicluster/icp/index.md
  content/en/docs/reference/glossary/mesh-federation.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/en/news/2019/announcing-1.1/_index.md
  content/en/news/2019/announcing-1.3/_index.md
Labels: cla: yes, size/M

#5292 Update reference docs.
  content/en/docs/reference/commands/operator/index.html
Labels: cla: yes, size/S

#5293 Update multicluster instructions
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
Labels: cla: yes, size/S

#5295 Remove bad aliases
  content/en/docs/setup/upgrade/_index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/docs/setup/upgrade/istioctl-upgrade/index.md
Labels: cla: yes, size/S

#5306 Add oreilly.com to lint exceptions
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#5196 update authorization for TCP task for v1beta1 policy
  content/en/docs/tasks/security/authz-tcp/index.md
Labels: cla: yes, size/L

#5302 Clarify istioctl install support for helm options
  .spelling
  content/en/docs/reference/config/installation-options/index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/L

#5303 [release-1.3] Update docs for CoreDNS newer than 1.3.2
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: no, size/M

#5311 Remove uses of istio-demo.yaml
  content/en/docs/ops/setup/standalone-operator/index.md
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
  content/en/docs/tasks/security/https-overlay/index.md
  content/en/faq/distributed-tracing/no-tracing.md
  content/en/faq/security/cert-lifetime-config.md
  content/en/faq/security/mysql-with-mtls.md
Labels: cla: yes, size/S

#5309 remove completed pods
  content/en/docs/setup/install/kubernetes/index.md
Labels: cla: yes, size/XS
