Repository istio/istio.io, pull requests merged in 2019-07, with the labels that each got.

#4624 zh: fix debug pilot doc.
  content_zh/docs/ops/traffic-management/proxy-cmd/index.md
Labels: cla: yes, kind/docs

#4623 Document upgrade steps for Istio CNI (#4518)
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes

#4627 Fix doc broken link
  content/docs/concepts/observability/index.md
Labels: action/merge-to-release-branch, cla: yes, kind/docs

#4356 Add clarity to transport auth section, inc new mode param
  content/docs/concepts/security/index.md
Labels: cla: yes

#4354 Add clarification on behaviour in absence of policy
  content/docs/concepts/security/index.md
Labels: action/merge-to-release-branch, cla: yes

#4633 1.1.11 release notes.
  content/about/notes/1.1.11/index.md
  content/blog/2019/announcing-1.1.11/index.md
  content/boilerplates/notes/1.1.11.md
Labels: action/merge-to-release-branch, cla: yes

#4628 fix error command.
  content_zh/docs/ops/traffic-management/observing/index.md
Labels: cla: yes, kind/docs

#4640 fix error in the jsonpath selector
  content/docs/tasks/telemetry/logs/access-log/index.md
Labels: action/merge-to-master, cla: yes

#4639 Show the URL for the Mixer self-monitoring endpoint
  content/docs/ops/telemetry/missing-metrics/index.md
Labels: action/merge-to-release-branch, cla: no

#4635 Adds blog post: performance benchmarking best practices
  .spelling
  content/blog/2019/performance-best-practices/cpu_max.png
  content/blog/2019/performance-best-practices/index.md
  content/blog/2019/performance-best-practices/latency_p50.png
  content/blog/2019/performance-best-practices/latency_p90.png
  content/blog/2019/performance-best-practices/latency_p99.png
Labels: action/merge-to-release-branch, area/perf and scalability, cla: yes

#4645 fix a typo: though -> through
  content/blog/2019/egress-traffic-control-in-istio-part-1/index.md
Labels: action/merge-to-release-branch, cla: yes

#4636 More traffic management corrections
  content/docs/concepts/traffic-management/index.md
Labels: action/merge-to-release-branch, cla: yes

#4649 Clarifies latency measurement section for Istio 1.2
  content/blog/2019/performance-best-practices/index.md
Labels: action/merge-to-release-branch, area/perf and scalability, cla: yes

#4638 Cleanup multicluster doc
  content/blog/2019/announcing-1.1/index.md
  content/blog/2019/multicluster-version-routing/index.md
  content/boilerplates/notes/1.1.md
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/examples/multicluster/_index.md
  content/docs/examples/multicluster/gke/index.md
  content/docs/examples/multicluster/icp/index.md
  content/docs/setup/kubernetes/additional-setup/config-profiles/index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/install/multicluster/_index.md
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
  content/docs/setup/kubernetes/install/multicluster/shared-gateways/diagram.svg
  content/docs/setup/kubernetes/install/multicluster/shared-gateways/index.md
  content/docs/setup/kubernetes/install/multicluster/shared-vpn/index.md
  content/docs/setup/kubernetes/install/multicluster/shared-vpn/multicluster-with-vpn.svg
  content/docs/setup/kubernetes/install/platform/_index.md
  content/docs/setup/kubernetes/install/platform/alicloud/index.md
  content/docs/setup/kubernetes/install/platform/gke/index.md
  content/docs/setup/kubernetes/install/platform/ibm/index.md
  content/docs/tasks/multicluster/gateways/index.md
  content_zh/docs/setup/kubernetes/additional-setup/config-profiles/index.md
  content_zh/docs/setup/kubernetes/install/multicluster/vpn/index.md
  content_zh/docs/tasks/multicluster/split-horizon-eds/index.md
Labels: action/merge-to-release-branch, cla: yes

#4647 doc(concepts): fix indentation
  content/docs/concepts/traffic-management/index.md
Labels: action/merge-to-release-branch, cla: no, kind/docs

#4232 Egress blog part 2
  .spelling
  content/blog/2019/egress-traffic-control-in-istio-part-1/index.md
  content/blog/2019/egress-traffic-control-in-istio-part-2/SecurityArchitectureWithL3Firewalls.svg
  content/blog/2019/egress-traffic-control-in-istio-part-2/index.md
Labels: cla: yes

#4644 Add our first glossary entries for the documentation
  content/docs/concepts/what-is-istio/index.md
  content/docs/reference/glossary/pod.md
Labels: action/merge-to-release-branch, cla: yes, kind/docs

#4651 duplicate feature in traffic management section
  content/about/feature-stages/index.md
Labels: action/merge-to-release-branch, cla: yes, kind/docs

#4658 Fix bad links
  content/docs/setup/kubernetes/_index.md
Labels: action/merge-to-release-branch, cla: yes

#4653 Dest rule evaluation subtlety
  content/docs/concepts/traffic-management/destination-rules-1.svg
  content/docs/concepts/traffic-management/index.md
  content/docs/ops/traffic-management/troubleshooting/index.md
Labels: action/merge-to-release-branch, cla: yes

#4666 Turn on mergify strict mode and add missing alias
  .mergify.yml
  content/docs/ops/_index.md
Labels: action/merge-to-release-branch, cla: yes

#4665 use role instead of clusterrole in egress gateway deployment
  content/blog/2018/egress-mongo/index.md
  content/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content_zh/blog/2018/egress-mongo/index.md
  content_zh/docs/tasks/traffic-management/edge-traffic/wildcard-egress-hosts/index.md
Labels: action/merge-to-release-branch, area/environments, cla: yes

#4668 Fix typo
  content/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: action/merge-to-master, cla: yes, kind/docs

#4667 Turn on mergify strict mode and add missing alias (#4666)
  .mergify.yml
  content/docs/ops/_index.md
Labels: cla: yes

#4664 Gateway instruction correction
  content/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: action/merge-to-release-branch, cla: no

#4677 Document preference to using an NLB with gateways
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
Labels: cla: yes, size/S

#4676 remove duplicated row for cert management
  content/about/feature-stages/index.md
Labels: action/merge-to-master, cla: yes, size/XS

#4675 Updating the bash script for upgrading sidecar
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: action/merge-to-master, area/user experience, cla: yes, kind/docs, size/XS

#4674 Improve control for auto-cherry picking to specific release branches.
  .mergify.yml
Labels: cla: yes

#4682 Added glossary entry for virtual service
  content/docs/reference/glossary/virtual-service.md
Labels: cla: yes, kind/docs, size/XS

#4684 Loblaw Digital in action
  content/about/community/customers/index.md
  content/about/community/customers/loblaw-digital.png
Labels: cla: yes, kind/docs, size/XS

#4683 Adds Scytale.io as a partner
  content/about/community/partners/index.md
  content/about/community/partners/scytale.svg
Labels: action/merge-to-release-1.2-branch, cla: yes, kind/docs, size/S

#4681 Add flexe to list of customers
  content/about/community/customers/flexe.svg
  content/about/community/customers/index.md
  content_zh/about/community/customers/index.md
Labels: action/merge-to-release-1.2-branch, cla: yes, kind/docs, size/XS

#4689 Put apporbit.com on the exception list since their site is down.
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#4680 Fix install CRD steps on various pages
  content/docs/examples/multicluster/gke/index.md
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
  content/docs/tasks/security/vault-ca/index.md
Labels: action/merge-to-release-1.2-branch, cla: yes, size/S

#4692 Add distroless as a core feature for 1.3.
  .spelling
  content/about/feature-stages/index.md
Labels: cla: yes, kind/docs, size/XS

#4637 Egress blog part 3
  content/blog/2019/egress-traffic-control-in-istio-part-1/index.md
  content/blog/2019/egress-traffic-control-in-istio-part-2/index.md
  content/blog/2019/egress-traffic-control-in-istio-part-3/index.md
Labels: action/merge-to-release-branch, cla: yes, size/L

#4691 Add cross-namespace configuration info in op guide
  content/blog/2018/delayering-istio/index.md
  content/docs/ops/traffic-management/deploy-guidelines/index.md
  content/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content_zh/blog/2018/delayering-istio/index.md
Labels: action/merge-to-release-1.2-branch, cla: yes, size/M

#4702 Point /charts/ at GCS directly instead of gcsweb.
  layouts/index.redir
Labels: area/test and release, cla: yes, size/XS

#4703 Grammar improvements
  content/docs/ops/traffic-management/deploy-guidelines/index.md
Labels: action/merge-to-release-1.2-branch, cla: yes, size/S

#4706 Softonic in action
  content/about/community/customers/index.md
  content/about/community/customers/softonic.png
Labels: action/merge-to-release-1.2-branch, cla: yes, size/XS

#4711 Add routing rules to the glossary
  content/docs/reference/glossary/routing-rules.md
Labels: cla: yes, kind/docs, size/XS

#4717 Rename multiple control planes multi cluster pattern
  content/blog/2019/announcing-1.1/index.md
  content/blog/2019/multicluster-version-routing/index.md
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/examples/multicluster/gke/index.md
  content/docs/examples/multicluster/icp/index.md
  content/docs/setup/kubernetes/additional-setup/config-profiles/index.md
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
  content/docs/setup/kubernetes/install/multicluster/shared-gateways/index.md
  content_zh/docs/setup/kubernetes/additional-setup/config-profiles/index.md
  content_zh/docs/tasks/multicluster/gateways/index.md
Labels: action/merge-to-release-1.2-branch, area/environments, area/networking, cla: yes, size/M

#4720 clarify text and fix typo under quick start
  content/docs/setup/kubernetes/install/kubernetes/index.md
Labels: cla: yes, kind/docs, size/XS

#4712 Fix link to issue 2160 on the release note for Istio 1.1.9
  content/boilerplates/notes/1.1.9.md
Labels: action/merge-to-release-1.2-branch, cla: yes, kind/docs, size/XS

#4722 Use updated container, now built in the tools repo.
  .circleci/config.yml
  Makefile
  scripts/Dockerfile
  scripts/build_and_push_docker.sh
Labels: cla: yes, size/M

#4727 Fix broken link in blog related to Traffic Mirroring
  content/blog/2018/traffic-mirroring/index.md
  content_zh/blog/2018/traffic-mirroring/index.md
Labels: action/merge-to-release-1.2-branch, cla: yes, kind/docs, size/XS

#4660 fix number err from `5` to `2`
  content_zh/boilerplates/verify-crds.md
  content_zh/docs/setup/kubernetes/install/helm/index.md
Labels: cla: yes, kind/docs, size/S

#4080 Add outlier check column in proxy config command
  content/docs/ops/traffic-management/proxy-cmd/index.md
Labels: cla: yes, size/XS

#4733 Pass user ID to docker.
  Makefile
Labels: cla: yes, size/XS

#4737 Update reference docs.
  content/boilerplates/notes/1.2.md
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/operator/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/annotations/index.html
  content/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/docs/reference/config/istio.authentication.v1alpha1/index.html
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/docs/reference/config/networking/v1alpha3/envoy-filter/index.html
  content/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/redisquota/index.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XXL

#4743 WIP: Switch to Tide & Mergify for this repo.
  .circleci/config.yml
  .mergify.yml
  Makefile
Labels: cla: yes, do-not-merge, do-not-merge/work-in-progress, size/M

#4745 Trivial change to test out tide+prow.
  README.md
Labels: cla: yes, size/XS
