Repository istio/istio.io, pull requests merged in 2019-08, with the labels that each got.

#4740 Fix broken link in Quick Start Evaluation Install
  content/docs/setup/kubernetes/install/kubernetes/index.md
Labels: cla: yes, kind/docs, size/XS

#4748 Change the security vulnerability report mailing list address.
  content/about/security-vulnerabilities/index.md
  content_zh/about/security-vulnerabilities/index.md
Labels: cherrypick/release-1.2, cla: yes, size/XS

#4749 [release-1.2] Change the security vulnerability report mailing list address.
  content/about/security-vulnerabilities/index.md
  content_zh/about/security-vulnerabilities/index.md
Labels: cla: yes, size/XS

#4750 Switch to Tide & Mergify for this repo. (#4743)
  .circleci/config.yml
  .mergify.yml
  Makefile
Labels: cla: yes, size/M

#4754 Istio 1.2.2 1.2.1 annoucements cherrypick to master
  content/about/notes/1.2.1/index.md
  content/about/notes/1.2.2/index.md
  content/blog/2019/announcing-1.2.1/index.md
  content/blog/2019/announcing-1.2.2/index.md
  content/boilerplates/notes/1.2.1.md
  content/boilerplates/notes/1.2.2.md
Labels: cla: yes, size/M

#4756 1.1.12 release notes
  content/about/notes/1.1.12/index.md
  content/blog/2019/announcing-1.1.12/index.md
  content/boilerplates/notes/1.1.12.md
Labels: cherrypick/release-1.2, cla: yes, kind/docs, size/S

#4755 Add release notes for Istio 1.2.3
  content/about/notes/1.2.3/index.md
  content/blog/2019/announcing-1.2.3/index.md
  content/blog/2019/cve-2019-12995/index.md
  content/boilerplates/notes/1.2.3.md
Labels: cherrypick/release-1.2, cla: yes, size/M

#4757 [release-1.2] 1.1.12 release notes
  content/about/notes/1.1.12/index.md
  content/blog/2019/announcing-1.1.12/index.md
  content/boilerplates/notes/1.1.12.md
Labels: cla: yes, size/S

#4758 [release-1.2] Add release notes for Istio 1.2.3
  content/about/notes/1.2.3/index.md
  content/blog/2019/announcing-1.2.3/index.md
  content/blog/2019/cve-2019-12995/index.md
  content/boilerplates/notes/1.2.3.md
Labels: cla: yes, size/M

#4753 Add Solo.io to list of partners
  content/about/community/partners/index.md
Labels: cherrypick/master, cla: yes, size/XS

#4761 add istio.io/operator as vanity URL
  layouts/index.redir
  static/golang/operator.html
Labels: area/config, cherrypick/release-1.2, cla: yes, kind/docs, size/XS

#4762 [release-1.2] add istio.io/operator as vanity URL
  layouts/index.redir
  static/golang/operator.html
Labels: cla: no, size/XS

#4764 [master] Add Solo.io to list of partners
  content/about/community/partners/index.md
Labels: cla: no, size/XS

#4767 Fix solo logo and text.
  content/about/community/partners/index.md
  content/about/community/partners/solo.webp
Labels: cherrypick/release-1.2, cla: yes, size/XS

#4771 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/annotations/index.html
  content/docs/reference/config/networking/v1alpha3/envoy-filter/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/app-identity-access-adapter/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/denier/index.html
  content/docs/reference/config/policy-and-telemetry/templates/tracespan/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/L

#4768 [release-1.2] Fix solo logo and text.
  content/about/community/partners/index.md
  content/about/community/partners/solo.webp
Labels: cla: yes, size/XS

#4763 istio api evolution blog post
  .spelling
  content/blog/2019/evolving-istios-apis/index.md
Labels: cherrypick/release-1.2, cla: yes, kind/docs, size/M

#4759 Document how and why to use distroless variant
  .spelling
  content/about/feature-stages/index.md
  content/docs/ops/security/harden-docker-images/index.md
Labels: area/environments, area/security, cla: yes, kind/docs, size/M

#4713 Mesh Expansion with gateways
  content/blog/2018/egress-tcp/index.md
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/examples/mesh-expansion/_index.md
  content/docs/examples/mesh-expansion/gateways/index.md
  content/docs/examples/mesh-expansion/shared-vpn/_index.md
  content/docs/examples/mesh-expansion/shared-vpn/integrating-vms/index.md
  content/docs/examples/mesh-expansion/shared-vpn/integrating-vms/mesh-expansion.svg
  content/docs/examples/mesh-expansion/shared-vpn/setups/index.md
  content/docs/setup/kubernetes/_index.md
  content/docs/tasks/security/health-check/index.md
  content/faq/security/cert-lifetime-config.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/docs/examples/mesh-expansion/_index.md
  content_zh/docs/examples/mesh-expansion/shared-vpn/_index.md
  content_zh/docs/examples/mesh-expansion/shared-vpn/integrating-vms/index.md
Labels: area/environments, area/user experience, cla: yes, do-not-merge, size/XL

#4785 Jblatt 1 2 4 and 1 1 13
  .spelling
  content/about/notes/1.1.13/index.md
  content/about/notes/1.2.4/index.md
  content/blog/2019/announcing-1.1.13/index.md
  content/blog/2019/announcing-1.2.4/index.md
  content/blog/2019/istio-security-003-004/index.md
  content/boilerplates/notes/1.1.13.md
  content/boilerplates/notes/1.2.4.md
Labels: cherrypick/master, cla: human-approved, cla: yes, size/L

#4786 Fix bad list formatting.
  content/blog/2019/istio-security-003-004/index.md
  content/boilerplates/notes/1.1.13.md
  content/boilerplates/notes/1.2.4.md
Labels: cla: yes, size/M

#4774 [release-1.2] istio api evolution blog post (#4763)
  .spelling
  content/blog/2019/evolving-istios-apis/index.md
Labels: cherrypick/master, cla: yes, do-not-merge, kind/docs, size/M

#4784 Followup of #4713 to better organize mesh expansion examples
  content/blog/2018/egress-tcp/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/examples/mesh-expansion/bookinfo-expanded/index.md
  content/docs/examples/mesh-expansion/bookinfo-expanded/mesh-expansion.svg
  content/docs/examples/mesh-expansion/multi-network/index.md
  content/docs/examples/mesh-expansion/shared-vpn/_index.md
  content/docs/examples/mesh-expansion/single-network/index.md
  content/faq/security/cert-lifetime-config.md
  content_zh/docs/examples/mesh-expansion/shared-vpn/integrating-vms/index.md
Labels: cla: yes, size/M

#4792 Announce upcoming 1.1 EOL.
  content/en/blog/2019/announcing-1.1-eol/index.md
Labels: area/test and release, cherrypick/release-1.2, cherrypick/release-1.3, cla: yes, kind/docs, size/S

#4795 Cherrypick 1.1 EOL warning to release branch
  content/blog/2019/announcing-1.1-eol/index.md
Labels: area/test and release, cla: yes, kind/docs, size/S

#4797 Update latest release
  data/args.yml
Labels: area/test and release, cla: yes, kind/docs, size/XS

#4799 Add a lint rule to prevent us forgetting to update the site version.
  layouts/shortcodes/relnote.html
Labels: cla: yes, size/S

#4801 Modify build_site.sh to work with new build-tools image
  Makefile.core.mk
  scripts/build_site.sh
Labels: cla: yes, size/S

#4804 Get istio.io working with BUILD_WITH_CONTAINER=1
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  Makefile.overrides.mk
  SUPPORT.md
Labels: cla: yes, size/L

#4787 Change the service name in the description to match the example
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, kind/docs, size/XS

#4806 Make sure we spell check all .md files, we have been skipping some.
  out.txt
  scripts/lint_site.sh
Labels: cla: yes, size/S

#4809 Docs/minification
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  scripts/build_site.sh
Labels: cla: yes, size/S

#4803 doc: Fix typo
  content/zh/docs/reference/config/istio.networking.v1alpha3/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#4808 Avoid redundant module downloads when running nodejs stuff.
  .commonfiles.sha
  Makefile
  Makefile.core.mk
  netlify.toml
  out.txt
  scripts/build_site.sh
  scripts/lint_site.sh
  scripts/run_gobindata.sh
Labels: cla: yes, size/M

#4810 Remove obsolete file
  content/en/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
Labels: cla: yes, size/L

#4800 Rename example YAML manifests to match intent
  content/en/docs/tasks/security/mtls-migration/index.md
  content/zh/docs/tasks/security/mtls-migration/index.md
Labels: cla: yes, size/XS

#4814 target page has moved
  content/en/docs/setup/platform-setup/minikube/index.md
Labels: area/environments, area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#4815 Update docs for locality lb changes
  content/en/docs/tasks/traffic-management/locality-load-balancing/index.md
Labels: cla: yes, size/XS

#4816 Fix bug preventing relative links to images in the zh directory.
  layouts/shortcodes/image.html
Labels: cla: yes, size/S

#4724 Update index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
Labels: cla: yes, kind/docs, size/XS

#4819 Moved LLB content from tasks to ops / fixed links
  content/en/about/feature-stages/index.md
  content/en/boilerplates/notes/1.2.md
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/ops/traffic-management/locality-load-balancing/index.md
Labels: cla: yes, kind/docs, size/XS

#4865 Fix path in scripts/tablegen.py to reflect content reorg
  scripts/tablegen.py
Labels: cla: yes, kind/docs, size/XS

#4854 Make sure user understands Outlier Detection is req'd for locality LB
  content/en/docs/ops/traffic-management/locality-load-balancing/index.md
Labels: cla: yes, size/S

#4870 Update common files
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  scripts/build_site.sh
  scripts/check_dockerfiles.sh
  scripts/check_license.sh
  scripts/gen_archive_site.sh
  scripts/gen_site.sh
  scripts/grab_reference_docs.sh
  scripts/lint_site.sh
  scripts/opt_site.sh
  scripts/run_gobindata.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
  scripts/tablegen.py
  scripts/tablegen_diff.py
Labels: cla: yes, size/XXL

#4869 Path updates
  README.md
  content/en/about/contribute/style-guide/index.md
  content/zh/about/contribute/style-guide/index.md
  scripts/gen_archive_site.sh
  scripts/tablegen_diff.py
Labels: cla: yes, size/S

#4874 Update common files and enable more linters.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  scripts/gen_site.sh
  scripts/grab_reference_docs.sh
  scripts/lint_site.sh
  scripts/opt_site.sh
Labels: cla: yes, size/M

#4813 Add Istio Deployment Models concept.
  content/en/blog/2019/announcing-1.1/index.md
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/concepts/deployment-models/cluster-iso.svg
  content/en/docs/concepts/deployment-models/cluster-ns.svg
  content/en/docs/concepts/deployment-models/exp-ns.svg
  content/en/docs/concepts/deployment-models/failover.svg
  content/en/docs/concepts/deployment-models/index.md
  content/en/docs/concepts/deployment-models/iso-ns.svg
  content/en/docs/concepts/deployment-models/multi-cluster.svg
  content/en/docs/concepts/deployment-models/multi-control.svg
  content/en/docs/concepts/deployment-models/multi-mesh.svg
  content/en/docs/concepts/deployment-models/multi-net.svg
  content/en/docs/concepts/deployment-models/multi-trust.svg
  content/en/docs/concepts/deployment-models/shared-control.svg
  content/en/docs/concepts/deployment-models/single-cluster.svg
  content/en/docs/concepts/deployment-models/single-net.svg
  content/en/docs/concepts/deployment-models/single-trust.svg
  content/en/docs/concepts/multicluster-deployments/index.md
  content/en/docs/examples/multicluster/_index.md
  content/en/docs/examples/multicluster/gke/index.md
  content/en/docs/examples/multicluster/icp/index.md
  content/en/docs/reference/glossary/cluster.md
  content/en/docs/reference/glossary/control-plane.md
  content/en/docs/reference/glossary/identity.md
  content/en/docs/reference/glossary/mesh-federation.md
  content/en/docs/reference/glossary/multi-cluster.md
  content/en/docs/reference/glossary/multi-mesh.md
  content/en/docs/reference/glossary/service-endpoint.md
  content/en/docs/reference/glossary/service-mesh.md
  content/en/docs/reference/glossary/trust-domain.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/zh/docs/concepts/multicluster-deployments/multicluster-split-horizon-eds.svg
  content/zh/docs/concepts/multicluster-deployments/multicluster-with-gateways.svg
  content/zh/docs/concepts/multicluster-deployments/multicluster-with-vpn.svg
  content/zh/docs/setup/kubernetes/additional-setup/config-profiles/index.md
  content/zh/docs/setup/kubernetes/install/multicluster/_index.md
  content/zh/docs/tasks/multicluster/gateways/index.md
Labels: cla: yes, kind/docs, size/XL

#4862 Update reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
Labels: cla: yes, kind/docs, size/L
