Repository istio/istio.io, pull requests merged in 2019-03, with the labels that each got.

#3441 rbac: remove destination.name from the documentation.
  content/docs/reference/config/authorization/constraints-and-properties/index.md
Labels: cla: yes

#3442 Clean up keywords.
  content/about/contribute/github/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/blog/2018/istio-authorization/index.md
  content/blog/2019/data-plane-setup/index.md
  content/docs/examples/advanced-gateways/_index.md
  content/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
  content/docs/examples/endpoints/index.md
  content/docs/examples/integrating-vms/index.md
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/docs/setup/kubernetes/additional-setup/requirements/index.md
  content/docs/setup/kubernetes/install/cni/index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/multicluster/gateways/index.md
  content/docs/setup/kubernetes/multicluster/vpn/index.md
  content/docs/tasks/policy-enforcement/denial-and-list/index.md
  content/docs/tasks/security/health-check/index.md
  content/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
  content/docs/tasks/telemetry/distributed-tracing/zipkin/index.md
  content/docs/tasks/traffic-management/egress/index.md
  content/docs/tasks/traffic-management/request-routing/index.md
  content/help/faq/distributed-tracing/minimal-requirements.md
  content/help/ops/security/debugging-authorization/index.md
  content/help/ops/traffic-management/troubleshooting/index.md
  content_zh/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
  content_zh/docs/setup/kubernetes/istio-cni-install/index.md
  content_zh/docs/setup/kubernetes/minimal-install/index.md
  content_zh/docs/tasks/policy-enforcement/denial-and-list/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/zipkin/index.md
Labels: approved, cla: yes

#3404 zh: content_zh/help/ops/traffic-management/troubleshooting
  content_zh/help/ops/traffic-management/troubleshooting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3450 fix link
  content/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
Labels: cla: yes

#3454 Update reference docs.
  content/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
Labels: approved, cla: yes

#3159 should specify the resource type:destinationrule.
  content/docs/tasks/security/mutual-tls/index.md
Labels: approved, cla: yes, lgtm

#3457 Open up Slack to the world.
  content/about/community/join/index.md
  content/about/community/join/slack.svg
  generated/css/all.css
  generated/css/all.css.map
  i18n/en.toml
  layouts/partials/footer.html
  src/sass/misc/_footer.scss
Labels: approved, cla: yes

#3224 Add guide for external cert management at ingress gateway using SDS
  content/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
  content/docs/tasks/traffic-management/secure-ingress/_index.md
  content/docs/tasks/traffic-management/secure-ingress/mount/index.md
  content/docs/tasks/traffic-management/secure-ingress/sds/index.md
Labels: approved, cla: yes, lgtm

#3462 Open up Slack to the world.
  content/about/community/index.md
  i18n/en.toml
  layouts/partials/community/slack.svg
  layouts/partials/footer.html
Labels: approved, cla: yes

#3463 Simplify sidebar logic.
  generated/css/all.css
  generated/css/all.css.map
  generated/img/icons.svg
  generated/js/all.min.js
  generated/js/all.min.js.map
  layouts/partials/primary_bottom.html
  layouts/partials/sidebar_level.html
  layouts/partials/sidebar_multicard.html
  layouts/partials/sidebar_singlecard.html
  src/icons/down-chevron.svg
  src/icons/right-chevron.svg
  src/js/sidebar.js
  src/sass/base/_base.scss
  src/sass/misc/_menu.scss
  src/sass/misc/_sidebar.scss
  src/sass/misc/_toc.scss
  src/sass/themes/_dark-theme.scss
  src/sass/themes/_light-theme.scss
  src/sass/themes/_vars.scss
Labels: approved, cla: yes

#3464 Add a fast language switcher button in preliminary mode.
  generated/css/all.css
  generated/css/all.css.map
  generated/img/icons.svg
  generated/js/all.min.js
  generated/js/all.min.js.map
  i18n/en.toml
  i18n/zh.toml
  layouts/_default/baseof.html
  layouts/partials/header.html
  scripts/build_site.sh
  src/icons/switch-lang.svg
  src/js/lang.js
  src/js/themes.js
  src/js/utils.js
  src/sass/misc/_floaters.scss
Labels: approved, cla: yes

#3465 zh： content/docs/setup/kubernetes/additional-setup/mesh-expansion
  content_zh/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content_zh/help/faq/security/cert-lifetime-config.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#3466 Add the svgo tool to the docker image.
  .circleci/config.yml
  Makefile
  README.md
  scripts/Dockerfile
  scripts/opt_site.sh
Labels: approved, cla: yes

#3467 Fix a bunch of broken aliases.
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/docs/setup/kubernetes/additional-setup/requirements/index.md
  content/docs/setup/kubernetes/download-release/index.md
  content/docs/setup/kubernetes/install/_index.md
  content/docs/setup/kubernetes/install/alicloud/index.md
  content/docs/setup/kubernetes/install/cni/index.md
  content/docs/setup/kubernetes/install/ibm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/install/minimal/index.md
  content/docs/setup/kubernetes/multicluster/_index.md
  content/docs/setup/kubernetes/multicluster/gateways/index.md
  content/docs/setup/kubernetes/platform-setup/alicloud/index.md
  content/docs/setup/kubernetes/platform-setup/aws/index.md
  content/docs/setup/kubernetes/platform-setup/azure/index.md
  content/docs/setup/kubernetes/platform-setup/docker/index.md
  content/docs/setup/kubernetes/platform-setup/gke/index.md
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
  content/docs/setup/kubernetes/platform-setup/minikube/index.md
  content/docs/setup/kubernetes/platform-setup/oci/index.md
  content/docs/setup/kubernetes/platform-setup/openshift/index.md
  content/docs/setup/kubernetes/upgrade/index.md
Labels: approved, cla: yes

#3473 A few formatting fixes.
  generated/css/all.css
  generated/css/all.css.map
  layouts/partials/sidebar_level.html
  src/sass/misc/_floaters.scss
  src/sass/misc/_header.scss
  src/sass/misc/_sidebar.scss
Labels: approved, cla: yes

#3481 Layout improvements for mobile.
  generated/css/all.css
  generated/css/all.css.map
  src/sass/misc/_floaters.scss
  src/sass/misc/_footer.scss
  src/sass/misc/_header.scss
Labels: approved, cla: yes

#3482 Fix problem with disappearing hamburger menu on Android.
  generated/css/all.css
  generated/css/all.css.map
  generated/js/all.min.js
  generated/js/all.min.js.map
  src/js/header.js
  src/sass/base/_constants.scss
  src/sass/misc/_header.scss
Labels: approved, cla: yes

#3472 zh： content/help/faq/security/k8s-health-checks
  content_zh/help/faq/security/k8s-health-checks.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3474 zh： content/docs/tasks/security/rbacg-roups
  content_zh/docs/tasks/security/rbac-groups/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3476 zh： content/docs/setup/kubernetes/install/cni
  content_zh/docs/setup/kubernetes/install/cni/index.md
  content_zh/help/faq/security/does-istio-support-authorization.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3426 zh: content_zh/docs/setup/kubernetes/platform-setup/ibm
  content_zh/docs/setup/kubernetes/platform-setup/ibm/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3483 A reference to the istio.io repository was missing
  content/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes

#3471 zh： content/docs/setup/kubernetes/docs/tasks/traffic-management/traff…
  content_zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3470 zh： content/docs/setup/kubernetes/docs/tasks/security/https-overlay
  content_zh/docs/tasks/security/https-overlay/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3469 zh： content/docs/setup/kubernetes/docs/tasks/traffic-management/mirro…
  content_zh/docs/tasks/traffic-management/mirroring/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3488 Bunch of structural improvements.
  content/_index.md
  generated/css/all.css
  generated/css/all.css.map
  generated/js/all.min.js
  generated/js/all.min.js.map
  layouts/_default/baseof.html
  layouts/partials/breadcrumbs.html
  layouts/partials/primary_bottom.html
  layouts/partials/primary_top.html
  layouts/partials/sidebar_level.html
  layouts/partials/sidebar_multicard.html
  layouts/partials/sidebar_singlecard.html
  layouts/partials/toc.html
  layouts/shortcodes/idea.html
  layouts/shortcodes/quote.html
  layouts/shortcodes/tabset.html
  layouts/shortcodes/tip.html
  layouts/shortcodes/warning.html
  src/js/links.js
  src/js/sidebar.js
  src/js/tabs.js
  src/sass/_all.scss
  src/sass/base/_base.scss
  src/sass/misc/_breadcrumbs.scss
  src/sass/misc/_floaters.scss
  src/sass/misc/_header.scss
  src/sass/misc/_primary.scss
  src/sass/misc/_sidebar.scss
  src/sass/misc/_tabset.scss
Labels: approved, cla: yes

#3486 Update content/help/faq/distributed-tracing/disabling-tracing.md
  content/help/faq/distributed-tracing/disabling-tracing.md
Labels: cla: yes

#3489 Stop checking in generated files.
  .circleci/config.yml
  .spelling
  Makefile
  README.md
  content/about/contribute/creating-and-editing-pages/index.md
Labels: approved, cla: yes

#3163 Update monitoring and access control for egress traffic blog post
  .spelling
  content/blog/2018/egress-monitoring-access-control/dashboard-egress-gateway.png
  content/blog/2018/egress-monitoring-access-control/egress-adapters-monitoring-policy.svg
  content/blog/2018/egress-monitoring-access-control/egress-adapters-monitoring.svg
  content/blog/2018/egress-monitoring-access-control/http-to-gateway.svg
  content/blog/2018/egress-monitoring-access-control/https-to-gateway.svg
  content/blog/2018/egress-monitoring-access-control/index.md
Labels: approved, cla: yes, lgtm

#3490 Update a few FAQ entries.
  content/help/faq/general/how-do-i-contribute.md
  content/help/faq/general/how-do-i-get-started.md
  content/help/faq/general/how-to-join-slack.md
Labels: approved, cla: yes

#3497 Update reference docs.
  content/blog/2018/egress-monitoring-access-control/index.md
  content/docs/reference/commands/istioctl/index.html
  content/help/faq/general/how-to-join-slack.md
  content/help/faq/general/istio-partners-and-vendors.md
  generated/css/all.css
  generated/css/all.css.map
  src/sass/_all.scss
  src/sass/base/_base.scss
  src/sass/misc/_code-blocks.scss
Labels: approved, cla: yes

#3455 kubectl logs -l only returns 10 lines
  content/help/ops/traffic-management/deploy-guidelines/index.md
Labels: approved, cla: yes

#3499 Remove old comment.
  content/docs/tasks/security/authz-http/index.md
Labels: approved, cla: yes, lgtm

#3500 Update Galley description for 1.1
  content/docs/concepts/what-is-istio/index.md
Labels: approved, cla: yes, lgtm

#3492 zh： /docs/examples/bookinfo
  content_zh/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3485 zh: add content_zh/help/faq/distributed-tracing/disabling-tracing.md
  content_zh/help/faq/distributed-tracing/disabling-tracing.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3440 Update the number of CRDs to expect during installation
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/ibm/index.md
  content/docs/setup/kubernetes/install/minimal/index.md
  content_zh/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes, lgtm

#3477 zh： content/help/faq/security/does-istio-support-authorization
  content_zh/help/faq/security/does-istio-support-authorization.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3506 moved older notes
  content_zh/about/notes/_index.md
  content_zh/about/notes/older/0.1/index.md
  content_zh/about/notes/older/0.2/index.md
  content_zh/about/notes/older/0.3/index.md
  content_zh/about/notes/older/0.4/index.md
  content_zh/about/notes/older/0.5/index.md
  content_zh/about/notes/older/0.6/index.md
  content_zh/about/notes/older/0.7/index.md
  content_zh/about/notes/older/0.8/index.md
  content_zh/about/notes/older/_index.md
  content_zh/blog/2018/traffic-mirroring/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3503 Restore ingress doc order
  content/docs/tasks/traffic-management/secure-ingress/_index.md
Labels: approved, cla: yes, lgtm

#3505 Some strings to translate
  i18n/zh.toml
Labels: cla: yes, lgtm, translation/chinese

#3507 zh: sync /docs/tasks/telemetry/using-istio-dashboard/index.md
  content_zh/docs/tasks/telemetry/using-istio-dashboard/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3428 Use the 443 port for cluster aware gateway, handle NodePort connectivity to the remote cluster
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes, lgtm

#3508 zh: sync /help/ops/traffic-management/deploy-guidelines/index.md
  content_zh/help/ops/traffic-management/deploy-guidelines/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3509 use a boilerplate for setting environment variables for kubectl contexts
  content/boilerplates/kubectl-multicluster-contexts.md
  content/docs/examples/multicluster/gateways/index.md
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: cla: yes

#3487 Spelling
  content_zh/docs/reference/commands/galley/index.md
  scripts/lint_site.sh
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3514 add start-httpbin-service boilerplate
  content/boilerplates/start-httpbin-service.md
  content/docs/tasks/traffic-management/circuit-breaking/index.md
  content/docs/tasks/traffic-management/ingress/index.md
Labels: approved, cla: yes, lgtm

#3412 Update references to value files
  content/docs/setup/kubernetes/multicluster/gateways/index.md
  content/docs/tasks/security/vault-ca/index.md
  content_zh/docs/setup/kubernetes/multicluster/gateways/index.md
Labels: cla: yes

#3435 Update health check task.
  content/docs/tasks/security/health-check/index.md
Labels: approved, cla: yes, lgtm

#3516 Fix typo in MTLS migration
  content/docs/tasks/security/mtls-migration/index.md
Labels: cla: yes

#3520 Update istio-demo install instructions
  .spelling
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/tasks/security/authn-policy/index.md
  content/docs/tasks/security/plugin-ca-cert/index.md
  content/help/faq/security/accessing-non-istio-services.md
  content_zh/help/faq/security/accessing-non-istio-services.md
Labels: cla: yes, lgtm

#3513 delete the CRD clean up section
  content/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes

#3518 Add support for an advisory string.
  i18n/en.toml
  i18n/zh.toml
  layouts/partials/footer.html
Labels: approved, cla: yes

#3522 zh: update /docs/tasks/telemetry/fluentd/index.md
  content_zh/docs/setup/kubernetes/install/_index.md
  content_zh/docs/tasks/telemetry/fluentd/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3523 zh: update /help/faq/general/how-do-i-contribute.md
  content_zh/help/faq/general/how-do-i-contribute.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3524 zh: update /docs/setup/_index.md
  content_zh/docs/setup/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3511 zh: update /help/ops/controlz/index.md
  content_zh/help/ops/controlz/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3525 zh: update /help/ops/security/debugging-authorization/index.md
  content_zh/help/ops/security/debugging-authorization/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3526 zh: sync with upstream
  content_zh/docs/setup/kubernetes/install/minimal/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#3444 update egress gateway instruction
  content/docs/examples/advanced-gateways/egress-gateway/index.md
Labels: approved, cla: yes, lgtm

#3396 Fix helm values for demo and uninstall steps
  content/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes, lgtm

#3423 Fix the failure to create the control plane for master cluster
  content/docs/examples/multicluster/gke/index.md
Labels: cla: yes, lgtm

#3384 [#12017] Update doc for unsupported hostnames in Cluster-Aware Service Routing…
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: no, ok-to-test

#3495 Remove .b from cert path httpbin.new.example.com curl
  content/docs/tasks/traffic-management/secure-ingress/sds/index.md
Labels: approved, cla: yes, lgtm

#3397 Add sampling info to Tracing tasks
  .spelling
  content/boilerplates/trace-generation.md
  content/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
  content/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content/docs/tasks/telemetry/distributed-tracing/zipkin/index.md
Labels: cla: yes

#3157 fail with 503 instead of 000 for injected-app
  content/docs/tasks/security/mutual-tls/index.md
Labels: cla: yes

#3410 add ingress troubleshooting section
  content/docs/tasks/traffic-management/ingress/index.md
Labels: cla: yes

#3529 Use two separate ingress gateways for two hosts
  content/docs/tasks/traffic-management/secure-ingress/mount/index.md
Labels: cla: yes

#3530 Add Pod to Service association requirement
  content/docs/setup/kubernetes/additional-setup/requirements/index.md
Labels: approved, cla: no, lgtm, ok-to-test

#3531 add access log task
  content/docs/tasks/telemetry/access-log/index.md
Labels: cla: yes

#3534 move deployment of Istio egress gateway into a separate section
  content/docs/examples/advanced-gateways/egress-gateway/index.md
Labels: cla: yes

#3535 add references to the "Deploy Istio egress gateway"
  content/blog/2018/egress-mongo/index.md
  content/docs/examples/advanced-gateways/egress-gateway-tls-origination/index.md
  content/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
Labels: approved, cla: yes, lgtm

#3542 zh: update content_zh/docs/tasks/traffic-management/fault-injection/index.md
  content_zh/docs/tasks/traffic-management/fault-injection/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3544 zh: update content_zh/help/ops/security/debugging-authorization/index.md
  content_zh/help/ops/security/debugging-authorization/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3545 zh: update content_zh/help/faq/security/check-policy.md
  content_zh/help/faq/security/check-policy.md
Labels: approved, cla: yes, lgtm

#3510 zh: update docs/setup/kubernetes/multicluster/gateways/index.md
  content_zh/docs/setup/kubernetes/multicluster/gateways/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3547 zh: update blog/_index.md, docs/setup/consul/quick-start/index.md
  content_zh/blog/_index.md
  content_zh/docs/setup/consul/quick-start/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3546 zh: update content_zh/docs/concepts/performance-and-scalability/index.md
  content_zh/docs/concepts/performance-and-scalability/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3552 zh: sync /docs/reference/config/policy-and-telemetry/metrics/index.md
  content_zh/blog/2018/istio-authorization/index.md
  content_zh/docs/reference/config/policy-and-telemetry/metrics/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3548 zh: update content_zh/about/community/join/index.md
  content_zh/about/community/join/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3549 zh: update content_zh/docs/examples/advanced-gateways/_index.md
  content_zh/docs/examples/advanced-gateways/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3550 zh: sync /docs/tasks/security/authz-http/index.md
  content_zh/docs/tasks/security/authz-http/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3541 zh: Add Chinese content advisory
  i18n/zh.toml
Labels: cla: yes, lgtm, translation/chinese

#3399 Clarify that egress gateway is disabled by default if Helm was used to install
  content/docs/reference/config/installation-options/index.md
Labels: approved, cla: yes, lgtm

#3553 make "Disable Envoy's access logging a separate section"
  content/docs/tasks/telemetry/access-log/index.md
Labels: cla: yes

#3539 Add warning stating that this doesn't work in Minikube
  content/docs/examples/advanced-gateways/egress-gateway/index.md
Labels: approved, cla: yes, lgtm

#3538 Merge minimal with helm install and simpify install paths
  content/about/feature-stages/index.md
  content/about/notes/1.0/index.md
  content/blog/2018/announcing-1.0/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/blog/2019/multicluster-version-routing/index.md
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/concepts/policies-and-telemetry/index.md
  content/docs/examples/multicluster/gateways/index.md
  content/docs/examples/multicluster/gke/index.md
  content/docs/examples/multicluster/icp/index.md
  content/docs/examples/multicluster/iks-icp/index.md
  content/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/additional-setup/requirements/index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/install/minimal/index.md
  content/docs/setup/kubernetes/install/multicluster/_index.md
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
  content/docs/setup/kubernetes/install/multicluster/gateways/multicluster-with-gateways.svg
  content/docs/setup/kubernetes/install/multicluster/vpn/index.md
  content/docs/setup/kubernetes/install/multicluster/vpn/multicluster-with-vpn.svg
  content/docs/setup/kubernetes/install/platform/_index.md
  content/docs/setup/kubernetes/install/platform/alicloud/app-catalog-istio-1.0.0.png
  content/docs/setup/kubernetes/install/platform/alicloud/index.md
  content/docs/setup/kubernetes/install/platform/gke/dm-tracing.png
  content/docs/setup/kubernetes/install/platform/gke/dm_bookinfo.png
  content/docs/setup/kubernetes/install/platform/gke/dm_gcp_iam.png
  content/docs/setup/kubernetes/install/platform/gke/dm_gcp_iam_role.png
  content/docs/setup/kubernetes/install/platform/gke/dm_grafana.png
  content/docs/setup/kubernetes/install/platform/gke/dm_kiali.png
  content/docs/setup/kubernetes/install/platform/gke/dm_kubernetes_workloads.png
  content/docs/setup/kubernetes/install/platform/gke/dm_launcher.png
  content/docs/setup/kubernetes/install/platform/gke/dm_prometheus.png
  content/docs/setup/kubernetes/install/platform/gke/index.md
  content/docs/setup/kubernetes/install/platform/ibm/index.md
  content/docs/setup/kubernetes/install/platform/ibm/istio-catalog-1.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-catalog-2.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-deletion.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-installation-1.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-installation-2.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-release.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-upgrade-1.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-upgrade-2.png
  content/help/faq/distributed-tracing/minimal-requirements.md
  content_zh/docs/setup/kubernetes/additional-setup/requirements/index.md
  content_zh/docs/setup/kubernetes/install/alicloud/index.md
  content_zh/docs/setup/kubernetes/install/gke/index.md
  content_zh/docs/setup/kubernetes/install/ibm/index.md
  content_zh/docs/setup/kubernetes/multicluster/gateways/index.md
  content_zh/docs/setup/kubernetes/multicluster/vpn/index.md
Labels: approved, cla: yes, lgtm

#3557 Clarify the definition of a handler.
  content/docs/concepts/policies-and-telemetry/index.md
Labels: approved, cla: yes, lgtm

#3559 Clarify upgrade options
  content/docs/setup/kubernetes/upgrade/index.md
Labels: approved, cla: yes, lgtm

#3540 Add note to explain authentication mesh policy CRD kind.
  content/docs/tasks/security/authn-policy/index.md
Labels: approved, cla: yes, lgtm

#3563 Fortio binary moved; breaks examples
  content/docs/tasks/traffic-management/circuit-breaking/index.md
  content_zh/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: approved, cla: yes, lgtm

#3560 Reorganized Community page, added calendar, clarified Slack
  content/about/community/join/gcal.svg
  content/about/community/join/index.md
  layouts/partials/footer.html
Labels: approved, cla: yes, lgtm

#3554 zh: sync /docs/setup/kubernetes/platform-setup/gke/index.md
  content_zh/docs/setup/kubernetes/install/_index.md
  content_zh/docs/setup/kubernetes/install/kubernetes/index.md
  content_zh/docs/setup/kubernetes/platform-setup/docker/index.md
  content_zh/docs/setup/kubernetes/platform-setup/gke/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3564 zh: sync /about/contribute/style-guide/index.md
  content_zh/about/contribute/style-guide/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3565 zh: sync /docs/setup/kubernetes/additional-setup/requirements/index.md
  content_zh/docs/setup/kubernetes/additional-setup/requirements/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3556 zh: docs/concepts/security/index.md
  content_zh/about/feature-stages/index.md
  content_zh/about/notes/1.0/index.md
  content_zh/about/notes/older/0.5/index.md
  content_zh/blog/2018/istio-authorization/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/tasks/security/authz-http/index.md
  content_zh/docs/tasks/security/authz-tcp/index.md
  content_zh/docs/tasks/security/rbac-groups/index.md
  content_zh/docs/tasks/security/role-based-access-control/index.md
  content_zh/help/faq/security/does-istio-support-authorization.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3493 zh： /docs/tasks/traffic-management/request-timeouts
  content_zh/docs/tasks/traffic-management/request-timeouts/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3491 zh： /about/security-vulnerabilities
  content_zh/about/security-vulnerabilities/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3475 zh： rename dir
  content_zh/about/feature-stages/index.md
  content_zh/about/notes/1.0/index.md
  content_zh/blog/2018/announcing-1.0/index.md
  content_zh/blog/2018/incremental-traffic-management/index.md
  content_zh/docs/concepts/multicluster-deployments/index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/examples/multicluster/gateways/index.md
  content_zh/docs/examples/multicluster/gke/index.md
  content_zh/docs/examples/multicluster/icp/index.md
  content_zh/docs/examples/multicluster/iks-icp/index.md
  content_zh/docs/setup/kubernetes/_index.md
  content_zh/docs/setup/kubernetes/additional-setup/cni/index.md
  content_zh/docs/setup/kubernetes/install/minimal/index.md
  content_zh/docs/setup/kubernetes/install/multicluster/_index.md
  content_zh/docs/setup/kubernetes/install/multicluster/gateways/index.md
  content_zh/docs/setup/kubernetes/install/multicluster/vpn/index.md
  content_zh/docs/setup/kubernetes/install/platform/alicloud/index.md
  content_zh/docs/setup/kubernetes/install/platform/gke/index.md
  content_zh/docs/setup/kubernetes/install/platform/ibm/index.md
  content_zh/help/faq/distributed-tracing/minimal-requirements.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3569 zh: update content_zh/docs/tasks/telemetry/_index.md
  content_zh/docs/tasks/telemetry/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3570 zh: update content_zh/help/faq/general/how-do-i-get-started.md
  content_zh/help/faq/general/how-do-i-get-started.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3571 zh: update content_zh/docs/reference/config/authorization/constraints-and-properties/index.md
  content_zh/docs/reference/config/authorization/constraints-and-properties/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3572 zh: update content_zh/docs/examples/intelligent-routing/index.md
  content_zh/docs/examples/intelligent-routing/index.md
Labels: approved, cla: yes, lgtm

#3568 zh: sync content_zh/help/ops/security/authorization-restrictive/index.md
  content_zh/help/ops/security/authorization-restrictive/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3567 #3566 : Fixing typo
  content/docs/concepts/performance-and-scalability/index.md
Labels: cla: yes, needs-ok-to-test

#3537 Fix the Istio CNI doc per the rel-1.1 helm chart decoupling changes
  content/docs/setup/kubernetes/additional-setup/cni/index.md
Labels: approved, cla: yes

#3498 Add 'Securing Kubernetes Ingress with Cert-Manager' example
  content/docs/examples/advanced-gateways/ingress-certmgr/index.md
Labels: approved, area/networking, cla: yes, lgtm

#3577 Implement consistent term for installation related flows
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/additional-setup/customize/index.md
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/docs/setup/kubernetes/additional-setup/sidecar-injection/index.md
  content/docs/setup/kubernetes/download-release/index.md
  content/docs/setup/kubernetes/install/_index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
  content/docs/setup/kubernetes/install/multicluster/vpn/index.md
  content/docs/setup/kubernetes/install/platform/_index.md
  content/docs/setup/kubernetes/install/platform/alicloud/index.md
  content/docs/setup/kubernetes/install/platform/gke/index.md
  content/docs/setup/kubernetes/install/platform/ibm/index.md
  content/docs/setup/kubernetes/upgrade/index.md
Labels: approved, cla: yes, lgtm

#3582 update value files dir to use istio-fetch
  content/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes, lgtm

#3578 Update dead link
  content/docs/concepts/performance-and-scalability/index.md
Labels: cla: yes, lgtm

#3584 forgot the other helm path
  content/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes, lgtm

#3393 Simplify the bookinfo instructions for auto injection
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes

#3588 Reflect removal of legacy ingress component in 1.1
  content/docs/reference/config/installation-options/index.md
Labels: approved, cla: yes, lgtm

#3585 Update kubectl get pods, svc output
  content/docs/setup/kubernetes/install/kubernetes/index.md
Labels: approved, cla: yes, lgtm, ok-to-test

#3592 Regenerate install options page for release-1.1
  content/docs/reference/config/installation-options/index.md
  scripts/tablegen.py
Labels: cla: yes

#3594 update enable cni install instruction
  content/docs/setup/kubernetes/additional-setup/cni/index.md
Labels: approved, cla: yes, lgtm

#3274 Update mesh expansion doc with birectional example.
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/help/faq/security/cert-lifetime-config.md
Labels: approved, cla: yes, lgtm

#3586 add FAQ on header casing
  content/help/faq/mixer/header-rules.md
Labels: approved, cla: yes, lgtm

#3595 Update egress task
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes

#3598 Using the term canary rollouts consistency
  content/docs/concepts/what-is-istio/index.md
Labels: cla: yes

#3583 Add a warning about using sudo for a TCP sample
  content/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: cla: yes

#3601 Bunch of site improvements.
  generated/css/all.css
  generated/css/all.css.map
  generated/js/all.min.js
  generated/js/all.min.js.map
  layouts/_default/baseof.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/partials/primary_bottom.html
  layouts/partials/primary_top.html
  layouts/partials/sidebar_multicard.html
  layouts/shortcodes/image.html
  layouts/shortcodes/text.html
  src/js/codeBlocks.js
  src/js/constants.js
  src/js/links.js
  src/js/sidebar.js
  src/js/tabs.js
  src/sass/base/_base.scss
  src/sass/misc/_breadcrumbs.scss
  src/sass/misc/_code-blocks.scss
  src/sass/misc/_footer.scss
  src/sass/misc/_header.scss
  src/sass/misc/_pagenav.scss
  src/sass/misc/_sidebar.scss
  src/sass/misc/_tabset.scss
Labels: approved, cla: yes

#3602 typo in what-is-istio page
  content/docs/concepts/what-is-istio/index.md
Labels: cla: yes, needs-ok-to-test

#3605 Link to Destination Rules concept from BookInfo
  content/docs/examples/bookinfo/index.md
Labels: cla: yes, needs-ok-to-test

#3607 Finish keyboard navigation for the header & menu.
  generated/css/all.css
  generated/css/all.css.map
  generated/js/all.min.js
  generated/js/all.min.js.map
  layouts/404.html
  layouts/_default/baseof.html
  layouts/_default/faq-landing.html
  layouts/partials/header.html
  layouts/partials/primary_bottom.html
  layouts/partials/primary_top.html
  layouts/partials/toc.html
  src/js/constants.js
  src/js/menu.js
  src/js/overlays.js
  src/js/sidebar.js
  src/js/utils.js
  src/sass/misc/_faq-landing.scss
  src/sass/misc/_header.scss
  src/sass/misc/_menu.scss
  src/sass/misc/_toc.scss
Labels: approved, cla: yes

#3608 update values references
  content/docs/examples/multicluster/gateways/index.md
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
Labels: approved, cla: yes

#3609 Typos
  content/docs/examples/multicluster/gateways/index.md
Labels: approved, cla: yes

#3614 Fix tab problem.
  content/docs/setup/kubernetes/install/multicluster/vpn/index.md
  generated/css/all.css
  generated/css/all.css.map
  generated/js/all.min.js
  generated/js/all.min.js.map
  layouts/shortcodes/tabset.html
  src/js/tabs.js
  src/sass/misc/_header.scss
  src/sass/misc/_tabset.scss
Labels: approved, cla: yes

#3612 Fix incorrect rendering of many callouts.
  content/docs/tasks/traffic-management/egress/index.md
  layouts/shortcodes/idea.html
  layouts/shortcodes/quote.html
  layouts/shortcodes/tip.html
  layouts/shortcodes/warning.html
Labels: approved, cla: yes

#3611 Update uninstall step for helm.
  content/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes

#3581 Document the sidecar.istio.io/statsInclusionPrefixes annotation
  content/help/ops/telemetry/envoy-stats/index.md
  content/help/ops/telemetry/missing-metrics/index.md
Labels: approved, cla: yes, lgtm

#3610 Tweak the installation pages.
  content/about/contribute/creating-and-editing-pages/index.md
  content/docs/examples/endpoints/index.md
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/download-release/index.md
  content/docs/setup/kubernetes/install/_index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/install/platform/alicloud/index.md
  content/docs/setup/kubernetes/install/platform/gke/index.md
  content/docs/setup/kubernetes/install/platform/ibm/index.md
  content/docs/setup/kubernetes/platform-setup/_index.md
  content/docs/setup/kubernetes/requirements/index.md
  content/docs/setup/kubernetes/upgrade/index.md
  content/docs/tasks/traffic-management/request-routing/index.md
  content/help/ops/traffic-management/troubleshooting/index.md
Labels: approved, cla: yes, lgtm

#3162 fail with 503 instead of 000 for injected-app
  content/docs/tasks/security/mutual-tls/index.md
Labels: cla: yes, lgtm

#3408 [Cluster-Aware] Enable the access log on primary cluster
  content/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes, lgtm

#3622 Prune a few things that shouldn't have been in the dictionary.
  .spelling
  content/docs/concepts/security/index.md
  content/docs/examples/multicluster/gateways/index.md
  content/docs/setup/kubernetes/additional-setup/sidecar-injection/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
  content/docs/tasks/security/plugin-ca-cert/index.md
  content/help/ops/setup/injection/index.md
  content_zh/docs/reference/commands/sidecar-injector/index.md
  content_zh/docs/setup/kubernetes/additional-setup/sidecar-injection/index.md
  content_zh/docs/setup/kubernetes/install/kubernetes/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: approved, cla: yes

#3624 Update reference docs.
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/docs/reference/config/networking/v1alpha3/service-entry/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
Labels: approved, cla: yes

#3627 Escape pipe symbol if it appears in the configuration options
  content/docs/reference/config/installation-options/index.md
  scripts/tablegen.py
Labels: cla: yes

#3626 Shuffle the setup directory a bit.
  content/blog/2018/export-logs-through-stackdriver/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/docs/examples/endpoints/index.md
  content/docs/reference/config/networking/_index.md
  content/docs/setup/_index.md
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/additional-setup/_index.md
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/download/index.md
  content/docs/setup/kubernetes/install/_index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/install/multicluster/_index.md
  content/docs/setup/kubernetes/install/platform/_index.md
  content/docs/setup/kubernetes/prepare/_index.md
  content/docs/setup/kubernetes/prepare/platform-setup/_index.md
  content/docs/setup/kubernetes/prepare/platform-setup/alicloud/csconsole.png
  content/docs/setup/kubernetes/prepare/platform-setup/alicloud/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/aws/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/azure/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/docker/dockerprefs.png
  content/docs/setup/kubernetes/prepare/platform-setup/docker/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/gke/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/ibm/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/minikube/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/oci/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/openshift/index.md
  content/docs/setup/kubernetes/prepare/requirements/index.md
  content/docs/setup/kubernetes/upgrade/index.md
  content/docs/tasks/traffic-management/request-routing/index.md
  content/help/ops/traffic-management/troubleshooting/index.md
  content_zh/docs/setup/_index.md
  content_zh/docs/setup/kubernetes/install/multicluster/_index.md
  content_zh/docs/setup/kubernetes/platform-setup/alicloud/index.md
  content_zh/docs/setup/kubernetes/platform-setup/docker/index.md
Labels: approved, cla: yes, lgtm

#3631 Update rate limit to use session cookie
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
  content_zh/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: approved, cla: yes, lgtm

#3630 Amend the style guide to match what we actually use.
  content/about/contribute/style-guide/index.md
Labels: approved, cla: yes

#3633 Improve the readability of the pod requirements.
  content/docs/setup/kubernetes/prepare/requirements/index.md
Labels: approved, cla: yes, lgtm

#3620 Provide documentation on configuration profiles/components/add ons.
  .spelling
  content/docs/setup/kubernetes/additional-setup/config-profiles/index.md
  content/docs/setup/kubernetes/install/helm/index.md
Labels: approved, cla: yes, lgtm

#3634 A few install doc tweeks
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/_index.md
  content/docs/setup/kubernetes/prepare/requirements/index.md
Labels: approved, cla: yes, lgtm

#3628 Fix bugs in multicluster gateway Istio installation
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
Labels: approved, cla: yes, lgtm

#3616 Update docs regarding when to use flexible mTLS
  content/docs/setup/kubernetes/install/kubernetes/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3619 Update doc of multi-cluster setup for ICP
  content/docs/examples/multicluster/icp/index.md
Labels: approved, cla: yes, lgtm

#3637 zh:/help/ops/setup/required-pod-capabilities/index.md
  content_zh/help/ops/setup/required-pod-capabilities/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3640 Sync rename dir.
  content_zh/blog/2018/export-logs-through-stackdriver/index.md
  content_zh/blog/2018/incremental-traffic-management/index.md
  content_zh/docs/examples/endpoints/index.md
  content_zh/docs/setup/kubernetes/_index.md
  content_zh/docs/setup/kubernetes/additional-setup/cni/index.md
  content_zh/docs/setup/kubernetes/download/index.md
  content_zh/docs/setup/kubernetes/install/helm/index.md
  content_zh/docs/setup/kubernetes/install/kubernetes/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/_index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/alicloud/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/aws/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/azure/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/docker/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/gke/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/ibm/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/minikube/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/oci/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/openshift/index.md
  content_zh/docs/setup/kubernetes/upgrade/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3645 zh: add content_zh/boilerplates/start-httpbin-service.md
  content_zh/boilerplates/start-httpbin-service.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3648 zh: add docs/setup/kubernetes/install/platform/_index.md, docs/setup/kubernetes/prepare
  content_zh/docs/setup/kubernetes/install/platform/_index.md
  content_zh/docs/setup/kubernetes/prepare/_index.md
Labels: approved, cla: yes, lgtm, translation/chinese
