Repository istio/istio.io, pull requests merged in 2019-06, with the labels that each got.

#4183 zh：egress_sni_monitoring_and_policies
  content_zh/blog/2019/appswitch/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies/index.md
  content_zh/docs/examples/advanced-gateways/ingress-sni-passthrough/index.md
  content_zh/docs/examples/multicluster/iks-icp/index.md
  content_zh/docs/reference/commands/mixs/index.md
  content_zh/docs/setup/kubernetes/additional-setup/requirements/index.md
  content_zh/docs/setup/kubernetes/install/multicluster/vpn/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/ibm/index.md
  content_zh/docs/tasks/telemetry/metrics/using-istio-dashboard/index.md
  content_zh/help/faq/security/accessing-non-istio-services.md
  content_zh/help/ops/setup/validation/index.md
  content_zh/help/ops/setup/webhook/index.md
Labels: cla: yes, translation/chinese

#4178 zh: added 1.1.7
  content_zh/about/notes/1.1.7/index.md
  content_zh/blog/2019/announcing-1.1.7/index.md
  content_zh/boilerplates/notes/1.1.7.md
Labels: cla: yes, translation/chinese

#4238 Update secure naming in security concept page
  content/docs/concepts/security/index.md
Labels: cla: yes

#4247 Clarify and improve setup instructions
  .spelling
  content/blog/2018/export-logs-through-stackdriver/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/docs/examples/endpoints/index.md
  content/docs/ops/traffic-management/troubleshooting/index.md
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/docs/setup/kubernetes/additional-setup/requirements/index.md
  content/docs/setup/kubernetes/getting-started/index.md
  content/docs/setup/kubernetes/install/_index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/platform-setup/_index.md
  content/docs/setup/kubernetes/platform-setup/alicloud/csconsole.png
  content/docs/setup/kubernetes/platform-setup/alicloud/index.md
  content/docs/setup/kubernetes/platform-setup/azure/index.md
  content/docs/setup/kubernetes/platform-setup/docker/dockerprefs.png
  content/docs/setup/kubernetes/platform-setup/docker/index.md
  content/docs/setup/kubernetes/platform-setup/gke/index.md
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
  content/docs/setup/kubernetes/platform-setup/minikube/index.md
  content/docs/setup/kubernetes/platform-setup/oci/index.md
  content/docs/setup/kubernetes/platform-setup/openshift/index.md
  content/docs/setup/kubernetes/prepare/_index.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content/docs/tasks/traffic-management/request-routing/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/alicloud/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/docker/index.md
Labels: cla: yes

#4252 Patch #4238 to release-1.1
  content/docs/concepts/security/index.md
Labels: cla: yes

#4230 Add information about configuring Istio to use an external Zipkin (pr…
  content/docs/tasks/telemetry/distributed-tracing/zipkin/index.md
Labels: cla: yes

#4249 fix(ops): change the yaml used in "Probes Rewriting"
  content/docs/ops/setup/app-health-check/index.md
Labels: cla: yes

#4240 Add a link to a guide for configuring k8s auth method on Vault [release 1.1 branch]
  content/docs/tasks/security/vault-ca/index.md
Labels: cla: yes

#4241 Add a link to a guide for configuring k8s auth method on Vault [master branch]
  content/docs/tasks/security/vault-ca/index.md
Labels: cla: yes

#4266 update cmd
  content/docs/tasks/security/auth-sds/index.md
Labels: cla: yes

#4276 1.1.8 release notes
  content/about/notes/1.1.8/index.md
  content/blog/2019/announcing-1.1.8/index.md
  content/boilerplates/notes/1.1.8.md
Labels: action/merge-to-release-branch

#4270 Refine mc
  content/docs/concepts/multicluster-deployments/index.md
Labels: area/environments

#4274 Adds a separate docs page for istioctl.
  content/docs/ops/setup/istioctl/index.md
  content/docs/setup/kubernetes/getting-started/index.md
Labels: area/user experience, kind/docs

#4292 zh: sync /docs/tasks/security/vault-ca/index.md
  content_zh/docs/tasks/security/vault-ca/index.md
Labels: cla: yes, translation/chinese

#4294 zh: added: 1.1.8
  content_zh/about/notes/1.1.8/index.md
  content_zh/blog/2019/announcing-1.1.8/index.md
  content_zh/boilerplates/notes/1.1.8.md
Labels: cla: yes, translation/chinese

#4296 zh: /blog/2019/announcing-1.0-eol/index.md
  content_zh/blog/2019/announcing-1.0-eol/index.md
Labels: cla: yes, translation/chinese

#4297 update kc link for ICP.
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
Labels: cla: yes

#4304 Fix Configure clients to send mutual TLS traffic
  content_zh/docs/tasks/security/mtls-migration/index.md
Labels: cla: yes, translation/chinese

#4298 zh: added: 1.0.8
  content_zh/about/notes/1.0.8/index.md
  content_zh/blog/2019/announcing-1.0.8/index.md
  content_zh/boilerplates/notes/1.0.8.md
Labels: cla: yes, translation/chinese

#4295 update setup steps for ICP.
  content/docs/setup/kubernetes/install/platform/ibm/index.md
  content/docs/setup/kubernetes/install/platform/ibm/istio-catalog-1.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-catalog-2.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-deletion.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-installation-1.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-installation-2.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-release.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-upgrade-1.png
  content/docs/setup/kubernetes/install/platform/ibm/istio-upgrade-2.png
Labels: cla: yes

#4290 Fix xargs usage of `-I`
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes

#4303 Adding loverto to OWNERS for Chinese.
  CODEOWNERS
Labels: cla: yes

#4313 Update root rotation blog
  content/blog/2019/root-transition/index.md
Labels: cla: yes

#4312 zsh completion updates
  content/docs/ops/setup/istioctl/index.md
Labels: cla: yes

#4314 update endpoints instructions
  content/docs/examples/endpoints/index.md
Labels: cla: yes

#4291 Document the Helm whitespace problem
  content/docs/setup/kubernetes/install/helm/index.md
Labels: cla: yes

#4311 update expected CRDs number.
  content/boilerplates/verify-crds.md
Labels: cla: yes

#4288 zh: /docs/examples/multicluster/gateways/index.md
  content_zh/docs/examples/multicluster/gateways/index.md
Labels: cla: yes, translation/chinese

#4324 zh: fix typo
  content_zh/docs/reference/glossary/mixer.md
Labels: cla: yes

#4323 fix istio-init chart upgrade issue.
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes

#4322 fix typo for glossary page
  content/docs/reference/glossary/mixer-instance.md
  content/docs/reference/glossary/mixer.md
  content/docs/reference/glossary/service-version.md
Labels: cla: yes

#4325 fix locality-weighted load balancing sample.
  content/docs/ops/traffic-management/locality-load-balancing/index.md
Labels: cla: yes

#4333 fix typo.
  content/docs/setup/kubernetes/install/helm/index.md
Labels: cla: yes

#4255 Injection caveats docs
  content/docs/ops/setup/injection/index.md
Labels: cla: yes

#4340 Remove hyphens in IBM-Cloud-Private
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
Labels: cla: yes

#4341 Adding missing quotes to yaml in traffic management docs
  content/docs/concepts/traffic-management/index.md
  content_zh/docs/concepts/traffic-management/index.md
Labels: cla: yes

#4263 Improve citadel doc: make it clear multiple-citadel is not supported
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content/help/ops/security/repairing-citadel/index.md
Labels: cla: yes

#4345 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixc/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/node_agent/index.html
  content/docs/reference/commands/operator/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html
  content/docs/reference/config/policy-and-telemetry/templates/apikey/index.html
  content/docs/reference/config/policy-and-telemetry/templates/authorization/index.html
  content/docs/reference/config/policy-and-telemetry/templates/checknothing/index.html
  content/docs/reference/config/policy-and-telemetry/templates/edge/index.html
  content/docs/reference/config/policy-and-telemetry/templates/listentry/index.html
  content/docs/reference/config/policy-and-telemetry/templates/logentry/index.html
  content/docs/reference/config/policy-and-telemetry/templates/metric/index.html
  content/docs/reference/config/policy-and-telemetry/templates/quota/index.html
  content/docs/reference/config/policy-and-telemetry/templates/reportnothing/index.html
  content/docs/reference/config/policy-and-telemetry/templates/tracespan/index.html
Labels: cla: yes

#4339 Docker Desktop updates
  content/docs/setup/kubernetes/platform-setup/docker/index.md
Labels: cla: yes

#4338 remove ICP IKS multicluster page
  content/docs/tasks/multicluster/iks-icp/index.md
  content_zh/docs/tasks/multicluster/iks-icp/index.md
Labels: cla: yes

#4336 Fix mTLS migration page
  content/docs/tasks/security/mtls-migration/index.md
Labels: cla: yes

#4319 authz permissive doc fix
  content/docs/tasks/security/authz-permissive/index.md
Labels: cla: yes

#4203 Updated with instructions for LightStep Tracing vs. LightStep [x]pm
  content/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
Labels: cla: no

#4284 Edits to rate limiting task
  .spelling
  content/docs/tasks/policy-enforcement/control-headers/index.md
  content/docs/tasks/policy-enforcement/denial-and-list/index.md
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes

#4299 Enhance minikube getting started page
  .spelling
  content/docs/setup/kubernetes/platform-setup/minikube/index.md
Labels: cla: yes

#4318 Update tracing task doc
  content/docs/concepts/what-is-istio/index.md
  content/docs/tasks/telemetry/distributed-tracing/jaeger/index.md
  content/docs/tasks/telemetry/distributed-tracing/jaeger/istio-tracing-details.png
  content/docs/tasks/telemetry/distributed-tracing/jaeger/istio-tracing-list.png
  content/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content/docs/tasks/telemetry/distributed-tracing/zipkin/index.md
  content/docs/tasks/telemetry/distributed-tracing/zipkin/istio-tracing-details-zipkin.png
  content/docs/tasks/telemetry/distributed-tracing/zipkin/istio-tracing-list-zipkin.png
  content/faq/distributed-tracing/how-to-support-tracing.md
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/overview/index.md
  content_zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content_zh/faq/distributed-tracing/how-to-support-tracing.md
  content_zh/faq/distributed-tracing/istio-copy-headers.md
  content_zh/faq/telemetry/istio-copy-headers.md
Labels: cla: yes

#4342 Update command for deprecated old style CRDs
  content/docs/ops/telemetry/missing-metrics/index.md
Labels: cla: yes

#4347 update CRDs count.
  content/boilerplates/verify-crds.md
Labels: cla: yes

#4351 Patch #4263 to master
  content/docs/ops/security/repairing-citadel/index.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes

#4352 update required helm version.
  content/docs/setup/kubernetes/install/multicluster/vpn/index.md
Labels: cla: yes

#4357 Title improvements
  content/docs/ops/_index.md
  content/docs/setup/kubernetes/_index.md
Labels: cla: yes

#4360 Update the version number.
  data/args.yml
Labels: cla: yes

#4307 Refine the multicluster gateways installation documentation
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
Labels: cla: yes

#4349 Fix RBAC groups user guide [master branch]
  content/docs/tasks/security/rbac-groups/index.md
Labels: area/security, cla: yes

#4366 Fix warning
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes

#4365 Stop checking in the "generated" directory.
  .gitignore
  Makefile
  generated/css/all.css
  generated/css/all.css.map
  generated/img/icons.svg
  generated/js/all.min.js
  generated/js/all.min.js.map
  generated/js/themes_init.min.js
  generated/js/themes_init.min.js.map
  tsconfig.json
Labels: cla: yes

#4359 Getting started page, one more time
  content/_index.md
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/getting-started/index.md
  content/docs/setup/kubernetes/install/helm/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes

#4320 rbac: simplify and make authorization HTTP/TCP tasks consistent
  content/docs/tasks/security/authz-http/index.md
  content/docs/tasks/security/authz-permissive/index.md
  content/docs/tasks/security/authz-tcp/index.md
Labels: cla: yes

#4346 zh: fix typo for glossary page
  content_zh/docs/reference/glossary/adapters.md
  content_zh/docs/reference/glossary/mixer-instance.md
  content_zh/docs/reference/glossary/service-version.md
Labels: cla: yes, translation/chinese

#4376 Add SataQiu as a reviewer for Chinese
  CODEOWNERS
Labels: cla: yes

#4355 using $SOURCE_POD variable
  content/docs/tasks/telemetry/logs/access-log/index.md
Labels: cla: yes

#4377 Remove GDB documentation
  content/docs/ops/component-debugging/index.md
Labels: cla: yes

#4378 The architecture diagram was damaged
  content/docs/concepts/what-is-istio/arch.svg
Labels: cla: yes

#4379 Fix doc 'istioctl apply' -> 'kubectl apply'
  content/docs/tasks/security/mutual-tls/index.md
Labels: cla: yes

#4306 zh: /help/ops/security/root-transition/index.md
  content_zh/blog/2019/root-transition/index.md
  content_zh/boilerplates/notes/1.1.md
  content_zh/docs/setup/kubernetes/upgrade/steps/index.md
  content_zh/help/ops/security/root-transition/index.md
Labels: cla: yes, translation/chinese

#4381 The dotted lines turned solid on import
  content/docs/concepts/what-is-istio/arch.svg
Labels: cla: yes

#4390 skip toc for Getting Started
  content/docs/setup/kubernetes/getting-started/index.md
Labels: cla: yes

#4389 Update reference docs
  content/about/community/partners/wso2.svg
  content/about/contribute/diagrams/diagram-guidelines.svg
  content/docs/concepts/what-is-istio/arch.svg
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixc/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  scripts/grab_reference_docs.sh
  src/icons/download.svg
Labels: cla: yes

#4391 Update reference docs
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/node_agent/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes

#4386 Update prep & install docs for IBM
  content/docs/setup/kubernetes/install/platform/ibm/add-on-install.png
  content/docs/setup/kubernetes/install/platform/ibm/index.md
  content/docs/setup/kubernetes/platform-setup/ibm/index.md
Labels: cla: no

#4394 Cluster-Aware Service Routing updates
  content/docs/tasks/multicluster/split-horizon-eds/index.md
Labels: cla: yes

#4396 Updated traffic management to point to ingress docs
  content/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: cla: yes

#4406 revise doc
  content/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: cla: yes

#4407 Improve ingress gateway doc
  content/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: cla: yes

#4399 Update to use kubectl apply instead of create where possible
  content/docs/tasks/multicluster/split-horizon-eds/index.md
Labels: cla: yes

#4383 Add loverto and SataQiu to OWNERS for Chinese (release-1.1 branch)
  content_zh/OWNERS
Labels: cla: yes

#4403 Address errors on the 'Secure Ingress Mount' page
  content/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
Labels: cla: yes

#4412 Move root-transition to docs/ to follow others
  content/blog/2019/root-transition/index.md
  content/docs/ops/security/root-transition/index.md
Labels: cla: yes

#4350 Fix RBAC groups user guide [release-1.1 branch]
  content/docs/tasks/security/rbac-groups/index.md
Labels: area/security, cla: yes

#4134 small update to policy check default
  content/docs/concepts/policies-and-telemetry/index.md
Labels: cla: yes

#4424 Remove links to outdated code
  content/docs/concepts/traffic-management/index.md
  content/docs/ops/security/root-transition/index.md
  content/docs/ops/traffic-management/locality-load-balancing/index.md
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/faq/distributed-tracing/how-distributed-tracing-works.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/ops/traffic-management/locality-load-balancing/index.md
  content_zh/docs/reference/config/istio.networking.v1alpha3/index.md
  content_zh/docs/tasks/security/authz-http/index.md
  content_zh/docs/tasks/security/authz-permissive/index.md
  content_zh/docs/tasks/security/authz-tcp/index.md
  content_zh/docs/tasks/security/role-based-access-control/index.md
  content_zh/faq/distributed-tracing/how-distributed-tracing-works.md
Labels: cla: yes

#4397 fix the egress gateway example for multi cluster gateways
  content/docs/tasks/multicluster/gateways/index.md
Labels: cla: yes

#4426 Update Galley feature stages.
  content/about/feature-stages/index.md
Labels: cla: yes

#4321 Add new Traffic management concept.
  content/blog/2017/0.1-canary/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/blog/2019/announcing-1.1/index.md
  content/boilerplates/notes/0.8.md
  content/boilerplates/notes/1.0.md
  content/boilerplates/notes/1.1.md
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/concepts/security/index.md
  content/docs/concepts/traffic-management/_index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/concepts/traffic-management/network/index.md
  content/docs/concepts/traffic-management/overview/discovery.svg
  content/docs/concepts/traffic-management/overview/index.md
  content/docs/concepts/traffic-management/overview/pilot-arch.svg
  content/docs/concepts/traffic-management/overview/routing-overview.svg
  content/docs/concepts/traffic-management/routing/_index.md
  content/docs/concepts/traffic-management/routing/destination-rules/destination-rules-1.svg
  content/docs/concepts/traffic-management/routing/destination-rules/index.md
  content/docs/concepts/traffic-management/routing/gateways/gateways-1.svg
  content/docs/concepts/traffic-management/routing/gateways/gateways-2.svg
  content/docs/concepts/traffic-management/routing/gateways/index.md
  content/docs/concepts/traffic-management/routing/service-entries/index.md
  content/docs/concepts/traffic-management/routing/service-entries/service-entries-1.svg
  content/docs/concepts/traffic-management/routing/sidecars/index.md
  content/docs/concepts/traffic-management/routing/virtual-services/index.md
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-1.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-2.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-3.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-4.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-5.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-6.svg
  content/docs/concepts/what-is-istio/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/ops/traffic-management/introduction/index.md
  content/docs/reference/config/networking/_index.md
  content/docs/reference/glossary/service-registry.md
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content/docs/tasks/security/authn-policy/index.md
  content/docs/tasks/traffic-management/egress/egress-control/index.md
  content/docs/tasks/traffic-management/request-timeouts/index.md
  content/faq/security/enabling-disabling-mtls.md
  content_zh/boilerplates/notes/1.1.md
Labels: cla: no

#4429 zh: update outdated link in RBAC tasks
  content_zh/docs/tasks/security/authz-http/index.md
  content_zh/docs/tasks/security/authz-permissive/index.md
  content_zh/docs/tasks/security/authz-tcp/index.md
  content_zh/docs/tasks/security/role-based-access-control/index.md
Labels: cla: yes, translation/chinese

#4418 zh: sync /docs/setup/kubernetes/upgrade/steps/index.md
  content_zh/boilerplates/notes/1.1.md
  content_zh/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes, translation/chinese

#4438 Another test
  content/test/boil/index.md
Labels: cla: yes

#4435 Clarify support for alpha features
  content/about/feature-stages/index.md
Labels: cla: yes

#4353 update multi-cluster setup doc in ICP.
  content/docs/tasks/multicluster/icp/index.md
Labels: area/environments, cla: yes

#4431 1.0 eol final announcement.
  content/blog/2019/announcing-1.0-eol-final/index.md
Labels: cla: yes

#4440 Cherry-Pick coderwoner for 1.1
  CODEOWNERS
Labels: cla: yes

#4419 zh: /blog/2019/cve-2019-12243/index.md
  content_zh/blog/2019/cve-2019-12243/index.md
Labels: cla: yes, translation/chinese

#4302 zh: Update index.md
  content_zh/docs/tasks/security/mtls-migration/index.md
Labels: cla: yes, translation/chinese

#4444 cherry pick - small update to policy check default #4134
  content/docs/concepts/policies-and-telemetry/index.md
Labels: cla: yes

#4447 Fix fault injection task
  .spelling
  content/docs/tasks/traffic-management/fault-injection/index.md
Labels: cla: yes

#4442 Fix www.envoyproxy.io links
  content/blog/2019/appswitch/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/help/faq/distributed-tracing/how-distributed-tracing-works.md
  content/help/ops/security/root-transition/index.md
  content/help/ops/traffic-management/locality-load-balancing/index.md
  content_zh/blog/2019/appswitch/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/reference/config/istio.networking.v1alpha3/index.md
  content_zh/help/faq/distributed-tracing/how-distributed-tracing-works.md
  content_zh/help/ops/security/root-transition/index.md
  content_zh/help/ops/traffic-management/locality-load-balancing/index.md
Labels: cla: yes

#4425 Improve the flow and language of the Getting started doc.
  content/docs/setup/kubernetes/_index.md
  content/docs/setup/kubernetes/getting-started/index.md
  content/docs/setup/kubernetes/install/kubernetes/index.md
Labels: cla: yes

#4450 Point to the right branch of istio/istio
  data/args.yml
Labels: cla: yes

#4451 Fix double and trailing spaces.
  content/docs/concepts/traffic-management/network/index.md
  content/docs/concepts/traffic-management/overview/index.md
  content/docs/concepts/traffic-management/routing/_index.md
  content/docs/concepts/traffic-management/routing/destination-rules/index.md
  content/docs/concepts/traffic-management/routing/gateways/index.md
  content/docs/concepts/traffic-management/routing/service-entries/index.md
  content/docs/concepts/traffic-management/routing/sidecars/index.md
  content/docs/concepts/traffic-management/routing/virtual-services/index.md
Labels: cla: yes

#4452 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes

#4410 Fix authn-policy task: add missing cleanup and a dependent lib
  .spelling
  content/docs/tasks/security/authn-policy/index.md
Labels: cla: yes

#4453 Fix sample indentation
  content/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: cla: yes

#4449 Traffic managment concepts fixes
  content/docs/concepts/traffic-management/routing/virtual-services/index.md
Labels: cla: yes

#4430 1.1.9 release notes.
  content/about/notes/1.1.9/index.md
  content/blog/2019/announcing-1.1.9/index.md
  content/boilerplates/notes/1.1.9.md
Labels: cla: yes

#4434 Update feature stability for 1.2
  content/about/feature-stages/index.md
Labels: cla: yes

#4443 zh: fix content_zh/blog/2019/cve-2019-12243 link
  content_zh/blog/2019/cve-2019-12243/index.md
Labels: cla: yes, translation/chinese

#4466 cherry pick 1.1.9 release notes into release-1.1 branch
  content/about/notes/1.1.9/index.md
  content/blog/2019/announcing-1.1.9/index.md
  content/boilerplates/notes/1.1.9.md
  data/args.yml
Labels: cla: yes

#4437 Fix setup for Egress Gateway with NetworkPolicy doc
  content/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: area/networking, cla: yes

#4475 VS merging is no longer experimental
  content/docs/ops/traffic-management/deploy-guidelines/index.md
Labels: cla: yes

#4476 Fix incorrect istioctl command
  content/docs/ops/traffic-management/troubleshooting/index.md
Labels: cla: yes

#4411 Add extra warning to 'Cluster-Aware Service Routing' page
  content/docs/tasks/multicluster/split-horizon-eds/index.md
Labels: cla: yes

#4433 Refine the health check doc.
  content/docs/ops/setup/app-health-check/index.md
Labels: cla: yes

#4479 Fix Hugo page generation issue.
  content/docs/concepts/traffic-management/routing/destination-rules/index.md
Labels: cla: yes, kind/docs

#4445 Fix the security tasks.
  content/docs/tasks/security/health-check/index.md
  content/docs/tasks/security/plugin-ca-cert/index.md
Labels: cla: yes

#4398 Update CNI docs
  .spelling
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/install/helm/index.md
  src/ts/tabset.ts
Labels: area/networking, cla: yes

#4488 Reverts the new Traffic management concept due to Hugo bug
  content/blog/2017/0.1-canary/index.md
  content/blog/2018/incremental-traffic-management/index.md
  content/blog/2019/announcing-1.1/index.md
  content/boilerplates/notes/0.8.md
  content/boilerplates/notes/1.0.md
  content/boilerplates/notes/1.1.md
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/concepts/security/index.md
  content/docs/concepts/traffic-management/_index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/concepts/traffic-management/network/index.md
  content/docs/concepts/traffic-management/overview/discovery.svg
  content/docs/concepts/traffic-management/overview/index.md
  content/docs/concepts/traffic-management/overview/pilot-arch.svg
  content/docs/concepts/traffic-management/overview/routing-overview.svg
  content/docs/concepts/traffic-management/routing/_index.md
  content/docs/concepts/traffic-management/routing/destination-rules/destination-rules-1.svg
  content/docs/concepts/traffic-management/routing/destination-rules/index.md
  content/docs/concepts/traffic-management/routing/gateways/gateways-1.svg
  content/docs/concepts/traffic-management/routing/gateways/gateways-2.svg
  content/docs/concepts/traffic-management/routing/gateways/index.md
  content/docs/concepts/traffic-management/routing/service-entries/index.md
  content/docs/concepts/traffic-management/routing/service-entries/service-entries-1.svg
  content/docs/concepts/traffic-management/routing/sidecars/index.md
  content/docs/concepts/traffic-management/routing/virtual-services/index.md
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-1.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-2.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-3.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-4.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-5.svg
  content/docs/concepts/traffic-management/routing/virtual-services/virtual-services-6.svg
  content/docs/concepts/what-is-istio/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/ops/traffic-management/introduction/index.md
  content/docs/reference/config/networking/_index.md
  content/docs/reference/glossary/service-registry.md
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content/docs/tasks/security/authn-policy/index.md
  content/docs/tasks/traffic-management/egress/egress-control/index.md
  content/docs/tasks/traffic-management/request-timeouts/index.md
  content/faq/security/enabling-disabling-mtls.md
  content_zh/boilerplates/notes/1.1.md
Labels: cla: yes, kind/docs

#4469 Release note 1.2
  .spelling
  content/about/notes/1.2/index.md
  content/boilerplates/notes/1.2.md
Labels: cla-manual, cla: no

#4485 Update description of Kiali graph icon
  content/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes

#4480 Minor cleanup of enabling-policy and rate-limiting for clarity
  content/docs/tasks/policy-enforcement/enabling-policy/index.md
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes

#4408 Update installation options for release-1.2
  content/docs/reference/config/installation-options-changes/index.md
  content/docs/reference/config/installation-options/index.md
Labels: cla: yes

#4474 add ipv6 support to sync with release note
  content/about/feature-stages/index.md
Labels: cla: yes

#4482 Document commands for running Kiali on OpenShift
  content/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes

#4477 Temporarily point GKE platform setup to OSS instructions
  content/docs/setup/kubernetes/install/platform/gke/index.md
Labels: cla: yes

#4471 Add upgrade notice for 1.2
  content/docs/setup/kubernetes/upgrade/notice/index.md
  content/docs/tasks/telemetry/kiali/index.md
Labels: cla: yes

#4468 Istio 1.2 announcement blog post
  .spelling
  content/about/feature-stages/index.md
  content/blog/2019/announcing-1.2/index.md
Labels: cla: yes

#4405 Remove [x]PM unless necessary
  content/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
Labels: cla: no

#4472 Refine the upgrade steps.
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: cla: yes

#4490 Revert "1.0 eol final announcement. (#4431)"
  content/blog/2019/announcing-1.0-eol-final/index.md
Labels: cla: yes

#4496 Restore eol final announcement.
  content/blog/2019/announcing-1.0-eol-final/index.md
Labels: cla: yes

#4495 Fix list not displaying correctly
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
Labels: cla: yes

#4498 Update apiVersion in blog
  content/blog/2017/0.1-canary/index.md
Labels: cla: yes

#4501 Add mising aliases
  content/docs/ops/_index.md
  content/docs/ops/component-debugging/index.md
  content/docs/ops/component-logging/index.md
  content/docs/ops/controlz/index.md
  content/docs/ops/misc/index.md
  content/docs/ops/security/_index.md
  content/docs/ops/security/authorization-permissive/index.md
  content/docs/ops/security/authorization-restrictive/index.md
  content/docs/ops/security/debugging-authorization/index.md
  content/docs/ops/security/end-user-auth/index.md
  content/docs/ops/security/keys-and-certs/index.md
  content/docs/ops/security/mutual-tls/index.md
  content/docs/ops/security/repairing-citadel/index.md
  content/docs/ops/security/root-transition/index.md
  content/docs/ops/setup/_index.md
  content/docs/ops/setup/app-health-check/index.md
  content/docs/ops/setup/injection/index.md
  content/docs/ops/setup/required-pod-capabilities/index.md
  content/docs/ops/setup/validation/index.md
  content/docs/ops/setup/webhook/index.md
  content/docs/ops/telemetry/_index.md
  content/docs/ops/telemetry/envoy-stats/index.md
  content/docs/ops/telemetry/grafana/index.md
  content/docs/ops/telemetry/missing-metrics/index.md
  content/docs/ops/traffic-management/_index.md
  content/docs/ops/traffic-management/deploy-guidelines/index.md
  content/docs/ops/traffic-management/introduction/index.md
  content/docs/ops/traffic-management/locality-load-balancing/index.md
  content/docs/ops/traffic-management/proxy-cmd/index.md
  content/docs/ops/traffic-management/troubleshooting/index.md
Labels: cla: yes

#4455 remove out-dated upgrade notice for mTLS and RBAC
  content/boilerplates/notes/1.1.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content_zh/boilerplates/notes/1.1.md
  content_zh/docs/setup/kubernetes/upgrade/notice/index.md
  content_zh/docs/setup/kubernetes/upgrade/setps/index.md
Labels: area/security, cla: yes

#4506 [1.2] Remove out-dated security upgrade notice
  content/boilerplates/notes/1.1.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content_zh/boilerplates/notes/1.1.md
  content_zh/docs/setup/kubernetes/upgrade/notice/index.md
  content_zh/docs/setup/kubernetes/upgrade/setps/index.md
Labels: area/security, cla: yes

#4500 Install istio-cni into kube-system to use system-node-critical priorityClass
  content/docs/setup/kubernetes/additional-setup/cni/index.md
  content/docs/setup/kubernetes/install/helm/index.md
Labels: area/networking, cla: yes

#4505 fix(metrics docs): cleanup metrics docs for commands and default metrics
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/config/policy-and-telemetry/metrics/index.md
Labels: cla: yes

#4484 Add tip to mention the policy propagation could be slow
  content/docs/tasks/security/authn-policy/index.md
Labels: cla: yes

#3734 Add Gardener project to platform-setup
  content/docs/setup/kubernetes/prepare/platform-setup/gardener/images/gardener_addon_checkboxes.png
  content/docs/setup/kubernetes/prepare/platform-setup/gardener/images/gardener_service_account.png
  content/docs/setup/kubernetes/prepare/platform-setup/gardener/images/gardener_shoot_creation.png
  content/docs/setup/kubernetes/prepare/platform-setup/gardener/index.md
Labels: cla: yes

#4511 Address comments from Doug re Mixer upgrade notice
  content/docs/setup/kubernetes/upgrade/notice/index.md
Labels: action/merge-to-release-branch, cla: yes

#4514 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/node_agent/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/docs/reference/config/networking/v1alpha3/service-entry/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking/index.html
  content/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes

#4515 Fix some stale links.
  content/docs/setup/kubernetes/prepare/platform-setup/gardener/index.md
Labels: cla: yes

#4493 Apply crds separately to avoid race
  content/docs/tasks/multicluster/gke/index.md
  content/docs/tasks/security/auth-sds/index.md
  content/docs/tasks/security/vault-ca/index.md
Labels: action/merge-to-release-branch, cla: yes

#4517 Remove percent synced from istioctl output sample
  content/docs/ops/traffic-management/proxy-cmd/index.md
Labels: cla: yes

#4508 Update index.md
  content/docs/concepts/traffic-management/index.md
Labels: cla: yes

#4520 Cherry-pick commits
  content/blog/2017/0.1-canary/index.md
  content/docs/ops/_index.md
  content/docs/ops/component-debugging/index.md
  content/docs/ops/component-logging/index.md
  content/docs/ops/controlz/index.md
  content/docs/ops/misc/index.md
  content/docs/ops/security/_index.md
  content/docs/ops/security/authorization-permissive/index.md
  content/docs/ops/security/authorization-restrictive/index.md
  content/docs/ops/security/debugging-authorization/index.md
  content/docs/ops/security/end-user-auth/index.md
  content/docs/ops/security/keys-and-certs/index.md
  content/docs/ops/security/mutual-tls/index.md
  content/docs/ops/security/repairing-citadel/index.md
  content/docs/ops/security/root-transition/index.md
  content/docs/ops/setup/_index.md
  content/docs/ops/setup/app-health-check/index.md
  content/docs/ops/setup/injection/index.md
  content/docs/ops/setup/required-pod-capabilities/index.md
  content/docs/ops/setup/validation/index.md
  content/docs/ops/setup/webhook/index.md
  content/docs/ops/telemetry/_index.md
  content/docs/ops/telemetry/envoy-stats/index.md
  content/docs/ops/telemetry/grafana/index.md
  content/docs/ops/telemetry/missing-metrics/index.md
  content/docs/ops/traffic-management/_index.md
  content/docs/ops/traffic-management/deploy-guidelines/index.md
  content/docs/ops/traffic-management/introduction/index.md
  content/docs/ops/traffic-management/locality-load-balancing/index.md
  content/docs/ops/traffic-management/proxy-cmd/index.md
  content/docs/ops/traffic-management/troubleshooting/index.md
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
Labels: cla: yes

#4521 More missing aliases
  content/faq/_index.md
  content/faq/distributed-tracing/index.md
  content/faq/general/index.md
  content/faq/metrics-and-logs/index.md
  content/faq/mixer/index.md
  content/faq/security/index.md
  content/faq/setup/index.md
  content/faq/traffic-management/index.md
Labels: action/merge-to-release-branch, cla: yes

#4519 Mention istioctl authn tls-check only check conflict states between c…
  content/docs/tasks/security/mutual-tls/index.md
Labels: action/merge-to-release-branch, cla: yes

#4525 Add new Traffic management concept as a single page
  .spelling
  content/blog/2017/0.1-canary/index.md
  content/blog/2019/announcing-1.1/index.md
  content/docs/concepts/traffic-management/destination-rules-1.svg
  content/docs/concepts/traffic-management/discovery.svg
  content/docs/concepts/traffic-management/gateways-1.svg
  content/docs/concepts/traffic-management/gateways-2.svg
  content/docs/concepts/traffic-management/index.md
  content/docs/concepts/traffic-management/pilot-arch.svg
  content/docs/concepts/traffic-management/routing-overview.svg
  content/docs/concepts/traffic-management/service-entries-1.svg
  content/docs/concepts/traffic-management/virtual-services-1.svg
  content/docs/concepts/traffic-management/virtual-services-2.svg
  content/docs/concepts/traffic-management/virtual-services-3.svg
  content/docs/concepts/traffic-management/virtual-services-4.svg
  content/docs/concepts/traffic-management/virtual-services-5.svg
  content/docs/concepts/traffic-management/virtual-services-6.svg
  content/docs/concepts/what-is-istio/index.md
  content/docs/reference/config/networking/_index.md
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content/docs/tasks/security/authn-policy/index.md
  content/docs/tasks/traffic-management/egress/egress-control/index.md
  content/docs/tasks/traffic-management/request-timeouts/index.md
  content_zh/docs/concepts/traffic-management/LoadBalancing.svg
  content_zh/docs/concepts/traffic-management/PilotAdapters.svg
  content_zh/docs/concepts/traffic-management/ServiceModel_RequestFlow.svg
  content_zh/docs/concepts/traffic-management/ServiceModel_Versions.svg
  content_zh/docs/concepts/traffic-management/TrafficManagementOverview.svg
  content_zh/docs/concepts/traffic-management/index.md
Labels: cla: yes

#4528 Update reference docs.
  content/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking/index.html
Labels: action/merge-to-release-branch, cla: yes

#4527 Fix doc issue
  content/docs/tasks/security/auth-sds/index.md
Labels: cla: yes
