Repository istio/istio.io, pull requests merged in 2019-09, with the labels that each got.

#4878 fix notes
  content/docs/concepts/traffic-management/index.md
Labels: cherrypick/master, cla: yes, size/XS

#4882 Add www.mysql.com to the link checking exception list, since it seems…
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#4877 Glossary improvements
  content/en/docs/reference/glossary/control-plane.md
  content/en/docs/reference/glossary/managed-control-plane.md
  content/en/docs/reference/glossary/service-mesh.md
Labels: cla: yes, size/S

#4890 Update upgrade steps for Istio 1.3
  README.md
  content/en/docs/setup/upgrade/steps/index.md
  data/args.yml
  layouts/shortcodes/istio_previous_version.html
Labels: cla: yes, size/L

#4901 Update auth-sds user guide
  content/en/docs/tasks/security/auth-sds/index.md
Labels: area/security, cherrypick/release-1.3, cla: yes, size/XS

#4907 Fixed vertical positioning of glossary entries.
  Makefile.core.mk
  src/sass/misc/_glossary.scss
Labels: cla: yes, size/S

#4911 Update reference docs.
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istio_ca/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/node_agent/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html
  content/en/docs/reference/config/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/en/docs/reference/config/networking/v1alpha3/envoy-filter/index.html
  content/en/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/en/docs/reference/config/networking/v1alpha3/service-entry/index.html
  content/en/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/en/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/app-identity-access-adapter/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/circonus/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/cloudmonitor/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/cloudwatch/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/datadog/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/denier/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/list/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/memquota/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/opa/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/prometheus/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/redisquota/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/signalfx/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/statsd/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stdio/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/zipkin/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/analytics/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/apikey/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/authorization/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/checknothing/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/edge/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/kubernetes/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/listentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/logentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/metric/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/quota/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/reportnothing/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/tracespan/index.html
Labels: cla: yes, size/XL

#4902 [release-1.3] Fixed injection and validation operations guides
  content/en/docs/ops/setup/injection-concepts/index.md
  content/en/docs/ops/setup/validation/index.md
Labels: cla: yes, kind/docs, size/S

#4701 Sds trustworthy jwt doc
  content/en/blog/2019/trustworthy-jwt-sds/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/platform-setup/gke/index.md
  content/en/docs/setup/platform-setup/minikube/index.md
  content/en/docs/tasks/security/auth-sds/index.md
Labels: cla: yes, kind/docs, size/M

#4918 Remove unneeded info in Setup page
  content/en/docs/setup/_index.md
Labels: cla: yes, size/XS

#4906 Update ingress-sds
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: area/security, cherrypick/release-1.3, cla: yes, size/S

#4904 [Release 1.3] Temporarily disable the user guide of Istio Vault integration for release 1.3
  content/en/about/feature-stages/index.md
  content/en/boilerplates/notes/1.1.md
  content/en/docs/tasks/security/vault-ca/index.md
  content/zh/boilerplates/notes/1.1.md
  content/zh/docs/tasks/security/vault-ca/index.md
Labels: area/security, area/user experience, cla: yes, kind/docs, size/L

#4920 match CRD with english version
  content_zh/docs/setup/kubernetes/install/helm/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#4916 Remove warning about obscure edge case in install
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS

#4925 Align multi-cluster examples with new terminology
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
Labels: cla: yes, size/M

#4905 [release-1.3] Enable OpenShift
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, kind/docs, size/S

#4790 Add Istio Operator install guide
  content/en/about/feature-stages/index.md
  content/en/boilerplates/experimental-feature-warning.md
  content/en/docs/reference/glossary/operator.md
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, kind/docs, size/L

#4917 Simplify CRD verification step
  content/en/boilerplates/verify-crds.md
Labels: cla: yes, size/XS

#4923 Remove platform-specific install instructions
  content/en/docs/setup/_index.md
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/install/platform/_index.md
  content/en/docs/setup/install/platform/alicloud/index.md
  content/en/docs/setup/install/platform/gke/dm-tracing.png
  content/en/docs/setup/install/platform/gke/dm_bookinfo.png
  content/en/docs/setup/install/platform/gke/dm_grafana.png
  content/en/docs/setup/install/platform/gke/dm_kiali.png
  content/en/docs/setup/install/platform/gke/dm_kubernetes_workloads.png
  content/en/docs/setup/install/platform/gke/dm_launcher.png
  content/en/docs/setup/install/platform/gke/dm_prometheus.png
  content/en/docs/setup/install/platform/gke/index.md
  content/en/docs/setup/install/platform/ibm/add-on-install.png
  content/en/docs/setup/install/platform/ibm/index.md
  content/en/docs/setup/platform-setup/MicroK8s/index.md
  content/en/docs/setup/platform-setup/alicloud/index.md
  content/en/docs/setup/platform-setup/gke/index.md
  content/en/docs/setup/platform-setup/ibm/index.md
  content/zh/docs/setup/kubernetes/install/platform/alicloud/app-catalog-istio-1.0.0.png
  content/zh/docs/setup/kubernetes/install/platform/alicloud/index.md
  content/zh/docs/setup/kubernetes/install/platform/gke/dm_gcp_iam.png
  content/zh/docs/setup/kubernetes/install/platform/gke/dm_gcp_iam_role.png
  content/zh/docs/setup/kubernetes/install/platform/gke/index.md
  content/zh/docs/setup/kubernetes/install/platform/ibm/index.md
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-catalog-1.png
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-catalog-2.png
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-deletion.png
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-installation-1.png
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-installation-2.png
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-release.png
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-upgrade-1.png
  content/zh/docs/setup/kubernetes/install/platform/ibm/istio-upgrade-2.png
Labels: cla: yes, do-not-merge/work-in-progress, size/L

#4932 Small correction in IBM Cloud platform instructions
  content/en/docs/setup/platform-setup/ibm/index.md
Labels: cla: yes, size/XS

#4937 Update reference docs.
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/L

#4875 add faq for auto port detection.
  content/en/faq/setup/k8s-auto-detect-inbound-ports.md
Labels: area/environments, cla: yes, size/XS

#4866 Update installation-options and installation-option-diff files
  content/en/docs/reference/config/installation-options-changes/index.md
  content/en/docs/reference/config/installation-options/index.md
Labels: cla: yes, size/L

#4820 add ambassador API gateway
  content/en/about/community/partners/ambassador.svg
  content/en/about/community/partners/index.md
Labels: cla: yes, ok-to-test, size/S

#4913 Update tablegen.py to be able to be run as part of the CI system
  scripts/tablegen.py
Labels: cla: yes, size/M

#4928 Remove port name requirement
  content/en/docs/ops/traffic-management/protocol-selection/index.md
  content/en/docs/setup/additional-setup/requirements/index.md
  content/en/faq/traffic-management/naming-port-convention.md
Labels: cla: yes, size/M

#4941 Port capture FAQ entry
  content/en/faq/setup/k8s-auto-detect-inbound-ports.md
  content/en/faq/traffic-management/controlling-inbound-ports.md
Labels: cla: yes, size/S

#4948 Refresh docs to include IstioControlPlane proto
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
Labels: cla: yes, size/XXL

#4910 remove force flag for istio init chart upgrade.
  content/en/docs/setup/upgrade/steps/index.md
Labels: area/environments, cla: yes, size/XS

#4746 Add docs for updated Citadel namespace targeting mechanism
  content/en/docs/concepts/security/index.md
  content/en/docs/reference/config/installation-options/index.md
  content/en/docs/tasks/security/ca-namespace-targeting/index.md
Labels: area/security, cla: yes, kind/docs, size/L

#4949 Disable support for the Chinese translation since it has fallen out of date.
  config.toml
  layouts/_default/baseof.html
  layouts/index.redir
  layouts/partials/header.html
Labels: cla: yes, size/S

#4950 Replace uses of ``` with {{< text >}}
  content/en/about/contribute/github/index.md
  content/en/blog/2019/istio-security-003-004/index.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/examples/mesh-expansion/multi-network/index.md
  content/en/docs/examples/mesh-expansion/single-network/index.md
  content/en/docs/ops/app-health-check/index.md
  content/en/docs/ops/traffic-management/protocol-selection/index.md
  content/en/docs/ops/troubleshooting/controlz/index.md
  scripts/lint_site.sh
Labels: cla: yes, size/M

#4952 Add support for text block links that point to other repos.
  content/en/about/contribute/creating-and-editing-pages/index.md
  data/args.yml
  layouts/partials/code_block.html
  src/ts/codeBlocks.ts
Labels: cla: yes, size/M

#4946 Revise ingress-sds user guide
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: cla: yes, size/XS

#4951 Address a recent problem in our release process
  content/en/blog/2019/incorrect-sidecar-image-1.2.4/index.md
Labels: area/security, area/test and release, cla: yes, size/S

#4953 Clarify multi-match and remove sourceLabels doc
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, size/L

#4924 Remove out-dated SDS stuff
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: cla: yes, kind/docs, size/XS

#4936 Add docs to the Istio operator CLI guide
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/L

#4955 Exclude istio/operator from having partner banner displayed
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XS

#4947 Sidecar injection
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: area/networking, cla: yes, size/M

#4960 Fix handling of SVG files without a viewBox element.
  layouts/shortcodes/image.html
Labels: cla: yes, size/XS

#4956 Update Performance and Scalability page for istio 1.3
  content/en/docs/concepts/performance-and-scalability/index.md
  content/en/docs/concepts/performance-and-scalability/latency.svg
  content/en/docs/concepts/performance-and-scalability/latency_p90.svg
Labels: cla: yes, size/XXL

#4980 Improve Tabs CSS
  src/sass/misc/_tabset.scss
  src/sass/themes/_dark-theme.scss
  src/sass/themes/_light-theme.scss
  src/sass/themes/_vars.scss
Labels: cla: yes, kind/docs, size/M

#4989 Fixes for the archive site.
  scripts/build_site.sh
  scripts/gen_archive_site.sh
  scripts/gen_site.sh
  scripts/opt_site.sh
Labels: cla: yes, size/S

#4990 Couple cherry picks
  scripts/gen_archive_site.sh
  src/sass/misc/_tabset.scss
  src/sass/themes/_dark-theme.scss
  src/sass/themes/_light-theme.scss
  src/sass/themes/_vars.scss
Labels: cla: no, size/M

#4991 Temporarily grab operator docs from master to fix broken links.
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XXL

#4992 Add instructions for deleting Istio
  content/en/docs/setup/install/operator/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#4993 [release-1.3] Add instructions for deleting Istio
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/XS

#4994 Fix service version glossary entry
  content/en/docs/reference/glossary/service-version.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#4995 [release-1.3] Fix service version glossary entry
  content/en/docs/reference/glossary/service-version.md
Labels: cla: no, size/XS

#4996 Fix multi-cluster profile descriptions
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#4997 [release-1.3] Fix multi-cluster profile descriptions
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: no, size/XS

#4998 Update release process.
  README.md
Labels: cla: yes, size/M

#4999 Fix the preformatted block download function on Firefox.
  src/ts/utils.ts
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5000 [release-1.3] Fix the preformatted block download function on Firefox.
  src/ts/utils.ts
Labels: cla: yes, size/XS

#4927 larger machine size that can fit default istio install
  content/en/docs/setup/platform-setup/gke/index.md
Labels: cla: no, kind/docs, ok-to-test, size/XS

#5006 typo: "diconnected" in page description
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5007 [release-1.3] typo: "diconnected" in page description
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
Labels: cla: no, size/XS

#5005 Add 1.1.15 release notes.
  content/en/about/notes/1.1.15/index.md
  content/en/blog/2019/announcing-1.1.15/index.md
  content/en/boilerplates/notes/1.1.15.md
Labels: cherrypick/release-1.3, cla: yes, size/S

#5009 Fix broken knative link.
  content/en/blog/2019/evolving-istios-apis/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5010 [release-1.3] Fix broken knative link.
  content/en/blog/2019/evolving-istios-apis/index.md
Labels: cla: yes, size/XS

#5008 [release-1.3] Add 1.1.15 release notes.
  content/en/about/notes/1.1.15/index.md
  content/en/blog/2019/announcing-1.1.15/index.md
  content/en/boilerplates/notes/1.1.15.md
Labels: cla: yes, size/S

#5001 Remove "etc" from service version glossary term
  content/en/docs/reference/glossary/service-version.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#5011 Add release notes for 1.2.6
  content/en/about/notes/1.2.6/index.md
  content/en/blog/2019/announcing-1.2.6/index.md
  content/en/boilerplates/notes/1.2.6.md
Labels: area/test and release, cherrypick/release-1.3, cla: yes, kind/docs, size/M

#5012 [release-1.3] Add release notes for 1.2.6
  content/en/about/notes/1.2.6/index.md
  content/en/blog/2019/announcing-1.2.6/index.md
  content/en/boilerplates/notes/1.2.6.md
Labels: cla: yes, size/M

#4977 update description for SDS with pod security policy
  content/en/docs/tasks/security/auth-sds/index.md
Labels: area/security, cherrypick/release-1.3, cla: yes, size/S

#5015 [release-1.3] update description for SDS with pod security policy
  content/en/docs/tasks/security/auth-sds/index.md
Labels: cla: yes, size/S

#4817 zh: Translate i18n for zh
  i18n/zh.toml
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#4783 Mixer out-of-process adapter for Knative scale-from-zero
  content/en/blog/2019/knative-activator-adapter/index.md
  content/en/blog/2019/knative-activator-adapter/knative-activator.png
  content/en/blog/2019/knative-activator-adapter/knative-mixer-adapter.png
Labels: cherrypick/release-1.3, cla: yes, ok-to-test, size/M

#4975 Mention mirror_percent field in mirroring task
  content/en/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes, size/XS

#5018 fix(release notes): remove Mixer adapter deprecation notice
  content/en/boilerplates/notes/1.3.md
Labels: area/policies and telemetry, area/test and release, cherrypick/release-1.3, cla: yes, size/XS

#5019 [release-1.3] fix(release notes): remove Mixer adapter deprecation notice
  content/en/boilerplates/notes/1.3.md
Labels: cla: yes, size/XS

#5020 [release-1.3] Mixer out-of-process adapter for Knative scale-from-zero
  content/en/blog/2019/knative-activator-adapter/index.md
  content/en/blog/2019/knative-activator-adapter/knative-activator.png
  content/en/blog/2019/knative-activator-adapter/knative-mixer-adapter.png
Labels: cla: no, size/M

#4981 Added App Identity and Access blog
  .spelling
  content/en/blog/2019/app-identity-and-access-adapter/index.md
Labels: cherrypick/release-1.3, cla: yes, kind/docs, ok-to-test, size/L

#5021 [release-1.3] Added App Identity and Access blog
  .spelling
  content/en/blog/2019/app-identity-and-access-adapter/index.md
Labels: cla: no, size/L

#5028 HTML-Proofer links lint errors
  content/en/docs/setup/platform-setup/gardener/index.md
  content/zh/docs/reference/config/policy-and-telemetry/adapters/cloudmonitor/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5030 [release-1.3] HTML-Proofer links lint errors
  content/en/docs/setup/platform-setup/gardener/index.md
  content/zh/docs/reference/config/policy-and-telemetry/adapters/cloudmonitor/index.md
Labels: cla: no, size/XS

#5029 Download button and flow
  content/en/_index.md
  content/en/docs/setup/_index.md
  content/en/docs/setup/install/kubernetes/index.md
  layouts/partials/footer.html
Labels: cherrypick/release-1.3, cla: yes, size/S

#5031 [release-1.3] Download button and flow
  content/en/_index.md
  content/en/docs/setup/_index.md
  content/en/docs/setup/install/kubernetes/index.md
  layouts/partials/footer.html
Labels: cla: no, size/S

#5023 dark-mode-css-bug
  src/sass/themes/_light-theme-syntax.scss
Labels: cherrypick/release-1.3, cla: yes, kind/docs, size/XS

#5014 Updated traffic management concept guide
  content/en/blog/2019/evolving-istios-apis/index.md
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/reference/glossary/crds.md
  content/en/docs/reference/glossary/data-plane.md
  content/en/docs/reference/glossary/routing-rules.md
  content/en/docs/reference/glossary/virtual-service.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: area/networking, cherrypick/release-1.3, cla: yes, kind/docs, ok-to-test, size/XXL

#4821 Adding FAQ entry for elastic search
  content/en/faq/applications/elasticsearch.md
  content/en/faq/applications/index.md
Labels: cla: yes, size/M

#5035 [release-1.3] dark-mode-css-bug
  src/sass/themes/_light-theme-syntax.scss
Labels: cla: yes, size/XS

#5025 Minor egress fixes
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
  content/en/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: cherrypick/release-1.3, cla: yes, size/S

#5042 Manual cherrypick #5014 to 1.3 branch
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/reference/glossary/crds.md
  content/en/docs/reference/glossary/data-plane.md
  content/en/docs/reference/glossary/routing-rules.md
  content/en/docs/reference/glossary/virtual-service.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: cla: yes, ok-to-test, size/XXL

#5036 Should not use loopback addresses
  .spelling
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: yes, size/S

#5044 [release-1.3] Should not use loopback addresses
  .spelling
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: no, size/S

#5045 Add DaoCloud to customers
  content/en/about/community/customers/daocloud.svg
  content/en/about/community/customers/index.md
  content/zh/about/community/customers/index.md
Labels: cherrypick/release-1.3, cla: yes, size/S

#5046 [release-1.3] Add DaoCloud to customers
  content/en/about/community/customers/daocloud.svg
  content/en/about/community/customers/index.md
  content/zh/about/community/customers/index.md
Labels: cla: no, size/S

#5043 document deleting the istio-system namespace in till uninstall path
  content/en/docs/setup/install/helm/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5047 [release-1.3] document deleting the istio-system namespace in till uninstall path
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS

#5053 Update grab_reference_docs.sh to add New Relic Adapter documentation
  scripts/grab_reference_docs.sh
Labels: cla: yes, needs-ok-to-test, size/XS

#5055 Fix typo of authn
  content/en/docs/tasks/security/mutual-tls/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5056 [release-1.3] Fix typo of authn
  content/en/docs/tasks/security/mutual-tls/index.md
Labels: cla: yes, size/XS

#5054 Update reference docs.
  content/en/docs/reference/commands/istio_ca/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/en/docs/reference/config/networking/v1alpha3/envoy-filter/index.html
  content/en/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/en/docs/reference/config/networking/v1alpha3/service-entry/index.html
  content/en/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/en/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/newrelic/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
Labels: cla: yes, size/XL

#5057 Update release-1.3 reference docs.
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/L

#4867 Add FAQ entry for running Cassandra
  content/en/faq/applications/cassandra.md
Labels: cla: yes, size/S

#5058 Update to latest Hugo.
  Makefile
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  netlify.toml
Labels: cla: yes, size/S

#5049 Egress TLS origination port 443 must be HTTPS
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/edge-traffic/egress-tls-origination/index.md
Labels: cherrypick/release-1.3, cla: yes, ok-to-test, size/XS

#5059 [release-1.3] Egress TLS origination port 443 must be HTTPS
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/edge-traffic/egress-tls-origination/index.md
Labels: cla: no, size/XS

#5062 Small traffic-management corrections
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/concepts/traffic-management/index.md
Labels: cherrypick/release-1.3, cla: yes, size/S

#5064 [release-1.3] Small traffic-management corrections
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: no, size/S

#5051 Replace multicast address with class E
  .spelling
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cherrypick/release-1.3, cla: yes, size/S

#5066 [release-1.3] Replace multicast address with class E
  .spelling
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: no, size/S

#5065 add istio.io/client-go as vanity URL
  layouts/index.redir
  static/golang/client-go.html
Labels: cherrypick/release-1.3, cla: yes, ok-to-test, size/XS

#5067 [release-1.3] add istio.io/client-go as vanity URL
  layouts/index.redir
  static/golang/client-go.html
Labels: cla: no, size/XS

#5063 1.3.1 release notes
  .spelling
  content/en/news/2019/announcing-1.3.1/index.md
Labels: cherrypick/release-1.3, cla: yes, size/M

#5072 Add istio.io/release-builder vanity url
  layouts/index.redir
  static/golang/release-builder.html
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5070 Update full_version to 1.3.1
  data/args.yml
Labels: cla: yes, size/XS

#5075 [release-1.3] Add istio.io/release-builder vanity url
  layouts/index.redir
  static/golang/release-builder.html
Labels: cla: yes, size/XS

#5074 [release-1.3] 1.3.1 release notes
  .spelling
  content/en/news/2019/announcing-1.3.1/index.md
Labels: cla: yes, size/M

#5076 Fix probe rewrite configuration command
  content/en/docs/ops/app-health-check/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5073 Remove usages of curl inside istio-proxy
  content/en/docs/ops/security/root-transition/index.md
  content/en/docs/ops/telemetry/envoy-stats/index.md
  content/en/docs/ops/troubleshooting/proxy-cmd/index.md
  content/en/docs/ops/troubleshooting/security-issues/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
Labels: cherrypick/release-1.3, cla: yes, size/M

#5077 [release-1.3] Fix probe rewrite configuration command
  content/en/docs/ops/app-health-check/index.md
Labels: cla: no, size/XS

#5078 [release-1.3] Remove usages of curl inside istio-proxy
  content/en/docs/ops/security/root-transition/index.md
  content/en/docs/ops/telemetry/envoy-stats/index.md
  content/en/docs/ops/troubleshooting/proxy-cmd/index.md
  content/en/docs/ops/troubleshooting/security-issues/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
Labels: cla: yes, size/M

#5027 Added blog for monitoring external service traffic
  .spelling
  content/en/blog/2019/monitoring-external-service-traffic/index.md
Labels: cherrypick/release-1.3, cla: yes, size/L

#5080 [release-1.3] Added blog for monitoring external service traffic
  .spelling
  content/en/blog/2019/monitoring-external-service-traffic/index.md
Labels: cla: yes, size/L

#5081 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/gobuild.sh
Labels: cla: yes, size/M

#5084 Fix broken links
  content/en/docs/examples/mesh-expansion/multi-network/index.md
Labels: cherrypick/release-1.3, cla: yes, size/XS

#5086 [release-1.3] Fix broken links
  content/en/docs/examples/mesh-expansion/multi-network/index.md
Labels: cla: no, size/XS

#5082 Add docs for psp istio-cni settings
  .spelling
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/XS

#5087 Remove inappropriate .spelling entry
  .spelling
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/XS
