Repository istio/istio.io, pull requests merged in 2019-04, with the labels that each got.

#3888 zh: add about/notes/1.1.2/index.md
  content_zh/about/notes/1.1.2/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3909 Fix handling of HTML entities in text blocks sometimes showing up as …
  generated/js/all.min.js
  generated/js/all.min.js.map
  src/ts/codeBlocks.ts
  src/ts/utils.ts
Labels: approved, cla: yes

#3908 zh: /docs/tasks/telemetry/gateways/index.md
  content_zh/docs/tasks/telemetry/gateways/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3910 zh: /blog/2019/sail-the-blog/index.md
  content_zh/blog/2019/sail-the-blog/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3877 zh： notice
  content_zh/docs/setup/kubernetes/upgrade/notice/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3891 Tidy up the minikube platform setup documentation
  content/docs/setup/kubernetes/prepare/platform-setup/minikube/index.md
Labels: approved, cla: yes, lgtm

#3913 zh: /docs/examples/advanced-gateways/ingress-certmgr/index.md
  content_zh/blog/2019/announcing-1.1/index.md
  content_zh/docs/examples/advanced-gateways/ingress-certmgr/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3919 More prep work for 1.1.2
  content/about/notes/1.0.7/index.md
  content/about/notes/1.1.2/index.md
  content/blog/2019/announcing-1.1.2/index.md
  content/boilerplates/notes/1.0.7.md
  content/boilerplates/notes/1.1.2.md
  content_zh/about/notes/1.1.2/index.md
  layouts/_default/release-note.html
  layouts/shortcodes/announcement_links.html
  layouts/shortcodes/relnote_links.html
Labels: approved, cla: yes

#3922 Fix copy to clipboard feature.
  generated/js/all.min.js
  generated/js/all.min.js.map
  src/ts/utils.ts
Labels: approved, cla: yes

#3924 Fix broken helm link in boilerplate security warn
  content/blog/2018/incremental-traffic-management/index.md
  content/boilerplates/helm-security-warning.md
  content_zh/blog/2018/incremental-traffic-management/index.md
  content_zh/boilerplates/helm-security-warning.md
  content_zh/docs/setup/kubernetes/install/platform/ibm/index.md
Labels: cla: yes, lgtm

#3916 Remove experimental security feature
  content/about/feature-stages/index.md
Labels: approved, cla: yes, lgtm

#3918 zh: /blog/2019/custom-ingress-gateway/index.md
  content_zh/blog/2019/custom-ingress-gateway/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3867 Update mTLS tutorial to correct namespace for destination rules.
  content/docs/tasks/security/authn-policy/index.md
Labels: cla: yes

#3928 Site improvements
  content/about/community/customers/getyourguide.svg
  content/about/community/join/gcal.svg
  content/blog/2018/egress-mongo/index.md
  content/blog/2018/egress-monitoring-access-control/egress-adapters-monitoring-policy.svg
  content/blog/2018/egress-monitoring-access-control/egress-adapters-monitoring.svg
  content/blog/2018/egress-monitoring-access-control/http-to-gateway.svg
  content/blog/2018/egress-monitoring-access-control/https-to-gateway.svg
  content/docs/concepts/performance-and-scalability/latency.svg
  content/docs/concepts/what-is-istio/arch.svg
  content/docs/examples/advanced-gateways/egress-gateway-tls-origination/index.md
  content/docs/examples/advanced-gateways/egress-gateway/index.md
  content/docs/examples/advanced-gateways/wildcard-egress-hosts/index.md
  content/test/tabs_and_lists/index.md
  generated/css/all.css
  generated/css/all.css.map
  generated/img/icons.svg
  generated/js/all.min.js
  generated/js/all.min.js.map
  i18n/en.toml
  i18n/zh.toml
  layouts/partials/footer.html
  layouts/shortcodes/text_hack.html
  scripts/opt_site.sh
  src/icons/download.svg
  src/icons/slack.svg
  src/sass/misc/_landing.scss
Labels: approved, cla: yes, lgtm

#3930 Improve 1.1 release notes
  content/boilerplates/notes/1.1.md
  content/docs/reference/config/installation-options-changes/index.md
  content/docs/reference/config/installation-options/index.md
  content/docs/setup/kubernetes/upgrade/notice/index.md
Labels: approved, cla: yes, lgtm

#3925 Fix html rendering issue for mesh expansion
  content/docs/setup/kubernetes/additional-setup/mesh-expansion/index.md
Labels: approved, cla: yes, lgtm

#3923 add 'change Istio to the blocking-egress-by-default policy'
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-mongo/index.md
  content/blog/2018/egress-tcp/index.md
Labels: approved, cla: yes, lgtm

#3935 Small release note fixes
  content/about/notes/1.1.1/index.md
  content/docs/reference/config/installation-options-changes/index.md
Labels: approved, cla: yes, lgtm

#3866 Add a FAQ help page for MySQL issue about PERMISSIVE mode.
  content/help/faq/security/mysql-with-mtls.md
Labels: approved, cla: yes, lgtm

#3886 Add a demo of Istio mTLS with Vault CA integration
  content/docs/tasks/security/vault-ca/index.md
Labels: approved, cla: yes, lgtm

#3941 Add another test file.
  test/command_example_atat.txt
Labels: approved, cla: yes

#3942 Site improvements
  content/test/tb/index.md
  generated/js/all.min.js
  generated/js/all.min.js.map
  layouts/partials/code_block.html
  src/ts/codeBlocks.ts
Labels: approved, cla: yes

#3952 zh: /boilerplates/notes/0.4.md
  content_zh/about/notes/older/0.4/index.md
  content_zh/boilerplates/notes/0.4.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3950 zh: /boilerplates/notes/0.3.md
  content_zh/about/notes/older/0.3/index.md
  content_zh/boilerplates/notes/0.3.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3947 zh: /boilerplates/notes/0.1.md
  content_zh/about/notes/older/0.1/index.md
  content_zh/boilerplates/notes/0.1.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3953 zh: /boilerplates/notes/0.5.md
  content_zh/about/notes/older/0.5/index.md
  content_zh/boilerplates/notes/0.5.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3956 zh: boilerplates & notes 0.6-1.1
  content_zh/about/notes/1.0.1/index.md
  content_zh/about/notes/1.0.2/index.md
  content_zh/about/notes/1.0.3/index.md
  content_zh/about/notes/1.0.4/index.md
  content_zh/about/notes/1.0.5/index.md
  content_zh/about/notes/1.0.6/index.md
  content_zh/about/notes/1.0.7/index.md
  content_zh/about/notes/1.0/index.md
  content_zh/about/notes/1.1/index.md
  content_zh/about/notes/older/0.6/index.md
  content_zh/about/notes/older/0.7/index.md
  content_zh/about/notes/older/0.8/index.md
  content_zh/boilerplates/notes/0.6.md
  content_zh/boilerplates/notes/0.7.md
  content_zh/boilerplates/notes/0.8.md
  content_zh/boilerplates/notes/1.0.1.md
  content_zh/boilerplates/notes/1.0.2.md
  content_zh/boilerplates/notes/1.0.3.md
  content_zh/boilerplates/notes/1.0.4.md
  content_zh/boilerplates/notes/1.0.5.md
  content_zh/boilerplates/notes/1.0.6.md
  content_zh/boilerplates/notes/1.0.7.md
  content_zh/boilerplates/notes/1.0.md
  content_zh/boilerplates/notes/1.1.1.md
  content_zh/boilerplates/notes/1.1.2.md
  content_zh/boilerplates/notes/1.1.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3954 updating reference docs for destination-rule.
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
Labels: cla: yes, needs-ok-to-test

#3920 zh: /docs/examples/advanced-gateways/egress-gateway-tls-origination/i…
  content_zh/docs/examples/advanced-gateways/egress-gateway-mtls-origination/index.md
  content_zh/docs/examples/advanced-gateways/egress-gateway-tls-origination/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3948 zh: /boilerplates/notes/0.2.md
  content_zh/about/notes/older/0.2/index.md
  content_zh/boilerplates/notes/0.2.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3934 zh: /docs/examples/advanced-gateways/egress_sni_monitoring_and_polici…
  content_zh/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3936 zh: /blog/2019/data-plane-setup/index.md
  content_zh/blog/2019/data-plane-setup/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3915 zh: /blog/2019/multicluster-version-routing/index.md
  content_zh/blog/2019/multicluster-version-routing/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3959 Move gcloud command to a separate section
  content/docs/setup/kubernetes/install/multicluster/gateways/index.md
Labels: approved, cla: yes, lgtm

#3964 Update Envoy restart time for cert rotation
  content/help/ops/traffic-management/troubleshooting/index.md
Labels: cla: yes, lgtm

#3968 Fix handling of embedded HTML in bash command output.
  generated/js/all.min.js
  generated/js/all.min.js.map
  src/ts/codeBlocks.ts
Labels: approved, cla: yes, lgtm

#3971 Update reference docs.
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/config/networking/v1alpha3/destination-rule/index.html
  content/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking/index.html
  scripts/grab_reference_docs.sh
Labels: approved, cla: yes

#3973 Improved egress task
  content/boilerplates/before-you-begin-egress.md
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3974 Add pod security policy to SDS task.
  content/docs/tasks/security/auth-sds/index.md
Labels: approved, area/security, cla: yes, lgtm

#3976 Fix grammar and invalid links in Skywalking adapter page
  content/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking/index.html
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3970 Introduce Citadel generated metrics
  content/docs/tasks/telemetry/metrics/querying-metrics/index.md
Labels: cla: yes, lgtm

#3966 Update index.md
  content/docs/examples/bookinfo/index.md
Labels: approved, cla: yes, lgtm

#3977 Updatep get policy
  content/help/ops/setup/injection/index.md
Labels: approved, cla: yes, lgtm

#3978 Missing changes for review feedback from #3973
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3962 zh: servicemesher/istio-official-translation#758
  content_zh/blog/2018/egress-monitoring-access-control/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3960 zh: /blog/2019/announcing-1.1.2/index.md
  content_zh/about/notes/1.1.2/index.md
  content_zh/blog/2019/announcing-1.1.2/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3958 zh: /boilerplates/notes/1.1.1.md
  content_zh/boilerplates/notes/1.1.1.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3875 zh： /blog/2019/appswitch
  content_zh/blog/2019/appswitch/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3979 [WIP] Use port 80 in tls origination of egress blog post
  content/blog/2018/egress-https/index.md
Labels: approved, cla: yes, lgtm

#3981 fix Debugging Envoy and Pilot
  content/help/ops/traffic-management/proxy-cmd/index.md
Labels: approved, cla: yes, lgtm

#3984 Optimize user experiences by replacing a manual step with a command
  content/docs/tasks/security/vault-ca/index.md
Labels: approved, area/user experience, cla: yes, lgtm

#3906 remove --export flag of kubectl since it is deprecated
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3980 add ygrene to list of companies using Istio in Action
  content/about/community/customers/index.md
  content/about/community/customers/ygrene.jpeg
Labels: cla: yes, needs-ok-to-test

#3914 add NashTech company to customers section
  content/about/community/customers/index.md
  content/about/community/customers/nashtech.png
Labels: cla: yes

#3884 Fix sidecar.istio.io/inject usage in EFK example
  content/docs/tasks/telemetry/logs/fluentd/index.md
Labels: approved, cla: yes, lgtm

#3949 make enabling of liveness HTTP probe rewrite a separate subsection
  content/help/ops/setup/app-health-check/index.md
Labels: cla: yes, lgtm

#3951 Update CNI GKE setting
  content/docs/setup/kubernetes/additional-setup/cni/index.md
Labels: cla: yes

#3991 use install/kubernetes/helm/istio instead of $HOME/istio-fetch/istio in egress gateway deployment
  content/docs/examples/advanced-gateways/egress-gateway/index.md
Labels: approved, cla: yes, lgtm

#3994 Remove warning from egress boilerplate
  content/boilerplates/before-you-begin-egress.md
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#3997 fix: typo
  content/docs/tasks/security/authz-http/index.md
Labels: cla: yes, needs-ok-to-test

#3999 Update references to kubernetes versions.
  content/docs/setup/kubernetes/additional-setup/sidecar-injection/index.md
  content/docs/setup/kubernetes/install/multicluster/vpn/index.md
  content/docs/setup/kubernetes/prepare/platform-setup/azure/index.md
  content/docs/setup/kubernetes/upgrade/steps/index.md
  content/help/faq/general/what-deployment-environment.md
  content/help/ops/setup/injection/index.md
  content/help/ops/setup/validation/index.md
  content/help/ops/setup/webhook/index.md
Labels: approved, cla: yes, lgtm

#3975 Update mixer configs
  content/docs/concepts/policies-and-telemetry/index.md
  content/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies/index.md
  content/docs/tasks/policy-enforcement/denial-and-list/index.md
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
  content/docs/tasks/telemetry/logs/collecting-logs/index.md
  content/docs/tasks/telemetry/logs/fluentd/index.md
  content/docs/tasks/telemetry/metrics/collecting-metrics/index.md
  content/docs/tasks/telemetry/metrics/tcp-metrics/index.md
  content/help/ops/telemetry/missing-metrics/index.md
Labels: approved, cla-manual, cla: yes, lgtm

#4000 Clarify ingress vs internal rules
  content/docs/tasks/traffic-management/ingress/index.md
Labels: approved, cla: yes, lgtm

#4002 Simplify tab rendering.
  generated/css/all.css
  generated/css/all.css.map
  src/sass/misc/_tabset.scss
Labels: approved, cla: yes

#4004 Fix missing parens and other small typos.
  content/boilerplates/notes/1.1.3.md
Labels: approved, cla: yes

#4003 zh: 1.1.3 release
  content_zh/about/notes/1.1.3/index.md
  content_zh/blog/2019/announcing-1.1.3/index.md
  content_zh/boilerplates/notes/1.1.3.md
Labels: approved, cla: yes, lgtm, translation/chinese

#3905 zh:update /docs/examples/multicluster/split-horizon-eds/index.md
  content_zh/docs/examples/multicluster/split-horizon-eds/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#4006 Remove -it from kubectl logs statement
  content/help/ops/traffic-management/troubleshooting/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#3988 Update the Egress MongoDB blog post
  content/blog/2018/egress-mongo/index.md
Labels: approved, cla: yes, lgtm

#3986 Update locality lb docs
  content/help/ops/traffic-management/locality-load-balancing/index.md
Labels: approved, cla: yes, lgtm

#4009 add transitional CRD sample
  content/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: cla: yes

#4008 Improve visibility of selected tabs.
  generated/css/all.css
  generated/css/all.css.map
  src/sass/misc/_tabset.scss
Labels: approved, cla: yes

#4010 zh: docs/setup/kubernetes/upgrade/notice/index.md
  content_zh/docs/setup/kubernetes/upgrade/notice/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, translation/chinese

#4018 Simplify release tracking.
  README.md
  data/args.yml
  data/releases.yml
  data/versions.yml
  layouts/partials/header.html
  layouts/shortcodes/relnote.html
Labels: approved, cla: yes

#4019 Simplify release tracking.
  README.md
  data/args.yml
  data/releases.yml
  data/versions.yml
  layouts/partials/header.html
  layouts/shortcodes/relnote.html
Labels: approved, cla: yes

#4020 Point to istio/istio master.
  content/boilerplates/notes/0.8.md
  content/docs/setup/consul/install/index.md
  content_zh/boilerplates/notes/0.8.md
  content_zh/docs/setup/consul/install/index.md
  data/args.yml
Labels: approved, cla: yes

#4022 Fix broken Envoy links.
  content/boilerplates/notes/0.8.md
  content_zh/boilerplates/notes/0.8.md
Labels: approved, cla: yes

#4021 Adding a section on moving to production with cert-manager
  content/docs/examples/advanced-gateways/ingress-certmgr/index.md
Labels: approved, cla: yes, lgtm

#4025 Release notes for 1.1.4
  content/about/notes/1.1.4/index.md
  content/blog/2019/announcing-1.1.4/index.md
  content/boilerplates/notes/1.1.4.md
  data/args.yml
Labels: approved, cla: yes

#4026 Update the deployment document for Citadel replica
  content/docs/setup/kubernetes/upgrade/steps/index.md
Labels: approved, cla: yes, lgtm

#4027 add a note to address grafana issue
  content/boilerplates/notes/1.0.6.md
Labels: approved, cla: yes, lgtm

#4029 cherry pick add a note to address grafana issue
  content/boilerplates/notes/1.0.6.md
Labels: approved, cla: yes

#4031 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/networking/v1alpha3/sidecar/index.html
  content/docs/reference/config/networking/v1alpha3/virtual-service/index.html
Labels: approved, cla: yes

#4028 1.1.4 release notes.
  content/about/notes/1.1.4/index.md
  content/blog/2019/announcing-1.1.4/index.md
  content/boilerplates/notes/1.1.4.md
Labels: approved, cla: yes

#4032 correct lint link
  scripts/lint_site.sh
Labels: approved, cla: yes

#4034 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixc/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/node_agent/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
  content/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/docs/reference/config/networking/v1alpha3/gateway/index.html
  content/docs/reference/config/networking/v1alpha3/virtual-service/index.html
  content/docs/reference/config/policy-and-telemetry/templates/checknothing/index.html
  content/docs/reference/config/policy-and-telemetry/templates/reportnothing/index.html
Labels: approved, cla: yes

#4035 Update reference docs.
  content/docs/reference/commands/galley/index.html
  content/docs/reference/commands/istio_ca/index.html
  content/docs/reference/commands/istioctl/index.html
  content/docs/reference/commands/mixs/index.html
  content/docs/reference/commands/pilot-agent/index.html
  content/docs/reference/commands/pilot-discovery/index.html
  content/docs/reference/commands/sidecar-injector/index.html
Labels: approved, cla: yes

#4036 Add support to build archive.istio.io's landing page.
  data/args.yml
  layouts/_default/baseof.html
  layouts/home.html
  layouts/partials/footer.html
  layouts/partials/header.html
Labels: approved, cla: yes

#4037 zh: /blog/2019/announcing-1.1.1/index.md
  content_zh/blog/2019/announcing-1.1.1/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#4040 zh: /docs/concepts/performance-and-scalability/index.md
  content_zh/docs/concepts/performance-and-scalability/index.md
Labels: approved, cla: yes, lgtm, translation/chinese

#4043 Site improvements
  Makefile
  archive_config.toml
  layouts/robots.txt
  scripts/gen_archive_site.sh
Labels: approved, cla: yes

#4044 Support for building archive.istio.io
  Makefile
  archive_config.toml
  data/args.yml
  layouts/_default/baseof.html
  layouts/home.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/robots.txt
  scripts/gen_archive_site.sh
Labels: approved, cla: yes

#4045 Tune the archive_landing mode.
  README.md
  layouts/partials/footer.html
  layouts/partials/header.html
Labels: approved, cla: yes

#4046 Tune the archive_landing mode.
  README.md
  layouts/partials/footer.html
  layouts/partials/header.html
Labels: approved, cla: yes

#4042 add mysql to named service ports list
  content/docs/setup/kubernetes/prepare/requirements/index.md
Labels: cla: yes, lgtm

#4048 Site improvements
  content/blog/2018/egress-monitoring-access-control/index.md
  content/blog/2019/data-plane-setup/index.md
  content/docs/concepts/multicluster-deployments/index.md
  content/docs/concepts/performance-and-scalability/index.md
  content/docs/examples/multicluster/split-horizon-eds/index.md
  content_zh/blog/2017/0.1-auth/index.md
  content_zh/blog/2018/egress-https/index.md
  content_zh/blog/2018/egress-monitoring-access-control/index.md
  content_zh/blog/2018/egress-tcp/index.md
  content_zh/blog/2018/export-logs-through-stackdriver/index.md
  content_zh/blog/2018/v1alpha3-routing/index.md
  content_zh/blog/2019/data-plane-setup/index.md
  content_zh/docs/concepts/multicluster-deployments/index.md
  content_zh/docs/concepts/policies-and-telemetry/index.md
  content_zh/docs/concepts/security/index.md
  content_zh/docs/concepts/traffic-management/index.md
  content_zh/docs/concepts/what-is-istio/index.md
  content_zh/docs/examples/bookinfo/index.md
  content_zh/docs/examples/integrating-vms/index.md
  content_zh/docs/examples/multicluster/split-horizon-eds/index.md
  content_zh/docs/setup/kubernetes/install/multicluster/gateways/index.md
  content_zh/docs/setup/kubernetes/install/multicluster/vpn/index.md
  content_zh/docs/setup/kubernetes/install/platform/alicloud/index.md
  content_zh/docs/setup/kubernetes/install/platform/gke/index.md
  content_zh/docs/setup/kubernetes/install/platform/ibm/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/alicloud/index.md
  content_zh/docs/setup/kubernetes/prepare/platform-setup/docker/index.md
  content_zh/docs/tasks/telemetry/distributed-tracing/lightstep/index.md
  content_zh/docs/tasks/telemetry/kiali/index.md
  content_zh/docs/tasks/telemetry/metrics/querying-metrics/index.md
  content_zh/docs/tasks/telemetry/metrics/using-istio-dashboard/index.md
  content_zh/help/ops/controlz/index.md
  layouts/shortcodes/gloss.html
  layouts/shortcodes/image.html
Labels: approved, cla: yes

#4049 Site improvements
  layouts/_default/faq.html
  layouts/partials/toc.html
Labels: approved, cla: yes

#4050 Site improvements
  generated/js/all.min.js
  generated/js/all.min.js.map
  src/ts/codeBlocks.ts
  src/ts/links.ts
  src/ts/scroll.ts
  src/ts/sidebar.ts
  src/ts/tabset.ts
Labels: approved, cla: yes

#4051 Site improvements
  generated/js/all.min.js
  generated/js/all.min.js.map
  layouts/_default/faq.html
  layouts/partials/toc.html
  src/ts/codeBlocks.ts
  src/ts/links.ts
  src/ts/scroll.ts
  src/ts/sidebar.ts
  src/ts/tabset.ts
Labels: approved, cla: yes

#4033 Fix user guide of Istio authorization for groups and list claims
  content/docs/tasks/security/rbac-groups/index.md
Labels: approved, area/security, cla: yes, lgtm

#4052 Fix check for ALLOW_ANY mode
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#4053 Cherry-pick: Fix check for ALLOW_ANY mode
  content/docs/tasks/traffic-management/egress/index.md
Labels: approved, cla: yes, lgtm

#4057 Reverse the polarity of anachronisms
  README.md
Labels: cla: yes

#4059 Fix typo.
  README.md
Labels: approved, cla: yes

#4030 #13575, second workaround
  content/help/ops/misc/index.md
Labels: cla: no

#4063 Update dates of egress blog posts
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-mongo/index.md
  content/blog/2018/egress-monitoring-access-control/index.md
  content/blog/2018/egress-tcp/index.md
Labels: cla: yes

#4071 Merge #4063 into master
  content/blog/2018/egress-https/index.md
  content/blog/2018/egress-mongo/index.md
  content/blog/2018/egress-monitoring-access-control/index.md
  content/blog/2018/egress-tcp/index.md
Labels: cla: yes

#4069 Fix the user guide of Istio Vault CA integration [master branch]
  content/docs/tasks/security/vault-ca/index.md
Labels: approved, cla: yes, lgtm

#4066 Fix the user guide of Istio Vault CA integration
  content/docs/tasks/security/vault-ca/index.md
Labels: cla: yes

#4075 Fix egress task explaination
  content/docs/examples/advanced-gateways/egress-tls-origination/index.md
Labels: cla: no

#4076 Fix egress task explanation
  content/docs/examples/advanced-gateways/egress-tls-origination/index.md
Labels: cla: no

#4073 set environment variables for cluster contexts automatically
  content/boilerplates/kubectl-multicluster-contexts.md
Labels: cla: yes

#4070 zh: /help/ops/setup/validation/index.md
  content_zh/help/ops/setup/validation/index.md
Labels: cla: yes, lgtm, translation/chinese

#4079 Add aliases to fix broken links in GKE docs.
  content/docs/concepts/security/index.md
  content/docs/concepts/traffic-management/index.md
  content/docs/examples/bookinfo/index.md
  content/docs/setup/kubernetes/_index.md
Labels: cla: yes
