Repository istio/istio.io, pull requests merged in 2020-02, with the labels that each got.

#6388 Fix 1.5 release date
  content/en/events/stickers/1.5.md
Labels: cla: yes, size/XS

#6385 Automator: update istio.io@master reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/layer5/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: cla: yes, size/XXL

#6368 update documentation for TCP traffic shifting: use a dedicated namesp…
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: cla: yes, ok-to-test, size/S

#6392 [release-1.4] Fix 1.5 release date
  content/en/events/stickers/1.5.md
Labels: cla: yes, size/XS

#6395 Istio 1.3.7 release announcement
  content/en/news/releases/1.3.x/announcing-1.3.7/index.md
Labels: area/test and release, cherrypick/release-1.4, cla: yes, size/S

#6397 [release 1.4] Manual cherry pick pick of #6379
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/news/releases/0.x/announcing-0.1/index.md
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/zh/news/2017/announcing-0.1/index.md
Labels: cla: yes, size/S

#6396 [release-1.4] Istio 1.3.7 release announcement
  content/en/news/releases/1.3.x/announcing-1.3.7/index.md
Labels: cla: yes, size/S

#6363 Define and link SDS on first mention
  content/en/docs/setup/platform-setup/gke/index.md
  content/en/docs/setup/platform-setup/minikube/index.md
Labels: cla: yes, kind/docs, size/XS

#6400 zh-translation: /docs/tasks/policy-enforcement/enabling-policy/index.md
  content/zh/docs/tasks/policy-enforcement/enabling-policy/index.md
Labels: cla: yes, size/XS, translation/chinese

#6399 zh-translation: /docs/tasks/traffic-management/egress/egress-kubernet…
  content/zh/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: cla: yes, size/XS, translation/chinese

#6402 [release-1.4] Update Solo.io logo
  content/en/about/community/partners/index.md
  content/en/about/community/partners/solo.png
  content/en/about/community/partners/solo.webp
Labels: cla: yes, size/XS

#6401 zh-update: /docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
Labels: cla: yes, size/M, translation/chinese

#6377 Updated cert-manager version
  content/en/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6389 finish off adding layer5 adapter
  content/en/docs/reference/config/policy-and-telemetry/adapters/layer5/index.html
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6391 add kubesphere to istio community partner
  content/en/about/community/partners/index.md
  content/en/about/community/partners/kubesphere.svg
Labels: cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/M

#6358 Rewrite contribution guides to empower reviewers
  .spelling
  content/en/about/contribute/_index.md
  content/en/about/contribute/add-content/index.md
  content/en/about/contribute/build/index.md
  content/en/about/contribute/code-blocks/index.md
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/about/contribute/diagrams/index.md
  content/en/about/contribute/formatting/index.md
  content/en/about/contribute/front-matter/index.md
  content/en/about/contribute/github/index.md
  content/en/about/contribute/review/index.md
  content/en/about/contribute/review/review-process.svg
  content/en/about/contribute/shortcodes/index.md
  content/en/about/contribute/style-guide/index.md
  content/en/about/contribute/terminology/index.md
  content/en/blog/2019/sail-the-blog/index.md
Labels: area/user experience, cla: yes, kind/docs, kind/enhancement, size/XXL

#5819 Make CoreDNS docs for Multi Cluster more precise
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: yes, kind/docs, size/M

#6405 zh-translation: /docs/examples/microservices-istio/setup-local-computer/in…
  content/zh/docs/examples/microservices-istio/setup-local-computer/index.md
Labels: cla: yes, size/S, translation/chinese

#6404 zh-update:/docs/tasks/security/authorization/authz-http/index.md
  content/zh/docs/tasks/security/authorization/authz-http/index.md
Labels: cla: yes, size/XS, translation/chinese

#6406 zh-update: /about/community/partners/index.md
  content/zh/about/community/partners/index.md
Labels: cla: yes, size/XS, translation/chinese

#6410 zh-translation: /events/stickers/1.5.md #1755
  content/zh/events/stickers/1.5.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6414 zh-update: /docs/tasks/security/authorization/authz-tcp/index.md
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
Labels: cla: yes, size/XS, translation/chinese

#6394 Automator: update istio.io@master reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/opa/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/prometheus/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/statsd/index.html
  data/analysis.yaml
Labels: cla: yes, size/M

#6398 Add option for Chinese
  layouts/index.redir
  layouts/partials/header.html
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6383 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/scripts/lint_go.sh
Labels: cla: yes, size/S

#6393 Update grab reference docs scripts
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  scripts/grab_reference_docs.sh
  static/operator-profile-default.yaml
  static/operator-profile-demo.yaml
  static/operator-profile-minimal.yaml
  static/operator-profile-sds.yaml
  static/operator.yaml
Labels: cla: yes, kind/docs, size/XL

#6408 zh-translation: setup-kubernetes-cluster/index.md #1761
  content/zh/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6412 zh-translation: app-health-check/index.md #1752
  content/zh/docs/ops/configuration/mesh/app-health-check/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6413 zh-translation: protocol-selection/index.md #1753
  content/zh/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6409 zh-translation: /docs/ops/configuration/mesh/validation/index.md #1765
  content/zh/docs/ops/configuration/mesh/validation/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6422 Fix CHANGLOG-* locations being updated in Kubernetes.
  content/en/blog/2019/trustworthy-jwt-sds/index.md
  content/en/news/releases/0.x/announcing-0.5/index.md
  content/en/news/releases/1.3.x/announcing-1.3/upgrade-notes/index.md
  content/pt-br/blog/2019/trustworthy-jwt-sds/index.md
  content/pt-br/news/releases/0.x/announcing-0.5/index.md
  content/pt-br/news/releases/1.3.x/announcing-1.3/upgrade-notes/index.md
  content/zh/news/releases/0.x/announcing-0.5/index.md
  content/zh/news/releases/1.3.x/announcing-1.3/upgrade-notes/index.md
Labels: cherrypick/release-1.4, cla: yes, size/S

#6418 Add documentation for IST0119 JWT analyzer
  content/en/docs/reference/config/analysis/ist0119/index.md
Labels: cla: yes, kind/docs, size/M

#6407 zh-translation: /docs/reference/config/security/conditions/index.md#1760
  content/zh/docs/reference/config/security/conditions/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6427 zh-translation: update ServiceMesher#1744-1745
  content/zh/docs/reference/config/installation-options/index.md
  content/zh/docs/tasks/security/webhook/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6423 zh-update:/docs/setup/install/multicluster/shared-gateways/index.md
  content/zh/docs/setup/install/multicluster/shared-gateways/index.md
Labels: cla: yes, size/XS, translation/chinese

#6431 zh-translation:/news/support/announcing-1.2-eol/index.md
  content/zh/news/support/announcing-1.2-eol/index.md
Labels: cla: yes, size/S, translation/chinese

#6429 zh-update: /docs/setup/getting-started/index.md
  content/zh/docs/setup/getting-started/index.md
Labels: cla: yes, size/S, translation/chinese

#6432 zh-update:/news/releases/1.4.x/announcing-1.4.3/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.3/index.md
Labels: cla: yes, size/M, translation/chinese

#6411 zh-translation: /docs/ops/common-problems/validation/index.md #1756
  content/zh/docs/ops/common-problems/validation/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6420 zh-translation: update for ServiceMesher#1746-1748
  content/zh/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6426 zh-translation: istioctl-analyze/index.md #1743
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6430 zh-update: /news/support/announcing-1.3-eol/index.md
  content/zh/news/support/announcing-1.3-eol/index.md
Labels: cla: yes, size/S, translation/chinese

#6425 Standealone Operator is beta in 1.5.
  content/en/about/feature-stages/index.md
Labels: area/environments, cla: yes, size/XS

#6434 add istioctl ps
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: cla: yes, ok-to-test, size/XS

#6416 Add option to setup Istio on KIND
  content/en/docs/setup/platform-setup/ibm/index.md
  content/en/docs/setup/platform-setup/kind/index.md
Labels: area/environments, area/user experience, cla: yes, kind/docs, ok-to-test, size/L

#6437 Update delete step
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
Labels: cla: yes, ok-to-test, size/XS

#6386 toss in action
  content/en/about/community/customers/index.md
  content/en/about/community/customers/toss.svg
Labels: cla: yes, kind/docs, ok-to-test, size/S

#6441 zh-translation: ServiceMesher#1735 and others
  content/zh/about/contribute/add-content/index.md
  content/zh/about/contribute/creating-and-editing-pages/index.md
  content/zh/about/contribute/github/index.md
  content/zh/about/contribute/review/index.md
  content/zh/about/contribute/review/review-process.svg
  content/zh/blog/2019/sail-the-blog/index.md
  content/zh/blog/2020/_index.md
  content/zh/docs/reference/glossary/adapters.md
  content/zh/docs/reference/glossary/destination.md
Labels: cla: yes, kind/docs, ok-to-test, size/XXL, translation/chinese

#6444 ISTIO Security 2020 001
  .spelling
  content/en/news/releases/1.3.x/announcing-1.3.8/index.md
  content/en/news/releases/1.4.x/announcing-1.4.4/index.md
  content/en/news/security/istio-security-2020-001/index.md
Labels: area/security, area/test and release, cherrypick/release-1.4, cla: yes, kind/docs, size/M

#6446 fix cut/paste error
  content/en/news/security/istio-security-2020-001/index.md
Labels: area/security, cla: yes, kind/docs, size/XS

#6436 [release 1.4] Manual cherry pick of #6422 - Fix CHANGLOG-* locations being updated in Kubernetes.
  content/en/blog/2019/trustworthy-jwt-sds/index.md
  content/en/news/releases/0.x/announcing-0.5/index.md
  content/en/news/releases/1.3.x/announcing-1.3/upgrade-notes/index.md
  content/zh/blog/2019/trustworthy-jwt-sds/index.md
  content/zh/news/2018/announcing-0.5/index.md
  content/zh/news/2019/announcing-1.3/upgrade-notes/index.md
Labels: cla: yes, size/S

#6448 Manual cherrypick 6444
  .spelling
  content/en/news/releases/1.3.x/announcing-1.3.8/index.md
  content/en/news/releases/1.4.x/announcing-1.4.4/index.md
  content/en/news/security/istio-security-2020-001/index.md
  data/args.yml
Labels: cla: yes, size/M

#6372 Add tutorial modules for enabling Istio, mTLS, versioning, gateway, logging
  .spelling
  content/en/docs/examples/microservices-istio/add-istio/dashboard-mesh.png
  content/en/docs/examples/microservices-istio/add-istio/dashboard-select-dashboard.png
  content/en/docs/examples/microservices-istio/add-istio/dashboard-service-select-productpage.png
  content/en/docs/examples/microservices-istio/add-istio/dashboard-service.png
  content/en/docs/examples/microservices-istio/add-istio/index.md
  content/en/docs/examples/microservices-istio/add-mtls/dashboard-ratings-mtls.png
  content/en/docs/examples/microservices-istio/add-mtls/index.md
  content/en/docs/examples/microservices-istio/add-mtls/kiali-mtls.png
  content/en/docs/examples/microservices-istio/add-new-microservice-version/bookinfo-reviews-v2.png
  content/en/docs/examples/microservices-istio/add-new-microservice-version/index.md
  content/en/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/dashboard-mesh-all.png
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/dashboard-ratings.png
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/kiali-display-menu.png
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/kiali-edge-labels-menu.png
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/kiali-initial.png
  content/en/docs/examples/microservices-istio/istio-ingress-gateway/index.md
  content/en/docs/examples/microservices-istio/istio-ingress-gateway/kiali-ingress-gateway-only.png
  content/en/docs/examples/microservices-istio/istio-ingress-gateway/kiali-ingress-gateway.png
  content/en/docs/examples/microservices-istio/logs-istio/index.md
  content/en/docs/examples/microservices-istio/logs-istio/prometheus.png
  content/en/docs/examples/microservices-istio/prereq/index.md
  content/en/docs/examples/microservices-istio/production-testing/index.md
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/tasks/observability/logs/access-log/index.md
Labels: cla: yes, kind/docs, size/XL

#6449 Issue security update and update 1.3.7 release notes
  .spelling
  content/en/news/releases/1.3.x/announcing-1.3.7/index.md
  content/en/news/security/istio-security-2020-002/index.md
Labels: area/policies and telemetry, area/security, cherrypick/release-1.4, cla: yes, size/M

#6417 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#6455 Update index.md
  content/en/news/security/istio-security-2020-001/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6452 [release-1.4] Issue security update and update 1.3.7 release notes
  .spelling
  content/en/news/releases/1.3.x/announcing-1.3.7/index.md
  content/en/news/security/istio-security-2020-002/index.md
Labels: cla: yes, size/M

#6454 Update index.md
  content/en/news/security/istio-security-2020-002/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6460 Revert "Standealone Operator is beta in 1.5. (#6425)"
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/XS

#6433 zh-update: /faq/applications/redis.md
  content/zh/faq/applications/redis.md
Labels: cla: yes, size/S, translation/chinese

#6471 Replace 3.5.6 ZooKeeper links with 3.5.7
  content/en/faq/applications/zookeeper.md
  content/pt-br/faq/applications/zookeeper.md
  content/zh/faq/applications/zookeeper.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6475 [release 1.4] Cherry pick of #6471 - Bad Zookeeper links
  content/en/faq/applications/zookeeper.md
Labels: cla: yes, size/XS

#6465 Update security concepts index.md
  content/en/docs/concepts/security/index.md
Labels: cla: yes, kind/docs, size/XS

#6476 1.3 EOL Final
  content/en/news/support/announcing-1.3-eol-final/index.md
Labels: cla: yes, size/S

#6451 Copy istio.io tests to istio.io repo
  Makefile.core.mk
  go.mod
  go.sum
  prow/integ-suite-kind.sh
  prow/lib.sh
  prow/upload-istioio-snippets.sh
  tests/README.md
  tests/configuration/health_check_test.go
  tests/configuration/main_test.go
  tests/configuration/scripts/cleanup.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_command.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_annotations.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_globally.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_separate_port.txt
  tests/examples/bookinfo_test.go
  tests/examples/main_test.go
  tests/examples/scripts/bookinfo.txt
  tests/security/authz_http_test.go
  tests/security/main_test.go
  tests/security/mtls_migration_test.go
  tests/security/scripts/authz_http.txt
  tests/security/scripts/mtls_migration.txt
  tests/tests.mk
  tests/trafficmanagement/ingress/main_test.go
  tests/trafficmanagement/ingress/scripts/cleanup.txt
  tests/trafficmanagement/ingress/scripts/configure_mtls_ingress.txt
  tests/trafficmanagement/ingress/scripts/configure_tls_ingress_multiple_hosts.txt
  tests/trafficmanagement/ingress/scripts/configure_tls_ingress_single_host.txt
  tests/trafficmanagement/ingress/scripts/generate_certs_and_keys.txt
  tests/trafficmanagement/ingress/scripts/troubleshooting.txt
  tests/trafficmanagement/ingress/secure_ingress_sds_test.go
  tests/trafficmanagement/main_test.go
  tests/trafficmanagement/mirror_test.go
  tests/trafficmanagement/scripts/mirror_deploy.txt
  tests/trafficmanagement/scripts/mirror_traffic.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_cleanup.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_setup.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_test.txt
  tests/trafficmanagement/scripts/traffic_shifting.txt
  tests/trafficmanagement/tcp_trafficshifting_test.go
  tests/trafficmanagement/traffic_shifting_test.go
Labels: cla: yes, size/XXL

#6435 zh-translation: update ServiceMesher#1740-1742
  content/zh/docs/concepts/security/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
  content/zh/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6478 zh-translation: update for ServiceMesher#1778-1785
  content/zh/about/feature-stages/index.md
  content/zh/blog/2019/trustworthy-jwt-sds/index.md
  content/zh/docs/setup/install/multicluster/gateways/index.md
  content/zh/docs/setup/install/multicluster/shared-gateways/index.md
  content/zh/docs/setup/platform-setup/ibm/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6477 zh-translation: update for ServiceMesher#1786-1791
  content/zh/about/contribute/diagrams/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
  content/zh/docs/setup/platform-setup/gke/index.md
  content/zh/docs/setup/platform-setup/minikube/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6464 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#6424 add kubesphere to platform-setup solutions
  .spelling
  content/en/docs/setup/platform-setup/gardener/index.md
  content/en/docs/setup/platform-setup/kubesphere/images/kubesphere-console.png
  content/en/docs/setup/platform-setup/kubesphere/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#6481 zh-translation: /docs/setup/platform-setup/kind/index.md
  content/zh/docs/setup/platform-setup/kind/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6473 Update docs for installing the operator
  content/en/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, size/L

#6483 zh-translation: /docs/reference/config/analysis/ist0119/index.md
  content/zh/docs/reference/config/analysis/ist0119/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6463 Correct typo
  content/en/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
  content/pt-br/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
  content/zh/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
Labels: cla: yes, size/XS

#6488 Point to 1.5 branch of Istio
  content/en/about/contribute/code-blocks/index.md
  content/pt-br/about/contribute/creating-and-editing-pages/index.md
  data/args.yml
Labels: cla: yes, size/S

#6466 1.4.5 release notes
  content/en/news/releases/1.4.x/announcing-1.4.5/index.md
Labels: cla: yes, size/S

#6491 1.4.5 release notes on 1.4 branch
  content/en/news/releases/1.4.x/announcing-1.4.5/index.md
  data/args.yml
Labels: cla: yes, size/S

#6467 remove references to experimental simplified multicluster setup scripts
  content/en/docs/examples/bookinfo-multicluster/index.md
  content/en/docs/setup/install/multicluster/simplified/index.md
  content/pt-br/docs/examples/bookinfo-multicluster/index.md
  content/pt-br/docs/setup/install/multicluster/simplified/index.md
Labels: cla: yes, size/L

#6468 remove deprecated platform specific examples
  content/en/docs/examples/platform/_index.md
  content/en/docs/examples/platform/endpoints/index.md
  content/en/docs/examples/platform/gke/index.md
  content/en/docs/examples/platform/icp/index.md
  content/pt-br/docs/examples/platform/_index.md
  content/pt-br/docs/examples/platform/endpoints/index.md
  content/pt-br/docs/examples/platform/gke/index.md
  content/pt-br/docs/examples/platform/icp/index.md
Labels: cla: yes, size/XXL

#6494 [release-1.4] Replace @geeknoid with infrastructure
  CODEOWNERS
Labels: cla: yes, size/XS

#6438 Add documentation for IST0119 JWT analyzer (#6418)
  content/en/docs/reference/config/analysis/ist0119/index.md
  data/analysis.yaml
Labels: cla: yes, kind/docs, size/M

#6484 Bump supported versions
  data/args.yml
Labels: cla: yes, size/XS

#6493 Doc fix [Standalone Operator Install]
  content/en/docs/setup/install/standalone-operator/index.md
  content/pt-br/docs/setup/install/standalone-operator/index.md
  content/zh/docs/setup/install/standalone-operator/index.md
Labels: area/test and release, cla: yes, kind/docs, size/S

#6490 Updated docker desktop image to reflect correct requirements
  content/en/docs/setup/platform-setup/docker/dockerprefs.png
  content/pt-br/docs/setup/platform-setup/docker/dockerprefs.png
  content/zh/docs/setup/platform-setup/docker/dockerprefs.png
Labels: area/config, cla: yes, kind/docs, ok-to-test, size/XS

#6510 Fix spelling
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: cla: yes, size/XS

#6461 [release-1.4] Set Kiali username and password on separate prompt
  content/en/docs/tasks/observability/kiali/index.md
Labels: cla: no, size/XS

#6489 Fix istio.io integration tests
  Makefile.core.mk
  bin/init.sh
  go.mod
  go.sum
  prow/config/trustworthy-jwt.yaml
  prow/integ-suite-kind.sh
  prow/lib.sh
  tests/tests.mk
  tests/trafficmanagement/ingress/main_test.go
Labels: cla: yes, size/L

#6521 Copy istio.io test framework from istio/istio
  pkg/test/istioio/builder.go
  pkg/test/istioio/context.go
  pkg/test/istioio/func.go
  pkg/test/istioio/input.go
  pkg/test/istioio/pod.go
  pkg/test/istioio/script.go
  pkg/test/istioio/snippet.go
  pkg/test/istioio/subtest.go
  pkg/test/istioio/verifier.go
  pkg/test/istioio/yaml.go
  tests/README.md
  tests/configuration/health_check_test.go
  tests/examples/bookinfo_test.go
  tests/security/authz_http_test.go
  tests/security/mtls_migration_test.go
  tests/trafficmanagement/ingress/secure_ingress_sds_test.go
  tests/trafficmanagement/mirror_test.go
  tests/trafficmanagement/tcp_trafficshifting_test.go
  tests/trafficmanagement/traffic_shifting_test.go
Labels: cla: yes, size/XXL

#6523 Set codeowners for istio.io tests
  CODEOWNERS
Labels: cla: yes, size/XS

#6524 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#6520 Update services/pods
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/M

#6504 update istioctl installation guide based on new API
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/upgrade/istioctl-upgrade/index.md
Labels: cla: yes, size/L

#6514 Update istioctl upgrade docs
  content/en/docs/setup/upgrade/istioctl-upgrade/index.md
Labels: cla: yes, kind/docs, size/M

#6517 Blog for removing cross-pod unix domain sockets
  content/en/blog/2020/istio-agent/index.md
  content/en/blog/2020/istio-agent/istio_agent.svg
Labels: cla: yes, size/XXL

#6486 Update reference docs
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/analysis/ist0105/index.md
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/pt-br/docs/reference/config/analysis/ist0105/index.md
  content/zh/docs/reference/config/analysis/ist0105/index.md
  data/analysis.yaml
Labels: cla: yes, kind/docs, size/XL

#6525 Update to use new IBM CLI commands
  content/en/docs/setup/platform-setup/ibm/index.md
Labels: cla: yes, size/XS

#6518 Update the SDS documentation on Node Agent for Istio 1.5
  content/en/docs/tasks/security/citadel-config/auth-sds/index.md
Labels: area/security, cla: yes, kind/docs, size/L

#6190 rewrite Secure Gateways (SDS) to use openssl for generating certs/keys
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: cla: yes, size/L

#6531 Add tip to download specific Istio version
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/XS

#6457 [release-1.4] Update index.md
  content/en/news/security/istio-security-2020-002/index.md
Labels: cla: no, size/XS

#6456 [release-1.4] Update index.md
  content/en/news/security/istio-security-2020-001/index.md
Labels: cla: no, size/XS

#6515 Remove webhook task from Istio 1.5 documentation
  content/en/blog/2019/webhook/index.md
  content/en/docs/tasks/security/webhook/index.md
  scripts/lint_site.sh
Labels: area/security, cla: yes, kind/docs, size/L

#6534 zh-update: /about/community/customers/index.md
  content/zh/about/community/customers/index.md
Labels: cla: yes, size/XS, translation/chinese

#6535 Change how stickers should be used
  .spelling
  content/en/about/contribute/shortcodes/index.md
  content/en/events/stickers/1.5.md
Labels: cla: yes, size/S

#6529 update operator api version and fix
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
  content/en/docs/tasks/security/dns-cert/index.md
  content/pt-br/docs/tasks/security/webhook/index.md
Labels: cla: yes, size/M

#6541 Update the document of DNS certificate management for Istio 1.5
  content/en/docs/tasks/security/dns-cert/index.md
Labels: area/security, cla: yes, kind/docs, size/XS

#6516 Update Node Agent to Istio Agent for Istio 1.5
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/security/node_agent.svg
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/faq/security/cert-lifetime-config.md
Labels: area/security, cla: yes, kind/docs, size/XXL

#6552 authz: add task for deny policy
  content/en/docs/tasks/security/authorization/_index.md
  content/en/docs/tasks/security/authorization/authz-deny/index.md
  content/en/docs/tasks/security/authorization/authz-http/index.md
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
Labels: area/security, cla: yes, size/L

#6543 (#6542) - add install, samples and out directories to .gitignore
  .gitignore
Labels: cla: yes, ok-to-test, size/XS

#6538 update some docs which still referring to standalone injector
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
Labels: cla: yes, size/S

#6546 Modernize authn tasks for 1.5 API and auto-mTLS by default
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/docs/tasks/security/authentication/mutual-tls/index.md
  content/en/faq/security/accessing-non-istio-services.md
Labels: area/security, cla: yes, kind/docs, size/XL

#6545 [release-1.4] Manual cherry-pick of #6535 (remove 1.5 sticker)
  .spelling
  content/en/about/contribute/creating-and-editing-pages/index.md
  content/en/events/stickers/1.5.md
Labels: cla: yes, size/M

#6548 Cleanup GKE platform setup
  content/en/docs/setup/platform-setup/gke/index.md
Labels: cla: yes, size/XS

#6556 Improve instructions on OpenShift
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, size/M

#6553 move DaoCloud to partners
  content/en/about/community/customers/index.md
  content/en/about/community/partners/daocloud.svg
  content/en/about/community/partners/index.md
Labels: cla: yes, size/XS

#6549 Remove unsupported SDS from helm
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/S

#6537 update release 1.5 performance and scalability page
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99.svg
Labels: cla: yes, size/XXL

#6550 Add note about JWT policies
  content/en/docs/ops/best-practices/security/index.md
Labels: cla: yes, size/M

#6598 Fixes and cleanup for running tests
  Makefile.core.mk
  bin/init.sh
  go.mod
  go.sum
  tests/README.md
Labels: cla: yes, size/S

#6599 Update circuit breaker task for 1.5
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: area/networking, cla: yes, size/L

#6526 Typo fixes for issue #6487
  content/en/docs/tasks/security/authorization/rbac-groups/index.md
Labels: cla: yes, kind/docs, size/XS

#6593 Remove examples that set global.mtls.enabled
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/installation-options/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: area/security, cla: yes, kind/docs, size/M

#6606 zh-translation: /news/releases/1.3.x/announcing-1.3.7/index.md #1776
  content/zh/news/releases/1.3.x/announcing-1.3.7/index.md
  content/zh/news/releases/1.3.x/announcing-1.3.8/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.4/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.5/index.md
  content/zh/news/security/istio-security-2020-001/index.md
  content/zh/news/security/istio-security-2020-002/index.md
  content/zh/news/support/announcing-1.3-eol-final/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6555 (#6544) cloned istio repository path should not have double quotes
  .gitignore
  Makefile.core.mk
Labels: area/test and release, cla: yes, kind/docs, ok-to-test, size/XS

#6528 Adding new flags to CNI docs
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/XS

#6596 Remove https overlay task
  content/en/docs/tasks/security/authentication/https-overlay/index.md
  content/en/faq/security/https-overlay.md
Labels: area/security, cla: yes, kind/docs, size/L

#6610 Remove warning about multiple replicas in citadel deployment
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6616 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#6533 fix(observability docs): restructure docs for v2 telemetry (and remove problematic Mixer refs)
  content/en/about/bugs/index.md
  content/en/about/feature-stages/index.md
  content/en/blog/2018/egress-monitoring-access-control/index.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/concepts/what-is-istio/index.md
  content/en/docs/examples/microservices-istio/logs-istio/index.md
  content/en/docs/ops/configuration/telemetry/in-proxy-service-telemetry/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/tasks/observability/logs/_index.md
  content/en/docs/tasks/observability/metrics/_index.md
  content/en/docs/tasks/observability/metrics/querying-metrics/index.md
  content/en/docs/tasks/observability/mixer/_index.md
  content/en/docs/tasks/observability/mixer/logs/_index.md
  content/en/docs/tasks/observability/mixer/logs/collecting-logs/index.md
  content/en/docs/tasks/observability/mixer/logs/fluentd/index.md
  content/en/docs/tasks/observability/mixer/metrics/_index.md
  content/en/docs/tasks/observability/mixer/metrics/collecting-metrics/index.md
  content/en/docs/tasks/observability/mixer/metrics/tcp-metrics/index.md
  content/en/docs/tasks/observability/mixer/metrics/tcp-metrics/istio-tcp-attribute-flow.svg
  content/en/news/releases/0.x/announcing-0.5/index.md
  content/en/news/releases/1.3.x/announcing-1.3.1/index.md
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: cla: yes, size/L

#6612 More fixes and cleanup for makefiles
  Makefile.core.mk
  bin/init.sh
  tests/tests.mk
Labels: cla: yes, size/M

#6620 sync new files to /about/contribute
  content/zh/about/contribute/build/index.md
  content/zh/about/contribute/code-blocks/index.md
  content/zh/about/contribute/formatting/index.md
  content/zh/about/contribute/front-matter/index.md
  content/zh/about/contribute/shortcodes/index.md
  content/zh/about/contribute/terminology/index.md
Labels: cla: yes, kind/docs, size/XXL, translation/chinese

#6589 Rewrite mtls migration instructions.
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
Labels: cla: yes, size/L

#6617 [release-1.4] Remove warning about multiple replicas in citadel deployment
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: cla: yes, size/XS

#6622 Add test for Enabling Policy Enforcement
  tests/policies/enabling_policy_enforcement_test.go
  tests/policies/main_test.go
  tests/policies/scripts/enabling_policy_enforcement.txt
  tests/policies/scripts/revert_policy_enforcement.txt
Labels: area/test and release, cla: yes, ok-to-test, size/L

#6623 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#6600 update operator ref doc
  content/en/blog/2019/introducing-istio-operator/index.md
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XXL

#6602 Update GKE platform setup
  content/en/docs/setup/platform-setup/gke/index.md
Labels: cla: yes, size/XS

#6637 Update docs and manifest for kubectl install of operator
  content/en/docs/setup/install/standalone-operator/index.md
  static/operator.yaml
Labels: cla: yes, size/S

#6603 Update Autocompletion to point to the full release page for tools directory.
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6470 remove the mixer policy concept page
  content/en/docs/concepts/policies/index.md
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/what-is-istio/index.md
  content/en/docs/tasks/policy-enforcement/control-headers/index.md
  content/en/docs/tasks/policy-enforcement/denial-and-list/index.md
  content/en/docs/tasks/policy-enforcement/enabling-policy/index.md
  content/en/docs/tasks/policy-enforcement/rate-limiting/index.md
Labels: area/policies and telemetry, area/security, cla: yes, size/M

#6646 CNI: Add a missing parameter to OpenShift
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/XS

#6643 Document the requirement for the NET_RAW capability
  content/en/docs/ops/common-problems/observability-issues/index.md
  content/en/docs/ops/deployment/requirements/index.md
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/M

#6627 Add ingress-gateway reachability to bookinfo test
  tests/examples/bookinfo_test.go
  tests/examples/scripts/bookinfo.txt
Labels: cla: yes, size/M

#6652 Fixed anchor links to point at glossary
  content/en/docs/reference/glossary/adapters.md
  content/en/docs/reference/glossary/data-plane.md
  content/en/docs/reference/glossary/destination.md
  content/en/docs/reference/glossary/envoy.md
  content/en/docs/reference/glossary/mixer-handler.md
  content/en/docs/reference/glossary/mixer-instance.md
  content/en/docs/reference/glossary/mixer.md
  content/en/docs/reference/glossary/pilot.md
  content/en/docs/reference/glossary/pod.md
  content/en/docs/reference/glossary/secure-naming.md
  content/en/docs/reference/glossary/service-consumer.md
  content/en/docs/reference/glossary/service-endpoint.md
  content/en/docs/reference/glossary/service-mesh.md
  content/en/docs/reference/glossary/service-name.md
  content/en/docs/reference/glossary/service-operator.md
  content/en/docs/reference/glossary/service-producer.md
  content/en/docs/reference/glossary/service-registry.md
  content/en/docs/reference/glossary/service-version.md
  content/en/docs/reference/glossary/service.md
  content/en/docs/reference/glossary/source.md
  content/en/docs/reference/glossary/workload-instance-principal.md
  content/en/docs/reference/glossary/workload-instance.md
  content/en/docs/reference/glossary/workload.md
Labels: cla: yes, kind/docs, size/M
