Repository istio/istio.io, pull requests merged in 2020-11, with the labels that each got.

#8422 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8424 add empty and preview profile to the table
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cherrypick/release-1.7, cla: yes, size/S

#8341 Adding support for experimental Custom CA integration using Kubernetes CSR API
  DOC_OWNERS.md
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cla: yes, size/L

#8425 [release-1.7] add empty and preview profile to the table
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, release-notes-none, size/S

#8421 Supported versions for 1.8 from TOC
  data/args.yml
Labels: cla: yes, size/XS

#8426 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8412 Add supported k8s versions to istio status
  content/en/about/supported-releases/index.md
Labels: cla: yes, kind/docs, size/S

#8385 Update istioctl installation docs
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/L

#8407 remove not generated files to avoid confusion
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/index.md
Labels: cla: yes, kind/docs, size/XS

#8427 [release-1.7] Add supported k8s versions to istio status
  content/en/about/supported-releases/index.md
Labels: cla: yes, release-notes-none, size/S

#8414 Cleanup pod requrements doc
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, size/M

#8433 Clarify minor doc
  content/en/docs/ops/best-practices/security/index.md
Labels: cla: yes, size/XS

#8436 Fix waiting for Kiali deployment to be ready
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/test.sh
Labels: cla: yes, size/S

#8437 Fix typo
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS

#8434 Add tip for vendor profiles
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, size/XS

#8438 Minor link fix
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, size/XS

#8390 update authz docs for remote.ip
  .spelling
  content/en/docs/reference/config/security/conditions/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
Labels: cla: yes, kind/docs, ok-to-test, size/XL

#8349 Add traffic requirements documentation
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, size/M

#8440 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8439 Remove deprecated stats field fields
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/snips.sh
Labels: cla: yes, size/M

#8442 Remove rbac instruction for GKE
  content/en/docs/setup/platform-setup/gke/index.md
Labels: area/environments, cla: yes, ok-to-test, size/S

#8444 Fix openshift docs
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, size/S

#8445 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8446 Update upgrade warning for minor version
  content/en/docs/setup/upgrade/_index.md
Labels: cla: yes, size/XS

#8432 Update operator upgrade docs
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/upgrade/gateways/index.md
Labels: cla: yes, size/M

#8337 Update the docs to add OpenShift install profile
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, ok-to-test, size/XS

#8450 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8451 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8452 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/type/workload-selector/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8443 Promote Helm installation to alpha
  content/en/docs/setup/install/helm/index.md
Labels: area/environments, cla: yes, kind/docs, size/S

#8403 add external istiod initial documentation
  DOC_OWNERS.md
  content/en/docs/setup/additional-setup/external-controlplane/external-controlplane.svg
  content/en/docs/setup/additional-setup/external-controlplane/index.md
Labels: cla: yes, kind/docs, size/L

#8420 update tls docs with minimum supported version and cipher suites
  content/en/docs/concepts/security/index.md
Labels: area/networking, cla: yes, size/S

#8428 Update ports usage doc
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, size/M

#8454 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8456 Fix profile warning in getting started doc
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/S

#8448 upgrade support --set flag
  content/en/docs/setup/upgrade/in-place/index.md
Labels: cla: yes, size/XS

#8447 Upgrade is not compatible with revisions
  content/en/docs/setup/upgrade/in-place/index.md
Labels: cla: yes, size/XS

#8246 Add health check using TCP socket
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
Labels: area/user experience, cherrypick/release-1.7, cla: yes, kind/docs, size/M

#8455 Install approach FAQ
  content/en/docs/setup/getting-started/index.md
  content/en/faq/setup/consul-app-not-working.md
  content/en/faq/setup/consul-unset-context.md
  content/en/faq/setup/install-method-selection.md
  content/en/faq/setup/k8s-migrating.md
Labels: cla: yes, size/M

#8465 [release-1.7] Add health check using TCP socket
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
Labels: cla: no, cla: yes, release-notes-none, size/M

#8457 cleanup eastwest gen
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
Labels: cla: yes, size/M

#8459 enh: enlarge search icon for better visibility
  layouts/partials/icon.html
  src/sass/misc/_header.scss
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#8467 Revert "cleanup eastwest gen"
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
Labels: cla: yes, size/M

#8461 Fix a peeve in the deployments document.
  content/en/docs/ops/deployment/deployment-models/index.md
Labels: cla: yes, size/XS

#8475 Add explicit hub/tag overrides for Helm commands
  content/en/docs/setup/install/helm/index.md
Labels: area/environments, cla: yes, kind/docs, size/S

#8478 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8476 enh: enlarge the cancel icon during search box
  src/sass/misc/_header.scss
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#8477 Move to an intermediate 1.8 build for testing
  go.mod
  go.sum
Labels: cla: yes, size/S

#8466 Document vendor profiles
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, size/XS

#8473 Another ref to install FAQ
  content/en/docs/setup/install/_index.md
Labels: cla: yes, size/XS

#8481 Update ICP to IOP
  content/en/docs/setup/upgrade/in-place/index.md
  content/en/docs/tasks/security/cert-management/dns-cert/index.md
Labels: cla: yes, size/XS

#8479 Update example to be a valid setting
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#8480 Update security doc for Istiod/SDS
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: cla: yes, size/L

#8471 external control plane doc updates
  content/en/docs/setup/additional-setup/external-controlplane/index.md
Labels: cla: yes, kind/docs, size/M

#8482 Add in removed tests (had regression failure) to verify fix
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
  content/en/docs/tasks/security/authorization/authz-td-migration/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/test.sh
Labels: cla: yes, size/M

#8483 No need to create ns up front
  content/en/docs/setup/upgrade/gateways/index.md
Labels: cla: yes, size/XS

#8472 Make proxy protocol EnvoyFilter consistent with Network Topology doc
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
Labels: cla: yes, kind/docs, ok-to-test, size/S

#8484 Update extension doc
  content/en/docs/concepts/wasm/index.md
Labels: cla: yes, size/S

#8489 adding a statement about alpha
  content/en/docs/setup/additional-setup/external-controlplane/index.md
Labels: cla: yes, kind/docs, size/XS

#8474 cleanup eastwest gen
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
Labels: cla: yes, size/M

#8487 Updates and clarifications in deployment models doc
  content/en/docs/ops/deployment/deployment-models/index.md
Labels: cla: yes, size/L

#8490 Small update on security concept page
  content/en/docs/concepts/security/index.md
Labels: cherrypick/release-1.8, cla: yes, size/S

#8495 Update istiod entry in glossary
  content/en/docs/reference/glossary/istiod.md
Labels: cla: yes, kind/docs, size/XS

#8491 Few fixes for ext control plane setup
  content/en/docs/setup/additional-setup/external-controlplane/index.md
Labels: cla: yes, size/S

#8418 use istioctl x workload in vm installation doc
  DOC_OWNERS.md
  content/en/docs/examples/virtual-machines/autoregistration/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/L

#8498 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8496 Analysis message for IST0116 and 117
  DOC_OWNERS.md
  content/en/docs/reference/config/analysis/ist0116/index.md
  content/en/docs/reference/config/analysis/ist0117/index.md
Labels: cla: yes, size/M

#8494 Update root transition operation page
  content/en/docs/ops/configuration/security/root-transition/index.md
Labels: area/security, cla: yes, size/L

#8500 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8501 Automator: update common-files@release-1.7 in istio/istio.io@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8504 Remove DOC_OWNERS.md
  DOC_OWNERS.md
  Makefile.core.mk
  scripts/doc_owners.sh
Labels: cla: yes, size/L

#8505 Automator: update common-files@release-1.6 in istio/istio.io@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#8499 Docs for codes analysis 122, 123, and 125
  content/en/docs/reference/config/analysis/ist0122/index.md
  content/en/docs/reference/config/analysis/ist0123/index.md
  content/en/docs/reference/config/analysis/ist0125/index.md
Labels: cla: yes, size/L

#8503 Update tenancy models doc
  content/en/docs/ops/deployment/deployment-models/index.md
  content/en/docs/ops/deployment/deployment-models/iso-ns.svg
Labels: cla: yes, size/M

#8502 Address suggestions from WG for Helm docs
  content/en/docs/setup/install/helm/index.md
Labels: area/environments, cla: yes, kind/docs, size/M

#8506 Analysis doc for codes 127-131
  content/en/docs/reference/config/analysis/ist0127/index.md
  content/en/docs/reference/config/analysis/ist0128/index.md
  content/en/docs/reference/config/analysis/ist0129/index.md
  content/en/docs/reference/config/analysis/ist0130/index.md
  content/en/docs/reference/config/analysis/ist0131/index.md
Labels: cla: yes, size/L

#8507 telemetry: updates to customizations
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, size/M

#8508 FAQ updates
  content/en/docs/ops/deployment/deployment-models/index.md
  content/en/faq/general/how-do-i-get-started.md
  content/en/faq/general/what-deployment-environment.md
  content/en/faq/general/where-is-the-documentation.md
Labels: cla: yes, size/S

#8512 add streaming metrics
  content/en/docs/reference/config/metrics/index.md
Labels: cla: yes, size/XS

#8511 Improving the accuracy and completeness of the Admiral project description
  content/en/docs/ops/deployment/deployment-models/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#8513 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8516 Remove @...@ from dir, only works for files
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/XS

#8519 Fix incorrect text about addons
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, size/XS

#8517 add verify traffic step for VM doc
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/M

#8518 Release notes for 1.7.5
  content/en/news/releases/1.7.x/announcing-1.7.5/index.md
Labels: cherrypick/release-1.7, cla: yes, size/M

#8453 Update feature stage
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/S

#8523 Fix archive link
  content/en/docs/_index.md
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#8525 Use cluster.env over sidecar.env to match install.
  content/en/docs/examples/virtual-machines/multi-network/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#8415 preliminary release notes for 1.8
  .spelling
  content/en/news/releases/1.8.x/_index.md
  content/en/news/releases/1.8.x/announcing-1.8/_index.md
  content/en/news/releases/1.8.x/announcing-1.8/change-notes/index.md
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: area/test and release, cla: yes, do-not-merge, kind/docs, size/L

#8520 [release-1.7] Release notes for 1.7.5
  content/en/news/releases/1.7.x/announcing-1.7.5/index.md
  data/args.yml
Labels: cla: yes, do-not-merge, release-notes-none, size/M

#8521 Reword release note for 1.7.5
  content/en/news/releases/1.7.x/announcing-1.7.5/index.md
Labels: cla: yes, size/XS

#8529 Mark v1.7 as archived
  config.toml
  data/args.yml
Labels: cla: yes, kind/docs, size/XS

#8530 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8531 [release-1.8] Reword release note for 1.7.5
  content/en/news/releases/1.7.x/announcing-1.7.5/index.md
Labels: cla: yes, do-not-merge, release-notes-none, size/XS

#8532 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8514 doc: update broken link
  content/en/docs/setup/getting-started/index.md
Labels: cherrypick/master, cherrypick/release-1.8, cla: yes, kind/docs, ok-to-test, size/XS

#8533 fix jsonpath typo on in-place upgrade section
  content/en/docs/setup/install/operator/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, ok-to-test, size/XS

#8534 [release-1.8] fix jsonpath typo on in-place upgrade section
  content/en/docs/setup/install/operator/index.md
Labels: cla: no, release-notes-none, size/XS

#8536 [release-1.8] doc: update broken link
  content/en/docs/setup/getting-started/index.md
Labels: cla: no, release-notes-none, size/XS

#8535 [master] doc: update broken link
  content/en/docs/setup/getting-started/index.md
Labels: cla: no, release-notes-none, size/XS

#8542 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8543 update release notes and authz task for a critical bug
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/news/releases/1.8.x/announcing-1.8/change-notes/index.md
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: area/security, cherrypick/release-1.8, cla: yes, size/S

#8544 [release-1.8] update release notes and authz task for a critical bug
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/news/releases/1.8.x/announcing-1.8/change-notes/index.md
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: cla: yes, release-notes-none, size/S

#8545 add security note for proxy protocol issue
  content/en/news/security/istio-security-2020-011/index.md
Labels: area/security, cherrypick/release-1.8, cla: yes, size/M

#8524 Several test framework improvements
  content/en/docs/setup/getting-started/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/tls_test.sh
  go.mod
  pkg/test/istioio/builder.go
  pkg/test/istioio/framework.go
  pkg/test/istioio/script.go
  pkg/test/istioio/snapshot.go
  pkg/test/istioio/snapshot_validator.go
  pkg/test/istioio/snapshotter.go
  pkg/test/istioio/step.go
  pkg/test/istioio/util.go
  tests/README.md
  tests/util/debug.sh
  tests/util/helpers.sh
  tests/util/samples.sh
  tests/util/verify.sh
Labels: cla: yes, size/XL

#8553 1.8 announcement page: remove broken link
  content/en/news/releases/1.8.x/announcing-1.8/_index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8555 [release-1.8] 1.8 announcement page: remove broken link
  content/en/news/releases/1.8.x/announcing-1.8/_index.md
Labels: cla: no, release-notes-none, size/XS

#8541 update the security documentation
  content/en/docs/reference/config/security/conditions/index.md
  content/en/docs/reference/config/type/_index.md
Labels: area/security, cherrypick/release-1.8, cla: yes, size/S

#8546 [release-1.8] add security note for proxy protocol issue
  content/en/news/security/istio-security-2020-011/index.md
Labels: cla: no, release-notes-none, size/M

#8538 Announce EOL for Istio 1.6
  content/en/news/support/announcing-1.6-eol-final/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8556 [release-1.8] update the security documentation
  content/en/docs/reference/config/security/conditions/index.md
  content/en/docs/reference/config/type/_index.md
Labels: cla: yes, release-notes-none, size/S

#8557 [release-1.8] Announce EOL for Istio 1.6
  content/en/news/support/announcing-1.6-eol-final/index.md
Labels: cla: no, release-notes-none, size/S

#8558 Automator: update common-files@release-1.8 in istio/istio.io@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8540 1.6.14 release notes
  content/en/news/releases/1.6.x/announcing-1.6.14/index.md
Labels: cherrypick/release-1.8, cla: yes, size/S

#8563 [release-1.8] 1.6.14 release notes
  content/en/news/releases/1.6.x/announcing-1.6.14/index.md
Labels: cla: yes, release-notes-none, size/S

#8559 Update istio/istio ref to 1.6.14
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
  go.mod
  go.sum
Labels: cla: yes, size/S

#8560 Update istio/istio ref to 1.7.5
  go.mod
  go.sum
Labels: cla: yes, size/S

#8561 Update istio/istio ref to 1.8.0
  go.mod
  go.sum
Labels: cla: yes, size/S

#8565 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8552 update 1.8 change notes
  content/en/news/releases/1.8.x/announcing-1.8/change-notes/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8566 update istiod gw sample in 1.8 upgrade notes
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8568 [release-1.8] update istiod gw sample in 1.8 upgrade notes
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: cla: yes, release-notes-none, size/XS

#8402 Rework locality LB docs into tasks
  content/en/about/feature-stages/index.md
  content/en/docs/ops/configuration/traffic-management/locality-load-balancing/index.md
  content/en/docs/ops/deployment/deployment-models/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/_index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/setup.svg
  content/en/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/snips.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/common.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/snips.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/test.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/sequence.svg
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/snips.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/test.sh
  content/en/news/releases/1.2.x/announcing-1.2/change-notes/index.md
  pkg/test/istioio/snapshot.go
  pkg/test/istioio/snapshot_validator.go
Labels: cla: yes, kind/docs, size/XXL

#8564 Test cleanup
  content/en/docs/examples/bookinfo/test.sh
  content/en/docs/ops/configuration/mesh/app-health-check/test.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  content/en/docs/setup/getting-started/test.sh
  content/en/docs/setup/install/multicluster/multi-primary/test.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/test.sh
  content/en/docs/setup/install/multicluster/primary-remote/test.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/test.sh
  content/en/docs/tasks/observability/distributed-tracing/jaeger/test.sh
  content/en/docs/tasks/observability/distributed-tracing/zipkin/test.sh
  content/en/docs/tasks/observability/gateways/insecure_access_test.sh
  content/en/docs/tasks/observability/gateways/secure_access_test.sh
  content/en/docs/tasks/observability/logs/access-log/test.sh
  content/en/docs/tasks/observability/metrics/customize-metrics/test.sh
  content/en/docs/tasks/observability/metrics/querying-metrics/test.sh
  content/en/docs/tasks/observability/metrics/tcp-metrics/test.sh
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/test.sh
  content/en/docs/tasks/security/authentication/authn-policy/test.sh
  content/en/docs/tasks/security/authorization/authz-deny/test.sh
  content/en/docs/tasks/security/authorization/authz-http/test.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
  content/en/docs/tasks/security/authorization/authz-jwt/test.sh
  content/en/docs/tasks/security/authorization/authz-tcp/test.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/test.sh
  content/en/docs/tasks/security/cert-management/dns-cert/test.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/test.sh
  content/en/docs/tasks/traffic-management/circuit-breaking/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/tls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/tls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/test.sh
  content/en/docs/tasks/traffic-management/egress/http-proxy/test.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
  content/en/docs/tasks/traffic-management/fault-injection/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/test.sh
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/test.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/test.sh
  content/en/docs/tasks/traffic-management/mirroring/test.sh
  content/en/docs/tasks/traffic-management/request-routing/test.sh
  content/en/docs/tasks/traffic-management/request-timeouts/test.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/test.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/test.sh
  pkg/test/istioio/framework.go
  tests/README.md
Labels: cla: yes, size/M

#8569 Link multicluster docs to locality LB
  content/en/docs/setup/install/multicluster/verify/index.md
Labels: cla: yes, kind/docs, size/XS

#8567 [release-1.8] update 1.8 change notes
  content/en/news/releases/1.8.x/announcing-1.8/change-notes/index.md
Labels: cla: yes, release-notes-none, size/XS

#8572 Update supported releases page
  content/en/about/supported-releases/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8576 [release-1.8] Update supported releases page
  content/en/about/supported-releases/index.md
Labels: cla: no, release-notes-none, size/S

#8575 update command to check connected istiod.
  content/en/docs/setup/upgrade/canary/index.md
Labels: area/environments, cherrypick/release-1.8, cla: yes, kind/docs, size/XS

#8577 [release-1.8] update command to check connected istiod.
  content/en/docs/setup/upgrade/canary/index.md
Labels: cla: no, release-notes-none, size/XS

#8574 Update Performance and Scalability Page for 1.8
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_without_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_without_jitter.svg
Labels: area/perf and scalability, cherrypick/release-1.8, cla: yes, size/S

#8571 Various cleanup for locality LB tasks
  content/en/docs/tasks/traffic-management/locality-load-balancing/cleanup/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/cleanup/snips.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/common.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
Labels: cla: yes, kind/docs, size/L

#8578 [release-1.8] Update Performance and Scalability Page for 1.8
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_without_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_without_jitter.svg
Labels: cla: yes, release-notes-none, size/S

#8580 [kiali] The API is no longer published.
  content/en/docs/tasks/observability/kiali/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8581 [release-1.8] [kiali] The API is no longer published.
  content/en/docs/tasks/observability/kiali/index.md
Labels: cla: no, release-notes-none, size/S

#8570 Minor improvements to locality LB tasks
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/_index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/test.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/test.sh
Labels: cla: yes, size/S

#8573 Add istioctl bug-report command for reporting bugs
  content/en/about/bugs/index.md
Labels: cherrypick/release-1.8, cla: yes, size/S

#8582 [release-1.8] Add istioctl bug-report command for reporting bugs
  content/en/about/bugs/index.md
Labels: cla: no, release-notes-none, size/S

#8583 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8586 Automator: update common-files@release-1.7 in istio/istio.io@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8585 fix operator install command witm helm.
  content/en/docs/setup/install/operator/index.md
Labels: area/environments, cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8584 add default access log format to the access log task
  .spelling
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
Labels: cla: yes, size/M

#8587 [release-1.8] fix operator install command witm helm.
  content/en/docs/setup/install/operator/index.md
Labels: cla: no, release-notes-none, size/S

#8591 [Helm] move warning before installing base helm chart
  content/en/docs/setup/install/helm/index.md
Labels: cherrypick/release-1.8, cla: yes, size/S

#8593 [Helm] fix invalid quote in tag
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS

#8598 [release-1.8] [Helm] move warning before installing base helm chart
  content/en/docs/setup/install/helm/index.md
Labels: cla: no, release-notes-none, size/S

#8486 Add documentation for Analysis messsage IST0132 VirtualServiceHostNotFoundInGateway
  content/en/docs/reference/config/analysis/ist0132/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#8595 zh-translation:content/en/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/operator/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#8600 zh-retranslation:content/zh/docs/setup/getting-started/index.md
  content/zh/docs/setup/getting-started/index.md
  content/zh/docs/setup/getting-started/kiali-example2.png
Labels: cherrypick/release-1.8, cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#8592 [Helm] update warning for canary upgrade of gateways
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS
