Repository istio/istio.io, pull requests merged in 2020-10, with the labels that each got.

#8247 Add example for how to install distroless images
  content/en/docs/ops/configuration/security/harden-docker-images/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8248 Fixes for multicluster install doc
  content/en/docs/setup/install/multicluster/index.md
  content/en/docs/setup/install/multicluster/snips.sh
Labels: cla: yes, kind/docs, size/L

#8251 More fixes for multicluster install docs.
  .spelling
  content/en/docs/setup/install/multicluster/index.md
  content/en/docs/setup/install/multicluster/multi-primary-multi-network.svg
  content/en/docs/setup/install/multicluster/multi-primary.svg
  content/en/docs/setup/install/multicluster/primary-remote-multi-network.svg
  content/en/docs/setup/install/multicluster/primary-remote.svg
  content/en/docs/setup/install/multicluster/snips.sh
Labels: cla: yes, kind/docs, size/L

#8255 [Test Framework] Refactor to properly use subtests.
  pkg/test/istioio/builder.go
  pkg/test/istioio/framework.go
  tests/setup/multicluster/doc_test.go
  tests/setup/profile_default/doc_test.go
  tests/setup/profile_demo/doc_test.go
  tests/setup/profile_none/doc_test.go
Labels: cla: yes, size/M

#8254 Revert to -o pipefail and fix lint-yaml, revert istio commit
  Makefile.core.mk
  go.mod
  go.sum
Labels: cla: yes, size/S

#8242 Warning about upgrading multiple minor versions
  content/en/docs/setup/upgrade/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8256 [release-1.7] Warning about upgrading multiple minor versions
  content/en/docs/setup/upgrade/index.md
Labels: cla: no, cla: yes, release-notes-none, size/XS

#8259 Update to the latest istio/istio
  go.mod
  go.sum
Labels: cla: yes, size/S

#8260 Update tests README note for kind cluster failure
  tests/README.md
Labels: cla: yes, size/XS

#8253 [Test Framework] Fixes to support multicluster
  content/en/docs/tasks/observability/distributed-tracing/zipkin/multicluster_test.sh
  pkg/test/istioio/framework.go
  pkg/test/istioio/script.go
  tests/README.md
  tests/setup/multicluster/doc_test.go
  tests/util/helpers.sh
  tests/util/verify.sh
Labels: cla: yes, kind/docs, size/L

#8261 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8257 Revert to common-files lint-yaml after fixing failure in common-files
  Makefile.core.mk
Labels: cla: yes, size/S

#8249 [release-1.7] Add example for how to install distroless images
  content/en/docs/ops/configuration/security/harden-docker-images/index.md
Labels: cla: no, release-notes-none, size/XS

#8250 README update on how to update build versions tests use
  Makefile.core.mk
  README.md
Labels: cla: yes, size/M

#8244 Update details for dynamic admission webhook prerequisites
  content/en/docs/ops/configuration/mesh/webhook/index.md
Labels: cla: yes, kind/docs, size/S

#8265 Automator: update common-files@release-1.6 in istio/istio.io@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#8268 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8262 [Test Framework] Add multicluster test for multi-primary
  content/en/docs/setup/install/multicluster/common.sh
  content/en/docs/setup/install/multicluster/multi-primary-test.sh
  content/en/docs/tasks/observability/distributed-tracing/zipkin/multicluster_test.sh
Labels: area/test and release, cla: yes, size/L

#8266 Improve doc for doc tests
  .gitignore
  README.md
  layouts/partials/primary_top.html
Labels: cla: yes, size/L

#8264 Istio sidecar DNS resolution blog
  content/en/blog/2020/dns-proxy/dns-interception-in-istio.png
  content/en/blog/2020/dns-proxy/index.md
  content/en/blog/2020/dns-proxy/role-of-dns-today.png
  content/en/blog/2020/dns-proxy/vm-dns-resolution-issues.png
Labels: cla: yes, size/L

#8273 Fix README typos
  README.md
Labels: cla: yes, size/XS

#8275 Drop citadel config in mixer documentation
  content/en/docs/tasks/observability/mixer/metrics/collecting-metrics/index.md
Labels: cla: yes, size/XS

#8276 Update protocol selection page
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: cla: yes, size/M

#8277 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8214 Add warning on egress gw instructions
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: area/networking, area/user experience, cla: yes, kind/docs, ok-to-test, size/S

#8280 update components for operator api.
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#8279 add instruction to remove istio label.
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: area/environments, cla: yes, kind/docs, size/S

#8267 Release notes for Istio 1.6.12
  content/en/news/releases/1.6.x/announcing-1.6.12/index.md
Labels: cherrypick/release-1.7, cla: yes, size/S

#8281 [release-1.7] Release notes for Istio 1.6.12
  content/en/news/releases/1.6.x/announcing-1.6.12/index.md
Labels: cla: no, release-notes-none, size/S

#8282 add pod securitycontext to k8s settings for operator api.
  content/en/docs/setup/install/istioctl/index.md
Labels: area/environments, cherrypick/release-1.6, cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8292 Automator: update common-files@release-1.7 in istio/istio.io@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8294 typo istop/io -> istio.io
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8288 [release-1.6] add pod securitycontext to k8s settings for operator api.
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, release-notes-none, size/XS

#8289 [release-1.7] add pod securitycontext to k8s settings for operator api.
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, release-notes-none, size/XS

#8291 Tip for using --set flag
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#8293 Update feature stage doc to make all mixer feature deprecated
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/XS

#8290 Update istio/istio test reference
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  go.mod
  go.sum
Labels: cla: yes, size/S

#8296 [release-1.7] Fix doc formatting
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: cla: yes, size/S

#8287 Update test reference to 1.6.12
  go.mod
  go.sum
Labels: cla: yes, size/S

#8297 Clarify setting sampling rate
  content/en/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
Labels: cla: yes, size/S

#8305 Update multicluster install docs with latest config.
  content/en/docs/setup/install/multicluster/index.md
  content/en/docs/setup/install/multicluster/snips.sh
  go.mod
  go.sum
Labels: area/test and release, cla: yes, kind/docs, size/L

#8306 zh_translation: fix a link error
  content/zh/docs/concepts/traffic-management/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#8307 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8308 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8312 [Test Framework] General improvements
  pkg/test/istioio/builder.go
  pkg/test/istioio/context.go
  pkg/test/istioio/framework.go
  pkg/test/istioio/input.go
  pkg/test/istioio/script.go
  tests/setup/multicluster/doc_test.go
  tests/setup/profile_default/doc_test.go
  tests/setup/profile_demo/doc_test.go
  tests/setup/profile_none/doc_test.go
  tests/tests.mk
Labels: cla: yes, size/L

#8313 zh_translation: fix a broken link in kiali task doc
  content/zh/docs/tasks/observability/kiali/index.md
Labels: area/test and release, cla: yes, kind/docs, size/XS, translation/chinese

#8310 Update reference script to not strip leading istio.io on /vx.y
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/proxy_extensions/attributegen/index.html
  content/en/docs/reference/config/proxy_extensions/basic_auth/index.html
  content/en/docs/reference/config/proxy_extensions/stackdriver/index.html
  content/en/docs/reference/config/proxy_extensions/stats/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  data/analysis.yaml
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XXL

#8311 Fix '/home/.gitconfig' error message when using build container
  Makefile.overrides.mk
Labels: cla: yes, size/XS

#8314 Clarify primary/remote using gloss refs
  content/en/docs/setup/install/multicluster/index.md
Labels: cla: yes, size/XS

#8316 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8315 Fix list in docs
  content/en/about/security-vulnerabilities/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8319 [release-1.7] Fix list in docs
  content/en/about/security-vulnerabilities/index.md
Labels: cla: yes, release-notes-none, size/XS

#8317 Fix recordingRule expr
  content/en/docs/ops/best-practices/observability/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#8298 Improvements to the network topologies doc
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
Labels: cla: yes, kind/docs, size/M

#8322 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8283 Add install/uninstall/upgrade steps for Istio with Helm3
  DOC_OWNERS.md
  content/en/docs/setup/install/helm/index.md
Labels: area/environments, cla: yes, size/L

#8320 Announce EOL for Istio 1.6.x
  content/en/news/support/announcing-1.6-eol/index.md
Labels: cla: yes, kind/docs, size/S

#8326 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/en/docs/reference/config/proxy_extensions/stackdriver/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8309 Fixes for multicluster tests
  content/en/docs/setup/install/multicluster/common.sh
  content/en/docs/setup/install/multicluster/index.md
  content/en/docs/setup/install/multicluster/multi-primary-multi-network-test.sh
  content/en/docs/setup/install/multicluster/multi-primary-test.sh
  content/en/docs/setup/install/multicluster/primary-remote-multi-network-test.sh
  content/en/docs/setup/install/multicluster/primary-remote-test.sh
  content/en/docs/setup/install/multicluster/snips.sh
  go.mod
  go.sum
  tests/util/helpers.sh
  tests/util/verify.sh
Labels: area/test and release, cla: yes, kind/docs, size/XL

#8324 [release-1.7] Announce EOL for Istio 1.6.x
  content/en/news/support/announcing-1.6-eol/index.md
Labels: cla: yes, release-notes-none, size/S

#8328 prepare for release-1.8 as istio source is already branched
  Makefile.core.mk
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  data/args.yml
Labels: cla: yes, size/S

#8329 Initial setting of istio test ref to 1.8 branch
  go.mod
  go.sum
Labels: cla: yes, size/S

#8331 Use remote profile for remote clusters
  content/en/docs/setup/install/multicluster/index.md
  content/en/docs/setup/install/multicluster/snips.sh
Labels: cla: yes, size/S

#8330 Understanding TLS configuration doc
  .spelling
  DOC_OWNERS.md
  content/en/docs/ops/common-problems/network-issues/index.md
  content/en/docs/ops/configuration/traffic-management/tls-configuration/gateway-connections.svg
  content/en/docs/ops/configuration/traffic-management/tls-configuration/index.md
  content/en/docs/ops/configuration/traffic-management/tls-configuration/sidecar-connections.svg
  content/en/faq/traffic-management/difference-between-mutual-and-istio-mutual.md
Labels: cla: yes, size/L

#8284 zh_translation: fix error ca-cert.pem
  content/zh/docs/tasks/security/plugin-ca-cert/index.md
Labels: cherrypick/release-1.7, cla: yes, ok-to-test, size/XS, translation/chinese

#8327 Add GCP/GKE global access attributes
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#8336 Switch to public blog slides
  content/en/blog/2020/multiple-control-planes/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8334 Add Openshift in the istioctl profile list
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, kind/docs, size/XS

#8338 [release-1.7] Switch to public blog slides
  content/en/blog/2020/multiple-control-planes/index.md
Labels: cla: yes, release-notes-none, size/XS

#8343 Update egress tasks
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: cla: yes, size/L

#8350 Added clarification on canary upgrades w.r.t gateways
  content/en/docs/setup/install/helm/index.md
Labels: area/environments, cla: yes, kind/docs, size/XS

#8346 Add wait for gateway to multicluster tests
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/install/multicluster/before-you-begin/index.md
  content/en/docs/setup/install/multicluster/common.sh
  content/en/docs/setup/install/multicluster/multi-primary/test.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/test.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/test.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/test.sh
  content/en/docs/tasks/security/authorization/authz-deny/test.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
  content/en/docs/tasks/security/authorization/authz-jwt/test.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/test.sh
  content/en/docs/tasks/security/cert-management/dns-cert/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/test.sh
  pkg/test/istioio/script.go
  tests/README.md
  tests/util/helpers.sh
  tests/util/verify.sh
Labels: area/test and release, cla: yes, kind/docs, size/L

#8351 Update ports page
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, size/XS

#8347 multi-network: label namespaces with network
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
Labels: cla: yes, size/M

#8358 Fix markdown section number issue
  content/en/docs/tasks/observability/gateways/index.md
Labels: cla: yes, size/S

#8344 1.6.13 release notes
  content/en/news/releases/1.6.x/announcing-1.6.13/index.md
Labels: cherrypick/release-1.7, cla: yes, size/S

#8318 Include prometheus-operator resource example for aggregationRules
  content/en/docs/ops/best-practices/observability/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#8339 update doc for classify metrics
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: cla: yes

#8367 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8368 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8360 Remove ICP from IBM Cloud platform setup page
  content/en/docs/setup/platform-setup/ibm/index.md
Labels: cla: yes, size/XS

#8356 Release notes for 1.7.4
  content/en/news/releases/1.7.x/announcing-1.7.4/index.md
Labels: cherrypick/release-1.7, cla: yes, size/M

#8369 fix vms gateway
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/XS

#8365 [release-1.6] Update test reference to 1.6.13
  go.mod
  go.sum
Labels: cla: yes, size/XS

#8366 [release-1.7] Update test reference to 1.7.4
  go.mod
  go.sum
Labels: cla: yes, size/S

#8299 Add ops guide for separate gateways management
  DOC_OWNERS.md
  content/en/docs/ops/configuration/multi-revision/_index.md
  content/en/docs/ops/configuration/multi-revision/gateways/index.md
Labels: cla: yes, size/L

#8342 step 10 is duplicated with step 4
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cherrypick/release-1.7, cla: yes, ok-to-test, size/XS

#8370 remove unused cleanup step
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
Labels: cla: yes, size/XS

#8373 Remove production usage as Helm support in pre-alpha
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, size/XS

#8348 List supported releases
  content/en/about/supported-releases/index.md
Labels: cla: yes, size/S

#8377 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XXL

#8379 Update the `Learn Microservices Using Kubernetes and Istio` example
  content/en/docs/examples/microservices-istio/add-istio/index.md
  content/en/docs/examples/microservices-istio/add-new-microservice-version/index.md
  content/en/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
  content/en/docs/examples/microservices-istio/logs-istio/index.md
  content/en/docs/examples/microservices-istio/package-service/index.md
  content/en/docs/examples/microservices-istio/production-testing/index.md
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/en/docs/examples/microservices-istio/setup-local-computer/index.md
Labels: cla: yes, size/M

#8375 Better organize upgrade setup instructions
  DOC_OWNERS.md
  content/en/docs/ops/configuration/multi-revision/_index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/upgrade/_index.md
  content/en/docs/setup/upgrade/canary/index.md
  content/en/docs/setup/upgrade/gateways/index.md
  content/en/docs/setup/upgrade/in-place/index.md
Labels: cla: yes, size/L

#8371 [release-1.7] Release notes for 1.7.4
  content/en/news/releases/1.7.x/announcing-1.7.4/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/M

#8376 add extra tag mesh config
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/snips.sh
Labels: cla: yes, size/S

#8381 Minor updates to downgrade instructions
  content/en/docs/setup/upgrade/_index.md
  content/en/docs/setup/upgrade/in-place/index.md
Labels: cla: yes, size/S

#8362 [release-1.7] 1.6.13 release notes
  content/en/news/releases/1.6.x/announcing-1.6.13/index.md
Labels: cla: yes, release-notes-none, size/S

#8389 Remove stale reference to consul
  content/en/docs/ops/deployment/architecture/index.md
Labels: cla: yes, size/XS

#8386 Update example doc with modern settings
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, size/XS

#8392 Fix invalid operator sample
  content/en/docs/setup/install/istioctl/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8384 Allow owned _index.md files
  DOC_OWNERS.md
  scripts/doc_owners.sh
Labels: cla: yes, size/XS

#8394 [release-1.7] Fix invalid operator sample
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: no, release-notes-none, size/XS

#8395 Update to more recent kubernetes version.
  content/en/docs/setup/platform-setup/minikube/index.md
Labels: cla: yes, size/XS

#8325 Update stats inclusion to use proxy config instead
  content/en/docs/ops/configuration/telemetry/envoy-stats/index.md
Labels: cla: yes, size/M

#8398 Minor updates for 1.8 of istioctl analyzer doc
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
Labels: cla: yes, size/XS

#8382 Improve how we operate by linking to recent changes and information
  content/en/about/community/join/governance.svg
  content/en/about/community/join/index.md
Labels: cherrypick/release-1.7, cla: yes, size/S

#8400 minor updates to Before You Begin (MC doc).
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/install/multicluster/before-you-begin/index.md
Labels: cla: yes, size/XS

#8406 [release-1.7] Improve how we operate by linking to recent changes and information
  content/en/about/community/join/governance.svg
  content/en/about/community/join/index.md
Labels: cla: no, release-notes-none, size/S

#8408 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8399 Update test reference to 1.8.0-alpha.2
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/logs/access-log/test.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
  content/en/docs/tasks/security/authorization/authz-td-migration/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/test.sh
  go.mod
  go.sum
Labels: cla: yes, size/L

#8354 Add guide about provision Istio certs for prometheus scraping
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cla: yes, size/M

#8378 grant mysql root access to other IPs
  content/en/docs/examples/virtual-machines/bookinfo/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#8413 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8416 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8417 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8419 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS
