Repository istio/istio.io, pull requests merged in 2020-01, with the labels that each got.

#6263 zh-translations: /blog/2019/egress-traffic-control-in-istio-part-3/index.md
  content/zh/blog/2019/egress-traffic-control-in-istio-part-3/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6268 zh-translation: /news/releases/1.1.x/announcing-1.1.2/index.md #1548
  content/zh/news/releases/1.1.x/announcing-1.1.2/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6269 zh-translation: /news/releases/1.1.x/announcing-1.1.13/index.md #1543
  content/zh/news/releases/1.1.x/announcing-1.1.13/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6270 zh-translation: /blog/2019/v1beta1-authorization-policy/index.md
  content/zh/blog/2019/v1beta1-authorization-policy/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6267 zh-translation: /news/releases/1.1.x/announcing-1.1/_index.md #1556
  content/zh/news/releases/1.1.x/announcing-1.1/_index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6264 zh-translation: /news/releases/1.2.x/announcing-1.2/_index.md
  content/zh/news/releases/1.2.x/announcing-1.2/_index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6247 zh-translation:/blog/2018/istio-authorization/index.md
  content/zh/blog/2018/istio-authorization/index.md
Labels: cla: yes, size/L, translation/chinese

#6219 Martin transferred the istio.io site to me, I need to update the search engine unique ID in response.
  data/args.yml
Labels: cla: yes, kind/docs, size/XS

#6220 Blog on configuration automation for Istio multicluster with local control planes
  .spelling
  content/en/blog/2020/_index.md
  content/en/blog/2020/multi-cluster-mesh-automation/Istio_mesh_example.svg
  content/en/blog/2020/multi-cluster-mesh-automation/Istio_mesh_example_with_admiral.svg
  content/en/blog/2020/multi-cluster-mesh-automation/index.md
Labels: area/config, area/networking, cla: yes, kind/docs, size/L

#6153 Tutorial fixes: prerequisites, setup Kubernetes, setup a local computer
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/en/docs/examples/microservices-istio/setup-local-computer/index.md
Labels: cla: yes, kind/docs, size/M

#6273 zh-translation: fix anchor for helm 1.3
  content/zh/news/releases/1.3.x/announcing-1.3/helm-changes/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6256 Fix local build break
  layouts/shortcodes/change_log.html
Labels: cla: yes, kind/docs, size/S

#6245 V1/2_POD_IP error when there are other pods labelled version=v1/2
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
Labels: cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#6286 Minor corrections to admiral blog post
  .spelling
  content/en/blog/2020/multi-cluster-mesh-automation/index.md
Labels: cla: yes, size/S

#6206 Fix comments of 5262
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: cla: yes, kind/docs, size/XS

#6278 fix docs for protocol sniffing
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: cla: yes, size/XS

#5879 [kiali] issue 19232 talk about changing configmap
  content/en/docs/tasks/observability/kiali/index.md
Labels: cla: yes, kind/docs, size/XS

#6266 zh-translation: news/releases/announcing-1.1/change-notes/index.md #1557
  content/zh/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6291 zh-translation: /news/releases/1.2.x/announcing-1.2/helm-changes/inde…
  content/zh/news/releases/1.2.x/announcing-1.2/helm-changes/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6287 Manual cherrypick of #6220
  .spelling
  content/en/blog/2019/monitoring-external-service-traffic/index.md
  content/en/blog/2020/_index.md
  content/en/blog/2020/multi-cluster-mesh-automation/Istio_mesh_example.svg
  content/en/blog/2020/multi-cluster-mesh-automation/Istio_mesh_example_with_admiral.svg
  content/en/blog/2020/multi-cluster-mesh-automation/index.md
Labels: cla: yes, size/L

#6296 remove invalid anchor for lint
  content/en/blog/2019/monitoring-external-service-traffic/index.md
  content/zh/blog/2019/monitoring-external-service-traffic/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6280 add notes for enabling mTLS for authz
  content/en/docs/concepts/security/index.md
  content/en/docs/reference/config/security/conditions/index.md
  content/en/docs/tasks/security/authorization/authz-http/index.md
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: area/security, cherrypick/release-1.4, cla: yes, size/M

#6299 [release-1.4] add notes for enabling mTLS for authz
  content/en/docs/concepts/security/index.md
  content/en/docs/reference/config/security/conditions/index.md
  content/en/docs/tasks/security/authorization/authz-http/index.md
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: cla: yes, size/M

#6255 Improve the MTLS migration task.
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
Labels: area/security, cla: yes, kind/docs, size/L

#6298 Use proper Envoy link
  content/en/blog/2019/monitoring-external-service-traffic/index.md
  content/zh/blog/2019/monitoring-external-service-traffic/index.md
Labels: cla: yes, size/XS

#6300 [release-1.4] Improve the MTLS migration task.
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
Labels: cla: no, size/L

#6172 Fix protocol selection Helm values
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: area/config, cla: yes, kind/docs, ok-to-test, size/XS

#6231 Adds an entry for Redis in the FAQ
  content/en/faq/applications/redis.md
Labels: cla: yes, kind/docs, size/M

#6216 Update index.md installation options
  content/en/docs/reference/config/installation-options/index.md
Labels: area/environments, cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#5996 [release-1.4] fix istioctl instruction install instruction on gke
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/XS

#6187 update 1.4 release notes for JWT with space-delimited claim
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: area/security, cherrypick/release-1.4, cla: yes, size/XS

#6301 [release-1.4] update 1.4 release notes for JWT with space-delimited claim
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: cla: yes, size/XS

#6302 [release-1.4] Update index.md installation options
  content/en/docs/reference/config/installation-options/index.md
Labels: cla: no, size/XS

#6191 use openssl to generate certificates and keys
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
Labels: cla: yes, kind/docs, size/M

#6027 update index.md
  content/en/docs/tasks/policy-enforcement/enabling-policy/index.md
Labels: area/config, area/environments, area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#6308 update doc to remove usage of stats filter
  content/en/docs/ops/configuration/telemetry/in-proxy-service-telemetry/index.md
  content/zh/docs/ops/configuration/telemetry/in-proxy-service-telemetry/index.md
Labels: cla: yes, size/M

#6259 certificate decode error when decoding from bash pipe by openssl
  content/en/docs/tasks/security/dns-cert/index.md
  content/zh/docs/tasks/security/dns-cert/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6293 zh-translation: graceful anchor for helm 1.3
  content/zh/news/releases/1.3.x/announcing-1.3/helm-changes/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6272 zh-translation: /news/releases/1.2.x/announcing-1.2/change-notes/i…
  content/zh/news/releases/1.2.x/announcing-1.2/change-notes/index.md
Labels: cla: yes, kind/docs, size/L, translation/chinese

#6275 zh-translation: /docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/istioctl/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6277 zh-translation: update zh translation docs/ops/diagnostic-tools/istioctl-analyze
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: yes, kind/docs, size/M, translation/chinese

#6281 zh-translation: install/multicluster/shared-gateways/index.md #1725
  content/zh/docs/setup/install/multicluster/shared-gateways/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#6289 zh-translation: /docs/ops/best-practices/deployment/index.md #1730
  content/zh/docs/ops/best-practices/deployment/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6290 zh-translation: /docs/ops/best-practices/security/index.md #1732
  content/zh/docs/ops/best-practices/security/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6292 zh-translation: /docs/ops/configuration/mesh/secret-creation/index.md and validation sync
  content/zh/docs/ops/configuration/mesh/secret-creation/index.md
  content/zh/docs/ops/configuration/mesh/validation/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6294 zh-translation: /best-practices/traffic-management/index.md #1731
  content/zh/docs/ops/best-practices/traffic-management/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6283 zh-translation: sync for some updated doc
  content/zh/docs/reference/glossary/virtual-service.md
  content/zh/docs/setup/install/multicluster/shared-vpn/index.md
  content/zh/docs/tasks/security/authentication/mtls-migration/index.md
  content/zh/docs/tasks/security/citadel-config/auth-sds/index.md
  content/zh/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
  content/zh/faq/distributed-tracing/no-tracing.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6276 zh-translation: translate missing operator doc
  content/zh/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, kind/docs, size/S, translation/chinese

#6306 zh-translation: 1.3.x/announcing-1.3/change-notes/index.md #1582
  content/zh/news/releases/1.3.x/announcing-1.3/change-notes/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6218 zh-translation: /blog/2019/app-identity-and-access-adapter/index.md
  content/zh/blog/2019/app-identity-and-access-adapter/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6312 correct typo for link
  content/en/docs/tasks/security/citadel-config/ca-namespace-targeting/index.md
Labels: cla: yes, size/XS

#6171 Tutorial fixes: single microservice, docker, Kubernetes
  content/en/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/en/docs/examples/microservices-istio/package-service/index.md
  content/en/docs/examples/microservices-istio/single/index.md
Labels: cla: yes, kind/docs, size/M

#6311 Fix a couple bugs.
  layouts/partials/code_block.html
  src/sass/base/_base.scss
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6313 [release-1.4] Fix a couple bugs.
  layouts/partials/code_block.html
  src/sass/base/_base.scss
Labels: cla: yes, size/XS

#6315 Fix broken operator link
  content/en/blog/2019/introducing-istio-operator/index.md
  content/pt-br/blog/2019/introducing-istio-operator/index.md
  content/zh/blog/2019/introducing-istio-operator/index.md
Labels: cla: yes, size/XS

#6184 added Layer5
  content/en/about/community/partners/index.md
  content/en/about/community/partners/layer5.png
Labels: cla: yes, ok-to-test, size/XS

#6237 1.4.3 Release Notes
  content/en/news/releases/1.4.x/announcing-1.4.3/index.md
Labels: cherrypick/release-1.4, cla: yes, size/M

#6317 [release-1.4] 1.4.3 Release Notes
  content/en/news/releases/1.4.x/announcing-1.4.3/index.md
  data/args.yml
Labels: cla: yes, size/M

#6321 [release-1.4] added Layer5
  content/en/about/community/partners/index.md
  content/en/about/community/partners/layer5.png
Labels: cla: yes, size/XS

#6318 Fix parenthesis
  content/en/news/releases/1.4.x/announcing-1.4.3/index.md
Labels: cherrypick/release-1.4, cla: yes, size/XS

#6322 [release-1.4] Fix parenthesis
  content/en/news/releases/1.4.x/announcing-1.4.3/index.md
Labels: cla: yes, size/XS

#6327 Typo fix
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#6310 pt-br-translation: Home Page
  .gitignore
  content/pt-br/_index.html
Labels: cla: yes, kind/docs, ok-to-test, size/L

#6288 zh-translation: Run ratings in Docker
  content/zh/docs/examples/microservices-istio/package-service/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6274 zh-translation: /docs/examples/microservices-istio/single/index.md
  content/zh/docs/examples/microservices-istio/single/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#6331 zh-translation: /news/releases/1.1.x/announcing-1.1.4/announcing-1.1.4/index.md #1550
  content/zh/news/releases/1.1.x/announcing-1.1.4/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#6320 More accurate link to AuthorizationPolicy#conditions from conditions page
  content/en/docs/reference/config/security/conditions/index.md
  content/pt-br/docs/reference/config/security/conditions/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6328 [release-1.4] Typo fix
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: cla: no, size/XS

#6325 [release-1.4] partner update - layer5
  content/en/about/community/partners/index.md
  content/en/about/community/partners/layer5.png
  content/en/about/community/partners/layer5.svg
Labels: cla: no, size/XS

#6330 Fix Liveness-HTTP for health check deployment
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
Labels: area/user experience, cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#6326 fix github edit url with correct language
  layouts/_default/baseof.html
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#6271 fix istioctl setup example.
  content/zh/docs/setup/install/istioctl/index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#6307 add meta CLUSTER_NAME to remote cluster
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
Labels: area/environments, cla: yes, kind/docs, size/XS

#6336 zh-translation: translate monitor traffic
  content/zh/blog/2019/monitoring-external-service-traffic/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6341 Announce upcoming 1.3 EOL
  content/en/news/support/announcing-1.3-eol/index.md
Labels: area/test and release, cherrypick/release-1.4, cla: yes, size/S

#6342 [release-1.4] Announce upcoming 1.3 EOL
  content/en/news/support/announcing-1.3-eol/index.md
Labels: cla: yes, size/S

#6339 [release-1.4] add meta CLUSTER_NAME to remote cluster
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
Labels: cla: no, size/XS

#6346 2019 vs 2020 typo in 1.3 EOL announcement
  content/en/news/support/announcing-1.3-eol/index.md
Labels: cherrypick/release-1.4, cla: yes, kind/docs, ok-to-test, size/XS

#6340 update Simplified Multicluster Install page
  content/en/docs/setup/install/multicluster/simplified/index.md
  content/pt-br/docs/setup/install/multicluster/simplified/index.md
  content/zh/docs/setup/install/multicluster/simplified/index.md
Labels: area/environments, cla: yes, ok-to-test, size/S

#6347 [release-1.4] 2019 vs 2020 typo in 1.3 EOL announcement
  content/en/news/support/announcing-1.3-eol/index.md
Labels: cla: no, size/XS

#6348 zh-translation: update some sentences
  content/zh/boilerplates/start-httpbin-service.md
  content/zh/docs/ops/common-problems/injection/index.md
  content/zh/docs/setup/install/istioctl/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/news/_index.md
  content/zh/news/releases/1.2.x/announcing-1.2/helm-changes/index.md
Labels: cla: yes, kind/docs, size/M, translation/chinese

#6350 #20068 Update namespace as per the integration test
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/S

#6354 Document suppression arguments for istioctl analyze
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: area/test and release, cla: yes, size/M

#6343 Clarifying automatic sidecar injection
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, kind/docs, size/XS

#6364 Introduce the guide at the beginning, not part way through
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, kind/docs, size/S

#6366 Automator: update istio.io@master reference docs
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istio_ca/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/security/istio.rbac.v1alpha1/index.html
Labels: cla: yes, size/XXL

#6371 Fix CNI instructions
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/XS

#6370 Add GRPC-WEB to supported protocol for Gateway
  content/en/docs/reference/config/networking/gateway/index.html
Labels: area/networking, cla: yes, kind/docs, ok-to-test, size/XS

#6373 Automator: update istio.io@master reference docs
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
Labels: cla: yes, size/S

#6382 Fix problem links
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/news/releases/0.x/announcing-0.1/index.md
  content/pt-br/docs/reference/config/security/istio.authentication.v1alpha1/index.html
  content/pt-br/news/releases/0.x/announcing-0.1/index.md
  content/zh/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/zh/news/releases/0.x/announcing-0.1/index.md
Labels: cla: yes, size/S

#6381 Apply netlify best practices
  netlify.toml
Labels: cla: yes, size/XS

#6352 Update grab_operator_yamls.sh script to point to istio/istio
  scripts/grab_operator_yamls.sh
Labels: cla: yes, kind/docs, size/XS

#6376 adding layer5 adapter to the repos
  scripts/grab_reference_docs.sh
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6365 Automator: update common-files@master in istio/istio.io@master
  LICENSE
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
Labels: cla: yes, size/M

#6380 Update Solo.io logo
  content/en/about/community/partners/index.md
  content/en/about/community/partners/solo.png
  content/en/about/community/partners/solo.webp
Labels: cla: yes, size/XS

#6361 Remove galley docs
  content/en/docs/ops/common-problems/validation/index.md
  content/en/docs/ops/configuration/mesh/validation/index.md
  content/en/docs/tasks/security/webhook/index.md
Labels: cla: yes, size/L

#6375 Automator: update istio.io@master reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: cla: yes, size/M
