Repository istio/istio.io, pull requests merged in 2020-03, with the labels that each got.

#6656 [release 1.4] Apply netlify best practices (#6381)
  netlify.toml
Labels: cla: yes, size/XS

#6654 Removed SDS reference per John Howard
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, kind/docs, size/XS

#6655 zh-translation for about/contribute/terminology
  content/zh/about/contribute/terminology/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6619 zh-translation: sync some missing content
  content/zh/news/releases/1.3.x/announcing-1.3.7/index.md
  content/zh/news/releases/1.3.x/announcing-1.3.8/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.4/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.5/index.md
  content/zh/news/security/istio-security-2019-007/index.md
  content/zh/news/security/istio-security-2020-001/index.md
  content/zh/news/security/istio-security-2020-002/index.md
  content/zh/news/support/announcing-1.3-eol-final/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6658 zh-translation:/content/zh/about/contribute/github/index.md
  content/zh/about/contribute/diagrams/index.md
  content/zh/about/contribute/github/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6648 Removed unneeded command from snippet
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#6677 Fix minor syntax error on istioctl describe
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: cla: yes, size/XS

#6665 Spelling update
  content/en/docs/tasks/observability/logs/access-log/index.md
Labels: cla: yes, size/XS

#6679 Community testing updates to querying metrics
  content/en/docs/tasks/observability/metrics/querying-metrics/index.md
  content/en/docs/tasks/observability/metrics/querying-metrics/prometheus_query_result_graphical.png
Labels: cla: yes, size/S

#6667 Add note to citadel doc
  content/en/docs/ops/configuration/mesh/secret-creation/index.md
Labels: cla: yes, size/XS

#6682 Fix per-port peer authentication command
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
Labels: cla: yes, kind/docs, size/S

#6688 Update troubleshooting guide for ingress SDS
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
Labels: area/security, cla: yes, kind/docs, size/XS

#6607 zh-translation: /about/contribute/_index.md #1777
  content/zh/about/contribute/_index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#6608 zh-translation: /about/contribute/style-guide/index.md #1781
  content/zh/about/contribute/style-guide/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6659 zh-trans:/content/zh/about/contribute/add-content/index.md
  content/zh/about/contribute/add-content/index.md
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#6686 Minor update to istioctl install doc
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#6708 Release 1.4.6
  .spelling
  content/en/news/releases/1.4.x/announcing-1.4.6/index.md
  content/en/news/security/istio-security-2020-003/index.md
Labels: cherrypick/release-1.4, cla: yes, size/L

#6709 [release-1.4] Release 1.4.6
  .spelling
  content/en/news/releases/1.4.x/announcing-1.4.6/index.md
  content/en/news/security/istio-security-2020-003/index.md
  data/args.yml
Labels: cla: yes, size/L

#6710 Fix CVE links and release notes goofiness
  content/en/news/releases/1.4.x/announcing-1.4.6/index.md
  content/en/news/security/istio-security-2020-003/index.md
Labels: cherrypick/release-1.4, cla: yes, size/S

#6712 [release-1.4] Fix CVE links and release notes goofiness
  content/en/news/releases/1.4.x/announcing-1.4.6/index.md
  content/en/news/security/istio-security-2020-003/index.md
Labels: cla: yes, size/S

#6685 access log updates for command output, variable names
  content/en/docs/tasks/observability/logs/access-log/index.md
Labels: cla: yes, size/M

#6694 Updated guide for Authorization Policy Trust Domain Migration
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
Labels: area/security, cla: yes, community/testing days, kind/docs, size/S

#6664 Updates to ExternalName doc
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: cla: yes, size/S

#6691 istio-policy should have been merged into istiod, cannnot see it by testing
  content/en/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, community/testing days, kind/docs, size/XS

#6692 authz: add task for IP allow list and black list on ingress gateway
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
Labels: area/security, cla: yes, size/L

#6693 authz: update authz JWT task
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
  content/en/docs/tasks/security/authorization/rbac-groups/index.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: area/security, cla: yes, size/L

#6642 Improved Istio Getting Started
  .spelling
  content/en/about/contribute/github/index.md
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/kiali-example2.png
Labels: cla: yes, community/testing days, kind/docs, size/L

#6701 zh-translation: /about/contribute/code-blocks/index.md #1768
  content/zh/about/contribute/code-blocks/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6699 zh-translation: /about/contribute/formatting/index.md #1769
  content/zh/about/contribute/formatting/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M, translation/chinese

#6696 zh-translation: /about/contribute/shortcodes/index.md #1772
  content/zh/about/contribute/shortcodes/index.md
  content/zh/events/stickers/1.5.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6666 Update pod and deployment requirements
  .spelling
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, size/M

#6684 Spelling and add a tip to using-istio-dashboard
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/index.md
Labels: cla: yes, size/S

#6611 Another clean up for global.mtls.enable
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/multicluster/shared-gateways/index.md
  content/en/docs/setup/install/multicluster/shared-vpn/index.md
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/citadel-config/health-check/index.md
  content/en/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
Labels: area/security, cla: yes, kind/docs, size/M

#6706 Remove deep dive mtls taks.
  content/en/blog/2018/egress-mongo/index.md
  content/en/docs/tasks/security/authentication/mutual-tls/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/faq/security/check-policy.md
  content/en/news/releases/1.0.x/announcing-1.0.3/index.md
Labels: cla: yes, size/L

#6700 Update telemetry with mixer deprecations in config section
  content/en/docs/reference/config/policy-and-telemetry/_index.md
  content/en/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content/en/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/en/docs/reference/config/policy-and-telemetry/mixer-overview/index.md
  content/en/docs/reference/config/telemetry/_index.md
  content/en/docs/reference/config/telemetry/configurable_metrics/index.md
  content/en/docs/reference/config/telemetry/metrics/index.md
Labels: area/policies and telemetry, cla: yes, size/L

#6715 Blog post to be cherrypicked and published immediately with 1.4
  .spelling
  content/en/blog/2020/tradewinds-2020/architecture-post-istiod.svg
  content/en/blog/2020/tradewinds-2020/architecture-pre-istiod.svg
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/news/security/istio-security-2020-003/index.md
Labels: cherrypick/release-1.4, cla: yes, kind/docs, size/L

#6736 Cherrypicked #6715 for immediate publication
  .spelling
  content/en/blog/2020/tradewinds-2020/architecture-post-istiod.svg
  content/en/blog/2020/tradewinds-2020/architecture-pre-istiod.svg
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/news/security/istio-security-2020-003/index.md
Labels: cla: yes, size/L

#6721 Fix issues related to OpenShift setup
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, size/XS

#6731 fix(architecture): remove mixer mentions from architecture doc
  content/en/blog/2019/app-identity-and-access-adapter/index.md
  content/en/docs/ops/deployment/architecture/index.md
Labels: area/policies and telemetry, cla: yes, size/M

#6730 Update Observability ops guide to reflect Mixer nature of tasks
  content/en/docs/ops/common-problems/observability-issues/index.md
Labels: area/policies and telemetry, cla: yes, size/M

#6698 zh-translation: /about/contribute/front-matter/index.md #1770
  content/zh/about/contribute/front-matter/index.md
  content/zh/faq/_index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6702 zh-translation: /blog/2020/multi-cluster-mesh-automation/index.md #1736
  content/zh/blog/2020/istio-agent/index.md
  content/zh/blog/2020/istio-agent/istio_agent.svg
  content/zh/blog/2020/multi-cluster-mesh-automation/Istio_mesh_example.svg
  content/zh/blog/2020/multi-cluster-mesh-automation/Istio_mesh_example_with_admiral.svg
  content/zh/blog/2020/multi-cluster-mesh-automation/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XXL, translation/chinese

#6739 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#6673 Fix pilot -> istiod for config validation docs
  content/en/docs/ops/common-problems/validation/index.md
Labels: cla: yes, size/S

#6547 Update for 1.5 profiles
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/M

#6747 Reweight platform pages
  content/en/docs/setup/platform-setup/MicroK8s/index.md
  content/en/docs/setup/platform-setup/alicloud/index.md
  content/en/docs/setup/platform-setup/azure/index.md
  content/en/docs/setup/platform-setup/docker/index.md
  content/en/docs/setup/platform-setup/gardener/index.md
  content/en/docs/setup/platform-setup/gke/index.md
  content/en/docs/setup/platform-setup/ibm/index.md
  content/en/docs/setup/platform-setup/kind/index.md
  content/en/docs/setup/platform-setup/kubesphere/index.md
  content/en/docs/setup/platform-setup/minikube/index.md
  content/en/docs/setup/platform-setup/oci/index.md
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, size/S

#6732 make update_ref_docs against release_1.5
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/commands/sidecar-injector/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  data/analysis.yaml
Labels: cla: yes, size/XXL

#6725 remove helm upgrade
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
Labels: cla: yes, size/M

#6711 Update architecture diagram to show istiod.
  content/en/docs/ops/deployment/architecture/arch.svg
Labels: cla: yes, kind/docs, size/XS

#6540 Refactor TCP Metrics task for telemetry v2
  content/en/docs/tasks/observability/metrics/tcp-metrics/alpn-based-tunneling-protocol.svg
  content/en/docs/tasks/observability/metrics/tcp-metrics/index.md
Labels: cla: yes, size/L

#6753 [release-1.5] Remove extra profile
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, size/XS

#6689 [Release-1.5] Update trouble shooting for end-user authentication
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: area/security, cla: yes, kind/docs, size/L

#6735 [Release-1.5] Remove mTLS tutorial module
  content/en/docs/examples/microservices-istio/add-istio/index.md
  content/en/docs/examples/microservices-istio/add-mtls/dashboard-ratings-mtls.png
  content/en/docs/examples/microservices-istio/add-mtls/index.md
  content/en/docs/examples/microservices-istio/add-mtls/kiali-mtls.png
  content/en/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
  content/en/docs/examples/microservices-istio/logs-istio/index.md
Labels: cla: yes, kind/docs, size/L

#6741 [Release-1.5] update certmanager part in the telemetry addon doc
  content/en/docs/tasks/observability/gateways/index.md
Labels: cla: yes, size/S

#6748 Expected output includes error message if pod outside mesh
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: cla: yes, size/XS

#6751 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#6613 [Release-1.5] change notes
  .spelling
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
Labels: area/test and release, cla: yes, kind/docs, size/M

#6703 [Release-1.5] update download url to the latest link
  content/en/docs/setup/platform-setup/kubesphere/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S

#6705 [Release-1.5] announcement
  .spelling
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
Labels: cla: yes, kind/docs, size/L

#6719 [Release-1.5] Fix the guide of "Verifying connectivity to Istio Pilot"
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: area/networking, area/security, cla: yes, size/M

#6727 [Release-1.5] Update security concept page for Istio 1.5
  .spelling
  content/en/docs/concepts/security/arch-sec.svg
  content/en/docs/concepts/security/architecture.svg
  content/en/docs/concepts/security/auth.svg
  content/en/docs/concepts/security/authn.svg
  content/en/docs/concepts/security/authz.svg
  content/en/docs/concepts/security/id-prov.svg
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/security/node_agent.svg
Labels: area/security, cla: yes, kind/docs, size/XXL

#6750 [Release-1.5] Update the Installation Options page for Helm
  content/en/docs/reference/config/installation-options/index.md
Labels: cla: yes, size/L

#6755 [release-1.5] Add new security reference docs
  content/en/docs/reference/config/security/jwt/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
Labels: cla: yes, size/XL

#6743 [Release-1.5] Update VM expansion doc
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
Labels: cla: yes, size/L

#6734 [Release-1.5] remove mixer references from egress tasks and deprecate where needed
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: area/networking, area/policies and telemetry, cla: yes, size/M

#6604 [Release-1.5] Update istioctl manifest cni installation option
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: yes, size/S

#6587 [Release-1.5] Remove tasks referring to the deprecated tool
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/faq/security/check-policy.md
Labels: area/security, cla: yes, community/testing days, kind/docs, size/S

#6740 [Release-1.5] Update security feature stages.
  content/en/about/feature-stages/index.md
Labels: area/security, cla: yes, size/S

#6760 v1.5
  data/versions.yml
  scripts/build_archive_site.sh
Labels: cla: yes, kind/docs, needs-ok-to-test, size/XS

#6761 v1.5
  data/args.yml
Labels: cla: yes, kind/docs, needs-ok-to-test, size/XS

#6615 [Release 1.5] Upgrade notice for new authentication APIs
  content/en/about/feature-stages/index.md
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: area/security, cherrypick/release-1.5, cla: yes, kind/docs, size/S

#6770 [release-1.5] [Release 1.5] Upgrade notice for new authentication APIs
  content/en/about/feature-stages/index.md
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: cla: yes, size/S

#6591 [Release-1.5] Delete auto-mTLS task
  content/en/about/feature-stages/index.md
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/docs/reference/config/analysis/ist0113/index.md
  content/en/docs/tasks/security/authentication/auto-mtls/index.md
  content/en/news/releases/1.4.x/announcing-1.4/_index.md
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
Labels: area/security, cherrypick/release-1.5, cla: yes, community/testing days, kind/docs, size/L

#6771 Add WASM blog
  .spelling
  content/en/blog/2020/wasm-announce/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/L

#6773 [release-1.5] Add WASM blog
  .spelling
  content/en/blog/2020/wasm-announce/index.md
Labels: cla: yes, size/L

#6775 Backport script fixes
  src/ts/sidebar.ts
Labels: cla: yes, size/S

#6785 Fix operator image
  static/operator.yaml
Labels: cla: yes, size/XS

#6769 More base release 1.6 stuff - Get pipeline working again
  .spelling
  content/en/docs/ops/common-problems/network-issues/index.md
  content/en/docs/ops/common-problems/observability-issues/index.md
  content/en/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/faq/metrics-and-logs/prometheus-application-metrics.md
  content/en/news/releases/1.0.x/announcing-1.0/index.md
  content/en/news/releases/1.3.x/announcing-1.3/change-notes/index.md
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
  content/en/news/releases/1.6.x/_index.md
  content/en/news/releases/1.6.x/announcing-1.6/_index.md
  content/pt-br/docs/ops/common-problems/observability-issues/index.md
  content/pt-br/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/pt-br/docs/setup/install/helm/index.md
  content/pt-br/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/pt-br/faq/metrics-and-logs/prometheus-application-metrics.md
  content/zh/docs/examples/platform/gke/index.md
  content/zh/docs/ops/common-problems/observability-issues/index.md
  content/zh/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md
  content/zh/faq/metrics-and-logs/prometheus-application-metrics.md
  layouts/_default/baseof.html
  layouts/partials/events.html
Labels: cla: yes, size/L

#6772 [release-1.5] [Release-1.5] Delete auto-mTLS task
  content/en/about/feature-stages/index.md
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/docs/reference/config/analysis/ist0113/index.md
  content/en/docs/tasks/security/authentication/auto-mtls/index.md
  content/en/news/releases/1.4.x/announcing-1.4/_index.md
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
Labels: cla: yes, size/L

#6635 fix(telemetry): add deprecation notices to Mixer tasks
  content/en/docs/tasks/observability/gateways/index.md
  content/en/docs/tasks/observability/metrics/querying-metrics/prometheus_query_result.png
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/index.md
  content/en/docs/tasks/observability/mixer/_index.md
  content/en/docs/tasks/observability/mixer/logs/_index.md
  content/en/docs/tasks/observability/mixer/logs/collecting-logs/index.md
  content/en/docs/tasks/observability/mixer/logs/fluentd/index.md
  content/en/docs/tasks/observability/mixer/metrics/_index.md
  content/en/docs/tasks/observability/mixer/metrics/collecting-metrics/index.md
  content/en/docs/tasks/observability/mixer/metrics/tcp-metrics/index.md
Labels: area/policies and telemetry, cherrypick/release-1.5, cla: yes, size/L

#6784 Add link to Wasm post
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/XS

#6782 remove errant period
  content/en/blog/2020/wasm-announce/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/XS

#6791 [release-1.5] Add link to Wasm post
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
Labels: cla: yes, size/XS

#6794 [release-1.5] remove errant period
  content/en/blog/2020/wasm-announce/index.md
Labels: cla: yes, size/XS

#6754 [Release-1.5] Authz: update TCP task to use tcp-echo
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: area/security, cherrypick/release-1.5, cla: yes, size/L

#6790 [release-1.5] fix(telemetry): add deprecation notices to Mixer tasks
  content/en/docs/tasks/observability/gateways/index.md
  content/en/docs/tasks/observability/metrics/querying-metrics/prometheus_query_result.png
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/index.md
  content/en/docs/tasks/observability/mixer/_index.md
  content/en/docs/tasks/observability/mixer/logs/_index.md
  content/en/docs/tasks/observability/mixer/logs/collecting-logs/index.md
  content/en/docs/tasks/observability/mixer/logs/fluentd/index.md
  content/en/docs/tasks/observability/mixer/metrics/_index.md
  content/en/docs/tasks/observability/mixer/metrics/collecting-metrics/index.md
  content/en/docs/tasks/observability/mixer/metrics/tcp-metrics/index.md
Labels: cla: yes, size/L

#6764 [Release-1.5] Add telemetry v2 with Wasm runtime as experiment feature
  content/en/docs/reference/config/telemetry/telemetry_v2_with_wasm/index.md
Labels: cla: yes, size/S

#6738 Add WebAssembly page.
  .spelling
  content/en/docs/concepts/wasm/extending.svg
  content/en/docs/concepts/wasm/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/M

#6795 Remove MTLS DR from Egress Gateway Task
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: area/networking, cherrypick/release-1.5, cla: yes, kind/docs, size/L

#6793 Add telemetry v2 with Wasm runtime as experiment feature
  content/en/docs/reference/config/telemetry/telemetry_v2_with_wasm/index.md
Labels: cla: yes, size/S

#6798 authz: update the change notes for deny and exclude matching
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
Labels: area/security, cherrypick/release-1.5, cla: yes, size/XS

#6797 [release-1.5] [Release-1.5] Authz: update TCP task to use tcp-echo
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: cla: yes, size/L

#6787 Traffic Mirror cleanup
  content/en/docs/tasks/traffic-management/mirroring/index.md
Labels: area/networking, cherrypick/release-1.5, cla: yes, kind/docs, size/L

#6792 [1.5] fixed link in blog post, fixed typo in relnote template
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/blog/2020/wasm-announce/index.md
  layouts/shortcodes/relnote.html
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/XS

#6800 [release-1.5] Remove MTLS DR from Egress Gateway Task
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: cla: yes, size/L

#6801 [release-1.5] authz: update the change notes for deny and exclude matching
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
Labels: cla: yes, size/XS

#6799 [release-1.5] Add WebAssembly page.
  .spelling
  content/en/docs/concepts/wasm/extending.svg
  content/en/docs/concepts/wasm/index.md
Labels: cla: yes, size/M

#6802 [release-1.5] Traffic Mirror cleanup
  content/en/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes, size/L

#6806 [release-1.5] [1.5] fixed link in blog post, fixed typo in relnote template
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/blog/2020/wasm-announce/index.md
  layouts/shortcodes/relnote.html
Labels: cla: no, size/XS

#6763 [release-1.5] Add note on automatic mutual TLS in the upgrade note
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: cherrypick/release-1.5, cla: yes, size/XS

#6808 [release-1.5] [release-1.5] Add note on automatic mutual TLS in the upgrade note
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: cla: yes, size/XS

#6744 Updated / added Kops documentation
  content/en/docs/setup/platform-setup/kops/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#6809 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#6745 zh-translation: trade winds 2020
  content/zh/blog/2020/tradewinds-2020/architecture-post-istiod.svg
  content/zh/blog/2020/tradewinds-2020/architecture-pre-istiod.svg
  content/zh/blog/2020/tradewinds-2020/index.md
  content/zh/docs/examples/bookinfo-multicluster/index.md
  content/zh/docs/examples/platform/_index.md
  content/zh/docs/examples/platform/endpoints/index.md
  content/zh/docs/examples/platform/gke/index.md
  content/zh/docs/examples/platform/icp/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/XL, translation/chinese

#6746 zh-translate:/content/zh/about/contribute/review/index.md
  content/zh/about/contribute/build/index.md
  content/zh/about/contribute/review/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#6811 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#6776 zh-translation: about contribute build
  content/zh/about/contribute/build/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/M, translation/chinese

#6813 Remove telemetry as it has not been upstreamed
  content/en/blog/2020/wasm-announce/index.md
Labels: cherrypick/release-1.5, cla: yes, size/XS

#6819 replace Citadel with Istio CA
  content/en/docs/tasks/security/plugin-ca-cert/index.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/XS

#6824 [release-1.5] Remove telemetry as it has not been upstreamed
  content/en/blog/2020/wasm-announce/index.md
Labels: cla: yes, size/XS

#6805 Egress TLS Task MTLS cleanup
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: area/networking, cherrypick/release-1.5, cla: yes, kind/docs, size/L

#6827 [release-1.5] Egress TLS Task MTLS cleanup
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: cla: yes, size/L

#6825 [master] replace Citadel with Istio CA
  content/en/docs/tasks/security/plugin-ca-cert/index.md
Labels: cla: no, size/XS

#6796 networking issue section update: disclaimer about auto mtls and remove authn check.
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: cherrypick/release-1.5, cla: yes, size/S

#6814 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#6718 Add lint-fast target for local development
  Makefile.core.mk
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#6828 Manual Cherrypick of #6796
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: cla: yes, size/S

#6829 cacerts secret to replace with istio-ca-secret
  content/en/docs/tasks/security/plugin-ca-cert/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/S

#6832 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#6817 zh-translation: fix some format errors
  content/zh/blog/2019/evolving-istios-apis/index.md
  content/zh/docs/ops/best-practices/traffic-management/index.md
  content/zh/docs/ops/deployment/deployment-models/index.md
  content/zh/faq/general/what-deployment-environment.md
  content/zh/faq/general/what-is-istio.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/S, translation/chinese

#6780 zh-translation:/docs/setup/install/istioctl/index.md
  content/zh/docs/ops/deployment/deployment-models/index.md
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/setup/install/istioctl/index.md
Labels: area/environments, cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/XXL, translation/chinese

#6812 zh-translation: add new blog 2020 wasm-announce
  content/zh/blog/2020/wasm-announce/index.md
  content/zh/docs/reference/config/telemetry/_index.md
  content/zh/docs/reference/config/telemetry/configurable_metrics/index.md
  content/zh/docs/reference/config/telemetry/metrics/index.md
  content/zh/docs/reference/config/telemetry/telemetry_v2_with_wasm/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/L, translation/chinese

#6833 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#6839 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#6836 Revert "cacerts secret to replace with istio-ca-secret"
  content/en/docs/tasks/security/plugin-ca-cert/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S

#6767 authz: update troubleshooting guide for authZ policy
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: area/security, cherrypick/release-1.5, cla: yes, size/M

#6762 fix label name for telemetry v2
  .spelling
  content/en/docs/reference/config/telemetry/metrics/index.md
Labels: cla: yes, size/XS

#6841 [release-1.5] authz: update troubleshooting guide for authZ policy
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: cla: yes, size/M

#6845 edit standard metrics
  content/en/docs/reference/config/telemetry/metrics/index.md
Labels: cla: yes, size/L

#6842 [release-1.5] fix label name for telemetry v2
  .spelling
  content/en/docs/reference/config/telemetry/metrics/index.md
Labels: cla: yes, size/XS

#6858 Cleanup .spelling (lower case istiod not allowed)
  .spelling
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
  content/zh/blog/2020/tradewinds-2020/index.md
  scripts/lint_site.sh
Labels: cherrypick/release-1.5, cla: yes, size/S

#6862 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#6861 Fix OKD link
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
  content/pt-br/docs/setup/additional-setup/sidecar-injection/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/XS

#6863 [release-1.5] Fix OKD link
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
  content/pt-br/docs/setup/additional-setup/sidecar-injection/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, size/XS

#6609 (#6586) move istio.io test for circuit breaking to istio.io repository
  tests/trafficmanagement/circuitbreaker_test.go
  tests/trafficmanagement/scripts/circuitbreaker_test_cleanup.txt
  tests/trafficmanagement/scripts/circuitbreaker_test_setup.txt
  tests/trafficmanagement/scripts/trip_circuitbreaker.txt
Labels: area/test and release, cla: yes, kind/docs, ok-to-test, size/L

#6810 feat(observability): add best practices guide
  .spelling
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/ops/best-practices/observability/production-prometheus.svg
Labels: area/policies and telemetry, cherrypick/release-1.5, cla: yes, size/L

#6865 [release-1.5] feat(observability): add best practices guide
  .spelling
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/ops/best-practices/observability/production-prometheus.svg
Labels: cla: no, size/L

#6864 Remove "Helm with Tiller" install path docs
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/L

#6866 Adding missing istioctl manifest change to 1.5.0 release notes
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
Labels: cherrypick/master, cla: yes, size/XS

#6867 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#6869 Mirror changes from #6864 that didn't cherrypick
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L

#6874 Extensibilty concept section postion wrong
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/wasm/index.md
  content/en/docs/concepts/what-is-istio/index.md
Labels: cherrypick/release-1.5, cla: yes, size/XS

#6875 Manual cherrypick of #6866
  content/en/news/releases/1.5.x/announcing-1.5/change-notes/index.md
Labels: cla: yes, size/XS

#6876 [release-1.5] Extensibilty concept section postion wrong
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/wasm/index.md
  content/en/docs/concepts/what-is-istio/index.md
Labels: cla: yes, size/XS

#6881 Update to the latest istio/istio
  go.mod
  go.sum
  pkg/test/istioio/pod.go
  pkg/test/istioio/script.go
  pkg/test/istioio/subtest.go
  tests/configuration/main_test.go
  tests/examples/main_test.go
  tests/policies/main_test.go
  tests/security/main_test.go
  tests/trafficmanagement/ingress/main_test.go
  tests/trafficmanagement/main_test.go
Labels: cla: yes, size/M

#6886 Remove KubeCon EU event, fix KubeSphere.io links, ignore 429s.
  content/en/docs/setup/platform-setup/kubesphere/index.md
  content/en/events/banners/kubecon-europe-2020.md
  scripts/lint_site.sh
Labels: cherrypick/release-1.5, cla: yes, size/S

#6419 Automator: update istio.io@master reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  data/analysis.yaml
Labels: cla: yes, size/L

#6888 Reword to clarify the intent of external access
  content/en/docs/setup/getting-started/index.md
Labels: area/user experience, cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/S

#6890 [release-1.5] Manual cherry-pick of #6886 - Remove KubeCon EU event, fix KubeSphere.io links, ignore 429s.
  content/en/docs/setup/platform-setup/kubesphere/index.md
  content/en/events/banners/kubecon-europe-2020.md
  scripts/lint_site.sh
Labels: cla: yes, size/S

#6870 Update generated docs script
  scripts/grab_reference_docs.sh
Labels: cherrypick/release-1.5, cla: yes, size/XS
