Repository istio/istio.io, pull requests merged in 2020-04, with the labels that each got.

#7015 [release-1.5] Add Comment about TCP Blackhole Cluster Fix in master/release1.5.1
  content/en/news/releases/1.5.x/announcing-1.5.1/index.md
Labels: cla: yes, size/XS

#7014 Make site linter more configurable
  Makefile.core.mk
  content/zh/blog/2020/istiod/index.md
  scripts/lint_site.sh
Labels: cherrypick/release-1.5, cla: yes, size/L

#7019 Manual cherrypick of #7014
  Makefile.core.mk
  scripts/lint_site.sh
Labels: cla: yes, size/L

#7018 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#7016 Fix TCP Traffic Shifting test script
  tests/trafficmanagement/scripts/tcp_trafficshifting_setup.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_test.txt
Labels: area/test and release, cla: yes, ok-to-test, size/S

#7010 Fix mTLS migration test script
  tests/security/scripts/mtls_migration.txt
Labels: area/test and release, cla: yes, ok-to-test, size/M

#7009 #7008 fix peer 2 request
  content/en/docs/concepts/security/index.md
Labels: cherrypick/release-1.5, cla: yes, ok-to-test, size/XS

#7022 [release-1.5] #7008 fix peer 2 request
  content/en/docs/concepts/security/index.md
Labels: cla: no, size/XS

#6997 Fix privildeged
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/faq/security/verify-mtls-encryption.md
Labels: cherrypick/release-1.5, cla: yes, size/XS

#6972 Rename PKI to Identity Issuance
  content/en/docs/concepts/security/index.md
Labels: cherrypick/release-1.5, cla: no, size/S

#7024 [release-1.5] Rename PKI to Identity Issuance
  content/en/docs/concepts/security/index.md
Labels: cla: no, size/S

#7020 [release-1.5] Update home page links
  content/en/_index.html
Labels: cla: no, size/XS

#7023 [release-1.5] Fix privildeged
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/faq/security/verify-mtls-encryption.md
Labels: cla: no, size/XS

#7012 Add documentation on Ingress support
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
Labels: cherrypick/release-1.5, cla: yes, size/L

#7030 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7028 Suppress brittle link warnings
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#7031 Remove GKE v1.11.x instructions
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: area/environments, cherrypick/master, cla: yes, kind/docs, ok-to-test, size/S

#7036 [master] Remove GKE v1.11.x instructions
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: yes, size/S

#6976 Automator: update istio.io@master reference docs
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/concepts/security/index.md
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/analysis/ist0113/index.md
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking/index.html
  content/en/docs/reference/config/security/istio.authentication.v1alpha1/index.html
  content/en/docs/reference/config/security/istio.rbac.v1alpha1/index.html
  content/en/news/releases/1.2.x/announcing-1.2/change-notes/index.md
  content/en/news/releases/1.3.x/announcing-1.3.8/index.md
  content/en/news/releases/1.4.x/announcing-1.4.4/index.md
  content/en/news/releases/1.4.x/announcing-1.4/_index.md
  content/en/news/releases/1.4.x/announcing-1.4/change-notes/index.md
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
  content/en/news/security/istio-security-2020-001/index.md
Labels: cla: yes, size/XXL

#7033 zh-translation: add content/zh/docs/ops/integrations
  content/zh/docs/ops/integrations/_index.md
  content/zh/docs/ops/integrations/certmanager/index.md
Labels: cla: yes, kind/docs, size/M, translation/chinese

#6982 zh-translation:/docs/concepts/security/index.md
  content/zh/docs/concepts/security/arch-sec.svg
  content/zh/docs/concepts/security/architecture.svg
  content/zh/docs/concepts/security/auth.svg
  content/zh/docs/concepts/security/authn.svg
  content/zh/docs/concepts/security/authz.svg
  content/zh/docs/concepts/security/id-prov.svg
  content/zh/docs/concepts/security/index.md
  content/zh/docs/concepts/security/node_agent.svg
  content/zh/docs/reference/glossary/istiod.md
Labels: cla: yes, kind/docs, ok-to-test, size/XL, translation/chinese

#7005 zh-translation: remove /docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-certmgr/index.md
  content/zh/news/releases/1.1.x/announcing-1.1/change-notes/index.md
  content/zh/news/releases/1.1.x/announcing-1.1/upgrade-notes/index.md
Labels: cla: yes, kind/docs, size/L, translation/chinese

#7037 zh-translation: move and update /docs/tasks/security/plugin-ca-cert/index.md
  content/zh/about/feature-stages/index.md
  content/zh/blog/2020/istiod/index.md
  content/zh/docs/examples/virtual-machines/multi-network/index.md
  content/zh/docs/examples/virtual-machines/single-network/index.md
  content/zh/docs/setup/install/multicluster/gateways/index.md
  content/zh/docs/setup/install/multicluster/shared-vpn/index.md
  content/zh/docs/tasks/security/citadel-config/plugin-ca-cert/index.md
  content/zh/docs/tasks/security/plugin-ca-cert/index.md
  content/zh/news/releases/0.x/announcing-0.5/index.md
Labels: cla: yes, kind/docs, size/L, translation/chinese

#7042 zh-translation: remove /docs/tasks/security/citadel-config/health-check/index.md
  content/zh/docs/tasks/security/citadel-config/health-check/index.md
  content/zh/news/releases/0.x/announcing-0.6/index.md
Labels: cla: yes, size/M, translation/chinese

#7045 zh-translation: remove /docs/tasks/security/citadel-config/ca-namespace-targeting/index.md
  content/zh/docs/tasks/security/citadel-config/ca-namespace-targeting/index.md
Labels: cla: yes, size/L, translation/chinese

#7039 Update base64 -d to --decode
  content/en/docs/setup/platform-setup/kind/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
Labels: cherrypick/release-1.5, cla: yes, size/XS

#7038 Update sed to include space before boolen value
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
Labels: area/user experience, cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/XS

#7048 [release-1.5] Update sed to include space before boolen value
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
Labels: cla: yes, size/XS

#7041 zh-translation:concepts/security/index.md
  content/zh/docs/concepts/security/arch-sec.svg
  content/zh/docs/concepts/security/authn.svg
  content/zh/docs/concepts/security/authz.svg
  content/zh/docs/concepts/security/id-prov.svg
  content/zh/docs/concepts/security/index.md
  content/zh/docs/reference/glossary/istiod.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/XL, translation/chinese

#7047 [release-1.5] Update base64 -d to --decode
  content/en/docs/setup/platform-setup/kind/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
Labels: cla: yes, size/XS

#7049 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#7050 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7052 Document app protocol
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: cla: yes, size/S

#7057 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7058 zh-translation: remove /docs/tasks/security/citadel-config/auth-sds/index.md
  content/zh/about/feature-stages/index.md
  content/zh/docs/setup/additional-setup/config-profiles/index.md
  content/zh/docs/tasks/security/authorization/authz-td-migration/index.md
  content/zh/docs/tasks/security/citadel-config/auth-sds/index.md
  content/zh/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: cla: yes, kind/docs, size/L, translation/chinese

#7065 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#7066 zh-translation: add /docs/tasks/security/authorization/authz-jwt/index.md
  content/zh/docs/tasks/security/authorization/authz-jwt/index.md
  content/zh/docs/tasks/security/authorization/rbac-groups/index.md
  content/zh/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: cla: yes, size/L, translation/chinese

#7046 Run examples tests under the demo profile
  tests/examples/bookinfo_test.go
  tests/examples/main_test.go
Labels: area/test and release, cla: yes, ok-to-test, size/S

#7056 fix yaml indent in docs/concepts/security
  content/en/docs/concepts/security/index.md
  content/zh/docs/concepts/security/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7059 Fixing incorrect quote type in istio-authorization blog post
  content/en/blog/2018/istio-authorization/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, needs-ok-to-test, size/XS

#7035 Initial documentation on Multiple Control Planes
  content/en/blog/2020/multiple-control-planes/index.md
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, size/M

#7060 translate getting-started page to brazilian portuguese pt-br
  content/pt-br/docs/setup/getting-started/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/L, translation/pt-br

#7071 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7043 Fix flaky circuit breaker test
  tests/trafficmanagement/circuitbreaker_test.go
  tests/trafficmanagement/scripts/trip_circuitbreaker.txt
Labels: area/test and release, cla: yes, ok-to-test, size/M

#7076 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7044 Generate test snippets from md files POC
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  pkg/test/istioio/script.go
  scripts/gen_snips.sh
  scripts/snip.py
  tests/trafficmanagement/scripts/traffic_shifting.txt
Labels: cla: yes, size/L

#7075 Allow specifying ADDITIONAL_CONTAINER_OPTIONS to help running tests locally
  Makefile.overrides.mk
Labels: cla: yes, size/XS

#7068 Add a Remove retired documentation section
  content/en/about/contribute/code-blocks/index.md
  content/en/about/contribute/diagrams/index.md
  content/en/about/contribute/formatting/index.md
  content/en/about/contribute/front-matter/index.md
  content/en/about/contribute/remove-content/index.md
  content/en/about/contribute/remove-content/remove-documentation.svg
  content/en/about/contribute/review/index.md
  content/en/about/contribute/shortcodes/index.md
  content/en/about/contribute/style-guide/index.md
  content/en/about/contribute/terminology/index.md
Labels: cla: yes, size/M

#7079 Add some clean targets that are already in the .gitignore
  Makefile.core.mk
Labels: cla: yes, size/XS

#7025 Refactor Secure Ingress tasks
  content/en/about/feature-stages/index.md
  content/en/docs/tasks/observability/gateways/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress-mount/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/faq/security/secure-ingress.md
  content/en/news/releases/1.2.x/announcing-1.2/change-notes/index.md
  content/en/news/releases/1.3.x/announcing-1.3/change-notes/index.md
Labels: cla: yes, size/XL

#7078 Ignore copied tests/integration directory
  .gitignore
Labels: cla: yes, ok-to-test, size/XS

#7070 Add grafana integration docs
  content/en/docs/ops/integrations/grafana/index.md
Labels: cla: yes, size/M

#7051 Remove Aporeto as a partner
  content/en/about/community/partners/aporeto.svg
  content/en/about/community/partners/index.md
Labels: cla: yes, size/XS

#7073 zh-translation: remove /docs/tasks/security/authentication/mutual-tls/index.md
  content/zh/blog/2018/egress-mongo/index.md
  content/zh/docs/tasks/security/authentication/mutual-tls/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/news/releases/1.0.x/announcing-1.0.3/index.md
Labels: cla: yes, size/L, translation/chinese

#7080 Update doc test README
  Makefile.core.mk
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  scripts/gen_snips.sh
  tests/README.md
  tests/security/mtls_migration_test.go
  tests/security/scripts/mtls_migration.txt
  tests/trafficmanagement/scripts/traffic_shifting.txt
Labels: cla: yes, size/L

#7054 uniform tracing header format
  content/en/faq/distributed-tracing/how-to-support-tracing.md
Labels: cla: yes, kind/docs, size/XS

#7091 zh-translation: /faq/security/https-overlay.md
  content/zh/faq/security/https-overlay.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#7088 zh-translation: /docs/reference/glossary/secure-naming.md
  content/zh/docs/reference/glossary/secure-naming.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#7086 zh-translation: /docs/reference/glossary/service-name.md
  content/zh/docs/reference/glossary/service-name.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#7087 zh-translation: /docs/reference/glossary/mixer-instance.md
  content/zh/docs/reference/glossary/mixer-instance.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#7084 Snip regen
  Makefile.core.mk
  tests/README.md
Labels: cla: yes, size/M

#7083 Remove Helm install instructions
  content/en/about/feature-stages/index.md
  content/en/blog/2018/incremental-traffic-management/index.md
  content/en/blog/2019/introducing-istio-operator/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/upgrade/cni-helm-upgrade/index.md
  content/en/faq/distributed-tracing/minimal-requirements.md
  content/en/news/releases/0.x/announcing-0.7/index.md
  content/en/news/releases/1.0.x/announcing-1.0/index.md
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
  content/en/news/security/istio-security-2019-005/index.md
Labels: cla: yes, size/L

#7069 Use standard ports for telemetry exposure
  content/en/docs/ops/deployment/requirements/index.md
  content/en/docs/tasks/observability/gateways/index.md
Labels: cla: yes, size/L

#7093 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7092 added a blog on using an external api gateway with istio 1.5 and SDS
  .spelling
  content/en/blog/2020/istio-sds-gloo/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/S

#7096 Fix all links with doc relative path in glossary directory
  content/zh/docs/reference/glossary/adapters.md
  content/zh/docs/reference/glossary/data-plane.md
  content/zh/docs/reference/glossary/destination.md
  content/zh/docs/reference/glossary/envoy.md
  content/zh/docs/reference/glossary/mixer-handler.md
  content/zh/docs/reference/glossary/mixer.md
  content/zh/docs/reference/glossary/pilot.md
  content/zh/docs/reference/glossary/pod.md
  content/zh/docs/reference/glossary/service-consumer.md
  content/zh/docs/reference/glossary/service-endpoint.md
  content/zh/docs/reference/glossary/service-mesh.md
  content/zh/docs/reference/glossary/service-name.md
  content/zh/docs/reference/glossary/service-operator.md
  content/zh/docs/reference/glossary/service-producer.md
  content/zh/docs/reference/glossary/service-registry.md
  content/zh/docs/reference/glossary/service-version.md
  content/zh/docs/reference/glossary/service.md
  content/zh/docs/reference/glossary/source.md
  content/zh/docs/reference/glossary/workload-instance.md
  content/zh/docs/reference/glossary/workload.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/M, translation/chinese

#7094 [release-1.5] added a blog on using an external api gateway with istio 1.5 and SDS
  .spelling
  content/en/blog/2020/istio-sds-gloo/index.md
Labels: cla: no, size/S

#7098 Pass utf-8 encoding as a param to opening md files
  scripts/snip.py
Labels: area/test and release, area/user experience, cla: yes, ok-to-test, size/XS

#7085 User guide tests and remove manual steps for plugging in CA cert
  content/en/docs/tasks/security/plugin-ca-cert/index.md
  content/en/docs/tasks/security/plugin-ca-cert/snips.sh
  go.mod
  go.sum
  tests/security/plugin_ca_cert/main_test.go
  tests/security/plugin_ca_cert/plugin_ca_cert_test.go
  tests/security/plugin_ca_cert/scripts/plugin_ca_cert.txt
Labels: area/security, cla: yes, size/L

#7100 Document check for lint errors in generated snip.sh files
  tests/README.md
Labels: cla: yes, size/S

#7102 zh-translation: egress gateway
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: cla: yes, size/L, translation/chinese

#7105 Fix code in 'Authorization for TCP traffic'
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7108 Fix doc 'Using the Istioctl Command-line Tool'
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7110 Add built-in verify functions to test framework
  pkg/test/istioio/script.go
  tests/README.md
  tests/security/plugin_ca_cert/scripts/plugin_ca_cert.txt
  tests/security/scripts/mtls_migration.txt
  tests/trafficmanagement/scripts/traffic_shifting.txt
  tests/util/verify.sh
Labels: cla: yes, size/L

#7103 User guide tests for DNS certificate management
  content/en/docs/tasks/security/dns-cert/index.md
  content/en/docs/tasks/security/dns-cert/snips.sh
  tests/security/dns_cert/dns_cert_test.go
  tests/security/dns_cert/main_test.go
  tests/security/dns_cert/scripts/dns_cert.txt
Labels: area/security, cla: yes, size/L

#7106 Retire helm documentation as we use a protobuf
  content/en/blog/2019/performance-best-practices/index.md
  content/en/docs/ops/configuration/mesh/secret-creation/index.md
  content/en/docs/reference/config/installation-options/index.md
  content/en/docs/reference/config/policy-and-telemetry/mixer-overview/index.md
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/news/releases/1.2.x/announcing-1.2/change-notes/index.md
  content/en/news/security/istio-security-2019-006/index.md
  scripts/tablegen.py
  scripts/tablegen_diff.py
Labels: cla: yes, size/XXL

#7114 Fix doc 'Traffic Management'
  content/en/docs/concepts/traffic-management/index.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/XS

#7115 Notes on testing
  tests/README.md
Labels: cla: yes, size/S

#7116 [master] Fix doc 'Using the Istioctl Command-line Tool'
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: cla: no, size/XS

#7117 [master] Fix code in 'Authorization for TCP traffic'
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: cla: no, size/XS

#7118 [master] Fix doc in 'Egress Gateways with TLS Origination'
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: cla: no, size/XS

#7119 [master] Fix doc 'Traffic Management'
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: no, size/XS

#7099 Use correct binary name when downloading istioctl
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/pt-br/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7120 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/M

#7113 add proxy repo to scrap docs from
  content/en/docs/reference/config/proxy_extensions/_index.md
  content/en/docs/reference/config/proxy_extensions/metadata_exchange/index.html
  content/en/docs/reference/config/proxy_extensions/stackdriver/index.html
  content/en/docs/reference/config/proxy_extensions/stats/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/L

#6660 Add test for Request Timeouts
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  tests/common/scripts/bookinfo.txt
  tests/trafficmanagement/request_timeouts_test.go
  tests/trafficmanagement/scripts/request_timeouts.txt
  tests/trafficmanagement/scripts/request_timeouts_delay.txt
Labels: area/test and release, cla: no, ok-to-test, size/L

#7126 Convert health check test to new model
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
  tests/README.md
  tests/configuration/scripts/cleanup.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_command.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_annotations.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_globally.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_separate_port.txt
Labels: cla: yes, size/L

#7127 Convert bookinfo test to new model
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/bookinfo/snips.sh
  tests/examples/scripts/bookinfo.txt
  tests/util/verify.sh
Labels: cla: yes, size/L

#7128 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7134 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#7131 Convert TCP traffic shifting test
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  content/en/docs/tasks/security/dns-cert/snips.sh
  content/en/docs/tasks/security/plugin-ca-cert/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  scripts/snip.py
  tests/trafficmanagement/scripts/tcp_trafficshifting_cleanup.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_setup.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_test.txt
  tests/util/verify.sh
Labels: cla: yes, size/L

#7136 Fix for running user guide tests
  tests/README.md
Labels: area/test and release, cla: yes, size/XS

#7139 Fix typo in https://istio.io/docs/reference/config/analysis/ist0118/
  content/en/docs/reference/config/analysis/ist0118/index.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/XS

#7132 Fix reference docs: galley cmd removed
  scripts/grab_reference_docs.sh
Labels: cla: yes, kind/docs, size/XS

#7122 Add docs for experimental tracing configuration
  content/en/about/feature-stages/index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
  content/en/faq/distributed-tracing/control-sampling.md
  content/en/faq/distributed-tracing/no-tracing.md
  content/en/news/releases/1.0.x/announcing-1.0.3/index.md
Labels: area/policies and telemetry, cla: yes, size/L

#7101 Add documentation for adding sidecar injector webhook annotations in 1.4
  content/en/docs/setup/additional-setup/cni/index.md
Labels: area/environments, area/test and release, cherrypick/release-1.5, cla: yes, do-not-merge, size/M

#7121 Release notes for 1.4.8
  content/en/news/releases/1.4.x/announcing-1.4.8/index.md
Labels: cherrypick/release-1.5, cla: yes, size/S

#7140 [release-1.5] Add documentation for adding sidecar injector webhook annotations in 1.4
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: no, size/M

#7141 [release-1.5] Release notes for 1.4.8
  content/en/news/releases/1.4.x/announcing-1.4.8/index.md
Labels: cla: no, size/S

#7142 Fix cleanup to delete authorization policy
  content/en/docs/tasks/security/authentication/authn-policy/index.md
Labels: cla: yes, size/XS

#7130 Adding release notes for 1.5.2
  content/en/news/releases/1.5.x/announcing-1.5.2/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/M

#7144 Clarify wording for openshift installs
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, size/XS

#7143 [release-1.5] Adding release notes for 1.5.2
  content/en/news/releases/1.5.x/announcing-1.5.2/index.md
  data/args.yml
Labels: cla: yes, size/M

#7147 [release-1.5] Clarify wording for openshift installs
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: no, size/XS

#7151 Uninstall: add note about removal of istio-system ns
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#7153 Partial convert mirror test to new model
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  content/en/docs/tasks/security/dns-cert/snips.sh
  content/en/docs/tasks/security/plugin-ca-cert/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  scripts/snip.py
  tests/trafficmanagement/mirror_test.go
Labels: cla: yes, size/L

#7125 zh-translation: /docs/faq/security/verify-mtls-encryption.md
  content/zh/faq/security/verify-mtls-encryption.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#7167 minikube updates
  content/en/docs/setup/platform-setup/minikube/index.md
Labels: cla: yes, size/S

#7163 Update IBM Cloud instructions
  content/en/docs/setup/platform-setup/ibm/index.md
Labels: cla: yes, size/XS

#7164 Update kind setup instructions removing Golang version
  content/en/docs/setup/platform-setup/kind/index.md
Labels: cla: yes, size/XS

#7160 Update supported releases
  data/args.yml
Labels: cla: yes, size/XS

#7161 Reorder uninstall putting Bookinfo sample first.
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/XS

#7165 Update standalone operator docs
  content/en/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, size/XS

#7166 Update istioctl install docs
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#7169 remove self signed in multi cluster shared cp example
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: cla: yes, size/XS

#7123 Updated Lightstep topic with new Lighstep brand and products
  .spelling
  content/en/docs/concepts/observability/index.md
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/istio-explorer.png
  content/en/docs/tasks/observability/distributed-tracing/lightstep/istio-services.png
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
  content/en/faq/distributed-tracing/how-distributed-tracing-works.md
  content/en/faq/distributed-tracing/how-envoy-based-tracing-works.md
  content/en/faq/distributed-tracing/how-to-support-tracing.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: cla: no, kind/docs, ok-to-test, size/M

#7172 lint_site.sh: Don't print error if "public" directory doesn't exist.
  scripts/lint_site.sh
Labels: area/test and release, cla: yes, size/M

#7170 Update links
  content/en/docs/setup/install/multicluster/gateways/index.md
Labels: cla: yes, size/XS

#7175 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#7171 Manual ref doc update from release 1.6 with galley removed.
  content/en/docs/concepts/observability/index.md
  content/en/docs/reference/commands/galley/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/attributegen/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/proxy_extensions/stats/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/news/releases/1.2.x/announcing-1.2/change-notes/index.md
  data/analysis.yaml
Labels: cla: yes, size/XXL

#7159 add tuya logo
  content/en/about/community/customers/index.md
  content/en/about/community/customers/tuya.png
Labels: area/user experience, cla: yes, ok-to-test, size/XS

#7137 Add docs for Customizing Istio Metrics
  content/en/docs/reference/config/telemetry/configurable_metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: area/policies and telemetry, cla: yes, kind/docs, size/L

#7177 Update upgrade instructions
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, size/M

#7178 Use `sniHosts` instead of `sni_hosts` in examples
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
Labels: area/networking, cherrypick/release-1.5, cla: yes, size/S

#7133 Update lint_site to only check languages for files in current PR
  Makefile.core.mk
  scripts/lint_site.sh
Labels: cla: yes, size/S

#7179 [release-1.5] Use `sniHosts` instead of `sni_hosts` in examples
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
Labels: cla: no, cla: yes, size/S

#7181 Fix removed folder reference
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/XS

#7182 Update install output
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/S

#7185 Revert "Update lint_site to only check languages for files in current PR"
  Makefile.core.mk
  scripts/lint_site.sh
Labels: cla: yes, size/S

#7183 Another Manual doc update
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/proxy_extensions/accesslogpolicy/index.html
  content/en/docs/reference/config/proxy_extensions/attributegen/index.html
  content/en/docs/reference/config/proxy_extensions/metadata_exchange/index.html
  content/en/docs/reference/config/proxy_extensions/stackdriver/index.html
Labels: cla: yes, size/L

#7180 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7150 Add docs for Classifying Metrics Based on Request or Response
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: cla: yes, size/L

#7187 Add namespace to gateway yaml for consistency
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#7189 cleanup a few of of the commands in egress examples
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: cla: yes, kind/docs, size/XS

#7191 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/proxy_extensions/metadata_exchange.html./index.html
Labels: cla: yes, size/L

#7193 Fix format for warning message
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: cla: yes, size/XS

#7188 account for istiod scenario when troubleshooting mutatingwebhooks
  content/en/docs/ops/common-problems/injection/index.md
Labels: cla: yes, kind/docs, size/S

#7198 Update Authentication page
  content/en/docs/tasks/security/authentication/authn-policy/index.md
Labels: cla: yes, size/XS

#7207 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS
