Repository istio/istio.io, pull requests merged in 2020-12, with the labels that each got.

#8597 Test for external control plane doc
  content/en/docs/setup/additional-setup/external-controlplane/index.md
  content/en/docs/setup/additional-setup/external-controlplane/snips.sh
  content/en/docs/setup/additional-setup/external-controlplane/test.sh
Labels: cherrypick/release-1.8, cla: yes, size/L

#8606 [release-1.8] Test for external control plane doc
  content/en/docs/setup/additional-setup/external-controlplane/index.md
  content/en/docs/setup/additional-setup/external-controlplane/snips.sh
  content/en/docs/setup/additional-setup/external-controlplane/test.sh
Labels: cla: yes, release-notes-none, size/L

#8509 Small update to clarify the mirror flow
  content/en/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes, ok-to-test, size/XS

#8610 fix incorrect uninstall command.
  content/en/docs/setup/upgrade/gateways/index.md
Labels: area/environments, cherrypick/release-1.8, cla: yes, kind/docs, size/XS

#8612 [release-1.8] fix incorrect uninstall command.
  content/en/docs/setup/upgrade/gateways/index.md
Labels: cla: yes, release-notes-none, size/XS

#8589 update canary upgrade doc for in-cluster operator.
  content/en/docs/setup/install/operator/index.md
Labels: area/environments, cherrypick/release-1.8, cla: yes, kind/docs, size/M

#8614 Automator: update common-files@release-1.7 in istio/istio.io@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8613 [release-1.8] update canary upgrade doc for in-cluster operator.
  content/en/docs/setup/install/operator/index.md
Labels: cla: no, release-notes-none, size/M

#8615 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8497 Add documentation for experimental service APIs integration
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cherrypick/release-1.8, cla: yes, size/L

#8616 [release-1.8] Add documentation for experimental service APIs integration
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cla: no, release-notes-none, size/L

#8617 Reorder ingress tasks
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cherrypick/release-1.8, cla: yes, size/S

#8618 [release-1.8] Reorder ingress tasks
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cla: no, release-notes-none, size/S

#8611 Use minimal profile instead of default
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/upgrade/gateways/index.md
Labels: area/environments, cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8625 [release-1.8] Use minimal profile instead of default
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/upgrade/gateways/index.md
Labels: cla: no, release-notes-none, size/S

#8626 [release-1.8] Remove Mixer related content from FAQ.
  content/en/faq/distributed-tracing/disabling-tracing.md
  content/en/faq/distributed-tracing/how-distributed-tracing-works.md
  content/en/faq/distributed-tracing/how-mixer-based-tracing-works.md
  content/en/faq/distributed-tracing/mixer-role.md
  content/en/faq/distributed-tracing/why-mixer-spans.md
  content/en/faq/metrics-and-logs/controlling-what-the-sidecar-reports.md
  content/en/faq/metrics-and-logs/life-of-a-request.md
  content/en/faq/metrics-and-logs/prometheus-for-non-k8s.md
Labels: cla: yes, release-notes-none, size/M

#8630 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8624 zh-retranslation:content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/install/helm/index.md
Labels: cla: yes, kind/docs, size/L, translation/chinese

#8633 zh-translation: docs/setup/install/virtual-machine/index.md
  content/zh/docs/setup/install/virtual-machine/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/L, translation/chinese

#8634 [release-1.8] zh-translation: docs/setup/install/virtual-machine/index.md
  content/zh/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, release-notes-none, size/L

#8627 Add blog about docker hub rate limit
  .spelling
  content/en/blog/2020/docker-rate-limit/index.md
Labels: cherrypick/release-1.8, cla: yes, size/M

#8635 [release-1.8] Add blog about docker hub rate limit
  .spelling
  content/en/blog/2020/docker-rate-limit/index.md
Labels: cla: no, release-notes-none, size/M

#8637 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8609 Created a blog about IstioCon 2021
  .spelling
  content/en/blog/2020/istiocon-2021/index.md
  content/en/blog/2020/istiocon-2021/istioconlogo.jpg
Labels: cherrypick/release-1.8, cla: yes, kind/docs, ok-to-test, size/S

#8640 [release-1.8] Created a blog about IstioCon 2021
  .spelling
  content/en/blog/2020/istiocon-2021/index.md
  content/en/blog/2020/istiocon-2021/istioconlogo.jpg
Labels: cla: no, release-notes-none, size/S

#8638 Add a special upgrade notice for 1.7.5
  .spelling
  content/en/news/releases/1.7.x/announcing-1.7.5/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/XS

#8639 release notes for 1.8.1
  content/en/news/releases/1.8.x/announcing-1.8.1/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8641 [release-1.8] Add a special upgrade notice for 1.7.5
  .spelling
  content/en/news/releases/1.7.x/announcing-1.7.5/index.md
Labels: cla: yes, release-notes-none, size/XS

#8642 [release-1.8] release notes for 1.8.1
  content/en/news/releases/1.8.x/announcing-1.8.1/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/M

#8636 Release notes for 1.7.6
  content/en/news/releases/1.7.x/announcing-1.7.6/index.md
Labels: area/test and release, cherrypick/release-1.8, cla: yes, size/S

#8645 Fix operator installation with --watchedNamespaces
  content/en/docs/setup/install/operator/index.md
Labels: cherrypick/release-1.8, cla: yes, size/S

#8646 [release-1.8] Fix operator installation with --watchedNamespaces
  content/en/docs/setup/install/operator/index.md
Labels: cla: no, release-notes-none, size/S

#8643 [release-1.8] Release notes for 1.7.6
  content/en/news/releases/1.7.x/announcing-1.7.6/index.md
Labels: cla: yes, release-notes-none, size/S

#8649 Update supported versions without known CVEs
  content/en/about/supported-releases/index.md
Labels: cla: yes, kind/docs, size/XS

#8652 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8526 Blog about how to expose client IP through the stack of NLB and istio
  content/en/blog/2020/show-source-ip/aws-proxy-protocol.png
  content/en/blog/2020/show-source-ip/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, ok-to-test, size/L

#8653 [release-1.8] Blog about how to expose client IP through the stack of NLB and istio
  content/en/blog/2020/show-source-ip/aws-proxy-protocol.png
  content/en/blog/2020/show-source-ip/index.md
Labels: cla: no, release-notes-none, size/L

#8650 [release-1.8] Update supported versions without known CVEs
  content/en/about/supported-releases/index.md
Labels: cla: no, release-notes-none, size/XS

#8658 fix incorrect security configuration for mtls.
  content/en/faq/security/mysql-with-mtls.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8659 [release-1.8] fix incorrect security configuration for mtls.
  content/en/faq/security/mysql-with-mtls.md
Labels: cla: yes, release-notes-none, size/S

#8662 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8660 Update istio.io/istio reference to 1.7.6
  go.mod
  go.sum
Labels: cla: yes, size/S

#8661 Update istio.io/istio reference to 1.8.1
  go.mod
  go.sum
Labels: cla: yes, size/S

#8663 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8664 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8654 keep meshID untouched for external cp test
  content/en/docs/setup/additional-setup/external-controlplane/test.sh
Labels: cla: yes, size/XS

#8656 clarifying VM installations for multi-cluster meshes
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cherrypick/release-1.8, cla: yes, needs-ok-to-test, size/XS

#8667 [release-1.8] clarifying VM installations for multi-cluster meshes
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: no, release-notes-none, size/XS

#8669 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8673 Some traffic management doc fixes
  content/en/docs/ops/best-practices/traffic-management/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: cla: yes, size/S

#8423 On Demand Egress Gateways post
  .spelling
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/index.md
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/proxying-legacy-services-using-egress-gateways-authz.svg
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/proxying-legacy-services-using-egress-gateways-communication.svg
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/proxying-legacy-services-using-egress-gateways-overview.svg
Labels: cherrypick/release-1.8, cla: yes, ok-to-test, size/XL

#8675 [release-1.8] manual cherrypick of #8423
  .spelling
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/index.md
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/proxying-legacy-services-using-egress-gateways-authz.svg
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/proxying-legacy-services-using-egress-gateways-communication.svg
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/proxying-legacy-services-using-egress-gateways-overview.svg
Labels: cla: yes, size/XL

#8677 Clarify env variable values
  content/en/docs/setup/additional-setup/external-controlplane/index.md
  content/en/docs/setup/additional-setup/external-controlplane/snips.sh
  content/en/docs/setup/install/multicluster/before-you-begin/index.md
Labels: cla: yes, size/M

#8680 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8670 zh-retranslation: docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/istioctl/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/XL, translation/chinese

#8681 [release-1.8] zh-retranslation: docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/istioctl/index.md
Labels: cla: yes, release-notes-none, size/XL

#8683 use right tick to indicate components installed
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: area/user experience, cla: yes, size/XS

#8679 Fix wrong link for Control Ingress Traffic task
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: cla: yes, size/XS

#8689 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8690 Fix istio-sidecar install doc error
  content/en/docs/setup/install/virtual-machine/index.md
  content/zh/docs/setup/install/virtual-machine/index.md
Labels: area/environments, cla: yes, kind/docs, size/XS

#8691 Small grammar corrections
  content/en/docs/ops/integrations/_index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: cla: yes, size/XS

#8692 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8696 zh-translation: glossary for Install Multicluster
  content/zh/docs/reference/glossary/primary-cluster.md
  content/zh/docs/reference/glossary/remote-cluster.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S, translation/chinese

#8694 zh-translation: docs/setup/install/multicluster/before-you-begin/index.md
  content/zh/docs/setup/install/multicluster/before-you-begin/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/M, translation/chinese

#8697 [release-1.8] zh-translation: glossary for Install Multicluster
  content/zh/docs/reference/glossary/primary-cluster.md
  content/zh/docs/reference/glossary/remote-cluster.md
Labels: cla: yes, release-notes-none, size/S, translation/chinese

#8698 [release-1.8] zh-translation: docs/setup/install/multicluster/before-you-begin/index.md
  content/zh/docs/setup/install/multicluster/before-you-begin/index.md
Labels: cla: yes, release-notes-none, size/M, translation/chinese

#8701 zh-translation: install multi-primary
  content/zh/docs/setup/install/multicluster/multi-primary/arch.svg
  content/zh/docs/setup/install/multicluster/multi-primary/index.md
  content/zh/docs/setup/install/multicluster/multi-primary/snips.sh
  content/zh/docs/setup/install/multicluster/multi-primary/test.sh
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/L, translation/chinese

#8702 [release-1.8] zh-translation: install multi-primary
  content/zh/docs/setup/install/multicluster/multi-primary/arch.svg
  content/zh/docs/setup/install/multicluster/multi-primary/index.md
  content/zh/docs/setup/install/multicluster/multi-primary/snips.sh
  content/zh/docs/setup/install/multicluster/multi-primary/test.sh
Labels: cla: yes, release-notes-none, size/L

#8703 zh-translation: install primary-remote & multi-primary_multi-network & primary-remote_multi-network
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/arch.svg
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/test.sh
  content/zh/docs/setup/install/multicluster/primary-remote/arch.svg
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote/snips.sh
  content/zh/docs/setup/install/multicluster/primary-remote/test.sh
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/arch.svg
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/test.sh
Labels: cherrypick/release-1.8, cla: yes, size/XXL, translation/chinese

#8705 [release-1.8] zh-translation: install primary-remote & multi-primary_multi-network & primary-remote_multi-network
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/arch.svg
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/test.sh
  content/zh/docs/setup/install/multicluster/primary-remote/arch.svg
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote/snips.sh
  content/zh/docs/setup/install/multicluster/primary-remote/test.sh
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/arch.svg
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/test.sh
Labels: cla: yes, release-notes-none, size/XXL

#8706 zh-translation: multicluster-index & multicluster-verify
  content/zh/docs/setup/install/multicluster/_index.md
  content/zh/docs/setup/install/multicluster/common.sh
  content/zh/docs/setup/install/multicluster/verify/index.md
  content/zh/docs/setup/install/multicluster/verify/snips.sh
Labels: cherrypick/release-1.8, cla: yes, size/L, translation/chinese

#8709 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8707 [release-1.8] zh-translation: multicluster-index & multicluster-verify
  content/zh/docs/setup/install/multicluster/_index.md
  content/zh/docs/setup/install/multicluster/common.sh
  content/zh/docs/setup/install/multicluster/verify/index.md
  content/zh/docs/setup/install/multicluster/verify/snips.sh
Labels: cla: yes, release-notes-none, size/L

#8708 zh-translation: Cleaning up obsolete files in multicluster install
  content/zh/docs/setup/install/multicluster/gateways/index.md
  content/zh/docs/setup/install/multicluster/gateways/multicluster-with-gateways.svg
  content/zh/docs/setup/install/multicluster/shared-gateways/diagram.svg
  content/zh/docs/setup/install/multicluster/shared-gateways/index.md
  content/zh/docs/setup/install/multicluster/shared-vpn/index.md
  content/zh/docs/setup/install/multicluster/shared-vpn/multicluster-with-vpn.svg
  content/zh/docs/setup/install/multicluster/simplified/index.md
Labels: cla: yes, size/XXL, translation/chinese

#8713 zh-translation: remove standalone-operator from install
  content/zh/docs/setup/install/_index.md
  content/zh/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, size/L, translation/chinese

#8717 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M
