Repository istio/istio.io, pull requests merged in 2020-08, with the labels that each got.

#7835 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#7836 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7838 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#7837 Update Tetrate Logo
  content/en/about/community/partners/tetrate.png
Labels: cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/XS

#7846 [release-1.6] Update Tetrate Logo
  content/en/about/community/partners/tetrate.png
Labels: cla: yes, release-notes-none, size/XS

#7852 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/M

#7858 Fix typo for deployment mode chapter
  content/zh/docs/ops/deployment/deployment-models/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7864 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7851 Add missing var declaration
  content/en/docs/examples/virtual-machines/single-network/index.md
Labels: cla: yes, size/XS

#7856 remove duplicate =
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/XS

#7832 Egress Gateway Automated Doc Test
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh
Labels: cla: yes, size/XL

#7841 Remove 'Secret Creation' operation
  DOC_OWNERS.md
  content/en/docs/ops/configuration/mesh/secret-creation/index.md
Labels: cla: yes, size/M

#7850 Fix spelling
  content/en/docs/reference/config/analysis/_index.md
Labels: cla: yes, size/XS

#7843 Syntax for --log_output_level; remove ref to Galley and Citadel, de-emphasize Mixer
  content/en/docs/ops/diagnostic-tools/component-logging/index.md
Labels: cla: yes, size/S

#7867 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7847 Do not explicitly set addon namespace
  content/en/docs/ops/integrations/grafana/index.md
  content/en/docs/ops/integrations/jaeger/index.md
  content/en/docs/ops/integrations/kiali/index.md
  content/en/docs/ops/integrations/prometheus/index.md
  content/en/docs/ops/integrations/zipkin/index.md
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/S

#7866 Fix broken circuit-breaking test
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
Labels: cla: yes, size/XS

#7871 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7870 fix doc of operator installation
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/S

#7872 Remove citadel from installation instructions
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#7868 Update test reference to 1.7.0-beta.1
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  go.mod
  go.sum
Labels: cla: yes, size/S

#7875 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7874 istioctl manifest changes
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/M

#7834 replace deprecated policy configuration with peerAuthentication in zh
  content/zh/docs/ops/diagnostic-tools/istioctl-describe/index.md
  content/zh/docs/tasks/security/authentication/mtls-migration/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#7879 [zh] Fix for best-practices traffic-management
  content/zh/docs/ops/best-practices/traffic-management/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#7880 Cleanup OpenShift instructions, removing outdated info
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: cla: yes, size/M

#7881 Fix some command output issues on Installing Sidecar page
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, size/XS

#7814 Automate Getting Started
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/test.sh
  scripts/snip.py
Labels: cla: yes, size/L

#7878 Fix Prometheus and Grafana svc not found during observability
  content/en/docs/tasks/observability/metrics/querying-metrics/index.md
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/index.md
Labels: area/user experience, cla: yes, kind/docs, size/M

#7873 Multicluster terminology improvements
  content/en/docs/ops/deployment/deployment-models/index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: cla: yes, size/M

#7883 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#7863 Update istioctl describe output
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: area/user experience, cla: yes, community/testing days, kind/docs, size/XS

#7882 Add logos for Istio users
  content/en/about/community/customers/amadeus.svg
  content/en/about/community/customers/anz.svg
  content/en/about/community/customers/bol-com.svg
  content/en/about/community/customers/chiper.png
  content/en/about/community/customers/chiper.svg
  content/en/about/community/customers/coyote.png
  content/en/about/community/customers/curve.svg
  content/en/about/community/customers/deepdesk.png
  content/en/about/community/customers/delphi-tech.png
  content/en/about/community/customers/fico.svg
  content/en/about/community/customers/freddie-mac.svg
  content/en/about/community/customers/giffgaff.svg
  content/en/about/community/customers/giphy.svg
  content/en/about/community/customers/gojek.svg
  content/en/about/community/customers/gov-uk.svg
  content/en/about/community/customers/hellofresh.svg
  content/en/about/community/customers/hsbc.svg
  content/en/about/community/customers/index.md
  content/en/about/community/customers/intuit.svg
  content/en/about/community/customers/lime.svg
  content/en/about/community/customers/lowes.svg
  content/en/about/community/customers/masmovil.svg
  content/en/about/community/customers/mercari.svg
  content/en/about/community/customers/nandos.svg
  content/en/about/community/customers/postman.svg
  content/en/about/community/customers/rapido.png
  content/en/about/community/customers/schlumberger.svg
  content/en/about/community/customers/shop-apotheke.svg
  content/en/about/community/customers/skyscanner.svg
  content/en/about/community/customers/spotify.svg
  content/en/about/community/customers/tokopedia.svg
  content/en/about/community/customers/trivago.svg
  content/en/about/community/customers/under-armour.svg
  content/en/about/community/customers/usaf.svg
  content/en/about/community/customers/walmart.svg
  content/en/about/community/customers/wayfair.svg
  content/en/about/community/customers/william-hill.svg
  content/en/about/community/customers/yahoo.svg
  content/en/about/community/customers/zendesk.svg
Labels: cla: yes, kind/docs, size/XXL

#7884 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7859 Update controlz interface img and output command
  content/en/docs/ops/diagnostic-tools/controlz/ctrlz.png
  content/en/docs/ops/diagnostic-tools/controlz/index.md
Labels: area/test and release, cla: yes, community/testing days, kind/docs, size/S

#7885 Slack URL and "time of community meeting" updates.
  content/en/faq/general/how-do-i-contribute.md
  content/en/faq/general/how-to-join-slack.md
  content/en/news/releases/1.3.x/announcing-1.3/_index.md
  content/en/news/releases/1.4.x/announcing-1.4/_index.md
  content/en/news/releases/1.5.x/announcing-1.5/_index.md
  content/en/news/releases/1.6.x/announcing-1.6/_index.md
  layouts/partials/footer.html
Labels: cla: yes, kind/docs, size/S

#7893 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#7895 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/meta/v1beta1/istio-status/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#7887 Egress Kubernetes Services Automated test
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/test.sh
Labels: cla: yes, size/L

#7897 Minor architecture doc tweaks
  content/en/docs/ops/deployment/architecture/index.md
Labels: cla: yes, kind/docs, size/S

#7899 Update output for disable envoy access logging
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
Labels: area/user experience, cla: yes, kind/docs, size/M

#7894 Fix multi network VM doc
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
Labels: cla: yes, size/S

#7901 Update test reference to 1.7-beta.2
  go.mod
  go.sum
Labels: cla: yes, size/S

#7826 Collecting Metrics for TCP Services automated test
  content/en/docs/tasks/observability/metrics/tcp-metrics/index.md
  content/en/docs/tasks/observability/metrics/tcp-metrics/snips.sh
  content/en/docs/tasks/observability/metrics/tcp-metrics/test.sh
Labels: cla: yes, size/L

#7891 Move back doc links to v1beta1 since we are still supporting 1.15
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, size/XS

#7886 Using an External HTTPS Proxy Automated Test
  content/en/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/en/docs/tasks/traffic-management/egress/http-proxy/snips.sh
  content/en/docs/tasks/traffic-management/egress/http-proxy/test.sh
Labels: cla: yes, size/L

#7909 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#7896 Remove print and download buttons in code blocks
  src/ts/codeBlocks.ts
Labels: cla: yes, kind/docs, size/M

#7857 update proxy-config output
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: area/test and release, cla: yes, community/testing days, kind/docs, size/M

#7912 Remove deprecated addonComponents
  content/en/docs/setup/install/operator/index.md
Labels: area/user experience, cla: yes, kind/docs, size/XS

#7889 Verify test cleanup
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/tls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/tls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/test.sh
  pkg/test/istioio/framework.go
  tests/util/verify.sh
Labels: cla: yes, size/L

#7903 Show examples in `Check what's installed` section
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#7907 Augment tracing configurability doc
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: yes, kind/docs, size/L

#7914 CVE announcement for 1.6.8 and 1.5.9
  .spelling
  content/en/news/releases/1.5.x/announcing-1.5.9/index.md
  content/en/news/releases/1.6.x/announcing-1.6.8/index.md
  content/en/news/security/istio-security-2020-009/index.md
  data/args.yml
Labels: cherrypick/master, cla: yes, size/L

#7916 Remove -it from kubectl exec calls
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/snips.sh
  content/en/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/en/docs/tasks/traffic-management/egress/http-proxy/snips.sh
  content/en/docs/tasks/traffic-management/egress/http-proxy/test.sh
  scripts/snip.py
Labels: cla: yes, size/M

#7919 Cherry-pick announcement for 1.5.9/1.6.8 into master
  .spelling
  content/en/news/releases/1.5.x/announcing-1.5.9/index.md
  content/en/news/releases/1.6.x/announcing-1.6.8/index.md
  content/en/news/security/istio-security-2020-009/index.md
Labels: cla: yes, kind/docs, size/L

#7913 [kiali] update for kiali that ships with istio 1.7
  content/en/docs/ops/integrations/kiali/index.md
  content/en/docs/tasks/observability/kiali/index.md
Labels: cla: yes, kind/docs, size/S

#7920 Update Prometheus metrics label pod_name to pod
  content/en/docs/ops/best-practices/observability/index.md
Labels: cla: yes, kind/docs, size/M

#7926 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#7923 Explain pod annotation overrides for tracing
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: yes, kind/docs, size/XS

#7935 redirect preliminary links to preliminary.istio.io
  layouts/index.redir
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/XS

#7940 [release-1.6] redirect preliminary links to preliminary.istio.io
  layouts/index.redir
Labels: cla: yes, release-notes-none, size/XS

#7930 add more description to uninstall command during upgrade
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, size/S

#7937 Remove retired command manifest versions
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, kind/docs, size/XS

#7934 Remove prometheus since it's no longer installed
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: cla: yes, size/XS

#7921 update wording on bookinfo destination rules differences
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/examples/bookinfo/test.sh
Labels: area/security, cla: yes, kind/docs, size/S

#7910 Update zipkin dashboard images and tracing description
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/istio-tracing-details-zipkin.png
  content/en/docs/tasks/observability/distributed-tracing/zipkin/istio-tracing-list-zipkin.png
Labels: area/user experience, cla: yes, kind/docs, size/XS

#7941 Learn Microservices using Kubernetes and Istio Issues changes for 1.7 (partial)
  content/en/docs/examples/microservices-istio/package-service/index.md
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/en/docs/examples/microservices-istio/setup-local-computer/index.md
Labels: cla: yes, size/S

#7911 zh-translation: Update MOSN blog
  content/zh/blog/2020/mosn-proxy/index.md
Labels: cherrypick/master, cherrypick/release-1.6, cla: yes, size/XS, translation/chinese

#7924 small update to canary upgrade doc
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, size/M

#7922 Add docs for target_arch
  content/en/docs/setup/getting-started/index.md
Labels: cherrypick/release-1.6, cla: yes, size/XS

#7947 [release-1.6] Add docs for target_arch
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, release-notes-none, size/XS

#7949 [release-1.6] Update test ref to 1.6.8
  go.mod
  go.sum
Labels: cla: yes, size/S

#7865 Redirect download scripts to master instead of stable branch
  layouts/index.redir
Labels: cla: yes, size/XS

#7953 Lint allow references to archive versions
  scripts/lint_site.sh
Labels: cla: yes, size/XS

#7954 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#7948 [release-1.6] Release 1.6 ref doc update
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  data/analysis.yaml
  scripts/grab_reference_docs.sh
  scripts/lint_site.sh
Labels: cla: yes, size/M

#7936 Update test ref to 1.7.0-rc.1
  go.mod
  go.sum
Labels: cla: yes, size/XS

#7956 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7929 change helm template link for upgrade-notes 1.5
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7950 remove helm instruction and upgrade notes from 1.4
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, kind/docs, size/M

#7952 Clean up metric customization to get rid of envoyfilter based text editing
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, size/L

#7890 remove how to enable app http probe instruction
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
  content/en/docs/ops/configuration/mesh/app-health-check/test.sh
Labels: cla: yes, kind/docs, size/L

#7957 Upgrade doc clarification
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, size/S

#7960 update in place upgrade doc
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, kind/docs, size/S

#7962 Minor fix on metric customization doc
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, size/XS

#7959 Next round of changes to get tutorial working
  content/en/docs/examples/microservices-istio/add-istio/index.md
  content/en/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
Labels: cla: yes, size/M

#7961 Cleanup health checking doc
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
  content/en/docs/ops/configuration/mesh/app-health-check/test.sh
Labels: cla: yes, size/L

#7963 Fix invalid inline code
  content/en/docs/tasks/observability/metrics/tcp-metrics/index.md
Labels: cla: yes, kind/docs, size/XS

#7964 [release-1.6] Remove retired command manifest versions
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, release-notes-none, size/XS

#7969 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#7968 Update test framework readme
  tests/README.md
Labels: cla: yes, size/S

#7967 Add warning for network policy enforcement
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh
Labels: cla: yes, size/S

#7970 Describe use of istioctl validate and analyze
  content/en/docs/ops/common-problems/validation/index.md
Labels: cla: yes, size/XS

#7972 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#7971 Deprecated tasks do not need tests + small wording fix
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/en/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
Labels: cla: yes, size/XS

#7966 Automated test for Querying metrics from prometheus
  content/en/docs/tasks/observability/metrics/querying-metrics/index.md
  content/en/docs/tasks/observability/metrics/querying-metrics/snips.sh
  content/en/docs/tasks/observability/metrics/querying-metrics/test.sh
Labels: cla: yes, kind/docs, ok-to-test, size/L

#7977 Updates to Kiali page
  content/en/docs/tasks/observability/kiali/index.md
Labels: cla: yes, size/XS

#7973 Update test ref to 1.7.0-rc.2
  go.mod
  go.sum
Labels: cla: yes, size/S

#7974 Microservices tutorial - Remove mTLS since it's never discussed
  content/en/docs/examples/microservices-istio/add-istio/index.md
Labels: cla: yes, size/S

#7975 Getting Started - small fixes related to addons.
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: cla: yes, size/XS

#7976 Add info on Kiali install
  content/en/docs/ops/integrations/kiali/index.md
Labels: cla: yes, size/XS

#7944 Automated test for customizing TCP metrics
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/snips.sh
  content/en/docs/tasks/observability/metrics/customize-metrics/test.sh
Labels: cla: yes, kind/docs, ok-to-test, size/L

#7979 Add link to envoy attributes in metric customization doc
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cherrypick/release-1.6, cla: yes, size/XS

#7982 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#7981 [release-1.6] Add link to envoy attributes in metric customization doc
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, release-notes-none, size/XS

#7984 Update test ref to 1.7.0-rc.3
  go.mod
  go.sum
Labels: cla: yes, size/XS

#7945 Workaround code regression
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/S

#7980 Fixed a grammatical error in a sentence.
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, ok-to-test, size/XS

#7987 [master] Fixed a grammatical error in a sentence.
  content/en/docs/setup/getting-started/index.md
Labels: cla: no, cla: yes, release-notes-none, size/XS

#7939 Add documentation for telemetry v1 vs v2
  content/en/about/feature-stages/index.md
  content/en/blog/2019/knative-activator-adapter/index.md
  content/en/faq/metrics-and-logs/telemetry-v1-vs-v2.md
  content/en/faq/mixer/attribute-expressions.md
  content/en/faq/mixer/header-rules.md
  content/en/faq/mixer/index.md
  content/en/faq/mixer/mixer-self-monitoring.md
  content/en/faq/mixer/seeing-mixer-config.md
  content/en/faq/mixer/why-mixer.md
  content/en/faq/mixer/writing-custom-adapters.md
Labels: cla: yes, kind/docs, size/L

#8005 Remove mix from update_ref_docs
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XS

#8004 Add blog post for Steering changes
  content/en/blog/2020/steering-changes/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/M

#8008 [release-1.7] Add blog post for Steering changes
  content/en/blog/2020/steering-changes/index.md
Labels: cla: yes, release-notes-none, size/M

#8007 Nothing to test on 'Istio Standard Metrics'
  content/en/docs/reference/config/metrics/index.md
Labels: cla: yes, size/XS

#7869 Replace usage of meshExpansion flag with istiod gateway code sample
  content/en/docs/setup/install/multicluster/shared/index.md
  content/en/docs/setup/install/virtual-machine/index.md
Labels: area/environments, cla: yes, size/M

#7072 zh-translation: /docs/reference/glossary/service-registry.md
  content/zh/docs/reference/glossary/service-registry.md
Labels: cla: yes, size/XS, translation/chinese

#8010 Release 1.5.10
  content/en/news/releases/1.5.x/announcing-1.5.10/index.md
  content/en/news/support/announcing-1.5-eol-final/index.md
Labels: area/test and release, cherrypick/master, cla: yes, size/S

#8016 [master] Release 1.5.10
  content/en/news/releases/1.5.x/announcing-1.5.10/index.md
  content/en/news/support/announcing-1.5-eol-final/index.md
Labels: cla: yes, release-notes-none, size/S

#8015 fix redirects from archive.istio.io to redirect correctly
  layouts/index.redir
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8018 [release-1.7] fix redirects from archive.istio.io to redirect correctly
  layouts/index.redir
Labels: cla: yes, release-notes-none, size/XS

#8009 Adding Meshdynamics.io to Istio partners page
  content/en/about/community/partners/index.md
  content/en/about/community/partners/meshdynamics.png
Labels: cherrypick/release-1.7, cla: yes, kind/docs, ok-to-test, size/XS

#8019 [release-1.7] Adding Meshdynamics.io to Istio partners page
  content/en/about/community/partners/index.md
  content/en/about/community/partners/meshdynamics.png
Labels: cla: no, release-notes-none, size/XS

#8020 fix base archive.istio.io redirect
  layouts/index.redir
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8022 Add warning about gateway names
  content/en/docs/setup/install/istioctl/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8021 [Cherry Pick] fix base archive.istio.io redirect (#8020)
  layouts/index.redir
Labels: cla: yes, kind/docs, size/XS

#8023 [release-1.7] Add warning about gateway names
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, release-notes-none, size/XS

#8025 zh-translation: Update istio.io / content / zh / docs / concepts / traffic-management…
  content/zh/docs/concepts/traffic-management/index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#8013 zh-translation: fix typos
  content/zh/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#8003 automated test for zipkin dashboard and modify snippet generation to take boilerplate into account
  content/en/boilerplates/kubectl-multicluster-contexts.md
  content/en/boilerplates/snips/before-you-begin-egress.sh
  content/en/boilerplates/snips/example.sh
  content/en/boilerplates/snips/kubectl-multicluster-contexts.sh
  content/en/boilerplates/snips/start-httpbin-service.sh
  content/en/boilerplates/snips/test-1.sh
  content/en/boilerplates/snips/test-3.sh
  content/en/boilerplates/snips/trace-generation.sh
  content/en/boilerplates/snips/verify-crds.sh
  content/en/boilerplates/trace-generation.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/zipkin/test.sh
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/metrics/querying-metrics/test.sh
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/snips.sh
  content/en/docs/tasks/traffic-management/egress/http-proxy/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  scripts/gen_snips.sh
  scripts/snip.py
  tests/util/helpers.sh
Labels: cla: yes, kind/docs, ok-to-test, size/L

#8030 Remove mention of "pilot agent"
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8031 [release-1.7] Remove mention of "pilot agent"
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
Labels: cla: yes, release-notes-none, size/XS

#8027 Bring back "Update min k8 supported version for istio 1.8 (#7776)""
  data/args.yml
Labels: cla: yes, kind/docs, size/XS

#8029 Add upgrade note for EnvoyFilter changes
  content/en/news/releases/1.7.x/announcing-1.7/upgrade-notes/index.md
Labels: cherrypick/release-1.7, cla: yes, size/M

#8032 [release-1.7] Add upgrade note for EnvoyFilter changes
  content/en/news/releases/1.7.x/announcing-1.7/upgrade-notes/index.md
Labels: cla: yes, release-notes-none, size/M

#8017 Describe external control planes
  content/en/docs/ops/deployment/deployment-models/index.md
  content/en/docs/ops/deployment/deployment-models/single-cluster-external-control-plane.svg
  content/en/docs/reference/glossary/external-control-plane.md
  content/en/docs/reference/glossary/managed-control-plane.md
  content/en/docs/reference/glossary/remote-cluster.md
Labels: cherrypick/release-1.7, cla: yes, size/M

#8034 [release-1.7] Describe external control planes
  content/en/docs/ops/deployment/deployment-models/index.md
  content/en/docs/ops/deployment/deployment-models/single-cluster-external-control-plane.svg
  content/en/docs/reference/glossary/external-control-plane.md
  content/en/docs/reference/glossary/managed-control-plane.md
  content/en/docs/reference/glossary/remote-cluster.md
Labels: cla: yes, release-notes-none, size/M

#8036 Fix duplicate period (..) on end of paragraphs
  content/en/docs/concepts/traffic-management/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, ok-to-test, size/XS

#8037 [release-1.7] Fix duplicate period (..) on end of paragraphs
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, release-notes-none, size/XS

#8038 fix incorrect label for upgrade.
  content/en/docs/setup/upgrade/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8041 [release-1.7] fix incorrect label for upgrade.
  content/en/docs/setup/upgrade/index.md
Labels: cla: no, release-notes-none, size/XS

#7978 blog post for central istiod
  content/en/blog/2020/new-deployment-model/index.md
  content/en/blog/2020/new-deployment-model/multiple-clusters-external-Istiod.svg
  content/en/blog/2020/new-deployment-model/multiple-external-Istiods.svg
  content/en/blog/2020/new-deployment-model/single-cluster-external-Istiod.svg
  content/en/blog/2020/new-deployment-model/single-cluster.svg
Labels: cherrypick/release-1.7, cla: yes, size/M

#8045 [release-1.7] blog post for central istiod
  content/en/blog/2020/new-deployment-model/index.md
  content/en/blog/2020/new-deployment-model/multiple-clusters-external-Istiod.svg
  content/en/blog/2020/new-deployment-model/multiple-external-Istiods.svg
  content/en/blog/2020/new-deployment-model/single-cluster-external-Istiod.svg
  content/en/blog/2020/new-deployment-model/single-cluster.svg
Labels: cla: no, release-notes-none, size/M

#8053 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
