Repository istio/istio.io, pull requests merged in 2020-05, with the labels that each got.

#7210 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#7205 Fix the link to the Operator API
  content/en/docs/setup/install/standalone-operator/index.md
Labels: area/environments, cla: yes, size/XS

#7211 Update automated test TAG to match go.mod istio commit
  prow/integ-suite-kind.sh
Labels: cla: yes, size/XS

#7204 Add linkinator to replace htmlproofer and increase linting speed
  content/en/blog/2018/egress-mongo/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/blog/2019/webhook/index.md
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/analytics/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/apikey/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/authorization/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/edge/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/kubernetes/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/listentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/logentry/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/metric/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/quota/index.html
  content/en/docs/reference/config/policy-and-telemetry/templates/tracespan/index.html
  content/en/docs/reference/config/proxy_extensions/metadata_exchange/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/faq/distributed-tracing/how-to-support-tracing.md
  content/pt-br/blog/2018/egress-mongo/index.md
  scripts/grab_reference_docs.sh
  scripts/lint_site.sh
Labels: cla: yes, kind/docs, ok-to-test, size/L

#7213 Update port information for 1.6
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, size/S

#7217 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#7219 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#7216 Remove node_agent from ref docs check
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XS

#7218 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/node_agent/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/proxy_extensions/metadata_exchange.html./index.html
Labels: cla: yes, size/L

#7220 Fix typo of PodDisruptionBudgets
  content/en/docs/setup/upgrade/index.md
  content/pt-br/docs/setup/upgrade/istioctl-upgrade/index.md
  content/zh/docs/setup/upgrade/istioctl-upgrade/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7209 Restructure the cert management tasks.
  content/en/about/feature-stages/index.md
  content/en/blog/2019/dns-cert/index.md
  content/en/blog/2020/istiod/index.md
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared/index.md
  content/en/docs/tasks/security/authentication/_index.md
  content/en/docs/tasks/security/authorization/_index.md
  content/en/docs/tasks/security/cert-management/_index.md
  content/en/docs/tasks/security/cert-management/dns-cert/index.md
  content/en/docs/tasks/security/cert-management/dns-cert/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/index.md
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/news/releases/0.x/announcing-0.5/index.md
  tests/security/dns_cert/dns_cert_test.go
  tests/security/dns_cert/scripts/dns_cert.txt
  tests/security/plugin_ca_cert/plugin_ca_cert_test.go
  tests/security/plugin_ca_cert/scripts/plugin_ca_cert.txt
Labels: area/security, cla: yes, kind/docs, size/M

#7224 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#7222 Add 1.4 EOL warning
  content/en/news/support/announcing-1.4-eol/index.md
Labels: cherrypick/release-1.5, cla: yes, size/S

#7186 Remove Galley Architecture section
  content/en/docs/ops/deployment/architecture/index.md
  content/en/news/releases/1.1.x/announcing-1.1/_index.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: cla: yes, community/testing days, size/S

#7225 [release-1.5] Add 1.4 EOL warning
  content/en/news/support/announcing-1.4-eol/index.md
Labels: cla: yes, size/S

#7223 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7227 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7157 Add docs for Wait for Resource Status to Apply Configuration
  content/en/docs/ops/configuration/mesh/config-resource-ready/index.md
  content/en/docs/reference/config/config-status/index.md
Labels: area/config, cla: yes, kind/docs, size/L

#7226 Correct Envoy Access Log links
  content/en/docs/ops/common-problems/network-issues/index.md
  content/en/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/en/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/en/docs/reference/config/telemetry/metrics/index.md
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/pt-br/docs/ops/common-problems/network-issues/index.md
  content/pt-br/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/pt-br/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/pt-br/docs/tasks/observability/logs/access-log/index.md
  content/zh/docs/ops/common-problems/network-issues/index.md
  content/zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/zh/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/zh/docs/reference/config/telemetry/metrics/index.md
  content/zh/docs/tasks/observability/logs/access-log/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#7228 Update kind image to 1.18.2
  prow/lib.sh
Labels: cla: yes, size/XS

#7230 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  data/analysis.yaml
Labels: cla: yes, size/M

#7214 Update test framework to use 1.6.0-beta.0
  .gitignore
  Makefile.core.mk
  bin/init.sh
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  go.mod
  go.sum
  prow/integ-suite-kind.sh
  tests/README.md
  tests/tests.mk
Labels: cla: yes, size/L

#7233 Remove snippet gen (# $snippet) from all tests
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  content/en/docs/tasks/security/authorization/authz-http/index.md
  content/en/docs/tasks/security/authorization/authz-http/snips.sh
  content/en/docs/tasks/security/cert-management/dns-cert/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  scripts/snip.py
  tests/README.md
  tests/security/authz_http_test.go
  tests/security/scripts/authz_http.txt
  tests/trafficmanagement/ingress/scripts/cleanup.txt
  tests/trafficmanagement/ingress/scripts/configure_mtls_ingress.txt
  tests/trafficmanagement/ingress/scripts/configure_tls_ingress_multiple_hosts.txt
  tests/trafficmanagement/ingress/scripts/configure_tls_ingress_single_host.txt
  tests/trafficmanagement/ingress/scripts/generate_certs_and_keys.txt
  tests/trafficmanagement/ingress/scripts/troubleshooting.txt
  tests/trafficmanagement/ingress/secure_ingress_sds_test.go
  tests/trafficmanagement/scripts/circuitbreaker_test_cleanup.txt
  tests/trafficmanagement/scripts/circuitbreaker_test_setup.txt
  tests/trafficmanagement/scripts/mirror_deploy.txt
  tests/trafficmanagement/scripts/mirror_traffic.txt
  tests/trafficmanagement/scripts/trip_circuitbreaker.txt
  tests/util/verify.sh
Labels: cla: yes, size/XXL

#7234 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: cla: yes, size/S

#7232 Try removing helm entries from see also on getting started page
  content/en/news/releases/1.1.x/announcing-1.1/helm-changes/index.md
  content/en/news/releases/1.2.x/announcing-1.2/helm-changes/index.md
  content/en/news/releases/1.3.x/announcing-1.3/helm-changes/index.md
Labels: cla: yes, size/XS

#7236 Update deprecated flags for meshConfig
  content/en/docs/ops/configuration/traffic-management/locality-load-balancing/index.md
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/policy-enforcement/enabling-policy/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/M

#7237 Use template for sub testcases, fix TAG for them
  Makefile.core.mk
  tests/tests.mk
Labels: cla: yes, size/S

#7235 Update index.md
  content/zh/docs/tasks/security/authentication/auto-mtls/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#7240 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: cla: yes, size/XS

#7239 Delete all snippet generating code from istioio test framework
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
  pkg/test/istioio/builder.go
  pkg/test/istioio/context.go
  pkg/test/istioio/func.go
  pkg/test/istioio/script.go
  pkg/test/istioio/snippet.go
  pkg/test/istioio/verifier.go
  pkg/test/istioio/yaml.go
  tests/security/authz_http_test.go
  tests/trafficmanagement/ingress/secure_ingress_sds_test.go
  tests/trafficmanagement/request_timeouts_test.go
  tests/trafficmanagement/tcp_trafficshifting_test.go
Labels: cla: yes, size/XXL

#7246 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7249 Update index.md(delete en)
  content/zh/docs/tasks/security/authentication/auto-mtls/index.md
Labels: cherrypick/release-1.5, cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#7176 Add authz-tcp user guide test.
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
  content/en/docs/tasks/security/authorization/authz-tcp/snips.sh
  go.sum
  tests/security/authz_tcp/authz_tcp_test.go
  tests/security/authz_tcp/main_test.go
  tests/security/authz_tcp/scripts/authz_tcp.txt
Labels: area/test and release, cla: yes, size/L

#7255 Add default timeout
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#7252 Fix yaml configuration and some explanation
  .spelling
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: cla: yes, size/L

#7265 Cleanup and fix TCP traffic routing test
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  tests/trafficmanagement/scripts/tcp_trafficshifting_setup.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_test.txt
Labels: cla: yes, size/L

#7247 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/proxy_extensions/attributegen/index.html
Labels: cla: yes, size/M

#7253 More doc testing
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  tests/README.md
  tests/trafficmanagement/ingress/ingress_control_test.go
  tests/trafficmanagement/ingress/scripts/ingress_control.sh
  tests/trafficmanagement/scripts/trip_circuitbreaker.txt
  tests/util/verify.sh
Labels: cla: yes, size/L

#7268 Add preview profile
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#7285 Add release notes for Istio 1.5.3 and Istio 1.4.9
  .spelling
  content/en/news/releases/1.4.x/announcing-1.4.9/index.md
  content/en/news/releases/1.5.x/announcing-1.5.3/index.md
  content/en/news/security/istio-security-2020-005/index.md
  data/args.yml
Labels: cla: yes, size/M

#7289 fix(observability): remove outdated info from concept doc
  content/en/docs/concepts/observability/index.md
Labels: cla: yes, size/S

#7282 Fix external charts
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#7276 Trivial grammar error fix
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
Labels: cla: yes, size/XS

#7277 Stop recommending bleeding edge istioctl analyzers
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: yes, size/S

#7278 Add --all-namespace flag to istioctl analyze
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: yes

#7294 Add warning to 1.5.3
  content/en/news/releases/1.5.x/announcing-1.5.3/index.md
Labels: cla: yes, size/XS

#7295 Update security note to skip 1.5.3
  content/en/news/security/istio-security-2020-005/index.md
Labels: cla: yes, size/XS

#7296 Add 1.5.4 release note
  content/en/news/releases/1.5.x/announcing-1.5.3/index.md
  content/en/news/releases/1.5.x/announcing-1.5.4/index.md
  content/en/news/security/istio-security-2020-005/index.md
  data/args.yml
Labels: cla: yes, kind/docs, size/M

#7292 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: cla: yes, size/L

#7264 Remove warning on hardening with distroless
  content/en/docs/ops/configuration/security/harden-docker-images/index.md
Labels: cla: yes, size/S

#7293 Move comment to proper line
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: yes, kind/docs, size/XS

#7299 Add Type colomn for svc output
  content/en/docs/tasks/observability/metrics/querying-metrics/index.md
Labels: area/test and release, area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#7301 Update http 1.1 to http 2
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: area/test and release, area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#7272 Update circuit breaker docs
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
Labels: cla: yes, size/S

#7302 Updating screenshots for kiali task
  content/en/docs/tasks/observability/kiali/index.md
  content/en/docs/tasks/observability/kiali/kiali-graph.png
  content/en/docs/tasks/observability/kiali/kiali-istioconfig0-errormsgs.png
  content/en/docs/tasks/observability/kiali/kiali-istioconfig1-tooltip.png
  content/en/docs/tasks/observability/kiali/kiali-istioconfig2-details-errormsgs.png
  content/en/docs/tasks/observability/kiali/kiali-istioconfig3-details-yaml1.png
  content/en/docs/tasks/observability/kiali/kiali-istioconfig3-details-yaml2.png
  content/en/docs/tasks/observability/kiali/kiali-istioconfig3-details-yaml3.png
  content/en/docs/tasks/observability/kiali/kiali-overview.png
  content/en/docs/tasks/observability/kiali/kiali-validate1-list.png
  content/en/docs/tasks/observability/kiali/kiali-validate2-errormsg.png
  content/en/docs/tasks/observability/kiali/kiali-validate3-ok.png
  content/en/docs/tasks/observability/kiali/kiali-wiz0-graph-options.png
  content/en/docs/tasks/observability/kiali/kiali-wiz1-graph-ratings-percent.png
  content/en/docs/tasks/observability/kiali/kiali-wiz2-ratings-service-action-menu.png
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7304 Automator: update common-files@release-1.5 in istio/istio.io@release-1.5
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#7269 [release-1.6] Update galley to istiod for istioctl-analyze command
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: area/test and release, area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#7306 Fix test.kube.postsubmit no longer needing to write snippets.
  tests/tests.mk
Labels: cla: yes, size/XS

#7290 Fix classify docs
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: area/policies and telemetry, cla: yes, size/XS

#7279 Add istioctl analyze to Getting Started
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, kind/docs, size/XS

#7309 update kiali screenshot
  content/en/docs/setup/getting-started/kiali-example2.png
Labels: cla: yes, kind/docs, size/XS

#7291 fix architecture diagram
  content/en/docs/ops/deployment/architecture/arch.svg
  content/zh/docs/ops/deployment/architecture/arch.svg
Labels: cla: yes, kind/docs, size/XS

#7266 Apache nifi faq
  .spelling
  content/en/faq/applications/nifi.md
Labels: cla: yes, kind/docs, size/M

#7308 Simplify TCPTrafficShiftingTest
  tests/trafficmanagement/ingress/scripts/ingress_control.sh
  tests/trafficmanagement/scripts/fault_injection.sh
  tests/trafficmanagement/scripts/request_routing.sh
  tests/trafficmanagement/scripts/request_timeouts.sh
  tests/trafficmanagement/scripts/tcp_trafficshifting.sh
  tests/trafficmanagement/scripts/tcp_trafficshifting_cleanup.txt
  tests/trafficmanagement/scripts/tcp_trafficshifting_setup.txt
  tests/trafficmanagement/tcp_trafficshifting_test.go
  tests/util/samples.sh
Labels: cla: yes, size/L

#7305 Manual cherry-pick of release files #7285 #7294 #7296
  .spelling
  content/en/news/releases/1.4.x/announcing-1.4.9/index.md
  content/en/news/releases/1.5.x/announcing-1.5.3/index.md
  content/en/news/releases/1.5.x/announcing-1.5.4/index.md
  content/en/news/security/istio-security-2020-005/index.md
Labels: cla: yes, size/L

#7313 Cleanup secure ingress test
  tests/trafficmanagement/ingress/scripts/cleanup.txt
  tests/trafficmanagement/ingress/scripts/configure_mtls_ingress.txt
  tests/trafficmanagement/ingress/scripts/configure_tls_ingress_multiple_hosts.txt
  tests/trafficmanagement/ingress/scripts/configure_tls_ingress_single_host.txt
  tests/trafficmanagement/ingress/scripts/generate_certs_and_keys.txt
  tests/trafficmanagement/ingress/scripts/secure_ingress.sh
  tests/trafficmanagement/ingress/secure_ingress_sds_test.go
  tests/trafficmanagement/ingress/secure_ingress_test.go
  tests/util/samples.sh
Labels: cla: yes, size/XL

#7314 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: cla: yes, size/M

#7315 Authz deny
  content/en/docs/tasks/security/authorization/authz-deny/index.md
  content/en/docs/tasks/security/authorization/authz-deny/snips.sh
  tests/README.md
  tests/examples/scripts/bookinfo.txt
  tests/security/authz_deny/authz_deny_test.go
  tests/security/authz_deny/main_test.go
  tests/security/authz_deny/scripts/authz_deny.sh
  tests/security/authz_tcp/scripts/authz_tcp.txt
  tests/security/plugin_ca_cert/scripts/plugin_ca_cert.txt
  tests/security/scripts/mtls_migration.txt
  tests/trafficmanagement/ingress/scripts/ingress_control.sh
  tests/trafficmanagement/ingress/scripts/secure_ingress.sh
  tests/trafficmanagement/scripts/fault_injection.sh
  tests/trafficmanagement/scripts/request_routing.sh
  tests/trafficmanagement/scripts/tcp_trafficshifting.sh
  tests/trafficmanagement/scripts/traffic_shifting.txt
  tests/util/verify.sh
Labels: cla: yes, size/XL

#7319 Update kubectl output
  content/en/docs/setup/install/standalone-operator/index.md
Labels: cla: yes, size/M

#7324 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  data/analysis.yaml
Labels: cla: yes, size/S

#7312 Delete mixer filter stats as they no longer exist
  content/en/docs/ops/configuration/telemetry/envoy-stats/index.md
Labels: cla: yes, kind/docs, size/XS

#7328 fix(retry): add default behavior about retry
  content/en/docs/concepts/traffic-management/index.md
  content/pt-br/docs/concepts/traffic-management/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7283 Add diagram to what-is-istio page
  content/en/docs/concepts/what-is-istio/index.md
Labels: cla: yes, kind/docs, size/S

#7320 update FAQ > General > slack instructions
  content/en/faq/general/how-to-join-slack.md
  content/pt-br/faq/general/how-to-join-slack.md
Labels: cla: yes, ok-to-test, size/S

#7331 Misleading default namespace value 'istio'
  content/en/blog/2018/aws-nlb/index.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/XS

#7251 Remove experimental link in feature status page; change to development
  content/en/about/feature-stages/index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: yes, kind/docs, size/XS

#7307 fix(metrics): Add multicluster labels to Standard Metrics doc
  content/en/docs/reference/config/telemetry/metrics/index.md
Labels: area/policies and telemetry, cla: yes, size/S

#7330 Update Python and Java code snippet
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
Labels: area/user experience, cla: yes, community/testing days, kind/docs, size/S

#7323 A bit of cleanup on the arch doc
  content/en/docs/ops/deployment/architecture/index.md
Labels: cla: yes, size/L

#7206 update for istio users why gloo
  content/en/blog/2020/istio-sds-gloo/index.md
Labels: cla: yes, size/XS

#7259 Update the Istio version for testing
  go.mod
  go.sum
Labels: cla: yes, size/M

#7333 Fix hard-coded downgrade versions
  content/en/docs/setup/upgrade/index.md
Labels: area/environments, cla: yes, kind/docs, size/XS

#5098 Blog post: Securely direct traffic from IBM Cloud Kubernetes Service Ingress to Istio Ingress Gateway
  content/en/blog/2020/alb-ingress-gateway-iks/alb-ingress-gateway.svg
  content/en/blog/2020/alb-ingress-gateway-iks/index.md
Labels: cla: yes, size/L

#7335 Cleanup circuit breaking test
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
  tests/trafficmanagement/circuit_breaking_test.go
  tests/trafficmanagement/scripts/circuit_breaking.sh
  tests/trafficmanagement/scripts/circuitbreaker_test_cleanup.txt
  tests/trafficmanagement/scripts/circuitbreaker_test_setup.txt
  tests/util/verify.sh
Labels: cla: yes, size/L

#7343 Envoy's Access Log links returning 404
  content/en/docs/tasks/observability/logs/access-log/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7338 Authz jwt
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  go.mod
  go.sum
  scripts/lint_site.sh
  scripts/snip.py
  tests/security/authz_jwt/authz_jwt_test.go
  tests/security/authz_jwt/main_test.go
  tests/security/authz_jwt/scripts/authz_jwt.sh
  tests/util/verify.sh
Labels: area/security, area/test and release, cla: yes, size/L

#7341 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#7346 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#7349 changed fromRegistry to match MAIN_CLUSTER_NAME
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: area/environments, area/networking, cla: yes, size/XS

#7040 Add Monitoring Multicluster Istio with Prometheus doc
  content/en/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/external-production-prometheus.svg
  content/en/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/in-mesh-production-prometheus.svg
  content/en/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/index.md
Labels: area/config, cla: yes, kind/docs, size/L

#7351 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
Labels: cla: yes, size/L

#7347 Update prometheus-application-metrics.md w/ fixed link
  content/en/faq/metrics-and-logs/prometheus-application-metrics.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7350 Bump istio/istio dependency
  Makefile.core.mk
  bin/init.sh
  go.mod
  go.sum
Labels: cla: yes, size/S

#7356 Fix curl request for istiod debug
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: area/user experience, cla: yes, kind/docs, size/XS

#7354 Update envoy and istiod output
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: area/user experience, cla: yes, kind/docs, size/L

#7353 Update inbound and outbound ports
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: cla: yes, kind/docs, size/XS

#7248 Add instructions on installing Istio for vms
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, community/testing days, size/L

#7336 Update istioctl install docs with overlay examples
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/L

#7162 Setup for GKE
  content/en/docs/setup/platform-setup/gke/index.md
  scripts/build_archive_site.sh
Labels: cla: yes, kind/docs, ok-to-test, size/S

#7358 Add Signal Sciences to partner page
  content/en/about/community/partners/index.md
  content/en/about/community/partners/signalsciences.svg
Labels: cla: yes, kind/docs, ok-to-test, size/M

#7337 Remove IPv6 support for Kubernetes as a core supported feature
  content/en/about/feature-stages/index.md
Labels: cla: yes, kind/docs, size/XS

#7242 Add documentation for gateway topology api
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
Labels: cla: yes, size/L

#7359 verify.sh: Don't exit on error in _run_and_verify_*() funcs.
  tests/util/verify.sh
Labels: area/test and release, cla: yes, size/S

#7361 authz-td-migration: Don't error when deleting non-existent items.
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
Labels: area/security, cla: yes, kind/docs, size/XS

#7363 Automator: update istio.io@release-1.6 reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#7360 correct typo in spiffe and add glossary entry
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/reference/glossary/spiffe.md
Labels: area/networking, cla: yes, kind/docs, size/S

#7362 Add proxy repo as vanity url
  layouts/index.redir
  static/golang/proxy.html
Labels: cla: yes, size/XS

#7365 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7366 Remove stray dash
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#7257 Virtual machine integration
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/XS

#7275 Upgrade notes for 1.6
  content/en/news/releases/1.6.x/_index.md
  content/en/news/releases/1.6.x/announcing-1.6/_index.md
  content/en/news/releases/1.6.x/announcing-1.6/change-notes/index.md
  content/en/news/releases/1.6.x/announcing-1.6/upgrade-notes/index.md
Labels: cla: yes, kind/docs, size/L

#7340 Remove para about application design goals
  content/en/docs/ops/deployment/architecture/index.md
Labels: cla: yes, kind/docs, size/S

#7370 debug.sh: Add debugging to test runs.
  pkg/test/istioio/script.go
  tests/util/debug.sh
Labels: area/config, area/test and release, cla: yes, size/S

#7372 Fix few small errors in the virtual machine guide
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/S

#7369 Clean up traffic shifting test
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  tests/trafficmanagement/scripts/traffic_shifting.sh
  tests/trafficmanagement/traffic_shifting_test.go
Labels: cla: yes, size/M

#7339 Fix Documentation for Customizing Metrics and TCP Metrics Task
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
  content/en/docs/tasks/observability/metrics/tcp-metrics/index.md
Labels: area/policies and telemetry, cla: yes, size/M

#7376 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7373 Small update to release note 1.6
  content/en/news/releases/1.6.x/announcing-1.6/change-notes/index.md
Labels: cla: yes, kind/docs, size/XS

#7321 add a blog entry describing WorkloadEntries
  content/en/blog/2020/workload-entry/index.md
  content/en/blog/2020/workload-entry/workload-entry-final.svg
  content/en/blog/2020/workload-entry/workload-entry-first-example.svg
Labels: cla: yes, ok-to-test, size/L

#7367 Add TLS origination doc test
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
  go.mod
  pkg/test/istioio/script.go
  tests/trafficmanagement/egress/main_test.go
  tests/trafficmanagement/egress/scripts/tls_origination.sh
  tests/trafficmanagement/egress/tls_origination_test.go
Labels: cla: yes, size/L

#7381 fix broken links in workload entry blog
  content/en/blog/2020/workload-entry/index.md
Labels: cherrypick/release-1.6, cla: yes, ok-to-test, size/XS

#7382 [release-1.6] fix broken links in workload entry blog
  content/en/blog/2020/workload-entry/index.md
Labels: cla: yes, size/XS

#7241 Update index.md(wrong command)
  content/zh/docs/tasks/policy-enforcement/enabling-policy/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#7384 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/workload-entry/index.html
  content/en/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/en/docs/reference/config/proxy_extensions/metadata_exchange/index.html
Labels: cla: yes, size/XL

#7383 Added virtualservice delegation
  content/en/news/releases/1.6.x/announcing-1.6/change-notes/index.md
Labels: cherrypick/release-1.6, cla: yes, size/XS

#7385 [release-1.6] Added virtualservice delegation
  content/en/news/releases/1.6.x/announcing-1.6/change-notes/index.md
Labels: cla: no, size/XS

#7386 Support escaped heredocs
  scripts/snip.py
  src/ts/codeBlocks.ts
Labels: cla: yes, size/XS

#7387 Cleanup mirroring test
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  tests/security/mtls_migration_test.go
  tests/trafficmanagement/mirroring_test.go
  tests/trafficmanagement/scripts/mirror_deploy.txt
  tests/trafficmanagement/scripts/mirror_traffic.txt
  tests/trafficmanagement/scripts/mirroring.sh
Labels: cla: yes, size/L

#7389 Cleanup remaining tests
  tests/configuration/health_check_test.go
  tests/configuration/scripts/cleanup.txt
  tests/configuration/scripts/liveness_and_readiness_probes.sh
  tests/configuration/scripts/liveness_and_readiness_probes_with_command.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_annotations.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_globally.txt
  tests/configuration/scripts/liveness_and_readiness_probes_with_http_separate_port.txt
  tests/examples/bookinfo_test.go
  tests/examples/scripts/bookinfo.sh
  tests/security/authz_deny/authz_deny_test.go
  tests/security/authz_deny/scripts/authz_deny.sh
  tests/security/authz_http_test.go
  tests/security/authz_jwt/authz_jwt_test.go
  tests/security/authz_jwt/scripts/authz_jwt.sh
  tests/security/authz_tcp/authz_tcp_test.go
  tests/security/authz_tcp/scripts/authz_tcp.sh
  tests/security/dns_cert/dns_cert_test.go
  tests/security/dns_cert/scripts/dns_cert.sh
  tests/security/mtls_migration_test.go
  tests/security/plugin_ca_cert/plugin_ca_cert_test.go
  tests/security/plugin_ca_cert/scripts/plugin_ca_cert.sh
  tests/security/scripts/authz_http.sh
  tests/security/scripts/mtls_migration.sh
  tests/trafficmanagement/fault_injection_test.go
Labels: cla: yes, size/L

#7395 Update tests README + small fixes
  Makefile.core.mk
  tests/README.md
  tests/trafficmanagement/mirroring_test.go
  tests/trafficmanagement/scripts/request_timeouts.sh
Labels: cla: yes, size/L

#7397 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#7398 Best-Practices: Remove reference to Citadel.
  content/en/docs/ops/best-practices/security/index.md
  content/pt-br/docs/ops/best-practices/security/index.md
Labels: area/security, cla: yes, kind/docs, size/S

#7399 Fix mirroring test
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  tests/README.md
  tests/tests.mk
  tests/trafficmanagement/scripts/mirroring.sh
  tests/util/verify.sh
Labels: cla: yes, size/M

#7403 update versions to 1.7
  data/args.yml
  data/versions.yml
Labels: cla: yes, kind/docs, size/S

#7402 [release-1.6] Best-Practices: Remove reference to Citadel.
  content/en/docs/ops/best-practices/security/index.md
  content/pt-br/docs/ops/best-practices/security/index.md
Labels: cla: yes, size/S

#7404 Add namespace creation step
  content/en/docs/setup/install/istioctl/index.md
Labels: cherrypick/master, cla: yes, size/XS

#7405 [master] Add namespace creation step
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#7408 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
Labels: cla: yes, size/M

#7406 auth: do not remove crd in upgrade note
  content/en/news/releases/1.6.x/announcing-1.6/upgrade-notes/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/S

#7407 Add authz-ingress user guide test.
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  tests/security/authz_ingress/authz_ingress_test.go
  tests/security/authz_ingress/main_test.go
  tests/security/authz_ingress/scripts/authz_ingress.sh
Labels: area/security, area/test and release, cla: yes, size/L

#7409 Update profile setup output
  content/en/docs/setup/getting-started/index.md
Labels: area/user experience, cherrypick/release-1.6, cla: yes, kind/docs, size/S

#7410 [release-1.6] auth: do not remove crd in upgrade note
  content/en/news/releases/1.6.x/announcing-1.6/upgrade-notes/index.md
Labels: cla: yes, size/S

#7411 [release-1.6] Update profile setup output
  content/en/docs/setup/getting-started/index.md
Labels: cla: yes, size/S

#7380 add a test for ingress SNI passthrough
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  tests/trafficmanagement/ingress/ingress_sni_passthrough_test.go
  tests/trafficmanagement/ingress/scripts/ingress_sni_passthrough.sh
Labels: area/test and release, cla: yes, kind/docs, size/L

#7417 Add make test_status command
  Makefile.core.mk
  scripts/test_status.sh
  tests/README.md
Labels: cla: yes, size/M

#7422 Update min k8 supported version for istio 1.7
  data/args.yml
Labels: area/user experience, cla: yes, kind/docs, size/XS

#7418 Fix sudo command on VM doc
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cherrypick/master, cla: yes, size/XS

#7420 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: cla: yes, size/M

#7424 [master] Fix sudo command on VM doc
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/XS

#7432 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
