Repository istio/istio.io, pull requests merged in 2020-09, with the labels that each got.

#8054 Update the release-1.6 test reference to 1.6.9
  go.mod
  go.sum
Labels: cla: yes, size/S

#8051 Docs: monitoring-multicluster-prometheus fixes
  content/en/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/L

#8050 Fix and test wildcard egress task
  content/en/boilerplates/before-you-begin-egress.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxy.svg
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxyCP.svg
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
Labels: cherrypick/release-1.7, cla: yes, size/XL

#8058 [release-1.7] Fix and test wildcard egress task
  content/en/boilerplates/before-you-begin-egress.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxy.svg
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxyCP.svg
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
Labels: cla: yes, release-notes-none, size/XL

#8060 [release-1.7] Automated test - Remotely access telemetry addons (both secure and insecure ways)
  content/en/docs/tasks/observability/gateways/index.md
  content/en/docs/tasks/observability/gateways/insecure_access_test.sh
  content/en/docs/tasks/observability/gateways/secure_access_test.sh
  content/en/docs/tasks/observability/gateways/snips.sh
  tests/util/addons.sh
Labels: cla: no, release-notes-none, size/XL

#8059 [release-1.7] automated test for zipkin dashboard and modify snippet generation to take boilerplate into account
  content/en/boilerplates/kubectl-multicluster-contexts.md
  content/en/boilerplates/snips/before-you-begin-egress.sh
  content/en/boilerplates/snips/example.sh
  content/en/boilerplates/snips/kubectl-multicluster-contexts.sh
  content/en/boilerplates/snips/start-httpbin-service.sh
  content/en/boilerplates/snips/test-1.sh
  content/en/boilerplates/snips/test-3.sh
  content/en/boilerplates/snips/trace-generation.sh
  content/en/boilerplates/snips/verify-crds.sh
  content/en/boilerplates/trace-generation.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/zipkin/test.sh
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/metrics/querying-metrics/test.sh
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/snips.sh
  content/en/docs/tasks/traffic-management/egress/http-proxy/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  scripts/gen_snips.sh
  scripts/snip.py
  tests/util/helpers.sh
Labels: cla: no, release-notes-none, size/L

#8040 Remove deprecated mixer for observability
  DOC_OWNERS.md
  content/en/about/feature-stages/index.md
  content/en/blog/2018/egress-monitoring-access-control/index.md
  content/en/docs/ops/common-problems/observability-issues/index.md
  content/en/docs/ops/deployment/requirements/index.md
  content/en/docs/ops/diagnostic-tools/component-logging/index.md
  content/en/docs/tasks/observability/mixer/_index.md
  content/en/docs/tasks/observability/mixer/logs/_index.md
  content/en/docs/tasks/observability/mixer/logs/collecting-logs/index.md
  content/en/docs/tasks/observability/mixer/logs/fluentd/index.md
  content/en/docs/tasks/observability/mixer/metrics/_index.md
  content/en/docs/tasks/observability/mixer/metrics/collecting-metrics/index.md
  content/en/docs/tasks/observability/mixer/metrics/tcp-metrics/index.md
  content/en/docs/tasks/observability/mixer/metrics/tcp-metrics/istio-tcp-attribute-flow.svg
  content/en/news/releases/0.x/announcing-0.5/index.md
Labels: area/policies and telemetry, cla: yes, kind/docs, size/XXL

#8065 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8066 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8073 Update kiali links
  content/en/docs/tasks/observability/kiali/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8074 [release-1.7] Update kiali links
  content/en/docs/tasks/observability/kiali/index.md
Labels: cla: yes, release-notes-none, size/XS

#8068 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8069 [release-1.7] Update Performance and Scalability Page for 1.7
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_without_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_without_jitter.svg
Labels: cherrypick/master, cla: yes, size/XXL

#8084 [release-1.7] Update Performance and Scalability Page for 1.7 (#8069)
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_without_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_without_jitter.svg
Labels: cla: yes, size/XXL

#8085 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8087 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8082 Update to newer version of 1.6.9 being spun
  go.mod
  go.sum
Labels: cla: yes, size/XS

#8079 add aihuishou.jpeg
  content/en/about/community/customers/aihuishou.jpeg
  content/en/about/community/customers/index.md
Labels: cherrypick/release-1.7, cla: yes, ok-to-test, size/XS

#8083 Remove failing extraneous command for logs
  content/en/about/bugs/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8078 Fix Sidecar Injection with annotation error
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/M

#8071 Remove deprecated Mixer Policies and Telemetry config
  DOC_OWNERS.md
  content/en/about/contribute/shortcodes/index.md
  content/en/about/feature-stages/index.md
  content/en/blog/2017/adapter-model/index.md
  content/en/blog/2017/adapter-model/machine.svg
  content/en/blog/2017/mixer-spof-myth/index.md
  content/en/blog/2018/egress-monitoring-access-control/index.md
  content/en/blog/2019/egress-traffic-control-in-istio-part-2/index.md
  content/en/blog/2019/egress-traffic-control-in-istio-part-3/index.md
  content/en/blog/2019/monitoring-external-service-traffic/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/blog/2020/wasm-announce/index.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/ops/best-practices/security/index.md
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/reference/config/policy-and-telemetry/_index.md
  content/en/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content/en/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/en/docs/reference/config/policy-and-telemetry/expression-language/index.md
  content/en/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/en/docs/reference/config/policy-and-telemetry/mixer-overview/adapters.svg
  content/en/docs/reference/config/policy-and-telemetry/mixer-overview/index.md
  content/en/docs/reference/config/policy-and-telemetry/mixer-overview/topology-with-cache.svg
  content/en/docs/reference/config/policy-and-telemetry/mixer-overview/topology-without-cache.svg
  content/en/docs/reference/config/policy-and-telemetry/templates/_index.md
  content/en/docs/reference/glossary/adapters.md
  content/en/docs/reference/glossary/attribute.md
  content/en/docs/reference/glossary/mixer-handler.md
  content/en/docs/reference/glossary/mixer-instance.md
  content/en/docs/reference/glossary/mixer.md
  content/en/docs/reference/glossary/workload-instance.md
  content/en/docs/tasks/policy-enforcement/_index.md
  content/en/docs/tasks/policy-enforcement/control-headers/index.md
  content/en/docs/tasks/policy-enforcement/enabling-policy/index.md
  content/en/docs/tasks/traffic-management/egress/egress_sni_monitoring_and_policies/index.md
  content/en/news/releases/0.x/announcing-0.4/index.md
  content/en/news/releases/1.0.x/announcing-1.0/index.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: area/policies and telemetry, cla: yes, kind/docs, size/XXL

#8095 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8096 [release-1.7] Fix Sidecar Injection with annotation error
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, release-notes-none, size/M

#8100 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XL

#8094 [release-1.7] Remove failing extraneous command for logs
  content/en/about/bugs/index.md
Labels: cla: yes, release-notes-none, size/XS

#8101 Fix typo for root-cert generation in VM Install Doc
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cherrypick/release-1.7, cla: yes, ok-to-test, size/XS

#8098 Istio 1.6.9 release notes
  content/en/news/releases/1.6.x/announcing-1.6.9/index.md
Labels: cla: yes, size/M

#8107 Fix recommended EnvoyFilter version
  content/en/news/releases/1.7.x/announcing-1.7/upgrade-notes/index.md
Labels: cherrypick/master, cla: yes, size/XS

#8108 [master] Fix recommended EnvoyFilter version
  content/en/news/releases/1.7.x/announcing-1.7/upgrade-notes/index.md
Labels: cla: yes, release-notes-none, size/XS

#8024 broken doc for multi-network VM mesh expansion, this updates it
  content/en/docs/examples/virtual-machines/multi-network/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/L

#8102 No need to pass additional -c for Istiod logs
  content/en/about/bugs/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8109 Announce Istio 1.6.9
  content/en/news/releases/1.6.x/announcing-1.6.9/index.md
Labels: cla: yes, size/M

#8114 Fix typo in upgrade docs
  content/en/docs/setup/upgrade/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8115 [release-1.7] Fix typo in upgrade docs
  content/en/docs/setup/upgrade/index.md
Labels: cla: yes, release-notes-none, size/XS

#8064 Accessing external services task test and more egress task cleanup
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/logs/access-log/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
  tests/util/verify.sh
Labels: cherrypick/release-1.7, cla: yes, size/XL

#8106 [release-1.7] Move to release-1.7 version of common files
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
  common/scripts/report_build_info.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: cla: yes, size/M

#8116 [release-1.7] Accessing external services task test and more egress task cleanup
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/logs/access-log/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
  tests/util/verify.sh
Labels: cla: yes, release-notes-none, size/XL

#8113 [release-1.7] No need to pass additional -c for Istiod logs
  content/en/about/bugs/index.md
Labels: cla: no, release-notes-none, size/XS

#8112 [release-1.7] broken doc for multi-network VM mesh expansion, this updates it
  content/en/docs/examples/virtual-machines/multi-network/index.md
Labels: cla: no, release-notes-none, size/L

#8117 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8055 Update reference docs based on latest 1.6
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
Labels: cla: yes, size/L

#8111 Release notes for 1.7.1
  .spelling
  content/en/news/releases/1.7.x/announcing-1.7.1/index.md
Labels: cherrypick/release-1.7, cla: yes, size/M

#8121 [release-1.7] Release notes for 1.7.1
  .spelling
  content/en/news/releases/1.7.x/announcing-1.7.1/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/M

#8105 [release-1.7] Update reference docs for 1.7.1
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: cla: yes, size/L

#8124 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8125 [release-1.7] correct broken link and name
  content/en/news/releases/1.7.x/announcing-1.7/change-notes/index.md
Labels: cla: yes, release-notes-none, size/XS

#8129 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8131 Adding test targets for each profile
  tests/tests.mk
Labels: cla: yes, size/S

#8132 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8133 fix: update root cert file name, add the suffix
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, kind/docs, size/XS

#8128 Add additional info about troubleshooting JWTs.
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
Labels: area/security, cherrypick/release-1.7, cla: yes, ok-to-test, size/M

#8043 Updating incorrect information in the glossary
  content/en/docs/reference/glossary/control-plane.md
  content/en/docs/reference/glossary/identity.md
  content/en/docs/reference/glossary/trust-domain.md
Labels: cherrypick/master, cla: yes, kind/docs, size/S

#8136 [master] Updating incorrect information in the glossary
  content/en/docs/reference/glossary/control-plane.md
  content/en/docs/reference/glossary/identity.md
  content/en/docs/reference/glossary/trust-domain.md
Labels: cla: no, release-notes-none, size/S

#8137 Disable cluster cleanup check until missing CRDs at start of profile_…
  tests/util/verify.sh
Labels: cla: yes, size/XS

#8138 [release-1.7] Add additional info about troubleshooting JWTs.
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
Labels: cla: no, release-notes-none, size/M

#8141 Add back verify - grep out CR failures
  tests/util/verify.sh
Labels: cla: yes, size/S

#8142 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8143 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8070 Add large scale security policy performance test blog
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_paths_vs_sourceIP.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_paths.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_policies_paths.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_policies_sourceIP.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_principals.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_requestPrincipals.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_sourceIP.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/RequestAuthN_jwks.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/index.md
  content/en/blog/2020/large-scale-security-policy-performance-tests/istio_setup.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/mtls_plaintext.svg
Labels: cherrypick/release-1.7, cla: yes, ok-to-test, size/XXL

#8146 Merge prow change from istio/istio
  prow/config/trustworthy-jwt.yaml
Labels: cla: yes, size/XS

#8149 Remove hardcoded cluster-ip-range
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
Labels: cla: yes, size/XS

#8147 [release-1.7] Add large scale security policy performance test blog
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_paths_vs_sourceIP.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_paths.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_policies_paths.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_policies_sourceIP.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_principals.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_requestPrincipals.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/AuthZ_var_sourceIP.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/RequestAuthN_jwks.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/index.md
  content/en/blog/2020/large-scale-security-policy-performance-tests/istio_setup.svg
  content/en/blog/2020/large-scale-security-policy-performance-tests/mtls_plaintext.svg
Labels: cla: no, release-notes-none, size/XXL

#8150 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8134 update the Chinese page on v1.7
  content/zh/docs/setup/getting-started/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#8152 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8151 Update the Chinese doc of version 1.7
  content/zh/docs/setup/install/istioctl/index.md
Labels: cla: yes, ok-to-test, size/S, translation/chinese

#8153 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8103 Update test reference - master
  Makefile.core.mk
  bin/init.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/test.sh
  content/en/docs/tasks/observability/gateways/secure_access_test.sh
  content/en/docs/tasks/observability/metrics/customize-metrics/test.sh
  content/en/docs/tasks/security/authentication/authn-policy/test.sh
  content/en/docs/tasks/security/authentication/mtls-migration/test.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
  content/en/docs/tasks/security/authorization/authz-td-migration/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/test.sh
  content/en/docs/tasks/security/cert-management/dns-cert/test.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/test.sh
  content/en/docs/tasks/traffic-management/mirroring/test.sh
  go.mod
  go.sum
  tests/setup/profile_demo/doc_test.go
  tests/util/helpers.sh
  tests/util/verify.sh
Labels: cla: yes, size/XL

#8099 Update docs for pluggin in CA certs
  bin/init.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/ca-hierarchy.svg
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/index.md
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/test.sh
Labels: cla: yes, size/XL

#8157 fix mysql password
  content/en/docs/examples/virtual-machines/bookinfo/index.md
Labels: cherrypick/master, cla: yes, size/XS

#8148 Simplify startup of egressgateway-with-sni-proxy
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
Labels: cla: yes, size/L

#8158 [master] fix mysql password
  content/en/docs/examples/virtual-machines/bookinfo/index.md
Labels: cla: no, release-notes-none, size/XS

#8159 Narrow tool files copied to only include certs.
  bin/init.sh
Labels: cla: yes, size/XS

#8161 README update
  README.md
  page-test.png
  tests/README.md
Labels: cla: yes, size/S

#8165 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8164 Release notes for 1.7.2
  content/en/news/releases/1.7.x/announcing-1.7.2/index.md
Labels: cherrypick/release-1.7, cla: yes, size/S

#8170 [release-1.7] Release notes for 1.7.2
  content/en/news/releases/1.7.x/announcing-1.7.2/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/S

#8174 1.6.10 reference doc updates
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#8171 Update TestRef for 1.7.2
  go.mod
  go.sum
Labels: cla: yes, size/S

#8169 Update TestRef for 1.6.10
  go.mod
  go.sum
Labels: cla: yes, size/XS

#8176 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8162 Expand deployment models to include multicluster considerations
  content/en/docs/ops/deployment/deployment-models/blue-green.svg
  content/en/docs/ops/deployment/deployment-models/endpoint-discovery.svg
  content/en/docs/ops/deployment/deployment-models/failover.svg
  content/en/docs/ops/deployment/deployment-models/index.md
  content/en/docs/reference/glossary/network.md
Labels: cla: yes, size/L

#8175 egress-gateway-tls-origination - Additional secrets need cleaning
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
Labels: cla: yes, size/XS

#8181 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8184 Logo changes
  content/en/about/community/customers/anz.svg
  content/en/about/community/customers/avito.svg
  content/en/about/community/customers/cash-app.svg
  content/en/about/community/customers/hotels-com.svg
  content/en/about/community/customers/index.md
  content/en/about/community/customers/nearpod.svg
  content/en/about/contribute/_index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/L

#8187 1 6 10 release notes
  content/en/news/releases/1.6.x/announcing-1.6.10/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/S

#8188 [release-1.7] 1 6 10 release notes
  content/en/news/releases/1.6.x/announcing-1.6.10/index.md
Labels: cla: yes, release-notes-none, size/S

#8186 Remove period at the end of the curl command
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: cherrypick/release-1.7, cla: yes, size/S

#8190 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8189 [release-1.7] Remove period at the end of the curl command
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: cla: no, release-notes-none, size/S

#8163 Try different timeout for tasks/security/authorization/authz-ingress
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/test.sh
  tests/util/helpers.sh
Labels: cla: yes, size/S

#8193 [release-1.7] Cherry-pick #8184 for logo changes
  content/en/about/community/customers/aihuishou.jpeg
  content/en/about/community/customers/amadeus.svg
  content/en/about/community/customers/anz.svg
  content/en/about/community/customers/avito.svg
  content/en/about/community/customers/bol-com.svg
  content/en/about/community/customers/cash-app.svg
  content/en/about/community/customers/chiper.svg
  content/en/about/community/customers/curve.svg
  content/en/about/community/customers/fico.svg
  content/en/about/community/customers/giphy.svg
  content/en/about/community/customers/gojek.svg
  content/en/about/community/customers/gov-uk.svg
  content/en/about/community/customers/hellofresh.svg
  content/en/about/community/customers/hotels-com.svg
  content/en/about/community/customers/hsbc.svg
  content/en/about/community/customers/iherb.svg
  content/en/about/community/customers/index.md
  content/en/about/community/customers/intuit.svg
  content/en/about/community/customers/lime.svg
  content/en/about/community/customers/lowes.svg
  content/en/about/community/customers/masmovil.svg
  content/en/about/community/customers/mercari.svg
  content/en/about/community/customers/nandos.svg
  content/en/about/community/customers/nearpod.svg
  content/en/about/community/customers/schlumberger.svg
  content/en/about/community/customers/shop-apotheke.svg
  content/en/about/community/customers/skyscanner.svg
  content/en/about/community/customers/spotify.svg
  content/en/about/community/customers/tokopedia.svg
  content/en/about/community/customers/trivago.svg
  content/en/about/community/customers/under-armour.svg
  content/en/about/community/customers/usaf.svg
  content/en/about/community/customers/walmart.svg
  content/en/about/community/customers/wayfair.svg
  content/en/about/community/customers/william-hill.svg
  content/en/about/community/customers/yahoo.svg
  content/en/about/contribute/_index.md
Labels: cla: yes, kind/docs, size/XXL

#8194 Fixing tests for osx
  bin/init.sh
  pkg/test/istioio/framework.go
Labels: cla: yes, size/S

#8195 Small improvements on getting started page
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8196 [release-1.7] Small improvements on getting started page
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: cla: yes, release-notes-none, size/XS

#8197 Fix MacOS tests using a container
  Makefile.core.mk
  bin/init.sh
Labels: cla: yes, size/S

#8199 Update to latest istio/istio
  go.mod
  go.sum
Labels: cla: yes, size/L

#8201 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8200 Fix readme.md typo referring to French language example.
  README.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#8206 Increase retry count for test flakiness
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
Labels: cla: yes, size/XS

#8198 Test flake - increase timeout and echo actual wait duration.
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
Labels: cla: yes, size/XS

#8204 Test Flake - Fix flaky failure
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
Labels: cla: yes, size/XS

#8154 [release-1.7] Update 1.6 docs: new ref docs, install changes
  archive/v1.6/_tracked_pages.json
  archive/v1.6/about/log/index.html
  archive/v1.6/docs/reference/commands/istioctl/index.html
  archive/v1.6/docs/reference/commands/pilot-agent/index.html
  archive/v1.6/docs/reference/commands/pilot-discovery/index.html
  archive/v1.6/docs/reference/config/index.html
  archive/v1.6/docs/reference/config/istio.operator.v1alpha1/index.html
  archive/v1.6/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  archive/v1.6/en/sitemap.xml
  archive/v1.6/sitemap.xml
  archive/v1.6/zh/_tracked_pages.json
  archive/v1.6/zh/docs/reference/config/installation-options/index.html
  archive/v1.6/zh/docs/setup/additional-setup/cni/index.html
  archive/v1.6/zh/docs/setup/additional-setup/config-profiles/index.html
  archive/v1.6/zh/docs/setup/getting-started/index.html
  archive/v1.6/zh/docs/setup/install/helm/index.html
Labels: cherrypick/master, cla: yes, size/M

#8210 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8212 remove duplicated anchor
  content/zh/faq/distributed-tracing/how-distributed-tracing-works.md
Labels: cherrypick/release-1.7, cla: yes, ok-to-test, size/XS, translation/chinese

#8209 Include redirects for static resources
  layouts/index.redir
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/XS

#8213 [release-1.7] Include redirects for static resources
  layouts/index.redir
Labels: cla: yes, release-notes-none, size/XS

#8215 [release-1.7] Test Flake - Fix flaky failure
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
Labels: cla: yes, release-notes-none, size/XS

#8216 Removal of the -it argument in the kubectl command for several example pages.
  content/en/docs/examples/microservices-istio/add-new-microservice-version/index.md
  content/en/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/en/docs/examples/microservices-istio/production-testing/index.md
Labels: area/test and release, cla: yes, kind/docs, ok-to-test, size/S

#8217 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8180 Rewrite multicluster installation docs
  DOC_OWNERS.md
  content/en/about/feature-stages/index.md
  content/en/blog/2019/multicluster-version-routing/index.md
  content/en/blog/2020/multi-cluster-mesh-automation/index.md
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/gateways/multicluster-with-gateways.svg
  content/en/docs/setup/install/multicluster/index.md
  content/en/docs/setup/install/multicluster/multi-primary-multi-network.svg
  content/en/docs/setup/install/multicluster/multi-primary.svg
  content/en/docs/setup/install/multicluster/primary-remote-multi-network.svg
  content/en/docs/setup/install/multicluster/primary-remote.svg
  content/en/docs/setup/install/multicluster/shared/diagram.svg
  content/en/docs/setup/install/multicluster/shared/index.md
  content/en/docs/setup/install/multicluster/shared/multicluster-with-vpn.svg
  content/en/docs/setup/install/multicluster/snips.sh
Labels: cla: yes, size/XXL

#8218 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8208 Update for process of creating an archive update
  README.md
Labels: cla: yes, size/XS

#8219 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8203 Single network virtual machine example
  content/en/docs/examples/virtual-machines/single-network/index.md
Labels: area/environments, area/networking, cherrypick/release-1.7, cla: yes, flag/needs-backport, size/L

#8220 [release-1.7] Single network virtual machine example
  content/en/docs/examples/virtual-machines/single-network/index.md
Labels: cla: no, release-notes-none, size/L

#8207 [master] [release-1.7] Update 1.6 docs: new ref docs, install changes
  archive/v1.6/_tracked_pages.json
  archive/v1.6/about/log/index.html
  archive/v1.6/docs/reference/commands/istioctl/index.html
  archive/v1.6/docs/reference/commands/pilot-agent/index.html
  archive/v1.6/docs/reference/commands/pilot-discovery/index.html
  archive/v1.6/docs/reference/config/index.html
  archive/v1.6/docs/reference/config/istio.operator.v1alpha1/index.html
  archive/v1.6/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  archive/v1.6/en/sitemap.xml
  archive/v1.6/sitemap.xml
  archive/v1.6/zh/_tracked_pages.json
  archive/v1.6/zh/docs/reference/config/installation-options/index.html
  archive/v1.6/zh/docs/setup/additional-setup/cni/index.html
  archive/v1.6/zh/docs/setup/additional-setup/config-profiles/index.html
  archive/v1.6/zh/docs/setup/getting-started/index.html
  archive/v1.6/zh/docs/setup/install/helm/index.html
Labels: cla: yes, release-notes-none, size/M

#8221 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8222 Blog post for 2020 steering election results
  .spelling
  content/en/blog/2020/steering-election-results/index.md
Labels: cherrypick/release-1.7, cla: yes, kind/docs, size/S

#8225 [release-1.7] Blog post for 2020 steering election results
  .spelling
  content/en/blog/2020/steering-election-results/index.md
Labels: cla: no, release-notes-none, size/S

#8227 Release 1.7 (#7998)
  .spelling
  content/en/news/releases/1.6.x/announcing-1.6.11/index.md
  content/en/news/releases/1.7.x/announcing-1.7.3/index.md
  content/en/news/security/istio-security-2020-010/index.md
  data/args.yml
Labels: cherrypick/master, cla: yes, size/M

#8230 Istio-2020-010
  .spelling
  content/en/news/releases/1.6.x/announcing-1.6.11/index.md
  content/en/news/releases/1.7.x/announcing-1.7.3/index.md
  content/en/news/security/istio-security-2020-010/index.md
Labels: cla: yes, size/M

#8235 lint-yaml will fail with pipefail and incoming fix, so remove now
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.yamllint.yml
Labels: cla: yes, size/S

#8233 Update test reference from latest master commit
  go.mod
  go.sum
Labels: cla: yes, size/S

#8236 Fix invalid arg on multicluster doc
  content/en/docs/setup/install/multicluster/index.md
  content/en/docs/setup/install/multicluster/snips.sh
  scripts/doc_owners.sh
Labels: cla: yes, size/XS

#8228 Add more details to security disclosure page
  content/en/about/security-vulnerabilities/index.md
Labels: cherrypick/release-1.7, cla: yes, size/XS

#8239 [release-1.7] Add more details to security disclosure page
  content/en/about/security-vulnerabilities/index.md
Labels: cla: no, release-notes-none, size/XS

#8231 Update test ref to 1.7.3
  Makefile.core.mk
  bin/init.sh
  go.mod
  go.sum
Labels: cla: yes, size/S

#8232 Update test ref to 1.6.11
  Makefile.core.mk
  go.mod
  go.sum
Labels: cla: yes, size/XS

#8243 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
