Repository istio/istio.io, pull requests merged in 2020-06, with the labels that each got.

#7435 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: cla: yes, size/M

#7437 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7415 Add tracing integration pages
  content/en/docs/ops/integrations/certmanager/index.md
  content/en/docs/ops/integrations/grafana/index.md
  content/en/docs/ops/integrations/jaeger/index.md
  content/en/docs/ops/integrations/prometheus/index.md
  content/en/docs/ops/integrations/zipkin/index.md
Labels: cla: yes, size/M

#7438 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#7090 zh-translation: /blog/2019/performance-best-practices/index.md
  content/zh/blog/2019/performance-best-practices/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/XS, translation/chinese

#7396 update doc to use istioctl install
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/ops/configuration/mesh/config-resource-ready/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/reference/config/config-status/index.md
  content/en/docs/reference/config/telemetry/telemetry_v2_with_wasm/index.md
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared/index.md
  content/en/docs/setup/upgrade/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/docs/tasks/observability/kiali/index.md
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/policy-enforcement/enabling-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
  content/en/docs/tasks/security/cert-management/dns-cert/index.md
  content/en/docs/tasks/security/cert-management/dns-cert/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/index.md
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: area/environments, area/user experience, cla: yes, kind/docs, size/M

#7440 Improve test verify functions
  tests/trafficmanagement/ingress/scripts/secure_ingress.sh
  tests/util/verify.sh
Labels: cla: yes, size/L

#7441 Move generally useful "sample_" functions to new "helpers.sh".
  pkg/test/istioio/script.go
  tests/examples/scripts/bookinfo.sh
  tests/security/authz_deny/scripts/authz_deny.sh
  tests/security/authz_jwt/scripts/authz_jwt.sh
  tests/security/authz_tcp/scripts/authz_tcp.sh
  tests/security/plugin_ca_cert/scripts/plugin_ca_cert.sh
  tests/security/scripts/mtls_migration.sh
  tests/trafficmanagement/ingress/scripts/secure_ingress.sh
  tests/trafficmanagement/scripts/circuit_breaking.sh
  tests/trafficmanagement/scripts/mirroring.sh
  tests/trafficmanagement/scripts/tcp_trafficshifting.sh
  tests/util/helpers.sh
  tests/util/samples.sh
Labels: area/test and release, cla: yes, size/L

#7393 Fixed tiny grammar problem.
  content/en/blog/2019/custom-ingress-gateway/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/XS

#7442 Fix missing "sample_" function conversions.
  tests/security/authn_policy/scripts/authn_policy.sh
  tests/security/authz_ingress/scripts/authz_ingress.sh
  tests/trafficmanagement/ingress/scripts/ingress_sni_passthrough.sh
Labels: area/test and release, cla: yes, size/S

#7377 Editorial: Fixed grammar error.
  content/en/blog/2020/multiple-control-planes/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/XS

#7443 [master] Fixed tiny grammar problem.
  content/en/blog/2019/custom-ingress-gateway/index.md
Labels: cla: no, size/XS

#7444 Fix typo in comment
  content/en/docs/ops/integrations/certmanager/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7416 network-issues: Remove "Headless TCP services losing connection".
  content/en/docs/ops/common-problems/network-issues/index.md
  content/pt-br/docs/ops/common-problems/network-issues/index.md
Labels: area/networking, area/security, cla: yes, kind/docs, size/M

#7446 init.sh: Add "make gen-charts".
  bin/init.sh
Labels: area/test and release, cla: yes, size/XS

#7401 Add 1.4 official EOL notice
  content/en/news/support/announcing-1.4-eol-final/index.md
Labels: cherrypick/release-1.6, cla: yes, size/S

#7451 New verify function: _run_and_verify_lines
  tests/trafficmanagement/ingress/scripts/secure_ingress.sh
  tests/trafficmanagement/scripts/circuit_breaking.sh
  tests/trafficmanagement/scripts/request_routing.sh
  tests/trafficmanagement/scripts/tcp_trafficshifting.sh
  tests/util/verify.sh
Labels: cla: yes, size/L

#7452 Rename _run_and_verify_xxx functions to _verify_xxx
  tests/README.md
  tests/configuration/scripts/liveness_and_readiness_probes.sh
  tests/examples/scripts/bookinfo.sh
  tests/security/authn_policy/scripts/authn_policy.sh
  tests/security/authz_deny/scripts/authz_deny.sh
  tests/security/authz_ingress/scripts/authz_ingress.sh
  tests/security/authz_jwt/scripts/authz_jwt.sh
  tests/security/authz_tcp/scripts/authz_tcp.sh
  tests/security/dns_cert/scripts/dns_cert.sh
  tests/security/plugin_ca_cert/scripts/plugin_ca_cert.sh
  tests/security/scripts/mtls_migration.sh
  tests/trafficmanagement/egress/scripts/tls_origination.sh
  tests/trafficmanagement/ingress/scripts/ingress_control.sh
  tests/trafficmanagement/ingress/scripts/ingress_sni_passthrough.sh
  tests/trafficmanagement/ingress/scripts/secure_ingress.sh
  tests/trafficmanagement/scripts/circuit_breaking.sh
  tests/trafficmanagement/scripts/fault_injection.sh
  tests/trafficmanagement/scripts/mirroring.sh
  tests/trafficmanagement/scripts/request_routing.sh
  tests/trafficmanagement/scripts/request_timeouts.sh
  tests/trafficmanagement/scripts/tcp_trafficshifting.sh
  tests/trafficmanagement/scripts/traffic_shifting.sh
  tests/util/verify.sh
Labels: cla: yes, size/L

#7454 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: cla: yes, size/M

#7449 update doc to use istioctl install (#7396)
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/ops/configuration/mesh/config-resource-ready/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/reference/config/config-status/index.md
  content/en/docs/reference/config/telemetry/telemetry_v2_with_wasm/index.md
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/install/multicluster/gateways/index.md
  content/en/docs/setup/install/multicluster/shared/index.md
  content/en/docs/setup/upgrade/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/docs/tasks/observability/kiali/index.md
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/policy-enforcement/enabling-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
  content/en/docs/tasks/security/cert-management/dns-cert/index.md
  content/en/docs/tasks/security/cert-management/dns-cert/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/index.md
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: area/user experience, cla: yes, kind/docs, size/M

#7458 Editorial: Fixed multiple bad verb-vs.-noun forms(+).
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S

#7455 Simplify passing --context to access different cluster
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: area/user experience, cherrypick/release-1.6, cla: yes, kind/docs, size/M

#7459 [release-1.6] Simplify passing --context to access different cluster
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: cla: yes, size/M

#7461 [release-1.6] Update the Makefile path for root cert generation.
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/XS

#7462 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#7464 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7466 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
Labels: cla: yes, size/XS

#7471 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#7445 Add addons blog post
  content/en/blog/2020/addon-rework/index.md
Labels: cherrypick/release-1.6, cla: yes, size/M

#7474 [release-1.6] Add addons blog post
  content/en/blog/2020/addon-rework/index.md
Labels: cla: no, size/M

#7473 [release-1.6] Update release-1.6 branch to use Istio 1.6.1 for testing
  go.mod
  go.sum
Labels: area/test and release, cla: yes, size/S

#7400 PR 1.6.1 release notes
  .spelling
  content/en/news/releases/1.6.x/announcing-1.6.1/index.md
Labels: cherrypick/release-1.6, cla: yes, size/M

#7476 [release-1.6] PR 1.6.1 release notes
  .spelling
  content/en/news/releases/1.6.x/announcing-1.6.1/index.md
  data/args.yml
Labels: cla: yes, size/M

#7475 Fix circuit-breaker snips
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
Labels: cla: yes, size/S

#7348 Add example for proxy.istio.io/config annotation
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: yes, size/S

#7477 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: cla: yes, size/M

#7478 Fix heading for bookinfo sample app in release notes for 1.6.1
  content/en/news/releases/1.6.x/announcing-1.6.1/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/XS

#7483 Fixed release date as it was released yesterday
  content/en/news/releases/1.6.x/announcing-1.6.1/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/XS

#7484 [release-1.6] Fixed release date as it was released yesterday
  content/en/news/releases/1.6.x/announcing-1.6.1/index.md
Labels: cla: yes, size/XS

#7482 [release-1.6] Fix heading for bookinfo sample app in release notes for 1.6.1
  content/en/news/releases/1.6.x/announcing-1.6.1/index.md
Labels: cla: yes, size/XS

#7479 [release-1.6] Add example for proxy.istio.io/config annotation
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: no, size/S

#7485 Add warning to generate
  content/en/docs/setup/install/istioctl/index.md
Labels: cherrypick/release-1.6, cla: yes, size/XS

#7430 Update istio sha for tests to current `master` from `release-1.6`
  Makefile.core.mk
  go.mod
  go.sum
  tests/security/authz_deny/scripts/authz_deny.sh
  tests/security/authz_jwt/scripts/authz_jwt.sh
Labels: cla: yes, size/M

#7463 Fixing typo in fortio command
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7481 Use istiod as core component for profile matrix
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: cherrypick/release-1.6, cla: yes, size/S

#7487 [release-1.6] Add warning to generate
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/XS

#7488 [release-1.6] Use istiod as core component for profile matrix
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: no, size/S

#7489 Fixed code typo
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: cherrypick/release-1.6, cla: yes, ok-to-test, size/XS

#7391 Added Envoy, Go and Istio matchings to Prometheus federation ServiceMonitors
  content/en/docs/ops/best-practices/observability/index.md
Labels: area/config, area/policies and telemetry, cla: yes, kind/docs, ok-to-test, size/XS

#7495 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#7498 replace deprecated policy configuration with peerAuthentication
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: area/user experience, cherrypick/release-1.6, cla: yes, kind/docs, size/S

#7494 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
Labels: cla: yes, size/S

#7493 Add missing cleanup for VirtualService nginx
  content/pt-br/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/XS

#7500 [release-1.6] Add missing cleanup for VirtualService nginx
  content/pt-br/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: cla: yes, size/XS

#7499 [release-1.6] replace deprecated policy configuration with peerAuthentication
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: cla: yes, size/S

#7490 SOURCE_BRANCH_NAME=release-1.6 make update_ref_docs for updates
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: cla: yes, size/M

#7496 Add entry on the (potentially) breaking change for resource visibility in Istio 1.5
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: area/networking, cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/S

#7492 Update to include instructions on moving test ref at patch release
  README.md
Labels: cla: yes, size/S

#7505 [release-1.6] Add entry on the (potentially) breaking change for resource visibility in Istio 1.5
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: cla: no, size/S

#7507 Disable ShellChecking for SC2164
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  content/en/docs/tasks/security/authorization/authz-deny/snips.sh
  content/en/docs/tasks/security/authorization/authz-http/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/en/docs/tasks/security/authorization/authz-tcp/snips.sh
  content/en/docs/tasks/security/cert-management/dns-cert/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/fault-injection/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/request-routing/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  scripts/snip.py
Labels: cla: yes, kind/docs, size/M

#7510 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: cla: yes, size/S

#7491 [release-1.6] Move the release-1.6 branch to use release-1.6 common files.
  README.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: cla: yes, size/M

#7423 add test for Access log
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  tests/observability/access-log_test.go
  tests/observability/main_test.go
  tests/observability/scripts/access_log.sh
Labels: cla: yes, size/L

#7513 Cleanup access log test
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  tests/observability/access-log_test.go
  tests/observability/main_test.go
  tests/observability/scripts/access_log.sh
Labels: cla: yes, size/M

#7465 Migration to a new framework for doc testing
  Makefile.core.mk
  content/en/docs/tasks/traffic-management/fault-injection/test.sh
  content/en/docs/tasks/traffic-management/request-routing/test.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/test.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/test.sh
  tests/README.md
  tests/doc_test_framework.go
  tests/old_tests.mk
  tests/setup/README.md
  tests/setup/profile_default/doc_test.go
  tests/setup/profile_demo/doc_test.go
  tests/setup/profile_none/doc_test.go
  tests/tests.mk
  tests/util/debug.sh
Labels: area/test and release, cla: yes, kind/docs, ok-to-test, size/XL

#7514 Fix typos in CNI doc
  content/en/docs/setup/additional-setup/cni/index.md
Labels: area/networking, cherrypick/release-1.6, cla: yes, kind/docs, size/S

#7529 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: cla: yes, size/L

#7502 Update istioctl docs
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/standalone-operator/index.md
Labels: cherrypick/release-1.6, cla: yes, size/M

#7530 [release-1.6] Update istioctl docs
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/standalone-operator/index.md
Labels: cla: no, size/M

#7531 Add Tetrateio to partner page
  content/en/about/community/partners/index.md
  content/en/about/community/partners/tetrate.png
Labels: cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/XS

#7527 [release-1.6] Release notes for ISTIO-SECURITY-2020-006
  .spelling
  content/en/news/releases/1.5.x/announcing-1.5.5/index.md
  content/en/news/releases/1.6.x/announcing-1.6.2/index.md
  content/en/news/security/istio-security-2020-006/index.md
  data/args.yml
Labels: cla: yes, do-not-merge, size/L

#7525 refactor(telemetry): move wasm telemetry docs to proxy extensions
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/blog/2020/wasm-announce/index.md
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/reference/config/metrics/index.md
  content/en/docs/reference/config/policy-and-telemetry/_index.md
  content/en/docs/reference/config/proxy_extensions/wasm_telemetry/index.md
  content/en/docs/reference/config/telemetry/_index.md
  content/en/docs/reference/config/telemetry/telemetry_v2_with_wasm/index.md
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: area/policies and telemetry, cherrypick/release-1.6, cla: yes, size/M

#7532 Temporarily unpublish Gloo blog post (on 1.6 branch)
  content/en/blog/2020/istio-sds-gloo/index.md
Labels: cla: yes, kind/docs, size/XS

#7534 [release-1.6] Add Tetrateio to partner page
  content/en/about/community/partners/index.md
  content/en/about/community/partners/tetrate.png
Labels: cla: yes, size/XS

#7542 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/gateway/index.html
Labels: cla: yes, size/XS

#7541 Add img redirects
  layouts/index.redir
Labels: cla: yes, size/XS

#7501 Egress Gateway TLS Origination Test Suite
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/tls_test.sh
Labels: area/security, cla: yes, kind/docs, size/XL

#7545 fix bug where *_test.sh doesn't source snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/tls_test.sh
  tests/doc_test_framework.go
Labels: area/test and release, cla: yes, kind/docs, size/XS

#7546 [release-1.6] Update Performance and Scalability Page for Istio release-1.6
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio.svg
Labels: area/perf and scalability, cherrypick/master, cla: yes, size/XXL

#7547 [master] [release-1.6] Update Performance and Scalability Page for Istio release-1.6
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio.svg
Labels: cla: yes, size/XXL

#7528 [release-1.6]Revise istioctl analyze doc page for better understanding
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: area/user experience, cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/L

#7549 [release-1.6] [release-1.6]Revise istioctl analyze doc page for better understanding
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: cla: no, size/L

#7557 Add Portshift to partner page
  content/en/about/community/partners/index.md
  content/en/about/community/partners/portshift.png
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7552 [release-1.6] refactor(telemetry): move wasm telemetry docs to proxy extensions
  content/en/blog/2020/tradewinds-2020/index.md
  content/en/blog/2020/wasm-announce/index.md
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/reference/config/metrics/index.md
  content/en/docs/reference/config/policy-and-telemetry/_index.md
  content/en/docs/reference/config/proxy_extensions/wasm_telemetry/index.md
  content/en/docs/reference/config/telemetry/_index.md
  content/en/docs/reference/config/telemetry/telemetry_v2_with_wasm/index.md
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, size/M

#7558 [release-1.6] Add Portshift to partner page
  content/en/about/community/partners/index.md
  content/en/about/community/partners/portshift.png
Labels: cla: no, size/XS

#7553 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/gateway/index.html
Labels: cla: yes, size/S

#7556 Fix description of Shared control plane
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/XS

#7548 Add a clause indicating that CNI works OOB
  content/en/docs/setup/additional-setup/cni/index.md
Labels: area/networking, cherrypick/release-1.6, cla: yes, size/S

#7559 [release-1.6] Fix description of Shared control plane
  content/en/docs/setup/install/multicluster/shared/index.md
Labels: cla: yes, size/XS

#7560 [release-1.6] Add a clause indicating that CNI works OOB
  content/en/docs/setup/additional-setup/cni/index.md
Labels: cla: no, size/S

#7550 Remove obsolete classes in old istioio framework
  pkg/test/istioio/framework.go
  pkg/test/istioio/pod.go
  pkg/test/istioio/script.go
  pkg/test/istioio/subtest.go
  tests/README.md
  tests/setup/README.md
  tests/setup/profile_default/doc_test.go
  tests/setup/profile_demo/doc_test.go
  tests/setup/profile_none/doc_test.go
  tests/tests.mk
Labels: area/test and release, cla: yes, kind/docs, size/L

#7563 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/M

#7569 Cherrypick 1.5.5 release note
  content/en/news/security/istio-security-2020-006/index.md
Labels: area/test and release, cla: yes, size/S

#7570 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: cla: yes, size/XS

#7573 Update operator status to beta
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/XS

#7578 [release-1.6] Update operator status to beta
  content/en/about/feature-stages/index.md
Labels: cla: yes, size/XS

#7579 Fix typo
  content/en/faq/applications/cassandra.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, needs-ok-to-test, size/XS

#7577 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
Labels: cla: yes, size/M

#7580 [release-1.6] Fix typo
  content/en/faq/applications/cassandra.md
Labels: cla: yes, size/XS

#7562 Add kiali integrations page
  .spelling
  content/en/docs/ops/integrations/kiali/index.md
  content/en/docs/ops/integrations/prometheus/index.md
  content/en/docs/ops/integrations/zipkin/index.md
  content/en/docs/tasks/observability/kiali/index.md
Labels: cla: yes, size/M

#7568 Update prom doc as default has changed
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cla: yes, size/M

#7583 Add release notes for 1.5.6
  content/en/news/releases/1.5.x/announcing-1.5.6/index.md
  content/en/news/security/istio-security-2020-003/index.md
  content/en/news/security/istio-security-2020-005/index.md
  content/en/news/security/istio-security-2020-006/index.md
Labels: area/test and release, cherrypick/master, cla: yes, size/M

#7582 [release-1.6] Update istio test reference to 1.6.3 in prep for release
  go.mod
  go.sum
Labels: area/test and release, cla: yes, size/XS

#7584 [master] Add release notes for 1.5.6
  content/en/news/releases/1.5.x/announcing-1.5.6/index.md
  content/en/news/security/istio-security-2020-003/index.md
  content/en/news/security/istio-security-2020-005/index.md
  content/en/news/security/istio-security-2020-006/index.md
Labels: cla: yes, size/M

#7587 [release-1.6] update install profile output
  content/en/docs/tasks/observability/logs/access-log/index.md
Labels: area/user experience, cla: yes, kind/docs, size/M

#7585 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: cla: yes, size/M

#7575 Release notes for 1.6.3
  .spelling
  content/en/news/releases/1.6.x/announcing-1.6.3/index.md
Labels: cherrypick/release-1.6, cla: yes, size/M

#7551 Release notes for Istio 1.4.10
  content/en/news/releases/1.4.x/announcing-1.4.10/index.md
  content/en/news/security/istio-security-2020-006/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/M

#7588 [release-1.6] Release notes for 1.6.3
  .spelling
  content/en/news/releases/1.6.x/announcing-1.6.3/index.md
  data/args.yml
Labels: cla: yes, size/M

#7596 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: cla: yes, size/XXL

#7592 Update ref docs for 1.6.3
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#7594 Remove old snippet examples
  examples/TestAuthorizationForHTTPServices.txt
  examples/examples__bookinfo.snippets.txt
  examples/tasks__security__mututal_tls_migration.snippets.txt
  examples/tasks__traffic_management__mirroring.snippets.txt
  test/snippet_example.txt
Labels: cla: yes, size/L

#7589 Some random poor quality doc fixes
  content/en/docs/concepts/security/index.md
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
  content/en/docs/tasks/security/authentication/mtls-migration/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
Labels: cla: yes, size/M

#7565 Update istio version for testing
  go.mod
  go.sum
  pkg/test/framework/features/features.yaml
  pkg/test/istioio/builder.go
  pkg/test/istioio/framework.go
  pkg/test/istioio/script.go
  tests/setup/profile_default/doc_test.go
  tests/setup/profile_demo/doc_test.go
  tests/setup/profile_none/doc_test.go
Labels: cla: yes, size/M

#7599 add junit report to build
  tests/tests.mk
Labels: area/test and release, cla: yes, kind/docs, size/XS

#7602 Fix identation of extra tags annotation
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cherrypick/release-1.6, cla: yes, size/XS

#7603 [release-1.6] Fix identation of extra tags annotation
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, size/XS

#7598 Replace deprecated api versions in EN docs
  content/en/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/en/docs/ops/integrations/certmanager/index.md
  content/en/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S

#7604 Update Istio ref
  go.mod
  go.sum
Labels: cla: yes, size/XS

#7605 Publish 1.4.10
  content/en/news/releases/1.4.x/announcing-1.4.10/index.md
  content/en/news/security/istio-security-2020-006/index.md
Labels: cla: yes, kind/docs, size/M

#7606 copy all root files over to root of public folder
  scripts/include_archive_site.sh
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/XS

#7607 Update 1.4.10 release date
  content/en/news/releases/1.4.x/announcing-1.4.10/index.md
Labels: area/config, cla: no, size/XS

#7600 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: cla: yes, size/M

#7610 Specify hosts in ibm kubernetes ingress blog post
  content/en/blog/2020/alb-ingress-gateway-iks/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/S

#7608 [release-1.6] copy all root files over to root of public folder
  scripts/include_archive_site.sh
Labels: cla: yes, size/XS

#7612 Enhance make test_status to list tested and untested docs
  scripts/test_status.sh
Labels: cla: yes, size/M

#7614 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7616 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#7617 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/mixs/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: cla: yes, size/S

#7620 Add proper wait for config calls to tests
  content/en/docs/examples/bookinfo/test.sh
  content/en/docs/ops/configuration/mesh/app-health-check/test.sh
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/test.sh
  content/en/docs/tasks/security/authentication/mtls-migration/test.sh
  content/en/docs/tasks/security/authorization/authz-deny/test.sh
  content/en/docs/tasks/security/authorization/authz-http/test.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
  content/en/docs/tasks/security/authorization/authz-jwt/test.sh
  content/en/docs/tasks/security/authorization/authz-tcp/test.sh
  content/en/docs/tasks/traffic-management/circuit-breaking/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/tls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/test.sh
  content/en/docs/tasks/traffic-management/fault-injection/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/test.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/test.sh
  content/en/docs/tasks/traffic-management/mirroring/test.sh
  content/en/docs/tasks/traffic-management/request-routing/test.sh
  content/en/docs/tasks/traffic-management/request-timeouts/test.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/test.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/test.sh
  tests/util/helpers.sh
Labels: cla: yes, size/L

#7591 Add new entries to clarify multicluster terminology.
  content/en/docs/reference/glossary/primary-cluster.md
  content/en/docs/reference/glossary/remote-cluster.md
Labels: cla: yes, size/S

#7618 update istio.io@customers doc
  content/en/about/community/customers/iherb.svg
  content/en/about/community/customers/index.md
  content/zh/about/community/customers/iherb.svg
  content/zh/about/community/customers/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#7623 fix(customize-metrics): typo
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, ok-to-test, size/XS

#7624 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#7516 Move install documentation to recommend samples/addons/
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/M

#7509 [release-1.5] Add an entry on the (potentially) breaking change for resource visibility
  content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Labels: area/networking, cla: yes, kind/docs, ok-to-test, size/S

#7627 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: cla: yes, size/XS

#7571 Add example to watch multiple namespaces for istio operator
  content/en/docs/setup/install/standalone-operator/index.md
Labels: area/environments, area/user experience, cla: yes, kind/docs, size/S

#7629 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/XS

#7630 Update community page to update Slack URL
  content/en/about/community/join/index.md
Labels: cherrypick/release-1.6, cla: yes, kind/docs, size/XS

#7631 [release-1.6] Update community page to update Slack URL
  content/en/about/community/join/index.md
Labels: cla: yes, size/XS

#7633 [release-1.6] Specify hosts in ibm kubernetes ingress blog post
  content/en/blog/2020/alb-ingress-gateway-iks/index.md
Labels: cla: yes, size/S

#7626 [release-1.6] Change makefile target to fix postsubmit test
  tests/tests.mk
Labels: area/test and release, cla: yes, size/XS

#7632 [release-1.6] fix(customize-metrics): typo
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, size/XS

#7640 More cleanup of the test framework
  pkg/test/istioio/builder.go
  pkg/test/istioio/framework.go
  pkg/test/istioio/input.go
  tests/setup/README.md
Labels: cla: yes, size/L

#7561 fix: kubectl exec command error
  content/zh/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#7638 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
Labels: cla: yes, size/M

#7639 upadte the content/en/docs/examples/virtual-machines/multi-network/in…
  content/en/docs/examples/virtual-machines/multi-network/index.md
Labels: cla: yes, size/XS

#7642 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#7644 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: cla: yes, size/XS
