Repository istio/istio.io, pull requests merged in 2021-01, with the labels that each got.

#8718 fix typo
  content/en/blog/2020/dns-proxy/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, needs-ok-to-test, size/XS

#8723 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8725 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8724 Use correct CRD version
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8730 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8731 [release-1.8] Use correct CRD version
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cla: yes, release-notes-none, size/XS

#8726 fix gateway multiple_revisions upgrade with in-cluster operator.
  content/en/docs/setup/upgrade/gateways/index.md
Labels: area/environments, cherrypick/release-1.8, cla: yes, kind/docs, size/M

#8537 Add Ratelimit Task using Envoy
  .spelling
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, size/L

#8736 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8732 [release-1.8] fix gateway multiple_revisions upgrade with in-cluster operator.
  content/en/docs/setup/upgrade/gateways/index.md
Labels: cla: yes, release-notes-none, size/M

#8739 add missing _index.md file
  content/en/docs/tasks/policy-enforcement/_index.md
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, size/S

#8740 Fix bad list item display format
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, size/S

#8741 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8743 gateway-upgrade: using operator requires namespace to be manually created
  content/en/docs/setup/upgrade/gateways/index.md
Labels: cla: yes, size/XS

#8742 In-place upgrade: filename is optional
  content/en/docs/setup/upgrade/in-place/index.md
Labels: cla: yes, size/XS

#8744 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8745 note the --revision flag for eastwest gateway
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/S

#8750 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8752 Update index.md
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8746 update virtual machine docs and fix multi-network doc
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/L

#8757 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8759 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8761 fix incorrect namespace of sample deploy for VM installation.
  content/en/docs/setup/install/virtual-machine/index.md
  go.sum
Labels: area/environments, cla: yes, kind/docs, size/L

#8737 Update supported platforms pages
  content/en/boilerplates/untested-platform.md
  content/en/docs/setup/platform-setup/MicroK8s/index.md
  content/en/docs/setup/platform-setup/alicloud/index.md
  content/en/docs/setup/platform-setup/azure/index.md
  content/en/docs/setup/platform-setup/gardener/index.md
  content/en/docs/setup/platform-setup/kubesphere/index.md
  content/en/docs/setup/platform-setup/oci/index.md
Labels: area/test and release, cla: yes, kind/docs, size/M

#8763 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8764 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/labels/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8765 [release-1.8] fix incorrect namespace of sample deploy for VM installation.
  content/en/docs/setup/install/virtual-machine/index.md
  go.sum
Labels: cla: yes, release-notes-none, size/L

#8748 Add documentation for DNS proxy
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
Labels: cla: yes, size/L

#8755 fix rendering issues in vm doc
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/L

#8753 [release-1.8] Update index.md
  content/en/blog/2020/proxying-legacy-services-using-egress-gateways/index.md
Labels: cla: no, release-notes-none, size/XS

#8762 [release-1.8] Update supported platforms pages
  content/en/boilerplates/untested-platform.md
  content/en/docs/setup/platform-setup/MicroK8s/index.md
  content/en/docs/setup/platform-setup/alicloud/index.md
  content/en/docs/setup/platform-setup/azure/index.md
  content/en/docs/setup/platform-setup/gardener/index.md
  content/en/docs/setup/platform-setup/kubesphere/index.md
  content/en/docs/setup/platform-setup/oci/index.md
Labels: cla: yes, release-notes-none, size/M

#8767 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/labels/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8768 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8769 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8771 Remove link to istio 1.1 feature stage
  content/en/about/feature-stages/index.md
Labels: cla: yes, kind/docs, size/XS

#8774 Fix link to standard Istio metric
  content/en/docs/concepts/observability/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, ok-to-test, size/XS

#8751 add external authorization task
  .spelling
  content/en/docs/tasks/security/authorization/authz-custom/index.md
Labels: area/security, cla: yes, size/L

#8777 prepare for v1.9 as istio source is already branched
  Makefile.core.mk
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  data/args.yml
Labels: cla: yes, size/S

#8747 Add docs for virtual machine probes
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/M

#8776 [release-1.8] Fix link to standard Istio metric
  content/en/docs/concepts/observability/index.md
Labels: cla: yes, release-notes-none, size/XS

#8780 release notes for Istio 1.8.2
  content/en/news/releases/1.8.x/announcing-1.8.2/index.md
  content/en/news/releases/1.8.x/announcing-1.8/change-notes/index.md
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: cherrypick/release-1.8, cla: yes, size/M

#8781 [release-1.8] release notes for Istio 1.8.2
  content/en/news/releases/1.8.x/announcing-1.8.2/index.md
  content/en/news/releases/1.8.x/announcing-1.8/change-notes/index.md
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/M

#8758 Merge Support Policy with Version info
  content/en/about/release-cadence/index.md
  content/en/about/supported-releases/index.md
  content/en/news/support/announcing-1.0-eol/index.md
  content/en/news/support/announcing-1.1-eol/index.md
  content/en/news/support/announcing-1.2-eol/index.md
  content/en/news/support/announcing-1.3-eol/index.md
  content/en/news/support/announcing-1.4-eol/index.md
  content/en/news/support/announcing-1.5-eol/index.md
  content/en/news/support/announcing-1.6-eol/index.md
Labels: area/test and release, cla: yes, kind/docs, size/L

#8782 Update 1.8.2 release date
  content/en/news/releases/1.8.x/announcing-1.8.2/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8783 [release-1.8] Update 1.8.2 release date
  content/en/news/releases/1.8.x/announcing-1.8.2/index.md
Labels: cla: yes, release-notes-none, size/XS

#8772 Use experimental as feature stage
  content/en/about/feature-stages/index.md
  content/en/boilerplates/experimental.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/reference/config/proxy_extensions/wasm_telemetry/index.md
  content/en/docs/setup/install/virtual-machine/index.md
  content/en/docs/setup/upgrade/gateways/index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cla: yes, kind/docs, size/M

#8778 update Lightstep docs with different instructions based on Satellite …
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
Labels: cla: yes, ok-to-test, size/M

#8787 Fix gateway example
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cla: yes, size/XS

#8784 Add transport api version to rate limiting service.
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, size/XS

#8793 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8795 Update to more recent kubernetes version
  content/en/docs/setup/platform-setup/minikube/index.md
Labels: cla: yes, size/XS

#8789 Fix RateLimit example manifest
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, ok-to-test, size/XS

#8562 Update istio.io/istio ref to 1.9.0-beta.0
  Makefile.core.mk
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/tasks/observability/metrics/customize-metrics/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  go.mod
  go.sum
  tests/util/samples.sh
Labels: cla: yes, size/XL

#8798 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8799 [release-1.8] update Lightstep docs with different instructions based on Satellite …
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
Labels: cla: no, release-notes-none, size/M

#8800 Announce EOL for Istio 1.7.x
  content/en/news/support/announcing-1.7-eol/index.md
Labels: cherrypick/release-1.8, cla: yes, kind/docs, size/S

#8796 Service API task doc test
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
  content/en/docs/tasks/traffic-management/ingress/service-apis/snips.sh
  content/en/docs/tasks/traffic-management/ingress/service-apis/test.sh
Labels: cla: yes, size/L

#8773 Silence curl command
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/examples/microservices-istio/add-new-microservice-version/index.md
  content/en/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/en/docs/examples/microservices-istio/production-testing/index.md
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/ops/configuration/security/root-transition/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/multicluster/verify/index.md
  content/en/docs/setup/install/multicluster/verify/snips.sh
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/snips.sh
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authorization/authz-deny/index.md
  content/en/docs/tasks/security/authorization/authz-deny/snips.sh
  content/en/docs/tasks/security/authorization/authz-http/test.sh
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/index.md
  content/en/docs/tasks/security/authorization/authz-td-migration/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/snips.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/test.sh
  content/en/news/security/istio-security-2020-007/index.md
Labels: cla: yes, size/L

#8803 dashboard controlz: append ns to pod for controlz output
  content/en/docs/ops/diagnostic-tools/controlz/index.md
Labels: cla: yes, community/testing days, size/XS

#8808 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8802 fix mirror task doc
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
Labels: cla: yes, size/XS

#8801 [release-1.8] Announce EOL for Istio 1.7.x
  content/en/news/support/announcing-1.7-eol/index.md
Labels: cla: yes, release-notes-none, size/S

#8811 Fix incorrect YAML casing
  content/en/docs/tasks/traffic-management/mirroring/index.md
Labels: cla: yes, size/XS

#8812 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8813 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8766 update release-1.6.14 release note
  content/en/news/releases/1.6.x/announcing-1.6.14/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8806 Fix example and use actual sample files so that we are ready for doc …
  content/en/docs/ops/configuration/mesh/config-resource-ready/index.md
Labels: cla: yes, size/S

#8814 [release-1.8] update release-1.6.14 release note
  content/en/news/releases/1.6.x/announcing-1.6.14/index.md
Labels: cla: yes, release-notes-none, size/XS

#8804 update latest logging scopes
  content/en/docs/ops/diagnostic-tools/component-logging/index.md
Labels: cla: yes, community/testing days, size/XS

#8809 Fix grafana script
  content/en/docs/ops/integrations/grafana/index.md
Labels: cherrypick/master, cla: yes, size/XS

#8817 [master] Fix grafana script
  content/en/docs/ops/integrations/grafana/index.md
Labels: cla: yes, release-notes-none, size/XS

#8818 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8819 Automator: update common-files@master in istio/istio.io@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8775 Add Liulishuo to customers
  content/en/about/community/customers/index.md
  content/en/about/community/customers/liulishuo.svg
  content/zh/about/community/customers/index.md
  content/zh/about/community/customers/liulishuo.svg
Labels: cla: yes, ok-to-test, size/L, translation/chinese

#8821 vm docs: fix bullets for generated files
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/XS

#8785 Add upgrade notes about 1.7.x to 1.8 regarding http 1xx and 204.
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: cherrypick/release-1.8, cla: yes

#8770 Add notice about centos 8 support
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8825 [release-1.8] Add notice about centos 8 support
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, release-notes-none, size/XS

#8824 [release-1.8] Add upgrade notes about 1.7.x to 1.8 regarding http 1xx and 204.
  content/en/news/releases/1.8.x/announcing-1.8/upgrade-notes/index.md
Labels: cla: yes, release-notes-none, size/XS

#8788 change header for platform per TOC guidance
  content/en/boilerplates/untested-document.md
  content/en/boilerplates/untested-platform.md
  content/en/docs/setup/platform-setup/MicroK8s/index.md
  content/en/docs/setup/platform-setup/alicloud/index.md
  content/en/docs/setup/platform-setup/azure/index.md
  content/en/docs/setup/platform-setup/gardener/index.md
  content/en/docs/setup/platform-setup/kubesphere/index.md
  content/en/docs/setup/platform-setup/oci/index.md
Labels: cla: yes, size/S

#8829 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8779 Update supported k8s versions for 1.9
  data/args.yml
Labels: cla: yes, size/XS

#8822 New analyze codes 135 and 136 for annotation feature phase
  content/en/docs/reference/config/analysis/ist0135/index.md
  content/en/docs/reference/config/analysis/ist0136/index.md
Labels: cla: yes, size/M

#8754 Add info about using Metallb for multi-cluster setup on kind
  .spelling
  content/en/boilerplates/multi-cluster-with-metallb.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote/index.md
Labels: cla: yes, size/S

#8830 Missing profile in the canary update example
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, kind/docs, size/XS

#8816 use different pod for querying kube system pods
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: cherrypick/release-1.8, cla: yes, size/S

#8836 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#8835 Update warning boilerplate for unsupported platforms
  content/en/boilerplates/untested-document.md
Labels: cla: yes, kind/docs, size/XS

#8834 [release-1.8] use different pod for querying kube system pods
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: cla: yes, release-notes-none, size/S

#8838 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8840 Add IST0123 Chinese translate
  content/zh/docs/reference/config/analysis/ist0123/index.md
Labels: area/user experience, cla: yes, kind/docs, size/M, translation/chinese

#8839 Add IST0122 Chinese translate
  content/zh/docs/reference/config/analysis/ist0122/index.md
Labels: cla: yes, ok-to-test, size/M, translation/chinese

#8831 Add IST0137 analysis docs
  content/en/docs/reference/config/analysis/ist0137/index.md
  data/analysis.yaml
Labels: area/user experience, cla: yes, size/M

#8846 Automator: update common-files@release-1.8 in istio/istio.io@release-1.8
  .gitattributes
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8845 Stop recommending binding to localhost
  content/en/faq/applications/cassandra.md
  content/en/faq/applications/elasticsearch.md
  content/en/faq/applications/nifi.md
  content/en/faq/applications/redis.md
  content/en/faq/applications/zookeeper.md
Labels: cla: yes, size/S

#8823 Test Automation for ops/configuration/mesh/config-resource-ready
  content/en/docs/ops/configuration/mesh/config-resource-ready/index.md
  content/en/docs/ops/configuration/mesh/config-resource-ready/snips.sh
  content/en/docs/ops/configuration/mesh/config-resource-ready/test.sh
Labels: cla: yes, size/M

#8844 use bookinfo pod to check envoy version
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: cla: yes, size/XS

#8859 Fix error when trying to run tests on Linux
  Makefile.core.mk
Labels: cla: yes, size/XS

#8860 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8853 Add docs test for VM installation
  content/en/docs/setup/install/virtual-machine/index.md
  content/en/docs/setup/install/virtual-machine/snips.sh
  content/en/docs/setup/install/virtual-machine/test.sh
  pkg/test/istioio/framework.go
Labels: cla: yes, size/L

#8861 Revert "Add IST0137 analysis docs"
  content/en/docs/reference/config/analysis/ist0137/index.md
  data/analysis.yaml
Labels: cla: yes, size/M

#8862 use latest version of dashboard to support k8 1.20
  content/en/docs/setup/platform-setup/kind/index.md
Labels: cla: yes, size/XS

#8855 add sleep
  content/en/docs/tasks/observability/metrics/customize-metrics/test.sh
Labels: cla: yes, size/XS

#8863 Fix typo and minor wording
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
Labels: cla: yes, kind/docs, size/XS

#8864 Remove localhost recommendation
  content/en/docs/ops/deployment/requirements/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8865 [release-1.8] Remove localhost recommendation
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, release-notes-none, size/XS

#8866 Automator: update common-files@release-1.7 in istio/istio.io@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8848 Add missing step to multicluster tests
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/test.sh
Labels: cla: yes, kind/docs, size/XS

#8871 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8872 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8876 Remove root cert transition guide
  content/en/blog/2019/root-transition/index.md
  content/en/docs/ops/configuration/security/root-transition/index.md
Labels: cla: yes, size/L

#8867 Release notes for 1.7.7
  content/en/news/releases/1.7.x/announcing-1.7.7/index.md
Labels: area/test and release, cherrypick/release-1.8, cla: yes, size/S

#8880 [release-1.8] Release notes for 1.7.7
  content/en/news/releases/1.7.x/announcing-1.7.7/index.md
Labels: cla: yes, release-notes-none, size/S

#8881 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8882 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS
