Repository istio/istio.io, pull requests merged in 2021-09, with the labels that each got.

#10272 add responsive video
  src/sass/base/_base.scss
Labels: area/user experience, size/XS, cla: yes, ok-to-test

#10285 [release-1.11] add responsive video
  src/sass/base/_base.scss
Labels: size/XS, cla: yes, release-notes-none

#10239 [release-1.11] Helm can use revision tags
  content/en/boilerplates/revision-tags-default-intro.md
  content/en/boilerplates/revision-tags-default-outro.md
  content/en/boilerplates/revision-tags-middle.md
  content/en/boilerplates/revision-tags-preamble.md
  content/en/boilerplates/revision-tags-prologue.md
  content/en/boilerplates/revision-tags-usage.md
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/boilerplates/snips/revision-tags-prologue.sh
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/upgrade/canary/index.md
  content/en/docs/setup/upgrade/helm/index.md
Labels: size/L, cla: yes, release-notes-none

#10261 Only lint markdown files in some areas of the linting
  scripts/lint_site.sh
Labels: size/S, cla: yes

#10200 Add instructions to enable remote cluster gateways using Helm
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: size/M, cla: yes

#10238 fix overlapping table
  src/sass/base/_base.scss
  src/sass/misc/_article.scss
Labels: area/user experience, size/S, cla: yes, ok-to-test

#10291 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: size/M, cla: yes, auto-merge, release-notes-none

#10292 Fixed typo in cipher suites
  content/en/docs/concepts/security/index.md
  content/zh/docs/concepts/security/index.md
Labels: area/security, kind/docs, size/XS, cla: yes, ok-to-test

#9572 Add doc on Telemetry API Tracing configuration
  .spelling
  content/en/docs/tasks/observability/distributed-tracing/configurability/_index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/mesh-and-proxy-config/index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/telemetry-api/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
Labels: size/L, cla: yes, cherrypick/release-1.11

#10294 Manual cherrypick of 10238
  src/sass/base/_base.scss
  src/sass/misc/_article.scss
Labels: size/S, cla: yes

#10284 [release-1.11] Add release notes for 1.11.2
  content/en/news/releases/1.11.x/announcing-1.11.2/index.md
Labels: size/M, cla: yes

#10296 [release-1.11] [release-1.11] Add release notes for 1.11.2
  content/en/news/releases/1.11.x/announcing-1.11.2/index.md
  data/args.yml
Labels: size/M, cla: yes, release-notes-none

#10295 [release-1.11] Add doc on Telemetry API Tracing configuration
  .spelling
  content/en/docs/tasks/observability/distributed-tracing/configurability/_index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/mesh-and-proxy-config/index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/telemetry-api/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
Labels: size/L, cla: yes, release-notes-none

#10293 [release-1.11] Fixed typo in cipher suites
  content/en/docs/concepts/security/index.md
  content/zh/docs/concepts/security/index.md
Labels: size/XS, cla: yes, release-notes-none

#10287 Update istio test ref to possible 1.11.2
  go.mod
  go.sum
Labels: size/S, cla: yes

#10289 Update ref docs for 1.11.2
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: size/S, cla: yes

#10297 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, cla: yes, auto-merge, release-notes-none

#10300 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, cla: yes, auto-merge, release-notes-none

#10299 1.9 extended support announcements
  content/en/blog/2021/extended-support/extended_support.png
  content/en/blog/2021/extended-support/index.md
  content/en/news/support/announcing-1.9-eol-final/index.md
  content/en/news/support/revised-1.9-eol/index.md
Labels: size/M, cla: yes

#10187 update favicons
  layouts/_default/baseof.html
  layouts/index.redir
  static/favicon.ico
  static/favicons/favicon.ico
  static/favicons/safari-pinned-tab.svg
Labels: area/user experience, size/XS, cla: yes, ok-to-test, cherrypick/release-1.11

#10302 docs: Added Casbin plugin on Ecosystems page
  data/companies.yml
  static/logos/casbin.png
Labels: size/XS, cla: yes, ok-to-test, cherrypick/release-1.11

#10305 [release-1.11] 1.9 extended support announcements
  content/en/blog/2021/extended-support/extended_support.png
  content/en/blog/2021/extended-support/index.md
  content/en/news/support/revised-1.9-eol/index.md
Labels: size/S, cla: yes, release-notes-none

#10303 [release-1.11] update favicons
  layouts/_default/baseof.html
  layouts/index.redir
  static/favicon.ico
  static/favicons/favicon.ico
  static/favicons/safari-pinned-tab.svg
Labels: size/XS, cla: yes, release-notes-none

#10308 Update Supported Version doc
  content/en/docs/releases/supported-releases/index.md
Labels: size/S, cla: yes, cherrypick/release-1.11

#10310 [release-1.11] Update Supported Version doc
  content/en/docs/releases/supported-releases/index.md
Labels: size/S, cla: yes, release-notes-none

#10309 Update index.md typo - Change TSL to TLS
  content/en/docs/ops/configuration/traffic-management/tls-configuration/index.md
Labels: kind/docs, size/XS, cla: yes, cherrypick/master, ok-to-test

#10312 [master] Update index.md typo - Change TSL to TLS
  content/en/docs/ops/configuration/traffic-management/tls-configuration/index.md
Labels: size/XS, cla: yes, release-notes-none

#10306 [release-1.11] docs: Added Casbin plugin on Ecosystems page
  data/companies.yml
  static/logos/casbin.png
Labels: size/XS, cla: yes, release-notes-none

#10313 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10314 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, cla: yes, auto-merge, release-notes-none

#10317 Fix typos
  content/zh/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
Labels: translation/chinese, size/XS, cla: yes, ok-to-test

#10318 Automator: update common-files@release-1.10 in istio/istio.io@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10320 docs: update broken OPA links
  content/en/about/faq/metrics-and-logs/mixer-migration.md
  content/en/blog/2021/better-external-authz/index.md
  content/en/docs/tasks/security/authorization/authz-custom/index.md
Labels: kind/docs, size/XS, cla: yes, ok-to-test

#10323 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10325 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  data/features.yaml
Labels: size/M, cla: yes, auto-merge, release-notes-none

#10327 Automator: update common-files@release-1.9 in istio/istio.io@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10326 update callout shortcode
  layouts/_default/baseof.html
  layouts/shortcodes/quote.html
  layouts/shortcodes/tip.html
Labels: area/user experience, size/S, cla: yes

#10329 [release-1.11] update callout shortcode
  layouts/_default/baseof.html
  layouts/shortcodes/quote.html
  layouts/shortcodes/tip.html
Labels: size/S, cla: yes, release-notes-none

#10279 translation: security/authentication/authn-policy/index.md
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, translation/chinese, size/M, cla: yes

#10330 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10328 Add DoneOps to pro_services providers
  data/companies.yml
  static/logos/doneops.svg
Labels: size/S, cla: yes, ok-to-test, cherrypick/release-1.11

#10307 minor improvements in the Reporting Bugs page
  content/en/docs/releases/bugs/index.md
Labels: size/M, cla: yes, ok-to-test, cherrypick/release-1.11

#10331 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10333 Add Cybrary to users of istio page
  data/companies.yml
  static/logos/cybrary.svg
Labels: size/XS, cla: yes, ok-to-test, cherrypick/release-1.11

#10334 [release-1.11] Add Cybrary to users of istio page
  data/companies.yml
  static/logos/cybrary.svg
Labels: size/XS, cla: yes, release-notes-none

#10337 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/labels/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
Labels: size/M, cla: yes, auto-merge, release-notes-none

#10338 glossary: Update spiffe trust-domain reference link
  content/en/docs/reference/glossary/trust-domain.md
  content/zh/docs/reference/glossary/trust-domain.md
Labels: kind/docs, size/XS, cla: yes, ok-to-test

#10340 [release-1.11] Add DoneOps to pro_services providers
  data/companies.yml
  static/logos/doneops.svg
Labels: size/S, cla: yes, release-notes-none

#10342 [release-1.11] glossary: Update spiffe trust-domain reference link
  content/en/docs/reference/glossary/trust-domain.md
  content/zh/docs/reference/glossary/trust-domain.md
Labels: size/XS, cla: yes, release-notes-none

#10343 Rewrite operator install docs for clarity around creating namespace
  content/en/docs/setup/install/operator/index.md
Labels: area/environments, kind/docs, size/M, cla: yes

#10344 [release-1.11] Rewrite operator install docs for clarity around creating namespace
  content/en/docs/setup/install/operator/index.md
Labels: size/M, cla: yes, release-notes-none

#10345 Automator: update common-files@release-1.11 in istio/istio.io@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10349 Fix grafana dashboard URLS after grafana update
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/index.md
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/test.sh
Labels: size/S, cla: yes

#10336 Update test reference to latest istio
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  go.mod
  go.sum
Labels: size/L, cla: yes

#10352 Update to use the test ref versions of addons.
  Makefile.core.mk
  tests/util/addons.sh
Labels: size/M, cla: yes, cherrypick/master, cherrypick/release-1.9, cherrypick/release-1.10

#10347 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: size/M, cla: yes, auto-merge, release-notes-none

#10358 Manual cherry-pick of #10352
  Makefile.core.mk
  tests/util/addons.sh
Labels: size/M, cla: yes

#10351 Fix to use Istio 1.11.2 images for testing.
  Makefile.core.mk
Labels: size/XS, cla: yes

#10356 [release-1.10] Manual cherry-pick of 10352 and move to 1.10.4
  Makefile.core.mk
  go.mod
  go.sum
  tests/util/addons.sh
Labels: size/M, cla: yes

#10350 Automator: update common-files@release-1.10 in istio/istio.io@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10259 Remove decoration dots
  config.toml
  content/en/blog/2017/_index.md
  content/en/blog/2018/_index.md
  content/en/blog/2019/_index.md
  content/en/blog/2020/_index.md
  content/en/blog/2021/_index.md
  content/en/news/releases/0.x/_index.md
  content/en/news/releases/1.0.x/_index.md
  content/en/news/releases/1.1.x/_index.md
  content/en/news/releases/1.10.x/_index.md
  content/en/news/releases/1.11.x/_index.md
  content/en/news/releases/1.2.x/_index.md
  content/en/news/releases/1.3.x/_index.md
  content/en/news/releases/1.4.x/_index.md
  content/en/news/releases/1.5.x/_index.md
  content/en/news/releases/1.6.x/_index.md
  content/en/news/releases/1.7.x/_index.md
  content/en/news/releases/1.8.x/_index.md
  content/en/news/releases/1.9.x/_index.md
  content/en/news/security/_index.md
  content/en/news/support/_index.md
  content/zh/blog/2017/_index.md
  content/zh/blog/2018/_index.md
  content/zh/blog/2019/_index.md
  content/zh/blog/2020/_index.md
  content/zh/blog/2021/_index.md
  content/zh/news/releases/0.x/_index.md
  content/zh/news/releases/1.0.x/_index.md
  content/zh/news/releases/1.1.x/_index.md
  content/zh/news/releases/1.2.x/_index.md
  content/zh/news/releases/1.3.x/_index.md
  content/zh/news/releases/1.4.x/_index.md
  content/zh/news/releases/1.5.x/_index.md
  content/zh/news/security/_index.md
  content/zh/news/support/_index.md
  layouts/_default/list.html
  layouts/news/release-grid.html
  layouts/news/security-grid.html
  scripts/gen_site.sh
  src/sass/_all.scss
  src/sass/misc/_read-tracking.scss
  src/sass/themes/_dark-theme.scss
  src/sass/themes/_light-theme.scss
  src/ts/readTracking.ts
Labels: area/user experience, size/L, cla: yes, ok-to-test

#10357 [release-1.9] Manual cherry-pick of 10352 - Move to 1.9.8
  Makefile.core.mk
  tests/util/addons.sh
Labels: size/M, cla: yes

#10359 [release-1.11] Remove decoration dots
  config.toml
  content/en/blog/2017/_index.md
  content/en/blog/2018/_index.md
  content/en/blog/2019/_index.md
  content/en/blog/2020/_index.md
  content/en/blog/2021/_index.md
  content/en/news/releases/0.x/_index.md
  content/en/news/releases/1.0.x/_index.md
  content/en/news/releases/1.1.x/_index.md
  content/en/news/releases/1.10.x/_index.md
  content/en/news/releases/1.11.x/_index.md
  content/en/news/releases/1.2.x/_index.md
  content/en/news/releases/1.3.x/_index.md
  content/en/news/releases/1.4.x/_index.md
  content/en/news/releases/1.5.x/_index.md
  content/en/news/releases/1.6.x/_index.md
  content/en/news/releases/1.7.x/_index.md
  content/en/news/releases/1.8.x/_index.md
  content/en/news/releases/1.9.x/_index.md
  content/en/news/security/_index.md
  content/en/news/support/_index.md
  content/zh/blog/2017/_index.md
  content/zh/blog/2018/_index.md
  content/zh/blog/2019/_index.md
  content/zh/blog/2020/_index.md
  content/zh/blog/2021/_index.md
  content/zh/news/releases/0.x/_index.md
  content/zh/news/releases/1.0.x/_index.md
  content/zh/news/releases/1.1.x/_index.md
  content/zh/news/releases/1.2.x/_index.md
  content/zh/news/releases/1.3.x/_index.md
  content/zh/news/releases/1.4.x/_index.md
  content/zh/news/releases/1.5.x/_index.md
  content/zh/news/security/_index.md
  content/zh/news/support/_index.md
  layouts/_default/list.html
  layouts/news/release-grid.html
  layouts/news/security-grid.html
  scripts/gen_site.sh
  src/sass/_all.scss
  src/sass/misc/_read-tracking.scss
  src/sass/themes/_dark-theme.scss
  src/sass/themes/_light-theme.scss
  src/ts/readTracking.ts
Labels: size/L, cla: yes, release-notes-none

#10161 Fix in attribute "name" on "metadata".
  content/en/docs/tasks/security/authorization/authz-custom/index.md
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
Labels: kind/docs, size/XS, cla: yes, cherrypick/master, ok-to-test, cherrypick/release-1.11

#10360 [release-1.11] Fix in attribute "name" on "metadata".
  content/en/docs/tasks/security/authorization/authz-custom/index.md
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
Labels: size/XS, cla: yes, release-notes-none

#10361 [master] Fix in attribute "name" on "metadata".
  content/en/docs/tasks/security/authorization/authz-custom/index.md
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
Labels: size/XS, cla: yes, release-notes-none

#10362 Fix tab content not rendering proper indent
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: size/L, cla: yes

#10365 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/jwt/index.html
Labels: size/S, cla: yes, auto-merge, release-notes-none

#10367 Update Istio test reference to latest commit - Helm install output
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/helm/snips.sh
  go.mod
  go.sum
Labels: size/M, cla: yes

#10368 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, cla: yes, auto-merge, release-notes-none

#10280 translation: Add table of contents test status
  content/zh/docs/examples/_index.md
  content/zh/docs/examples/microservices-istio/_index.md
  content/zh/docs/reference/config/_index.md
  content/zh/docs/reference/config/networking/_index.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/install/_index.md
  content/zh/docs/setup/install/multicluster/_index.md
  content/zh/docs/setup/platform-setup/_index.md
  content/zh/docs/tasks/observability/distributed-tracing/_index.md
  content/zh/docs/tasks/security/_index.md
  content/zh/docs/tasks/traffic-management/_index.md
Labels: kind/docs, translation/chinese, size/S, cla: yes

#10346 [ZH] delete extra pages in the FAQ setup section
  content/zh/about/faq/setup/consul-app-not-working.md
  content/zh/about/faq/setup/consul-unset-context.md
  content/zh/about/faq/setup/k8s-migrating.md
Labels: kind/docs, translation/chinese, size/S, cla: yes

#10374 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10373 docs: update Oracle Cloud Infrastructure platform setup documentation
  content/en/docs/setup/platform-setup/oci/index.md
Labels: kind/docs, size/M, ok-to-test

#10378 [release-1.11] docs: update Oracle Cloud Infrastructure platform setup documentation
  content/en/docs/setup/platform-setup/oci/index.md
Labels: size/M, cla: yes, release-notes-none

#10377 Add 1.11.3 release notes
  .spelling
  content/en/news/releases/1.11.x/announcing-1.11.3/index.md
Labels: area/test and release, size/M

#10379 [release-1.11] Add 1.11.3 release notes
  .spelling
  content/en/news/releases/1.11.x/announcing-1.11.3/index.md
  data/args.yml
Labels: size/M, cla: yes, release-notes-none

#10369 Update the reference docs for 1.11.3
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/M

#10370 Update test reference to point to 1.11.3
  go.mod
  go.sum
Labels: size/S

#10366 Allow overriding istio/api Git URL for local checking
  Makefile.core.mk
  scripts/grab_reference_docs.sh
Labels: size/S, cla: yes, ok-to-test

#10257 [release-1.11] zh-translation:reference/config/proxy_extensions/metadata_exchange
  content/zh/docs/reference/config/proxy_extensions/metadata_exchange/index.html
Labels: translation/chinese, size/M, cla: yes, release-notes-none

#10385 Test iptables workaround
  bin/init.sh
Labels: size/XS, cherrypick/release-1.11

#10389 Remove mixer from traffic problems troubleshoot guide.
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: size/S, cherrypick/release-1.1

#10391 [release-1.11] Remove mixer from traffic problems troubleshoot guide.
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: size/S, cla: yes, release-notes-none

#10364 Improve DestinationRule Security Best Practices
  content/en/docs/ops/best-practices/security/index.md
Labels: area/security, area/networking, size/S, cla: yes

#10392 Add upgrade note about new hostPath at CNI DaemomSet.
  .spelling
  content/en/news/releases/1.11.x/announcing-1.11/upgrade-notes/index.md
Labels: size/XS, cla: yes, cherrypick/release-1.11

#10394 [release-1.11] Add upgrade note about new hostPath at CNI DaemomSet.
  .spelling
  content/en/news/releases/1.11.x/announcing-1.11/upgrade-notes/index.md
Labels: size/XS, cla: yes, release-notes-none

#10393 Update index.md
  content/en/blog/2021/discovery-selectors/index.md
Labels: kind/docs, size/XS, cla: yes, ok-to-test
