Repository istio/istio.io, pull requests merged in 2021-02, with the labels that each got.

#8887 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8847 Simplify CRD backup command
  content/en/docs/setup/install/helm/index.md
Labels: cherrypick/master, cla: yes, size/XS

#8889 [master] Simplify CRD backup command
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, release-notes-none, size/XS

#8868 Add troubleshooting guide for VMs
  content/en/docs/ops/diagnostic-tools/virtual-machines/index.md
Labels: cla: yes, size/L

#8852 Update istio test ref to 1.9.0-rc.0
  go.mod
  go.sum
Labels: cla: yes, size/S

#8879 [release-1.7] Update test reference to 1.7.7
  Makefile.core.mk
  go.mod
  go.sum
Labels: cla: yes, size/M

#8826 [release-1.8] Update the istio test reference to 1.8.2
  go.mod
  go.sum
Labels: cla: yes, size/S

#8873 fix jwt test
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
Labels: cla: yes, size/S

#8833 [release-1.8] change header for platform per TOC guidance (#8788)
  content/en/boilerplates/untested-document.md
  content/en/boilerplates/untested-platform.md
  content/en/docs/setup/platform-setup/MicroK8s/index.md
  content/en/docs/setup/platform-setup/alicloud/index.md
  content/en/docs/setup/platform-setup/azure/index.md
  content/en/docs/setup/platform-setup/gardener/index.md
  content/en/docs/setup/platform-setup/kubesphere/index.md
  content/en/docs/setup/platform-setup/oci/index.md
Labels: cla: yes, kind/docs, size/S

#8893 Kops Docs: Fix ServiceAccountVolume proposed configuration
  content/en/docs/setup/platform-setup/kops/index.md
Labels: area/environments, area/user experience, cla: yes, kind/docs, ok-to-test, size/XS

#8899 Few updates to install options
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, size/S

#8902 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8895 Change baseEjectionTime to be less than maxEjectionTime (default 300s)
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/snips.sh
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/failover/snips.sh
Labels: cla: yes, size/XS

#8896 Update sidecar-injection doc based on 1.9.0-rc.0
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, kind/docs, size/M

#8904 Improve the plug-in cert task.
  .spelling
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/index.md
Labels: area/security, cherrypick/release-1.9, cla: yes, size/M

#8892 VMs: add doc test, re-org examples
  content/en/blog/2018/egress-tcp/index.md
  content/en/docs/examples/virtual-machines/_index.md
  content/en/docs/examples/virtual-machines/index.md
  content/en/docs/examples/virtual-machines/multi-network/index.md
  content/en/docs/examples/virtual-machines/single-network/index.md
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/examples/virtual-machines/test.sh
  content/en/docs/examples/virtual-machines/vm-bookinfo.svg
  content/en/docs/setup/install/virtual-machine/common.sh
  content/en/docs/setup/install/virtual-machine/test.sh
  content/en/faq/security/cert-lifetime-config.md
  tests/util/samples.sh
Labels: cla: yes, size/XL

#8870 Add VM architecture diagram
  content/en/docs/ops/deployment/vm-architecture/index.md
  content/en/docs/ops/deployment/vm-architecture/multi-network.svg
  content/en/docs/ops/deployment/vm-architecture/service-selector.svg
  content/en/docs/ops/deployment/vm-architecture/single-network.svg
Labels: cla: yes, size/L

#8906 Improve security concept.
  content/en/docs/concepts/security/index.md
Labels: area/security, cherrypick/release-1.9, cla: yes, size/M

#8914 [release-1.8] Update to use the release-1.8 common-files.
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: cla: yes, size/M

#8915 Need to update common-files branch when creating a new version
  scripts/create_version.sh
Labels: cla: yes, size/XS

#8894 Add tip to Customize Metrics about waiting (delay needed to limit test flakes)
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: cla: yes, size/XS

#8920 Move grpc metrics to the right place.
  content/en/docs/reference/config/metrics/index.md
Labels: cherrypick/release-1.8, cla: yes, size/XS

#8921 [release-1.8] Move grpc metrics to the right place.
  content/en/docs/reference/config/metrics/index.md
Labels: cla: yes, release-notes-none, size/XS

#8919 Update istio test ref to 1.9.0
  go.mod
  go.sum
Labels: cla: yes, size/S

#8911 remove tcp health check
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
Labels: cla: yes, size/M

#8898 Fix helm docs for Istio 1.9.0
  content/en/boilerplates/helm-hub-tag.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/M

#8925 release notes for 1.8.3
  content/en/news/releases/1.8.x/announcing-1.8.3/index.md
Labels: cherrypick/release-1.8, cla: yes, size/M

#8926 [release-1.8] release notes for 1.8.3
  content/en/news/releases/1.8.x/announcing-1.8.3/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/M

#8927 Improve sidecar injector documentation
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, size/L

#8884 Release notes for 1.9
  .spelling
  content/en/news/releases/1.9.x/_index.md
  content/en/news/releases/1.9.x/announcing-1.9/change-notes/index.md
  content/en/news/releases/1.9.x/announcing-1.9/upgrade-notes/index.md
Labels: cla: yes, size/L

#8910 1.9.0 announcement blog
  .spelling
  content/en/about/feature-stages/index.md
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
  content/en/news/releases/1.9.x/_index.md
  content/en/news/releases/1.9.x/announcing-1.9/_index.md
Labels: cla: yes, kind/docs, size/L

#8933 Missing make gen during branch cut (update links in snips.sh)
  scripts/create_version.sh
Labels: cla: yes, size/XS

#8934 mark v1.8 as archived
  config.toml
  data/args.yml
Labels: cla: yes, kind/docs, size/XS

#8918 Add doc about WebAssembly module remote load.
  .spelling
  content/en/docs/ops/configuration/extensibility/_index.md
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: cherrypick/release-1.9, cla: yes, size/L

#8941 Add upgrade notice about XDS v2
  content/en/news/releases/1.9.x/announcing-1.9/upgrade-notes/index.md
Labels: cherrypick/release-1.9, cla: yes, size/M

#8940 [release-1.9] Add doc about WebAssembly module remote load. (#8918)
  .spelling
  content/en/docs/ops/configuration/extensibility/_index.md
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: cla: yes, size/L

#8939 A couple of minor edits to the VM Architecture Page
  content/en/docs/ops/deployment/vm-architecture/index.md
Labels: cherrypick/release-1.9, cla: yes, kind/docs, size/S

#8938 Wasm remote load release notes
  content/en/news/releases/1.9.x/announcing-1.9/change-notes/index.md
Labels: cherrypick/release-1.9, cla: yes, size/XS

#8944 [release-1.9] Wasm remote load release notes
  content/en/news/releases/1.9.x/announcing-1.9/change-notes/index.md
Labels: cla: yes, release-notes-none, size/XS

#8942 [release-1.9] Add upgrade notice about XDS v2
  content/en/news/releases/1.9.x/announcing-1.9/upgrade-notes/index.md
Labels: cla: yes, release-notes-none, size/M

#8946 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8943 [release-1.9] A couple of minor edits to the VM Architecture Page
  content/en/docs/ops/deployment/vm-architecture/index.md
Labels: cla: yes, release-notes-none, size/S

#8947 Added section for remote wasm extensions to 1.9 announcement.
  content/en/news/releases/1.9.x/announcing-1.9/_index.md
Labels: cherrypick/release-1.9, cla: yes, size/XS

#8953 [release-1.9] Added section for remote wasm extensions to 1.9 announcement.
  content/en/news/releases/1.9.x/announcing-1.9/_index.md
Labels: cla: yes, release-notes-none, size/XS

#8955 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/envoy-filter/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8945 add Wasm extension feature stage.
  content/en/about/feature-stages/index.md
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: cherrypick/release-1.9, cla: yes, size/S

#8959 Revert "Improve sidecar injector documentation (#8927)"
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, size/L

#8956 [release-1.9] add Wasm extension feature stage.
  content/en/about/feature-stages/index.md
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: cla: yes, release-notes-none, size/S

#8928 Add warning and workarounds for revision validation bug
  .spelling
  content/en/docs/setup/upgrade/canary/index.md
Labels: area/environments, cherrypick/release-1.9, cla: yes, kind/docs, size/XS

#8961 [release-1.9] Add warning and workarounds for revision validation bug
  .spelling
  content/en/docs/setup/upgrade/canary/index.md
Labels: cla: yes, release-notes-none, size/XS

#8963 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8890 add ext-authz blog
  content/en/blog/2021/_index.md
  content/en/blog/2021/better-external-authz/external_authz.svg
  content/en/blog/2021/better-external-authz/index.md
  content/en/news/releases/1.9.x/announcing-1.9/_index.md
  content/en/news/releases/1.9.x/announcing-1.9/change-notes/index.md
Labels: area/security, cherrypick/release-1.9, cla: yes, size/XL

#8950 Update test reference on main branch to istio.io/istio master
  Makefile.core.mk
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  go.mod
  go.sum
Labels: cla: yes, size/M

#8964 [release-1.9] add ext-authz blog
  content/en/blog/2021/_index.md
  content/en/blog/2021/better-external-authz/external_authz.svg
  content/en/blog/2021/better-external-authz/index.md
  content/en/news/releases/1.9.x/announcing-1.9/_index.md
  content/en/news/releases/1.9.x/announcing-1.9/change-notes/index.md
Labels: cla: yes, release-notes-none, size/XL

#8960 Update make gen to do a format-go and check in updated files
  Makefile.core.mk
  pkg/test/istioio/script.go
  pkg/test/istioio/snapshot.go
  tests/setup/multicluster/doc_test.go
  tests/setup/profile_default/doc_test.go
  tests/setup/profile_demo/doc_test.go
  tests/setup/profile_none/doc_test.go
Labels: cla: yes, size/S

#8965 Expand istio_version variable in snips
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  scripts/snip.py
Labels: cla: yes, size/S

#8901 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#8967 Make trace pod annotation warning more visible.
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, size/XS

#8975 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/L

#8978 Remove alpha warning from VM install guide
  content/en/docs/setup/install/virtual-machine/index.md
Labels: area/environments, cherrypick/release-1.9, cla: yes, kind/docs, size/XS

#8981 [release-1.9] Remove alpha warning from VM install guide
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, release-notes-none, size/XS

#8972 fix command in the ext-authz blog
  content/en/blog/2021/better-external-authz/index.md
Labels: area/security, cherrypick/release-1.9, cla: yes, size/XS

#8982 [release-1.9] fix command in the ext-authz blog
  content/en/blog/2021/better-external-authz/index.md
Labels: cla: yes, release-notes-none, size/XS

#8983 IstioCon blog post
  .spelling
  content/en/blog/2021/istiocon-2021-program/index.md
  content/en/blog/2021/istiocon-2021-program/istiocon-program.png
Labels: cherrypick/master, cla: yes, size/M

#8970 [release-1.8] Make trace pod annotation warning more visible.
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: yes, release-notes-none, size/XS

#8971 [release-1.9] Make trace pod annotation warning more visible.
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cla: yes, release-notes-none, size/XS

#8976 Update customize prom scraping instruction.
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cla: yes, size/M

#8987 [release-1.9] Update customize prom scraping instruction.
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cla: yes, release-notes-none, size/M

#8984 [master] IstioCon blog post
  .spelling
  content/en/blog/2021/istiocon-2021-program/index.md
  content/en/blog/2021/istiocon-2021-program/istiocon-program.png
Labels: cla: yes, release-notes-none, size/M

#8988 s/service-apis/gateway-api/
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: area/networking, cherrypick/release-1.9, cla: yes, size/XS

#8990 Revert "Remove rbac instruction for GKE"
  content/en/docs/setup/platform-setup/gke/index.md
Labels: cla: yes, size/S

#8989 [release-1.9] s/service-apis/gateway-api/
  content/en/docs/tasks/traffic-management/ingress/service-apis/index.md
Labels: cla: yes, release-notes-none, size/XS

#8897 Update observability best practices
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cherrypick/release-1.9, cla: yes, kind/docs, size/S

#8948 Add doc about how to work around missing metric expiry.
  .spelling
  content/en/faq/metrics-and-logs/metric-expiry.md
  content/en/faq/metrics-and-logs/telemetry-v1-vs-v2.md
Labels: cherrypick/release-1.9, cla: yes, size/S

#8952 Add initial security best practices documentation
  content/en/docs/ops/best-practices/security/index.md
Labels: cla: yes, size/L

#8994 [release-1.9] Add doc about how to work around missing metric expiry.
  .spelling
  content/en/faq/metrics-and-logs/metric-expiry.md
  content/en/faq/metrics-and-logs/telemetry-v1-vs-v2.md
Labels: cla: yes, release-notes-none, size/S

#8962 Clarify Prometheus TLS settings.
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cherrypick/release-1.9, cla: yes, size/M

#8996 [release-1.9] Clarify Prometheus TLS settings.
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cla: yes, release-notes-none, size/M

#8997 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#8998 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#8993 [release-1.9] Update observability best practices
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cla: yes, release-notes-none, size/S

#9003 [release-1.9] Add initial security best practices documentation
  content/en/docs/ops/best-practices/security/index.md
Labels: cla: yes, release-notes-none, size/L

#9004 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9000 Make attribute gen yaml file valid.
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: cherrypick/release-1.9, cla: yes

#9010 [release-1.9] Make attribute gen yaml file valid.
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: cla: yes, release-notes-none, size/M

#9002 Fix the client IP addresses for the authz ingress task
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
Labels: area/security, cherrypick/release-1.9, cla: yes, size/S

#9009 Fix link to Configuration title
  content/en/docs/ops/integrations/prometheus/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#9011 [release-1.9] Fix the client IP addresses for the authz ingress task
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
Labels: cla: yes, release-notes-none, size/S

#9016 [release-1.9] Bump basic auth Wasm extension version.
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: cla: yes, size/XS

#9019 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9021 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/M

#9018 Use istio ecosystem wasm extensions repo in extensibility concept page.
  content/en/docs/concepts/wasm/index.md
Labels: cherrypick/release-1.9, cla: yes, size/S

#9026 [release-1.9] Use istio ecosystem wasm extensions repo in extensibility concept page.
  content/en/docs/concepts/wasm/index.md
Labels: cla: yes, release-notes-none, size/S

#8957 add a troubleshooting guide for multicluster
  content/en/docs/ops/diagnostic-tools/multicluster/index.md
  content/en/docs/ops/diagnostic-tools/virtual-machines/index.md
Labels: cla: yes, size/L

#9034 Remove fixed limitation warning
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: cla: yes, size/M

#9035 Fixed "are is" to "are" and addressed an incorrect link
  content/en/boilerplates/helm-hub-tag.md
  content/en/docs/setup/install/helm/index.md
Labels: cla: yes, kind/docs, needs-ok-to-test, ok-to-test, size/XS

#9032 Fixed "i.e." to standard "i.e.,".
  content/en/faq/distributed-tracing/how-envoy-based-tracing-works.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/XS

#9030 Fixed "byte" to "bytes" (2 occurrences).
  content/en/docs/reference/config/metrics/index.md
Labels: cherrypick/master, cla: yes, ok-to-test, size/XS

#9031 Fixed "setup" to "set up" (verb case).
  content/en/docs/tasks/observability/gateways/index.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/XS

#9033 Fixed "Per pod" to "Per-pod" (used as adjective).
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
Labels: cherrypick/master, cla: yes, kind/docs, ok-to-test, size/XS

#9036 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9022 fix circuit breaker task
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
Labels: cherrypick/release-1.9, cla: yes, ok-to-test, size/XS

#9020 Add documentation for Analysis messsage IST0134 ServiceEntryAddresses…
  content/en/docs/reference/config/analysis/ist0134/index.md
Labels: cla: yes, kind/docs, size/M

#9025 Add blog for zero configuration Istio
  content/en/blog/2021/zero-config-istio/index.md
Labels: cla: yes, size/M

#9045 Fix istio.io tests for newer kubectl
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
Labels: cla: yes, size/S

#9046 Fix istio.io tests when moving to later kubectl
  tests/util/addons.sh
Labels: cla: yes, size/XS

#9042 [release-1.9] fix circuit breaker task
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
Labels: cla: yes, release-notes-none, size/XS

#9047 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/proxy_extensions/accesslogpolicy/index.html
  content/en/docs/reference/config/proxy_extensions/attributegen/index.html
  content/en/docs/reference/config/proxy_extensions/metadata_exchange/index.html
  content/en/docs/reference/config/proxy_extensions/stackdriver/index.html
  content/en/docs/reference/config/proxy_extensions/stats/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9048 Ignore error on first kiali apply
  tests/util/addons.sh
Labels: cla: yes, size/XS

#9049 Ignore some errors
  content/en/docs/setup/additional-setup/external-controlplane/test.sh
Labels: cla: yes, size/XS

#9044 Fix syntax on local rate limiting
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cherrypick/release-1.9, cla: yes, kind/docs, ok-to-test, size/XS

#8913 Add cross references to virtual machine docs
  content/en/docs/ops/diagnostic-tools/virtual-machines/index.md
  content/en/docs/setup/install/virtual-machine/index.md
Labels: cla: yes, size/XS

#9058 a note to increase memory
  content/en/docs/setup/platform-setup/kind/index.md
Labels: cherrypick/master, cla: yes, size/XS

#9043 update authz troubleshoot common problems
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: area/security, cherrypick/release-1.9, cla: yes, size/M

#9017 Add out-of-mesh server metadata info into telemetry v2 faq.
  content/en/faq/metrics-and-logs/telemetry-v1-vs-v2.md
Labels: cherrypick/release-1.9, cla: yes, size/XS

#9060 [release-1.9] update authz troubleshoot common problems
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: cla: yes, release-notes-none, size/M

#9061 [release-1.9] Add out-of-mesh server metadata info into telemetry v2 faq.
  content/en/faq/metrics-and-logs/telemetry-v1-vs-v2.md
Labels: cla: yes, release-notes-none, size/XS

#9054 Release notes for 1.7.8
  content/en/news/releases/1.7.x/announcing-1.7.8/index.md
Labels: cherrypick/release-1.9, cla: yes

#9064 [release-1.9] Release notes for 1.7.8
  content/en/news/releases/1.7.x/announcing-1.7.8/index.md
Labels: cla: yes, release-notes-none, size/S

#9005 Announce EOL for Istio 1.7
  content/en/news/support/announcing-1.7-eol-final/index.md
Labels: cherrypick/release-1.9, cla: yes, size/S

#9066 Announce EOL for Istio 1.7 (#9005)
  content/en/news/support/announcing-1.7-eol-final/index.md
Labels: cla: yes, size/S

#9068 Add suggested additions to security dock
  content/en/docs/ops/best-practices/security/index.md
Labels: cla: yes, size/M

#9069 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9067 [release-1.9] Bump basic auth 1.9 Wasm extension module to 1.9.2
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: cla: yes, size/XS

#9071 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9056 Update istio test ref to 1.7.8
  go.mod
  go.sum
Labels: cla: yes, size/XS

#9055 [release-1.9] Add blog for zero configuration Istio
  content/en/blog/2021/zero-config-istio/index.md
Labels: cherrypick/master, cla: yes, release-notes-none, size/M

#9073 [master] [release-1.9] Add blog for zero configuration Istio
  content/en/blog/2021/zero-config-istio/index.md
Labels: cla: yes, release-notes-none, size/S

#9063 Manual cherry picks of #9038-#9041
  content/en/docs/reference/config/metrics/index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
  content/en/docs/tasks/observability/gateways/index.md
  content/en/faq/distributed-tracing/how-envoy-based-tracing-works.md
Labels: cla: yes, size/S

#9059 [master] a note to increase memory
  content/en/docs/setup/platform-setup/kind/index.md
Labels: cla: yes, release-notes-none, size/XS

#9074 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9072 fix workaround for revision validation bug
  .spelling
  content/en/docs/setup/upgrade/canary/index.md
Labels: cla: yes, kind/docs, size/S

#9077 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
