Repository istio/istio.io, pull requests merged in 2021-07, with the labels that each got.

#10020 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/security/jwt/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#10017 [release-1.10] Update test reference to 1.10.2
  Makefile.core.mk
  bin/init.sh
  go.mod
  go.sum
Labels: cla: yes, size/M

#10012 routeConfiguration.vhost.name use empty string as wildcard
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, size/XS

#10018 Cherry pick change forward for testing private built releases
  bin/init.sh
Labels: cla: yes, size/XS

#10026 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10027 Blog for Istio Community Meetup China in Chinese
  content/zh/blog/2021/_index.md
  content/zh/blog/2021/istiomeetups-china/index.md
Labels: cla: yes, size/M, translation/chinese

#10022 Add cloudzone to pro_services
  data/companies.yml
  static/logos/cloudzone.svg
Labels: cla: yes, ok-to-test, size/L

#10028 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10031 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9955 zh-translation/about/faq/security/mysql-with-mtls.md
  content/zh/about/faq/security/mysql-with-mtls.md
Labels: cla: yes, size/M, translation/chinese

#10025 Blog for Istio Community Meetup China
  .spelling
  content/en/blog/2021/istio-community-meetup-china/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/M

#10029 [release-1.10] Blog for Istio Community Meetup China in Chinese
  content/zh/blog/2021/_index.md
  content/zh/blog/2021/istiomeetups-china/index.md
Labels: cla: yes, release-notes-none, size/M

#10033 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/M

#10035 [release-1.10] Blog for Istio Community Meetup China
  .spelling
  content/en/blog/2021/istio-community-meetup-china/index.md
Labels: cla: yes, release-notes-none, size/M

#10036 Automator: update common-files@release-1.10 in istio/istio.io@release-1.10
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#10034 zh-translation: docs/releases/security-vulnerabilities/index.md
  content/zh/about/faq/general/istio-doesnt-work.md
  content/zh/about/faq/general/roadmap.md
  content/zh/docs/releases/security-vulnerabilities/index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#10039 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10040 Automator: update common-files@release-1.9 in istio/istio.io@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10024 add links to modal and make description/details clear
  data/companies.yml
  layouts/shortcodes/interactive_panel_modal.html
  src/sass/misc/_modal.scss
Labels: cla: yes, kind/docs, kind/site infra, new-site, size/S

#10041 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#10042 components section has been missed, need to add in
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cla: yes, size/S

#10045 [release-1.10] components section has been missed, need to add in
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cla: yes, release-notes-none, size/S

#9961 add normalization guideline in security best practice
  content/en/docs/ops/best-practices/security/index.md
Labels: area/security, cla: yes, size/M

#10048 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XL

#10049 zh-translation: /docs/releases/contribute/_index.md
  content/zh/docs/releases/contribute/_index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#10030 Remove warning about removed limitation
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: cherrypick/release-1.10, cla: yes, size/S

#10032 Add the information that you can concatenate CA certs
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: area/environments, area/security, cherrypick/master, cla: yes, kind/docs, size/XS

#10057 [master] Add the information that you can concatenate CA certs
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: cla: yes, release-notes-none, size/XS

#10058 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10055 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#10054 [release-1.10] Remove warning about removed limitation
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: cla: yes, release-notes-none, size/S

#10056 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/M

#10051 fix ratelimit doc
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#10060 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#10061 Add NCC security assessment announcement blog
  .spelling
  content/en/blog/2021/ncc-security-assessment/NCC_Group_Google_GOIST2005_Report_2020-08-06_v1.1.pdf
  content/en/blog/2021/ncc-security-assessment/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/L

#10066 Update istio test reference
  go.mod
  go.sum
Labels: cla: yes, size/S

#10067 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9983 Update for simplified istiod-remote charts
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
Labels: cla: yes, size/M

#10069 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10070 Automator: update common-files@release-1.9 in istio/istio.io@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10072 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10073 Automator: update common-files@release-1.10 in istio/istio.io@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10047 Update helm upgrade instructions
  content/en/docs/setup/upgrade/helm/index.md
Labels: cla: yes, kind/docs, size/S

#10075 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  data/features.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#10074 [release-1.10] Update helm upgrade instructions
  content/en/docs/setup/upgrade/helm/index.md
Labels: cla: yes, release-notes-none, size/S

#10062 zh-translation/docs/releases/feature-stages/index.md
  content/zh/docs/releases/feature-stages/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/L, translation/chinese

#10078 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#10064 zh-translation: /content/en/docs/tasks/security/cert-management/custo…
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/L, translation/chinese

#10065 zh-translation/content/en/docs/tasks/traffic-management/ingress/secur…
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: cla: yes, kind/docs, size/XS

#9996 zh-translation: content/zh/docs/ops/best-practices/observability
  content/zh/docs/ops/best-practices/observability/index.md
  content/zh/docs/ops/best-practices/observability/production-prometheus.svg
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#10081 No longer need this warning about Kiali addon install.
  content/en/docs/ops/integrations/kiali/index.md
Labels: cherrypick/release-1.11, cla: yes, kind/docs

#10082 Update for branch cut
  Makefile.core.mk
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: cla: yes, size/L

#10077 [release-1.10] zh-translation/docs/releases/feature-stages/index.md
  content/zh/docs/releases/feature-stages/index.md
Labels: cla: yes, release-notes-none, size/L

#10080 [release-1.10] zh-translation: /content/en/docs/tasks/security/cert-management/custo…
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cla: yes, release-notes-none, size/L

#10083 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#10059 Add release notes for 1.10.3
  .spelling
  content/en/news/releases/1.10.x/announcing-1.10.3/index.md
Labels: cla: yes, kind/docs, size/S

#10088 [release-1.10] Add release notes for 1.10.3
  .spelling
  content/en/news/releases/1.10.x/announcing-1.10.3/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/S

#10089 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/S

#10087 Add command reference for install-cni.
  content/en/docs/reference/commands/install-cni/index.html
  scripts/grab_reference_docs.sh
Labels: cla: yes, size/XL

#10091 Mark concept docs as `test: n/a`
  content/en/docs/concepts/observability/index.md
  content/en/docs/concepts/security/index.md
  content/en/docs/concepts/traffic-management/index.md
  content/en/docs/ops/best-practices/security/index.md
  content/en/docs/ops/best-practices/traffic-management/index.md
  content/en/docs/ops/common-problems/injection/index.md
  content/en/docs/ops/common-problems/network-issues/index.md
  content/en/docs/ops/common-problems/observability-issues/index.md
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/en/docs/ops/deployment/requirements/index.md
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
Labels: cla: yes, size/S

#10092 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10098 Minor typo in cert-manager documentation
  content/en/docs/ops/integrations/certmanager/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/XS

#10099 [release-1.10] Minor typo in cert-manager documentation
  content/en/docs/ops/integrations/certmanager/index.md
Labels: cla: yes, release-notes-none, size/XS

#10097 Samples referenced was in incorrect directory
  content/en/docs/setup/install/istioctl/index.md
Labels: cla: yes, kind/docs, size/XS

#10096 Announcing 1.9.7
  .spelling
  content/en/news/releases/1.9.x/announcing-1.9.7/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/S

#10105 [release-1.10] Announcing 1.9.7
  .spelling
  content/en/news/releases/1.9.x/announcing-1.9.7/index.md
Labels: cla: yes, release-notes-none, size/S

#10106 Update final 1.8 EOL date in supported releases
  content/en/docs/releases/supported-releases/index.md
Labels: cherrypick/release-1.10, cla: yes, size/XS

#10107 Automator: update common-files@release-1.10 in istio/istio.io@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10109 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10110 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#10108 [release-1.10] Update final 1.8 EOL date in supported releases
  content/en/docs/releases/supported-releases/index.md
Labels: cla: yes, release-notes-none, size/XS

#10044 Fix PR template checklist format
  .github/pull_request_template.md
Labels: cla: yes, ok-to-test, size/S

#10115 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10114 Nest subsections under proper header for injection
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, size/M

#10118 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/M

#10095 Announce 1.9 eol
  content/en/docs/releases/supported-releases/index.md
  content/en/news/support/announcing-1.9-eol/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/S

#10126 Announce 1.9 eol (#10095)
  content/en/docs/releases/supported-releases/index.md
  content/en/news/support/announcing-1.9-eol/index.md
Labels: cla: yes, kind/docs, size/S

#10124 User supported endpoint for connectivity test
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: cla: yes, size/XS

#10128 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#10127 External control plane part 2 test
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: cla: yes, ok-to-test, size/M

#10131 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9592 helm install: create ns separately for operator
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, release-notes-none, size/S

#10130 fix apiVersion for gw install
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/zh/docs/setup/additional-setup/external-controlplane/index.md
  content/zh/docs/setup/additional-setup/external-controlplane/snips.sh
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cherrypick/master, cla: yes, kind/docs, size/S

#10132 [master] fix apiVersion for gw install
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/zh/docs/setup/additional-setup/external-controlplane/index.md
  content/zh/docs/setup/additional-setup/external-controlplane/snips.sh
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: cla: yes, release-notes-none, size/S

#10134 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#10076 fixed docs errors when working on issues#33906
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cla: yes, size/M

#10086 Update canary upgrade docs
  content/en/docs/setup/upgrade/canary/index.md
  content/en/docs/setup/upgrade/canary/tags-updated.png
  content/en/docs/setup/upgrade/canary/tags.png
  data/features.yaml
Labels: cla: yes, size/M

#10136 Automator: update istio.io@ reference docs
  data/features.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
