Repository istio/istio.io, pull requests merged in 2021-06, with the labels that each got.

#9755 zh-translation: blog/2019/introducing-istioctl-analyze/index.md
  content/zh/blog/2019/introducing-istioctl-analyze/index.md
Labels: cla: yes, kind/docs, size/S, translation/chinese

#9862 Fix typo.
  content/zh/docs/concepts/security/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#9857 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/S

#9863 Fix typo. (#9862)
  content/zh/docs/concepts/security/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#9860 Replace deprecated filters values with latest and correct values
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, ok-to-test, size/XS

#9849 Remove unneeded icons from src/icons
  src/icons/blog.svg
  src/icons/bugs.svg
  src/icons/bullhorn.svg
  src/icons/cadence.svg
  src/icons/classroom.svg
  src/icons/concepts.svg
  src/icons/contribute.svg
  src/icons/docs.svg
  src/icons/examples.svg
  src/icons/faq.svg
  src/icons/feature-status.svg
  src/icons/glossary.svg
  src/icons/guide.svg
  src/icons/helm.svg
  src/icons/istio-blue-logo.svg
  src/icons/log.svg
  src/icons/reference.svg
  src/icons/releases.svg
  src/icons/setup.svg
  src/icons/tasks.svg
  src/icons/vulnerabilities.svg
Labels: cherrypick/release-1.10, cla: yes, kind/docs, ok-to-test, size/S

#9866 Add 1.10.x to news/releases
  content/en/news/releases/1.10.x/_index.md
  content/en/news/releases/1.10.x/announcing-1.10/_index.md
Labels: cherrypick/release-1.10, cla: yes, size/S

#9868 [release-1.10] Replace deprecated filters values with latest and correct values
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, release-notes-none, size/XS

#9869 [release-1.10] Remove unneeded icons from src/icons
  src/icons/blog.svg
  src/icons/bugs.svg
  src/icons/bullhorn.svg
  src/icons/cadence.svg
  src/icons/classroom.svg
  src/icons/concepts.svg
  src/icons/contribute.svg
  src/icons/docs.svg
  src/icons/examples.svg
  src/icons/faq.svg
  src/icons/feature-status.svg
  src/icons/glossary.svg
  src/icons/guide.svg
  src/icons/helm.svg
  src/icons/istio-blue-logo.svg
  src/icons/log.svg
  src/icons/reference.svg
  src/icons/releases.svg
  src/icons/setup.svg
  src/icons/tasks.svg
  src/icons/vulnerabilities.svg
Labels: cla: yes, release-notes-none, size/S

#9870 [release-1.10] Add 1.10.x to news/releases
  content/en/news/releases/1.10.x/_index.md
  content/en/news/releases/1.10.x/announcing-1.10/_index.md
Labels: cla: yes, release-notes-none, size/S

#9865 Add wait to allow sleep pod to start
  content/en/docs/ops/configuration/telemetry/envoy-stats/test.sh
Labels: cla: yes, size/XS

#9871 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9565 Analysis message for IST0144
  content/en/docs/reference/config/analysis/ist0144/index.md
Labels: cla: yes, release-notes-none, size/M

#9873 [release-1.10] Add wait to allow sleep pod to start
  content/en/docs/ops/configuration/telemetry/envoy-stats/test.sh
Labels: cla: yes, release-notes-none, size/XS

#9706 Add documentation for gateway installation and management
  content/en/docs/setup/additional-setup/gateway/canary-upgrade.svg
  content/en/docs/setup/additional-setup/gateway/high-level-canary.svg
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/gateway/inplace-upgrade.svg
  content/en/docs/setup/additional-setup/gateway/shared-gateway.svg
  content/en/docs/setup/additional-setup/gateway/user-gateway.svg
  content/en/docs/setup/install/_index.md
Labels: cla: yes, size/L

#9876 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9874 [release-1.10] Add documentation for gateway installation and management
  content/en/docs/setup/additional-setup/gateway/canary-upgrade.svg
  content/en/docs/setup/additional-setup/gateway/high-level-canary.svg
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/gateway/inplace-upgrade.svg
  content/en/docs/setup/additional-setup/gateway/shared-gateway.svg
  content/en/docs/setup/additional-setup/gateway/user-gateway.svg
  content/en/docs/setup/install/_index.md
Labels: cla: yes, release-notes-none, size/L

#9797 Remove faq/applications
  content/en/about/faq/applications/cassandra.md
  content/en/about/faq/applications/elasticsearch.md
  content/en/about/faq/applications/index.md
  content/en/about/faq/applications/nifi.md
  content/en/about/faq/applications/redis.md
  content/en/about/faq/applications/zookeeper.md
  content/en/about/faq/traffic-management/statefulsets.md
Labels: cherrypick/release-1.10, cla: yes, size/L

#9879 [release-1.10] Remove faq/applications
  content/en/about/faq/applications/cassandra.md
  content/en/about/faq/applications/elasticsearch.md
  content/en/about/faq/applications/index.md
  content/en/about/faq/applications/nifi.md
  content/en/about/faq/applications/redis.md
  content/en/about/faq/applications/zookeeper.md
  content/en/about/faq/traffic-management/statefulsets.md
Labels: cla: yes, release-notes-none, size/L

#9878 A few gateway install clarifications
  content/en/docs/setup/additional-setup/gateway/index.md
Labels: cherrypick/release-1.10, cla: yes, size/M

#9881 [release-1.10] A few gateway install clarifications
  content/en/docs/setup/additional-setup/gateway/index.md
Labels: cla: yes, release-notes-none, size/M

#9880 Blog: Locality failover for external services
  .spelling
  content/en/blog/2021/external-locality-failover/external-locality-failover.png
  content/en/blog/2021/external-locality-failover/index.md
Labels: cla: yes, kind/docs, size/L

#9882 small edits for Blog: Locality failover for external services
  content/en/blog/2021/external-locality-failover/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#9883 [release-1.10] Blog: Locality failover for external services
  .spelling
  content/en/blog/2021/external-locality-failover/external-locality-failover.png
  content/en/blog/2021/external-locality-failover/index.md
Labels: cla: yes, release-notes-none, size/L

#9884 [release-1.10] small edits for Blog: Locality failover for external services
  content/en/blog/2021/external-locality-failover/index.md
Labels: cla: yes, release-notes-none, size/XS

#9886 Automator: update istio.io@ reference docs
  data/features.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9887 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/L

#9889 Update Gateway API doc
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
Labels: cherrypick/release-1.10, cla: yes, size/S

#9890 remove namespce for cluster scope resources.
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
Labels: area/environments, cla: yes, size/XS

#9896 [release-1.9] Fix image used by sleep sample (doesn't use istio/istio sleep)
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
Labels: cla: yes, release-notes-none, size/XS

#9899 correct typo on rate limiting page
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, kind/docs, size/XS

#9902 [release-1.10] Analysis message for IST0144
  content/en/docs/reference/config/analysis/ist0144/index.md
Labels: cla: yes, release-notes-none, size/M

#9904 [release-1.10] correct typo on rate limiting page
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, release-notes-none, size/XS

#9900 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9894 [release-1.10] Update Gateway API doc
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
Labels: cla: yes, release-notes-none, size/S

#9905 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9903 fix invalid link
  content/zh/docs/concepts/observability/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#9893 Automator: update common-files@release-1.9 in istio/istio.io@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9885 fix a typo
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: cla: yes, size/XS

#9493 update the auto mtls troubleshooting guide.
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: area/networking, area/security, cherrypick/release-1.10, cla: yes, kind/docs, size/XS

#9906 [release-1.10] update the auto mtls troubleshooting guide.
  content/en/docs/ops/common-problems/security-issues/index.md
Labels: cla: yes, release-notes-none, size/XS

#9907 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9898 Add release notes for 1.10.1
  content/en/news/releases/1.10.x/announcing-1.10.1/index.md
Labels: cherrypick/release-1.10, cla: yes, size/S

#9911 add direct pod IP troubleshooting guide for multicluster
  content/en/docs/ops/diagnostic-tools/multicluster/index.md
Labels: cla: yes, size/M

#9915 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9912 [release-1.10] Add release notes for 1.10.1
  content/en/news/releases/1.10.x/announcing-1.10.1/index.md
  data/args.yml
Labels: cla: yes, release-notes-none, size/S

#9872 [release-1.10] Update reference docs 1.10.1
  content/en/docs/reference/config/annotations/index.html
Labels: cla: yes, size/S

#9897 [release-1.10] Update Istio test ref to 1.10.1
  go.mod
  go.sum
Labels: cla: yes, size/XS

#9918 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/L

#9920 Fix copy paste of text bash sections
  content/en/docs/ops/best-practices/security/index.md
Labels: cherrypick/release-1.10, cla: yes, size/L

#9921 [release-1.10] Fix copy paste of text bash sections
  content/en/docs/ops/best-practices/security/index.md
Labels: cla: yes, release-notes-none, size/L

#9923 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/envoy-filter/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#9924 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/M

#9922 update match condition for configPatches
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: area/policies and telemetry, cla: yes, kind/docs, size/S

#9925 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#9926 Update link to Shared Drive folder
  .spelling
  content/en/docs/releases/contribute/diagrams/index.md
  content/zh/docs/releases/contribute/diagrams/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/S

#9931 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9930 [release-1.10] Update link to Shared Drive folder
  .spelling
  content/en/docs/releases/contribute/diagrams/index.md
  content/zh/docs/releases/contribute/diagrams/index.md
Labels: cla: yes, release-notes-none, size/S

#9934 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  data/analysis.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#9908 add reference page for supported normalization in authz
  content/en/docs/ops/best-practices/security/index.md
  content/en/docs/reference/config/security/normalization/index.md
Labels: area/security, cla: yes, size/L

#9936 Add warn for namespace
  content/en/docs/setup/install/operator/index.md
Labels: cherrypick/release-1.10, cla: yes, size/XS

#9935 Highlight port conflict warning
  content/en/docs/ops/deployment/requirements/index.md
Labels: cherrypick/release-1.10, cla: yes, size/XS

#9940 [release-1.10] Add warn for namespace
  content/en/docs/setup/install/operator/index.md
Labels: cla: yes, size/XS

#9938 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9933 [release-1.10] Reference doc update
  data/features.yaml
Labels: cla: yes, kind/docs, size/XS

#9941 Automator: update common-files@release-1.10 in istio/istio.io@release-1.10
  SUPPORT.md
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9939 [release-1.10] Highlight port conflict warning
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, release-notes-none, size/XS

#9800 Add documentation on traffic routing details
  .spelling
  content/en/docs/ops/configuration/traffic-management/traffic-routing/index.md
Labels: cla: yes, size/L

#9927 zh-translation: docs/ops/configuration/traffic-management/tls-configuration
  content/zh/docs/ops/configuration/traffic-management/tls-configuration/gateway-connections.svg
  content/zh/docs/ops/configuration/traffic-management/tls-configuration/index.md
  content/zh/docs/ops/configuration/traffic-management/tls-configuration/sidecar-connections.svg
Labels: cla: yes, kind/docs, ok-to-test, size/L, translation/chinese

#9944 Fix typo in EXTERNAL_CA env comment
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cherrypick/release-1.10, cla: yes, size/XS

#9945 [release-1.10] Fix typo in EXTERNAL_CA env comment
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: cla: yes, release-notes-none, size/XS

#9946 [release-1.10] Add documentation on traffic routing details
  .spelling
  content/en/docs/ops/configuration/traffic-management/traffic-routing/index.md
Labels: cla: yes, release-notes-none, size/L

#9947 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9948 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/M

#9949 zh/about/faq/_index.md
  content/zh/about/faq/_index.md
Labels: cla: yes, kind/docs, size/XS

#9950 zh-translation/content/en/about/ecosystem/index.md
  content/zh/about/ecosystem/index.md
Labels: cla: yes, kind/docs, size/S

#9951 zh-translation/faq/general/how-do-i-contribute.md
  content/zh/about/faq/general/how-do-i-contribute.md
Labels: cla: yes, kind/docs, size/XS

#9958 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9952 zh-translation/about/faq/general/what-is-istio.md
  content/zh/about/faq/general/what-is-istio.md
Labels: cla: yes, size/XS, translation/chinese

#9953 zh-translation/about/faq/security/cert-lifetime-config.md
  content/zh/about/faq/security/cert-lifetime-config.md
Labels: cla: yes, size/M, translation/chinese

#9954 zh-translation/about/faq/security/k8s-health-checks.md
  content/zh/about/faq/security/k8s-health-checks.md
Labels: cla: yes, size/S, translation/chinese

#9956 zh/about/faq/security/non-istio-to-istio.md
  content/zh/about/faq/security/non-istio-to-istio.md
Labels: cla: yes, size/XS, translation/chinese

#9959 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#9962 Replacing referenced issues for scale down issue
  content/en/docs/ops/common-problems/injection/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, ok-to-test, size/XS

#9966 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/S

#9895 Flag experimental pages with dagger
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/reference/config/proxy_extensions/wasm_telemetry/index.md
  content/en/docs/setup/upgrade/gateways/index.md
  content/en/docs/tasks/observability/distributed-tracing/configurability/index.md
  content/en/docs/tasks/security/authorization/authz-dry-run/index.md
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
  layouts/partials/navigation_level.html
Labels: cherrypick/release-1.10, cla: yes, kind/docs, ok-to-test, size/M

#9969 remove Mixer dashboard from the Grafana setup script
  content/en/docs/ops/integrations/grafana/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/XS

#9971 Add traffic management concept alias
  content/en/docs/concepts/traffic-management/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/XS

#9972 [release-1.10] Add traffic management concept alias
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, release-notes-none, size/XS

#9973 [master] remove Mixer dashboard from the Grafana setup script
  content/en/docs/ops/integrations/grafana/index.md
Labels: cla: yes, release-notes-none, size/XS

#9974 [release-1.10] Replacing referenced issues for scale down issue
  content/en/docs/ops/common-problems/injection/index.md
Labels: cla: yes, release-notes-none, size/XS

#9942 GKE platform setup: multicluster firewall rule
  content/en/docs/setup/platform-setup/gke/index.md
Labels: cherrypick/release-1.10, cla: yes, size/S

#9910 New ports added to the code
  content/en/docs/ops/deployment/requirements/index.md
Labels: cla: yes, size/S

#9975 [release-1.10] GKE platform setup: multicluster firewall rule
  content/en/docs/setup/platform-setup/gke/index.md
Labels: cla: yes, release-notes-none, size/S

#9970 zh-translation: /content/en/docs/examples/microservices-istio/logs-is…
  content/zh/blog/2019/evolving-istios-apis/index.md
  content/zh/docs/examples/microservices-istio/logs-istio/index.md
  content/zh/docs/setup/getting-started/index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#9979 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#9968 content/en/about/service-mesh/index.md
  content/zh/about/service-mesh/index.md
Labels: cla: yes, kind/docs, ok-to-test, size/S, translation/chinese

#9917 add mitigation for unsupported normalization in security best practice
  .spelling
  content/en/docs/ops/best-practices/security/index.md
Labels: area/security, cla: yes, size/M

#9982 zh-translation: content/en/docs/examples/microservices-istio/add-new-…
  content/zh/docs/examples/microservices-istio/add-new-microservice-version/index.md
Labels: cla: yes, kind/docs, size/XS, translation/chinese

#9986 6/24 security release doc update
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.10.x/announcing-1.10.2/index.md
  content/en/news/releases/1.9.x/announcing-1.9.6/index.md
  content/en/news/security/istio-security-2021-006/index.md
  content/en/news/security/istio-security-2021-007/index.md
  data/args.yml
Labels: cherrypick/master, cla: yes, kind/docs, size/L

#9988 Manual cherry-pick of #9986
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.10.x/announcing-1.10.2/index.md
  content/en/news/releases/1.9.x/announcing-1.9.6/index.md
  content/en/news/security/istio-security-2021-006/index.md
  content/en/news/security/istio-security-2021-007/index.md
Labels: cla: yes, size/L

#9981 fix weak algorithm
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#9990 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#9991 Update reporters for recent cve
  content/en/news/security/istio-security-2021-007/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/XS

#9993 [release-1.10] Update reporters for recent cve
  content/en/news/security/istio-security-2021-007/index.md
Labels: cla: yes, release-notes-none, size/XS

#9992 Improve traffic shifting task overview
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: cla: yes, size/M

#9998 zh-translation: fix weak algorithm
  content/zh/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
Labels: cla: yes, ok-to-test, size/XS, translation/chinese

#9757 zh-translation: blog/2019/knative-activator-adapter/index.m
  content/zh/blog/2019/knative-activator-adapter/index.md
Labels: cla: yes, kind/docs, size/S, translation/chinese

#9888 Upgrade the ops documents translate to Chinese.
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-describe/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
  content/zh/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: cla: yes, ok-to-test, size/XL, translation/chinese

#9999 Update bug reporting instructions for docs
  content/en/docs/releases/bugs/index.md
Labels: cherrypick/master, cla: yes, kind/docs, size/XS

#9957 update zh enableAutoMtls default true
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: cla: yes, kind/docs, ok-to-test, size/XS, translation/chinese

#10002 [release-1.10] Improve traffic shifting task overview
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: cla: yes, release-notes-none, size/M

#9997 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: cla: yes, release-notes-none, size/S

#10001 [master] Update bug reporting instructions for docs
  content/en/docs/releases/bugs/index.md
Labels: cla: yes, release-notes-none, size/XS

#10000 zh-translation: zh-translation/content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/XS, translation/chinese

#10004 Add comments to the user and vendor pages
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  content/en/about/case-studies/_index.md
  content/en/about/ecosystem/index.md
  data/companies.yml
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/M

#9967 Remove outdated usage
  content/en/docs/concepts/traffic-management/index.md
Labels: cherrypick/release-1.10, cla: yes, size/XS

#10006 [release-1.10] Add comments to the user and vendor pages
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  content/en/about/case-studies/_index.md
  content/en/about/ecosystem/index.md
  data/companies.yml
Labels: cla: yes, release-notes-none, size/M

#10007 [master] Remove outdated usage
  content/en/docs/concepts/traffic-management/index.md
Labels: cla: yes, release-notes-none, size/XS

#9978 fix the wording in the ext-authz blog
  content/en/blog/2021/better-external-authz/index.md
Labels: area/security, cherrypick/release-1.10, cla: yes, size/XS

#10003 [release-1.10] zh-translation: zh-translation/content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: cla: yes, release-notes-none, size/XS, translation/chinese

#10011 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: auto-merge, cla: yes, release-notes-none, size/M

#10008 Announce steering election and TOC election result
  .spelling
  content/en/blog/2021/steering-election/index.md
Labels: cherrypick/release-1.10, cla: yes, kind/docs, size/S

#10009 [release-1.10] fix the wording in the ext-authz blog
  content/en/blog/2021/better-external-authz/index.md
Labels: cla: yes, release-notes-none, size/XS

#9901 missing a space after "kubectl get pods -l"
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
Labels: cla: yes, kind/docs, ok-to-test, size/XS

#10013 [release-1.10] Announce steering election and TOC election result
  .spelling
  content/en/blog/2021/steering-election/index.md
Labels: cla: yes, release-notes-none, size/S

#10010 Add table of contents test status
  content/en/docs/_index.md
  content/en/docs/concepts/_index.md
  content/en/docs/examples/_index.md
  content/en/docs/examples/microservices-istio/_index.md
  content/en/docs/reference/config/_index.md
  content/en/docs/reference/config/networking/_index.md
  content/en/docs/setup/_index.md
  content/en/docs/setup/install/_index.md
  content/en/docs/setup/install/multicluster/_index.md
  content/en/docs/setup/platform-setup/_index.md
  content/en/docs/tasks/observability/distributed-tracing/_index.md
  content/en/docs/tasks/security/_index.md
  content/en/docs/tasks/traffic-management/_index.md
  content/en/docs/tasks/traffic-management/ingress/_index.md
  content/zh/docs/_index.md
  content/zh/docs/concepts/what-is-istio/index.md
  scripts/test_status.sh
Labels: cla: yes, size/M

#10016 Automator: update common-files@master in istio/istio.io@master
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#10019 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
