Repository istio/istio.io, pull requests merged in 2021-10, with the labels that each got.

#10396 [master] Update index.md
  content/en/blog/2021/discovery-selectors/index.md
Labels: size/XS, cla: yes, release-notes-none

#10397 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10399 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10401 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
Labels: size/M, cla: yes, auto-merge, release-notes-none

#10402 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/S, cla: yes, auto-merge, release-notes-none

#10406 Configure istio-system namespace for istioctl install
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: size/XS, cla: yes

#10400 update best practice for host match
  content/en/docs/ops/best-practices/security/index.md
Labels: area/security, size/M, cla: yes

#10451 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/L, cla: yes, auto-merge, release-notes-none
