Repository istio/istio.io, pull requests merged in 2021-12, with the labels that each got.

#10549 zh-translation1.12.x Releases
  content/zh/news/releases/1.12.x/_index.md
Labels: kind/docs, translation/chinese, size/XS, cla: yes, ok-to-test

#10551 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10553 Add release notes for 1.11.5
  content/en/news/releases/1.11.x/announcing-1.11.5/index.md
Labels: size/M, cla: yes, cherrypick/release-1.12

#10555 Improve performance documentation
  content/en/docs/ops/deployment/performance-and-scalability/index.md
Labels: size/M, cla: yes

#10554 [release-1.12] Add release notes for 1.11.5
  content/en/news/releases/1.11.x/announcing-1.11.5/index.md
Labels: size/M, cla: yes, release-notes-none

#10521 Add 1.10 pre-EOL announcement
  content/en/news/support/announcing-1.10-eol/index.md
Labels: size/S, cla: yes, cherrypick/release-1.12

#10547 Add 1.10.6 release notes
  content/en/news/releases/1.10.x/announcing-1.10.6/index.md
Labels: size/S, cla: yes, cherrypick/release-1.12

#10556 [release-1.12] Add 1.10 pre-EOL announcement
  content/en/news/support/announcing-1.10-eol/index.md
Labels: size/S, cla: yes, release-notes-none

#10558 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10565 zh-translation: zh/news/releases/1.11.x/announcing-1.11.4/index.md
  content/zh/news/releases/1.11.x/announcing-1.11.4/index.md
Labels: kind/docs, translation/chinese, size/S, cla: yes, ok-to-test

#10569 Automator: update common-files@release-1.12 in istio/istio.io@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#10520 [release-1.12] Update istio test reference to 1.12.0
  go.mod
  go.sum
Labels: size/XS, cla: yes

#10557 [release-1.12] Add 1.10.6 release notes
  content/en/news/releases/1.10.x/announcing-1.10.6/index.md
Labels: size/S, cla: yes, release-notes-none

#10571 Add Constant Contact as User of Istio
  data/companies.yml
  static/logos/constant-contact-logo.svg
Labels: kind/docs, size/M, cla: yes, ok-to-test, cherrypick/release-1.12

#10570 Fix Helm install and upgrade commands for istio-operator
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/install/operator/snips.sh
Labels: size/XS, cla: yes, cherrypick/release-1.12

#10573 [release-1.12] Fix Helm install and upgrade commands for istio-operator
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/install/operator/snips.sh
Labels: size/XS, cla: yes, release-notes-none

#10567 zh/news/releases/1.9.x/announcing-1.9.3/index.md
  content/zh/news/releases/1.9.x/announcing-1.9.3/index.md
Labels: kind/docs, translation/chinese, size/S, cla: yes, ok-to-test

#10515 [release-1.11] mark v1.11 as archived
  config.toml
  data/args.yml
Labels: size/XS, cla: yes

#10526 add test for the dry-run task
  content/en/docs/tasks/security/authorization/authz-dry-run/index.md
  content/en/docs/tasks/security/authorization/authz-dry-run/prometheus.png
  content/en/docs/tasks/security/authorization/authz-dry-run/snips.sh
  content/en/docs/tasks/security/authorization/authz-dry-run/test.sh
  content/en/docs/tasks/security/authorization/authz-dry-run/trace.png
  tests/README.md
  tests/util/verify.sh
Labels: area/security, size/L, cla: yes

#10574 Add release notes for 1.12.1
  content/en/news/releases/1.12.x/announcing-1.12.1/index.md
Labels: size/M, cherrypick/release-1.12

#10568 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/L, cla: yes, release-notes-none

#10585 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#10584 Update current version to 1.12.1
  content/en/news/releases/1.12.x/announcing-1.12.1/index.md
  data/args.yml
Labels: size/M

#10577 [release-1.10] Update istio test reference to 1.10.6
  go.mod
  go.sum
Labels: size/S

#10578 [release-1.11] Update istio test reference to 1.11.5
  go.mod
  go.sum
Labels: size/S

#10581 [release-1.12] Update istio test ref to 1.12.1
  go.mod
  go.sum
Labels: size/S

#10587 clarify sidecar doc
  content/en/docs/concepts/traffic-management/index.md
  content/zh/docs/concepts/traffic-management/index.md
Labels: size/XS, ok-to-test, cherrypick/release-1.12

#10580 [release-1.11] Update ref docs for 1.11.5
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/M

#10576 Add Slime to integrations
  data/companies.yml
  static/logos/slime.png
Labels: kind/docs, size/XS, ok-to-test

#10582 [release-1.12] Update the reference docs for 1.12.1
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/telemetry/index.html
Labels: size/L

#10586 Add CORS faq
  content/en/about/faq/traffic-management/cors.md
Labels: size/M, cherrypick/release-1.12

#10588 [release-1.12] Add CORS faq
  content/en/about/faq/traffic-management/cors.md
Labels: size/M, release-notes-none

#10589 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#10528 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/proxy-config/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  data/analysis.yaml
Labels: size/XXL, cla: yes, auto-merge, release-notes-none

#10593 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#10596 Fix VERIFY_CERT_AT_CLIENT typo in 1.12 release notes
  content/en/news/releases/1.12.x/announcing-1.12/change-notes/index.md
Labels: kind/docs, size/XS, ok-to-test, cherrypick/release-1.12

#10595 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  data/features.yaml
Labels: size/M, auto-merge, release-notes-none

#10597 [release-1.12] Fix VERIFY_CERT_AT_CLIENT typo in 1.12 release notes
  content/en/news/releases/1.12.x/announcing-1.12/change-notes/index.md
Labels: size/XS, release-notes-none

#10598 [release-1.12] clarify sidecar doc
  content/en/docs/concepts/traffic-management/index.md
  content/zh/docs/concepts/traffic-management/index.md
Labels: size/XS, release-notes-none

#10599 [release-1.12] Add Constant Contact as User of Istio
  data/companies.yml
  static/logos/constant-contact-logo.svg
Labels: size/M, release-notes-none

#10601 [release-1.12] Improve performance documentation
  content/en/docs/ops/deployment/performance-and-scalability/index.md
Labels: size/M, release-notes-none

#10600 [release-1.12] Add Slime to integrations
  data/companies.yml
  static/logos/slime.png
Labels: size/XS, release-notes-none

#10603 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10604 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
Labels: size/S, auto-merge, release-notes-none

#10606 Automator: update common-files@release-1.12 in istio/istio.io@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#10607 Update istio/istio test reference. Also needs a code change.
  go.mod
  go.sum
  pkg/test/istioio/snapshot_validator.go
Labels: size/M

#10575 remove deleted docs in english
  content/zh/blog/2017/adapter-model/index.md
  content/zh/blog/2017/adapter-model/machine.svg
  content/zh/docs/reference/config/istio.operator.v1alpha12.pb/index.html
  content/zh/docs/reference/config/policy-and-telemetry/_index.md
  content/zh/docs/reference/config/policy-and-telemetry/adapters/_index.md
  content/zh/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/apigee/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/app-identity-access-adapter/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/circonus/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/cloudmonitor/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/cloudwatch/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/datadog/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/denier/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/kubernetesenv/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/list/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/memquota/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/newrelic/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/opa/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/prometheus/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/redisquota/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/solarwinds/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/stackdriver/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/statsd/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/stdio/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/wavefront/index.html
  content/zh/docs/reference/config/policy-and-telemetry/adapters/zipkin/index.html
  content/zh/docs/reference/config/policy-and-telemetry/attribute-vocabulary/index.md
  content/zh/docs/reference/config/policy-and-telemetry/expression-language/index.md
  content/zh/docs/reference/config/policy-and-telemetry/istio.mixer.v1.config.client/index.html
  content/zh/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/index.html
  content/zh/docs/reference/config/policy-and-telemetry/metrics/index.md
  content/zh/docs/reference/config/policy-and-telemetry/mixer-overview/adapters.svg
  content/zh/docs/reference/config/policy-and-telemetry/mixer-overview/index.md
  content/zh/docs/reference/config/policy-and-telemetry/mixer-overview/topology-with-cache.svg
  content/zh/docs/reference/config/policy-and-telemetry/mixer-overview/topology-without-cache.svg
  content/zh/docs/reference/config/policy-and-telemetry/templates/_index.md
  content/zh/docs/reference/config/policy-and-telemetry/templates/analytics/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/apikey/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/authorization/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/checknothing/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/edge/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/kubernetes/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/listentry/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/logentry/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/metric/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/quota/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/reportnothing/index.html
  content/zh/docs/reference/config/policy-and-telemetry/templates/tracespan/index.html
Labels: translation/chinese, size/XXL

#10608 Add k8s 1.18 to the list for Istio 1.11
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS, cherrypick/master

#10615 [master] Add k8s 1.18 to the list for Istio 1.11
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS, release-notes-none

#10594 Virtual Machine Blog Post
  content/en/blog/2021/simple-vms/forwarding-proxy.png
  content/en/blog/2021/simple-vms/grpc-json-transcoding.png
  content/en/blog/2021/simple-vms/index.md
  content/en/blog/2021/simple-vms/istio-current-vm-process.png
  content/en/blog/2021/simple-vms/local-machine.png
  content/en/blog/2021/simple-vms/multi-direction-traffic-flow.png
  content/en/blog/2021/simple-vms/runtime-support.png
  content/en/blog/2021/simple-vms/single-direction-traffic-flow.png
  content/en/blog/2021/simple-vms/traffic-flow.png
  content/en/blog/2021/simple-vms/virtual-machine-on-boarding-steps.png
Labels: kind/docs, size/M

#10616 [release-1.12] Virtual Machine Blog Post
  content/en/blog/2021/simple-vms/forwarding-proxy.png
  content/en/blog/2021/simple-vms/grpc-json-transcoding.png
  content/en/blog/2021/simple-vms/index.md
  content/en/blog/2021/simple-vms/istio-current-vm-process.png
  content/en/blog/2021/simple-vms/local-machine.png
  content/en/blog/2021/simple-vms/multi-direction-traffic-flow.png
  content/en/blog/2021/simple-vms/runtime-support.png
  content/en/blog/2021/simple-vms/single-direction-traffic-flow.png
  content/en/blog/2021/simple-vms/traffic-flow.png
  content/en/blog/2021/simple-vms/virtual-machine-on-boarding-steps.png
Labels: size/M, release-notes-none

#10611 zh: remove outdated usage
  content/zh/docs/concepts/traffic-management/index.md
Labels: kind/docs, translation/chinese, size/XS

#10612 zh-translation: remove mixer from traffic problems troubleshoot guide
  content/zh/docs/ops/common-problems/network-issues/index.md
Labels: kind/docs, translation/chinese, size/S

#10560 zh/news/releases/1.10.x/announcing-1.10.3/index.md
  content/zh/news/releases/1.10.x/announcing-1.10.3/index.md
Labels: translation/chinese, size/S, cla: yes, ok-to-test

#10561 zh/news/releases/1.10.x/announcing-1.10.1/index.md
  content/zh/news/releases/1.10.x/announcing-1.10.1/index.md
Labels: kind/docs, translation/chinese, size/S, cla: yes, ok-to-test

#10562 zh/news/releases/1.10.x/announcing-1.10.2/index.md
  content/zh/news/releases/1.10.x/announcing-1.10.2/index.md
Labels: kind/docs, translation/chinese, size/S, cla: yes, ok-to-test

#10563 zh/news/releases/1.10.x/announcing-1.10.5/index.md
  content/zh/news/releases/1.10.x/announcing-1.10.5/index.md
Labels: kind/docs, translation/chinese, size/M, cla: yes, ok-to-test

#10613 zh: sync traffic management alias
  content/zh/docs/concepts/traffic-management/index.md
Labels: kind/docs, translation/chinese, size/XS

#10618 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#10617 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#10590 analysis message IST0150
  content/en/docs/reference/config/analysis/ist0150/index.md
  data/analysis.yaml
Labels: kind/docs, area/user experience, size/M, ok-to-test

#10605 Lean more towards resilient vs robust and reliability vs failure recovery.
  content/en/docs/concepts/traffic-management/index.md
Labels: size/XS, cherrypick/master, ok-to-test

#10620 [master] Lean more towards resilient vs robust and reliability vs failure recovery.
  content/en/docs/concepts/traffic-management/index.md
Labels: size/XS, release-notes-none

#10621 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  data/analysis.yaml
Labels: size/XS, auto-merge, release-notes-none

#10566 zh/news/releases/1.9.x/announcing-1.9.2/index.md
  content/zh/news/releases/1.9.x/announcing-1.9.2/index.md
Labels: kind/docs, translation/chinese, size/M, cla: yes, ok-to-test

#10564 zh/news/releases/1.10.x/announcing-1.10.6/index.md
  content/zh/news/releases/1.10.x/announcing-1.10.6/index.md
Labels: kind/docs, translation/chinese, size/S, cla: yes, ok-to-test

#10619 zh-translation: remove stale document
  content/zh/docs/tasks/observability/logs/collecting-logs/index.md
  content/zh/docs/tasks/observability/logs/fluentd/index.md
Labels: kind/docs, translation/chinese, size/L, ok-to-test

#10559 zh-translation: zh/news/releases/1.11.x/announcing-1.11.5/index.md
  content/zh/news/releases/1.11.x/announcing-1.11.5/index.md
Labels: kind/docs, translation/chinese, size/S, cla: yes, ok-to-test

#10530 Announcing Wasm alpha availability blog.
  .spelling
  content/en/blog/2021/wasm-api-alpha/index.md
  content/en/blog/2021/wasm-api-alpha/istio-agent-architecture.svg
Labels: kind/docs, size/XXL, cla: yes, cherrypick/release-1.12

#10626 [release-1.12] Announcing Wasm alpha availability blog.
  .spelling
  content/en/blog/2021/wasm-api-alpha/index.md
  content/en/blog/2021/wasm-api-alpha/istio-agent-architecture.svg
Labels: size/XXL, release-notes-none

#10630 Change test to support as we actually test on more releases.
  content/en/docs/setup/platform-setup/_index.md
Labels: size/XS

#10634 [release-1.12] Change test to support as we actually test on more releases.
  content/en/docs/setup/platform-setup/_index.md
Labels: size/XS, release-notes-none

#10643 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10647 style: add spaces between letters
  content/zh/blog/2021/istiomeetups-china/index.md
Labels: size/S, cherrypick/release-1.12

#10649 [release-1.12] style: add spaces between letters
  content/zh/blog/2021/istiomeetups-china/index.md
Labels: size/S, release-notes-none

#10650 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10642 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#10653 zh-tranlation:news/releases/1.9.x/announcing-1.9.5/index.md
  content/zh/news/releases/1.9.x/announcing-1.9.5/index.md
Labels: kind/docs, translation/chinese, size/M, ok-to-test

#10622 zh-translation: news/releases/1.9.x/announcing-1.9.9/index.md
  content/zh/news/releases/1.9.x/announcing-1.9.9/index.md
Labels: kind/docs, translation/chinese, size/S

#10652 zh-tranlation:news/releases/1.11.x/announcing-1.11.3/index.md
  content/zh/news/releases/1.11.x/announcing-1.11.3/index.md
Labels: kind/docs, translation/chinese, size/M, ok-to-test

#10657 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10628 zh-traslation-/docs/reference/config/analysis/ist0150/index.md
  content/zh/docs/reference/config/analysis/ist0150/index.md
Labels: kind/docs, translation/chinese, size/M, ok-to-test

#10665 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#10664 zh-translation:/boilerplates/revision-tags-middle.md
  content/zh/boilerplates/revision-tags-middle.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10666 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10663 zh-translation:boilerplates/revision-tags-default-outro.md
  content/zh/boilerplates/revision-tags-default-outro.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#10623 zh-translation: news/releases/1.9.x/announcing-1.9.7/index.md
  content/zh/news/releases/1.9.x/announcing-1.9.7/index.md
Labels: kind/docs, translation/chinese, size/S

#10624 zh-translation: news/releases/1.9.x/announcing-1.9.6/index.md
  content/zh/news/releases/1.9.x/announcing-1.9.6/index.md
Labels: kind/docs, translation/chinese, size/S

#10625 zh-translation: news/releases/1.9.x/announcing-1.9.4/index.md
  content/zh/news/releases/1.9.x/announcing-1.9.4/index.md
Labels: kind/docs, translation/chinese, size/M

#10651 zh-tranlation:/news/releases/1.11.x/announcing-1.11.2/index.md
  content/zh/news/releases/1.11.x/announcing-1.11.2/index.md
Labels: kind/docs, translation/chinese, size/M, ok-to-test

#10658 zh-translation:boilerplates/helm-backup.md
  content/zh/boilerplates/helm-backup.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10659 zh-translation:/boilerplates/helm-jwt-warning.md
  content/zh/boilerplates/helm-jwt-warning.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10660 zh-translation:/boilerplates/helm-preamble.md
  content/zh/boilerplates/helm-preamble.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#10661 zh-translation:boilerplates/helm-prereqs.md
  content/zh/boilerplates/helm-prereqs.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10662 zh-translation:boilerplates/revision-tags-default-intro.md
  content/zh/boilerplates/revision-tags-default-intro.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10667 zh-translation:/boilerplates/revision-tags-preamble.md
  content/zh/boilerplates/revision-tags-preamble.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#10668 zh-tarnslation:/boilerplates/revision-tags-prologue.md
  content/zh/boilerplates/revision-tags-prologue.md
Labels: kind/docs, size/S, ok-to-test

#10671 fix(citadel-config): remove unused directory
  content/zh/docs/tasks/security/citadel-config/_index.md
Labels: translation/chinese, size/XS, cherrypick/release-1.12

#10672 fix: remove duplicated pages of DNS and CA
  content/zh/docs/tasks/security/dns-cert/index.md
  content/zh/docs/tasks/security/plugin-ca-cert/index.md
Labels: translation/chinese, size/L, cherrypick/release-1.12

#10669 zh-translation:boilerplates/revision-tags-usage.md
  content/zh/boilerplates/revision-tags-usage.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#10674 [release-1.12] fix(citadel-config): remove unused directory
  content/zh/docs/tasks/security/citadel-config/_index.md
Labels: size/XS, release-notes-none

#10675 [release-1.12] fix: remove duplicated pages of DNS and CA
  content/zh/docs/tasks/security/dns-cert/index.md
  content/zh/docs/tasks/security/plugin-ca-cert/index.md
Labels: size/L, release-notes-none

#10676 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10682 zh:/about/case-studies/t-mobile/index.md
  content/zh/about/case-studies/t-mobile/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10673 fix-#10609:zh-translation:docs/tasks/security/authentication/authn-policy/
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#10679 zh-translation:/about/case-studies/airbnb/index.md
  content/zh/about/case-studies/airbnb/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10680 zh:/about/case-studies/atlassian/index.md
  content/zh/about/case-studies/atlassian/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10683 zh:/about/case-studies/cash-app/index.md
  content/zh/about/case-studies/cash-app/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10691 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10677 zh-translation：/about/faq/traffic-management/cors.md
  content/zh/about/faq/traffic-management/cors.md
Labels: kind/docs, size/M, ok-to-test

#10678 zh-translation:about/faq/traffic-management/statefulsets.md
  content/zh/about/faq/traffic-management/statefulsets.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#10692 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10695 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/annotations/index.html
Labels: size/S, auto-merge, release-notes-none

#10696 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/telemetry/index.html
Labels: size/L, auto-merge, release-notes-none

#10701 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#10699 zh:/about/case-studies/fico/index.md
  content/zh/about/case-studies/fico/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10698 [zh] Fix Mutual TLS Migration page
  content/zh/docs/tasks/security/authentication/mtls-migration/index.md
Labels: translation/chinese, size/S

#10703 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#10702 Update index.md: Found a command missing from the Chinese document
  content/zh/docs/examples/bookinfo/index.md
Labels: kind/docs, size/XS, ok-to-test, cherrypick/release-1.12

#10693 zh:/news/releases/1.12.x/announcing-1.12/upgrade-notes/index.md
  content/zh/news/releases/1.12.x/announcing-1.12/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#10655 [CNI] Document 1337 UID workaround for init container.
  content/en/docs/setup/additional-setup/cni/index.md
Labels: size/S, cla: yes, cherrypick/release-1.12

#10704 [release-1.12] [CNI] Document 1337 UID workaround for init container.
  content/en/docs/setup/additional-setup/cni/index.md
Labels: size/S, release-notes-none

#10654 Update Wasm module distribution doc to use WasmPlugin.
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: size/L, cherrypick/release-1.12

#10705 [release-1.12] Update Wasm module distribution doc to use WasmPlugin.
  content/en/docs/ops/configuration/extensibility/wasm-module-distribution/index.md
Labels: size/L, release-notes-none
