Repository istio/istio.io, pull requests merged in 2022-10, with the labels that each got.

#12035 Update kubernetes dashboard instructions for kind
  content/en/docs/setup/platform-setup/kind/index.md
Labels: size/XS, cherrypick/release-1.15

#12038 [release-1.15] Update kubernetes dashboard instructions for kind
  content/en/docs/setup/platform-setup/kind/index.md
Labels: size/XS, release-notes-none

#12037 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#12039 [release-1.15] Fix bash command error
  content/zh/docs/ops/common-problems/injection/index.md
Labels: size/XS, release-notes-none

#12041 Update gateway-api version v1alpha2 -> v1beta1
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
Labels: size/S

#12044 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12045 Automator: update common-files@release-1.14 in istio/istio.io@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12048 Automator: update common-files@master in istio/istio.io@master
  LICENSE
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#12043 update hugo to 0.104.3
  netlify.toml
Labels: size/XS, cla: yes

#12058 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11998 zh: sync docs/setup/getting-started
  content/zh/docs/setup/getting-started/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.15

#12060 [release-1.15] zh: sync docs/setup/getting-started
  content/zh/docs/setup/getting-started/index.md
Labels: size/M, release-notes-none

#12028 zh:sync announcing-1.15.1/
  content/zh/news/releases/1.15.x/announcing-1.15.1/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.15

#12051 Add gateway-api instructions: secure-ingress
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/test.sh
Labels: size/XXL

#12063 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#12067 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/L, auto-merge, release-notes-none

#11727 zh: updated for ist0153
  content/zh/docs/reference/config/analysis/ist0153/index.md
Labels: translation/chinese, size/M, ok-to-test, cherrypick/release-1.15

#12017 zh:sync /ops/configuration/telemetry/envoy-stats/
  content/zh/docs/ops/configuration/telemetry/envoy-stats/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.15

#12068 [release-1.15] zh:sync /ops/configuration/telemetry/envoy-stats/
  content/zh/docs/ops/configuration/telemetry/envoy-stats/index.md
Labels: size/M, release-notes-none

#11730 zh: localize /releases/1.14.x/announcing-1.14.3/
  content/zh/news/releases/1.14.x/announcing-1.14.3/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.15

#12070 [release-1.15] zh: updated for ist0153
  content/zh/docs/reference/config/analysis/ist0153/index.md
Labels: size/M, release-notes-none

#12071 [release-1.15] zh: localize /releases/1.14.x/announcing-1.14.3/
  content/zh/news/releases/1.14.x/announcing-1.14.3/index.md
Labels: size/S, release-notes-none

#12027 zh:sync blog/2022/istio-accepted-into-cncf/
  content/zh/blog/2022/istio-accepted-into-cncf/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.15

#12072 [release-1.15] zh:sync blog/2022/istio-accepted-into-cncf/
  content/zh/blog/2022/istio-accepted-into-cncf/index.md
Labels: size/S, release-notes-none

#12069 fix operator install
  content/en/docs/setup/install/operator/test.sh
Labels: area/environments, size/XS

#12077 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  data/features.yaml
Labels: size/S, auto-merge, release-notes-none

#12076 zh: update the anchor-point for the clean-up of authz-deny and custom
  content/zh/docs/tasks/security/authorization/authz-custom/index.md
  content/zh/docs/tasks/security/authorization/authz-deny/index.md
Labels: area/security, kind/docs, translation/chinese, size/XS, ok-to-test

#12080 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#12052 Release notes for Istio 1.14.5
  content/en/news/releases/1.14.x/announcing-1.14.5/index.md
Labels: kind/docs, size/M, cherrypick/master

#12049 [release-1.14] Update istio test reference to 1.14.5 build
  go.mod
  go.sum
Labels: size/L

#12054 [release-1.13] Update istio test reference to the 1.13.9 istio commit
  go.mod
  go.sum
Labels: size/L

#12081 [master] Release notes for Istio 1.14.5
  content/en/news/releases/1.14.x/announcing-1.14.5/index.md
Labels: size/M, release-notes-none

#12053 Release notes for Istio 1.13.9
  .spelling
  content/en/news/releases/1.13.x/announcing-1.13.9/index.md
Labels: kind/docs, size/S, cla: yes, cherrypick/master

#12082 [master] Release notes for Istio 1.13.9
  .spelling
  content/en/news/releases/1.13.x/announcing-1.13.9/index.md
Labels: size/S, release-notes-none

#12055 Release Notes for 1.15.2
  content/en/docs/setup/getting-started/snips.sh
  content/en/news/releases/1.15.x/announcing-1.15.2/index.md
  data/args.yml
Labels: kind/docs, size/S

#12057 [release-1.15] Update the istio test reference to the 1.15.2 build's istio commit
  go.mod
  go.sum
Labels: size/S

#12083 Manual Cherry Pick 1.15.2 release note
  content/en/news/releases/1.15.x/announcing-1.15.2/index.md
Labels: kind/docs, size/S

#12074 [release-1.15] Update reference docs with 1.15.2
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/S

#12079 update links
  content/en/blog/2018/egress-mongo/index.md
  content/en/blog/2018/hp/index.md
  content/en/blog/2019/evolving-istios-apis/index.md
  content/en/blog/2019/isolated-clusters/index.md
  content/en/blog/2019/performance-best-practices/index.md
  content/en/blog/2020/open-usage/index.md
  content/en/blog/2020/steering-changes/index.md
  layouts/_default/baseof.html
  pkg/test/istioio/builder.go
Labels: kind/docs, size/S

#12073 Fix a link for analysis
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: kind/docs, size/M, cherrypick/release-1.15

#12085 [release-1.15] Fix a link for analysis
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
Labels: size/M, release-notes-none

#12084 Announce Istio 1.13 end of life
  content/en/news/support/announcing-1.13-eol-final/index.md
Labels: kind/docs, size/S, cherrypick/master

#12088 [master] Announce Istio 1.13 end of life
  content/en/news/support/announcing-1.13-eol-final/index.md
Labels: size/S, release-notes-none

#12091 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/XS, auto-merge, release-notes-none

#12090 zh:sync /blog/2022/introducing-ambient-mesh/
  content/zh/blog/2022/introducing-ambient-mesh/ambient-layers.png
  content/zh/blog/2022/introducing-ambient-mesh/ambient-secure-overlay.png
  content/zh/blog/2022/introducing-ambient-mesh/ambient-waypoint.png
  content/zh/blog/2022/introducing-ambient-mesh/index.md
  content/zh/blog/2022/introducing-ambient-mesh/traditional-istio.png
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.15

#12092 [release-1.15] zh:sync /blog/2022/introducing-ambient-mesh/
  content/zh/blog/2022/introducing-ambient-mesh/ambient-layers.png
  content/zh/blog/2022/introducing-ambient-mesh/ambient-secure-overlay.png
  content/zh/blog/2022/introducing-ambient-mesh/ambient-waypoint.png
  content/zh/blog/2022/introducing-ambient-mesh/index.md
  content/zh/blog/2022/introducing-ambient-mesh/traditional-istio.png
Labels: size/L, release-notes-none

#12094 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12099 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12100 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12095 zh:sync /blog/2022/get-started-ambient/
  content/zh/blog/2022/get-started-ambient/app-in-ambient-l7.png
  content/zh/blog/2022/get-started-ambient/app-in-ambient-secure-overlay.png
  content/zh/blog/2022/get-started-ambient/app-not-in-ambient.png
  content/zh/blog/2022/get-started-ambient/index.md
Labels: kind/docs, translation/chinese, size/L

#12102 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#12087 gateway-api doc: ingress-sni-passthrough
  content/en/boilerplates/gateway-api-experimental.md
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/docs/setup/additional-setup/getting-started/test.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/gtwapi_test_disabled.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/test.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/test.sh
  tests/util/gateway-api.sh
  tests/util/helpers.sh
Labels: size/L

#12108 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12105 zh:fix issues in /mtls-migration/index.md
  content/zh/docs/tasks/security/authentication/mtls-migration/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.15

#12110 [release-1.15] zh:fix issues in /mtls-migration/index.md
  content/zh/docs/tasks/security/authentication/mtls-migration/index.md
Labels: size/S, release-notes-none

#12111 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/proxy-config/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/networking/workload-entry/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/jwt/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/proxy-config/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/networking/workload-entry/index.html
  content/zh/docs/reference/config/networking/workload-group/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/XXL, auto-merge, release-notes-none

#12109 Fix broken sni-passthrough doc test
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/test.sh
  content/en/docs/tasks/traffic-management/mirroring/test.sh
  tests/util/helpers.sh
Labels: size/S

#12115 A few doc layout and clarity improvements
  content/en/docs/setup/getting-started/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: size/M

#12089 added security bulletin
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.13.x/announcing-1.13.9/index.md
  content/en/news/releases/1.14.x/announcing-1.14.5/index.md
  content/en/news/releases/1.15.x/announcing-1.15.2/index.md
  content/en/news/security/istio-security-2022-007/index.md
Labels: kind/docs, size/M, cherrypick/release-1.15

#12106 Remove restart requirement for ext-authz
  content/en/docs/tasks/security/authorization/authz-custom/index.md
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
Labels: kind/docs, size/S, ok-to-test

#12117 [release-1.15] zh:sync announcing-1.15.2/
  content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
Labels: size/S, release-notes-none

#12118 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#12114 zh: docs/ops/configuration/traffic-management/dns/
  content/zh/docs/ops/configuration/traffic-management/dns/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.15

#12121 fix route docs
  content/en/docs/concepts/traffic-management/index.md
Labels: kind/docs, size/XS, ok-to-test

#12122 fixed broken health step check
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
Labels: kind/docs, size/XS, ok-to-test

#12123 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/S, auto-merge, release-notes-none

#12124 zh: docs/tasks/traffic-management/ingress/secure-ingress/
  content/zh/boilerplates/gateway-api-support.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: kind/docs, translation/chinese, size/XL

#12113 zh:sync /examples/bookinfo/
  content/zh/docs/examples/bookinfo/index.md
Labels: kind/docs, translation/chinese, size/M

#12125 zh: chore
  content/zh/blog/2022/gateway-api-beta/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.15

#12128 [release-1.15] zh: chore
  content/zh/blog/2022/gateway-api-beta/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/S, release-notes-none

#12126 zh: sync /tasks/traffic-management/tcp-traffic-shifting/
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.15

#12132 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#12127 zh:sync /tasks/security/authorization/authz-custom/
  content/zh/docs/tasks/security/authorization/authz-custom/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.15

#12134 [release-1.15] zh:sync /tasks/security/authorization/authz-custom/
  content/zh/docs/tasks/security/authorization/authz-custom/index.md
Labels: size/M, release-notes-none

#12135 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12130 zh: docs/ops/deployment/requirements
  content/zh/docs/ops/deployment/requirements/index.md
Labels: kind/docs, translation/chinese, size/L

#12133 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
Labels: size/L, auto-merge, release-notes-none

#12137 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/XS, auto-merge, release-notes-none

#12139 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12138 Prepare for release 1.16.0
  Makefile.core.mk
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/zh/docs/reference/commands/istioctl/index.html
  data/args.yml
  go.mod
  go.sum
Labels: size/L

#12143 Update release order on https://istio.io/news/releases/
  content/en/news/releases/1.15.x/_index.md
Labels: size/XS, cherrypick/release-1.15

#12144 [release-1.15] Update release order on https://istio.io/news/releases/
  content/en/news/releases/1.15.x/_index.md
Labels: size/XS, release-notes-none

#12145 zh:sync /releases/supported-releases/
  content/zh/docs/releases/supported-releases/index.md
Labels: kind/docs, translation/chinese, size/S

#12146 zh:sync /get-involved/_index.md
  content/zh/get-involved/_index.md
Labels: kind/docs, translation/chinese, size/S

#12147 zh:sync /enabling-defense-in-depth-for-enterprise-applications/
  content/zh/about/solutions/enabling-defense-in-depth-for-enterprise-applications/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.15

#12148 [release-1.15] zh:sync /enabling-defense-in-depth-for-enterprise-applications/
  content/zh/about/solutions/enabling-defense-in-depth-for-enterprise-applications/index.md
Labels: size/M, release-notes-none

#12149 make case study suggestion support multi language
  i18n/en.toml
  i18n/zh.toml
  layouts/partials/case_study_suggestions.html
Labels: size/XS

#12151 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12152 [release-1.15] make case study suggestion support multi language
  i18n/en.toml
  i18n/zh.toml
  layouts/partials/case_study_suggestions.html
Labels: size/XS, release-notes-none

#12153 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#12136 zh:sync /ops/common-problems/network-issues/
  content/zh/docs/ops/common-problems/network-issues/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.15

#12142 fix table
  src/sass/base/_base.scss
  src/sass/misc/_article.scss
Labels: area/user experience, size/S

#12161 [release-1.15] zh:sync /ops/common-problems/network-issues/
  content/zh/docs/ops/common-problems/network-issues/index.md
Labels: size/L, release-notes-none

#12157 Add 1.15.3 release notes
  content/en/news/releases/1.15.x/announcing-1.15.3/index.md
Labels: size/S

#12150 add Baidu AI Cloud to the Istio ecosystem page.
  data/companies.yml
  static/logos/baidu-ai-cloud.svg
Labels: kind/docs, size/M

#12158 Explain counter and distribution
  content/en/docs/reference/config/metrics/index.md
Labels: kind/docs, size/XS

#12162 [release-1.15] Cherry pick 1.15.3's release notes
  content/en/docs/setup/getting-started/snips.sh
  content/en/news/releases/1.15.x/announcing-1.15.3/index.md
  data/args.yml
Labels: kind/docs, size/M

#12164 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#12165 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#12166 [zh] sync content/zh/docs/reference/config/metrics/index.md
  content/zh/docs/reference/config/metrics/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#12167 zh:sync /releases/1.15.x/announcing-1.15.3/
  content/zh/news/releases/1.15.x/announcing-1.15.3/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.15

#12168 [release-1.15] zh:sync /releases/1.15.x/announcing-1.15.3/
  content/zh/news/releases/1.15.x/announcing-1.15.3/index.md
Labels: size/S, release-notes-none

#12140 Document Sidecar Ingress TLS Termination Feature
  content/en/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/test.sh
Labels: area/networking, kind/docs, size/XL

#12159 [release-1.15] Update the 1.15 test reference to the 1.15.3 build
  go.mod
  go.sum
Labels: size/S

#12163 gateway-api: more gateway api documentation
  content/en/boilerplates/gateway-api-future.md
  content/en/boilerplates/gateway-api-support.md
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
Labels: size/M

#12160 [release-1.15] Update reference docs for 1.15.3
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/XS

#12156 gateway-api: enable mutual tls test
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/test.sh
  tests/util/verify.sh
Labels: size/M
