Repository istio/istio.io, pull requests merged in 2022-03, with the labels that each got.

#10989 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#10992 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#10963 Fix docs for installation: Istio Operator is not suggested for a production environment
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/operator/index.md
Labels: area/environments, kind/docs, area/user experience, size/S, ok-to-test

#10991 [release-1.13] Update PILOT_ENABLE_LEGACY_ISTIO_MUTUAL_CREDENTIAL_NAME value for 1.11
  content/en/news/releases/1.11.x/announcing-1.11.6/index.md
Labels: size/XS, release-notes-none

#10996 [release-1.13] Possible fix for test flake
  content/en/docs/tasks/traffic-management/egress/http-proxy/test.sh
Labels: size/XS, release-notes-none

#10993 [release-1.13] Fix docs for installation: Istio Operator is not suggested for a production environment
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/operator/index.md
Labels: size/S, release-notes-none

#10979 Update to use dynamic version
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: size/XS, cherrypick/release-1.13

#10997 [release-1.13] Update to use dynamic version
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: size/XS, release-notes-none

#10998 Clarify injection for gateways
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/install/helm/index.md
Labels: size/XS

#11002 [release-1.13] Clarify injection for gateways
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/install/helm/index.md
Labels: size/XS, release-notes-none

#11004 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11005 [release-1.12] Update istio test reference to 1.12.5
  go.mod
  go.sum
Labels: size/S

#11006 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#11007 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11008 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: size/S, auto-merge, release-notes-none

#11010 Automator: update common-files@release-1.13 in istio/istio.io@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11009 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11012 Automator: update common-files@release-1.11 in istio/istio.io@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11014 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11011 Automator: update common-files@release-1.12 in istio/istio.io@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11018 [release-1.13] Add Stilingue as Istio user
  data/companies.yml
  static/logos/stilingue.svg
Labels: size/S, release-notes-none

#11015 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#10834 Add Merbridge blog - use ebpf to accelerate the Istio dataplane
  .spelling
  content/en/blog/2022/_index.md
  content/en/blog/2022/merbridge/1.png
  content/en/blog/2022/merbridge/2.png
  content/en/blog/2022/merbridge/3.png
  content/en/blog/2022/merbridge/4.png
  content/en/blog/2022/merbridge/5.png
  content/en/blog/2022/merbridge/6.png
  content/en/blog/2022/merbridge/7.png
  content/en/blog/2022/merbridge/8.png
  content/en/blog/2022/merbridge/9.png
  content/en/blog/2022/merbridge/index.md
Labels: kind/docs, size/L, cherrypick/release-1.13

#11019 [release-1.13] Add Merbridge blog - use ebpf to accelerate the Istio dataplane
  .spelling
  content/en/blog/2022/_index.md
  content/en/blog/2022/merbridge/1.png
  content/en/blog/2022/merbridge/2.png
  content/en/blog/2022/merbridge/3.png
  content/en/blog/2022/merbridge/4.png
  content/en/blog/2022/merbridge/5.png
  content/en/blog/2022/merbridge/6.png
  content/en/blog/2022/merbridge/7.png
  content/en/blog/2022/merbridge/8.png
  content/en/blog/2022/merbridge/9.png
  content/en/blog/2022/merbridge/index.md
Labels: size/L, release-notes-none

#11017 Accessibility update "go to top"
  layouts/_default/baseof.html
Labels: size/XS

#11003 clarify grpc-web
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: area/networking, kind/docs, size/XS

#11020 [release-1.13] Accessibility update "go to top"
  layouts/_default/baseof.html
Labels: size/XS, release-notes-none

#11021 [release-1.13] clarify grpc-web
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: size/XS, release-notes-none

#11023 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11036 [release-1.12] Update istio reference to 1.12.5
  go.mod
  go.sum
Labels: size/S

#11037 [release-1.11] Update istio test reference to 1.11.8
  go.mod
  go.sum
Labels: size/S

#11034 [release-1.13] Update reference docs for 1.13.2
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
Labels: size/S

#11035 [release-1.13] Update istio test reference to 1.13.2
  go.mod
  go.sum
Labels: size/S

#11038 March 2022 CVE
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/docs/setup/getting-started/snips.sh
  content/en/news/releases/1.11.x/announcing-1.11.8/index.md
  content/en/news/releases/1.12.x/announcing-1.12.5/index.md
  content/en/news/releases/1.13.x/announcing-1.13.2/index.md
  content/en/news/security/istio-security-2022-003/index.md
  content/en/news/security/istio-security-2022-004/index.md
  data/args.yml
Labels: size/L, cla: yes, cherrypick/master

#11040 Manual cherry-pick of #11038
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.11.x/announcing-1.11.8/index.md
  content/en/news/releases/1.12.x/announcing-1.12.5/index.md
  content/en/news/releases/1.13.x/announcing-1.13.2/index.md
  content/en/news/security/istio-security-2022-003/index.md
  content/en/news/security/istio-security-2022-004/index.md
Labels: size/L

#11028 zh-translation: update setup/platform-setup/kops/index.md
  content/zh/docs/setup/platform-setup/kops/index.md
Labels: kind/docs, translation/chinese, size/XS

#11029 zh-translation: update docs/setup/platform-setup/docker/index.md
  content/zh/docs/setup/platform-setup/docker/index.md
Labels: kind/docs, translation/chinese, size/XS

#10750 zh:kubernetes-1.22-with-older-releases.md
  content/zh/events/banners/kubernetes-1.22-with-older-releases.md
Labels: kind/docs, translation/chinese, size/XS

#10951 sync en docs pr to zh:multicluster traffic management #10486
  content/zh/docs/ops/configuration/traffic-management/multicluster/index.md
  content/zh/docs/ops/deployment/deployment-models/index.md
  content/zh/docs/releases/bugs/index.md
Labels: kind/docs, translation/chinese, size/L, ok-to-test

#10953 zh:news/releases/1.12.x/announcing-1.12.1/index.md
  content/zh/news/releases/1.12.x/announcing-1.12.1/index.md
Labels: kind/docs, translation/chinese, size/M

#11031 zh: zh/setup/getting-started/index.md
  content/zh/docs/setup/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS

#11025 zh: update request-routing docs
  content/zh/docs/tasks/traffic-management/request-routing/index.md
Labels: kind/docs, translation/chinese, size/XS

#10994 zh:docs/reference/glossary/injection.md/auto-mtls.mdgateway.md
  content/zh/docs/reference/glossary/auto-mtls.md
  content/zh/docs/reference/glossary/gateway.md
  content/zh/docs/reference/glossary/injection.md
Labels: kind/docs, translation/chinese, size/S

#10746 zh:/about/faq/metrics-and-logs/metric-expiry.md
  content/zh/about/faq/metrics-and-logs/metric-expiry.md
Labels: kind/docs, translation/chinese, size/S, lifecycle/automatically-closed

#11030 zh: update zh/content/en/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/operator/index.md
Labels: kind/docs, translation/chinese, size/XS

#11041 Workaround for issue #37674
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
Labels: area/environments, size/XS, cherrypick/release-1.13

#11042 [release-1.13] Workaround for issue #37674
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
Labels: size/XS, release-notes-none

#11043 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#11044 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#11024 zh: update tasks/observability/logs/access-log file
  content/zh/docs/tasks/observability/logs/access-log/index.md
Labels: kind/docs, translation/chinese, size/L

#11026 zh: update oci docs
  content/zh/docs/setup/platform-setup/oci/index.md
Labels: kind/docs, translation/chinese, size/M

#11046 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#11027 zh: update access-log
  content/zh/docs/tasks/observability/logs/access-log/index.md
Labels: kind/docs, translation/chinese, size/M

#10999 Update support policy to reflect changes
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS, cherrypick/release-1.13

#11049 [release-1.13] Update support policy to reflect changes
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS, release-notes-none

#11050 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/S, auto-merge, release-notes-none

#11051 Fix scripts for shellcheck 0.8
  .gitignore
  config.toml
  scripts/lint_site.sh
Labels: kind/docs, size/S

#11052 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11053 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: size/L, auto-merge, release-notes-none

#10995 zh:/news/security/istio-security-2022-003/index.md
  content/zh/news/security/istio-security-2022-003/index.md
Labels: kind/docs, translation/chinese, size/M

#11056 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11059 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/M, auto-merge, release-notes-none

#11067 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/proxy-config/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
Labels: size/L, auto-merge, release-notes-none

#11065 fix wide tables under the table of contents
  src/sass/base/_base.scss
Labels: area/user experience, size/XS, cherrypick/release-1.13

#11068 [release-1.13] fix wide tables under the table of contents
  src/sass/base/_base.scss
Labels: size/XS, release-notes-none

#11072 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11073 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: size/M, auto-merge, release-notes-none

#11071 Add document on "Understanding DNS"
  content/en/docs/ops/configuration/traffic-management/dns/index.md
Labels: size/M

#11066 Clarify resource annotations behavior
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: size/M

#11074 [release-1.13] Add document on "Understanding DNS"
  content/en/docs/ops/configuration/traffic-management/dns/index.md
Labels: size/M, release-notes-none

#11063 1.11 EOL is approaching
  content/en/news/support/announcing-1.11-eol/index.md
Labels: size/S, cherrypick/release-1.13

#11075 [release-1.13] 1.11 EOL is approaching
  content/en/news/support/announcing-1.11-eol/index.md
Labels: size/S, release-notes-none

#11076 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/L, auto-merge, release-notes-none

#11077 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/telemetry/index.html
Labels: size/L, auto-merge, release-notes-none

#11080 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
Labels: size/M, auto-merge, release-notes-none

#11079 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#11083 Add istiocon registration blog
  content/en/blog/2022/istiocon-register/index.md
  content/en/blog/2022/istiocon-register/istioconreg.jpg
Labels: size/S

#11084 [release-1.13] Add istiocon registration blog
  content/en/blog/2022/istiocon-register/index.md
  content/en/blog/2022/istiocon-register/istioconreg.jpg
Labels: size/S, release-notes-none

#11087 [release-1.13] Add banner for IstioCon 2022 registration
  content/en/events/banners/istiocon-2022.md
Labels: size/XS, release-notes-none

#11088 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11089 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  data/analysis.yaml
Labels: size/L, auto-merge, release-notes-none

#11086 [zh] create index.md about announcing-1.11-eol
  content/zh/news/support/announcing-1.11-eol/index.md
Labels: kind/docs, size/S, ok-to-test

#11085 doc: change 'plain text' to 'plaintext'
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
Labels: kind/docs, size/XS, ok-to-test

#11092 fix aeraki github address
  content/en/blog/2021/aeraki/index.md
Labels: kind/docs, size/S

#11094 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11093 [release-1.13] fix aeraki github address
  content/en/blog/2021/aeraki/index.md
Labels: size/S, release-notes-none

#11096 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11097 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#11090 Attempt to build on netlify with 0.95.0 hugo
  netlify.toml
Labels: kind/docs, size/XS

#11100 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11102 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
Labels: size/M, auto-merge, release-notes-none

#11101 Restore bugs.svg
  src/icons/bugs.svg
Labels: kind/docs, size/XS

#11104 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11105 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#11106 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11110 1.11 EOL
  content/en/news/support/announcing-1.11-eol-final/index.md
Labels: cherrypick/release-1.13

#11103 Fix workload aggregating rules for TCP byte metrics
  content/en/docs/ops/best-practices/observability/index.md
  content/zh/docs/ops/best-practices/observability/index.md
Labels: area/policies and telemetry, kind/docs, size/L, ok-to-test

#11113 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11112 [release-1.13] 1.11 EOL
  content/en/news/support/announcing-1.11-eol-final/index.md
Labels: size/S, release-notes-none

#11099 Istioctl on remote clusters blog post
  content/en/blog/2022/istioctl-proxy/index.md
  content/en/blog/2022/istioctl-proxy/istioctl-primary-cluster.svg
  content/en/blog/2022/istioctl-proxy/istioctl-remote-cluster.svg
Labels: kind/docs, area/user experience, size/L, cherrypick/release-1.13

#11114 [release-1.13] Istioctl on remote clusters blog post
  content/en/blog/2022/istioctl-proxy/index.md
  content/en/blog/2022/istioctl-proxy/istioctl-primary-cluster.svg
  content/en/blog/2022/istioctl-proxy/istioctl-remote-cluster.svg
Labels: size/L, release-notes-none

#11115 [release-1.13] Fix workload aggregating rules for TCP byte metrics
  content/en/docs/ops/best-practices/observability/index.md
  content/zh/docs/ops/best-practices/observability/index.md
Labels: size/L, release-notes-none

#11116 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11122 [release-1.12] Update istio test reference to 1.12.6
  go.mod
  go.sum
Labels: size/XS

#11119 Update istio test reference (as well as api, pkg, and client-go)
  go.mod
  go.sum
Labels: size/XL

#11123 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/M, auto-merge, release-notes-none

#11125 [release-1.13] Remove tip for bad script
  content/en/docs/setup/platform-setup/kind/index.md
Labels: size/S, release-notes-none

#11126 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
Labels: size/S, auto-merge, release-notes-none

#11128 [ZH] Fix Jaeger installation link
  content/zh/docs/tasks/observability/distributed-tracing/jaeger/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#11129 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11131 fix indentation for custom tags
  content/en/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
Labels: size/XS, cherrypick/release-1.13
