Repository istio/istio.io, pull requests merged in 2022-05, with the labels that each got.

#11246 rollback of unnecessary changes
  src/sass/base/_constants.scss
Labels: size/XS, cherrypick/release-1.13

#11250 [release-1.13] rollback of unnecessary changes
  src/sass/base/_constants.scss
Labels: size/XS, release-notes-none

#11249 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#11245 [zh] Sync en docs in docs/concepts/_index.md
  content/zh/docs/concepts/_index.md
Labels: kind/docs, translation/chinese, size/XS

#11248 Update content/en/about/faq/security/verify-mtls-encryption.md
  content/en/about/faq/security/verify-mtls-encryption.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#11238 Add Statsig as a user
  data/companies.yml
  static/logos/statsig.svg
Labels: kind/docs, size/XS, cherrypick/release-1.13

#11255 [release-1.13] Add Statsig as a user
  data/companies.yml
  static/logos/statsig.svg
Labels: size/XS, release-notes-none

#11166 User guide for Istio TLS configuration
  content/en/docs/tasks/security/tls-configuration/_index.md
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/snips.sh
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/test.sh
Labels: area/security, size/L

#11260 zh-update: istio-has-applied-to-join-the-cncf.md
  content/zh/events/banners/istio-has-applied-to-join-the-cncf.md
Labels: size/XS

#10730 zh:/news/releases/1.12.x/announcing-1.12/_index.md
  content/zh/news/releases/1.12.x/announcing-1.12/_index.md
Labels: translation/chinese, size/M, cherrypick/release-1.12

#10741 zh:/blog/2021/direct-upgrade/index.md
  content/zh/blog/2021/direct-upgrade/index.md
Labels: kind/docs, translation/chinese, size/M

#11258 Update:zh-update-/releases/security-vulnerabilities/index.md
  content/zh/docs/releases/security-vulnerabilities/index.md
Labels: kind/docs, translation/chinese, size/XS

#11263 Automator: update common-files@master in istio/istio.io@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#11221 fix multicluster prometheus
  content/en/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/index.md
Labels: area/policies and telemetry, size/XS

#11265 Update zh/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/index.md
  content/zh/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/index.md
Labels: kind/docs, size/XS

#11271 fix incorrect name of validation webhook
  content/en/docs/ops/common-problems/validation/index.md
Labels: kind/docs, size/XS

#11262 [release-1.13] zh:/news/releases/1.12.x/announcing-1.12/_index.md
  content/zh/news/releases/1.12.x/announcing-1.12/_index.md
Labels: translation/chinese, size/M, release-notes-none

#11269 Update istio test reference to the new 1.14.0-alpha.0 build
  go.mod
  go.sum
Labels: size/XS

#11273 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
Labels: size/XL, auto-merge, release-notes-none

#11267 Release notes for 1.12.7
  content/en/news/releases/1.12.x/announcing-1.12.7/index.md
Labels: size/S, cherrypick/release-1.13

#11274 [release-1.13] Release notes for 1.12.7
  content/en/news/releases/1.12.x/announcing-1.12.7/index.md
Labels: size/S, release-notes-none

#11275 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
Labels: size/XS, auto-merge, release-notes-none

#11282 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  data/analysis.yaml
Labels: size/M, auto-merge, release-notes-none

#11286 zh: zh/integrations/kiali/index.md
  content/zh/docs/ops/integrations/kiali/index.md
Labels: translation/chinese, size/XS

#11290 Automator: update istio.io@ reference docs
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
Labels: size/XL, auto-merge, release-notes-none

#11292 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11294 Added Planday as user of Istio
  data/companies.yml
  static/logos/planday.svg
Labels: size/S, ok-to-test

#11295 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#11298 Automator: update common-files@release-1.13 in istio/istio.io@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11047 zh: update blog 2022 merbridge
  content/zh/blog/2022/_index.md
  content/zh/blog/2022/merbridge/1.png
  content/zh/blog/2022/merbridge/2.png
  content/zh/blog/2022/merbridge/3.png
  content/zh/blog/2022/merbridge/4.png
  content/zh/blog/2022/merbridge/5.png
  content/zh/blog/2022/merbridge/6.png
  content/zh/blog/2022/merbridge/7.png
  content/zh/blog/2022/merbridge/8.png
  content/zh/blog/2022/merbridge/9.png
  content/zh/blog/2022/merbridge/index.md
Labels: kind/docs, translation/chinese, size/L

#11299 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  data/analysis.yaml
Labels: size/M, auto-merge, release-notes-none

#11303 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11281 Add webhooks to test framework snapshot
  content/en/docs/examples/virtual-machines/test.sh
  content/en/docs/ops/configuration/telemetry/envoy-stats/test.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  content/en/docs/setup/additional-setup/cni/test.sh
  content/en/docs/setup/getting-started/test.sh
  content/en/docs/setup/install/external-controlplane/test.sh
  content/en/docs/setup/install/multicluster/common.sh
  content/en/docs/setup/install/virtual-machine/test.sh
  content/en/docs/tasks/observability/gateways/secure_access_test.sh
  content/en/docs/tasks/observability/metrics/customize-metrics/test.sh
  content/en/docs/tasks/security/cert-management/dns-cert/test.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/test.sh
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/test.sh
  pkg/test/istioio/snapshot.go
Labels: size/L

#11296 zh: zh/common-problems/security-issues/index.md
  content/zh/docs/ops/common-problems/security-issues/index.md
Labels: translation/chinese, size/XS

#11297 zh: setup/install/helm/index.md
  content/zh/docs/setup/install/helm/index.md
Labels: translation/chinese, size/L

#11259 zh:/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
  content/zh/docs/tasks/security/tls-configuration/_index.md
  content/zh/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
  content/zh/docs/tasks/security/tls-configuration/workload-min-tls-version/snips.sh
  content/zh/docs/tasks/security/tls-configuration/workload-min-tls-version/test.sh
Labels: kind/docs, translation/chinese, size/L

#11284 zh: content/zh/about/faq/setup/install-method-selection.md
  content/zh/about/faq/setup/install-method-selection.md
Labels: translation/chinese, size/S

#11285 zh: content/zh/docs/ops/configuration/mesh/webhook/index.md
  content/zh/docs/ops/configuration/mesh/webhook/index.md
Labels: translation/chinese, size/XS

#11287 zh: supported-releases/index.md
  content/zh/docs/releases/supported-releases/index.md
Labels: translation/chinese, size/S

#11288 zh: content/zh/docs/setup/additional-setup/cni/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: translation/chinese, size/S

#11283 zh: docs/tasks/observability/distributed-tracing/mesh-and-proxy-confi…
  content/zh/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
Labels: translation/chinese, size/L

#11306 zh: content/zh/about/faq/distributed-tracing/control-sampling.md
  content/zh/about/faq/distributed-tracing/control-sampling.md
Labels: translation/chinese, size/XS

#11310 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11309 1.13.4 release note
  content/en/docs/setup/getting-started/snips.sh
  content/en/news/releases/1.13.x/announcing-1.13.4/index.md
  data/args.yml
Labels: size/S, cherrypick/master

#11318 Fix https://github.com/istio/istio.io/issues/11317
  content/en/news/releases/1.13.x/announcing-1.13.4/index.md
Labels: size/S

#11304 [release-1.13] Update Istio test reference to 1.13.4
  go.mod
  go.sum
Labels: size/S

#11320 Update istio reference to recent 1.14 commit.
  go.mod
  go.sum
Labels: size/S

#11325 docs: style format
  content/zh/docs/concepts/traffic-management/index.md
Labels: kind/docs, size/XS, ok-to-test

#11301 Document Egress mTLS origination at sidecar using credentialName in DR
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/tls_test.sh
Labels: area/networking, size/L

#11327 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11332 Egress TLS Origination - fix typos
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
Labels: size/XS

#11331 Fix console log error
  content/zh/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
Labels: translation/chinese, size/XS, ok-to-test

#11335 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11337 Update multicluster test kind image
  archive/v1.10/docs/tasks/traffic-management/locality-load-balancing/common.sh
  archive/v1.10/zh/docs/tasks/traffic-management/locality-load-balancing/common.sh
  archive/v1.11/docs/tasks/traffic-management/locality-load-balancing/common.sh
  archive/v1.11/zh/docs/tasks/traffic-management/locality-load-balancing/common.sh
  archive/v1.12/docs/tasks/traffic-management/locality-load-balancing/common.sh
  archive/v1.12/zh/docs/tasks/traffic-management/locality-load-balancing/common.sh
  archive/v1.9/docs/tasks/traffic-management/locality-load-balancing/common.sh
  common/config/.golangci-format.yml
  content/en/docs/tasks/traffic-management/locality-load-balancing/common.sh
  content/zh/docs/tasks/traffic-management/locality-load-balancing/common.sh
  prow/integ-suite-kind.sh
Labels: size/S

#11340 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
Labels: size/XS, auto-merge, release-notes-none

#11338 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#11342 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/XS, auto-merge, release-notes-none

#11343 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#11345 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#11333 Revert to BlackFriday if Goldmark issues cannot be fixed.
  config.toml
Labels: size/S

#11334 Update supported versions
  data/args.yml
Labels: size/XS

#11344 Add document for kernel module requirements under platform setup
  .spelling
  content/en/docs/setup/platform-setup/prerequisites/index.md
Labels: area/environments, kind/docs, size/M

#11346 Fix title ("mininum" > "minimum")
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
Labels: size/XS, ok-to-test

#11348 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, auto-merge, release-notes-none

#11347 Update istio test ref to latest 1.14.0 build
  go.mod
  go.sum
Labels: size/S

#11349 fix istioctl install twice
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: size/XS

#11358 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#11300 Add Cloud Scale Inc as pro services
  data/companies.yml
  static/logos/cloudscaleinc.png
Labels: kind/docs, size/XS, ok-to-test

#11264 Istio 1.14 release announcement, change-notes, and upgrade-notes
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.14.x/_index.md
  content/en/news/releases/1.14.x/announcing-1.14/_index.md
  content/en/news/releases/1.14.x/announcing-1.14/change-notes/index.md
  content/en/news/releases/1.14.x/announcing-1.14/upgrade-notes/index.md
Labels: area/test and release, size/L

#11350 fixing #11311 try 2 (1.0 broken diagram and fortio iframe fixes)
  archive/v1.0/docs/concepts/performance-and-scalability/index.html
Labels: kind/docs, size/XS
