Repository istio/istio.io, pull requests merged in 2023-09, with the labels that each got.

#13801 [zh] Sync #13794 into Chinese
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: kind/docs, translation/chinese, size/XS

#13792 [zh] Optimize translation into Chinese
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#13802 [zh] Sync #13798 into Chinese
  content/zh/boilerplates/gateway-api-gamma-support.md
Labels: kind/docs, translation/chinese, size/S

#13788 [zh] Sync #13782 with some format fix for about/* for Chinese docs
  content/zh/about/faq/distributed-tracing/how-to-support-tracing.md
  content/zh/about/faq/distributed-tracing/initial-zipkin-header.md
  content/zh/about/faq/distributed-tracing/istio-copy-headers.md
  content/zh/about/faq/distributed-tracing/minimal-requirements.md
  content/zh/about/faq/general/how-do-i-contribute.md
  content/zh/about/faq/general/how-do-i-get-started.md
  content/zh/about/faq/general/what-deployment-environment.md
  content/zh/about/faq/general/what-is-istio.md
  content/zh/about/faq/general/where-is-the-documentation.md
  content/zh/about/faq/general/why-use-istio.md
  content/zh/about/faq/metrics-and-logs/accessing-telemetry-via-rest.md
  content/zh/about/faq/metrics-and-logs/life-of-a-request.md
  content/zh/about/faq/metrics-and-logs/metric-expiry.md
  content/zh/about/faq/metrics-and-logs/mixer-migration.md
  content/zh/boilerplates/gateway-api-experimental.md
  content/zh/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
Labels: kind/docs, translation/chinese, size/L

#13803 Refine prometheus scrape in FAQ
  content/en/about/faq/metrics-and-logs/prometheus-application-metrics.md
Labels: kind/docs, size/S, ok-to-test

#13806 Fix deprecation warning message
  hugo.toml
Labels: kind/docs, size/XS

#13808 gateway-api: use standard crd install command in mesh docs
  content/en/boilerplates/gateway-api-gamma-support.md
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
Labels: size/S

#13809 [release-1.18] Update 1.17 EOL est date to Oct
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#13804 [zh] Sync #13803 into Chinese
  content/zh/about/faq/metrics-and-logs/prometheus-application-metrics.md
Labels: kind/docs, translation/chinese, size/S

#13810 [zh] Sync Gateway API GAMMA support
  content/zh/boilerplates/gateway-api-gamma-support.md
Labels: kind/docs, translation/chinese, size/XS

#13812 [zh-cn] sync deployment/vm-architecture
  content/zh/docs/setup/install/virtual-machine/index.md
Labels: kind/docs, translation/chinese

#13783 Release Notes - 1.19.0
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.19.x/_index.md
  content/en/news/releases/1.19.x/announcing-1.19/_index.md
  content/en/news/releases/1.19.x/announcing-1.19/change-notes/index.md
  content/en/news/releases/1.19.x/announcing-1.19/upgrade-notes/index.md
  data/compatibility/supportStatus.yml
Labels: area/test and release, kind/docs, size/L

#13816 update_ref_docs fails on an arm machine
  content/en/blog/2021/wasm-progress/index.md
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/analysis/ist0117/index.md
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/proxy_extensions/metadata_exchange/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/analysis/ist0117/index.md
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/proxy_extensions/metadata_exchange/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  data/analysis.yaml
  scripts/grab_reference_docs.sh
  scripts/grab_reference_docs_zh.sh
Labels: size/XXL

#13682 Add more Info to locality load balancing page
  content/en/docs/tasks/traffic-management/locality-load-balancing/_index.md
  content/en/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/index.md
Labels: kind/docs, size/M

#13799 update hugo to 0.117.0
  netlify.toml
Labels: size/XS

#13818 [release-1.19] Update istio test ref to the 1.19.0 commit
  go.mod
  go.sum
Labels: size/S

#13717 For 1.20, drop requirement to have a Service associated with a pod
  content/en/docs/ops/deployment/requirements/index.md
Labels: release-notes-none

#13795 Remove anyuid instructions for OpenShift
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: size/S, ok-to-test

#13820 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/S, auto-merge, release-notes-none

#13823 [zh] Sync #13816 and fix format of WASM blog
  content/zh/blog/2021/wasm-progress/index.md
Labels: kind/docs, translation/chinese, size/L

#13821 [zh] Sync release 1.19 release announcement and upgrade notes into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/_index.md
  content/zh/news/releases/1.19.x/announcing-1.19/_index.md
  content/zh/news/releases/1.19.x/announcing-1.19/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#13827 update the release 1.19 perf data
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
Labels: area/perf and scalability, kind/docs, size/XXL

#13822 adding Amazon EKS with Istio setup to platform-setup page
  content/en/docs/setup/platform-setup/amazon-eks/index.md
Labels: kind/docs, size/S, ok-to-test

#13828 [release-1.19] adding Amazon EKS with Istio setup to platform-setup page
  content/en/docs/setup/platform-setup/amazon-eks/index.md
Labels: size/S, release-notes-none

#13829 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13830 Automator: update common-files@release-1.19 in istio/istio.io@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13832 [zh] Sync #13822 AWS EKS into Chinese
  content/zh/docs/setup/platform-setup/amazon-eks/index.md
Labels: kind/docs, translation/chinese, size/S

#13826 [zh] Sync #13717 into Chinese
  content/zh/docs/ops/deployment/requirements/index.md
Labels: kind/docs, translation/chinese, size/XS

#13831 [zh] Sync #13827 into Chinese
  content/zh/docs/ops/deployment/performance-and-scalability/index.md
Labels: kind/docs, translation/chinese, size/XS

#13833 Automator: update common-files@release-1.18 in istio/istio.io@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13825 [zh] Sync docs/tasks/traffic-management/locality-load-balancing
  content/zh/docs/tasks/traffic-management/locality-load-balancing/_index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/index.md
Labels: kind/docs, translation/chinese, size/M

#13838 [master] update the release 1.19 perf data
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
Labels: size/XXL, release-notes-none

#13836 [release-1.19] [zh] Sync #13822 AWS EKS into Chinese
  content/zh/docs/setup/platform-setup/amazon-eks/index.md
Labels: size/S, release-notes-none

#13839 [release-1.19] [zh] Sync docs/tasks/traffic-management/locality-load-balancing
  content/zh/docs/tasks/traffic-management/locality-load-balancing/_index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/index.md
Labels: size/M, release-notes-none

#13784 [release 1.18] Update istio test ref for 1.18.3
  go.mod
  go.sum
Labels: size/S

#13841 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/L, auto-merge, release-notes-none

#13824 [zh] Sync change notes 1.19 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/announcing-1.19/_index.md
  content/zh/news/releases/1.19.x/announcing-1.19/change-notes/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.19

#13842 [release-1.19] [zh] Sync change notes 1.19 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/announcing-1.19/_index.md
  content/zh/news/releases/1.19.x/announcing-1.19/change-notes/index.md
Labels: size/L, release-notes-none

#13843 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13778 Fixed numbering for installation steps in the tip
  content/en/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/operator/index.md
Labels: kind/docs, size/XS, ok-to-test

#13847 fix typo in security and lightstep
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
Labels: translation/chinese, size/XS, ok-to-test

#13850 [release-1.19] Fixed numbering for installation steps in the tip
  content/en/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/operator/index.md
Labels: size/XS, release-notes-none

#13851 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13852 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/XS, auto-merge, release-notes-none

#13845 update hugo to 0.118.2
  netlify.toml
Labels: area/user experience, size/XS

#13856 1.18.3 release notes
  content/en/news/releases/1.18.x/announcing-1.18.3/index.md
Labels: kind/docs, size/M, cherrypick/release-1.19

#13858 Aws eks setup
  content/en/docs/setup/platform-setup/amazon-eks/index.md
Labels: kind/docs, size/XS, ok-to-test

#13857 [release-1.19] 1.18.3 release notes
  content/en/news/releases/1.18.x/announcing-1.18.3/index.md
Labels: size/M, release-notes-none

#13855 Document special case for gateway install on OpenShift
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/gateway/snips.sh
  content/en/docs/setup/additional-setup/gateway/test.sh
Labels: size/S

#13860 Manual cherry-pick of #13858
  content/en/docs/setup/platform-setup/amazon-eks/index.md
Labels: size/XS

#13861 [zh] Sync /additional-setup/gateway/
  content/zh/docs/setup/additional-setup/gateway/index.md
Labels: translation/chinese, size/S

#13864 [zh] Sync #13858 into Chinese
  content/zh/docs/setup/platform-setup/amazon-eks/index.md
Labels: translation/chinese, size/XS

#13863 Remove the SVG tips generated by draw.io
  content/en/docs/setup/additional-setup/gateway/canary-upgrade.svg
  content/en/docs/setup/additional-setup/gateway/high-level-canary.svg
  content/en/docs/setup/additional-setup/gateway/inplace-upgrade.svg
  content/en/docs/setup/additional-setup/gateway/shared-gateway.svg
  content/en/docs/setup/additional-setup/gateway/user-gateway.svg
Labels: size/XXL, cherrypick/release-1.19

#13865 [release-1.19] [zh] Sync 1.18.3 release notes into Chinese
  content/zh/news/releases/1.18.x/announcing-1.18.3/index.md
Labels: size/M, release-notes-none

#13866 [release-1.19] [zh] Sync #13858 into Chinese
  content/zh/docs/setup/platform-setup/amazon-eks/index.md
Labels: size/XS, release-notes-none

#13869 [zh] Sync SVGs in /setup/additional-setup/gateway/
  content/zh/docs/setup/additional-setup/gateway/canary-upgrade.svg
  content/zh/docs/setup/additional-setup/gateway/high-level-canary.svg
  content/zh/docs/setup/additional-setup/gateway/inplace-upgrade.svg
  content/zh/docs/setup/additional-setup/gateway/shared-gateway.svg
  content/zh/docs/setup/additional-setup/gateway/user-gateway.svg
Labels: kind/docs, translation/chinese, size/XXL, cherrypick/release-1.19

#13873 Small correction in dual-stack blog
  content/en/blog/2023/experimental-dual-stack/index.md
Labels: size/XS, cherrypick/release-1.19

#13876 [zh] Sync #13873 into Chinese
  content/zh/blog/2023/experimental-dual-stack/index.md
Labels: kind/docs, translation/chinese, size/XS

#13878 [release-1.19] [zh] Sync #13873 into Chinese
  content/zh/blog/2023/experimental-dual-stack/index.md
Labels: size/XS, release-notes-none

#13879 Update index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
Labels: size/XS, ok-to-test

#13880 Fix insecure directory command
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: size/XS, cherrypick/release-1.19

#13882 [release-1.19] Fix insecure directory command
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: size/XS, release-notes-none

#13884 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
Labels: size/M, auto-merge, release-notes-none

#13886 [zh] Sync #13880 into Chinese
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.19

#13885 [zh] Sync #13879 into Chinese
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.19

#13888 [release-1.19] [zh] Sync #13880 into Chinese
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
Labels: size/XS, release-notes-none

#13889 [release-1.19] [zh] Sync #13879 into Chinese
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XS, release-notes-none

#13874 [zh] sync wildcard-egress-hosts http-proxy
  content/zh/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: area/environments, translation/chinese, size/L, cherrypick/release-1.19

#13891 [release-1.19] [zh] sync wildcard-egress-hosts http-proxy
  content/zh/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: size/L, release-notes-none

#13890 Fix ambient release link
  content/en/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, size/XS, area/ambient, cherrypick/release-1.19

#13893 [release-1.19] Fix ambient release link
  content/en/docs/ops/ambient/getting-started/index.md
Labels: size/XS, release-notes-none

#13892 Update istio test ref, hardcode sha from Gateway API to non-release
  Makefile.core.mk
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
  scripts/get_gateway_api_version.sh
Labels: size/L

#13895 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13872 zh: docs/ops/integrations/spire/
  content/zh/docs/ops/integrations/spire/index.md
Labels: kind/docs, translation/chinese, size/XL, cherrypick/release-1.19

#13894 [zh] Sync #13890 into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.19

#13896 [release-1.19] zh: docs/ops/integrations/spire/
  content/zh/docs/ops/integrations/spire/index.md
Labels: size/XL, release-notes-none

#13897 [release-1.19] [zh] Sync #13890 into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: size/XS, release-notes-none

#13868 [release-1.17] Update the istio test reference to the 1.17.6 candidate
  bin/init.sh
  go.mod
  go.sum
Labels: size/L

#13883 Release notes for 1.17.6
  .spelling
  content/en/news/releases/1.17.x/announcing-1.17.6/index.md
Labels: kind/docs, size/S, cherrypick/release-1.19

#13900 [release-1.19] Release notes for 1.17.6
  .spelling
  content/en/news/releases/1.17.x/announcing-1.17.6/index.md
Labels: size/S, release-notes-none

#13208 Add gateway-api instructions to timeouts task
  content/en/docs/tasks/traffic-management/request-timeouts/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/test.sh
Labels: size/L, lifecycle/staleproof

#13849 Updated the canary upgrade page
  content/en/docs/setup/upgrade/canary/canary_upgrade_test.sh
  content/en/docs/setup/upgrade/canary/index.md
  content/en/docs/setup/upgrade/canary/snips.sh
Labels: kind/docs, size/M, ok-to-test

#13899 gateway-api: setup tips and warnings corrections
  content/en/boilerplates/gateway-api-experimental.md
  content/en/boilerplates/gateway-api-gamma-support.md
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/gtwapi_test-disable.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
Labels: size/L

#13901 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#13903 [zh] Sync #13849 into Chinese
  content/zh/docs/setup/upgrade/canary/index.md
Labels: kind/docs, translation/chinese, size/S

#13905 Fix indentations in canary upgrade
  content/en/docs/setup/upgrade/canary/index.md
Labels: kind/docs, size/S

#13834 Add a blog of network traffic analyzing for both Ambient and Sidecar
  content/en/blog/2023/traffic-for-ambient-and-sidecar/ambient-to-sidecar.png
  content/en/blog/2023/traffic-for-ambient-and-sidecar/index.md
  content/en/blog/2023/traffic-for-ambient-and-sidecar/sidecar-to-ambient.png
Labels: kind/docs, size/L, area/ambient, cherrypick/release-1.19

#13907 Add instructions to cleanup CRDs in getting started uninstall section
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
Labels: size/S

#13909 [zh] Sync 1.17.6 release notes into Chinese
  content/zh/news/releases/1.17.x/announcing-1.17.6/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.19

#13915 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/S, auto-merge, release-notes-none

#13914 [zh] Sync #13907 into Chinese
  content/zh/docs/setup/additional-setup/getting-started/index.md
Labels: kind/docs, translation/chinese, size/S

#13902 [zh] Sync #13899 into Chinese
  content/zh/boilerplates/gateway-api-experimental.md
  content/zh/boilerplates/gateway-api-gamma-support.md
  content/zh/docs/tasks/traffic-management/circuit-breaking/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: kind/docs, translation/chinese, size/L

#13904 [zh] Sync #13208 into Chinese
  content/zh/docs/tasks/traffic-management/request-timeouts/index.md
Labels: kind/docs, translation/chinese, size/L

#13919 [zh-cn] improve authz-custom authz-deny authz-tcp
  content/zh/docs/tasks/security/authorization/authz-custom/index.md
  content/zh/docs/tasks/security/authorization/authz-deny/index.md
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
Labels: kind/docs, translation/chinese

#13917 updating primary-remote on multi-net docs
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/test.sh
Labels: kind/docs, size/M

#13922 [release-1.19] updating primary-remote on multi-net docs
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/test.sh
Labels: size/M, release-notes-none

#13921 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#13912 Fixes for the ambient/sidecar traffic blog
  content/en/blog/2023/traffic-for-ambient-and-sidecar/index.md
Labels: kind/docs, size/S

#13913 [zh] Sync Ambient and Sidecar Traffic blog into Chinese
  content/zh/blog/2023/traffic-for-ambient-and-sidecar/ambient-to-sidecar.png
  content/zh/blog/2023/traffic-for-ambient-and-sidecar/index.md
  content/zh/blog/2023/traffic-for-ambient-and-sidecar/sidecar-to-ambient.png
Labels: kind/docs, translation/chinese, size/L

#13925 Fix doc test
  content/en/docs/reference/config/analysis/ist0104/index.md
Labels: kind/docs, area/user experience, size/M

#13927 [zh] Sync #13925 to remove from Chinese doc
  content/zh/docs/reference/config/analysis/ist0104/index.md
Labels: kind/docs, translation/chinese, size/M

#13918 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  data/analysis.yaml
Labels: size/M, auto-merge, release-notes-none

#13926 [zh] Sync #13917 into Chinese
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: kind/docs, translation/chinese, size/S

#13929 telemetry: change ALL_METRICS to REQUEST_COUNT
  content/en/docs/tasks/observability/metrics/telemetry-api/index.md
  content/en/docs/tasks/observability/metrics/telemetry-api/snips.sh
  content/zh/docs/tasks/observability/metrics/telemetry-api/index.md
Labels: area/extensions and telemetry, size/S, ok-to-test

#13935 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13930 [zh] improve integrations/spire
  content/zh/docs/ops/integrations/spire/index.md
Labels: kind/docs, translation/chinese, size/L

#13928 Replace mention of virtual service in dns proxying docs
  content/en/docs/ops/configuration/traffic-management/dns/index.md
Labels: kind/docs, size/XS, ok-to-test

#13936 [zh] Sync #13928 into Chinese
  content/zh/docs/ops/configuration/traffic-management/dns/index.md
Labels: kind/docs, translation/chinese, size/XS

#13932 [zh] Fix and improve format for reference doc in Chinese
  content/zh/docs/reference/config/config-status/index.md
  content/zh/docs/reference/config/proxy_extensions/wasm_telemetry/index.md
  content/zh/docs/reference/config/security/conditions/index.md
  content/zh/docs/reference/config/security/normalization/index.md
Labels: kind/docs, translation/chinese, size/L

#13939 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none

#13940 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#13943 initial eol announcement for 1.17
  content/en/news/support/announcing-1.17-eol/index.md
  data/compatibility/supportStatus.yml
Labels: kind/docs, size/S, cherrypick/release-1.19

#13944 [release-1.19] initial eol announcement for 1.17
  content/en/news/support/announcing-1.17-eol/index.md
  data/compatibility/supportStatus.yml
Labels: size/S, release-notes-none

#13931 [zh] Improve and fix format for example docs in Chinese
  content/zh/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
  content/zh/docs/examples/microservices-istio/setup-local-computer/index.md
  content/zh/docs/examples/microservices-istio/single/index.md
Labels: kind/docs, translation/chinese, size/L

#13946 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/S, auto-merge, release-notes-none

#13950 small corrections to istiocon china blog post
  content/en/blog/2023/istiocon-china/index.md
Labels: kind/docs, cherrypick/release-1.19

#13934 Update Hugo version to match tools image
  netlify.toml
Labels: size/XS

#13951 [release-1.19] small corrections to istiocon china blog post
  content/en/blog/2023/istiocon-china/index.md
Labels: size/XS, release-notes-none

#13948 [zh] Sync 1.17 eol announcement into Chinese
  content/zh/news/support/announcing-1.17-eol/index.md
Labels: kind/docs, translation/chinese, size/S
