Repository istio/istio.io, pull requests merged in 2023-11, with the labels that each got.

#14086 [zh] Localize /telemetry/monitoring-multicluster-prometheus/ images
  content/zh/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/external-production-prometheus.svg
  content/zh/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/in-mesh-production-prometheus.svg
Labels: kind/docs, translation/chinese, size/XXL

#14088 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14089 fix typo in the pilot-agent page
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: kind/docs, size/XS, ok-to-test

#14090 [release-1.19] fix typo in the pilot-agent page
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/XS, release-notes-none

#14093 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/XS, auto-merge, release-notes-none

#14095 Update application labeling guidance
  content/en/docs/ops/deployment/requirements/index.md
Labels: size/S

#14103 [zh] fix typo in `docs/setup` `docs/tasks`
  content/zh/docs/setup/platform-setup/k3d/index.md
  content/zh/docs/setup/platform-setup/minikube/index.md
  content/zh/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
  content/zh/docs/tasks/traffic-management/fault-injection/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/distribute/index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
Labels: translation/chinese, size/M

#14097 [zh] Sync #14095 into Chinese
  content/zh/docs/ops/deployment/requirements/index.md
Labels: translation/chinese, size/S

#14099 Fix patch version with known cve list
  content/en/docs/releases/supported-releases/index.md
Labels: kind/docs, cherrypick/release-1.19

#14106 [zh] Sync #14099 into Chinese
  content/zh/docs/releases/supported-releases/index.md
Labels: kind/docs, translation/chinese, size/XS

#14104 Updated IMESH logo into svg format
  static/logos/imesh.svg
Labels: area/user experience, size/XS, ok-to-test

#14110 Automator: update common-files@release-1.19 in istio/istio.io@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14116 Update Kiali Getting started link in the English documentation for is…
  content/en/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
Labels: size/XS, ok-to-test

#14115 updated link to appswitch
  content/en/blog/2018/delayering-istio/index.md
Labels: kind/docs, size/XS, ok-to-test

#13635 Ambient L4/ ZTunnel User's Guide Issue #13481
  .spelling
  content/en/docs/ops/ambient/usage/_index.md
  content/en/docs/ops/ambient/usage/install/index.md
  content/en/docs/ops/ambient/usage/waypoint/index.md
  content/en/docs/ops/ambient/usage/ztunnel/hbone-packet.png
  content/en/docs/ops/ambient/usage/ztunnel/index.md
  content/en/docs/ops/ambient/usage/ztunnel/ztunnel-architecture.png
  content/en/docs/ops/ambient/usage/ztunnel/ztunnel-datapath-1.png
  content/en/docs/ops/ambient/usage/ztunnel/ztunnel-hairpin.png
  content/en/docs/ops/ambient/usage/ztunnel/ztunnel-waypoint-datapath.png
Labels: kind/docs, size/XL, ok-to-test, area/ambient

#14105 [manual cherrypick] istio-security-004 content #13993
  content/en/news/releases/1.17.x/announcing-1.17.8/index.md
  content/en/news/releases/1.18.x/announcing-1.18.5/index.md
  content/en/news/releases/1.19.x/announcing-1.19.3/index.md
  content/en/news/security/istio-security-2023-004/index.md
Labels: kind/docs, size/M

#14052 Docs: update diagnostic-tools trust con
  content/en/docs/ops/diagnostic-tools/multicluster/index.md
Labels: kind/docs, size/XS, ok-to-test

#13745 Add EKS warning to Primary Remote instructions
  content/en/docs/setup/install/multicluster/primary-remote/index.md
Labels: area/security, area/environments, kind/docs, area/user experience, size/XS

#13284 Add missing deploy OPA in a separate pod tab
  content/en/blog/2021/better-external-authz/index.md
Labels: kind/docs, size/M, ok-to-test

#14118 Change PR template
  .github/pull_request_template.md
Labels: size/S

#14119 [zh] Sync #14116 to fix Kiali link into Chinese
  content/zh/docs/examples/microservices-istio/setup-kubernetes-cluster/index.md
Labels: kind/docs, translation/chinese, size/XS

#14120 [zh] Sync #14115 to update AppSwitch link into Chinese
  content/zh/blog/2018/delayering-istio/index.md
Labels: kind/docs, translation/chinese, size/XS

#14121 [zh] Sync link fix of Envoy #14111 into Chinese
  content/zh/blog/2017/0.1-using-network-policy/index.md
Labels: kind/docs, translation/chinese, size/XS

#14125 [zh] Sync #13745 into Chinese
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
Labels: kind/docs, translation/chinese, size/XS

#14124 [zh] Sync #13933 into Chinese
  content/zh/docs/ops/integrations/prometheus/index.md
Labels: kind/docs, translation/chinese, size/S

#14122 [zh] Sync 1.17.8, 1.18.5, 1.19.3 and related security update into Chinese
  content/zh/news/releases/1.17.x/announcing-1.17.8/index.md
  content/zh/news/releases/1.18.x/announcing-1.18.5/index.md
  content/zh/news/releases/1.19.x/announcing-1.19.3/index.md
  content/zh/news/security/istio-security-2023-004/index.md
Labels: kind/docs, translation/chinese, size/L

#14083 [zh] Update /about/service-mesh text and images
  content/zh/about/service-mesh/index.md
  content/zh/about/service-mesh/service-mesh.svg
Labels: kind/docs, translation/chinese, size/XXL

#14123 [zh] Sync #13284 into Chinese with missed translation
  content/zh/blog/2021/better-external-authz/index.md
Labels: kind/docs, translation/chinese, size/L

#14100 Auto sort .spelling with `make gen`
  .spelling
  Makefile.core.mk
Labels: area/test and release, size/L

#14091 Update istio test ref to 1.20.0-rc.0
  bin/init.sh
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/L

#14134 Glossary updates
  content/en/docs/releases/contribute/shortcodes/index.md
Labels: kind/docs, size/XS

#14135 [release-1.19] Glossary updates
  content/en/docs/releases/contribute/shortcodes/index.md
Labels: size/XS, release-notes-none

#14136 [zh] Sync #14134 into Chinese
  content/zh/docs/releases/contribute/shortcodes/index.md
Labels: kind/docs, translation/chinese, size/XS

#14131 [zh] Localize the install doc arch image into Chinese
  content/zh/docs/setup/install/multicluster/primary-remote/arch.svg
Labels: kind/docs, translation/chinese, size/XL

#14137 [zh] Localize arch image for install multi-primary into Chinese
  content/zh/docs/setup/install/multicluster/multi-primary/arch.svg
Labels: kind/docs, size/XL

#14138 [zh] Localize arch svg for multi-primary multi-network install doc into Chinese
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/arch.svg
Labels: translation/chinese, size/XXL

#14139 [zh-cn] sync egress-tls-origination
  content/zh/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
Labels: kind/docs, size/L

#14140 [zh] Localize two svg in /traffic-management/tls-configuration/
  content/zh/docs/ops/configuration/traffic-management/tls-configuration/gateway-connections.svg
  content/zh/docs/ops/configuration/traffic-management/tls-configuration/index.md
  content/zh/docs/ops/configuration/traffic-management/tls-configuration/sidecar-connections.svg
Labels: kind/docs, translation/chinese, size/XXL

#14142 [zh] Update /traffic-management/multicluster/ and its glossary
  content/zh/docs/ops/configuration/traffic-management/multicluster/index.md
  content/zh/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/zh/docs/reference/glossary/namespace-sameness.md
Labels: kind/docs, translation/chinese, size/L

#14141 Improve helm doc
  content/en/docs/setup/install/helm/index.md
Labels: area/environments, kind/docs, size/S

#14129 Release Notes for 1.19.4
  content/en/news/releases/1.19.x/announcing-1.19.4/index.md
Labels: size/M

#13074 Add Wehkamp as an Istio user
  data/companies.yml
  static/logos/wehkamp.svg
Labels: size/XS, ok-to-test

#13757 Added a warning in the ambient getting started guide
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/setup/platform-setup/kind/index.md
Labels: size/S, ok-to-test

#14144 Update version to 1.19.4
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.19.x/announcing-1.19.4/index.md
  data/args.yml
Labels: area/test and release, size/M

#14143 [zh] Localize arch image for primary remote multi-network install doc into Chinese
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/arch.svg
Labels: kind/docs, translation/chinese, size/XL

#13568 docs: update to use PROXY config
  content/en/docs/ops/common-problems/upgrade-issues/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
Labels: size/L

#14148 [zh] Sync network-topologies and authz-ingress
  content/zh/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
Labels: kind/docs, translation/chinese, size/L

#14149 Fix typo for ztunnel doc
  content/en/docs/ops/ambient/usage/ztunnel/index.md
Labels: size/XS

#14147 [zh] Sync /ops/ambient/getting-started/
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/L

#14101 Add release 1.20 releasenotes
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.20.x/_index.md
  content/en/news/releases/1.20.x/announcing-1.20/_index.md
  content/en/news/releases/1.20.x/announcing-1.20/change-notes/index.md
  content/en/news/releases/1.20.x/announcing-1.20/upgrade-notes/index.md
  data/compatibility/supportStatus.yml
Labels: area/test and release, kind/docs, size/L

#14133 [release-1.19] Update the reference docs for 1.19.4
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M

#14132 [release-1.19] Update test reference to 1.19.4
  go.mod
  go.sum
Labels: size/M

#14150 update 1.20 release notes
  .spelling
  content/en/news/releases/1.20.x/announcing-1.20/_index.md
Labels: size/XS

#14152 [release-1.20] update 1.20 release notes
  .spelling
  content/en/news/releases/1.20.x/announcing-1.20/_index.md
Labels: size/XS, release-notes-none

#14153 Fixup master branch post 1.20 branch cut
  .spelling
  scripts/create_version.sh
Labels: size/XS

#14156 Update test reference to 1.20.0
  go.mod
  go.sum
Labels: size/S

#14159 [zh] Sync 1.19.4 release note and 1.20 major release update into Chinese
  content/zh/news/releases/1.19.x/announcing-1.19.4/index.md
  content/zh/news/releases/1.19.x/announcing-1.19/_index.md
  content/zh/news/releases/1.20.x/_index.md
  content/zh/news/releases/1.20.x/announcing-1.20/_index.md
Labels: kind/docs, translation/chinese, size/L

#14163 Fix yaml indentation in ambient get started doc
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
Labels: size/M

#14107 Update CEL documentation to capture type checking errors.
  content/en/docs/tasks/observability/logs/telemetry-api/index.md
  content/en/docs/tasks/observability/logs/telemetry-api/snips.sh
Labels: area/extensions and telemetry, kind/docs, size/M

#14166 [release-1.20] Fix yaml indentation in ambient get started doc
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
Labels: size/M, release-notes-none

#14165 Fix make format-spelling difference on MacOS
  Makefile.core.mk
Labels: size/XS

#14158 Fixed Hugo's warning regarding index file
  content/zh/docs/ops/ambient/usage/_index.md
Labels: kind/docs, translation/chinese, size/XS

#14168 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/M, auto-merge, release-notes-none

#14161 [zh] Sync 1.20 upgrade note into Chinese
  content/zh/news/releases/1.20.x/announcing-1.20/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#14171 [zh] Sync #14107 into Chinese
  content/zh/docs/tasks/observability/logs/telemetry-api/index.md
Labels: kind/docs, translation/chinese, size/S

#14169 [zh] Sync #14157 update into Chinese with indent fix
  content/zh/docs/ops/ambient/getting-started/index.md
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
Labels: kind/docs, translation/chinese, size/L

#14167 [release-1.20] Fix make format-spelling difference on MacOS
  Makefile.core.mk
Labels: size/XS, release-notes-none

#14172 Fix typo for istioctl command pre-check to precheck
  content/en/news/releases/1.20.x/announcing-1.20/change-notes/index.md
  content/zh/news/releases/1.20.x/announcing-1.20/change-notes/index.md
Labels: kind/docs, size/XS

#14174 [zh] Fix typo from istoictl to istioctl
  content/zh/docs/setup/upgrade/in-place/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.20

#14175 [release-1.20] [zh] Fix typo from istoictl to istioctl
  content/zh/docs/setup/upgrade/in-place/index.md
Labels: size/XS, release-notes-none

#14178 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14098 update hugo to 0.120.4
  netlify.toml
Labels: size/XS

#14181 [zh] Sync /ops/common-problems/upgrade-issues/
  content/zh/docs/ops/common-problems/upgrade-issues/index.md
Labels: kind/docs, translation/chinese, size/M

#14179 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
Labels: size/M, auto-merge, release-notes-none

#14180 Remove left sidebar buttons from preliminary pages
  layouts/_default/baseof.html
  src/icons/pencil.svg
  src/icons/switch-lang.svg
  src/sass/misc/_floaters.scss
Labels: kind/docs, size/M, ok-to-test

#14183 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/L, auto-merge, release-notes-none

#14186 Automator: update common-files@release-1.20 in istio/istio.io@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14164 Blog : Istio at KubeCon NA 2023
  .spelling
  content/en/blog/2023/istio-at-kubecon-na/chop-wood-carry-water.jpg
  content/en/blog/2023/istio-at-kubecon-na/cncf-ambassadors.jpg
  content/en/blog/2023/istio-at-kubecon-na/contrib-fest.jpg
  content/en/blog/2023/istio-at-kubecon-na/ica.jpg
  content/en/blog/2023/istio-at-kubecon-na/index.md
  content/en/blog/2023/istio-at-kubecon-na/istio-booth-1.jpg
  content/en/blog/2023/istio-at-kubecon-na/istio-booth-2.jpg
  content/en/blog/2023/istio-at-kubecon-na/istio-day-paris.jpg
  content/en/blog/2023/istio-at-kubecon-na/istio-t-shirts.jpg
  content/en/blog/2023/istio-at-kubecon-na/istioday-session-1.jpg
  content/en/blog/2023/istio-at-kubecon-na/istioday-session-2.jpg
  content/en/blog/2023/istio-at-kubecon-na/maintainer-track.jpg
  content/en/blog/2023/istio-at-kubecon-na/servicemesh-battle-scars-panel.jpg
  content/en/blog/2023/istio-at-kubecon-na/top-contributors-1.jpg
  content/en/blog/2023/istio-at-kubecon-na/welcome.jpg
Labels: size/L, cherrypick/release-1.20

#14187 [release-1.20] Blog : Istio at KubeCon NA 2023
  .spelling
  content/en/blog/2023/istio-at-kubecon-na/chop-wood-carry-water.jpg
  content/en/blog/2023/istio-at-kubecon-na/cncf-ambassadors.jpg
  content/en/blog/2023/istio-at-kubecon-na/contrib-fest.jpg
  content/en/blog/2023/istio-at-kubecon-na/ica.jpg
  content/en/blog/2023/istio-at-kubecon-na/index.md
  content/en/blog/2023/istio-at-kubecon-na/istio-booth-1.jpg
  content/en/blog/2023/istio-at-kubecon-na/istio-booth-2.jpg
  content/en/blog/2023/istio-at-kubecon-na/istio-day-paris.jpg
  content/en/blog/2023/istio-at-kubecon-na/istio-t-shirts.jpg
  content/en/blog/2023/istio-at-kubecon-na/istioday-session-1.jpg
  content/en/blog/2023/istio-at-kubecon-na/istioday-session-2.jpg
  content/en/blog/2023/istio-at-kubecon-na/maintainer-track.jpg
  content/en/blog/2023/istio-at-kubecon-na/servicemesh-battle-scars-panel.jpg
  content/en/blog/2023/istio-at-kubecon-na/top-contributors-1.jpg
  content/en/blog/2023/istio-at-kubecon-na/welcome.jpg
Labels: size/L, release-notes-none

#14190 [zh]Update Zipkin install link
  content/zh/docs/tasks/observability/distributed-tracing/zipkin/index.md
Labels: translation/chinese, size/XS, ok-to-test

#14170 Improve some text in /ambient/usage/ztunnel/
  content/en/docs/ops/ambient/usage/ztunnel/index.md
Labels: kind/docs, size/M, cherrypick/release-1.20

#13772 Updated envoy website URLs to new domain
  content/en/blog/2017/0.1-auth/index.md
  content/en/blog/2017/0.1-using-network-policy/index.md
  content/en/news/releases/0.x/announcing-0.1/index.md
  content/zh/blog/2017/0.1-auth/index.md
  content/zh/blog/2017/0.1-using-network-policy/index.md
  content/zh/news/releases/0.x/announcing-0.1/index.md
Labels: kind/docs, size/S, ok-to-test

#14191 [release-1.20] Improve some text in /ambient/usage/ztunnel/
  content/en/docs/ops/ambient/usage/ztunnel/index.md
Labels: size/M, release-notes-none

#14189 [zh] Sync KubeCon NA blog into Chinese
  content/zh/blog/2023/istio-at-kubecon-na/chop-wood-carry-water.jpg
  content/zh/blog/2023/istio-at-kubecon-na/cncf-ambassadors.jpg
  content/zh/blog/2023/istio-at-kubecon-na/contrib-fest.jpg
  content/zh/blog/2023/istio-at-kubecon-na/ica.jpg
  content/zh/blog/2023/istio-at-kubecon-na/index.md
  content/zh/blog/2023/istio-at-kubecon-na/istio-booth-1.jpg
  content/zh/blog/2023/istio-at-kubecon-na/istio-booth-2.jpg
  content/zh/blog/2023/istio-at-kubecon-na/istio-day-paris.jpg
  content/zh/blog/2023/istio-at-kubecon-na/istio-t-shirts.jpg
  content/zh/blog/2023/istio-at-kubecon-na/istioday-session-1.jpg
  content/zh/blog/2023/istio-at-kubecon-na/istioday-session-2.jpg
  content/zh/blog/2023/istio-at-kubecon-na/maintainer-track.jpg
  content/zh/blog/2023/istio-at-kubecon-na/servicemesh-battle-scars-panel.jpg
  content/zh/blog/2023/istio-at-kubecon-na/top-contributors-1.jpg
  content/zh/blog/2023/istio-at-kubecon-na/welcome.jpg
Labels: kind/docs, translation/chinese, size/L

#14192 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/S, auto-merge, release-notes-none

#14194 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb-native.yaml
  common/scripts/metallb.yaml
Labels: size/XXL, auto-merge, release-notes-none

#14195 [release-1.20] add dual-stack installation page
  content/en/docs/setup/additional-setup/dual-stack/index.md
Labels: size/L, release-notes-none

#14197 [release-1.20] Small update to the dual-stack documentation
  content/en/docs/setup/additional-setup/dual-stack/index.md
Labels: size/XS, release-notes-none

#14198 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#14199 [zh] Sync dual-stack doc into Chinese
  content/zh/docs/setup/additional-setup/dual-stack/index.md
Labels: kind/docs, translation/chinese, size/L

#14201 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/config/security/jwt/index.html
Labels: size/M, auto-merge, release-notes-none

#14202 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14182 1.18 EoL announcement
  content/en/news/support/announcing-1.18-eol/index.md
Labels: kind/docs, size/S, cherrypick/release-1.20

#14203 [release-1.20] 1.18 EoL announcement
  content/en/news/support/announcing-1.18-eol/index.md
Labels: size/S, release-notes-none

#14207 [zh] Sync 1.18 EOL into Chinese
  content/zh/news/support/announcing-1.18-eol/index.md
Labels: kind/docs, translation/chinese, size/S

#14205 Add Linux Foundation trademark link to site footer
  i18n/en.toml
  i18n/pt-br.toml
  i18n/zh.toml
  layouts/partials/footer.html
Labels: kind/docs, size/S, ok-to-test

#14209 [release-1.20] Add Linux Foundation trademark link to site footer
  i18n/en.toml
  i18n/pt-br.toml
  i18n/zh.toml
  layouts/partials/footer.html
Labels: size/S, release-notes-none

#14188 Blog post for egress SNI routing.
  content/en/blog/2023/egress-sni/egress-sni-flow.png
  content/en/blog/2023/egress-sni/index.md
Labels: size/L, ok-to-test, cherrypick/release-1.20

#14212 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none
