Repository istio/istio.io, pull requests merged in 2023-07, with the labels that each got.

#13493 [zh] sync /ops/common-problems/upgrade-issues/
  content/zh/docs/ops/common-problems/upgrade-issues/index.md
Labels: kind/docs, translation/chinese, size/L

#13455 [zh] update /ops/configuration/mesh/app-health-check/index.md
  content/zh/docs/ops/configuration/mesh/app-health-check/index.md
Labels: kind/docs, translation/chinese, size/M

#13498 Corrected some translation content in the document
  content/zh/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#13488 [zh] ops/best-practices/deployment/index.md
  content/zh/docs/ops/best-practices/deployment/index.md
Labels: translation/chinese, size/S

#13496 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#13438 [zh] sync /news/support/announcing-1.16-eol/
  content/zh/news/support/announcing-1.16-eol/index.md
Labels: translation/chinese, size/S, cherrypick/release-1.18

#13499 update Chinese documentation of the traffic-management section
  content/zh/docs/concepts/traffic-management/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#13502 [release-1.18] [zh] sync /news/support/announcing-1.16-eol/
  content/zh/news/support/announcing-1.16-eol/index.md
Labels: size/S, release-notes-none

#13503 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, auto-merge, release-notes-none

#13500 [zh] Sync Better External Authorization blog into Chinese
  content/zh/blog/2021/better-external-authz/external_authz.svg
  content/zh/blog/2021/better-external-authz/index.md
Labels: kind/docs, translation/chinese, size/XL

#13466 [zh] diagnostic-tools-cni: fixed some string that not translated
  content/zh/docs/ops/diagnostic-tools/cni/index.md
Labels: kind/docs, translation/chinese, size/S

#13506 [zh] sync files in boilerplates and glossary
  content/zh/boilerplates/before-you-begin-egress.md
  content/zh/boilerplates/cve-2020-007-configmap.md
  content/zh/boilerplates/experimental.md
  content/zh/boilerplates/external-loadbalancer-support.md
  content/zh/boilerplates/gateway-api-experimental.md
  content/zh/boilerplates/gateway-api-gamma-support.md
  content/zh/boilerplates/gateway-api-install-crds.md
  content/zh/boilerplates/revision-tags-default-intro.md
  content/zh/boilerplates/revision-tags-middle.md
  content/zh/boilerplates/revision-tags-preamble.md
  content/zh/boilerplates/test-1.md
  content/zh/boilerplates/trace-generation.md
  content/zh/docs/reference/glossary/adapters.md
  content/zh/docs/reference/glossary/annotation.md
  content/zh/docs/reference/glossary/attribute.md
  content/zh/docs/reference/glossary/data-plane.md
  content/zh/docs/reference/glossary/dataplane-mode.md
  content/zh/docs/reference/glossary/destination.md
  content/zh/docs/reference/glossary/external-control-plane.md
  content/zh/docs/reference/glossary/identity.md
  content/zh/docs/reference/glossary/injection.md
  content/zh/docs/reference/glossary/multi-mesh.md
  content/zh/docs/reference/glossary/namespace-sameness.md
  content/zh/docs/reference/glossary/network.md
  content/zh/docs/reference/glossary/operator.md
  content/zh/docs/reference/glossary/proxyless.md
  content/zh/docs/reference/glossary/service-endpoint.md
  content/zh/docs/reference/glossary/service-name.md
  content/zh/docs/reference/glossary/service-operator.md
  content/zh/docs/reference/glossary/service-registry.md
  content/zh/docs/reference/glossary/sidecar.md
  content/zh/docs/reference/glossary/source.md
  content/zh/docs/reference/glossary/spiffe.md
  content/zh/docs/reference/glossary/tls-origination.md
  content/zh/docs/reference/glossary/workload-instance-principal.md
  content/zh/docs/reference/glossary/workload-instance.md
  content/zh/docs/reference/glossary/workload.md
Labels: kind/docs, translation/chinese, size/L

#13509 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13512 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#13511 Fix yaml file format and changed TSL to TLS
  content/zh/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#13513 Tweak long lines in istioctl and istioctl-analyze
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
Labels: kind/docs, size/L

#13508 Update netlify.toml to match tools versions in the build-tools image.
  netlify.toml
Labels: size/XS

#13515 Update supported versions for master
  data/compatibility/supportStatus.yml
Labels: size/XS

#13517 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13518 Automator: update common-files@release-1.18 in istio/istio.io@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13520 [zh] sync faq/(distributed-tracing/metrics-and-logs/traffic-management)
  content/zh/about/faq/distributed-tracing/index.md
  content/zh/about/faq/metrics-and-logs/index.md
  content/zh/about/faq/traffic-management/index.md
Labels: kind/docs, translation/chinese, size/XS

#13521 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13522 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13523 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13524 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
Labels: size/M, auto-merge, release-notes-none

#13525 Tweak line wrappings in integrations
  content/en/docs/ops/integrations/certmanager/index.md
  content/en/docs/ops/integrations/grafana/index.md
  content/en/docs/ops/integrations/jaeger/index.md
  content/en/docs/ops/integrations/kiali/index.md
  content/en/docs/ops/integrations/loadbalancers/index.md
  content/en/docs/ops/integrations/prometheus/index.md
Labels: kind/docs, size/L

#13527 [zh] fix localization of metrics in faq
  content/zh/about/faq/metrics-and-logs/index.md
Labels: kind/docs, translation/chinese, size/XS

#13504 [zh sync] delete docs/reference/config/security/constraints-and-properties/index.md
  content/zh/docs/reference/config/security/constraints-and-properties/index.md
Labels: translation/chinese, size/M

#13531 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13532 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13533 Automator: update common-files@release-1.18 in istio/istio.io@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13534 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13535 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13536 update hugo to 0.115.2
  netlify.toml
Labels: area/test and release, size/XS

#13538 fix typo in security-issues
  content/zh/docs/ops/common-problems/injection/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#13540 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13529 [zh] Sync Announcing the alpha availability of WebAssembly Plugins blog into Chinese
  content/zh/blog/2021/wasm-api-alpha/index.md
  content/zh/blog/2021/wasm-api-alpha/istio-agent-architecture.svg
Labels: kind/docs, translation/chinese, size/XXL

#13541 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#13542 the Dual Stack feature flag has been uniformed as ISTIO_DUAL_STACK
  content/en/blog/2023/experimental-dual-stack/index.md
  content/zh/blog/2023/experimental-dual-stack/index.md
Labels: size/XS

#13545 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13544 add blog post for 11am ET on Wed
  .spelling
  content/en/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/M, cherrypick/master

#13550 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13549 Fix operator/test.sh for downloadIstio TARGET_OS change
  content/en/docs/setup/install/operator/test.sh
Labels: size/XS, cherrypick/release-1.18

#13551 [release-1.18] Fix operator/test.sh for downloadIstio TARGET_OS change
  content/en/docs/setup/install/operator/test.sh
Labels: size/XS, release-notes-none

#13539 Update istio test reference
  go.mod
  go.sum
Labels: size/M

#13552 Add vmware to graduation blog
  content/en/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/XS

#13553 [release-1.18] Add vmware to graduation blog
  content/en/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/XS, release-notes-none

#13537 update makefile versions to match docker/build-tools/Dockerfile
  Makefile.core.mk
Labels: area/test and release, size/S

#13554 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/labels/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/labels/index.html
Labels: size/XXL, auto-merge, release-notes-none

#13555 add DaoCloud to graduation blog
  content/en/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/XS

#13556 [release-1.18] add DaoCloud to graduation blog
  content/en/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/XS, release-notes-none

#13546 [zh] sync blog: istio-graduates-within-cncf
  content/zh/blog/2023/istio-graduates-within-cncf/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.18

#13557 [release-1.18] [zh] sync blog: istio-graduates-within-cncf
  content/zh/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/L, release-notes-none

#13558 Automator: update common-files@release-1.18 in istio/istio.io@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13563 Release notes for 1.16.6, 1.17.4, 1.18.1
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.16.x/announcing-1.16.6/index.md
  content/en/news/releases/1.17.x/announcing-1.17.4/releaseNotes.md
  content/en/news/releases/1.18.x/announcing-1.18.1/releaseNotes.md
  content/en/news/security/istio-security-2023-002/index.md
Labels: kind/docs, size/L

#13559 [release-1.18] Run istio.io tests against current 1.18 branch commit
  go.mod
  go.sum
Labels: size/M

#13570 JWT routing task fixes
  content/en/docs/tasks/security/authentication/jwt-route/index.md
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/test.sh
Labels: size/S

#13560 [release-1.17] Update istio.io tests for 1.17
  go.mod
  go.sum
Labels: size/S

#13561 [release-1.16] Update istio.io tests for 1.16
  go.mod
  go.sum
Labels: size/S

#13571 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13569 [release-1.18] manual cherry pick of release notes 1.16.6, 1.17.4, 1.18.1
  .spelling
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/releases/supported-releases/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.16.x/announcing-1.16.6/index.md
  content/en/news/releases/1.17.x/announcing-1.17.4/releaseNotes.md
  content/en/news/releases/1.18.x/announcing-1.18.1/releaseNotes.md
  content/en/news/security/istio-security-2023-002/index.md
  data/args.yml
Labels: kind/docs

#13329 1.18.1 - Document CRL usage (#13275)
  content/en/boilerplates/crl-tip.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: size/S, 1.18.1

#13565 Updates to graduation blog & home page
  .spelling
  content/en/_index.html
  content/en/blog/2023/istio-graduates-within-cncf/index.md
  content/en/events/banners/istio-graduates-within-cncf.md
  data/companies.yml
Labels: size/S, cherrypick/release-1.18

#13562 [release-1.18] Generate new reference docs for 1.18.1
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/M

#13572 [release-1.18] Updates to graduation blog & home page
  .spelling
  content/en/_index.html
  content/en/blog/2023/istio-graduates-within-cncf/index.md
  content/en/events/banners/istio-graduates-within-cncf.md
  data/companies.yml
Labels: size/S, release-notes-none

#13567 [zh] sync /tasks/security/authentication/claim-to-header/
  content/zh/docs/tasks/security/authentication/claim-to-header/index.md
Labels: kind/docs, translation/chinese, size/XS

#13577 Rename release notes
  content/en/news/releases/1.17.x/announcing-1.17.4/index.md
  content/en/news/releases/1.18.x/announcing-1.18.1/index.md
Labels: size/XS, cherrypick/release-1.18

#13579 [release-1.18] Rename release notes
  content/en/news/releases/1.17.x/announcing-1.17.4/index.md
  content/en/news/releases/1.18.x/announcing-1.18.1/index.md
Labels: size/XS, release-notes-none

#13578 [zh] Sync JWT routing fixes in Chinese docs
  content/zh/docs/tasks/security/authentication/jwt-route/index.md
Labels: kind/docs, translation/chinese, size/XS

#13583 [zh] sync a svg in blog of wasm-api
  content/zh/blog/2021/wasm-api-alpha/istio-agent-architecture.svg
Labels: kind/docs, translation/chinese, size/XXL

#13580 [zh] Sync 1.18.1, 1.17.4 and 1.16.6 release note and 2023-002 security update into Chinese
  content/zh/news/releases/1.16.x/announcing-1.16.6/index.md
  content/zh/news/releases/1.17.x/announcing-1.17.4/index.md
  content/zh/news/releases/1.18.x/announcing-1.18.1/index.md
  content/zh/news/security/istio-security-2023-002/index.md
Labels: kind/docs, translation/chinese, size/L

#13581 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#13586 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#13585 move Telemetry API to alpha
  content/en/docs/tasks/observability/telemetry/index.md
Labels: area/extensions and telemetry, size/XS

#13587 [zh] Sync move Telemetry API to alpha in Chinese doc
  content/zh/docs/tasks/observability/telemetry/index.md
Labels: kind/docs, size/XS

#13584 [zh] Sync gRPC Proxyless Service Mesh blog into Chinese
  content/zh/blog/2021/proxyless-grpc/architecture.svg
  content/zh/blog/2021/proxyless-grpc/index.md
  content/zh/blog/2021/proxyless-grpc/latencies_p50.svg
  content/zh/blog/2021/proxyless-grpc/latencies_p99.svg
Labels: kind/docs, translation/chinese, size/XXL

#13591 Bump gateway api version used in examples
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: area/networking, size/S

#13582 update hugo to 0.115.3
  netlify.toml
Labels: area/test and release, size/XS

#13592 update intel's post link address
  content/en/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/XS, cherrypick/release-1.18

#13596 [release-1.18] update intel's post link address
  content/en/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/XS, release-notes-none

#13595 Re-enable processing of gateway-api version in `make gen`
  Makefile.core.mk
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
Labels: size/S

#13597 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#13599 [zh-cn] improve rate-limit telemetry
  content/zh/docs/tasks/observability/telemetry/index.md
  content/zh/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: kind/docs, translation/chinese

#13598 [release-1.18] move Telemetry API to alpha
  content/en/docs/tasks/observability/telemetry/index.md
Labels: size/XS, release-notes-none

#13589 Move remote secret command out of experimental
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/multicluster/multi-primary/index.md
  content/en/docs/setup/install/multicluster/multi-primary/snips.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
Labels: area/environments, area/user experience, size/M

#13600 [zh] sync /releases/supported-releases
  content/zh/docs/releases/supported-releases/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.18

#13602 [release-1.18] [zh] sync /releases/supported-releases
  content/zh/docs/releases/supported-releases/index.md
Labels: size/XS, release-notes-none

#13601 [zh] Sync Move remote secret command out of experimental for Chinese docs
  content/zh/docs/setup/install/external-controlplane/index.md
  content/zh/docs/setup/install/multicluster/multi-primary/index.md
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: kind/docs, translation/chinese, size/S

#13603 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XL, auto-merge, release-notes-none

#13606 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13607 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#13605 [zh] Change a term about namespace
  content/zh/docs/setup/install/virtual-machine/index.md
  content/zh/docs/tasks/observability/logs/access-log/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#13611 [zh] Correction the translation typo of the "example"
  content/zh/docs/tasks/security/cert-management/plugin-ca-cert/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#13610 update hugo to 0.115.4
  netlify.toml
Labels: area/test and release, size/XS

#13614 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#13612 Update istio test reference
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
  go.mod
  go.sum
Labels: size/L

#13615 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13613 [zh] sync diagnostic-tools/multicluster
  content/zh/docs/ops/diagnostic-tools/multicluster/index.md
Labels: kind/docs, translation/chinese, size/L

#13617 [zh] Sync #13612 updates into Chinese version
  content/zh/docs/ops/ambient/getting-started/index.md
  content/zh/docs/ops/configuration/traffic-management/dns-proxy/index.md
Labels: kind/docs, translation/chinese, size/XS

#13619 Release notes
  .spelling
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/releases/supported-releases/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.16.x/announcing-1.16.7/index.md
  content/en/news/releases/1.17.x/announcing-1.17.5/index.md
  content/en/news/releases/1.18.x/announcing-1.18.2/index.md
  content/en/news/security/istio-security-2023-003/index.md
  content/en/news/support/announcing-1.16-eol-final/index.md
  data/args.yml
Labels: size/L, cherrypick/master

#13622 [release-1.18] Fix dns-proxy test
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
Labels: size/XS

#13623 Manual cherry-pick of #13619 (Various release notes)
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.16.x/announcing-1.16.7/index.md
  content/en/news/releases/1.17.x/announcing-1.17.5/index.md
  content/en/news/releases/1.18.x/announcing-1.18.2/index.md
  content/en/news/security/istio-security-2023-003/index.md
  content/en/news/support/announcing-1.16-eol-final/index.md
Labels: size/L

#13626 change support status of 1.16
  data/compatibility/supportStatus.yml
Labels: kind/docs, size/XS, cherrypick/release-1.18

#13627 [release-1.18] change support status of 1.16
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#13628 fix description of 1.17.5 announcement
  content/en/news/releases/1.17.x/announcing-1.17.5/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.18

#13629 [release-1.18] fix description of 1.17.5 announcement
  content/en/news/releases/1.17.x/announcing-1.17.5/index.md
Labels: size/XS, release-notes-none

#13633 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/XS, auto-merge, release-notes-none

#13634 [zh] Sync 1.18.2, 1.17.5, 1.16.7 release notes with support release, 1.16-eol and security-2023-003 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.16.x/announcing-1.16.7/index.md
  content/zh/news/releases/1.17.x/announcing-1.17.5/index.md
  content/zh/news/releases/1.18.x/announcing-1.18.2/index.md
  content/zh/news/security/istio-security-2023-003/index.md
  content/zh/news/support/announcing-1.16-eol-final/index.md
Labels: kind/docs, translation/chinese, size/L

#13618 [zh] improve customize-installation-helm sidecar-injection
  content/zh/docs/setup/additional-setup/customize-installation-helm/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: kind/docs, translation/chinese, size/L

#13616 Fix Improper Spacing When Displaying Multiple Banners
  src/sass/misc/_banners.scss
  src/ts/events.ts
Labels: kind/docs, size/M, ok-to-test, cherrypick/release-1.18

#13637 Fix handling of @@ link notation
  content/en/docs/setup/platform-setup/k3d/index.md
  layouts/partials/code_block.html
  src/ts/codeBlocks.ts
Labels: kind/docs, size/XS, cherrypick/release-1.18

#13640 add missed / to @@ link handling regex
  layouts/partials/code_block.html
  src/ts/codeBlocks.ts
Labels: kind/docs, size/XS

#13642 Manual Cherry Pick - Fix @@ links
  content/en/docs/setup/platform-setup/k3d/index.md
  layouts/partials/code_block.html
  src/ts/codeBlocks.ts
Labels: kind/docs, size/XS

#13643 update links for cves
  content/en/news/releases/1.16.x/announcing-1.16.7/index.md
  content/en/news/releases/1.17.x/announcing-1.17.5/index.md
  content/en/news/releases/1.18.x/announcing-1.18.2/index.md
  content/en/news/security/istio-security-2023-003/index.md
Labels: size/M, cherrypick/release-1.18

#13644 [release-1.18] update links for cves
  content/en/news/releases/1.16.x/announcing-1.16.7/index.md
  content/en/news/releases/1.17.x/announcing-1.17.5/index.md
  content/en/news/releases/1.18.x/announcing-1.18.2/index.md
  content/en/news/security/istio-security-2023-003/index.md
Labels: size/M, release-notes-none

#13625 Add gateway-api instructions to authn policy task
  content/en/docs/tasks/security/authentication/authn-policy/gtwapi_test.sh
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/test.sh
Labels: size/L

#13645 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/L, auto-merge, release-notes-none

#13641 [zh]improve gateway gateway-api observability/gateways
  content/zh/docs/setup/additional-setup/gateway/index.md
  content/zh/docs/tasks/observability/gateways/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: kind/docs, translation/chinese, size/L

#13649 Add CFP reminder banner for IstioCon Virtual and Istio Day NA
  .spelling
  content/en/events/banners/istioday-cfp-2023.md
Labels: size/S

#13650 [release-1.18] Add CFP reminder banner for IstioCon Virtual and Istio Day NA
  .spelling
  content/en/events/banners/istioday-cfp-2023.md
Labels: size/S, release-notes-none

#13653 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#13651 [zh] sync /setup/platform-setup/_index
  content/zh/docs/setup/platform-setup/_index.md
Labels: kind/docs, translation/chinese

#13646 [zh] sync tasks/security/authentication/authn-policy/
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, translation/chinese, size/L

#13647 [zh] Sync CVE links #13643 to Chinese version
  content/zh/news/releases/1.16.x/announcing-1.16.7/index.md
  content/zh/news/releases/1.17.x/announcing-1.17.5/index.md
  content/zh/news/releases/1.18.x/announcing-1.18.2/index.md
  content/zh/news/security/istio-security-2023-003/index.md
Labels: kind/docs, translation/chinese, size/M

#13654 [zh] Sync #13637 into Chinese version doc
  content/zh/docs/setup/platform-setup/k3d/index.md
Labels: kind/docs, translation/chinese, size/XS

#13656 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/S, auto-merge, release-notes-none

#13657 Updated branding for Outshift by Cisco
  data/companies.yml
  static/logos/cisco.svg
  static/logos/outshift.svg
Labels: kind/docs, size/M, ok-to-test, cherrypick/release-1.18

#13658 [release-1.18] Updated branding for Outshift by Cisco
  data/companies.yml
  static/logos/cisco.svg
  static/logos/outshift.svg
Labels: size/M, release-notes-none

#13652 Resize f5 Logo to Be Reasonably Sized on Page
  static/logos/f5.svg
Labels: kind/docs, size/S, cherrypick/release-1.18

#13660 [release-1.18] Resize f5 Logo to Be Reasonably Sized on Page
  static/logos/f5.svg
Labels: size/S, release-notes-none

#13662 [zh] sync istioday-cfp-2023.md
  content/zh/events/banners/istioday-cfp-2023.md
Labels: kind/docs, translation/chinese, size/S

#13665 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#13663 [zh] sync /ops/best-practices/security/
  content/zh/docs/ops/best-practices/security/index.md
Labels: kind/docs, translation/chinese, size/L

#13667 Fix a typo in platform setup
  content/en/docs/setup/platform-setup/k3d/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.18

#13661 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/L, release-notes-none

#13669 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
