Repository istio/istio.io, pull requests merged in 2023-03, with the labels that each got.

#12810 [zh] sync /ops/best-practices/security/index.md
  content/zh/docs/ops/best-practices/security/index.md
Labels: kind/docs, translation/chinese, size/L, ok-to-test, cherrypick/release-1.17

#12817 [release-1.17] [zh] sync /ops/best-practices/security/index.md
  content/zh/docs/ops/best-practices/security/index.md
Labels: size/L, release-notes-none

#12818 Gloss refs and other small improvemetents in ambient docs
  content/en/docs/ops/ambient/architecture/index.md
  content/en/docs/ops/ambient/getting-started/index.md
Labels: size/M

#12820 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12825 [release-1.17] Update reference docs formatting.
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/L

#12824 [zh]sync and improve primary-remote multi-primary_multi-network primary-remote_multi-network
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: kind/docs, translation/chinese, size/L

#12826 Automator: update common-files@master in istio/istio.io@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#12804 accesslog: example of Telemetry API with cluster_name
  content/en/docs/tasks/observability/logs/telemetry-api/index.md
Labels: area/extensions and telemetry, kind/docs, size/S, ok-to-test

#12680 Update Istio/SPIRE demo to use SPIRE Controller Manager
  .spelling
  content/en/docs/ops/integrations/spire/automatic_registration_test.sh
  content/en/docs/ops/integrations/spire/index.md
  content/en/docs/ops/integrations/spire/snips.sh
Labels: area/security, kind/docs, size/XL

#12709 Fix minor nits on the security tasks page Plugin CA Certificate
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/index.md
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/test.sh
Labels: size/M, ok-to-test

#12831 Update link to point to alpha0
  content/en/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, size/XS

#12812 Update the get started blog to refer to latest doc
  content/en/blog/2022/get-started-ambient/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.17

#12836 [release-1.17] Update the get started blog to refer to latest doc
  content/en/blog/2022/get-started-ambient/index.md
Labels: size/XS, release-notes-none

#12837 [release-1.17] Introducing ztunnel blog
  .spelling
  content/en/blog/2023/rust-based-ztunnel/index.md
  content/en/blog/2023/rust-based-ztunnel/kiali-ambient.png
  content/en/blog/2023/rust-based-ztunnel/ztunnel-architecture.png
Labels: size/L, release-notes-none

#12838 [release-1.17] correct link in ztunnel blog.
  content/en/blog/2023/rust-based-ztunnel/index.md
Labels: size/XS, release-notes-none

#12839 update link to point to the get started guide
  content/en/blog/2023/rust-based-ztunnel/index.md
Labels: kind/docs, size/XS, cherrypick/master

#12840 [master] update link to point to the get started guide
  content/en/blog/2023/rust-based-ztunnel/index.md
Labels: size/XS, release-notes-none

#12841 [zh] improve traffic-management/multicluster
  content/zh/docs/ops/configuration/traffic-management/multicluster/index.md
Labels: kind/docs, translation/chinese, size/M

#12832 Cleanup some old documention left over in Egress task
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: size/XS

#12847 Update istio reference to latest from main branch
  go.mod
  go.sum
  pkg/test/istioio/snapshot.go
Labels: size/M

#12765 wasm: use wasm API for attributegen
  content/en/blog/2021/wasm-progress/index.md
  content/en/docs/reference/config/proxy_extensions/attributegen/index.html
  content/en/docs/reference/config/proxy_extensions/stats/index.html
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
  content/en/docs/tasks/observability/metrics/tcp-metrics/index.md
Labels: size/XL

#12819 TCP Traffic page edit
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
  content/en/docs/tasks/security/authorization/authz-tcp/snips.sh
Labels: kind/docs, area/user experience, size/M, ok-to-test

#12827 add doc tests for ambient getting started guide
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/ops/ambient/getting-started/test.sh
Labels: size/L

#12849 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
Labels: size/L, auto-merge, release-notes-none

#12846 update hugo to 0.111.2
  netlify.toml
Labels: size/XS

#12850 add missing tests for ambient doc
  content/en/docs/ops/ambient/getting-started/test.sh
Labels: size/XS

#12851 Remove 'Experimental features..' text from feature-stages page
  content/en/docs/releases/feature-stages/index.md
Labels: kind/docs, size/XS, ok-to-test, cherrypick/release-1.17

#12852 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
Labels: size/M, auto-merge, release-notes-none

#12855 [release-1.17] accesslog: example of Telemetry API with cluster_name
  content/en/docs/tasks/observability/logs/telemetry-api/index.md
Labels: size/S, release-notes-none

#12853 [release-1.17] Remove 'Experimental features..' text from feature-stages page
  content/en/docs/releases/feature-stages/index.md
Labels: size/XS, release-notes-none

#12856 Small fixes to custom CA doc
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: size/S

#12858 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12861 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12860 Automator: update common-files@release-1.15 in istio/istio.io@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12862 Automator: update istio.io@ reference docs
  data/features.yaml
Labels: size/XS, auto-merge, release-notes-none

#12864 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12253 dual-stack blog
  .spelling
  content/en/blog/2023/experimental-dual-stack/index.md
Labels: kind/docs, size/L

#12868 [release-1.17] dual-stack blog
  .spelling
  content/en/blog/2023/experimental-dual-stack/index.md
Labels: size/L, release-notes-none

#12871 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/XS, auto-merge, release-notes-none

#12872 [zh] translate image caption in multi cluster setup
  content/zh/docs/setup/install/multicluster/multi-primary/index.md
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#12869 gateway-api: add gateway api instructions to ingress access control doc
  .spelling
  content/en/docs/tasks/security/authorization/authz-ingress/gtwapi_test.sh
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
Labels: size/XXL

#12867 Add tests for smart DNS docs
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
Labels: size/L

#12877 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
Labels: size/L, auto-merge, release-notes-none

#12857 Stackgenie details added
  data/companies.yml
  static/logos/stackgenie.svg
Labels: size/XS, ok-to-test, cherrypick/release-1.17

#12878 [release-1.17] Stackgenie details added
  data/companies.yml
  static/logos/stackgenie.svg
Labels: size/XS, release-notes-none

#12842 [zh]sync deployment-models
  content/zh/docs/ops/deployment/deployment-models/blue-green.svg
  content/zh/docs/ops/deployment/deployment-models/endpoint-discovery.svg
  content/zh/docs/ops/deployment/deployment-models/index.md
  content/zh/docs/ops/deployment/deployment-models/single-cluster-external-control-plane.svg
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.17

#12843 [zh]update blog rust-based-ztunnel in chinese
  content/zh/blog/2023/rust-based-ztunnel/index.md
  content/zh/blog/2023/rust-based-ztunnel/kiali-ambient.png
  content/zh/blog/2023/rust-based-ztunnel/ztunnel-architecture.png
Labels: kind/docs, translation/chinese, size/L, ok-to-test, cherrypick/release-1.17

#12880 [release-1.17] [zh]sync deployment-models
  content/zh/docs/ops/deployment/deployment-models/blue-green.svg
  content/zh/docs/ops/deployment/deployment-models/endpoint-discovery.svg
  content/zh/docs/ops/deployment/deployment-models/index.md
  content/zh/docs/ops/deployment/deployment-models/single-cluster-external-control-plane.svg
Labels: size/L, release-notes-none

#12883 [release-1.17] [zh]update blog rust-based-ztunnel in chinese
  content/zh/blog/2023/rust-based-ztunnel/index.md
  content/zh/blog/2023/rust-based-ztunnel/kiali-ambient.png
  content/zh/blog/2023/rust-based-ztunnel/ztunnel-architecture.png
Labels: size/L, release-notes-none

#12449 dual-stack blog for Chinese
  content/zh/blog/2023/experimental-dual-stack/index.md
Labels: translation/chinese, size/L, cherrypick/release-1.17

#12881 [zh] content/zh/docs/ops/diagnostic-tools/cni/index.md
  content/zh/docs/ops/diagnostic-tools/cni/index.md
Labels: translation/chinese, size/M, ok-to-test, cherrypick/release-1.17

#12886 [release-1.17] dual-stack blog for Chinese
  content/zh/blog/2023/experimental-dual-stack/index.md
Labels: kind/docs, translation/chinese, size/L

#12887 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12791 Added headersToDownstreamOnAllow example in ext authz task page
  content/en/docs/tasks/security/authorization/authz-custom/index.md
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
Labels: kind/docs, size/XS, ok-to-test

#12885 [zh] update blog: experimental-dual-stack
  content/zh/blog/2023/experimental-dual-stack/index.md
Labels: kind/docs, translation/chinese, size/L

#12891 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/config/security/jwt/index.html
Labels: size/M, auto-merge, release-notes-none

#12874 single network services/endpoints can not have duplicate address
  content/en/docs/ops/deployment/deployment-models/index.md
Labels: size/XS, cherrypick/release-1.17

#12893 [release-1.17] single network services/endpoints can not have duplicate address
  content/en/docs/ops/deployment/deployment-models/index.md
Labels: size/XS, release-notes-none

#12894 gateway: run as non-root in example
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/gateway/snips.sh
Labels: size/S

#12889 gateway-api: add instructions to gateway topology doc
  content/en/docs/ops/configuration/traffic-management/network-topologies/gtwapi_test.sh
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/snips.sh
  content/en/docs/ops/configuration/traffic-management/network-topologies/test.sh
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
Labels: size/L

#12895 Update test reference to latest istio commit
  content/en/docs/tasks/observability/logs/otel-provider/index.md
  content/en/docs/tasks/observability/logs/otel-provider/snips.sh
  content/en/docs/tasks/observability/logs/otel-provider/test.sh
  go.mod
  go.sum
  tests/util/samples.sh
Labels: size/L

#12896 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#12898 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#12899 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12900 Automator: update common-files@release-1.15 in istio/istio.io@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12902 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12905 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, auto-merge, release-notes-none

#12834 breakout support status table to yaml file
  content/en/docs/releases/supported-releases/index.md
  data/args.yml
  data/compatibility/supportStatus.yml
  layouts/shortcodes/support_status_table.html
  layouts/shortcodes/supported_kubernetes_versions.html
  scripts/create_version.sh
Labels: size/L, ok-to-test

#12906 [zh] sync 2 files in /docs/tasks/security/
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: kind/docs, translation/chinese, size/L

#12914 Update the istio test reference and fix test code
  go.mod
  go.sum
  pkg/test/istioio/snapshot.go
Labels: size/M

#12915 teleletry: fix format
  content/en/docs/tasks/observability/logs/telemetry-api/index.md
Labels: area/extensions and telemetry, size/L, cherrypick/release-1.17

#12888 add docs for DNS Proxying for External TCP services
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
Labels: size/L

#12908 Specify EXTERNAL_CA env under .Values.pilot.env
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/snips.sh
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: size/S

#12920 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#12923 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12924 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/install-cni/index.html
Labels: size/L, auto-merge, release-notes-none

#12913 Mention gRPC probe in health checking of istio services page
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/en/docs/ops/configuration/mesh/app-health-check/snips.sh
Labels: kind/docs, size/M, ok-to-test

#12916 Telemetry API: custom metrics
  content/en/docs/tasks/observability/metrics/telemetry-api/index.md
Labels: size/L

#12926 [release-1.17] breakout support status table to yaml file
  content/en/docs/releases/supported-releases/index.md
  data/args.yml
  data/compatibility/supportStatus.yml
  layouts/shortcodes/support_status_table.html
  layouts/shortcodes/supported_kubernetes_versions.html
  scripts/create_version.sh
Labels: size/L, release-notes-none

#12928 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12930 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12929 Automator: update common-files@release-1.15 in istio/istio.io@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12931 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/M, auto-merge, release-notes-none

#12925 [zh] fix code format
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: kind/docs, translation/chinese, size/M, ok-to-test

#12901 [release-1.17] Redirect fix for `go get`
  layouts/index.redir
Labels: size/XS

#12935 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  data/analysis.yaml
Labels: size/M, auto-merge, release-notes-none

#12934 fix wrong folder name
  content/en/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
Labels: size/XS

#12937 gateway-api: change wait ready to wait programmed
  content/en/blog/2022/getting-started-gtwapi/index.md
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/snips.sh
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/zh/docs/examples/bookinfo/index.md
  content/zh/docs/setup/install/external-controlplane/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: size/M

#12939 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
Labels: size/XS, auto-merge, release-notes-none

#12942 [zh] sync docs concepts/traffic-management/index.md
  content/zh/docs/concepts/traffic-management/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#12941 [zh] sync content/zh/docs/concepts/observability/index.md
  content/zh/docs/concepts/observability/index.md
Labels: size/XS, ok-to-test

#12949 [zh]sync telemetry-api/index
  content/zh/docs/tasks/observability/metrics/telemetry-api/index.md
Labels: kind/docs, translation/chinese, size/L, ok-to-test

#12927 Update Supportted k8s release table for main branch
  data/compatibility/supportStatus.yml
Labels: size/XS, cherrypick/release-1.17

#12952 [release-1.17] Update Supportted k8s release table for main branch
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#12953 Fix gtw wait in util functions
  tests/util/helpers.sh
  tests/util/samples.sh
Labels: size/XS

#12956 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: size/L, auto-merge, release-notes-none

#12959 [zh]sync releases/log/index
  content/zh/docs/releases/log/index.md
Labels: kind/docs, size/XS

#12918 minor fixes to the Istio Standard Metrics page
  content/en/docs/reference/config/metrics/index.md
Labels: kind/docs, size/S, ok-to-test, cherrypick/release-1.17

#12961 gateway-api: future proof gateway address
  content/en/blog/2022/getting-started-gtwapi/index.md
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/snips.sh
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/zh/docs/examples/bookinfo/index.md
  content/zh/docs/setup/install/external-controlplane/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: size/M

#12963 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/L, auto-merge, release-notes-none

#12964 [zh]sync reference/config/metrics/index.md
  content/zh/docs/reference/config/metrics/index.md
Labels: kind/docs, translation/chinese, size/S

#12955 Updates Gateway Status Checking
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/ops/ambient/getting-started/test.sh
  go.mod
  go.sum
Labels: kind/docs, size/M, ok-to-test, area/ambient

#12890 Add blog: ambient ebpf redirection
  .spelling
  content/en/blog/2023/ambient-ebpf-redirection/MaxQPS.png
  content/en/blog/2023/ambient-ebpf-redirection/P75-Latency-with-8000-qps.png
  content/en/blog/2023/ambient-ebpf-redirection/ambient-ebpf.png
  content/en/blog/2023/ambient-ebpf-redirection/index.md
Labels: kind/docs, size/M, cherrypick/release-1.17

#12969 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#12965 [zh]sync releases/feature-stages/index.md
  content/zh/docs/releases/feature-stages/index.md
Labels: kind/docs, translation/chinese, size/XS

#12954 Reformat dates to use a consistent format
  data/compatibility/supportStatus.yml
Labels: kind/docs, size/S, cherrypick/release-1.17

#12974 [release-1.17] Reformat dates to use a consistent format
  data/compatibility/supportStatus.yml
Labels: size/S, release-notes-none

#12909 [zh]sync /releases/supported-releases/index.md
  content/zh/docs/releases/supported-releases/index.md
Labels: translation/chinese, size/M, ok-to-test

#12962 Update the test reference and skywalking test
  go.mod
  go.sum
Labels: size/S

#12970 Add istioctl command for CNI install
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/additional-setup/cni/snips.sh
  content/en/docs/setup/additional-setup/cni/test.sh
Labels: area/environments, kind/docs, size/S

#12976 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#12977 [zh] Add blog: ambient ebpf redirection
  content/zh/blog/2023/ambient-ebpf-redirection/MaxQPS.png
  content/zh/blog/2023/ambient-ebpf-redirection/P75-Latency-with-8000-qps.png
  content/zh/blog/2023/ambient-ebpf-redirection/ambient-ebpf.png
  content/zh/blog/2023/ambient-ebpf-redirection/index.md
Labels: kind/docs, size/M, area/ambient

#12957 [zh] sync /ops/ambient/getting-started/
  content/zh/docs/ops/ambient/_index.md
  content/zh/docs/ops/ambient/getting-started/index.md
  content/zh/docs/ops/ambient/getting-started/kiali-ambient-bookinfo.png
  content/zh/docs/reference/glossary/ambient.md
  content/zh/docs/reference/glossary/waypoint.md
  content/zh/docs/reference/glossary/ztunnel.md
Labels: kind/docs, translation/chinese, size/L, area/ambient

#12944 [zh] sync add external-loadbalancer-support.md
  content/zh/boilerplates/external-loadbalancer-support.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#12932 Adds K8s Gateway API to Getting Started Guide
  content/en/docs/ops/ambient/getting-started/gtwapi_test.sh
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/ops/ambient/getting-started/test.sh
Labels: kind/docs, size/L, ok-to-test, area/ambient

#12978 [release-1.17] [zh] Add blog: ambient ebpf redirection
  content/zh/blog/2023/ambient-ebpf-redirection/MaxQPS.png
  content/zh/blog/2023/ambient-ebpf-redirection/P75-Latency-with-8000-qps.png
  content/zh/blog/2023/ambient-ebpf-redirection/ambient-ebpf.png
  content/zh/blog/2023/ambient-ebpf-redirection/index.md
Labels: size/M, release-notes-none

#12967 add a waypoint proxy blog
  .spelling
  content/en/blog/2023/waypoint-proxy-made-simple/index.md
  content/en/blog/2023/waypoint-proxy-made-simple/sidecar-config.png
  content/en/blog/2023/waypoint-proxy-made-simple/waypoint-architecture.png
  content/en/blog/2023/waypoint-proxy-made-simple/waypoint-config.png
Labels: kind/docs, size/L, cherrypick/release-1.17, area/ambient

#12980 [release-1.17] add a waypoint proxy blog
  .spelling
  content/en/blog/2023/waypoint-proxy-made-simple/index.md
  content/en/blog/2023/waypoint-proxy-made-simple/sidecar-config.png
  content/en/blog/2023/waypoint-proxy-made-simple/waypoint-architecture.png
  content/en/blog/2023/waypoint-proxy-made-simple/waypoint-config.png
Labels: size/L, release-notes-none

#12981 add a link to the new waypoint blog
  content/en/blog/2023/ambient-merged-istio-main/index.md
Labels: size/XS, cherrypick/master

#12982 [master] add a link to the new waypoint blog
  content/en/blog/2023/ambient-merged-istio-main/index.md
Labels: size/XS, release-notes-none
