Repository istio/istio.io, pull requests merged in 2023-01, with the labels that each got.

#12426 Add a bullet symbol in /additional-setup/cni/
  content/en/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, size/XS

#12425 [zh] sync /setup/additional-setup/cni/
  content/zh/docs/setup/additional-setup/cni/cni.svg
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, translation/chinese, size/L

#12423 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12429 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#12430 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
Labels: size/XS, auto-merge, release-notes-none

#12417 Automator: update istio@ test reference
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-support.sh
  content/en/boilerplates/snips/gateway-api-version.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/M, release-notes-none

#12418 update hugo to 0.109.0
  netlify.toml
Labels: size/XS

#12431 Update version page
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS, cherrypick/release-1.16

#12432 [release-1.16] Update version page
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS, release-notes-none

#12433 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12434 [release-1.16] [zh] sync /docs/releases/supported-releases/
  content/zh/docs/releases/supported-releases/index.md
Labels: size/S, release-notes-none

#12408 [zh] fix translation errors
  content/zh/docs/concepts/security/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test, cherrypick/release-1.16

#12437 [zh] sync /authorization/authz-tcp/
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
Labels: kind/docs, translation/chinese, size/S

#12436 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#12413 [zh] sync /releases/security-vulnerabilities/
  content/zh/docs/releases/security-vulnerabilities/index.md
Labels: kind/docs, translation/chinese, size/S

#12427 task for copy claim to header
  content/en/docs/tasks/security/authentication/claim-to-header/index.md
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/test.sh
Labels: area/security, size/L

#12440 Run go-mod-update
  go.mod
  go.sum
  pkg/test/istioio/snapshot.go
Labels: size/XS

#12442 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#12443 [zh] sync /setup/platform-setup/gardener/
  content/zh/docs/setup/platform-setup/gardener/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.16

#12441 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12444 [release-1.16] [zh] sync /setup/platform-setup/gardener/
  content/zh/docs/setup/platform-setup/gardener/index.md
Labels: size/M, release-notes-none

#12445 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12447 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: size/M, auto-merge, release-notes-none

#12446 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#12448 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12415 Doc: multiple control planes using revisions and discoverySelectors
  .spelling
  content/en/docs/setup/install/multiple-controlplanes/index.md
  content/en/docs/setup/install/multiple-controlplanes/single-cluster-multiple-istiods.svg
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
  content/en/docs/setup/install/multiple-controlplanes/test.sh
Labels: kind/docs, size/XL

#12451 Fix text boxes not displaying quite right
  content/en/docs/setup/install/multiple-controlplanes/index.md
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
Labels: size/M

#11062 re-submit pr#10873
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: area/networking, size/XS, release-notes-none

#12454 Automator: update common-files@release-1.15 in istio/istio.io@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12453 Add CNCF logo footer & LF terms
  content/en/_index.html
  i18n/en.toml
  i18n/zh.toml
  layouts/partials/footer.html
  src/sass/misc/_landing.scss
  static/img/cncf-color.svg
Labels: size/L

#12458 [release-1.16] Doc: multiple control planes using revisions and discoverySelectors
  .spelling
  content/en/docs/setup/install/multiple-controlplanes/index.md
  content/en/docs/setup/install/multiple-controlplanes/single-cluster-multiple-istiods.svg
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
  content/en/docs/setup/install/multiple-controlplanes/test.sh
Labels: size/XL, release-notes-none

#12460 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12455 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  data/features.yaml
Labels: size/L, auto-merge, release-notes-none

#12461 [release-1.16] Fix text boxes not displaying quite right
  content/en/docs/setup/install/multiple-controlplanes/index.md
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
Labels: size/M, release-notes-none

#12462 [release-1.16] Add CNCF logo footer & LF terms
  content/en/_index.html
  i18n/en.toml
  i18n/zh.toml
  layouts/partials/footer.html
  src/sass/misc/_landing.scss
  static/img/cncf-color.svg
Labels: size/L, release-notes-none

#12468 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#12469 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/jwt/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
Labels: size/M, auto-merge, release-notes-none

#12459 Improve see-also references for gateway api
  content/en/blog/2022/getting-started-gtwapi/index.md
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XS, cherrypick/release-1.16

#12471 [release-1.16] Improve see-also references for gateway api
  content/en/blog/2022/getting-started-gtwapi/index.md
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XS, release-notes-none

#12470 [zh] sync /setup/install/multiple-controlplanes/
  content/zh/docs/setup/install/multiple-controlplanes/index.md
  content/zh/docs/setup/install/multiple-controlplanes/single-cluster-multiple-istiods.svg
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.16

#12472 [release-1.16] [zh] sync /setup/install/multiple-controlplanes/
  content/zh/docs/setup/install/multiple-controlplanes/index.md
  content/zh/docs/setup/install/multiple-controlplanes/single-cluster-multiple-istiods.svg
Labels: size/L, release-notes-none

#12473 Add missing context argument when installing crds
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: size/M

#12435 Add otel headers to tracing faq
  content/en/about/faq/distributed-tracing/how-to-support-tracing.md
  content/zh/about/faq/distributed-tracing/how-to-support-tracing.md
Labels: kind/docs, size/S, cherrypick/release-1.16

#12475 [release-1.16] Add otel headers to tracing faq
  content/en/about/faq/distributed-tracing/how-to-support-tracing.md
  content/zh/about/faq/distributed-tracing/how-to-support-tracing.md
Labels: size/S, release-notes-none

#12478 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12466 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/L, release-notes-none

#12477 Remote cluster get crds also needs context arg
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
Labels: size/XS

#12480 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12438 update filter that depends on xds v2 api
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: kind/docs, size/XS, ok-to-test

#12484 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12485 Stable Revisions feature is Alpha
  content/en/docs/setup/upgrade/canary/index.md
Labels: do-not-merge, size/XS

#12487 Update istio.io to prepare for 1.17
  Makefile.core.mk
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/jwt/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  data/args.yml
  go.mod
  go.sum
Labels: size/L

#12488 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12489 fix footer policies text on mobile
  src/sass/misc/_footer.scss
Labels: area/user experience, size/XS, cherrypick/release-1.16

#12493 [release-1.16] fix footer policies text on mobile
  src/sass/misc/_footer.scss
Labels: size/XS, release-notes-none

#12494 Fix flakiest test
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
Labels: size/S

#12491 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/jwt/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  data/features.yaml
Labels: size/M, auto-merge, release-notes-none

#12495 Is the sleep delete affecting the later start?
  tests/util/samples.sh
Labels: size/XS

#12497 update Solo.io and Gloo Edge logos
  static/logos/gloo.png
  static/logos/solo.png
Labels: kind/docs, size/XS, ok-to-test

#12499 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#12501 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12476 Enhance helm documentation
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/install/helm/test.sh
Labels: kind/docs, size/L

#12504 [release-1.16] update Solo.io and Gloo Edge logos
  static/logos/gloo.png
  static/logos/solo.png
Labels: size/XS, release-notes-none

#12502 [release-1.16] Updating InfraCloud in Pro_Services Providers (under Ecosystem)
  data/companies.yml
Labels: size/XS, release-notes-none

#12505 Update k8s version used for istio.io tests
  prow/integ-suite-kind.sh
Labels: area/test and release, size/XS

#12507 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12511 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
Labels: size/XS, auto-merge, release-notes-none

#12506 Add PDB and HPA example for gateway-api
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
Labels: size/L

#12512 Automator: update common-files@release-1.15 in istio/istio.io@release-1.15
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#12503 [release-1.16] [zh] fix translation errors
  content/zh/docs/concepts/security/index.md
Labels: size/XS, release-notes-none

#12510 Add more context to the PROXY protocol gateway config section
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
Labels: size/S, ok-to-test

#12513 Fix wildcard egress section titles
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
Labels: size/M

#12508 Update values so istioctl x wait works
  content/en/docs/ops/configuration/mesh/config-resource-ready/snips.sh
  content/en/docs/ops/configuration/traffic-management/network-topologies/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/setup/additional-setup/gateway/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/multicluster/multi-primary/snips.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
  content/en/docs/setup/install/virtual-machine/snips.sh
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/logs/otel-provider/snips.sh
  content/en/docs/tasks/observability/metrics/customize-metrics/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/snips.sh
  scripts/snip.py
  tests/setup/profile_default/doc_test.go
  tests/setup/profile_demo/doc_test.go
Labels: size/M

#12514 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12516 fix indentation and add missing field
  content/en/docs/ops/integrations/spire/index.md
Labels: kind/docs, size/M, ok-to-test

#12519 [release-1.16] fix indentation and add missing field
  content/en/docs/ops/integrations/spire/index.md
Labels: size/M, release-notes-none

#12496 Enhance docs for revision tags and add tests
  content/en/boilerplates/revision-tags-middle.md
  content/en/boilerplates/revision-tags-prologue.md
  content/en/boilerplates/revision-tags-usage.md
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/setup/upgrade/canary/canary_upgrade_test.sh
  content/en/docs/setup/upgrade/canary/index.md
  content/en/docs/setup/upgrade/canary/revision_tags_test.sh
  content/en/docs/setup/upgrade/canary/snips.sh
Labels: size/L

#12521 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#12523 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12515 Test istio-dashboard fix of generating additional trace data
  content/en/docs/tasks/observability/metrics/using-istio-dashboard/test.sh
Labels: size/XS

#12522 Add missing gateway-api guard in test
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/test.sh
Labels: size/XS

#12524 Automator: update common-files@release-1.15 in istio/istio.io@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12525 Remove Helm feature stage from preamble
  content/en/boilerplates/helm-preamble.md
Labels: size/XS

#12526 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12533 Add image sized for OpenGraph preview
  static/img/istio-social.svg
Labels: size/XS

#12534 [release-1.16] Add image sized for OpenGraph preview
  static/img/istio-social.svg
Labels: size/XS, release-notes-none

#12535 Add markdown-only lint option
  Makefile.core.mk
Labels: size/XS

#12531 Media resources
  content/en/about/media-resources/index.md
  content/zh/about/media-resources/index.md
  layouts/_default/baseof.html
  layouts/index.redir
  src/sass/_all.scss
  src/sass/misc/_media-resources.scss
  static/img/istio-bluelogo-nobackground-framed.svg
  static/img/istio-bluelogo-nobackground-unframed.svg
  static/img/istio-bluelogo-whitebackground-framed.svg
  static/img/istio-bluelogo-whitebackground-unframed.svg
  static/img/istio-whitelogo-bluebackground-framed.svg
  static/img/istio-whitelogo-bluebackground-unframed.svg
  static/img/istio-whitelogo-nobackground-framed.svg
  static/img/istio-whitelogo-nobackground-unframed.svg
Labels: size/L

#12528 Announce IstioDay at KubeCon Europe 2023
  .spelling
  content/en/blog/2023/istioday-kubecon-eu/index.md
  content/en/blog/2023/istioday-kubecon-eu/istioday-eu-logo.png
Labels: size/M, cherrypick/release-1.16

#12532 Automator: update istio.io@ reference docs
  data/features.yaml
Labels: size/XS, auto-merge, release-notes-none

#12539 [release-1.16] Media resources (#12531)
  content/en/about/media-resources/index.md
  content/zh/about/media-resources/index.md
  layouts/_default/baseof.html
  layouts/index.redir
  src/sass/_all.scss
  src/sass/misc/_media-resources.scss
  static/img/istio-bluelogo-nobackground-framed.svg
  static/img/istio-bluelogo-nobackground-unframed.svg
  static/img/istio-bluelogo-whitebackground-framed.svg
  static/img/istio-bluelogo-whitebackground-unframed.svg
  static/img/istio-whitelogo-bluebackground-framed.svg
  static/img/istio-whitelogo-bluebackground-unframed.svg
  static/img/istio-whitelogo-nobackground-framed.svg
  static/img/istio-whitelogo-nobackground-unframed.svg
Labels: size/L

#12527 Update custom ca integration with k8s CSR demo
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: kind/docs, size/XS, ok-to-test

#12543 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12498 [zh] Sync ingress-with-no-route-rules.md
  content/zh/about/faq/traffic-management/ingress-with-no-route-rules.md
Labels: kind/docs, translation/chinese, size/M

#12546 [release-1.16] [zh] sync /boilerplates/gateway-api
  content/zh/boilerplates/gateway-api-choose.md
  content/zh/boilerplates/gateway-api-future.md
  content/zh/boilerplates/gateway-api-gamma-support.md
  content/zh/boilerplates/gateway-api-install-crds.md
  content/zh/boilerplates/gateway-api-support.md
  content/zh/boilerplates/gateway-api-version.md
Labels: size/M, release-notes-none

#12518 [zh] sync /ops/integrations/skywalking/
  content/zh/docs/ops/integrations/skywalking/index.md
Labels: kind/docs, translation/chinese, size/M

#12545 Automator: update istio.io@ reference docs
  data/features.yaml
Labels: size/XS, auto-merge, release-notes-none

#12482 update tracing
  content/en/docs/ops/integrations/jaeger/index.md
  content/en/docs/ops/integrations/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
Labels: area/policies and telemetry, size/M, cherrypick/release-1.16

#12547 [release-1.16] update tracing
  content/en/docs/ops/integrations/jaeger/index.md
  content/en/docs/ops/integrations/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
Labels: size/M, release-notes-none

#12550 [zh] modify /setup/platform-setup/oci/
  content/zh/docs/setup/platform-setup/oci/index.md
Labels: kind/docs, translation/chinese, size/M

#12548 update boilerplates
  content/en/boilerplates/telemetry-tracing-tips.md
  content/en/docs/ops/integrations/jaeger/index.md
  content/en/docs/ops/integrations/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
Labels: size/S

#12551 add telemetry tips
  content/en/docs/tasks/observability/telemetry/index.md
Labels: size/S

#12555 Add December 2022 security audit report
  .spelling
  content/en/blog/2023/ada-logics-security-assessment/Istio audit report - ADA Logics - 2022-12-28 - v1.0.pdf
  content/en/blog/2023/ada-logics-security-assessment/index.md
Labels: size/L

#12553 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12538 Update revision tag diagrams
  content/en/boilerplates/revision-tags-middle.md
  content/en/boilerplates/revision-tags-prologue.md
  content/en/docs/setup/upgrade/canary/revision-tags-after.svg
  content/en/docs/setup/upgrade/canary/revision-tags-before.svg
  content/en/docs/setup/upgrade/canary/tags-updated.png
  content/en/docs/setup/upgrade/canary/tags.png
Labels: size/S, ok-to-test

#12556 [master] Add December 2022 security audit report
  .spelling
  content/en/blog/2023/ada-logics-security-assessment/Istio audit report - ADA Logics - 2022-12-28 - v1.0.pdf
  content/en/blog/2023/ada-logics-security-assessment/index.md
Labels: size/L, release-notes-none

#12530 Add 1.15.5 release notes
  content/en/news/releases/1.15.x/announcing-1.15.5/index.md
Labels: size/S, cherrypick/release-1.16

#12529 1.16.2 release notes
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/news/releases/1.16.x/announcing-1.16.2/index.md
  data/args.yml
Labels: kind/docs, size/M

#12559 [release-1.16] Add 1.15.5 release notes
  content/en/news/releases/1.15.x/announcing-1.15.5/index.md
Labels: size/S, release-notes-none

#12540 [release-1.15] Update istio test reference to 1.15.5
  go.mod
  go.sum
Labels: size/S

#12541 [release-1.16] Update istio test reference for 1.16.2
  go.mod
  go.sum
Labels: size/L

#12560 [release-1.16] add telemetry tips
  content/en/docs/tasks/observability/telemetry/index.md
Labels: size/S, release-notes-none

#12561 Small fix in istio day announcement
  content/en/blog/2023/istioday-kubecon-eu/index.md
Labels: size/XS, cherrypick/release-1.16

#12563 [release-1.16] Small fix in istio day announcement
  content/en/blog/2023/istioday-kubecon-eu/index.md
Labels: size/XS, release-notes-none

#12565 Remove experimental from stable revisions title
  content/en/blog/2021/revision-tags/index.md
  content/en/docs/setup/upgrade/helm/index.md
  content/en/news/releases/1.10.x/announcing-1.10/_index.md
Labels: size/XS
