Repository istio/istio.io, pull requests merged in 2023-12, with the labels that each got.

#14215 Manual cherrypick of #14146
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: size/S

#14214 Remove use of installed-state
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
Labels: size/S

#14218 [zh] Sync #14214 into Chinese
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: translation/chinese, size/XS

#14217 [zh] sync releases/bugs front-matter add-content
  content/zh/docs/releases/bugs/index.md
  content/zh/docs/releases/contribute/add-content/index.md
  content/zh/docs/releases/contribute/front-matter/index.md
Labels: kind/docs, translation/chinese, size/L

#14219 [zh] improve shortcodes
  content/zh/docs/releases/contribute/shortcodes/index.md
Labels: translation/chinese, size/L

#14222 Fix type in egress SNI routing blog
  content/en/blog/2023/egress-sni/index.md
Labels: kind/docs, size/XS

#14226 [release-1.20] Fix type in egress SNI routing blog
  content/en/blog/2023/egress-sni/index.md
Labels: size/XS, release-notes-none

#14200 Update istio test reference to latest commit and fix tests
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
  content/en/docs/setup/install/external-controlplane/test.sh
  content/en/docs/tasks/observability/logs/telemetry-api/test-disable.sh
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/test_disable.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
  go.mod
  go.sum
Labels: size/L

#14230 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#14208 [zh] Localize deployment arch image into Chinese
  content/zh/docs/ops/deployment/architecture/arch.svg
Labels: translation/chinese, size/XL

#14232 [zh] Localize deployment-models iso-ns image
  content/zh/docs/ops/deployment/deployment-models/iso-ns.svg
Labels: kind/docs, translation/chinese, size/L

#14234 [zh] Localize deployment-models multi-control image
  content/zh/docs/ops/deployment/deployment-models/multi-control.svg
Labels: kind/docs, translation/chinese, size/L

#14233 [zh] Localize deployment model image into Chinese
  content/zh/docs/ops/deployment/deployment-models/cluster-iso.svg
Labels: kind/docs, translation/chinese, size/L

#14238 [zh] Localize deployment model shared-control image
  content/zh/docs/ops/deployment/deployment-models/shared-control.svg
Labels: kind/docs, translation/chinese, size/L

#14239 [zh] Localize deployment models single-cluster image
  content/zh/docs/ops/deployment/deployment-models/single-cluster.svg
Labels: translation/chinese, size/L

#14240 [zh] Localize deployment cluster-ns image into Chinese
  content/zh/docs/ops/deployment/deployment-models/cluster-ns.svg
Labels: kind/docs, translation/chinese, size/L

#14241 [zh] Localize deployment multi-net image
  content/zh/docs/ops/deployment/deployment-models/multi-net.svg
Labels: translation/chinese, size/L

#14242 [zh] Localize deployment exp-ns image into Chinese
  content/zh/docs/ops/deployment/deployment-models/exp-ns.svg
Labels: kind/docs, translation/chinese, size/L

#14243 [zh] Localize deployment failover image
  content/zh/docs/ops/deployment/deployment-models/failover.svg
Labels: translation/chinese, size/L

#14244 [zh] Localize deployment single-trust image
  content/zh/docs/ops/deployment/deployment-models/single-trust.svg
Labels: translation/chinese, size/L

#14245 [zh] Localize deployment blue-green image into Chinese
  content/zh/docs/ops/deployment/deployment-models/blue-green.svg
Labels: kind/docs, translation/chinese, size/XXL

#14221 [zh] Sync egress SNI routing blog into Chinese
  content/zh/blog/2023/egress-sni/egress-sni-flow.png
  content/zh/blog/2023/egress-sni/index.md
Labels: kind/docs, translation/chinese, size/L

#14250 [zh] Localize deployment single-cluster-external-control-plane image into Chinese
  content/zh/docs/ops/deployment/deployment-models/single-cluster-external-control-plane.svg
Labels: kind/docs, translation/chinese, size/XL

#14231 [zh] improve style-guide terminology
  content/zh/docs/releases/contribute/style-guide/index.md
  content/zh/docs/releases/contribute/terminology/index.md
Labels: translation/chinese, size/L

#14259 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  data/analysis.yaml
Labels: size/M, auto-merge, release-notes-none

#14248 Re-enable tasks/observability/logs/telemetry-api
  content/en/docs/tasks/observability/logs/telemetry-api/test.sh
  go.mod
  go.sum
Labels: size/S

#14258 Replace a PNG with a SVG in the security concept
  content/en/docs/concepts/security/authz-eval.png
  content/en/docs/concepts/security/authz-eval.svg
  content/en/docs/concepts/security/index.md
Labels: kind/docs, size/L, cherrypick/release-1.20

#14262 [release-1.20] Replace a PNG with a SVG in the security concept
  content/en/docs/concepts/security/authz-eval.png
  content/en/docs/concepts/security/authz-eval.svg
  content/en/docs/concepts/security/index.md
Labels: size/L, release-notes-none

#14228 Relese 1.20 performance test
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency-p90-fortio-with-uniform.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency-p99-fortio-with-uniform.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
Labels: area/perf and scalability, size/XXL, ok-to-test, cherrypick/release-1.20

#14249 Move text from diagram to body paras for blog egress-sni
  content/en/blog/2023/egress-sni/egress-sni-flow.png
  content/en/blog/2023/egress-sni/egress-sni-flow.svg
  content/en/blog/2023/egress-sni/index.md
Labels: kind/docs, size/L, cherrypick/release-1.20

#14267 [release-1.20] Move text from diagram to body paras for blog egress-sni
  content/en/blog/2023/egress-sni/egress-sni-flow.png
  content/en/blog/2023/egress-sni/egress-sni-flow.svg
  content/en/blog/2023/egress-sni/index.md
Labels: size/L, release-notes-none

#14268 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14269 Automator: update common-files@release-1.19 in istio/istio.io@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14270 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
Labels: size/S, auto-merge, release-notes-none

#14272 Automator: update common-files@release-1.18 in istio/istio.io@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14271 Automator: update common-files@release-1.20 in istio/istio.io@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14261 [zh] Sync #14146 into Chinese
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: kind/docs, translation/chinese, size/S

#14266 [zh] Sync #14228 1.20 performance test into Chinese
  content/zh/docs/ops/deployment/performance-and-scalability/index.md
  content/zh/docs/ops/deployment/performance-and-scalability/latency-p90-fortio-with-uniform.svg
  content/zh/docs/ops/deployment/performance-and-scalability/latency-p99-fortio-with-uniform.svg
  content/zh/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/zh/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
Labels: kind/docs, translation/chinese, size/XXL

#14280 [release-1.20] Fix ext authz doc
  content/en/docs/tasks/security/authorization/authz-custom/index.md
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
Labels: size/XS, release-notes-none

#14281 [zh] Sync #14274 into Chinese
  content/zh/docs/tasks/security/authorization/authz-custom/index.md
Labels: kind/docs, translation/chinese, size/XS

#14276 Add missing component in _rewrite_helm_repo
  tests/util/helpers.sh
Labels: area/test and release, size/XS

#14264 [zh] Sync #14258 and localize svgs into Chinese
  content/zh/docs/concepts/security/arch-sec.svg
  content/zh/docs/concepts/security/authn.svg
  content/zh/docs/concepts/security/authz-eval.png
  content/zh/docs/concepts/security/authz-eval.svg
  content/zh/docs/concepts/security/authz.svg
  content/zh/docs/concepts/security/id-prov.svg
  content/zh/docs/concepts/security/index.md
Labels: kind/docs, translation/chinese, size/XXL

#14277 [zh] Sync #14257 into Chinese
  content/zh/docs/setup/additional-setup/dual-stack/index.md
Labels: kind/docs, translation/chinese, size/M

#14283 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/install-cni/index.html
Labels: size/XS, auto-merge, release-notes-none

#14287 added cleanup section of an observability task
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: kind/docs, size/XS, ok-to-test

#14286 [zh] Localize overview.svg in security concept
  content/zh/docs/concepts/security/index.md
  content/zh/docs/concepts/security/overview.svg
Labels: kind/docs, translation/chinese, size/L

#14288 [zh] Sync #14287 into Chinese
  content/zh/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: kind/docs, translation/chinese, size/S

#14290 Correct typos
  content/en/docs/examples/microservices-istio/add-istio/index.md
Labels: kind/docs, size/XS, ok-to-test

#14282 Enable jwt-route
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/test.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/XL

#14296 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
Labels: size/M, auto-merge, release-notes-none

#14297 delete the
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: kind/docs, size/XS, ok-to-test

#14298 [release-1.20] delete the
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
Labels: size/XS, release-notes-none

#14300 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#14299 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#14308 [release-1.20] Rework header animation to use WebGL render and WGSL shaders
  layouts/home.html
  src/ts/headerAnimation.js
Labels: size/L, release-notes-none

#14302 ISTIO-SECURITY-2023-005 & CNI Docs Updates
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/news/security/istio-security-2023-005/index.md
Labels: kind/docs, size/M, cherrypick/release-1.20

#14311 Update supportStatus.yml
  data/compatibility/supportStatus.yml
Labels: kind/docs, size/XS, ok-to-test, cherrypick/release-1.20

#14312 1.18.6 release notes
  content/en/news/releases/1.18.x/announcing-1.18.6/index.md
Labels: kind/docs, size/M, cherrypick/release-1.20

#14309 [release-1.20] ISTIO-SECURITY-2023-005 & CNI Docs Updates
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/news/security/istio-security-2023-005/index.md
Labels: size/M, release-notes-none

#14313 [release-1.20] Manual cherrypick of 1.20.1 release notes
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.20.x/announcing-1.20.1/index.md
  data/args.yml
Labels: kind/docs, size/M

#14310 [release-1.20] Release notes for 1.19.5
  content/en/news/releases/1.19.x/announcing-1.19.5/index.md
Labels: size/M, release-notes-none

#14314 [release-1.20] 1.18.6 release notes
  content/en/news/releases/1.18.x/announcing-1.18.6/index.md
Labels: size/M, release-notes-none

#14294 [release-1.18] Update to use 1.18.6 for testing
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  go.mod
  go.sum
Labels: size/M

#14295 [release-1.19] Update to use 1.19.5 for testing
  go.mod
  go.sum
  tests/tests.mk
Labels: size/S

#14293 [release-1.20] make update_ref_docs for 1.20.1
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/en/docs/reference/config/type/workload-selector/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/type/workload-selector/index.html
Labels: size/XL

#14315 [release-1.20] Update supportStatus.yml
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#14292 [release-1.20] Update to use 1.20.1 for testing
  Makefile.core.mk
  go.mod
  go.sum
Labels: size/S

#14318 Fix a date to security-2023-005 in 1.20.1 release notes for consistency
  content/en/news/releases/1.20.x/announcing-1.20.1/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.20

#14319 Fix typo for best practices security doc
  content/en/docs/ops/best-practices/security/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.20

#14320 [release-1.20] Fix a date to security-2023-005 in 1.20.1 release notes for consistency
  content/en/news/releases/1.20.x/announcing-1.20.1/index.md
Labels: size/XS, release-notes-none

#14321 [release-1.20] Fix typo for best practices security doc
  content/en/docs/ops/best-practices/security/index.md
Labels: size/XS, release-notes-none

#14323 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#14324 [zh]improve plugin-ca-cert/index.md
  content/zh/docs/tasks/security/cert-management/plugin-ca-cert/index.md
Labels: kind/docs, translation/chinese, size/S

#14326 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14325 [zh] Fix wrong header of Prometheus doc
  content/zh/docs/ops/integrations/prometheus/index.md
Labels: kind/docs, translation/chinese, size/S

#14322 [zh] Sync security-2023-005 into Chinese
  content/zh/news/security/istio-security-2023-005/index.md
Labels: kind/docs, translation/chinese, size/M

#13871 Add ambient helm installation guide
  content/en/docs/ops/ambient/install/_index.md
  content/en/docs/ops/ambient/install/helm-installation/index.md
  content/en/docs/ops/ambient/install/helm-installation/snips.sh
  content/en/docs/ops/ambient/install/helm-installation/test.sh
  content/en/docs/ops/ambient/usage/ztunnel/index.md
Labels: area/environments, kind/docs, size/L

#14328 [zh] Optimize the zh translation of deployment documents
  content/zh/about/deployment/index.md
Labels: kind/docs, size/XS, ok-to-test

#14331 [release-1.20] Add missing component in _rewrite_helm_repo
  tests/util/helpers.sh
Labels: size/XS, release-notes-none

#14330 [release-1.20] Add ambient helm installation guide (#13871)
  content/en/docs/ops/ambient/install/_index.md
  content/en/docs/ops/ambient/install/helm-installation/index.md
  content/en/docs/ops/ambient/install/helm-installation/snips.sh
  content/en/docs/ops/ambient/install/helm-installation/test.sh
  content/en/docs/ops/ambient/usage/ztunnel/index.md
Labels: kind/docs, size/L

#14327 update hugo to 0.121.1
  netlify.toml
Labels: area/test and release, size/XS

#14333 Update documentation for ExternalName in 1.21
  content/en/docs/ops/configuration/traffic-management/traffic-routing/index.md
Labels: size/M, release-notes-none

#14334 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14336 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  data/analysis.yaml
Labels: size/M, auto-merge, release-notes-none

#14332 [zh] Sync install ambient with helm doc into Chinese
  content/zh/docs/ops/ambient/install/_index.md
  content/zh/docs/ops/ambient/install/helm-installation/index.md
Labels: kind/docs, translation/chinese, size/L

#14306 [zh] Update terms about load-balance, observability and _index page
  content/zh/_index.html
  content/zh/about/case-studies/autotrader/index.md
  content/zh/about/case-studies/bol.com/index.md
  content/zh/about/case-studies/ebay/index.md
  content/zh/about/case-studies/t-mobile/index.md
  content/zh/about/case-studies/wp-engine/index.md
  content/zh/about/deployment/index.md
  content/zh/about/service-mesh/index.md
  content/zh/blog/2018/aws-nlb/index.md
  content/zh/blog/2019/knative-activator-adapter/index.md
  content/zh/blog/2019/performance-best-practices/index.md
  content/zh/blog/2020/istiod/index.md
  content/zh/blog/2020/wasm-announce/index.md
  content/zh/blog/2020/workload-entry/index.md
  content/zh/blog/2021/zero-config-istio/index.md
  content/zh/blog/2022/merbridge/index.md
  content/zh/docs/ops/ambient/usage/ztunnel/index.md
  content/zh/docs/ops/deployment/deployment-models/index.md
  content/zh/docs/ops/integrations/kiali/index.md
  content/zh/docs/releases/feature-stages/index.md
  content/zh/docs/setup/install/external-controlplane/index.md
  content/zh/docs/tasks/observability/_index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
  content/zh/news/releases/0.x/announcing-0.1/index.md
  content/zh/news/releases/1.0.x/announcing-1.0/index.md
  content/zh/news/releases/1.1.x/announcing-1.1.3/index.md
  content/zh/news/releases/1.18.x/announcing-1.18/change-notes/index.md
  content/zh/news/releases/1.3.x/announcing-1.3/_index.md
  content/zh/news/releases/1.5.x/announcing-1.5/_index.md
  content/zh/news/releases/1.6.x/announcing-1.6/_index.md
  content/zh/news/releases/1.9.x/announcing-1.9.4/index.md
Labels: kind/docs, translation/chinese, size/L, ok-to-test

#14317 [zh] Localize 1.18.6, 1.19.5, and 1.20.1 release notes
  content/zh/news/releases/1.18.x/announcing-1.18.6/index.md
  content/zh/news/releases/1.19.x/announcing-1.19.5/index.md
  content/zh/news/releases/1.20.x/announcing-1.20.1/index.md
Labels: kind/docs, translation/chinese, size/L

#14337 update deprecated field percent to percentage
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
Labels: kind/docs, size/S

#14335 [zh] Add translations to /traffic-management/traffic-routing/
  content/zh/docs/ops/configuration/traffic-management/traffic-routing/index.md
Labels: kind/docs, translation/chinese, size/L

#14340 [release-1.20] update deprecated field percent to percentage
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
Labels: size/S, release-notes-none

#14348 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
Labels: size/M, auto-merge, release-notes-none

#14349 [release-1.20] [zh] Sync install ambient with helm doc into Chinese
  content/zh/docs/ops/ambient/install/_index.md
  content/zh/docs/ops/ambient/install/helm-installation/index.md
Labels: size/L, release-notes-none

#14338 [zh] Sync #14337 into Chinese
  content/zh/docs/tasks/traffic-management/request-timeouts/index.md
Labels: kind/docs, translation/chinese, size/XS

#14339 [zh] Sync rest of #13871 into Chinese
  content/zh/docs/ops/ambient/usage/ztunnel/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.20

#14351 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/L, release-notes-none

#14353 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: size/S, auto-merge, release-notes-none

#14356 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#14354 [zh] Localize a case study: /bluecore/
  content/zh/about/case-studies/bluecore/bluecore-containers.png
  content/zh/about/case-studies/bluecore/bluecore-statistics.png
  content/zh/about/case-studies/bluecore/index.md
Labels: kind/docs, translation/chinese, size/L

#14357 [zh] Sync deployment model doc to the latest English content
  content/zh/docs/ops/deployment/deployment-models/blue-green.svg
  content/zh/docs/ops/deployment/deployment-models/failover.svg
  content/zh/docs/ops/deployment/deployment-models/index.md
  content/zh/docs/ops/deployment/deployment-models/iso-ns.svg
Labels: size/XXL

#14359 update protocol-selection notes
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: area/networking, kind/docs, size/XS, cherrypick/release-1.20

#14360 [release-1.20] update protocol-selection notes
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: size/XS, release-notes-none

#14361 [zh] Sync #14359 into Chinese
  content/zh/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: kind/docs, translation/chinese, size/XS

#14363 [release-1.20] [zh] Sync #14359 into Chinese
  content/zh/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: size/XS, release-notes-none

#14364 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/install-cni/index.html
Labels: size/L, auto-merge, release-notes-none

#14362 add san-validation documentation
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
Labels: size/M

#14367 [release-1.20] add san-validation documentation
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
Labels: size/M, release-notes-none

#14368 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#14370 [release-1.20] [zh] Translate Ambient and ztunnel L4 docs into Chinese
  content/zh/docs/ops/ambient/usage/_index.md
  content/zh/docs/ops/ambient/usage/install/index.md
  content/zh/docs/ops/ambient/usage/waypoint/index.md
  content/zh/docs/ops/ambient/usage/ztunnel/hbone-packet.png
  content/zh/docs/ops/ambient/usage/ztunnel/index.md
  content/zh/docs/ops/ambient/usage/ztunnel/ztunnel-architecture.png
  content/zh/docs/ops/ambient/usage/ztunnel/ztunnel-datapath-1.png
  content/zh/docs/ops/ambient/usage/ztunnel/ztunnel-hairpin.png
  content/zh/docs/ops/ambient/usage/ztunnel/ztunnel-waypoint-datapath.png
Labels: size/XL, release-notes-none

#14372 [zh] Sync #14362 into Chinese
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: kind/docs, translation/chinese, size/S

#14373 [release-1.20] [zh] Sync #14362 into Chinese
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: size/S, release-notes-none

#14371 [release-1.20] [zh] Sync rest of #13871 into Chinese
  content/zh/docs/ops/ambient/usage/ztunnel/index.md
Labels: size/XS, release-notes-none

#14375 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: size/XS, auto-merge, release-notes-none

#14378 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#14380 Update ist0102 and ist0118
  content/en/docs/reference/config/analysis/ist0102/index.md
  content/en/docs/reference/config/analysis/ist0118/index.md
Labels: kind/docs, size/S

#14365 Add ist0166 message description
  content/en/docs/reference/config/analysis/ist0166/index.md
Labels: kind/docs, size/L

#14384 [zh] Sync istio#14200 into Chinese
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, size/XS, ok-to-test

#14376 [zh] Update text from ist0001 to ist0118
  content/zh/docs/reference/config/analysis/ist0001/index.md
  content/zh/docs/reference/config/analysis/ist0002/index.md
  content/zh/docs/reference/config/analysis/ist0101/index.md
  content/zh/docs/reference/config/analysis/ist0102/index.md
  content/zh/docs/reference/config/analysis/ist0103/index.md
  content/zh/docs/reference/config/analysis/ist0106/index.md
  content/zh/docs/reference/config/analysis/ist0107/index.md
  content/zh/docs/reference/config/analysis/ist0108/index.md
  content/zh/docs/reference/config/analysis/ist0109/index.md
  content/zh/docs/reference/config/analysis/ist0110/index.md
  content/zh/docs/reference/config/analysis/ist0111/index.md
  content/zh/docs/reference/config/analysis/ist0112/index.md
  content/zh/docs/reference/config/analysis/ist0113/index.md
  content/zh/docs/reference/config/analysis/ist0116/index.md
  content/zh/docs/reference/config/analysis/ist0118/index.md
Labels: kind/docs, translation/chinese, size/L

#14389 [zh] Localize ist0166 into Chinese
  content/zh/docs/reference/config/analysis/ist0166/index.md
Labels: kind/docs, translation/chinese, size/L

#14387 Clarify Helm installation chart usage
  content/en/boilerplates/helm-preamble.md
Labels: area/environments, kind/docs, size/XS, ok-to-test

#14390 Remove analysis/ist0119
  content/en/docs/reference/config/analysis/ist0119/index.md
  content/zh/docs/reference/config/analysis/ist0119/index.md
Labels: kind/docs, size/L

#14391 Remove a redundant SVG and update some zh text in deployment/architecture/
  content/en/docs/ops/deployment/architecture/discovery.svg
  content/zh/docs/ops/deployment/architecture/discovery.svg
  content/zh/docs/ops/deployment/architecture/index.md
Labels: kind/docs, size/S

#14394 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#14395 [zh] Sync #14387 into Chinese
  content/zh/boilerplates/helm-preamble.md
Labels: kind/docs, translation/chinese, size/XS

#14393 [release-1.20] Clarify Helm installation chart usage
  content/en/boilerplates/helm-preamble.md
Labels: size/XS, release-notes-none

#14392 [zh] Update text from ist0122 to ist0130
  content/zh/docs/reference/config/analysis/ist0122/index.md
  content/zh/docs/reference/config/analysis/ist0123/index.md
  content/zh/docs/reference/config/analysis/ist0125/index.md
  content/zh/docs/reference/config/analysis/ist0127/index.md
  content/zh/docs/reference/config/analysis/ist0128/index.md
  content/zh/docs/reference/config/analysis/ist0129/index.md
  content/zh/docs/reference/config/analysis/ist0130/index.md
Labels: kind/docs, translation/chinese, size/L

#14388 Fix example in Gateway with TLS termination common problems doc
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: size/XS, ok-to-test

#14396 [release-1.20] Fix example in Gateway with TLS termination common problems doc
  content/en/docs/ops/common-problems/network-issues/index.md
Labels: size/XS, release-notes-none

#14385 Update example of refine the mutual TLS settings per port
  content/en/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, size/XS, ok-to-test

#14397 [zh] Sync #14388 into Chinese with format fix
  content/zh/docs/ops/common-problems/network-issues/index.md
Labels: translation/chinese, size/S

#14399 [zh] Sync with English content remove the useless old ambient install file
  content/zh/docs/ops/ambient/usage/install/index.md
Labels: kind/docs, translation/chinese, size/XS

#14398 [zh] Sync #14385 into Chinese
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, translation/chinese, size/XS

#14401 [zh] Update ist0131 to ist0150
  content/zh/docs/reference/config/analysis/ist0131/index.md
  content/zh/docs/reference/config/analysis/ist0132/index.md
  content/zh/docs/reference/config/analysis/ist0134/index.md
  content/zh/docs/reference/config/analysis/ist0135/index.md
  content/zh/docs/reference/config/analysis/ist0136/index.md
  content/zh/docs/reference/config/analysis/ist0137/index.md
  content/zh/docs/reference/config/analysis/ist0143/index.md
  content/zh/docs/reference/config/analysis/ist0144/index.md
  content/zh/docs/reference/config/analysis/ist0150/index.md
Labels: kind/docs, translation/chinese, size/L
