Repository istio/istio.io, pull requests merged in 2023-02, with the labels that each got.

#12562 [zh] Sync /traffic-management/network-topologies/
  content/zh/docs/ops/configuration/traffic-management/network-topologies/index.md
Labels: kind/docs, translation/chinese, size/M

#12566 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/S, auto-merge, release-notes-none

#12554 Skew policy documentation
  content/en/docs/releases/supported-releases/index.md
Labels: kind/docs, size/XS, ok-to-test

#12574 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12567 [zh] sync files in boilerplates
  content/zh/boilerplates/helm-jwt-warning.md
  content/zh/boilerplates/helm-preamble.md
  content/zh/boilerplates/revision-tags-default-intro.md
  content/zh/boilerplates/revision-tags-middle.md
  content/zh/boilerplates/revision-tags-prologue.md
  content/zh/boilerplates/start-otel-collector-service.md
  content/zh/boilerplates/telemetry-tracing-tips.md
  content/zh/docs/setup/upgrade/canary/revision-tags-after.svg
  content/zh/docs/setup/upgrade/canary/revision-tags-before.svg
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.16

#12568 [zh] sync /examples/microservices-istio/single/
  content/zh/docs/examples/microservices-istio/single/index.md
Labels: kind/docs, translation/chinese, size/M

#12575 [release-1.16] [zh] sync files in boilerplates
  content/zh/boilerplates/helm-jwt-warning.md
  content/zh/boilerplates/helm-preamble.md
  content/zh/boilerplates/revision-tags-default-intro.md
  content/zh/boilerplates/revision-tags-middle.md
  content/zh/boilerplates/revision-tags-prologue.md
  content/zh/boilerplates/start-otel-collector-service.md
  content/zh/boilerplates/telemetry-tracing-tips.md
  content/zh/docs/setup/upgrade/canary/revision-tags-after.svg
  content/zh/docs/setup/upgrade/canary/revision-tags-before.svg
Labels: size/M, release-notes-none

#12569 Add minimal profile for docs test setups
  tests/setup/README.md
  tests/setup/profile_minimal/doc_test.go
Labels: size/M

#12578 [zh] sync /setup/platform-setup/kind/
  content/zh/docs/setup/platform-setup/kind/index.md
Labels: kind/docs, translation/chinese, size/S

#12581 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12486 Update Gateway selector in ingress demo for Helm Installation
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
Labels: area/environments, kind/docs, size/S, ok-to-test

#12579 Relationship between Istio and Envoy
  .spelling
  content/en/docs/releases/supported-releases/index.md
Labels: size/M

#12583 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12584 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#12586 Cherry Pick of 1.16.2 release notes
  content/en/news/releases/1.16.x/announcing-1.16.2/index.md
Labels: kind/docs, size/S

#12589 Fixups for prior PR
  .spelling
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS

#12588 Manual cherry-pick of #12579 (minor corrections to push back)
  .spelling
  content/en/docs/releases/supported-releases/index.md
Labels: size/M

#12594 update current year
  data/args.yml
Labels: size/XS, cherrypick/release-1.16

#12595 [release-1.16] update current year
  data/args.yml
Labels: size/XS, release-notes-none

#12596 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/L, auto-merge, release-notes-none

#12580 2023 Istio Steering Contributor Seats
  .spelling
  content/en/blog/2023/steering-contribution-seat-results/index.md
Labels: size/M, cherrypick/release-1.16

#12597 [release-1.16] 2023 Istio Steering Contributor Seats
  .spelling
  content/en/blog/2023/steering-contribution-seat-results/index.md
Labels: size/M, release-notes-none

#12585 [zh] sync /setup/upgrade/helm/
  content/zh/docs/setup/upgrade/helm/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.16

#12598 [release-1.16] [zh] sync /setup/upgrade/helm/
  content/zh/docs/setup/upgrade/helm/index.md
Labels: size/S, release-notes-none

#12599 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12591 Update istio.io test reference to 1.17.0-beta.2
  go.mod
  go.sum
  tests/util/samples.sh
Labels: size/M

#12544 Flix flakey tcp-traffic-shifting/gateway test
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/test.sh
Labels: size/XS

#12600 Fix script comment
  tests/tests.mk
Labels: size/XS

#12601 gateway-api: fix gateway deployment name
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
Labels: size/XS

#12604 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#12605 [zh] Fix some inaccurate descriptions
  content/zh/docs/concepts/traffic-management/index.md
Labels: kind/docs, translation/chinese, size/S

#12606 [release-1.16] [zh] Fix some inaccurate descriptions
  content/zh/docs/concepts/traffic-management/index.md
Labels: size/S, release-notes-none

#12607 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12564 Optimize doc testing based on PR changes
  prow/integ-suite-kind.sh
  scripts/pr_tests.py
Labels: size/M

#12610 Fix unbound PULL_NUMBER
  prow/integ-suite-kind.sh
Labels: size/XS

#12611 Fix a typo about login and log in
  content/en/docs/setup/platform-setup/kind/index.md
  content/en/docs/tasks/traffic-management/fault-injection/index.md
Labels: kind/docs, size/S

#12613 [zh] Fix some inaccurate or missing translations
  content/zh/docs/concepts/security/index.md
  content/zh/docs/concepts/wasm/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.16

#12615 [release-1.16] [zh] Fix some inaccurate or missing translations
  content/zh/docs/concepts/security/index.md
  content/zh/docs/concepts/wasm/index.md
Labels: size/S, release-notes-none

#12616 [zh] sync /releases/supported-releases/
  content/zh/docs/releases/supported-releases/index.md
Labels: kind/docs, translation/chinese, size/M

#12617 docs: sync content/zh/news/releases/1.4.x/announcing-1.4.10/index.md
  content/zh/news/releases/1.4.x/announcing-1.4.10/index.md
Labels: size/M, ok-to-test

#12619 Update istio test ref to 1.17.0-rc.0
  go.mod
  go.sum
Labels: size/S

#12576 Migrate ingress-sni-passthrough test to minimal profile setup
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/gtwapi_test.sh
  tests/setup/profile_minimal/doc_test.go
Labels: size/S

#12621 [zh] Resync page install/helm
  content/zh/docs/setup/install/helm/index.md
Labels: kind/docs, translation/chinese, size/L, ok-to-test, cherrypick/release-1.16

#12636 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#12639 fix lint
  tests/util/gateway-api.sh
Labels: size/XS

#12638 [zh] sync /about/solutions/
  content/zh/about/solutions/increasing-kubernetes-deployment-and-management-efficiency/index.md
  content/zh/about/solutions/instituting-obeservability-and-sre-best-practices/index.md
Labels: kind/docs, translation/chinese, size/S

#12618 [zh] /security/security-policy-examples/
  content/zh/docs/ops/configuration/security/security-policy-examples/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.16

#12640 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/jwt/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
Labels: size/M, auto-merge, release-notes-none

#12635 [zh] Resync page distributed-tracing/lightstep
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-explorer.png
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-services.png
Labels: kind/docs, size/L, ok-to-test, cherrypick/release-1.16

#12637 Change heading levels in security-policy-examples
  content/en/docs/ops/configuration/security/security-policy-examples/index.md
Labels: kind/docs, size/S

#12645 [release-1.16] fix lint (#12639)
  tests/util/gateway-api.sh
Labels: size/XS

#12643 [release-1.16] Change heading levels in security-policy-examples
  content/en/docs/ops/configuration/security/security-policy-examples/index.md
Labels: size/S, release-notes-none

#12626 Minor tweaks to the DOcker Desktop page
  content/en/docs/setup/platform-setup/docker/index.md
Labels: size/XS

#12627 Minikube setup updates
  content/en/docs/setup/platform-setup/minikube/index.md
Labels: size/XS

#12628 Update Helm install feature status in FAQ
  content/en/about/faq/setup/install-method-selection.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/upgrade/helm/index.md
Labels: size/XS

#12647 Change for consistency with title in claim-to-header
  content/en/docs/tasks/security/authentication/claim-to-header/index.md
Labels: kind/docs, size/S

#12649 Move docs to Gateway API v0.6.1
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/boilerplates/snips/gateway-api-version.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/S

#12652 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12654 Fix test optimzation parameters
  prow/integ-suite-kind.sh
Labels: size/XS

#12650 Termporarily remove the Performance page from the website
  content/en/blog/2019/performance-best-practices/index.md
  content/en/blog/2022/cryptomb-privatekeyprovider/index.md
  content/en/docs/ops/deployment/performance-and-scalability/index.md.disable
  content/en/news/releases/1.1.x/announcing-1.1/_index.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: size/S

#12651 Add missing --set to install command
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
Labels: size/XS

#12656 [zh] sync /news/releases/1.4.x/announcing-1.4/change-notes/index.md
  content/zh/news/releases/1.4.x/announcing-1.4/change-notes/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#12642 docs: Add k3d platform setup
  content/en/docs/setup/platform-setup/k3d/index.md
Labels: kind/docs, size/L, ok-to-test

#12657 [zh] Resync page reference/config/analysis/ist0137
  content/zh/docs/reference/config/analysis/ist0137/index.md
Labels: kind/docs, translation/chinese, size/XS

#12662 Clarify mtls migration policy location
  content/en/docs/tasks/security/authentication/mtls-migration/index.md
  content/en/docs/tasks/security/authentication/mtls-migration/snips.sh
Labels: size/S

#12661 gateway api: ignore error on install CRDs
  content/en/blog/2022/getting-started-gtwapi/index.md
  content/en/boilerplates/gateway-api-install-crds.md
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
Labels: size/S

#12633 Preparing release notes for Istio-release-1.17
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.17.x/_index.md
  content/en/news/releases/1.17.x/announcing-1.17/_index.md
  content/en/news/releases/1.17.x/announcing-1.17/change-notes/index.md
  content/en/news/releases/1.17.x/announcing-1.17/upgrade-notes/index.md
  data/args.yml
Labels: kind/docs, size/L

#12653 Update istio test reference to latest (possible 1.17.0)
  go.mod
  go.sum
Labels: size/XS

#12666 Fix page title
  content/en/news/releases/1.17.x/announcing-1.17/_index.md
Labels: cherrypick/master

#12667 [master] Fix page title
  content/en/news/releases/1.17.x/announcing-1.17/_index.md
Labels: size/XS, release-notes-none

#12646 [zh] sync /security/authentication/claim-to-header/
  content/zh/docs/tasks/security/authentication/claim-to-header/index.md
Labels: kind/docs, translation/chinese, size/L

#12648 [zh] Resync page external-controlplane
  content/zh/docs/setup/install/external-controlplane/index.md
Labels: kind/docs, translation/chinese, size/XL, cherrypick/release-1.17

#12668 [release-1.17] [zh] Resync page external-controlplane
  content/zh/docs/setup/install/external-controlplane/index.md
Labels: size/XL, release-notes-none

#12659 [zh] Resync about/deployment/index.md
  content/zh/about/deployment/index.md
Labels: kind/docs, translation/chinese, size/L

#12669 [zh] sync /distributed-tracing/skywalking/
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/index.md
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/istio-service-list-skywalking.png
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/istio-tracing-list-skywalking.png
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.17

#12671 [release-1.17] [zh] sync /distributed-tracing/skywalking/
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/index.md
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/istio-service-list-skywalking.png
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/istio-tracing-list-skywalking.png
Labels: size/L, release-notes-none

#12670 [zh] Add missing --set to install command
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: translation/chinese, size/XS

#12663 Add warning in 1.15 upgrade notes
  content/en/news/releases/1.15.x/announcing-1.15/upgrade-notes/index.md
Labels: size/S, cherrypick/release-1.17

#12673 [release-1.17] Add warning in 1.15 upgrade notes
  content/en/news/releases/1.15.x/announcing-1.15/upgrade-notes/index.md
Labels: size/S, release-notes-none

#12675 Enable istioctl-analyze
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/test.sh
Labels: size/XS

#12678 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12681 Automator: update common-files@release-1.16 in istio/istio.io@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12682 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12683 Automator: update common-files@release-1.15 in istio/istio.io@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12685 [release-1.17] [zh] Add missing --set to install command
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: size/XS, release-notes-none

#12689 Fix some typos in custom-ca-k8s
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: kind/docs, size/S

#12684 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  data/analysis.yaml
Labels: size/L, auto-merge, release-notes-none

#12691 Fix lint error by updating reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/S

#12690 Add IBM Kubernetes Load Balancer type to table
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
Labels: size/XS

#12692 update support-policy patch statement
  content/en/docs/releases/supported-releases/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.17

#12694 [release-1.17] update support-policy patch statement
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS, release-notes-none

#12686 [zh] sync /distributed-tracing/opencensusagent/
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/index.md
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-details.png
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-list.png
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.17

#12688 [zh] sync /cert-management/custom-ca-k8s/
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.17

#12699 [release-1.17] [zh] sync /distributed-tracing/opencensusagent/
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/index.md
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-details.png
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-list.png
Labels: size/L, release-notes-none

#12701 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#12700 [release-1.17] [zh] sync /cert-management/custom-ca-k8s/
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: size/S, release-notes-none

#12703 Fix some consistency issues in authz-deny
  content/en/docs/tasks/security/authorization/authz-deny/index.md
Labels: kind/docs, size/M, cherrypick/release-1.17

#12704 [release-1.17] Fix some consistency issues in authz-deny
  content/en/docs/tasks/security/authorization/authz-deny/index.md
Labels: size/M, release-notes-none

#12706 Update 1.17 release notes
  content/en/news/releases/1.17.x/announcing-1.17/_index.md
Labels: kind/docs, size/XS, cherrypick/release-1.17

#12707 [release-1.17] Update 1.17 release notes
  content/en/news/releases/1.17.x/announcing-1.17/_index.md
Labels: size/XS, release-notes-none

#12705 Update distroless doc
  content/en/docs/ops/configuration/security/harden-docker-images/index.md
Labels: size/M

#12708 [release-1.17] Update distroless doc
  content/en/docs/ops/configuration/security/harden-docker-images/index.md
Labels: size/M, release-notes-none

#12716 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12717 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/L, auto-merge, release-notes-none

#12696 Add release note for istioctl 1.17 auth plugin removal
  .spelling
  content/en/news/releases/1.17.x/announcing-1.17/change-notes/index.md
  content/en/news/releases/1.17.x/announcing-1.17/upgrade-notes/index.md
Labels: size/XS, cherrypick/release-1.17

#12720 [release-1.17] Add release note for istioctl 1.17 auth plugin removal
  .spelling
  content/en/news/releases/1.17.x/announcing-1.17/change-notes/index.md
  content/en/news/releases/1.17.x/announcing-1.17/upgrade-notes/index.md
Labels: size/XS, release-notes-none

#12722 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/jwt/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/jwt/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
Labels: size/M, auto-merge, release-notes-none

#12718 [zh] Fix the inconsistency between Chinese and English content
  content/zh/docs/concepts/security/authz-eval.png
  content/zh/docs/concepts/security/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.17

#12723 [release-1.17] [zh] Fix the inconsistency between Chinese and English content
  content/zh/docs/concepts/security/authz-eval.png
  content/zh/docs/concepts/security/index.md
Labels: size/S, release-notes-none

#12724 [zh] sync /platform-setup/minikube/
  content/zh/docs/setup/platform-setup/minikube/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.17

#12728 [release-1.17] [zh] sync /platform-setup/minikube/
  content/zh/docs/setup/platform-setup/minikube/index.md
Labels: size/S, release-notes-none

#12702 [zh] sync 2 files in /tasks/security
  content/zh/docs/tasks/security/authorization/authz-deny/index.md
  content/zh/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.17

#12729 [release-1.17] [zh] sync 2 files in /tasks/security
  content/zh/docs/tasks/security/authorization/authz-deny/index.md
  content/zh/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
Labels: size/M, release-notes-none

#12730 Fix troubleshooting multicluster link error
  content/en/docs/ops/diagnostic-tools/multicluster/index.md
Labels: size/XS, cherrypick/release-1.17

#12733 [release-1.17] Fix troubleshooting multicluster link error
  content/en/docs/ops/diagnostic-tools/multicluster/index.md
Labels: size/XS, release-notes-none

#12517 update hugo to 0.110.0
  netlify.toml
Labels: size/XS, cherrypick/release-1.17

#12736 [release-1.17] update hugo to 0.110.0
  netlify.toml
Labels: size/XS, release-notes-none

#12735 Fix cleanup instructions for TLS version config task
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/snips.sh
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/test.sh
Labels: kind/docs, size/S, ok-to-test, cherrypick/release-1.17

#12739 [release-1.17] Fix cleanup instructions for TLS version config task
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/snips.sh
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/test.sh
Labels: size/S, release-notes-none

#12731 [zh] sync /news/releases/1.17x/
  content/zh/news/releases/1.17x/_index.md
  content/zh/news/releases/1.17x/announcing-1.17/_index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.17

#12740 [release-1.17] [zh] sync /news/releases/1.17x/
  content/zh/news/releases/1.17x/_index.md
  content/zh/news/releases/1.17x/announcing-1.17/_index.md
Labels: size/L, release-notes-none

#12741 [zh] sync /workload-min-tls-version/index.md
  content/zh/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
Labels: kind/docs, translation/chinese, size/S

#12732 [zh] sync /security/harden-docker-images/
  content/zh/docs/ops/configuration/security/harden-docker-images/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.17

#12742 [release-1.17] [zh] sync /security/harden-docker-images/
  content/zh/docs/ops/configuration/security/harden-docker-images/index.md
Labels: size/M, release-notes-none

#12747 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12737 1.15.6 Release notes
  content/en/news/releases/1.15.x/announcing-1.15.6/index.md
Labels: kind/docs, size/S, cherrypick/release-1.17

#12738 1.16.3 release notes
  content/en/news/releases/1.16.x/announcing-1.16.3/index.md
Labels: kind/docs, size/M, cherrypick/release-1.17

#12749 [release-1.17] 1.16.3 release notes
  content/en/news/releases/1.16.x/announcing-1.16.3/index.md
Labels: size/M, release-notes-none

#12711 [release-1.16] Reference doc update for 1.16.3
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/L

#12748 [release-1.17] 1.15.6 Release notes
  content/en/news/releases/1.15.x/announcing-1.15.6/index.md
Labels: size/S, release-notes-none

#12745 [zh] sync /1.17x/announcing-1.17/upgrade-notes/
  content/zh/news/releases/1.17x/announcing-1.17/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.17

#12750 [release-1.17] [zh] sync /1.17x/announcing-1.17/upgrade-notes/
  content/zh/news/releases/1.17x/announcing-1.17/upgrade-notes/index.md
Labels: size/S, release-notes-none

#12751 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/M, auto-merge, release-notes-none

#12756 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12753 [zh] sync traffic-management/traffic-shifting
  content/zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.17

#12758 [release-1.17] [zh] sync traffic-management/traffic-shifting
  content/zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: size/L, release-notes-none

#12760 Add (blank) ambient stub pages
  content/en/docs/ops/ambient/_index.md
  content/en/docs/ops/ambient/architecture/index.md
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/usage/index.md
Labels: size/M

#12762 Automator: update istio.io@ reference docs
  data/features.yaml
Labels: size/S, auto-merge, release-notes-none

#12763 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#12754 [zh] sync /traffic-management/tcp-traffic-shifting/
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.17

#12755 [zh] sync /traffic-management/ingress/gateway-api/
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.17

#12766 [release-1.17] [zh] sync /traffic-management/tcp-traffic-shifting/
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: size/L, release-notes-none

#12767 [release-1.17] [zh] sync /traffic-management/ingress/gateway-api/
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/L, release-notes-none

#12744 Add IST0158 message description
  content/en/docs/reference/config/analysis/ist0158/index.md
Labels: size/S

#12769 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#12761 Add instructions to set global_downstream_max_connections
  .spelling
  content/en/docs/ops/best-practices/security/index.md
Labels: area/environments, kind/docs, size/S, ok-to-test

#12712 [release-1.15] Update reference docs for 1.15.6
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M

#12726 Release notes for 1.17.1
  .spelling
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/news/releases/1.17.x/announcing-1.17.1/index.md
  data/args.yml
Labels: size/M

#12714 [release-1.16] Update istio test reference for 1.16.3
  go.mod
  go.sum
Labels: size/S

#12713 [release-1.15] Update istio test reference for 1.15.6
  go.mod
  go.sum
Labels: size/S
