Repository istio/istio.io, pull requests merged in 2023-08, with the labels that each got.

#13671 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/S, auto-merge, release-notes-none

#13672 Update the CFP banner
  .spelling
  content/en/events/banners/istioday-cfp-2023.md
Labels: size/XS, cherrypick/release-1.18

#13673 [release-1.18] Update the CFP banner
  .spelling
  content/en/events/banners/istioday-cfp-2023.md
Labels: size/XS, release-notes-none

#13670 Updating Pomerium
  data/companies.yml
Labels: kind/docs, size/XS, ok-to-test

#13675 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#13676 fix typo in traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#13679 Automator: update common-files@release-1.17 in istio/istio.io@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13681 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#13678 update typo
  content/zh/about/faq/setup/install-method-selection.md
  content/zh/blog/2017/0.1-using-network-policy/index.md
  content/zh/docs/concepts/security/index.md
  content/zh/docs/concepts/traffic-management/index.md
  content/zh/docs/ops/best-practices/observability/index.md
  content/zh/docs/reference/config/analysis/ist0144/index.md
  content/zh/docs/releases/contribute/style-guide/index.md
  content/zh/news/releases/1.12.x/announcing-1.12/change-notes/index.md
Labels: kind/docs, translation/chinese, size/M

#13683 Automator: update common-files@release-1.18 in istio/istio.io@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13684 [zh] sync external-controlplane
  content/zh/docs/setup/install/external-controlplane/index.md
Labels: translation/chinese, size/L

#13686 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#13689 [zh] sync loadbalancers
  content/zh/docs/ops/integrations/loadbalancers/index.md
Labels: kind/docs, translation/chinese

#13687 [zh] sync /reference/glossary
  content/zh/docs/reference/glossary/index.md
Labels: kind/docs, translation/chinese

#13693 Fix a spelling error
  content/en/docs/setup/upgrade/_index.md
Labels: size/XS

#13694 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/XL, auto-merge, release-notes-none

#13691 prepare for v1.19 as istio source is already branched
  Makefile.core.mk
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  data/args.yml
  go.mod
  go.sum
Labels: size/L

#13696 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/XL, auto-merge, release-notes-none

#13697 [zh] sync observability/logs/* zipkin
  content/zh/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/zh/docs/tasks/observability/logs/access-log/index.md
  content/zh/docs/tasks/observability/logs/otel-provider/index.md
  content/zh/docs/tasks/observability/logs/telemetry-api/index.md
Labels: translation/chinese, size/L

#13690 [zh] sync tcp-metrics querying-metrics customize-metrics
  content/zh/docs/tasks/observability/metrics/customize-metrics/index.md
  content/zh/docs/tasks/observability/metrics/querying-metrics/index.md
  content/zh/docs/tasks/observability/metrics/tcp-metrics/index.md
Labels: kind/docs, translation/chinese

#13695 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#13378 add dlb blog
  .spelling
  content/en/blog/2023/dlb-connection-balancing/index.md
Labels: size/L

#13701 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13702 Mention that Ambient CNI support is limited ATM
  content/en/docs/ops/ambient/getting-started/index.md
Labels: size/XS

#13703 [release-1.18] Mention that Ambient CNI support is limited ATM
  content/en/docs/ops/ambient/getting-started/index.md
Labels: size/XS, release-notes-none

#13699 [zh] sycn observability/gateways
  content/zh/docs/tasks/observability/gateways/index.md
Labels: kind/docs, translation/chinese, size/L

#13705 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#13706 [release-1.18] add dlb blog
  .spelling
  content/en/blog/2023/dlb-connection-balancing/index.md
Labels: size/L, release-notes-none

#13708 [release-1.18] Correct date in DLB blog post
  content/en/blog/2023/dlb-connection-balancing/index.md
Labels: size/XS, release-notes-none

#13713 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
Labels: size/M, auto-merge, release-notes-none

#13714 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#13716 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#13718 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13704 [zh] sync blog: 2023/dlb-connection-balancing/
  content/zh/blog/2023/dlb-connection-balancing/index.md
Labels: translation/chinese, size/L

#13692 Add reference to a page with more details.
  content/en/docs/ops/deployment/requirements/index.md
Labels: size/XS

#13721 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#13722 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#13723 [zh] sync traffic-management/dns-proxy protocol-selection network-topologies
  content/zh/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/zh/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/zh/docs/ops/configuration/traffic-management/protocol-selection/index.md
Labels: translation/chinese, size/L

#13724 [zh] Sync #13692 to the Chinese version
  content/zh/docs/ops/deployment/requirements/index.md
Labels: kind/docs, translation/chinese, size/XS

#13666 [zh] update /setup/platform-setup docs
  content/zh/docs/setup/platform-setup/MicroK8s/index.md
  content/zh/docs/setup/platform-setup/alicloud/index.md
  content/zh/docs/setup/platform-setup/docker/index.md
  content/zh/docs/setup/platform-setup/gardener/index.md
  content/zh/docs/setup/platform-setup/gke/index.md
  content/zh/docs/setup/platform-setup/huaweicloud/index.md
  content/zh/docs/setup/platform-setup/k3d/index.md
  content/zh/docs/setup/platform-setup/kops/index.md
  content/zh/docs/setup/platform-setup/kubesphere/index.md
  content/zh/docs/setup/platform-setup/oci/index.md
Labels: kind/docs, translation/chinese, size/L

#13729 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#13719 Add the Ambient Profile to the Installation Configuration Profiles Table
  content/en/boilerplates/ambient-alpha-warning.md
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
Labels: kind/docs, size/M

#13731 [release-1.18] Blog: Native Sidecars
  content/en/blog/2023/native-sidecars/index.md
Labels: size/L, release-notes-none

#13727 [zh] sync install/virtual-machine in-place
  content/zh/docs/setup/install/virtual-machine/index.md
  content/zh/docs/setup/upgrade/in-place/index.md
Labels: kind/docs, translation/chinese, size/L

#13734 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13735 gateway-api: Service parentRef needs to specify core group
  content/en/docs/ops/ambient/architecture/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/request-routing/index.md
  content/en/docs/tasks/traffic-management/request-routing/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  content/zh/docs/ops/ambient/architecture/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/request-routing/index.md
  content/zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: size/M, cherrypick/release-1.18

#13739 [release-1.18] gateway-api: Service parentRef needs to specify core group
  content/en/docs/ops/ambient/architecture/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/request-routing/index.md
  content/en/docs/tasks/traffic-management/request-routing/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  content/zh/docs/ops/ambient/architecture/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/request-routing/index.md
  content/zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: size/M, release-notes-none

#13736 2023 Steering Election Results
  content/en/blog/2023/steering-election-results/index.md
Labels: size/S, cherrypick/release-1.18

#13741 [release-1.18] 2023 Steering Election Results
  content/en/blog/2023/steering-election-results/index.md
Labels: size/S, release-notes-none

#13733 [zh] Sync #13719 into Chinese with some fixes and improvements
  content/zh/boilerplates/ambient-alpha-warning.md
  content/zh/docs/ops/ambient/architecture/index.md
  content/zh/docs/ops/ambient/getting-started/index.md
  content/zh/docs/ops/best-practices/image-signing-validation/index.md
  content/zh/docs/ops/best-practices/observability/index.md
  content/zh/docs/setup/additional-setup/config-profiles/index.md
  content/zh/docs/setup/additional-setup/customize-installation/index.md
  content/zh/docs/setup/additional-setup/pod-security-admission/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: kind/docs, translation/chinese, size/L

#13732 [zh] Sync Kubernetes Native Sidecar in Istio blog into Chinese
  content/zh/blog/2023/native-sidecars/index.md
Labels: kind/docs, translation/chinese, size/L

#13746 update d2iq company logo
  static/logos/d2iq.svg
Labels: size/XS

#13748 [release-1.18] update d2iq company logo
  static/logos/d2iq.svg
Labels: size/XS, release-notes-none

#13730 Analysis message for IST0157
  content/en/docs/reference/config/analysis/ist0157/index.md
Labels: size/XS, cherrypick/release-1.18

#13751 [release-1.18] Analysis message for IST0157
  content/en/docs/reference/config/analysis/ist0157/index.md
Labels: size/XS, release-notes-none

#13754 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/XL, auto-merge, release-notes-none

#13758 [zh] Fix typo and improve format for case study part
  content/zh/about/case-studies/autotrader/index.md
  content/zh/about/case-studies/bol.com/index.md
  content/zh/about/case-studies/splunk/index.md
  content/zh/about/case-studies/wp-engine/index.md
Labels: translation/chinese, size/L

#13759 [zh] Fix a left typo and improve content format
  content/zh/about/case-studies/airbnb/index.md
  content/zh/about/case-studies/atlassian/index.md
  content/zh/about/case-studies/cash-app/index.md
  content/zh/about/case-studies/ebay/index.md
  content/zh/about/case-studies/fico/index.md
  content/zh/about/case-studies/salesforce/index.md
  content/zh/about/case-studies/t-mobile/index.md
  content/zh/about/case-studies/zozo/index.md
  content/zh/about/community/join/index.md
  content/zh/about/deployment/index.md
  content/zh/about/faq/distributed-tracing/how-distributed-tracing-works.md
Labels: kind/docs, translation/chinese, size/L

#13760 [zh] Sync #13730 into Chinese
  content/zh/docs/reference/config/analysis/ist0157/index.md
Labels: kind/docs, translation/chinese, size/XS

#13755 Remove 7 zh files that not exist in en upstream currently
  content/zh/about/case-studies/redhat/index.md
  content/zh/about/case-studies/vmware/index.md
  content/zh/about/community/_index.md
  content/zh/about/faq/security/accessing-non-istio-services.md
  content/zh/boilerplates/helm-security-warning.md
Labels: translation/chinese, size/M, ok-to-test

#13762 Fix broken link
  content/en/docs/concepts/traffic-management/index.md
Labels: size/XS

#13763 [release-1.18] Fix broken link
  content/en/docs/concepts/traffic-management/index.md
Labels: size/XS, release-notes-none

#13761 [zh] improve tencent-cloud-mesh prerequisites
  content/zh/docs/setup/platform-setup/prerequisites/index.md
  content/zh/docs/setup/platform-setup/tencent-cloud-mesh/index.md
Labels: kind/docs, translation/chinese, size/M

#13768 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13740 perf data for istio 1.19
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_without_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_without_jitter.svg
Labels: area/perf and scalability, kind/docs, size/XXL

#13766 [zh] Sync broken link fix #13762 into Chinese
  content/zh/docs/concepts/traffic-management/index.md
  content/zh/docs/ops/common-problems/network-issues/index.md
Labels: kind/docs, translation/chinese, size/XS

#13771 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13765 update intel company logo
  static/logos/intel.svg
Labels: area/user experience, size/M, cherrypick/release-1.18

#13738 Release 1.18 performance data
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_without_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
  content/en/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_without_jitter.svg
Labels: area/perf and scalability, kind/docs, size/XXL

#13767 [zh] sync /tasks/observability/metrics/telemetry-api
  content/zh/docs/tasks/observability/metrics/telemetry-api/index.md
Labels: kind/docs, translation/chinese, size/XS

#13770 [zh] sync deployment/performance-and-scalability
  content/zh/docs/ops/deployment/performance-and-scalability/index.md
  content/zh/docs/ops/deployment/performance-and-scalability/latency_p90_fortio_with_jitter.svg
  content/zh/docs/ops/deployment/performance-and-scalability/latency_p99_fortio_with_jitter.svg
Labels: kind/docs, translation/chinese, size/XXL

#13776 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/workload-entry/index.html
  content/zh/docs/reference/config/networking/workload-entry/index.html
Labels: size/M, auto-merge, release-notes-none

#13769 Update to istio 1.19.0-rc.0 + samples fix
  Makefile.core.mk
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/ops/configuration/telemetry/envoy-stats/test.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/L

#13781 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13785 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#13782 gateway-api: doc tests should not run with alpha CRDs by default
  content/en/boilerplates/gateway-api-experimental.md
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
  content/en/docs/tasks/traffic-management/egress/egress-kubernetes-services/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh
  tests/setup/profile-default/doc_test.go
  tests/setup/profile-demo/doc_test.go
  tests/setup/profile-minimal/doc_test.go
Labels: size/M

#13787 update zh docs info
  content/zh/docs/concepts/security/index.md
  content/zh/docs/concepts/traffic-management/index.md
  content/zh/docs/examples/bookinfo/index.md
Labels: kind/docs, translation/chinese, size/S, ok-to-test

#13794 Update GAMMA status
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XS

#13796 Fix Inconsistently Sized Company Logos
  layouts/partials/company_logo.html
  src/sass/base/_base.scss
  src/sass/misc/_logo-gallery.scss
  static/logos/google-cloud.png
  static/logos/mulesoft.svg
  static/logos/tencent-cloud.svg
  static/logos/tetrate.svg
Labels: kind/docs, size/L

#13798 gateway-api: improve mesh warning messages
  content/en/boilerplates/gateway-api-gamma-support.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/S
