Repository istio/istio.io, pull requests merged in 2024-11, with the labels that each got.

#15854 [zh] Sync #15849 supported versions for 1.24 into Chinese
  content/zh/docs/releases/supported-releases/index.md
Labels: translation/chinese, size/XS

#15855 [zh] Sync #15850 blog attribution into Chinese
  content/zh/blog/2024/ambient-vs-cilium/index.md
Labels: kind/docs, translation/chinese, size/XS

#15834 1.23.3 Release notes
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.23.x/announcing-1.23.3/index.md
  data/args.yml
  go.mod
  go.sum
Labels: size/L, do-not-merge/hold

#15827 1.23.3 Release Notes
  content/en/news/releases/1.23.x/announcing-1.23.3/index.md
Labels: size/S

#15858 [zh] Sync 1.23.3 release notes into Chinese
  content/zh/news/releases/1.23.x/announcing-1.23.3/index.md
Labels: translation/chinese, size/S

#15862 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15861 [release-1.23] Manual backport 1.23-relevant parts of #15744
  content/en/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/en/docs/ops/configuration/traffic-management/network-topologies/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/opentelemetry/http_test.sh
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/logs/otel-provider/index.md
  content/en/docs/tasks/observability/logs/otel-provider/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/index.md
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/index.md
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/index.md
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/test.sh
  content/en/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/en/docs/tasks/traffic-management/egress/http-proxy/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/snips.sh
  content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/test.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/snips.sh
Labels: kind/docs, size/L

#15847 Add details about auto_san_validation behavior
  content/en/boilerplates/auto-san-validation.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
Labels: kind/docs, size/S

#15857 Blog - Istio sessions at Kubecon NA 2024
  .spelling
  content/en/blog/2024/kubecon-na/index.md
  content/en/blog/2024/kubecon-na/kubecon-na.png
Labels: kind/docs, size/M, cherrypick/release-1.23

#15863 [release-1.23] Blog - Istio sessions at Kubecon NA 2024
  .spelling
  content/en/blog/2024/kubecon-na/index.md
  content/en/blog/2024/kubecon-na/kubecon-na.png
Labels: size/M, release-notes-none

#15864 [release-1.23] Add details about auto_san_validation behavior
  content/en/boilerplates/auto-san-validation.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
Labels: size/S, release-notes-none

#15851 Initial 1.24.0 release notes
  .spelling
  content/en/_index.html
  content/en/news/releases/1.24.x/_index.md
  content/en/news/releases/1.24.x/announcing-1.24/_index.md
  content/en/news/releases/1.24.x/announcing-1.24/change-notes/index.md
  content/en/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: size/L

#15727 1.24 performance updates
  content/en/docs/ops/deployment/performance-and-scalability/index.md
  content/en/docs/ops/deployment/performance-and-scalability/istio-1.22.0-fortio-90.png
  content/en/docs/ops/deployment/performance-and-scalability/istio-1.22.0-fortio-99.png
  content/en/docs/ops/deployment/performance-and-scalability/istio-1.24.0-fortio-90.png
  content/en/docs/ops/deployment/performance-and-scalability/istio-1.24.0-fortio-99.png
Labels: area/perf and scalability, size/M, area/ambient, cherrypick/release-1.24

#15871 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15868 [zh] Sync 1.24 announcing into Chinese
  content/zh/_index.html
  content/zh/news/releases/1.23.x/announcing-1.23/_index.md
  content/zh/news/releases/1.24.x/_index.md
  content/zh/news/releases/1.24.x/announcing-1.24/_index.md
Labels: kind/docs, translation/chinese, size/L

#15865 [zh] Sync Istio sessions at Kubecon NA 2024 blog into Chinese
  content/zh/blog/2024/kubecon-na/index.md
  content/zh/blog/2024/kubecon-na/kubecon-na.png
Labels: kind/docs, translation/chinese, size/M

#15866 [zh] Sync #15847 details about auto_san_validation behavior into Chinese
  content/zh/boilerplates/auto-san-validation.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
Labels: kind/docs, translation/chinese, size/S

#15874 Fix the blog link typo in 1.24 announcement
  content/en/news/releases/1.24.x/announcing-1.24/_index.md
Labels: kind/docs, size/XS

#15877 Add new load balancing algorithms
  .spelling
  content/en/docs/concepts/traffic-management/index.md
Labels: size/XS

#15880 Update reference doc updater
  scripts/grab_reference_docs.sh
Labels: size/XS

#15701 Add note on Gateway API Manual Deployment and Policy Attachment
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: area/networking, size/XS

#15879 update feature status for ambient
  content/en/docs/overview/dataplane-modes/index.md
  content/en/docs/releases/feature-stages/index.md
  data/features.yaml
  layouts/shortcodes/features.html
Labels: size/L

#15881 ambient ga blog
  .spelling
  content/en/_index.html
  content/en/blog/2024/ambient-reaches-ga/index.md
  content/en/blog/2024/ambient-reaches-ga/ztunnel-image.png
  content/en/news/releases/1.24.x/announcing-1.24/_index.md
Labels: kind/docs, size/L, area/ambient

#15883 Copy edits for ambient launch blogs
  content/en/blog/2022/ambient-security/index.md
  content/en/blog/2022/introducing-ambient-mesh/index.md
Labels: size/M

#15873 Fix formatting issue in crd-upgrade-123.md
  content/en/boilerplates/crd-upgrade-123.md
  content/uk/boilerplates/crd-upgrade-123.md
  content/zh/boilerplates/crd-upgrade-123.md
Labels: kind/docs, size/M, ok-to-test

#15736 Correct ztunnel-config command
  content/en/docs/ambient/usage/troubleshoot-waypoint/index.md
Labels: kind/docs, size/XS, ok-to-test, area/ambient

#15893 fix last name typo in the ga blog
  content/en/blog/2024/ambient-reaches-ga/index.md
Labels: kind/docs, size/XS, area/ambient

#15894 Update our company logo
  content/en/_index.html
  data/companies.yml
  static/logos/gloo.svg
  static/logos/solo.svg
Labels: kind/docs, size/S, cherrypick/release-1.23

#15896 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15899 Bump reference docs back to master
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/proxy-config/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/networking/workload-entry/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/en/docs/reference/config/type/workload-selector/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/proxy-config/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/networking/workload-entry/index.html
  content/zh/docs/reference/config/networking/workload-group/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/type/workload-selector/index.html
  data/features.yaml
Labels: size/XXL

#15897 1.24.0 release note updates
  content/en/news/releases/1.24.x/announcing-1.24/_index.md
  content/en/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: size/S, cherrypick/release-1.24

#15890 [uk] Update Ukrainian documentation for ambient mode and related features
  content/uk/_index.html
  content/uk/blog/2024/ambient-reaches-ga/index.md
  content/uk/blog/2024/ambient-reaches-ga/ztunnel-image.png
  content/uk/docs/ambient/usage/troubleshoot-waypoint/index.md
  content/uk/docs/concepts/traffic-management/index.md
  content/uk/docs/overview/dataplane-modes/index.md
  content/uk/docs/releases/feature-stages/index.md
  content/uk/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/uk/news/releases/1.24.x/announcing-1.24/_index.md
Labels: size/L, ok-to-test, cherrypick/release-1.24

#15892 Fix doc link typo for Ambient GA blog
  content/en/blog/2024/ambient-reaches-ga/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.24

#15869 [zh] Sync 1.24 change notes into Chinese
  content/zh/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15870 [zh] Sync 1.24 upgrade notes into Chinese
  content/zh/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15872 [zh] Sync #15727 1.24 performance updates into Chinese
  content/zh/docs/ops/deployment/performance-and-scalability/index.md
  content/zh/docs/ops/deployment/performance-and-scalability/istio-1.22.0-fortio-90.png
  content/zh/docs/ops/deployment/performance-and-scalability/istio-1.22.0-fortio-99.png
  content/zh/docs/ops/deployment/performance-and-scalability/istio-1.24.0-fortio-90.png
  content/zh/docs/ops/deployment/performance-and-scalability/istio-1.24.0-fortio-99.png
Labels: kind/docs, translation/chinese, size/M

#15882 [zh] Sync #15877 add new load balancing algorithms into Chinese
  content/zh/docs/concepts/traffic-management/index.md
Labels: translation/chinese, size/XS

#15885 [zh] Sync #15701 add note on Gateway API Manual Deployment and Policy Attachment Chinese
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: kind/docs, translation/chinese, size/XS

#15900 [release-1.24] 1.24.0 release note updates
  content/en/news/releases/1.24.x/announcing-1.24/_index.md
  content/en/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: size/S, release-notes-none

#15901 [release-1.24] Fix doc link typo for Ambient GA blog
  content/en/blog/2024/ambient-reaches-ga/index.md
Labels: size/XS, release-notes-none

#15902 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
Labels: size/M, auto-merge, release-notes-none

#15903 [zh] Sync #15897 1.24.0 release note updates into Chinese
  content/zh/news/releases/1.24.x/announcing-1.24/_index.md
  content/zh/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: kind/docs, translation/chinese, size/S

#15889 [zh] Sync #15736 correct ztunnel-config command into Chinese
  content/zh/docs/ambient/usage/troubleshoot-waypoint/index.md
Labels: kind/docs, translation/chinese, size/XS

#15887 [zh] Sync Ambient mode GA blog into Chinese
  content/zh/_index.html
  content/zh/blog/2024/ambient-reaches-ga/index.md
  content/zh/blog/2024/ambient-reaches-ga/ztunnel-image.png
  content/zh/news/releases/1.24.x/announcing-1.24/_index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.24

#15905 [release-1.24] [zh] Sync Ambient mode GA blog into Chinese
  content/zh/_index.html
  content/zh/blog/2024/ambient-reaches-ga/index.md
  content/zh/blog/2024/ambient-reaches-ga/ztunnel-image.png
  content/zh/news/releases/1.24.x/announcing-1.24/_index.md
Labels: size/L, release-notes-none

#15888 [zh] Sync #15883 copy edits for ambient launch blogs into Chinese
  content/zh/blog/2022/ambient-security/index.md
  content/zh/blog/2022/introducing-ambient-mesh/index.md
Labels: kind/docs, translation/chinese, size/L

#15908 [zh]sync latest-release.md
  content/zh/events/banners/latest-release.md
Labels: translation/chinese, size/XS, release-notes-none

#15898 update kind node image version and point go.mod to master
  go.mod
  go.sum
  prow/config/default.yaml
  prow/integ-suite-kind.sh
Labels: size/M

#15910 Add some missed upgrade notes
  content/en/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: size/M, release-notes-none, cherrypick/release-1.24

#15912 [release-1.24] Add some missed upgrade notes
  content/en/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: size/M, release-notes-none

#15914 [zh]sync #15912 pull request
  content/zh/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: translation/chinese, size/M

#15916 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15913 removed istioctl profile cmd references (en)
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: kind/docs, size/M, ok-to-test

#15919 [zh] Sync #15913 remove istioctl profile cmd references into Chinese
  content/zh/docs/setup/additional-setup/config-profiles/index.md
  content/zh/docs/setup/additional-setup/customize-installation/index.md
  content/zh/docs/setup/install/istioctl/index.md
Labels: kind/docs, translation/chinese, size/L

#15918 add alauda logo because we provide istio
  data/companies.yml
  static/logos/alauda-logo.png
Labels: kind/docs, size/XS, ok-to-test

#15920 [release-1.24] add alauda logo because we provide istio
  data/companies.yml
  static/logos/alauda-logo.png
Labels: size/XS, release-notes-none

#15922 Include platform details while installing ztunnel on OpenShift
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: size/S, cherrypick/release-1.24

#15904 Add encoding to RSS feed
  layouts/blog/rss.xml
  layouts/news/rss.xml
  layouts/rss.xml
Labels: size/XS, cherrypick/release-1.24

#15925 [release-1.24] Add encoding to RSS feed
  layouts/blog/rss.xml
  layouts/news/rss.xml
  layouts/rss.xml
Labels: size/XS, release-notes-none

#15921 Unveil the Istio Phippy Book
  .spelling
  content/en/blog/2024/istio-phippy-book/book_cover.png
  content/en/blog/2024/istio-phippy-book/index.md
  content/en/blog/2024/istio-phippy-book/phippy_and_family.png
Labels: size/M, cherrypick/release-1.24

#15924 [release-1.24] Include platform details while installing ztunnel on OpenShift
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: size/S, release-notes-none

#15926 [zh] Sync #15922 platform details while installing ztunnel on OpenShift into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: translation/chinese, size/S

#15928 [zh] Sync Istio Phippy book blog into Chinese
  content/zh/blog/2024/istio-phippy-book/book_cover.png
  content/zh/blog/2024/istio-phippy-book/index.md
  content/zh/blog/2024/istio-phippy-book/phippy_and_family.png
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.24

#15923 add a remote cluster check step to "verify the installation" multicluster setup docs
  content/en/docs/setup/install/multicluster/common.sh
  content/en/docs/setup/install/multicluster/verify/index.md
  content/en/docs/setup/install/multicluster/verify/snips.sh
Labels: kind/docs, size/M, ok-to-test

#15927 [release-1.24] Unveil the Istio Phippy Book
  .spelling
  content/en/blog/2024/istio-phippy-book/book_cover.png
  content/en/blog/2024/istio-phippy-book/index.md
  content/en/blog/2024/istio-phippy-book/phippy_and_family.png
Labels: size/M, release-notes-none

#15930 Fix FAQ in Ukrainian doesn't work as expected
  src/ts/events.ts
Labels: kind/docs, size/XS, cherrypick/release-1.24

#15932 [release-1.24] Fix FAQ in Ukrainian doesn't work as expected
  src/ts/events.ts
Labels: size/XS, release-notes-none

#15933 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/labels/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/labels/index.html
Labels: size/M, auto-merge, release-notes-none

#15937 [release-1.24] Fix annotation name in release notes
  content/en/news/releases/1.24.x/announcing-1.24/change-notes/index.md
  content/uk/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: size/XS, release-notes-none

#15931 Document DNS Auto Allocation Version 2
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
Labels: kind/docs, size/L, cherrypick/release-1.24

#15939 [release-1.24] Document DNS Auto Allocation Version 2
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
Labels: size/L, release-notes-none

#15940 Fixup quote in release notes
  content/en/news/releases/1.24.x/announcing-1.24/change-notes/index.md
  content/uk/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.24

#15942 [release-1.24] Fixup quote in release notes
  content/en/news/releases/1.24.x/announcing-1.24/change-notes/index.md
  content/uk/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: size/XS, release-notes-none

#15943 [zh] Sync #15936 fix annotation name in release notes into Chinese
  content/zh/news/releases/1.24.x/announcing-1.24/change-notes/index.md
Labels: kind/docs, translation/chinese, size/XS

#15944 remove reference to MetalLB in Kind related Docs
  content/en/docs/setup/platform-setup/kind/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.24

#15945 [release-1.24] remove reference to MetalLB in Kind related Docs
  content/en/docs/setup/platform-setup/kind/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: size/XS, release-notes-none

#15947 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15934 [zh] Sync #15923 add a remote cluster check step to "verify the installation" multicluster setup docs into Chinese
  content/zh/docs/setup/install/multicluster/verify/index.md
Labels: kind/docs, translation/chinese, size/S

#15941 [zh] Sync #15931 DNS Auto Allocation Version 2 into Chinese
  content/zh/docs/ops/configuration/traffic-management/dns-proxy/index.md
Labels: kind/docs, translation/chinese, size/L

#15946 [zh] Sync #15944 remove reference to MetalLB in kind related docs into Chinese
  content/zh/docs/setup/platform-setup/kind/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: kind/docs, translation/chinese, size/S

#15949 Clarify API support in waypoint
  content/en/docs/ambient/usage/l7-features/index.md
Labels: size/XS, release-notes-none, cherrypick/release-1.24

#15950 [release-1.24] Clarify API support in waypoint
  content/en/docs/ambient/usage/l7-features/index.md
Labels: size/XS, release-notes-none

#15948 [zh] update some zh text in ingress-control
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: kind/docs, translation/chinese, size/L

#15938 fix header arrow
  src/icons/dropdown-arrow.svg
Labels: size/XS, cherrypick/release-1.24

#15954 [release-1.24] fix header arrow
  src/icons/dropdown-arrow.svg
Labels: size/XS, release-notes-none

#15955 disable authz-tcp test
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: size/XS

#15956 [release-1.24] disable authz-tcp test
  content/en/docs/tasks/security/authorization/authz-tcp/index.md
Labels: size/XS, release-notes-none

#15958 fix telemetry test
  content/en/docs/tasks/observability/metrics/telemetry-api/index.md
  content/en/docs/tasks/observability/metrics/telemetry-api/snips.sh
Labels: size/XS

#15953 [zh] Sync #15949 clarify API support in waypoint into Chinese
  content/zh/docs/ambient/usage/l7-features/index.md
Labels: kind/docs, translation/chinese, size/XS

#15962 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/labels/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/config/labels/index.html
Labels: size/L, auto-merge, release-notes-none

#15959 Manually update test reference and disable authz-test
  content/en/docs/tasks/security/authorization/authz-tcp/test_disabled.sh
  go.mod
  go.sum
Labels: size/S

#15965 update peer metadata
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: size/S, cherrypick/release-1.24

#15966 [release-1.24] update peer metadata
  content/en/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: size/S, release-notes-none

#15907 Fix revision in uninstall previous control plane
  content/en/docs/ambient/upgrade/helm/index.md
  content/en/docs/ambient/upgrade/helm/revision_test.sh
  content/en/docs/ambient/upgrade/helm/snips.sh
  content/uk/docs/ambient/upgrade/helm/index.md
  content/zh/docs/ambient/upgrade/helm/index.md
Labels: size/S, cherrypick/release-1.24

#15969 [release-1.24] removed istioctl profile cmd references (en)
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: size/M, release-notes-none

#15972 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
Labels: size/XS, auto-merge, release-notes-none

#15968 [release-1.24] Fix revision in uninstall previous control plane
  content/en/docs/ambient/upgrade/helm/index.md
  content/en/docs/ambient/upgrade/helm/revision_test.sh
  content/en/docs/ambient/upgrade/helm/snips.sh
  content/uk/docs/ambient/upgrade/helm/index.md
  content/zh/docs/ambient/upgrade/helm/index.md
Labels: size/S, release-notes-none

#15961 [zh] Sync disable authz-tcp test and fix telemetry test into Chinese
  content/zh/docs/tasks/observability/metrics/telemetry-api/index.md
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
Labels: kind/docs, translation/chinese, size/XS

#15967 update ttl for proxy dns resolution
  content/en/docs/ops/configuration/traffic-management/dns/index.md
Labels: size/XS, ok-to-test

#15970 fix istioctl profiles links
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
Labels: cherrypick/release-1.24

#15974 [release-1.24] fix istioctl profiles links
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
Labels: size/XS, release-notes-none

#15977 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/L, auto-merge, release-notes-none

#15973 [zh] Sync #15965 update peer metadata into Chinese
  content/zh/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: kind/docs, translation/chinese, size/S

#15975 [zh] Sync #15967 update ttl for proxy dns resolution into Chinese
  content/zh/docs/ops/configuration/traffic-management/dns/index.md
Labels: kind/docs, translation/chinese, size/XS

#15976 [zh] Sync #15970 fix istioctl profiles links into Chinese
  content/zh/docs/setup/additional-setup/config-profiles/index.md
  content/zh/docs/setup/additional-setup/customize-installation/index.md
Labels: kind/docs, translation/chinese, size/XS

#15981 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15983 [zh] Sync multicluster multi-primary doc updates into Chinese
  content/zh/docs/setup/install/multicluster/before-you-begin/index.md
  content/zh/docs/setup/install/multicluster/multi-primary/index.md
Labels: kind/docs, translation/chinese, size/L

#15985 [zh] Sync multicluster primary-remote doc updates into Chinese
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
Labels: kind/docs, translation/chinese, size/L

#15986 [zh] Sync multicluster primary-remote multi network doc updates into Chinese
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: kind/docs, translation/chinese, size/L

#15960 [uk] sync fixes for 1.24 with upstream
  content/uk/blog/2024/istio-phippy-book/book_cover.png
  content/uk/blog/2024/istio-phippy-book/index.md
  content/uk/blog/2024/istio-phippy-book/phippy_and_family.png
  content/uk/docs/ambient/install/platform-prerequisites/index.md
  content/uk/docs/ambient/usage/l7-features/index.md
  content/uk/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/uk/docs/setup/platform-setup/kind/index.md
  content/uk/docs/tasks/security/authorization/authz-tcp/index.md
  content/uk/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: kind/docs, size/L, cherrypick/release-1.24

#15971 Update distributed tracing docs
  .spelling
  content/en/about/faq/distributed-tracing/disabling-tracing.md
  content/en/about/faq/distributed-tracing/external-zipkin.md
  content/en/about/faq/distributed-tracing/how-distributed-tracing-works.md
  content/en/about/faq/distributed-tracing/how-envoy-based-tracing-works.md
  content/en/about/faq/distributed-tracing/how-to-support-tracing.md
  content/en/about/faq/distributed-tracing/initial-trace-header.md
  content/en/about/faq/distributed-tracing/initial-zipkin-header.md
  content/en/about/faq/distributed-tracing/minimal-requirements.md
  content/en/about/faq/distributed-tracing/no-tracing.md
  content/en/boilerplates/start-otel-collector-service.md
  content/en/docs/concepts/observability/index.md
  content/en/docs/ops/integrations/jaeger/index.md
  content/en/docs/ops/integrations/skywalking/index.md
  content/en/docs/ops/integrations/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/en/docs/tasks/observability/distributed-tracing/jaeger/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/en/docs/tasks/observability/distributed-tracing/lightstep/istio-explorer.png
  content/en/docs/tasks/observability/distributed-tracing/lightstep/istio-services.png
  content/en/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-details-lightstep.png
  content/en/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-list-lightstep.png
  content/en/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
  content/en/docs/tasks/observability/distributed-tracing/opentelemetry/index.md
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
  content/en/docs/tasks/observability/distributed-tracing/sampling/index.md
  content/en/docs/tasks/observability/distributed-tracing/sampling/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/skywalking/index.md
  content/en/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
  content/en/docs/tasks/observability/distributed-tracing/telemetry-api/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/telemetry-api/test.sh
  content/en/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/en/docs/tasks/observability/distributed-tracing/zipkin/snips.sh
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/otel-provider/index.md
  content/en/docs/tasks/security/authorization/authz-dry-run/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: size/XL

#15995 Mark istio 1.21 as EOL
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none, cherrypick/release-1.24

#15996 [release-1.24] Mark istio 1.21 as EOL
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#15990 change png to svg for localization in ambient archtecture control-plane
  content/en/docs/ambient/architecture/control-plane/index.md
  content/en/docs/ambient/architecture/control-plane/ztunnel-architecture.png
  content/en/docs/ambient/architecture/control-plane/ztunnel-architecture.svg
Labels: kind/docs, size/L, ok-to-test

#15999 [release-1.24] change png to svg for localization in ambient archtecture control-plane
  content/en/docs/ambient/architecture/control-plane/index.md
  content/en/docs/ambient/architecture/control-plane/ztunnel-architecture.png
  content/en/docs/ambient/architecture/control-plane/ztunnel-architecture.svg
Labels: size/L, release-notes-none

#16001 Disable authz flake
  content/en/docs/tasks/security/authorization/authz-tcp/test_disabled.sh
Labels: size/XS

#15867 feat: add kyverno authz server blog post
  .spelling
  content/en/blog/2024/authz-policy-with-kyverno/dynamic-metadata.svg
  content/en/blog/2024/authz-policy-with-kyverno/filters-chain.svg
  content/en/blog/2024/authz-policy-with-kyverno/index.md
  content/en/blog/2024/authz-policy-with-kyverno/overview.svg
Labels: area/extensions and telemetry, size/L, ok-to-test

#15998 1.24.1 release notes
  .spelling
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.24.x/announcing-1.24.1/index.md
  data/args.yml
Labels: kind/docs, size/M

#15989 [release-1.24] [uk] sync fixes for 1.24 with upstream
  content/uk/blog/2024/istio-phippy-book/book_cover.png
  content/uk/blog/2024/istio-phippy-book/index.md
  content/uk/blog/2024/istio-phippy-book/phippy_and_family.png
  content/uk/docs/ambient/install/platform-prerequisites/index.md
  content/uk/docs/ambient/usage/l7-features/index.md
  content/uk/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/uk/docs/setup/platform-setup/kind/index.md
  content/uk/docs/tasks/security/authorization/authz-tcp/index.md
  content/uk/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: size/L, release-notes-none

#15979 Removing deprecated `istioctl verify-install` from "Getting Started" with ambient
  content/en/docs/ambient/getting-started/_index.md
Labels: area/environments, kind/docs, size/XS, ok-to-test, area/ambient

#15987 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/L, release-notes-none

#15992 [zh] Sync faq and boilerplates tracing related updates into Chinese
  content/zh/about/faq/distributed-tracing/disabling-tracing.md
  content/zh/about/faq/distributed-tracing/external-zipkin.md
  content/zh/about/faq/distributed-tracing/how-distributed-tracing-works.md
  content/zh/about/faq/distributed-tracing/how-envoy-based-tracing-works.md
  content/zh/about/faq/distributed-tracing/how-to-support-tracing.md
  content/zh/about/faq/distributed-tracing/initial-trace-header.md
  content/zh/about/faq/distributed-tracing/initial-zipkin-header.md
  content/zh/about/faq/distributed-tracing/minimal-requirements.md
  content/zh/about/faq/distributed-tracing/no-tracing.md
  content/zh/boilerplates/start-otel-collector-service.md
Labels: kind/docs, translation/chinese, size/L

#15993 [zh] Sync observability docs update into Chinese
  content/zh/docs/concepts/observability/index.md
  content/zh/docs/ops/integrations/jaeger/index.md
  content/zh/docs/ops/integrations/skywalking/index.md
  content/zh/docs/ops/integrations/zipkin/index.md
  content/zh/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/zh/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
  content/zh/docs/tasks/observability/distributed-tracing/opentelemetry/index.md
  content/zh/docs/tasks/observability/distributed-tracing/overview/index.md
  content/zh/docs/tasks/observability/distributed-tracing/sampling/index.md
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/index.md
  content/zh/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
  content/zh/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/zh/docs/tasks/observability/logs/access-log/index.md
  content/zh/docs/tasks/observability/logs/otel-provider/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: kind/docs, translation/chinese, size/L

#15994 [zh] Sync remove lightstep with links into Chinese
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-explorer.png
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-services.png
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-details-lightstep.png
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-list-lightstep.png
  content/zh/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.24

#16008 [release-1.24] [zh] Sync remove lightstep with links into Chinese
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-explorer.png
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-services.png
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-details-lightstep.png
  content/zh/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-list-lightstep.png
  content/zh/news/releases/1.1.x/announcing-1.1/change-notes/index.md
Labels: size/L, release-notes-none

#15997 Make compat version support more explicit
  content/en/docs/setup/additional-setup/compatibility-versions/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.24

#16015 [release-1.24] Make compat version support more explicit
  content/en/docs/setup/additional-setup/compatibility-versions/index.md
Labels: size/XS, release-notes-none

#15988 [Doc] Fix kubectl command namespace selections
  content/en/docs/setup/install/multiple-controlplanes/index.md
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
  content/zh/docs/setup/install/multiple-controlplanes/index.md
Labels: kind/docs, size/XS, ok-to-test, cherrypick/release-1.24

#16014 DNS Auto Allocation is enabled by default for 1.25
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
Labels: kind/docs, size/L

#16013 [zh] Sync authz policy with kyverno blog into Chinese
  content/zh/blog/2024/authz-policy-with-kyverno/dynamic-metadata.svg
  content/zh/blog/2024/authz-policy-with-kyverno/filters-chain.svg
  content/zh/blog/2024/authz-policy-with-kyverno/index.md
  content/zh/blog/2024/authz-policy-with-kyverno/overview.svg
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.24

#16017 [release-1.24] [zh] Sync authz policy with kyverno blog into Chinese
  content/zh/blog/2024/authz-policy-with-kyverno/dynamic-metadata.svg
  content/zh/blog/2024/authz-policy-with-kyverno/filters-chain.svg
  content/zh/blog/2024/authz-policy-with-kyverno/index.md
  content/zh/blog/2024/authz-policy-with-kyverno/overview.svg
Labels: size/L, release-notes-none

#16018 [zh] Sync update hbone-packet.png to svg #15991
  content/zh/docs/ambient/architecture/hbone/hbone-packet.png
  content/zh/docs/ambient/architecture/hbone/hbone-packet.svg
  content/zh/docs/ambient/architecture/hbone/index.md
Labels: kind/docs, translation/chinese, size/L

#16021 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#16020 [zh] Sync #15997 make compat version support more explicit into Chinese
  content/zh/docs/setup/additional-setup/compatibility-versions/index.md
Labels: kind/docs, translation/chinese, size/XS

#16016 [zh] Sync DNS Auto Allocation is enabled by default for 1.25 #16014
  content/zh/docs/ops/configuration/traffic-management/dns-proxy/index.md
Labels: kind/docs, translation/chinese, size/L

#16007 Small improvements to the ambient mode quickstart
  content/en/docs/ambient/getting-started/_index.md
  content/en/docs/ambient/getting-started/cleanup/index.md
  content/en/docs/ambient/getting-started/cleanup/snips.sh
  content/en/docs/ambient/getting-started/deploy-sample-app/index.md
  content/en/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/en/docs/ambient/getting-started/enforce-auth-policies/snips.sh
  content/en/docs/ambient/getting-started/manage-traffic/index.md
  content/en/docs/ambient/getting-started/secure-and-visualize/index.md
  content/en/docs/ambient/getting-started/secure-and-visualize/kiali-ambient-bookinfo.png
  content/en/docs/ambient/getting-started/secure-and-visualize/kiali-tcp-traffic.png
  content/en/docs/ambient/getting-started/secure-and-visualize/snips.sh
  content/en/docs/ambient/getting-started/test.sh
Labels: size/L

#16024 [release-1.24] Small improvements to the ambient mode quickstart
  content/en/docs/ambient/getting-started/_index.md
  content/en/docs/ambient/getting-started/cleanup/index.md
  content/en/docs/ambient/getting-started/cleanup/snips.sh
  content/en/docs/ambient/getting-started/deploy-sample-app/index.md
  content/en/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/en/docs/ambient/getting-started/enforce-auth-policies/snips.sh
  content/en/docs/ambient/getting-started/manage-traffic/index.md
  content/en/docs/ambient/getting-started/secure-and-visualize/index.md
  content/en/docs/ambient/getting-started/secure-and-visualize/kiali-ambient-bookinfo.png
  content/en/docs/ambient/getting-started/secure-and-visualize/kiali-tcp-traffic.png
  content/en/docs/ambient/getting-started/secure-and-visualize/snips.sh
  content/en/docs/ambient/getting-started/test.sh
Labels: size/L, release-notes-none

#16022 Move Blog Year Buttons to Grid Layout
  src/sass/misc/_blog.scss
Labels: size/M, cherrypick/release-1.24

#16026 [release-1.24] Move Blog Year Buttons to Grid Layout
  src/sass/misc/_blog.scss
Labels: size/M, release-notes-none
