Repository istio/istio.io, pull requests merged in 2024-04, with the labels that each got.

#14812 Fix authz-ingress test flake
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/security/authorization/authz-ingress/test.sh
Labels: size/S

#14816 Remove the reference to installed-state CR
  content/en/docs/setup/install/istioctl/index.md
Labels: kind/docs, size/S, ok-to-test, cherrypick/release-1.21

#14814 update Istio CNI Helm install instructions and add to test
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/additional-setup/cni/snips.sh
  content/en/docs/setup/additional-setup/cni/test.sh
Labels: kind/docs, size/S, cherrypick/release-1.21

#14821 [release-1.21] update Istio CNI Helm install instructions and add to test
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/additional-setup/cni/snips.sh
  content/en/docs/setup/additional-setup/cni/test.sh
Labels: size/S, release-notes-none

#14819 [zh] Sync #14816 into Chinese
  content/zh/docs/setup/install/istioctl/index.md
Labels: kind/docs, translation/chinese, size/S

#14822 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#14815 [zh] Sync authorization/authz-ingress/index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
Labels: kind/docs, translation/chinese, size/XS

#14823 [zh] Sync #14814 into Chinese
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.21

#14824 [release-1.21] [zh] Sync #14814 into Chinese
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: size/S, release-notes-none

#14826 ambient/install: mention k3s CNI paths
  content/en/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, size/XS, ok-to-test, area/ambient

#14828 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#14829 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14830 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/L, auto-merge, release-notes-none

#14832 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/M, auto-merge, release-notes-none

#14833 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14834 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#14836 Automator: update common-files@release-1.20 in istio/istio.io@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14835 Automator: update common-files@release-1.21 in istio/istio.io@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14838 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/M, auto-merge, release-notes-none

#14837 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/M, auto-merge, release-notes-none

#14839 Mark Gateway API as stable, beta for mesh
  data/features.yaml
Labels: size/S, release-notes-none

#14840 Automator: update common-files@release-1.19 in istio/istio.io@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14841 Fix distroless field name
  content/en/docs/ops/configuration/security/harden-docker-images/index.md
Labels: size/XS

#14843 [release-1.21] Fix distroless field name
  content/en/docs/ops/configuration/security/harden-docker-images/index.md
Labels: size/XS, release-notes-none

#14734 Add GKE note for `kube-system` to Platform Prerequisites
  .spelling
  content/en/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: area/environments, kind/docs, size/S, area/ambient, cherrypick/release-1.21

#14847 [release-1.21] Add GKE note for `kube-system` to Platform Prerequisites
  .spelling
  content/en/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: size/S, release-notes-none

#14848 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
Labels: size/S, auto-merge, release-notes-none

#14849 [zh] Sync #14841 image type value fix into Chinese
  content/zh/docs/ops/configuration/security/harden-docker-images/index.md
Labels: kind/docs, translation/chinese, size/XS

#14851 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#14853 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#14850 [zh] Sync #14734 GKE prerequisite into Chinese
  content/zh/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.21

#14854 [release-1.21] [zh] Sync #14734 GKE prerequisite into Chinese
  content/zh/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: size/S, release-notes-none

#14844 [release-1.20] Update test reference and reference docs for 1.20.5
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  go.mod
  go.sum
Labels: size/L

#14857 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#14845 [release-1.19] Update test reference and reference docs for 1.19.9
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  go.mod
  go.sum
Labels: size/XL

#14825 Add OpenTelemetry tracing export example via HTTP
  content/en/docs/tasks/observability/distributed-tracing/opentelemetry/grpc_test.sh
  content/en/docs/tasks/observability/distributed-tracing/opentelemetry/http_test.sh
  content/en/docs/tasks/observability/distributed-tracing/opentelemetry/index.md
  content/en/docs/tasks/observability/distributed-tracing/opentelemetry/snips.sh
Labels: area/extensions and telemetry, size/L

#14842 [release-1.21] Update test reference and reference docs for 1.21.1
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/labels/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/labels/index.html
  go.mod
  go.sum
Labels: size/XL

#14859 update hugo to 0.124.1
  netlify.toml
Labels: size/XS

#14860 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/M, auto-merge, release-notes-none

#14827 [zh] Sync Ambient K3S prerequisite #14826 into Chinese
  content/zh/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/XS

#14858 [Manual Cherrypick] 1.19.9, 1.20.5, 1.21.1 and Security Advisory 2024-002
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.19.x/announcing-1.19.9/index.md
  content/en/news/releases/1.20.x/announcing-1.20.5/index.md
  content/en/news/releases/1.21.x/announcing-1.21.1/index.md
  content/en/news/security/istio-security-2024-002/index.md
Labels: size/L

#14753 Add Gateway API instructions to gateway TLS origination doc
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/gtwapi_mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/gtwapi_tls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/tls_test.sh
Labels: size/XXL

#14865 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, auto-merge, release-notes-none

#14796 [zh] sync news announcing-1.19-eol
  content/zh/news/support/announcing-1.19-eol/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.21

#14862 [zh] Sync #14858 1.19.9, 1.20.5, 1.21.1 and Security Advisory 2024-002 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/announcing-1.19.9/index.md
  content/zh/news/releases/1.20.x/announcing-1.20.5/index.md
  content/zh/news/releases/1.21.x/announcing-1.21.1/index.md
  content/zh/news/security/istio-security-2024-002/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.21

#14868 [release-1.21] [zh] Sync #14858 1.19.9, 1.20.5, 1.21.1 and Security Advisory 2024-002 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/announcing-1.19.9/index.md
  content/zh/news/releases/1.20.x/announcing-1.20.5/index.md
  content/zh/news/releases/1.21.x/announcing-1.21.1/index.md
  content/zh/news/security/istio-security-2024-002/index.md
Labels: size/L, release-notes-none

#14866 Fix incorrect issue link in releasenotes
  content/en/news/releases/1.20.x/announcing-1.20.5/index.md
  content/en/news/releases/1.21.x/announcing-1.21.1/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.21

#14863 Fix CVSS Vector Calculator Link Gen
  content/en/news/security/istio-security-2019-001/index.md
  content/en/news/security/istio-security-2019-002/index.md
  content/en/news/security/istio-security-2019-003/index.md
  content/en/news/security/istio-security-2019-004/index.md
  content/en/news/security/istio-security-2019-005/index.md
  content/en/news/security/istio-security-2019-006/index.md
  content/en/news/security/istio-security-2019-007/index.md
  content/en/news/security/istio-security-2022-003/index.md
  content/en/news/security/istio-security-2022-004/index.md
  content/en/news/security/istio-security-2022-005/index.md
  content/en/news/security/istio-security-2022-006/index.md
  content/en/news/security/istio-security-2022-007/index.md
  content/en/news/security/istio-security-2022-008/index.md
  content/en/news/security/istio-security-2023-001/index.md
  content/en/news/security/istio-security-2023-002/index.md
  content/en/news/security/istio-security-2023-003/index.md
  content/en/news/security/istio-security-2023-004/index.md
  content/en/news/security/istio-security-2024-001/index.md
  content/en/news/security/istio-security-2024-002/index.md
  content/zh/news/security/istio-security-2019-001/index.md
  content/zh/news/security/istio-security-2019-002/index.md
  content/zh/news/security/istio-security-2019-003/index.md
  content/zh/news/security/istio-security-2019-004/index.md
  content/zh/news/security/istio-security-2019-005/index.md
  content/zh/news/security/istio-security-2019-006/index.md
  content/zh/news/security/istio-security-2019-007/index.md
  content/zh/news/security/istio-security-2022-003/index.md
  content/zh/news/security/istio-security-2022-004/index.md
  content/zh/news/security/istio-security-2022-005/index.md
  content/zh/news/security/istio-security-2022-006/index.md
  content/zh/news/security/istio-security-2022-007/index.md
  content/zh/news/security/istio-security-2022-008/index.md
  content/zh/news/security/istio-security-2023-001/index.md
  content/zh/news/security/istio-security-2023-002/index.md
  content/zh/news/security/istio-security-2023-003/index.md
  content/zh/news/security/istio-security-2023-004/index.md
  content/zh/news/security/istio-security-2024-001/index.md
  layouts/news/security-grid.html
  layouts/shortcodes/security_bulletin.html
Labels: kind/docs, size/M, cherrypick/release-1.21

#14870 [release-1.21] Fix CVSS Vector Calculator Link Gen
  content/en/news/security/istio-security-2019-001/index.md
  content/en/news/security/istio-security-2019-002/index.md
  content/en/news/security/istio-security-2019-003/index.md
  content/en/news/security/istio-security-2019-004/index.md
  content/en/news/security/istio-security-2019-005/index.md
  content/en/news/security/istio-security-2019-006/index.md
  content/en/news/security/istio-security-2019-007/index.md
  content/en/news/security/istio-security-2022-003/index.md
  content/en/news/security/istio-security-2022-004/index.md
  content/en/news/security/istio-security-2022-005/index.md
  content/en/news/security/istio-security-2022-006/index.md
  content/en/news/security/istio-security-2022-007/index.md
  content/en/news/security/istio-security-2022-008/index.md
  content/en/news/security/istio-security-2023-001/index.md
  content/en/news/security/istio-security-2023-002/index.md
  content/en/news/security/istio-security-2023-003/index.md
  content/en/news/security/istio-security-2023-004/index.md
  content/en/news/security/istio-security-2024-001/index.md
  content/en/news/security/istio-security-2024-002/index.md
  content/zh/news/security/istio-security-2019-001/index.md
  content/zh/news/security/istio-security-2019-002/index.md
  content/zh/news/security/istio-security-2019-003/index.md
  content/zh/news/security/istio-security-2019-004/index.md
  content/zh/news/security/istio-security-2019-005/index.md
  content/zh/news/security/istio-security-2019-006/index.md
  content/zh/news/security/istio-security-2019-007/index.md
  content/zh/news/security/istio-security-2022-003/index.md
  content/zh/news/security/istio-security-2022-004/index.md
  content/zh/news/security/istio-security-2022-005/index.md
  content/zh/news/security/istio-security-2022-006/index.md
  content/zh/news/security/istio-security-2022-007/index.md
  content/zh/news/security/istio-security-2022-008/index.md
  content/zh/news/security/istio-security-2023-001/index.md
  content/zh/news/security/istio-security-2023-002/index.md
  content/zh/news/security/istio-security-2023-003/index.md
  content/zh/news/security/istio-security-2023-004/index.md
  content/zh/news/security/istio-security-2024-001/index.md
  layouts/news/security-grid.html
  layouts/shortcodes/security_bulletin.html
Labels: size/M, release-notes-none

#14869 [release-1.21] Fix incorrect issue link in releasenotes
  content/en/news/releases/1.20.x/announcing-1.20.5/index.md
  content/en/news/releases/1.21.x/announcing-1.21.1/index.md
Labels: size/XS, release-notes-none

#14867 [release-1.21] [zh] sync news announcing-1.19-eol
  content/zh/news/support/announcing-1.19-eol/index.md
Labels: size/S, release-notes-none

#14871 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  data/features.yaml
Labels: size/XXL, auto-merge, release-notes-none

#14872 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
Labels: size/XXL, auto-merge, release-notes-none

#14873 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14875 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/XXL, auto-merge, release-notes-none

#14878 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#14861 [zh] Sync #14825 improve otel example into Chinese
  content/zh/docs/tasks/observability/distributed-tracing/opentelemetry/index.md
Labels: kind/docs, translation/chinese, size/M

#14864 [zh] Sync #14753 Gateway API instructions to gateway TLS origination into Chinese
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
Labels: kind/docs, translation/chinese, size/XL

#14879 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#14877 Automator: update istio@ test reference
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/L, release-notes-none

#14880 Fixup K3S ambinet docs to be a bit more clear
  content/en/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: size/XS

#14881 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14882 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#14883 Fix k3s English link and sync #14880 update into Chinese
  content/en/docs/ops/ambient/install/platform-prerequisites/index.md
  content/zh/docs/ops/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/XS

#14778 Grafana: Use latest dashboard revision in import reference script
  content/en/docs/ops/integrations/grafana/index.md
Labels: area/environments, kind/docs, size/XS, ok-to-test

#14891 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XXL, auto-merge, release-notes-none

#14892 [zh] Sync #14778 #14876 and #14885 into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
  content/zh/docs/ops/integrations/grafana/index.md
  content/zh/docs/tasks/observability/logs/telemetry-api/index.md
Labels: kind/docs, translation/chinese, size/XS

#14889 Clarification on injection
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: size/XS

#14888 Update ambient helm install index.md to be consistent
  content/en/docs/ops/ambient/install/helm-installation/index.md
  content/en/docs/ops/ambient/install/helm-installation/snips.sh
Labels: size/M

#14898 gateway-api: use v1 resources in examples
  content/en/docs/ops/ambient/architecture/index.md
  content/en/docs/ops/ambient/usage/ztunnel/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/en/docs/tasks/traffic-management/ingress/secure-ingress/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/request-routing/index.md
  content/en/docs/tasks/traffic-management/request-routing/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
  content/zh/docs/ops/ambient/architecture/index.md
  content/zh/docs/ops/ambient/usage/ztunnel/index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/request-routing/index.md
  content/zh/docs/tasks/traffic-management/request-timeouts/index.md
  content/zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: size/L

#14904 Update CVE number for Security Advisory 2024-002.
  .spelling
  content/en/news/security/istio-security-2024-002/index.md
  content/zh/news/security/istio-security-2024-002/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.21

#14906 [release-1.21] Update CVE number for Security Advisory 2024-002.
  .spelling
  content/en/news/security/istio-security-2024-002/index.md
  content/zh/news/security/istio-security-2024-002/index.md
Labels: size/XS, release-notes-none

#14910 Remove note about insecure usage of TLS
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
Labels: size/XS

#14911 [master] Clarification on injection
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: size/XS, release-notes-none

#14912 [release-1.21] Update ambient helm install index.md to be consistent
  content/en/docs/ops/ambient/install/helm-installation/index.md
  content/en/docs/ops/ambient/install/helm-installation/snips.sh
Labels: size/M, release-notes-none

#14884 ambient: comment no gateway as default
  content/en/docs/ops/ambient/getting-started/index.md
Labels: area/environments, kind/docs, size/XS, area/ambient

#14915 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14917 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/XXL, auto-merge, release-notes-none

#14896 [zh] Sync #14888 ambient helm install update into Chinese
  content/zh/docs/ops/ambient/install/helm-installation/index.md
Labels: kind/docs, translation/chinese, size/S

#14897 [zh] Sync #14889 clarification on injection into Chinese
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: kind/docs, translation/chinese, size/XS

#14913 [zh] Sync #14884 comment no gateway as default into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS

#14925 Automator: update istio@ test reference
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/M, release-notes-none

#14922 Ambient get started update
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
Labels: kind/docs, size/L, area/ambient

#14924 update hugo to 0.125.2
  netlify.toml
Labels: size/XS

#14927 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14921 [release-1.21] Release notes 1.19, 1.20, 1.21 and sec adv 2024-003
  .spelling
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/releases/supported-releases/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.19.x/announcing-1.19.10/index.md
  content/en/news/releases/1.20.x/announcing-1.20.6/index.md
  content/en/news/releases/1.21.x/announcing-1.21.2/index.md
  content/en/news/security/istio-security-2024-003/index.md
  data/args.yml
Labels: kind/docs, size/L

#14909 Update to use current version
  content/en/docs/ops/ambient/install/helm-installation/index.md
  content/en/docs/ops/ambient/install/helm-installation/snips.sh
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/helm/snips.sh
  tests/README.md
  tests/util/verify.sh
Labels: size/L

#14919 footer: fix broken link
  layouts/partials/footer.html
Labels: size/XS

#14920 k3d: remove inject
  content/en/docs/setup/platform-setup/k3d/index.md
Labels: size/XS

#14929 [release-1.21] Update the istio test reference to 1.21.2
  go.mod
  go.sum
Labels: size/S

#14928 update enroll-namespace message in example output
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
Labels: kind/docs, size/XS, area/ambient

#14931 [release-1.20] Update the istio test reference to 1.20.6
  go.mod
  go.sum
Labels: size/XS

#14932 [release-1.19] Update the istio test reference to 1.19.10
  go.mod
  go.sum
Labels: size/XS

#14934 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/L, auto-merge, release-notes-none

#14935 [zh] Sync #14909 command result istio version update into Chinese
  content/zh/docs/ops/ambient/install/helm-installation/index.md
  content/zh/docs/setup/install/helm/index.md
Labels: kind/docs, translation/chinese, size/M

#14926 [zh] Sync #14922 Ambient get started update into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/L

#14937 [zh] Sync #14928 enroll-namespace message output into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS

#14936 [zh] Sync #14920 k3s inject remove into Chinese
  content/zh/docs/setup/platform-setup/k3d/index.md
Labels: kind/docs, translation/chinese, size/XS

#14938 cherrypick master: Release notes 1.19, 1.20, 1.21 and sec adv 2024-003 (#14921)
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.19.x/announcing-1.19.10/index.md
  content/en/news/releases/1.20.x/announcing-1.20.6/index.md
  content/en/news/releases/1.21.x/announcing-1.21.2/index.md
  content/en/news/security/istio-security-2024-003/index.md
Labels: kind/docs, size/M

#14933 Move ambient to top level in docs
  content/en/blog/2022/get-started-ambient/index.md
  content/en/blog/2023/ambient-merged-istio-main/index.md
  content/en/blog/2023/rust-based-ztunnel/index.md
  content/en/blog/2023/waypoint-proxy-made-simple/index.md
  content/en/docs/ambient/_index.md
  content/en/docs/ambient/architecture/index.md
  content/en/docs/ambient/getting-started/gtwapi_test-disabled.sh
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/kiali-ambient-bookinfo.png
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/ambient/getting-started/test-disabled.sh
  content/en/docs/ambient/install/_index.md
  content/en/docs/ambient/install/helm-installation/index.md
  content/en/docs/ambient/install/helm-installation/snips.sh
  content/en/docs/ambient/install/helm-installation/test.sh
  content/en/docs/ambient/install/platform-prerequisites/index.md
  content/en/docs/ambient/upgrade/_index.md
  content/en/docs/ambient/upgrade/helm-upgrade/common.sh
  content/en/docs/ambient/upgrade/helm-upgrade/index.md
  content/en/docs/ambient/upgrade/helm-upgrade/snips.sh
  content/en/docs/ambient/upgrade/helm-upgrade/test.sh
  content/en/docs/ambient/usage/_index.md
  content/en/docs/ambient/usage/traffic-redirection/index.md
  content/en/docs/ambient/usage/traffic-redirection/pod-added-to-ambient.svg
  content/en/docs/ambient/usage/traffic-redirection/traffic-flows-between-pods-in-ambient.svg
  content/en/docs/ambient/usage/waypoint/index.md
  content/en/docs/ambient/usage/ztunnel/hbone-packet.png
  content/en/docs/ambient/usage/ztunnel/index.md
  content/en/docs/ambient/usage/ztunnel/ztunnel-architecture.png
  content/en/docs/ambient/usage/ztunnel/ztunnel-datapath-1.png
  content/en/docs/ambient/usage/ztunnel/ztunnel-hairpin.png
  content/en/docs/ambient/usage/ztunnel/ztunnel-waypoint-datapath.png
  content/en/docs/ops/ambient/install/_index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/en/events/banners/ambient-release.md
  content/en/news/releases/1.19.x/announcing-1.19/_index.md
Labels: size/M

#14914 Fix egress mtls origination test
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/snips.sh
Labels: size/L

#14943 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14944 Allow / in compare like prefixes
  tests/util/verify.sh
Labels: size/XS

#14949 fix ambient redirects
  content/en/docs/ambient/_index.md
  content/en/docs/ambient/architecture/index.md
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/install/_index.md
  content/en/docs/ambient/install/helm-installation/index.md
  content/en/docs/ambient/install/platform-prerequisites/index.md
  content/en/docs/ambient/upgrade/_index.md
  content/en/docs/ambient/upgrade/helm-upgrade/index.md
  content/en/docs/ambient/usage/_index.md
  content/en/docs/ambient/usage/traffic-redirection/index.md
  content/en/docs/ambient/usage/waypoint/index.md
  content/en/docs/ambient/usage/ztunnel/index.md
Labels: size/S

#14939 [zh] Sync #14921 Release notes 1.19, 1.20, 1.21 and sec adv 2024-003 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/announcing-1.19.10/index.md
  content/zh/news/releases/1.20.x/announcing-1.20.6/index.md
  content/zh/news/releases/1.21.x/announcing-1.21.2/index.md
  content/zh/news/security/istio-security-2024-003/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.21

#14950 [zh] Sync #14914 fix egress mtls origination test into Chinese
  content/zh/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
Labels: kind/docs, translation/chinese, size/L

#14951 [release-1.21] [zh] Sync #14921 Release notes 1.19, 1.20, 1.21 and sec adv 2024-003 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/announcing-1.19.10/index.md
  content/zh/news/releases/1.20.x/announcing-1.20.6/index.md
  content/zh/news/releases/1.21.x/announcing-1.21.2/index.md
  content/zh/news/security/istio-security-2024-003/index.md
Labels: size/L, release-notes-none

#14948 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/M, auto-merge, release-notes-none

#14953 starting fixup for ambient getting-stated tests
  content/en/docs/ambient/getting-started/gtwapi_test.sh
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/ambient/getting-started/test.sh
Labels: kind/docs, size/M, area/ambient

#14954 Clarify use of path template operators with MERGE_SLASHES
  content/en/docs/reference/config/security/normalization/index.md
Labels: area/security, size/XS

#14961 revert hugo to 0.125.1
  netlify.toml
Labels: size/XS

#14940 [zh] Sync #14933 move ambient to top level in docs into Chinese
  content/zh/blog/2022/get-started-ambient/index.md
  content/zh/blog/2022/istio-accepted-into-cncf/index.md
  content/zh/blog/2023/ambient-ebpf-redirection/index.md
  content/zh/blog/2023/ambient-merged-istio-main/index.md
  content/zh/blog/2023/istio-at-kubecon-eu/index.md
  content/zh/blog/2023/istio-graduates-within-cncf/index.md
  content/zh/blog/2023/istiocon-china/index.md
  content/zh/blog/2023/rust-based-ztunnel/index.md
  content/zh/blog/2023/waypoint-proxy-made-simple/index.md
  content/zh/docs/ambient/_index.md
  content/zh/docs/ambient/architecture/index.md
  content/zh/docs/ambient/getting-started/index.md
  content/zh/docs/ambient/getting-started/kiali-ambient-bookinfo.png
  content/zh/docs/ambient/install/_index.md
  content/zh/docs/ambient/install/helm-installation/index.md
  content/zh/docs/ambient/install/platform-prerequisites/index.md
  content/zh/docs/ambient/upgrade/_index.md
  content/zh/docs/ambient/upgrade/helm-upgrade/index.md
  content/zh/docs/ambient/usage/_index.md
  content/zh/docs/ambient/usage/traffic-redirection/index.md
  content/zh/docs/ambient/usage/traffic-redirection/pod-added-to-ambient.svg
  content/zh/docs/ambient/usage/traffic-redirection/traffic-flows-between-pods-in-ambient.svg
  content/zh/docs/ambient/usage/waypoint/index.md
  content/zh/docs/ambient/usage/ztunnel/hbone-packet.png
  content/zh/docs/ambient/usage/ztunnel/index.md
  content/zh/docs/ambient/usage/ztunnel/ztunnel-architecture.png
  content/zh/docs/ambient/usage/ztunnel/ztunnel-datapath-1.png
  content/zh/docs/ambient/usage/ztunnel/ztunnel-hairpin.png
  content/zh/docs/ambient/usage/ztunnel/ztunnel-waypoint-datapath.png
  content/zh/docs/ops/ambient/install/_index.md
  content/zh/docs/ops/ambient/upgrade/_index.md
  content/zh/docs/setup/additional-setup/config-profiles/index.md
  content/zh/events/banners/ambient-release.md
  content/zh/news/releases/1.18.x/announcing-1.18/_index.md
  content/zh/news/releases/1.19.x/announcing-1.19/_index.md
Labels: kind/docs, translation/chinese, size/L

#14964 [zh] Sync #14954 clarify use of path template operators with MERGE_SLASHES into Chinese
  content/zh/docs/reference/config/security/normalization/index.md
Labels: kind/docs, translation/chinese, size/XS

#14962 [zh] Sync #14949 ambient doc redirections into Chinese
  content/zh/docs/ambient/_index.md
  content/zh/docs/ambient/architecture/index.md
  content/zh/docs/ambient/getting-started/index.md
  content/zh/docs/ambient/install/_index.md
  content/zh/docs/ambient/install/helm-installation/index.md
  content/zh/docs/ambient/install/platform-prerequisites/index.md
  content/zh/docs/ambient/upgrade/_index.md
  content/zh/docs/ambient/upgrade/helm-upgrade/index.md
  content/zh/docs/ambient/usage/_index.md
  content/zh/docs/ambient/usage/traffic-redirection/index.md
  content/zh/docs/ambient/usage/waypoint/index.md
  content/zh/docs/ambient/usage/ztunnel/index.md
Labels: kind/docs, translation/chinese, size/S

#14963 [zh] Sync #14953 ambient get start test output fix into Chinese
  content/zh/docs/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/S

#14965 Try enabling authz-dry-run test
  content/en/docs/tasks/security/authorization/authz-dry-run/test.sh
Labels: size/XS

#14959 Update istio test reference to beta.0 commit
  go.mod
  go.sum
Labels: size/XS

#14960 Announce 1.19 EOL
  content/en/news/support/announcing-1.19-eol-final/index.md
Labels: area/test and release, size/S, cherrypick/release-1.21

#14969 [release-1.21] Announce 1.19 EOL
  content/en/news/support/announcing-1.19-eol-final/index.md
Labels: size/S, release-notes-none

#14947 updating dashboard instructions to reflect latest kubernetes dashboar…
  content/en/docs/setup/platform-setup/k3d/index.md
Labels: kind/docs, size/XS, ok-to-test

#14971 Update index.md
  content/en/docs/setup/install/multicluster/primary-remote/index.md
Labels: size/XS, ok-to-test

#14972 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#14974 [zh] Sync #14960 Announce 1.19 EOL into Chinese
  content/zh/news/support/announcing-1.19-eol-final/index.md
Labels: kind/docs, translation/chinese, size/S

#14966 Update test to use profile=none since it now installs Istio
  content/en/docs/tasks/security/authorization/authz-dry-run/test.sh
Labels: size/XS

#14976 [zh] Sync #14958 remove istio api from ambient mode getting started guide into Chinese
  content/zh/docs/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XL

#14980 Simplify gw yaml a bit in get started
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/snips.sh
Labels: kind/docs, size/S, area/ambient

#14982 Forgot to remove namespace
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/snips.sh
Labels: kind/docs, size/XS, area/ambient

#14986 [zh] Sync #14980 simplify gw yaml a bit in get started into Chinese
  content/zh/docs/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/S

#14987 [zh] Sync #14982 remove namespace into Chinese
  content/zh/docs/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS

#14985 update support release about 1.22
  .spelling
  content/en/docs/releases/supported-releases/index.md
  data/compatibility/supportStatus.yml
Labels: size/M

#14988 Automator: update istio@ test reference
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/M, release-notes-none

#14979 scripts: update get_gateway_api_version.sh
  scripts/get_gateway_api_version.sh
Labels: size/XS

#14990 Add k3d platform for ambient
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, size/S, area/ambient

#14991 [zh] Sync #14985 support release about 1.22 into Chinese
  content/zh/docs/releases/supported-releases/index.md
Labels: kind/docs, translation/chinese, size/XS

#14968 Tweak the LHS moving ambient and slight rename for legacy
  content/en/docs/ambient/_index.md
  content/en/docs/setup/_index.md
Labels: size/XS

#14998 [zh] Sync #14990 add k3d platform for ambient into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/S

#15001 use targetrefs instead in get started doc
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/snips.sh
Labels: kind/docs, size/XS, area/ambient
