Repository istio/istio.io, pull requests merged in 2024-01, with the labels that each got.

#14402 [zh] Update /install/external-controlplane/
  content/zh/docs/setup/install/external-controlplane/external-controlplane.svg
  content/zh/docs/setup/install/external-controlplane/external-multicluster.svg
  content/zh/docs/setup/install/external-controlplane/index.md
Labels: kind/docs, translation/chinese, size/XXL

#14403 Remove unused IST0113 analysis
  content/en/docs/reference/config/analysis/ist0113/index.md
  content/zh/docs/reference/config/analysis/ist0113/index.md
Labels: kind/docs, size/L

#14404 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#14405 Remove extra alpha status warning
  content/en/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, cherrypick/release-1.20

#14407 [zh] Sync ambient warning with #14405 into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.20

#14408 [release-1.20] [zh] Sync ambient warning with #14405 into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: size/XS, release-notes-none

#14411 [zh] Update text from ist0151 to ist0164
  content/zh/docs/reference/config/analysis/ist0151/index.md
  content/zh/docs/reference/config/analysis/ist0152/index.md
  content/zh/docs/reference/config/analysis/ist0153/index.md
  content/zh/docs/reference/config/analysis/ist0154/index.md
  content/zh/docs/reference/config/analysis/ist0155/index.md
  content/zh/docs/reference/config/analysis/ist0158/index.md
  content/zh/docs/reference/config/analysis/ist0161/index.md
  content/zh/docs/reference/config/analysis/ist0162/index.md
  content/zh/docs/reference/config/analysis/ist0163/index.md
  content/zh/docs/reference/config/analysis/ist0164/index.md
Labels: kind/docs, translation/chinese, size/M

#14406 [release-1.20] Remove extra alpha status warning
  content/en/docs/ops/ambient/getting-started/index.md
Labels: size/XS, release-notes-none

#14307 Add advanced ratelimit example
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
  content/en/docs/tasks/policy-enforcement/rate-limit/snips.sh
  content/en/docs/tasks/policy-enforcement/rate-limit/test.sh
Labels: kind/docs, size/L, ok-to-test

#14412 [release-1.20] Add advanced ratelimit example
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
  content/en/docs/tasks/policy-enforcement/rate-limit/snips.sh
  content/en/docs/tasks/policy-enforcement/rate-limit/test.sh
Labels: size/L, release-notes-none

#14415 [release-1.20] Fix egress-tls-origination test- snip renamed
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/mtls_test.sh
Labels: size/XS

#14400 Update to latest istio commit. Fix egress test
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/mtls_test.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/M

#14414 [zh] Sync #14307 advanced rate limit example into Chinese
  content/zh/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.20

#14419 [release-1.20] [zh] Sync #14307 advanced rate limit example into Chinese
  content/zh/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: translation/chinese, size/L, release-notes-none

#14421 Remove 1.17 from CVE table, update Envoy version section
  .spelling
  content/en/docs/releases/supported-releases/index.md
Labels: size/S, cherrypick/release-1.20

#14425 [release-1.20] Remove 1.17 from CVE table, update Envoy version section
  .spelling
  content/en/docs/releases/supported-releases/index.md
Labels: size/S, release-notes-none

#14427 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
Labels: size/L, auto-merge, release-notes-none

#14410 Add 1.18.7 releasenote
  content/en/news/releases/1.18.x/announcing-1.18.7/index.md
  content/en/news/support/announcing-1.18-eol-final/index.md
  data/compatibility/supportStatus.yml
Labels: kind/docs, size/M, cherrypick/release-1.20

#14428 [zh] Sync #14421 into Chinese
  content/zh/docs/releases/supported-releases/index.md
Labels: kind/docs, translation/chinese, size/S

#14429 [release-1.20] Add 1.18.7 releasenote
  content/en/news/releases/1.18.x/announcing-1.18.7/index.md
  content/en/news/support/announcing-1.18-eol-final/index.md
  data/compatibility/supportStatus.yml
Labels: size/M, release-notes-none

#14430 [zh] Sync 1.18.7 release note and 1.18 eol into Chinese
  content/zh/news/releases/1.18.x/announcing-1.18.7/index.md
  content/zh/news/support/announcing-1.18-eol-final/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.20

#14431 [release-1.20] [zh] Sync 1.18.7 release note and 1.18 eol into Chinese
  content/zh/news/releases/1.18.x/announcing-1.18.7/index.md
  content/zh/news/support/announcing-1.18-eol-final/index.md
Labels: size/M, release-notes-none

#14418 Fix indentations and tweak long lines in policy-enforcement/rate-limit task
  content/en/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: kind/docs, size/L

#14433 gateway-api: improve sample cleanup instructions
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/test.sh
Labels: size/S

#14434 docs: update customize installation page
  content/en/docs/setup/additional-setup/customize-installation/index.md
Labels: area/environments, kind/docs, size/XS

#14435 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14436 Cleanup Azure AKS-Engine references
  content/en/docs/setup/platform-setup/azure/index.md
Labels: kind/docs, size/M, ok-to-test

#14439 [zh] Sync #14433 into Chinese
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: kind/docs, translation/chinese, size/XS

#14440 [zh] Sync #14434 into Chinese
  content/zh/docs/setup/additional-setup/customize-installation/index.md
Labels: kind/docs, translation/chinese, size/XS

#14441 [zh] Sync #14436 into Chinese
  content/zh/docs/setup/platform-setup/azure/index.md
Labels: kind/docs, translation/chinese, size/M

#14426 [zh] Sync /reference/config/metrics/
  content/zh/docs/reference/config/metrics/index.md
Labels: kind/docs, translation/chinese, size/L

#14442 [zh] Fix broken links, anchors and translate for customize install doc
  content/zh/docs/setup/additional-setup/customize-installation/index.md
Labels: kind/docs, translation/chinese, size/M

#14437 Release notes for 1.19.6
  content/en/news/releases/1.19.x/announcing-1.19.6/index.md
Labels: area/test and release, size/M, cherrypick/release-1.20

#14444 [release-1.20] Release notes for 1.19.6
  content/en/news/releases/1.19.x/announcing-1.19.6/index.md
Labels: size/M, release-notes-none

#14416 [release-1.18] Update to use 1.18.7 for testing
  go.mod
  go.sum
Labels: size/M

#14446 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: size/L, auto-merge, release-notes-none

#14449 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#14447 [zh] sync /ops/diagnostic-tools/multicluster/
  content/zh/docs/ops/diagnostic-tools/multicluster/index.md
Labels: kind/docs, translation/chinese, size/XS

#14409 Add ist0167 message description
  content/en/docs/reference/config/analysis/ist0167/index.md
Labels: kind/docs, area/user experience, size/M

#14450 update hugo to 0.121.2
  netlify.toml
Labels: size/XS

#14443 Add dependency computation for scripts in presubmit job
  scripts/pr_tests.py
Labels: area/test and release, size/M

#14452 Fix directory level of script dependencies
  scripts/pr_tests.py
Labels: area/test and release, size/XS

#14445 gateway-api: add gateway api instructions to egress-control doc
  content/en/boilerplates/gateway-api-experimental.md
  content/en/boilerplates/gateway-api-gamma-support.md
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/test.sh
Labels: size/L

#14451 [zh] Sync ist0167 into Chinese
  content/zh/docs/reference/config/analysis/ist0167/index.md
Labels: kind/docs, translation/chinese, size/M

#14454 [zh] Sync #14445 into Chinese
  content/zh/boilerplates/gateway-api-experimental.md
  content/zh/boilerplates/gateway-api-gamma-support.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.20

#14455 [release-1.20] [zh] Sync #14445 into Chinese
  content/zh/boilerplates/gateway-api-experimental.md
  content/zh/boilerplates/gateway-api-gamma-support.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: size/L, release-notes-none

#14438 Add 1.20.2 releasenotes
  content/en/news/releases/1.20.x/announcing-1.20.2/index.md
Labels: kind/docs, size/M, cherrypick/release-1.20

#14457 [zh] Sync releasenote 1.19.6 into Chinese
  content/zh/news/releases/1.19.x/announcing-1.19.6/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.19

#14460 [release-1.20] [zh] Sync releasenote 1.19.6 into Chinese
  content/zh/news/releases/1.19.x/announcing-1.19.6/index.md
Labels: size/M, release-notes-none

#14462 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14461 Manual cherry-pick 1.20.2 releasenotes
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.20.x/announcing-1.20.2/index.md
  data/args.yml
Labels: kind/docs, size/M

#14463 [release-1.20] [zh] Sync releasenote 1.20.2 into Chinese
  content/zh/news/releases/1.20.x/announcing-1.20.2/index.md
Labels: size/M, release-notes-none

#14464 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
Labels: size/M, auto-merge, release-notes-none

#14466 Automator: update common-files@release-1.20 in istio/istio.io@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14465 Automator: update common-files@release-1.19 in istio/istio.io@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14423 [release-1.20] Update to use 1.20.2 for testing
  go.mod
  go.sum
Labels: size/M

#14424 [release-1.20] Update reference docs for 1.20.2
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
Labels: size/L

#14468 use github discussion
  content/en/get-involved/_index.md
Labels: size/XS, cherrypick/release-1.20

#14469 [release-1.20] use github discussion
  content/en/get-involved/_index.md
Labels: size/XS, release-notes-none

#14471 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14470 [zh] Sync #14468 into Chinese
  content/zh/get-involved/_index.md
Labels: kind/docs, translation/chinese, size/XS

#14472 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#14467 [zh] Sync setup/additional-setup/cni/
  content/zh/docs/setup/additional-setup/cni/cni.svg
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, translation/chinese, size/L

#14474 docs: fix an incorrect link on the Observability page
  content/en/docs/concepts/observability/index.md
Labels: release-notes-none, cherrypick/release-1.20

#14475 [release-1.20] docs: fix an incorrect link on the Observability page
  content/en/docs/concepts/observability/index.md
Labels: size/XS, release-notes-none

#14476 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/labels/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/labels/index.html
Labels: size/XXL, auto-merge, release-notes-none

#14479 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
Labels: size/S, auto-merge, release-notes-none

#14480 Automator: update common-files@release-1.20 in istio/istio.io@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14477 [zh] Sync #14474 into Chinese
  content/zh/docs/concepts/observability/index.md
Labels: kind/docs, translation/chinese, size/XS

#14483 [release-1.20] update current date
  data/args.yml
Labels: size/XS, release-notes-none

#14484 Update the istio test reference and fix ambient failure
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/en/docs/ops/ambient/install/helm-installation/index.md
  content/en/docs/ops/ambient/install/helm-installation/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/L

#14485 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14488 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
Labels: size/L, auto-merge, release-notes-none

#14489 [zh] Sync #14484 into Chinese
  content/zh/docs/ops/ambient/install/helm-installation/index.md
Labels: kind/docs, translation/chinese, size/XS

#14487 [zh] Update /setup/install/multicluster/
  content/zh/docs/reference/glossary/service-mesh.md
  content/zh/docs/setup/install/multicluster/_index.md
Labels: kind/docs, translation/chinese, size/S

#14490 zh: fix typo and translation error
  content/zh/docs/ops/configuration/traffic-management/network-topologies/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#14473 gateway-api: add Gateway API instructions to egress gateways doc
  content/en/boilerplates/gateway-api-experimental.md
  content/en/boilerplates/gateway-api-gamma-support.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh
Labels: size/XXL

#14493 fix typo livenessProve to livenessProbe
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/zh/docs/ops/configuration/mesh/app-health-check/index.md
Labels: kind/docs, size/XS, ok-to-test, cherrypick/release-1.20

#14486 Designate master and Istio 1.20 as being supported on Kubernetes 1.29
  data/compatibility/supportStatus.yml
Labels: kind/docs, size/XS, cherrypick/release-1.20

#14494 [release-1.20] Designate master and Istio 1.20 as being supported on Kubernetes 1.29
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#14495 [release-1.20] fix typo livenessProve to livenessProbe
  content/en/docs/ops/configuration/mesh/app-health-check/index.md
  content/zh/docs/ops/configuration/mesh/app-health-check/index.md
Labels: size/XS, release-notes-none

#14417 Add documentation for compatibility versions
  content/en/docs/setup/additional-setup/compatibility-versions/index.md
Labels: size/M

#14497 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#14498 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  data/analysis.yaml
Labels: size/M, auto-merge, release-notes-none

#14499 [zh] Sync Compatibility Versions into Chinese
  content/zh/docs/setup/additional-setup/compatibility-versions/index.md
Labels: kind/docs, translation/chinese, size/M

#14492 [zh] Sync /traffic-management/egress/egress-gateway/
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: kind/docs, translation/chinese, size/XL

#14503 Create a blog to keep track of upcoming kubeCon EU activities related to Istio
  .spelling
  content/en/blog/2024/kubecon-eu/KubeConParis.png
  content/en/blog/2024/kubecon-eu/index.md
Labels: size/M, cherrypick/release-1.20

#14505 [release-1.20] Create a blog to keep track of upcoming kubeCon EU activities related to Istio
  .spelling
  content/en/blog/2024/kubecon-eu/KubeConParis.png
  content/en/blog/2024/kubecon-eu/index.md
Labels: size/M, release-notes-none

#14506 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/L, auto-merge, release-notes-none

#14509 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#14507 [zh] Sync istio kubecon eu 2024 blog into Chinese
  content/zh/blog/2024/kubecon-eu/KubeConParis.png
  content/zh/blog/2024/kubecon-eu/index.md
Labels: kind/docs, translation/chinese, size/M

#14512 [release-1.20] [zh] Sync istio kubecon eu 2024 blog into Chinese
  content/zh/blog/2024/kubecon-eu/KubeConParis.png
  content/zh/blog/2024/kubecon-eu/index.md
Labels: size/M, release-notes-none

#14511 [zh] improve ingress-sni-passthrough
  content/zh/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
Labels: kind/docs, translation/chinese, size/XS

#14510 [zh] sync wildcard-egress-hosts
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxy.svg
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxyCP.svg
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: kind/docs, translation/chinese, size/L

#14514 [zh] Update /egress/wildcard-egress-hosts/
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxyCP.svg
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: kind/docs, translation/chinese, size/XXL

#14513 [zh] Sync boilerplates folder
  content/zh/boilerplates/gateway-api-experimental.md
  content/zh/boilerplates/gateway-api-gamma-support.md
  content/zh/boilerplates/gateway-api-version.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
Labels: kind/docs, translation/chinese, size/M

#14515 Fix warning for compatibilityVersion
  content/en/docs/setup/additional-setup/compatibility-versions/index.md
  content/zh/docs/setup/additional-setup/compatibility-versions/index.md
Labels: size/XS

#14517 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14518 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14519 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#14522 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14500 sync new format of labels and annotations
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/labels/index.html
Labels: size/XL

#14525 [zh] sync config pages
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/labels/index.html
Labels: size/XL

#14523 [zh] Sync #14491 Ambient upgrade doc into Chinese
  content/zh/docs/ops/ambient/architecture/index.md
  content/zh/docs/ops/ambient/install/_index.md
  content/zh/docs/ops/ambient/install/helm-installation/index.md
  content/zh/docs/ops/ambient/upgrade/_index.md
  content/zh/docs/ops/ambient/upgrade/helm-upgrade/index.md
  content/zh/docs/ops/ambient/usage/_index.md
  content/zh/docs/ops/ambient/usage/ztunnel/index.md
Labels: kind/docs, translation/chinese, size/L

#14529 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/L, auto-merge, release-notes-none

#14526 [zh] Localization svgs in additional-setup/gateway
  content/zh/docs/setup/additional-setup/gateway/high-level-canary.svg
  content/zh/docs/setup/additional-setup/gateway/shared-gateway.svg
  content/zh/docs/setup/additional-setup/gateway/user-gateway.svg
Labels: translation/chinese, size/XL

#14530 Update images for canary upgrade
  content/en/docs/setup/upgrade/canary/revision-tags-after.svg
  content/zh/docs/setup/upgrade/canary/revision-tags-after.svg
Labels: kind/docs, size/XXL

#14531 [release-1.20] Update images for canary upgrade
  content/en/docs/setup/upgrade/canary/revision-tags-after.svg
  content/zh/docs/setup/upgrade/canary/revision-tags-after.svg
Labels: size/XXL, release-notes-none

#14534 [release-1.20] [zh] update gateway api tips
  content/zh/docs/setup/getting-started/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XS, release-notes-none

#14536 [release-1.20] [zh] update /additional-setup/config-profiles/
  content/zh/docs/setup/additional-setup/config-profiles/index.md
Labels: size/S, release-notes-none

#14538 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14520 Fix revision test
  content/en/docs/setup/upgrade/canary/canary_upgrade_test.sh
  content/en/docs/setup/upgrade/canary/index.md
  content/en/docs/setup/upgrade/canary/revision_tags_test.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  go.mod
  go.sum
Labels: kind/docs, size/M

#14516 Add wait flag to istioctl waypoint apply cmd
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, size/S, area/ambient

#14502 Small improvements to egress gateway doc
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/EgressGatewayWithSNIProxyCP.svg
Labels: size/S

#14527 prepare for v1.21 as Istio source is already branched
  Makefile.core.mk
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/reference/config/istio.operator.v1alpha1/index.html
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/zh/docs/reference/config/istio.operator.v1alpha1/index.html
  data/args.yml
  go.mod
  go.sum
Labels: size/M

#14539 Add KubeCon EU Istio sessions to the blog
  content/en/blog/2024/kubecon-eu/index.md
Labels: size/S, cherrypick/release-1.20

#14540 [release-1.20] Add KubeCon EU Istio sessions to the blog
  content/en/blog/2024/kubecon-eu/index.md
Labels: size/S, release-notes-none

#14541 Add tag cleanup section
  content/zh/docs/setup/upgrade/canary/index.md
Labels: kind/docs, size/XS

#14543 [release-1.20] Add tag cleanup section
  content/zh/docs/setup/upgrade/canary/index.md
Labels: size/XS, release-notes-none

#14532 [zh] Sync /setup/upgrade/canary/
  content/zh/docs/setup/upgrade/canary/index.md
  content/zh/docs/setup/upgrade/canary/revision-tags-before.svg
  content/zh/docs/setup/upgrade/canary/tags-updated.png
  content/zh/docs/setup/upgrade/canary/tags.png
Labels: kind/docs, translation/chinese, size/XS

#14542 Fix in-place upgrade doc to be more accurate
  content/en/docs/setup/upgrade/in-place/index.md
Labels: kind/docs, size/XS

#14545 [zh] Sync kubecon eu 2024 blog into Chinese
  content/zh/blog/2024/kubecon-eu/index.md
Labels: kind/docs, translation/chinese, size/S

#14546 [zh] Sync #14542 with typo fix into Chinese
  content/zh/docs/setup/upgrade/in-place/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.20

#14548 [release-1.20] [zh] Sync #14542 with typo fix into Chinese
  content/zh/docs/setup/upgrade/in-place/index.md
Labels: size/S, release-notes-none

#14547 [release-1.20] Fix in-place upgrade doc to be more accurate
  content/en/docs/setup/upgrade/in-place/index.md
Labels: size/XS, release-notes-none

#13659 Add Ambient Alpha Banner to Homepage
  content/en/events/banners/ambient-release.md
Labels: kind/docs, size/XS, cherrypick/release-1.20

#14551 [release-1.20] Add Ambient Alpha Banner to Homepage
  content/en/events/banners/ambient-release.md
Labels: size/XS, release-notes-none

#14552 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/L, auto-merge, release-notes-none

#14553 [zh] Sync Ambient banner into Chinese
  content/zh/events/banners/ambient-release.md
Labels: kind/docs, translation/chinese, size/XS

#14554 [release-1.20] [zh] Sync Ambient banner into Chinese
  content/zh/events/banners/ambient-release.md
Labels: size/XS, release-notes-none

#14555 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#14496 Re-add mgmt certs
  content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
Labels: size/L, cherrypick/release-1.20

#14558 [release-1.20] Re-add mgmt certs
  content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
Labels: size/L, release-notes-none

#14559 add additional breakpoints for blog content width
  Makefile.core.mk
  src/sass/misc/_blog.scss
Labels: kind/docs, size/S, cherrypick/release-1.20

#14560 [release-1.20] add additional breakpoints for blog content width
  Makefile.core.mk
  src/sass/misc/_blog.scss
Labels: size/S, release-notes-none

#14524 initial draft blog for inpod
  .spelling
  content/en/blog/2024/inpod-traffic-redirection-ambient/index.md
  content/en/blog/2024/inpod-traffic-redirection-ambient/pod-added-to-ambient.svg
  content/en/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-between-pods-in-ambient.svg
  content/en/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-plaintext.svg
Labels: size/L, cherrypick/release-1.20

#14563 [release-1.20] initial draft blog for inpod
  .spelling
  content/en/blog/2024/inpod-traffic-redirection-ambient/index.md
  content/en/blog/2024/inpod-traffic-redirection-ambient/pod-added-to-ambient.svg
  content/en/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-between-pods-in-ambient.svg
  content/en/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-plaintext.svg
Labels: size/L, release-notes-none

#14568 [zh] Update translation of minor version for consistency
  content/zh/about/faq/setup/install-method-selection.md
  content/zh/blog/2021/direct-upgrade/index.md
  content/zh/blog/2021/extended-support/index.md
  content/zh/docs/ops/ambient/upgrade/helm-upgrade/index.md
  content/zh/docs/releases/supported-releases/index.md
  content/zh/docs/setup/upgrade/canary/index.md
  content/zh/docs/setup/upgrade/helm/index.md
  content/zh/news/support/announcing-1.10-eol/index.md
  content/zh/news/support/announcing-1.11-eol/index.md
  content/zh/news/support/announcing-1.12-eol/index.md
  content/zh/news/support/announcing-1.13-eol/index.md
  content/zh/news/support/announcing-1.14-eol/index.md
  content/zh/news/support/announcing-1.15-eol/index.md
  content/zh/news/support/announcing-1.16-eol/index.md
  content/zh/news/support/announcing-1.17-eol/index.md
  content/zh/news/support/announcing-1.18-eol/index.md
Labels: kind/docs, translation/chinese, size/M

#14570 Automator: update common-files@master in istio/istio.io@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
