Repository istio/istio.io, pull requests merged in 2024-07, with the labels that each got.

#15364 [release-1.22] Fix CNI doc wrong anchor
  content/en/docs/setup/additional-setup/cni/index.md
Labels: size/XS, release-notes-none

#15351 Add 1.20.8 releasenotes
  content/en/news/releases/1.20.x/announcing-1.20.8/index.md
Labels: kind/docs, size/S, cherrypick/release-1.22

#15362 [zh] Sync #15282 CNI doc update into Chinese
  content/zh/docs/reference/glossary/cni.md
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, translation/chinese, size/L

#15365 [zh] remove about/community/join
  content/zh/about/community/join/discourse.svg
  content/zh/about/community/join/drive.svg
  content/zh/about/community/join/gcal.svg
  content/zh/about/community/join/github.png
  content/zh/about/community/join/governance.svg
  content/zh/about/community/join/group.svg
  content/zh/about/community/join/index.md
  content/zh/about/community/join/servicemesher.svg
  content/zh/about/community/join/slack.svg
  content/zh/about/community/join/stackoverflow.svg
  content/zh/about/community/join/twitter.svg
Labels: kind/docs, translation/chinese, size/M

#15367 [zh] Sync 1.20.8 release note into Chinese
  content/zh/news/releases/1.20.x/announcing-1.20.8/index.md
Labels: kind/docs, translation/chinese, size/S

#15366 [release-1.22] Add 1.20.8 releasenotes
  content/en/news/releases/1.20.x/announcing-1.20.8/index.md
Labels: size/S, release-notes-none

#15368 [zh] Update setup/additional-setup/cni/
  content/zh/docs/setup/additional-setup/cni/index.md
  content/zh/news/releases/1.7.x/announcing-1.7.1/index.md
Labels: kind/docs, translation/chinese, size/L

#15371 [master cp] security adv, release notes 1.22.1 and 1.21.4 (#15358)
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.21.x/announcing-1.21.4/index.md
  content/en/news/releases/1.22.x/announcing-1.22.2/index.md
  content/en/news/security/istio-security-2024-005/index.md
  data/compatibility/supportStatus.yml
Labels: kind/docs, size/L

#15370 Add Venturenox to the list of professional services providers
  data/companies.yml
  static/logos/venturenox.svg
Labels: size/L, ok-to-test

#15373 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
Labels: size/M, auto-merge, release-notes-none

#15372 [release-1.22] Add Venturenox to the list of professional services providers
  data/companies.yml
  static/logos/venturenox.svg
Labels: size/L, release-notes-none

#15374 [zh] Sync 1.21.4, 1.22.2 release notes and security update into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.21.x/announcing-1.21.4/index.md
  content/zh/news/releases/1.22.x/announcing-1.22.2/index.md
  content/zh/news/security/istio-security-2024-005/index.md
Labels: kind/docs, translation/chinese, size/L

#15375 Remove port and fix invalid domain.
  content/en/docs/ops/diagnostic-tools/proxy-cmd/index.md
  content/zh/docs/ops/diagnostic-tools/proxy-cmd/index.md
Labels: size/S

#15376 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15338 fix slider items on mobile
  layouts/home.html
  src/sass/misc/_logo-gallery.scss
Labels: size/S

#15377 [release-1.22] fix slider items on mobile
  layouts/home.html
  src/sass/misc/_logo-gallery.scss
Labels: size/S, release-notes-none

#15378 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#15315 remove wasm telemetry
  content/en/blog/2020/wasm-announce/index.md
  content/en/docs/reference/config/proxy_extensions/wasm_telemetry/index.md
Labels: size/M

#15369 [release-1.22] [zh] Sync 1.20.8 release note into Chinese
  content/zh/news/releases/1.20.x/announcing-1.20.8/index.md
Labels: size/S, release-notes-none

#15379 Automator: update common-files@release-1.21 in istio/istio.io@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15380 Automator: update common-files@release-1.22 in istio/istio.io@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15381 [zh] Sync #15315 remove wasm telemetry into Chinese
  content/zh/blog/2020/wasm-announce/index.md
  content/zh/docs/reference/config/proxy_extensions/wasm_telemetry/index.md
Labels: kind/docs, translation/chinese, size/M

#15382 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15384 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#15387 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/networking/serviceentry-status/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/networking/serviceentry-status/index.html
Labels: size/L, auto-merge, release-notes-none

#15388 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/serviceentry-status/index.html
  content/zh/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/serviceentry-status/index.html
Labels: size/L, auto-merge, release-notes-none

#15386 update hugo to v0.128.2
  netlify.toml
Labels: size/XS

#15393 [release-1.22] wasm: update link
  content/en/docs/concepts/wasm/index.md
Labels: size/XS, release-notes-none

#15395 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15385 [zh] Sync files in /events/banners/
  content/zh/events/banners/announcing-ambient-mesh.md
  content/zh/events/banners/istio-graduates-within-cncf.md
  content/zh/events/banners/kubernetes-1.22-with-older-releases.md
Labels: kind/docs, translation/chinese, size/S

#15396 [zh] Sync #15392 WASM Hub link fix into Chinese
  content/zh/docs/concepts/wasm/index.md
Labels: kind/docs, translation/chinese, size/XS

#15397 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15400 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/S, auto-merge, release-notes-none

#15401 [zh] sync /setup/getting-started
  content/zh/docs/setup/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS

#15402 Fix z-index of front page text and animation
  content/en/_index.html
  content/zh/_index.html
  src/sass/base/_constants.scss
  src/sass/misc/_landing.scss
  src/ts/headerAnimation.js
Labels: kind/docs, size/S

#15405 [release-1.22] [zh] Sync #14996 part of home page changes into Chinese
  content/zh/_index.html
  content/zh/docs/ops/deployment/architecture/cni/index.md
  content/zh/docs/overview/_index.md
  content/zh/docs/reference/glossary/ebpf.md
  content/zh/docs/reference/glossary/waypoint.md
  i18n/zh.toml
Labels: size/L, release-notes-none

#15407 [release-1.22] Fix z-index of front page text and animation
  content/en/_index.html
  content/zh/_index.html
  src/sass/base/_constants.scss
  src/sass/misc/_landing.scss
  src/ts/headerAnimation.js
Labels: size/S, release-notes-none

#15409 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15408 Update shared drive location
  content/en/get-involved/_index.md
  content/zh/get-involved/_index.md
Labels: size/XS

#15399 [zh] Sync metrics/customize-metrics/index.md
  content/zh/docs/tasks/observability/metrics/customize-metrics/index.md
Labels: kind/docs, translation/chinese, size/S

#15394 Fix docs on customTags
  content/en/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
  content/en/docs/tasks/observability/distributed-tracing/telemetry-api/snips.sh
Labels: size/XS, ok-to-test

#15411 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#15412 [zh] Sync #15394 customTags fix for otel doc into Chinese
  content/zh/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
Labels: kind/docs, translation/chinese, size/XS

#15413 Revise documentation to remove outdated references to Pilot, Galley and Citadel
  .spelling
  content/en/about/faq/metrics-and-logs/prometheus-application-metrics.md
  content/en/docs/ops/best-practices/traffic-management/index.md
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/en/docs/ops/deployment/architecture/arch.svg
  content/en/docs/ops/deployment/architecture/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/platform-setup/gke/index.md
  content/en/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
Labels: kind/docs, size/M

#15415 [release-1.22] Revise documentation to remove outdated references to Pilot, Galley and Citadel
  .spelling
  content/en/about/faq/metrics-and-logs/prometheus-application-metrics.md
  content/en/docs/ops/best-practices/traffic-management/index.md
  content/en/docs/ops/common-problems/security-issues/index.md
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/en/docs/ops/deployment/architecture/arch.svg
  content/en/docs/ops/deployment/architecture/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/platform-setup/gke/index.md
  content/en/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
Labels: size/M, release-notes-none

#15414 New Google Analytics property IDs
  data/args.yml
Labels: kind/docs, size/XS, cherrypick/release-1.22

#15418 [release-1.22] New Google Analytics property IDs
  data/args.yml
Labels: size/XS, release-notes-none

#15423 Clarify ztunnel isn't required to talk to a waypoint.
  content/en/docs/ambient/overview/index.md
Labels: kind/docs, size/XS, area/ambient, cherrypick/release-1.22

#15424 [release-1.22] Clarify ztunnel isn't required to talk to a waypoint.
  content/en/docs/ambient/overview/index.md
Labels: size/XS, release-notes-none

#15416 [zh] Sync #15413 remove outdated Pilot, Galley and Citadel into Chinese
  content/zh/about/faq/metrics-and-logs/prometheus-application-metrics.md
  content/zh/docs/ops/best-practices/traffic-management/index.md
  content/zh/docs/ops/common-problems/security-issues/index.md
  content/zh/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/zh/docs/ops/deployment/architecture/arch.svg
  content/zh/docs/ops/deployment/architecture/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
  content/zh/docs/setup/install/operator/index.md
  content/zh/docs/setup/platform-setup/gke/index.md
  content/zh/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
Labels: translation/chinese, size/XL

#15427 [zh] Sync deployment/architecture/arch.svg and revise a few text
  content/zh/docs/ops/deployment/architecture/arch.svg
  content/zh/docs/ops/deployment/architecture/index.md
Labels: kind/docs, translation/chinese, size/XL

#15421 Add 1.22.3 and 1.21.5 release notes
  content/en/news/releases/1.21.x/announcing-1.21.5/index.md
  content/en/news/releases/1.22.x/announcing-1.22.3/index.md
Labels: area/test and release, size/M

#15428 [cherrypick] 1.22.3 1.21.5 release notes
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/ambient/install/helm-installation/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.21.x/announcing-1.21.5/index.md
  content/en/news/releases/1.22.x/announcing-1.22.3/index.md
  data/args.yml
Labels: size/L

#15430 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#15431 fix typo
  content/en/news/releases/1.22.x/announcing-1.22.3/index.md
Labels: size/XS, cherrypick/release-1.22

#15432 [release-1.22] fix typo
  content/en/news/releases/1.22.x/announcing-1.22.3/index.md
Labels: size/XS, release-notes-none

#15429 [zh] Sync release notes 1.21.5 and 1.22.3 into Chinese
  content/zh/news/releases/1.21.x/announcing-1.21.5/index.md
  content/zh/news/releases/1.22.x/announcing-1.22.3/index.md
Labels: kind/docs, translation/chinese, size/M

#15434 [release-1.22] update reference documents
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
Labels: kind/docs, size/M

#15435 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15437 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/M, auto-merge, release-notes-none

#15438 [zh] Sync common-problems/security-issues/
  content/zh/docs/ops/common-problems/security-issues/index.md
Labels: kind/docs, translation/chinese, size/L

#15439 [zh] update ops/common-problems/network-issues/
  content/zh/docs/ops/common-problems/network-issues/index.md
Labels: kind/docs, translation/chinese, size/M

#15440 fix top of page scrolling when a banner is visible
  src/sass/base/_constants.scss
  src/ts/events.ts
Labels: size/XS, cherrypick/release-1.22

#15444 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15447 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/L, auto-merge, release-notes-none

#15454 [zh] improve tls-configuration mtls-migration custom-ca-k8s
  content/zh/docs/ops/configuration/traffic-management/tls-configuration/index.md
  content/zh/docs/tasks/security/authentication/mtls-migration/index.md
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: translation/chinese, size/L

#15456 update hugo to v0.129.0
  netlify.toml
Labels: size/XS

#15443 prepare for v1.23
  Makefile.core.mk
  content/en/docs/ambient/getting-started/cleanup/index.md
  content/en/docs/ambient/getting-started/cleanup/snips.sh
  content/en/docs/ambient/getting-started/deploy-sample-app/snips.sh
  content/en/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/en/docs/ambient/getting-started/enforce-auth-policies/snips.sh
  content/en/docs/ambient/getting-started/test.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/snips.sh
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/ops/configuration/mesh/config-resource-ready/index.md
  content/en/docs/ops/configuration/mesh/config-resource-ready/snips.sh
  content/en/docs/ops/configuration/mesh/config-resource-ready/test.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
  content/en/docs/reference/config/config-status/index.md
  content/en/docs/setup/upgrade/canary/index.md
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/en/docs/tasks/traffic-management/circuit-breaking/index.md
  content/en/docs/tasks/traffic-management/circuit-breaking/snips.sh
  content/en/docs/tasks/traffic-management/circuit-breaking/test.sh
  content/zh/docs/ambient/getting-started/cleanup/index.md
  content/zh/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/zh/docs/ambient/usage/extend-waypoint-wasm/index.md
  data/args.yml
  go.mod
  go.sum
Labels: kind/docs, size/XL

#15467 Automator: update common-files@master in istio/istio.io@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15451 docs: show the page title above the TOC for generated pages.
  layouts/partials/toc.html
Labels: kind/docs, size/XS

#15466 [zh] Sync #15443 prepare for 1.23 update into Chinese
  content/zh/docs/ops/configuration/mesh/config-resource-ready/index.md
  content/zh/docs/reference/config/config-status/index.md
  content/zh/docs/setup/upgrade/canary/index.md
  content/zh/docs/tasks/traffic-management/circuit-breaking/index.md
Labels: kind/docs, translation/chinese, size/L

#15468 fix date line on mobile, tablet
  src/sass/misc/_blog.scss
Labels: size/XS

#15453 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#15469 [zh] Revise ops/diagnostic-tools/cni/
  content/zh/docs/ops/diagnostic-tools/cni/index.md
Labels: kind/docs, translation/chinese, size/M

#15471 Declare Istio 1.20 support is dropped
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none, cherrypick/release-1.22

#15473 [release-1.22] Declare Istio 1.20 support is dropped
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#15472 move dualstack to alpha
  content/en/docs/setup/additional-setup/dual-stack/index.md
Labels: size/XS

#15470 bump istio and re-enable dns alloc tests
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
  go.mod
  go.sum
Labels: kind/docs, size/S

#15475 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15477 [zh] Sync #15472 move dualstack to alpha into Chinese
  content/zh/docs/setup/additional-setup/dual-stack/index.md
Labels: kind/docs, translation/chinese, size/XS

#15478 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
Labels: size/S, auto-merge, release-notes-none

#15480 [zh] Fix the step for creating a 'helloworld-credential' secret
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: size/XS, ok-to-test

#15482 [zh] Fix the indentation issue in the command for the task 'Ingress Sidecar TLS Termination'
  content/zh/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/index.md
Labels: kind/docs, size/S, ok-to-test

#15446 fix formatting in mirroring task
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/test.sh
Labels: kind/docs, size/XL

#15481 [zh] Sync and update setup/getting-started/
  content/zh/docs/setup/getting-started/index.md
Labels: kind/docs, translation/chinese, size/M

#15485 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15487 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15484 [zh] Sync #15446 mirroring task format fix into Chinese
  content/zh/docs/tasks/traffic-management/mirroring/index.md
Labels: kind/docs, translation/chinese, size/XL

#15436 Update sidecar getting started guide
  content/en/blog/2024/v1-apis/index.md
  content/en/boilerplates/trace-generation.md
  content/en/docs/ops/diagnostic-tools/istioctl/index.md
  content/en/docs/ops/integrations/spire/index.md
  content/en/docs/setup/additional-setup/customize-installation-helm/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
  content/en/docs/setup/additional-setup/download-istio-release/index.md
  content/en/docs/setup/additional-setup/getting-started-istio-apis/index.md
  content/en/docs/setup/additional-setup/getting-started-istio-apis/kiali-example2.png
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/additional-setup/getting-started-istio-apis/test.sh
  content/en/docs/setup/getting-started/bookinfo-browser.png
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/test.sh
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/install/virtual-machine/index.md
  content/en/docs/setup/platform-setup/kind/index.md
  content/en/docs/setup/upgrade/in-place/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/news/releases/1.16.x/announcing-1.16/upgrade-notes/index.md
  layouts/shortcodes/relnote.html
Labels: size/XL

#15497 [release-1.20] Update istio.io test reference to 1.20.8
  go.mod
  go.sum
Labels: size/S

#15479 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#15499 [zh] Sync #15474 waypoint doc update into Chinese
  content/zh/boilerplates/gateway-api-install-crds.md
  content/zh/boilerplates/gateway-api-remove-crds.md
  content/zh/docs/ambient/getting-started/_index.md
  content/zh/docs/ambient/getting-started/cleanup/index.md
  content/zh/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/zh/docs/ambient/usage/waypoint/index.md
Labels: kind/docs, translation/chinese, size/L

#15491 [zh] Sync part of #15436 add get started istio apis page into Chinese
  content/zh/docs/setup/additional-setup/getting-started-istio-apis/index.md
  content/zh/docs/setup/additional-setup/getting-started-istio-apis/kiali-example2.png
Labels: kind/docs, translation/chinese, size/L

#15492 [zh] Sync part of #15436 update get started page into Chinese
  content/zh/docs/setup/getting-started/bookinfo-browser.png
  content/zh/docs/setup/getting-started/index.md
Labels: kind/docs, translation/chinese, size/L

#15504 [release-1.22] Fix EOL dates for 21 and 22
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#15500 Fix ambient doc tests
  content/en/docs/ambient/getting-started/test.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/snips.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/test.sh
  tests/README.md
  tests/setup/README.md
Labels: size/L

#15506 update hugo to v0.130.0
  netlify.toml
Labels: size/XS
