Repository istio/istio.io, pull requests merged in 2024-05, with the labels that each got.

#14994 Refresh ambient architecture doc
  content/en/docs/ambient/architecture/index.md
Labels: kind/docs, size/M, area/ambient

#14995 Remove ztunnel hairpinning from docs
  content/en/docs/ambient/usage/ztunnel/index.md
  content/en/docs/ambient/usage/ztunnel/ztunnel-hairpin.png
Labels: kind/docs, size/S, area/ambient

#15004 Move HBONE section into its own doc
  content/en/docs/ambient/architecture/_index.md
  content/en/docs/ambient/architecture/tls-tunnel/hbone-packet.png
  content/en/docs/ambient/architecture/tls-tunnel/index.md
  content/en/docs/ambient/usage/ztunnel/index.md
  content/en/docs/reference/glossary/hbone.md
Labels: area/networking, kind/docs, size/M, area/ambient

#15015 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15016 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15009 1.19 EOL
  content/en/docs/releases/supported-releases/index.md
  data/compatibility/supportStatus.yml
Labels: area/test and release, size/XS, cherrypick/release-1.21

#15017 Sync ambient pod exclusion doc with https://github.com/istio/istio/pull/50804
  content/en/docs/ambient/usage/ztunnel/index.md
Labels: kind/docs, size/XS, area/ambient

#15019 [release-1.21] Cherry-pick #15009
  content/en/docs/releases/supported-releases/index.md
  data/compatibility/supportStatus.yml
Labels: size/XS

#15020 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15010 move architecture docs
  content/en/docs/ambient/architecture/_index.md
  content/en/docs/ambient/architecture/hbone/hbone-packet.png
  content/en/docs/ambient/architecture/hbone/index.md
  content/en/docs/ambient/architecture/traffic-redirection/index.md
  content/en/docs/ambient/architecture/traffic-redirection/pod-added-to-ambient.svg
  content/en/docs/ambient/architecture/traffic-redirection/traffic-flows-between-pods-in-ambient.svg
  content/en/docs/ambient/architecture/traffic-routing/index.md
  content/en/docs/ambient/usage/ztunnel/index.md
  content/en/docs/ops/deployment/requirements/index.md
  content/en/docs/reference/glossary/hbone.md
Labels: size/L

#15021 [zh] Sync #15009 1.19 EOL into Chinese
  content/zh/docs/releases/supported-releases/index.md
Labels: translation/chinese, size/XS

#15024 Move non-usage stuff out of ztunnel usage guide
  content/en/docs/ambient/architecture/_index.md
  content/en/docs/ambient/architecture/control-plane/index.md
  content/en/docs/ambient/architecture/control-plane/ztunnel-architecture.png
  content/en/docs/ambient/architecture/data-plane/index.md
  content/en/docs/ambient/architecture/data-plane/ztunnel-datapath-1.png
  content/en/docs/ambient/architecture/data-plane/ztunnel-waypoint-datapath.png
  content/en/docs/ambient/architecture/traffic-routing/index.md
  content/en/docs/ambient/usage/ztunnel/index.md
  content/en/docs/reference/glossary/data-plane.md
  content/en/docs/reference/glossary/ztunnel.md
Labels: area/networking, kind/docs, size/L, area/ambient

#15026 Remove current caveat section
  content/en/docs/ambient/usage/ztunnel/index.md
Labels: size/S

#15027 Add more ztunnel architectural context
  content/en/docs/ambient/architecture/data-plane/index.md
  content/en/docs/ambient/architecture/hbone/index.md
  content/en/docs/ambient/architecture/traffic-redirection/index.md
Labels: kind/docs, size/M, area/ambient

#15011 update Managing In-Mesh Certificates page
  content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
Labels: size/XS, ok-to-test

#15013 [zh] Sync #14995 remove ztunnel hairpinning from doc into Chinese
  content/zh/docs/ambient/usage/ztunnel/index.md
  content/zh/docs/ambient/usage/ztunnel/ztunnel-hairpin.png
Labels: kind/docs, translation/chinese, size/M

#15022 [zh] Sync #15017 ambient pod exclusion doc into Chinese
  content/zh/docs/ambient/usage/ztunnel/index.md
Labels: kind/docs, translation/chinese, size/XS

#15002 [zh] Sync #15001 use targetrefs instead in get started doc into Chinese
  content/zh/docs/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS

#15031 [zh] Sync #15011 update Managing In-Mesh Certificates page into Chinese
  content/zh/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
Labels: kind/docs, translation/chinese, size/XS

#15012 [zh] Sync #14994 refresh ambient architecture doc into Chinese
  content/zh/docs/ambient/architecture/index.md
Labels: kind/docs, translation/chinese, size/L

#15033 [zh] Sync #15004 move HBONE section into its own doc into Chinese
  content/zh/docs/ambient/architecture/_index.md
  content/zh/docs/ambient/architecture/tls-tunnel/hbone-packet.png
  content/zh/docs/ambient/architecture/tls-tunnel/index.md
  content/zh/docs/ambient/usage/ztunnel/index.md
  content/zh/docs/reference/glossary/hbone.md
Labels: kind/docs, translation/chinese, size/M

#15034 [zh] Sync #15010 move architecture docs into Chinese
  content/zh/docs/ambient/architecture/_index.md
  content/zh/docs/ambient/architecture/hbone/hbone-packet.png
  content/zh/docs/ambient/architecture/hbone/index.md
  content/zh/docs/ambient/architecture/traffic-redirection/index.md
  content/zh/docs/ambient/architecture/traffic-redirection/pod-added-to-ambient.svg
  content/zh/docs/ambient/architecture/traffic-redirection/traffic-flows-between-pods-in-ambient.svg
  content/zh/docs/ambient/architecture/traffic-routing/index.md
  content/zh/docs/ambient/usage/ztunnel/index.md
  content/zh/docs/ops/deployment/requirements/index.md
  content/zh/docs/reference/glossary/hbone.md
Labels: kind/docs, translation/chinese, size/L

#15036 [zh] Localized an image: alpn-based-tunneling-protocol.svg
  content/zh/docs/tasks/observability/metrics/tcp-metrics/alpn-based-tunneling-protocol.svg
Labels: translation/chinese, size/L

#15035 [zh] Translate two SVGs in ambient/architecture
  content/zh/docs/ambient/architecture/traffic-redirection/index.md
  content/zh/docs/ambient/architecture/traffic-redirection/pod-added-to-ambient.svg
  content/zh/docs/ambient/architecture/traffic-redirection/traffic-flows-between-pods-in-ambient.svg
Labels: translation/chinese, size/XXL

#15030 docs: add cloudraft in professional service
  data/companies.yml
  static/logos/cloudraft.svg
Labels: kind/docs, size/XS, ok-to-test

#15040 [zh] document translation sync
  content/zh/docs/tasks/observability/metrics/telemetry-api/index.md
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: size/M

#15029 Automator: update istio@ test reference
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/L, release-notes-none

#15028 Refactor ztunnel docs
  content/en/docs/ambient/_index.md
  content/en/docs/ambient/architecture/_index.md
  content/en/docs/ambient/architecture/traffic-redirection/index.md
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/install/_index.md
  content/en/docs/ambient/overview/index.md
  content/en/docs/ambient/upgrade/_index.md
  content/en/docs/ambient/usage/_index.md
  content/en/docs/ambient/usage/add-workloads/index.md
  content/en/docs/ambient/usage/debugging/index.md
  content/en/docs/ambient/usage/policy/index.md
  content/en/docs/ambient/usage/waypoint/index.md
  content/en/docs/ambient/usage/ztunnel/index.md
Labels: size/XL

#15007 initial waypoint guide
  content/en/docs/ambient/usage/waypoint/index.md
Labels: kind/docs, size/L, area/ambient

#15042 [zh] Sync #15026 remove caveat section from ztunnel into Chinese
  content/zh/docs/ambient/usage/ztunnel/index.md
Labels: kind/docs, translation/chinese, size/S

#15045 Correct the indentation in the cleanup section of the egress-tls-origination task
  content/en/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
Labels: kind/docs, size/XS, ok-to-test

#14856 Add Sampling configuration page
  .spelling
  content/en/docs/tasks/observability/distributed-tracing/sampling/index.md
  content/en/docs/tasks/observability/distributed-tracing/sampling/mesh_test.sh
  content/en/docs/tasks/observability/distributed-tracing/sampling/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/sampling/telemetry_test.sh
Labels: area/extensions and telemetry, size/L

#15048 move bookinfo version earlier & change tcp/tlsroute to alpha
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/ambient/usage/waypoint/index.md
Labels: kind/docs, size/XS, area/ambient

#15049 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#15050 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#14702 Add operational document on configuration scoping
  content/en/docs/ops/configuration/mesh/configuration-scoping/index.md
  content/en/docs/ops/deployment/performance-and-scalability/index.md
Labels: size/L

#15056 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14981 v1 APIs and Stable Profile announcement
  content/en/blog/2024/v1-apis/index.md
Labels: area/extensions and telemetry, area/security, area/environments, area/networking, kind/docs, area/user experience, size/L

#15058 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15051 Waypoint doc updates
  content/en/docs/ambient/architecture/_index.md
  content/en/docs/ambient/architecture/traffic-redirection/index.md
  content/en/docs/ambient/usage/add-workloads/index.md
  content/en/docs/ambient/usage/l4-policy/index.md
  content/en/docs/ambient/usage/l7-features/index.md
  content/en/docs/ambient/usage/policy/index.md
  content/en/docs/ambient/usage/troubleshoot-waypoint/index.md
  content/en/docs/ambient/usage/troubleshoot-ztunnel/index.md
  content/en/docs/ambient/usage/waypoint/index.md
  content/en/docs/reference/glossary/cni.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XL

#15062 update callout css
  src/sass/misc/_callout.scss
  src/sass/themes/_light-theme.scss
Labels: kind/docs, size/M, ok-to-test

#15063 [zh] Translate Ambient waypoint usage doc into Chinese
  content/zh/docs/ambient/usage/waypoint/index.md
Labels: kind/docs, translation/chinese, size/L

#15052 [zh] Translate Trace Sampling doc into Chinese
  content/zh/docs/tasks/observability/distributed-tracing/sampling/index.md
Labels: kind/docs, translation/chinese, size/L

#15060 [zh] Translate v1 API blog into Chinese
  content/zh/blog/2024/v1-apis/index.md
Labels: kind/docs, translation/chinese, size/L

#15047 [zh] improve `egress` translation for egress docs
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: kind/docs, translation/chinese, size/L

#15054 [zh] Translate Configuration Scoping doc into Chinese
  content/zh/docs/ops/configuration/mesh/configuration-scoping/index.md
Labels: kind/docs, translation/chinese, size/L

#15057 [zh] Translate Ambient Control Plane and Data Plane docs into Chinese
  content/zh/docs/ambient/architecture/_index.md
  content/zh/docs/ambient/architecture/control-plane/index.md
  content/zh/docs/ambient/architecture/control-plane/ztunnel-architecture.png
  content/zh/docs/ambient/architecture/data-plane/index.md
  content/zh/docs/ambient/architecture/data-plane/ztunnel-datapath-1.png
  content/zh/docs/ambient/architecture/data-plane/ztunnel-waypoint-datapath.png
Labels: kind/docs, translation/chinese, size/L

#15068 Automator: update istio@ test reference
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-support.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/M, release-notes-none

#15071 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15070 add ambient beta blog
  content/en/blog/2024/ambient-reaches-beta/index.md
Labels: kind/docs, size/L, area/ambient

#15044 1.22 releasenotes
  .spelling
  content/en/news/releases/1.22.x/_index.md
  content/en/news/releases/1.22.x/announcing-1.22/_index.md
  content/en/news/releases/1.22.x/announcing-1.22/change-notes/index.md
  content/en/news/releases/1.22.x/announcing-1.22/upgrade-notes/index.md
Labels: size/L

#15084 bump api and istio refs
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/index.md
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/test.sh
  go.mod
  go.sum
Labels: kind/docs, size/L

#15074 Copy edits for ambient blog
  content/en/blog/2024/ambient-reaches-beta/index.md
Labels: size/M, cherrypick/release-1.22

#15077 Fix some typos in 1.22 change notes
  content/en/news/releases/1.22.x/announcing-1.22/change-notes/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.22

#15087 remove missed ambient alpha warnings
  content/en/boilerplates/ambient-alpha-warning.md
  content/en/docs/ambient/upgrade/helm-upgrade/index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/zh/boilerplates/ambient-alpha-warning.md
  content/zh/docs/ambient/upgrade/helm-upgrade/index.md
  content/zh/docs/setup/additional-setup/config-profiles/index.md
Labels: kind/docs, size/M, cherrypick/release-1.22

#15088 remove opencensus docs
  content/en/about/faq/distributed-tracing/how-to-support-tracing.md
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/index.md
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-details.png
  content/en/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-list.png
  content/en/docs/tasks/observability/distributed-tracing/overview/index.md
Labels: kind/docs, size/L

#15089 [release-1.22] Copy edits for ambient blog
  content/en/blog/2024/ambient-reaches-beta/index.md
Labels: size/M, release-notes-none

#15090 [release-1.22] Fix some typos in 1.22 change notes
  content/en/news/releases/1.22.x/announcing-1.22/change-notes/index.md
Labels: size/XS, release-notes-none

#15091 [release-1.22] remove missed ambient alpha warnings
  content/en/boilerplates/ambient-alpha-warning.md
  content/en/docs/ambient/upgrade/helm-upgrade/index.md
  content/en/docs/setup/additional-setup/config-profiles/index.md
  content/zh/boilerplates/ambient-alpha-warning.md
  content/zh/docs/ambient/upgrade/helm-upgrade/index.md
  content/zh/docs/setup/additional-setup/config-profiles/index.md
Labels: size/M, release-notes-none

#15083 Updates integrations/certmanager doc page with tips for issuer and acme
  content/en/docs/ops/integrations/certmanager/index.md
Labels: kind/docs, size/M, ok-to-test, cherrypick/release-1.22

#15092 fix link alias
  content/en/news/releases/1.22.x/announcing-1.22/_index.md
Labels: size/XS, cherrypick/release-1.22

#15093 [release-1.22] fix link alias
  content/en/news/releases/1.22.x/announcing-1.22/_index.md
Labels: size/XS, release-notes-none

#15064 [zh] Translate Ambient troubleshoot ztunnel doc into Chinese
  content/zh/docs/ambient/usage/troubleshoot-ztunnel/index.md
Labels: kind/docs, translation/chinese, size/L

#15065 [zh] Translate Ambient L4 policy usage doc into Chinese
  content/zh/docs/ambient/usage/l4-policy/index.md
  content/zh/docs/reference/glossary/cni.md
Labels: kind/docs, translation/chinese, size/L

#15094 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15067 [zh] Translate Ambient L7 feature doc into Chinese
  content/zh/docs/ambient/usage/l7-features/index.md
Labels: kind/docs, translation/chinese, size/L

#15085 added link for quick start in spire
  content/en/docs/ops/integrations/spire/index.md
Labels: kind/docs, size/XS

#15095 [zh] Sync Ambient overview and remove ztunnel docs into Chinese
  content/zh/docs/ambient/architecture/traffic-routing/index.md
  content/zh/docs/ambient/overview/index.md
Labels: kind/docs, translation/chinese, size/L

#15080 [zh] Translate Ambient add workload doc into Chinese
  content/zh/docs/ambient/usage/add-workloads/index.md
Labels: kind/docs, translation/chinese, size/L

#15041 Wasm Configuration for Ambient Mode
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: size/L, cherrypick/release-1.22

#15097 Wasm Configuration for Ambient Mode release-1.22 branch
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: size/L

#15066 [zh] Sync the latest Ambient HBONE and traffic redirection docs into Chinese
  content/zh/docs/ambient/architecture/_index.md
  content/zh/docs/ambient/architecture/hbone/index.md
  content/zh/docs/ambient/architecture/traffic-redirection/index.md
Labels: kind/docs, translation/chinese, size/L

#15076 [zh] Translate Gateway API Mesh stable blog into Chinese
  content/zh/blog/2024/gateway-mesh-ga/index.md
Labels: kind/docs, translation/chinese, size/L

#15078 [zh] Translate Ambient beta blog into Chinese
  content/zh/blog/2024/ambient-reaches-beta/index.md
Labels: kind/docs, translation/chinese, size/L

#15098 [zh] Translate 1.22 change note into Chinese
  content/zh/news/releases/1.22.x/announcing-1.22/change-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15100 Fix links in ambient usage and architecture docs
  content/en/docs/ambient/architecture/data-plane/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: kind/docs, size/S, area/ambient

#15104 [release-1.22] Fix links in ambient usage and architecture docs
  content/en/docs/ambient/architecture/data-plane/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: size/S, release-notes-none

#15101 [zh] Translate 1.22 release announcement into Chinese
  content/zh/news/releases/1.22.x/_index.md
  content/zh/news/releases/1.22.x/announcing-1.22/_index.md
Labels: kind/docs, translation/chinese, size/L

#15105 [zh] Sync 1.22 upgrade note with #15083 #15085 update into Chinese
  content/zh/docs/ops/integrations/certmanager/index.md
  content/zh/docs/ops/integrations/spire/index.md
  content/zh/news/releases/1.22.x/announcing-1.22/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15106 [zh] Sync #15088 remove OpenCensus into Chinese
  content/zh/about/faq/distributed-tracing/how-to-support-tracing.md
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/index.md
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-details.png
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/istio-tracing-list.png
  content/zh/docs/tasks/observability/distributed-tracing/overview/index.md
Labels: kind/docs, translation/chinese, size/L

#15102 [zh] Translate ambient/usage/troubleshoot-waypoint/
  content/zh/docs/ambient/usage/troubleshoot-waypoint/index.md
Labels: kind/docs, translation/chinese, size/L

#15107 [zh] improve production-testing
  content/zh/docs/examples/microservices-istio/production-testing/index.md
Labels: size/XS

#15111 Automator: update common-files@release-1.20 in istio/istio.io@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15108 Add note about `RunAs` fields in Customizing Injection section
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: size/XS, cherrypick/release-1.22

#15112 [release-1.22] Add note about `RunAs` fields in Customizing Injection section
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: size/XS, release-notes-none

#15116 [release-1.22] Link to wasm document from layer 7 features
  content/en/docs/ambient/usage/l7-features/index.md
Labels: size/XS, release-notes-none

#15120 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15122 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15117 Add a note about init containers and OpenShift
  content/en/docs/setup/additional-setup/cni/index.md
Labels: size/XS, cherrypick/release-1.22

#15126 [release-1.22] Add a note about init containers and OpenShift
  content/en/docs/setup/additional-setup/cni/index.md
Labels: size/XS, release-notes-none

#15118 Wasm Configuration for Ambient Mode - Test
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/snips.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/test.sh
Labels: size/L, cherrypick/release-1.22

#15127 [release-1.22] Wasm Configuration for Ambient Mode - Test
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/snips.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/test.sh
Labels: size/L, release-notes-none

#15103 Update Istio documentation to reflect stable Kubernetes Gateway API support
  content/en/boilerplates/gateway-api-future.md
Labels: size/XS, cherrypick/release-1.22

#15131 Update Istio documentation to reflect stable Kubernetes Gateway API support - Release-1.22
  content/en/boilerplates/gateway-api-future.md
Labels: size/XS

#15132 Wasm Configuration for Ambient Mode - Fixes
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: size/XS, cherrypick/release-1.22

#15133 [release-1.22] Wasm Configuration for Ambient Mode - Fixes
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: size/XS, release-notes-none

#15124 [zh] Sync #15110 link Wasm doc from L7 feature into Chinese
  content/zh/docs/ambient/usage/l7-features/index.md
Labels: kind/docs, translation/chinese, size/XS

#15125 [zh] Sync #15108 add note about `RunAs` fields in Customizing Injection section into Chinese
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: kind/docs, translation/chinese, size/XS

#15129 [zh] Sync #15117 note about init containers and OpenShift into Chinese
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, translation/chinese, size/XS

#15130 [zh] Sync #15103 #15118 into Chinese
  content/zh/boilerplates/gateway-api-future.md
  content/zh/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: kind/docs, translation/chinese, size/XS

#15139 [release-1.22] fix text field
  content/en/docs/ambient/usage/l4-policy/index.md
Labels: size/XS, release-notes-none

#15140 [zh] Sync ambient/usage/l4-policy/ with #15138
  content/zh/docs/ambient/usage/l4-policy/index.md
Labels: translation/chinese, size/S

#15135 [zh] Sync #15132 Wasm config fix into Chinese
  content/zh/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: kind/docs, translation/chinese, size/XS

#15145 [zh] sync /docs/tasks/traffic-management/egress/egress-gateway
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: kind/docs, size/XS, ok-to-test

#15149 [zh] Remove ztunnel docs from ambient/usage
  content/zh/docs/ambient/usage/ztunnel/index.md
  content/zh/docs/ambient/usage/ztunnel/ztunnel-architecture.png
  content/zh/docs/ambient/usage/ztunnel/ztunnel-datapath-1.png
  content/zh/docs/ambient/usage/ztunnel/ztunnel-waypoint-datapath.png
Labels: kind/docs, translation/chinese, size/XL

#15147 update hugo to v0.126.1
  netlify.toml
Labels: size/XS

#15121 Fixup kmod prereqs
  content/en/about/deployment/index.md
  content/en/about/faq/security/mysql-with-mtls.md
  content/en/blog/2024/inpod-traffic-redirection-ambient/index.md
  content/en/boilerplates/helm-prereqs.md
  content/en/docs/examples/microservices-istio/logs-istio/index.md
  content/en/docs/ops/best-practices/security/index.md
  content/en/docs/ops/common-problems/network-issues/index.md
  content/en/docs/ops/common-problems/observability-issues/index.md
  content/en/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/en/docs/ops/deployment/application-requirements/index.md
  content/en/docs/ops/deployment/platform-requirements/index.md
  content/en/docs/ops/diagnostic-tools/istioctl-describe/index.md
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/additional-setup/customize-installation-helm/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
  content/en/docs/setup/additional-setup/getting-started/index.md
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/install/istioctl/index.md
  content/en/docs/setup/install/operator/index.md
  content/en/docs/setup/install/virtual-machine/index.md
  content/en/docs/setup/platform-setup/prerequisites/index.md
  content/en/docs/tasks/traffic-management/request-routing/index.md
  content/en/news/releases/1.3.x/announcing-1.3/change-notes/index.md
Labels: area/networking, kind/docs, size/L, area/ambient, cherrypick/release-1.22

#15146 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#15123 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/networking/workload-entry/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
  content/en/docs/reference/config/proxy_extensions/accesslogpolicy/index.html
  content/en/docs/reference/config/proxy_extensions/stackdriver/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/en/docs/reference/config/type/workload-selector/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/networking/workload-entry/index.html
  content/zh/docs/reference/config/networking/workload-group/index.html
  content/zh/docs/reference/config/proxy_extensions/accesslogpolicy/index.html
  content/zh/docs/reference/config/proxy_extensions/stackdriver/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/type/workload-selector/index.html
  data/features.yaml
Labels: size/XXL, auto-merge, release-notes-none

#15153 [zh] Sync #15121 fixup kmod prereqs into Chinese
  content/zh/about/deployment/index.md
  content/zh/about/faq/security/mysql-with-mtls.md
  content/zh/blog/2024/inpod-traffic-redirection-ambient/index.md
  content/zh/boilerplates/helm-prereqs.md
  content/zh/docs/examples/microservices-istio/logs-istio/index.md
  content/zh/docs/ops/best-practices/security/index.md
  content/zh/docs/ops/common-problems/network-issues/index.md
  content/zh/docs/ops/common-problems/observability-issues/index.md
  content/zh/docs/ops/configuration/traffic-management/protocol-selection/index.md
  content/zh/docs/ops/deployment/application-requirements/index.md
  content/zh/docs/ops/deployment/platform-requirements/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl-describe/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
  content/zh/docs/setup/additional-setup/customize-installation-helm/index.md
  content/zh/docs/setup/additional-setup/customize-installation/index.md
  content/zh/docs/setup/additional-setup/getting-started/index.md
  content/zh/docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/virtual-machine/index.md
  content/zh/docs/setup/platform-setup/prerequisites/index.md
  content/zh/docs/tasks/traffic-management/request-routing/index.md
  content/zh/news/releases/1.3.x/announcing-1.3/change-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15136 Wasm Configuration for Ambient Mode - Updates
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/snips.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/test.sh
Labels: size/M

#15154 [zh] Sync #15136 Wasm configuration updae for Ambient mode into Chinese
  content/zh/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: translation/chinese, size/M

#15157 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15158 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15152 Updates Ambient Getting Started Guide
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/ambient/getting-started/test.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/test.sh
Labels: kind/docs, size/M, area/ambient, cherrypick/release-1.22

#15160 [release-1.22] Updates Ambient Getting Started Guide
  content/en/docs/ambient/getting-started/index.md
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/ambient/getting-started/test.sh
  content/en/docs/ambient/usage/extend-waypoint-wasm/test.sh
Labels: size/M, release-notes-none

#15150 Update documentation to not refer to experimental Gateway APIs
  content/en/boilerplates/gateway-api-gamma-experimental.md
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-experimental.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/request-routing/index.md
  content/en/docs/tasks/traffic-management/request-routing/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
Labels: size/M

#15162 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/XXL, auto-merge, release-notes-none

#15161 [zh] Sync #15152 into Chinese for ambient/getting-started
  content/zh/docs/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/M

#15163 [release-1.22] Update documentation to not refer to experimental Gateway APIs
  content/en/boilerplates/gateway-api-gamma-experimental.md
  content/en/boilerplates/snips/gateway-api-experimental.sh
  content/en/boilerplates/snips/gateway-api-gamma-experimental.sh
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  content/en/docs/tasks/traffic-management/mirroring/index.md
  content/en/docs/tasks/traffic-management/mirroring/snips.sh
  content/en/docs/tasks/traffic-management/request-routing/index.md
  content/en/docs/tasks/traffic-management/request-routing/snips.sh
  content/en/docs/tasks/traffic-management/request-timeouts/index.md
  content/en/docs/tasks/traffic-management/request-timeouts/snips.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/tcp-traffic-shifting/snips.sh
  content/en/docs/tasks/traffic-management/traffic-shifting/index.md
  content/en/docs/tasks/traffic-management/traffic-shifting/snips.sh
Labels: size/M, release-notes-none

#15164 [zh] Sync #15150 Gateway API ref update into Chinese
  content/zh/boilerplates/gateway-api-gamma-experimental.md
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/request-routing/index.md
  content/zh/docs/tasks/traffic-management/request-timeouts/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
  content/zh/docs/tasks/traffic-management/traffic-shifting/index.md
Labels: kind/docs, translation/chinese, size/S

#15170 add asiainfo company support again
  data/companies.yml
  static/logos/asiainfo.svg
Labels: size/L, ok-to-test, cherrypick/release-1.22

#15173 [release-1.22] add asiainfo company support again
  data/companies.yml
  static/logos/asiainfo.svg
Labels: size/L, release-notes-none

#15177 Improve the social sharing buttons
  layouts/blog/single.html
  layouts/partials/posts_share_social.html
  src/sass/base/_base.scss
  src/sass/misc/_blog.scss
Labels: size/M, cherrypick/release-1.22

#15178 [release-1.22] Improve the social sharing buttons
  layouts/blog/single.html
  layouts/partials/posts_share_social.html
  src/sass/base/_base.scss
  src/sass/misc/_blog.scss
Labels: size/M, release-notes-none

#15171 happy bday blog
  .spelling
  content/en/blog/2024/happy-7th-birthday/7th-birthday.png
  content/en/blog/2024/happy-7th-birthday/contribution.png
  content/en/blog/2024/happy-7th-birthday/dockerhub.png
  content/en/blog/2024/happy-7th-birthday/github-stars.png
  content/en/blog/2024/happy-7th-birthday/index.md
Labels: kind/docs, size/L

#15081 Announce upcoming 1.20 EOL
  content/en/news/support/announcing-1.20-eol/index.md
Labels: kind/docs, size/S, cherrypick/release-1.22

#15181 [zh] Sync 1.20 eol into Chinese
  content/zh/news/support/announcing-1.20-eol/index.md
Labels: kind/docs, translation/chinese, size/S, cherrypick/release-1.22

#15182 [release-1.22] [zh] Sync 1.20 eol into Chinese
  content/zh/news/support/announcing-1.20-eol/index.md
Labels: size/S, release-notes-none

#15179 [release-1.22] Announce upcoming 1.20 EOL
  content/en/news/support/announcing-1.20-eol/index.md
Labels: size/S, release-notes-none

#15183 [release-1.22] happy bday blog
  .spelling
  content/en/blog/2024/happy-7th-birthday/7th-birthday.png
  content/en/blog/2024/happy-7th-birthday/contribution.png
  content/en/blog/2024/happy-7th-birthday/dockerhub.png
  content/en/blog/2024/happy-7th-birthday/github-stars.png
  content/en/blog/2024/happy-7th-birthday/index.md
Labels: size/L, release-notes-none

#15176 changed release name from 1.22 to 1.21
  content/en/docs/ops/deployment/performance-and-scalability/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.22

#15186 [zh] Sync #15176 changed release name from 1.22 to 1.21 into Chinese
  content/zh/docs/ops/deployment/performance-and-scalability/index.md
Labels: kind/docs, translation/chinese, size/XS, cherrypick/release-1.22

#15187 [release-1.22] [zh] Sync #15176 changed release name from 1.22 to 1.21 into Chinese
  content/zh/docs/ops/deployment/performance-and-scalability/index.md
Labels: size/XS, release-notes-none

#15180 [zh] Sync happy bday blog into Chinese
  content/zh/blog/2024/happy-7th-birthday/7th-birthday.png
  content/zh/blog/2024/happy-7th-birthday/contribution.png
  content/zh/blog/2024/happy-7th-birthday/dockerhub.png
  content/zh/blog/2024/happy-7th-birthday/github-stars.png
  content/zh/blog/2024/happy-7th-birthday/index.md
Labels: kind/docs, translation/chinese, size/L

#15189 [zh] Localization images in bookinfo
  content/zh/docs/examples/bookinfo/noistio.svg
  content/zh/docs/examples/bookinfo/withistio.svg
Labels: translation/chinese, size/XL

#15192 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15191 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#15193 [zh] Revise zh text in examples/bookinfo
  content/zh/docs/examples/bookinfo/index.md
Labels: kind/docs, translation/chinese, size/L

#15198 [zh] Revise examples: enable-istio-all-microservices
  content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
Labels: kind/docs, translation/chinese, size/M

#15072 Ambient policy enforcement
  .spelling
  content/en/docs/ambient/usage/l4-policy/index.md
  content/en/docs/ambient/usage/l7-features/index.md
  content/en/docs/reference/glossary/gateway-api.md
  content/en/docs/reference/glossary/hbone.md
  content/en/docs/reference/glossary/secure-l4-overlay.md
Labels: kind/docs, size/L, area/ambient, cherrypick/release-1.22

#15202 [release-1.22] Ambient policy enforcement
  .spelling
  content/en/docs/ambient/usage/l4-policy/index.md
  content/en/docs/ambient/usage/l7-features/index.md
  content/en/docs/reference/glossary/gateway-api.md
  content/en/docs/reference/glossary/hbone.md
  content/en/docs/reference/glossary/secure-l4-overlay.md
Labels: size/L, release-notes-none

#15204 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15206 updating statement about peer authn in l4-policy usage doc
  content/en/docs/ambient/usage/l4-policy/index.md
Labels: area/security, kind/docs, size/XS, area/ambient, cherrypick/release-1.22

#15209 [zh] Sync #15072 Ambient L7 usage update into Chinese
  content/zh/docs/ambient/usage/l7-features/index.md
  content/zh/docs/reference/glossary/gateway-api.md
  content/zh/docs/reference/glossary/secure-l4-overlay.md
Labels: kind/docs, translation/chinese, size/L

#15208 [zh] Sync ambient/usage/l4-policy/index.md
  content/zh/docs/ambient/usage/l4-policy/index.md
  content/zh/docs/reference/glossary/secure-l4-overlay.md
Labels: kind/docs, translation/chinese, size/L

#15211 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15188 [zh] improve vm-architecture observability-issues grafana
  content/zh/docs/ops/common-problems/observability-issues/index.md
  content/zh/docs/ops/deployment/vm-architecture/index.md
  content/zh/docs/ops/integrations/grafana/index.md
Labels: translation/chinese, size/L
