Repository istio/istio.io, pull requests merged in 2024-12, with the labels that each got.

#16027 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#16025 [uk] Cherrypick latest updates in 1.24 for Ukrainian translation
  content/uk/about/faq/distributed-tracing/disabling-tracing.md
  content/uk/about/faq/distributed-tracing/external-zipkin.md
  content/uk/about/faq/distributed-tracing/how-distributed-tracing-works.md
  content/uk/about/faq/distributed-tracing/how-envoy-based-tracing-works.md
  content/uk/about/faq/distributed-tracing/how-to-support-tracing.md
  content/uk/about/faq/distributed-tracing/initial-trace-header.md
  content/uk/about/faq/distributed-tracing/initial-zipkin-header.md
  content/uk/about/faq/distributed-tracing/minimal-requirements.md
  content/uk/about/faq/distributed-tracing/no-tracing.md
  content/uk/boilerplates/start-otel-collector-service.md
  content/uk/docs/ambient/architecture/control-plane/index.md
  content/uk/docs/ambient/architecture/control-plane/ztunnel-architecture.png
  content/uk/docs/ambient/architecture/control-plane/ztunnel-architecture.svg
  content/uk/docs/ambient/getting-started/_index.md
  content/uk/docs/ambient/getting-started/cleanup/index.md
  content/uk/docs/ambient/getting-started/deploy-sample-app/index.md
  content/uk/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/uk/docs/ambient/getting-started/manage-traffic/index.md
  content/uk/docs/ambient/getting-started/secure-and-visualize/index.md
  content/uk/docs/ambient/getting-started/secure-and-visualize/kiali-ambient-bookinfo.png
  content/uk/docs/ambient/getting-started/secure-and-visualize/kiali-tcp-traffic.png
  content/uk/docs/concepts/observability/index.md
  content/uk/docs/ops/integrations/jaeger/index.md
  content/uk/docs/ops/integrations/zipkin/index.md
  content/uk/docs/setup/additional-setup/compatibility-versions/index.md
  content/uk/docs/setup/additional-setup/config-profiles/index.md
  content/uk/docs/setup/additional-setup/customize-installation/index.md
  content/uk/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-explorer.png
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-services.png
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-details-lightstep.png
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-list-lightstep.png
  content/uk/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
  content/uk/docs/tasks/observability/distributed-tracing/opentelemetry/index.md
  content/uk/docs/tasks/observability/distributed-tracing/overview/index.md
  content/uk/docs/tasks/observability/distributed-tracing/sampling/index.md
  content/uk/docs/tasks/observability/distributed-tracing/skywalking/index.md
  content/uk/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
  content/uk/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/uk/docs/tasks/observability/logs/access-log/index.md
  content/uk/docs/tasks/observability/logs/otel-provider/index.md
  content/uk/docs/tasks/observability/metrics/customize-metrics/index.md
  content/uk/docs/tasks/traffic-management/egress/egress-control/index.md
  content/uk/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: size/XL, cherrypick/release-1.24

#16023 [zh] Sync #16007 the ambient mode quickstart update into Chinese
  content/zh/docs/ambient/getting-started/_index.md
  content/zh/docs/ambient/getting-started/cleanup/index.md
  content/zh/docs/ambient/getting-started/deploy-sample-app/index.md
  content/zh/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/zh/docs/ambient/getting-started/manage-traffic/index.md
  content/zh/docs/ambient/getting-started/secure-and-visualize/index.md
  content/zh/docs/ambient/getting-started/secure-and-visualize/kiali-ambient-bookinfo.png
  content/zh/docs/ambient/getting-started/secure-and-visualize/kiali-tcp-traffic.png
Labels: kind/docs, translation/chinese, size/L

#16033 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16035 GKE platform profile
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: area/environments, kind/docs, size/S, area/ambient

#16032 [uk] Add release notes for Istio 1.24.1 patch release
  content/uk/news/releases/1.24.x/announcing-1.24.1/index.md
Labels: size/M

#16031 [uk] Sync Ukrainian translation with upstream documentation
  content/uk/blog/2024/authz-policy-with-kyverno/dynamic-metadata.svg
  content/uk/blog/2024/authz-policy-with-kyverno/filters-chain.svg
  content/uk/blog/2024/authz-policy-with-kyverno/index.md
  content/uk/blog/2024/authz-policy-with-kyverno/overview.svg
  content/uk/docs/ambient/architecture/hbone/hbone-packet.png
  content/uk/docs/ambient/architecture/hbone/hbone-packet.svg
  content/uk/docs/ambient/architecture/hbone/index.md
  content/uk/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/uk/docs/ops/configuration/traffic-management/dns/index.md
  content/uk/docs/ops/integrations/skywalking/index.md
  content/uk/docs/setup/install/istioctl/index.md
  content/uk/docs/setup/install/multicluster/before-you-begin/index.md
  content/uk/docs/setup/install/multicluster/multi-primary/index.md
  content/uk/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/uk/docs/setup/install/multicluster/primary-remote/index.md
  content/uk/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/uk/docs/setup/install/multicluster/verify/index.md
  content/uk/docs/setup/platform-setup/kind/index.md
  content/uk/docs/tasks/observability/metrics/telemetry-api/index.md
Labels: size/XXL

#16030 update resource attachment
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XS, cherrypick/release-1.24

#16038 [release-1.24] update resource attachment
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/XS, release-notes-none

#16036 [zh] Sync #16035 GKE platform profile into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/M

#16041 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/workload-group/index.html
Labels: size/L, auto-merge, release-notes-none

#16039 Add warning for injection customization
  content/en/docs/setup/additional-setup/sidecar-injection/index.md
Labels: size/XS

#16048 Automator: update common-files@release-1.24 in istio/istio.io@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16049 Fix istioctl install command for OpenShift
  content/en/docs/setup/platform-setup/openshift/index.md
  content/uk/docs/setup/platform-setup/openshift/index.md
  content/zh/docs/setup/platform-setup/openshift/index.md
Labels: size/XS

#16043 [zh] Sync #16039 add warning for injection customization into Chinese
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
Labels: kind/docs, translation/chinese, size/XS

#16059 Automator: update common-files@release-1.22 in istio/istio.io@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16060 Do the thing we suggest instead of documenting the hard way
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/install/helm/test.sh
Labels: area/environments, size/M, cherrypick/release-1.24

#16063 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#16065 Fixup CRD upgrade note to (hopefully) be clearer
  content/en/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: size/XS, cherrypick/release-1.24

#16066 [release-1.24] Fixup CRD upgrade note to (hopefully) be clearer
  content/en/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: size/XS, release-notes-none

#16067 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16062 [zh] Sync #16060 use one cmd to create namespace with deploy into Chinese
  content/zh/docs/setup/install/helm/index.md
Labels: kind/docs, translation/chinese, size/S

#16058 [release-1.24] test babel fix for netlify
  Makefile.core.mk
Labels: size/XS, release-notes-none

#16064 Automator: update common-files@release-1.24 in istio/istio.io@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16055 [zh] Sync #16052 fixup istio-cni upgrade warning into Chinese
  content/zh/docs/ambient/upgrade/helm/index.md
Labels: kind/docs, translation/chinese, size/S

#16068 [zh] Sync #16065 fixup CRD upgrade note to (hopefully) be clearer into Chinese
  content/zh/news/releases/1.24.x/announcing-1.24/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/XS

#16070 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#16061 [release-1.24] Do the thing we suggest instead of documenting the hard way
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/install/helm/test.sh
Labels: size/M, release-notes-none

#16029 [release-1.24] [uk] Cherrypick latest updates in 1.24 for Ukrainian translation
  content/uk/about/faq/distributed-tracing/disabling-tracing.md
  content/uk/about/faq/distributed-tracing/external-zipkin.md
  content/uk/about/faq/distributed-tracing/how-distributed-tracing-works.md
  content/uk/about/faq/distributed-tracing/how-envoy-based-tracing-works.md
  content/uk/about/faq/distributed-tracing/how-to-support-tracing.md
  content/uk/about/faq/distributed-tracing/initial-trace-header.md
  content/uk/about/faq/distributed-tracing/initial-zipkin-header.md
  content/uk/about/faq/distributed-tracing/minimal-requirements.md
  content/uk/about/faq/distributed-tracing/no-tracing.md
  content/uk/boilerplates/start-otel-collector-service.md
  content/uk/docs/ambient/architecture/control-plane/index.md
  content/uk/docs/ambient/architecture/control-plane/ztunnel-architecture.png
  content/uk/docs/ambient/architecture/control-plane/ztunnel-architecture.svg
  content/uk/docs/ambient/getting-started/_index.md
  content/uk/docs/ambient/getting-started/cleanup/index.md
  content/uk/docs/ambient/getting-started/deploy-sample-app/index.md
  content/uk/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/uk/docs/ambient/getting-started/manage-traffic/index.md
  content/uk/docs/ambient/getting-started/secure-and-visualize/index.md
  content/uk/docs/ambient/getting-started/secure-and-visualize/kiali-ambient-bookinfo.png
  content/uk/docs/ambient/getting-started/secure-and-visualize/kiali-tcp-traffic.png
  content/uk/docs/concepts/observability/index.md
  content/uk/docs/ops/integrations/jaeger/index.md
  content/uk/docs/ops/integrations/zipkin/index.md
  content/uk/docs/setup/additional-setup/compatibility-versions/index.md
  content/uk/docs/setup/additional-setup/config-profiles/index.md
  content/uk/docs/setup/additional-setup/customize-installation/index.md
  content/uk/docs/tasks/observability/distributed-tracing/jaeger/index.md
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/index.md
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-explorer.png
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-services.png
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-details-lightstep.png
  content/uk/docs/tasks/observability/distributed-tracing/lightstep/istio-tracing-list-lightstep.png
  content/uk/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
  content/uk/docs/tasks/observability/distributed-tracing/opentelemetry/index.md
  content/uk/docs/tasks/observability/distributed-tracing/overview/index.md
  content/uk/docs/tasks/observability/distributed-tracing/sampling/index.md
  content/uk/docs/tasks/observability/distributed-tracing/skywalking/index.md
  content/uk/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
  content/uk/docs/tasks/observability/distributed-tracing/zipkin/index.md
  content/uk/docs/tasks/observability/logs/access-log/index.md
  content/uk/docs/tasks/observability/logs/otel-provider/index.md
  content/uk/docs/tasks/observability/metrics/customize-metrics/index.md
  content/uk/docs/tasks/traffic-management/egress/egress-control/index.md
  content/uk/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: size/XL, release-notes-none

#16071 fix Helm test error introduced in #16060
  content/en/docs/setup/upgrade/helm/common.sh
Labels: size/XS

#16072 [release-1.24] fix Helm test error introduced in #16060
  content/en/docs/setup/upgrade/helm/common.sh
Labels: size/XS, release-notes-none

#16069 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#16074 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/annotations/index.html
Labels: size/XS, auto-merge, release-notes-none

#16075 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16081 Fix typos and consistency for an example of microservices-istio
  content/en/docs/examples/microservices-istio/add-new-microservice-version/index.md
Labels: kind/docs, size/XS

#16080 [zh] Improve add-new-microservice-version/index.md
  content/zh/docs/examples/microservices-istio/add-new-microservice-version/index.md
Labels: kind/docs, translation/chinese, size/M

#16077 fix menu icon
  layouts/partials/primary_top.html
  src/icons/hamburger-sidebar.svg
Labels: area/user experience, size/XS

#16084 [release-1.24] fix menu icon
  layouts/partials/primary_top.html
  src/icons/hamburger-sidebar.svg
Labels: size/XS, release-notes-none

#16083 CSS changes for code blocks & message fields tables
  assets/sass/_all.scss
  assets/sass/misc/_code-blocks.scss
  assets/sass/misc/_message-fields.scss
  assets/sass/themes/_light-theme.scss
  assets/sass/themes/_vars.scss
  layouts/partials/code_block.html
Labels: size/M, cherrypick/release-1.24

#16085 [release-1.24] CSS changes for code blocks & message fields tables
  assets/sass/_all.scss
  assets/sass/misc/_code-blocks.scss
  assets/sass/misc/_message-fields.scss
  assets/sass/themes/_light-theme.scss
  assets/sass/themes/_vars.scss
  layouts/partials/code_block.html
Labels: size/M, release-notes-none

#16057 Explicitly document how to template manifests with both `helm` and `istioctl` and remove references to `istioctl manifest diff`
  content/en/about/faq/setup/install-method-selection.md
  content/en/docs/ambient/install/helm/index.md
  content/en/docs/ambient/install/istioctl/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: size/L, cherrypick/release-1.24

#16086 [release-1.24] Explicitly document how to template manifests with both `helm` and `istioctl` and remove references to `istioctl manifest diff`
  content/en/about/faq/setup/install-method-selection.md
  content/en/docs/ambient/install/helm/index.md
  content/en/docs/ambient/install/istioctl/index.md
  content/en/docs/setup/install/helm/index.md
  content/en/docs/setup/install/istioctl/index.md
Labels: size/L, release-notes-none

#16088 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/proxy-config/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/proxy-config/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
Labels: size/L, auto-merge, release-notes-none

#16092 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16093 Automator: update common-files@release-1.24 in istio/istio.io@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16089 [zh] Sync #16057 faq install and ambient install docs into Chinese
  content/zh/about/faq/setup/install-method-selection.md
  content/zh/docs/ambient/install/helm/index.md
  content/zh/docs/ambient/install/istioctl/index.md
Labels: kind/docs, translation/chinese, size/L

#16090 [zh] Sync #16057 helm and istioctl setup docs into Chinese
  content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/install/istioctl/index.md
Labels: kind/docs, translation/chinese, size/L

#16091 add specific policies to ambient getting started guide
  content/en/docs/ambient/getting-started/cleanup/index.md
  content/en/docs/ambient/getting-started/deploy-sample-app/index.md
  content/en/docs/ambient/getting-started/deploy-sample-app/snips.sh
  content/en/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/en/docs/ambient/getting-started/enforce-auth-policies/snips.sh
  content/en/docs/ambient/getting-started/secure-and-visualize/index.md
  content/en/docs/ambient/getting-started/test.sh
  content/en/docs/setup/getting-started/index.md
  content/en/docs/setup/getting-started/snips.sh
Labels: size/L

#16094 new format refdocs
  content/en/docs/reference/config/annotations/index.html
  content/en/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/labels/index.html
  content/en/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/proxy-config/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/networking/workload-entry/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/en/docs/reference/config/type/workload-selector/index.html
Labels: size/XXL

#16101 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#16096 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#16100 Remove reference to L7 EnvoyFilter for WayPoints from Ambient docs
  content/en/docs/ambient/usage/l7-features/index.md
Labels: kind/docs, size/XS, area/ambient

#16097 Change Hover Background for CTA Button in Header
  assets/sass/misc/_button.scss
Labels: kind/docs, size/S

#16104 [release-1.24] Change Hover Background for CTA Button in Header
  assets/sass/misc/_button.scss
Labels: size/S, release-notes-none

#16106 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/reference/config/labels/index.html
  content/en/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/en/docs/reference/config/networking/destination-rule/index.html
  content/en/docs/reference/config/networking/envoy-filter/index.html
  content/en/docs/reference/config/networking/gateway/index.html
  content/en/docs/reference/config/networking/proxy-config/index.html
  content/en/docs/reference/config/networking/service-entry/index.html
  content/en/docs/reference/config/networking/sidecar/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/en/docs/reference/config/networking/workload-entry/index.html
  content/en/docs/reference/config/networking/workload-group/index.html
  content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/en/docs/reference/config/security/peer_authentication/index.html
  content/en/docs/reference/config/security/request_authentication/index.html
  content/en/docs/reference/config/telemetry/index.html
  content/en/docs/reference/config/type/workload-selector/index.html
  content/zh/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/labels/index.html
  content/zh/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/proxy-config/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/networking/workload-entry/index.html
  content/zh/docs/reference/config/networking/workload-group/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/type/workload-selector/index.html
Labels: size/XXL, auto-merge, release-notes-none

#16105 announcement for 1.22 EOL
  content/en/news/support/announcing-1.22-eol/index.md
Labels: size/S, cherrypick/release-1.24

#16079 [zh] Improve microservices-istio/prereq/index.md
  content/zh/docs/examples/microservices-istio/prereq/index.md
Labels: kind/docs, translation/chinese, size/S

#16107 Remove Style Conflicts from Hamburger Menu SVGs
  layouts/partials/primary_top.html
  src/icons/hamburger-sidebar.svg
  src/icons/menu-close.svg
  src/icons/menu-hamburger.svg
Labels: kind/docs, size/XS, cherrypick/release-1.24

#16112 [release-1.24] Remove Style Conflicts from Hamburger Menu SVGs
  layouts/partials/primary_top.html
  src/icons/hamburger-sidebar.svg
  src/icons/menu-close.svg
  src/icons/menu-hamburger.svg
Labels: size/XS, release-notes-none

#16098 [zh] Sync #16091 add specific policies to ambient getting started guide into Chinese
  content/zh/docs/ambient/getting-started/cleanup/index.md
  content/zh/docs/ambient/getting-started/deploy-sample-app/index.md
  content/zh/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/zh/docs/ambient/getting-started/secure-and-visualize/index.md
  content/zh/docs/setup/getting-started/index.md
Labels: kind/docs, translation/chinese, size/L

#16110 [zh] Sync 1.22 EOL into Chinese
  content/zh/news/support/announcing-1.22-eol/index.md
Labels: kind/docs, translation/chinese, size/S

#16113 ambient: clarify ztunnel runs a task-per-pod, not process
  content/en/docs/ambient/architecture/traffic-redirection/index.md
Labels: size/XS, release-notes-none

#16115 Changes for 2024-12-18 releases
  .spelling
  content/en/news/releases/1.22.x/announcing-1.22.7/index.md
  content/en/news/releases/1.23.x/announcing-1.23.4/index.md
  content/en/news/releases/1.24.x/announcing-1.24.2/index.md
  content/en/news/security/istio-security-2024-007/index.md
Labels: area/security, size/L, ok-to-test

#16114 [release-1.24] ambient: clarify ztunnel runs a task-per-pod, not process
  content/en/docs/ambient/architecture/traffic-redirection/index.md
Labels: size/XS, release-notes-none

#16116 Release 1.24
  .spelling
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.22.x/announcing-1.22.7/index.md
  content/en/news/releases/1.23.x/announcing-1.23.4/index.md
  content/en/news/releases/1.24.x/announcing-1.24.2/index.md
  content/en/news/security/istio-security-2024-007/index.md
  data/args.yml
Labels: area/security, size/L, ok-to-test

#16117 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
Labels: size/M, auto-merge, release-notes-none

#16120 remove verify-install instructions
  content/en/docs/setup/install/istioctl/index.md
Labels: size/S

#16046 [zh] Sync #16045 fix typo in OpenShift pre-requisites for ambient into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/XS

#16118 [zh] Sync 1.22.7, 1.23.4, 1.24.2 release notes with security update into Chinese
  content/zh/news/releases/1.22.x/announcing-1.22.7/index.md
  content/zh/news/releases/1.23.x/announcing-1.23.4/index.md
  content/zh/news/releases/1.24.x/announcing-1.24.2/index.md
  content/zh/news/security/istio-security-2024-007/index.md
Labels: kind/docs, translation/chinese, size/L

#16119 [zh] Sync #16113 clarify ztunnel runs a task-per-pod, not process for ambient into Chinese
  content/zh/docs/ambient/architecture/traffic-redirection/index.md
Labels: kind/docs, translation/chinese, size/XS

#16122 [zh] Sync #16120 remove verify-install instructions into Chinese
  content/zh/docs/setup/install/istioctl/index.md
Labels: kind/docs, translation/chinese, size/S

#16123 Don't pin us to a 3-4 year old Helm release
  content/en/boilerplates/helm-preamble.md
  content/en/boilerplates/helm-prereqs.md
Labels: area/environments, kind/docs, size/S, cherrypick/release-1.24

#16124 [release-1.24] Don't pin us to a 3-4 year old Helm release
  content/en/boilerplates/helm-preamble.md
  content/en/boilerplates/helm-prereqs.md
Labels: size/S, release-notes-none

#16127 TFW you were thinking of two alternate sentence fragments…
  content/en/boilerplates/helm-prereqs.md
Labels: kind/docs, size/XS, cherrypick/release-1.24

#16128 [release-1.24] TFW you were thinking of two alternate sentence fragments…
  content/en/boilerplates/helm-prereqs.md
Labels: size/XS, release-notes-none

#16126 fix: pin kyverno-authz-server version
  content/en/blog/2024/authz-policy-with-kyverno/index.md
  content/uk/blog/2024/authz-policy-with-kyverno/index.md
  content/zh/blog/2024/authz-policy-with-kyverno/index.md
Labels: size/XS, ok-to-test

#16078 Create hidden parallel doctest docs for ambient wrapper chart, so it at least gets exercised a bit
  content/en/docs/ambient/install/helm/all-in-one/index.md
  content/en/docs/ambient/install/helm/all-in-one/snips.sh
  content/en/docs/ambient/install/helm/all-in-one/test.sh
  content/en/docs/ambient/install/helm/index.md
  content/en/docs/ambient/upgrade/helm/all-in-one/common.sh
  content/en/docs/ambient/upgrade/helm/all-in-one/index.md
  content/en/docs/ambient/upgrade/helm/all-in-one/snips.sh
  content/en/docs/ambient/upgrade/helm/all-in-one/test.sh
  content/en/docs/setup/upgrade/helm/index.md
  tests/util/helpers.sh
Labels: size/L

#16005 [zh] Update overview/dataplane-modes/index.md
  content/zh/docs/overview/dataplane-modes/index.md
  content/zh/docs/overview/why-choose-istio/index.md
Labels: kind/docs, translation/chinese, size/L

#16125 [zh] Sync #16123 helm support updates into Chinese
  content/zh/boilerplates/helm-preamble.md
  content/zh/boilerplates/helm-prereqs.md
Labels: kind/docs, translation/chinese, size/S

#16129 [zh] Sync Ambient all-in-one helm installation doc into Chinese
  content/zh/docs/ambient/install/helm/all-in-one/index.md
Labels: kind/docs, translation/chinese, size/L

#16130 [zh] Sync Ambient helm upgrade all-in-one doc with some related updates into Chinese
  content/zh/docs/ambient/install/helm/index.md
  content/zh/docs/ambient/upgrade/helm/all-in-one/index.md
  content/zh/docs/ambient/upgrade/helm/index.md
  content/zh/docs/setup/upgrade/helm/index.md
Labels: kind/docs, translation/chinese, size/L

#16135 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/proxy_extensions/stats/index.html
  content/zh/docs/reference/config/proxy_extensions/stats/index.html
Labels: size/L, auto-merge, release-notes-none

#16136 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/S, auto-merge, release-notes-none

#16131 Automator: update istio@ test reference
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-experimental.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/boilerplates/snips/gateway-api-remove-crds.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: size/L, release-notes-none

#16138 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
