Repository istio/istio.io, pull requests merged in 2024-10, with the labels that each got.

#15749 Remove release notes that were accidentally introduced
  content/en/news/releases/1.22.x/announcing-1.22/change-notes/index.md
  content/zh/news/releases/1.22.x/announcing-1.22/change-notes/index.md
Labels: size/XS, cherrypick/release-1.23

#15750 [release-1.23] Remove release notes that were accidentally introduced
  content/en/news/releases/1.22.x/announcing-1.22/change-notes/index.md
  content/zh/news/releases/1.22.x/announcing-1.22/change-notes/index.md
Labels: size/XS, release-notes-none

#15751 Remove OpenShift warning from bookinfo page
  content/en/docs/examples/bookinfo/index.md
Labels: size/XS

#15753 [master] Remove OpenShift warning from bookinfo page
  content/en/docs/examples/bookinfo/index.md
Labels: size/XS, release-notes-none

#15757 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15758 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15760 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, auto-merge, release-notes-none

#15761 Automator: update common-files@release-1.23 in istio/istio.io@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15763 Mention VPC CNI also has trouble ignoring link-local (ambient platform prereqs)
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: area/environments, kind/docs, size/XS, area/ambient, cherrypick/release-1.23

#15766 [zh] Sync #15763 Mention VPC CNI for EKS also has trouble ignoring link-local into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/S

#15769 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15771 [zh] Sync #15744 fixup Helm CRD docs into Chinese
  content/zh/boilerplates/crd-upgrade-123.md
  content/zh/docs/ambient/upgrade/helm/index.md
  content/zh/docs/ops/configuration/traffic-management/network-topologies/index.md
  content/zh/docs/setup/upgrade/helm/index.md
  content/zh/docs/tasks/observability/logs/access-log/index.md
  content/zh/docs/tasks/observability/logs/otel-provider/index.md
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
  content/zh/docs/tasks/security/authentication/claim-to-header/index.md
  content/zh/docs/tasks/security/authorization/authz-custom/index.md
  content/zh/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: kind/docs, translation/chinese, size/L

#15768 Deautomator: update istio@ test reference
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/gateway-api-gamma-experimental.sh
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/en/boilerplates/snips/gateway-api-remove-crds.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/gtwapi_test_disabled.sh
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/external-controlplane/test_disabled.sh
  content/en/docs/setup/install/multicluster/multi-primary/index.md
  content/en/docs/setup/install/multicluster/multi-primary/test_disabled.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/test_disabled.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/test_disabled.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/test_disabled.sh
  content/en/docs/setup/install/multicluster/verify/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  data/args.yml
  go.mod
  go.sum
Labels: kind/docs, size/L

#15774 Add back ambient helm inplace upgrade docs
  content/en/docs/ambient/upgrade/helm/index.md
  content/en/docs/ambient/upgrade/helm/inplace_test.sh
  content/en/docs/ambient/upgrade/helm/revision_test.sh
  content/en/docs/ambient/upgrade/helm/snips.sh
Labels: area/environments, size/L, area/ambient

#15778 [zh] Sync #15768 Deautomator: update istio@ test reference into Chinese
  content/zh/docs/setup/install/external-controlplane/index.md
  content/zh/docs/setup/install/multicluster/multi-primary/index.md
  content/zh/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/zh/docs/setup/install/multicluster/verify/index.md
Labels: kind/docs, translation/chinese, size/S

#15780 [zh] Sync #15774 add back ambient helm inplace upgrade into Chinese
  content/zh/docs/ambient/upgrade/helm/index.md
Labels: kind/docs, translation/chinese, size/L

#15770 Add link to Luca Cavallin's post
  .spelling
  content/en/blog/2024/link-the-istio-service-mesh-for-people-who-have-stuff-to-do.md
Labels: size/S

#15779 Mark the Operator as deprecated
  content/en/about/faq/setup/install-method-selection.md
  content/en/docs/setup/install/operator/index.md
Labels: size/XS

#15781 [release-1.23] Add link to Luca Cavallin's post
  .spelling
  content/en/blog/2024/link-the-istio-service-mesh-for-people-who-have-stuff-to-do.md
Labels: size/S, release-notes-none

#15782 add README for multicluster docs tests
  tests/README.md
Labels: kind/docs, size/M

#15776 Fixup and re-enable remote tests
  content/en/docs/setup/install/external-controlplane/gtwapi_test.sh
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/external-controlplane/test.sh
  content/en/docs/setup/install/multicluster/multi-primary/index.md
  content/en/docs/setup/install/multicluster/multi-primary/test.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/index.md
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/test.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/test.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/test.sh
  content/en/docs/setup/install/multicluster/verify/index.md
Labels: size/S

#15784 Mention `ip_set` kmods in requirements
  content/en/docs/ops/deployment/platform-requirements/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.23

#15788 [zh] Sync #15784 mention ip_set kmods in requirements into Chinese
  content/zh/docs/ops/deployment/platform-requirements/index.md
Labels: kind/docs, translation/chinese, size/XS

#15666 fix title
  src/sass/base/_base.scss
Labels: size/XS, cherrypick/release-1.23

#15789 [release-1.23] fix title
  src/sass/base/_base.scss
Labels: size/XS, release-notes-none

#15785 Add more detail to the EKS workaround
  .spelling
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, size/S, area/ambient, cherrypick/release-1.23

#15787 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15791 [zh] Sync #15785 add more detail to the EKS workaround into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/XS

#15792 [zh] Sync replace "sleep" to “curl” part 1 into Chinese
  content/zh/boilerplates/before-you-begin-egress.md
  content/zh/docs/ambient/architecture/traffic-redirection/index.md
  content/zh/docs/ambient/getting-started/cleanup/index.md
  content/zh/docs/ambient/getting-started/enforce-auth-policies/index.md
  content/zh/docs/ambient/getting-started/manage-traffic/index.md
  content/zh/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/zh/docs/ambient/usage/l4-policy/index.md
  content/zh/docs/ambient/usage/troubleshoot-waypoint/index.md
  content/zh/docs/ambient/usage/troubleshoot-ztunnel/index.md
  content/zh/docs/ambient/usage/verify-mtls-enabled/index.md
  content/zh/docs/concepts/security/index.md
  content/zh/docs/examples/microservices-istio/add-istio/index.md
  content/zh/docs/examples/microservices-istio/add-new-microservice-version/index.md
  content/zh/docs/examples/microservices-istio/bookinfo-kubernetes/index.md
  content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
  content/zh/docs/examples/microservices-istio/production-testing/index.md
  content/zh/docs/ops/common-problems/injection/index.md
  content/zh/docs/ops/common-problems/network-issues/index.md
  content/zh/docs/ops/common-problems/security-issues/index.md
  content/zh/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/zh/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
  content/zh/docs/ops/diagnostic-tools/multicluster/index.md
  content/zh/docs/ops/diagnostic-tools/proxy-cmd/index.md
  content/zh/docs/ops/integrations/spire/index.md
  content/zh/docs/reference/config/analysis/ist0127/index.md
  content/zh/docs/setup/additional-setup/dual-stack/index.md
  content/zh/docs/setup/additional-setup/sidecar-injection/index.md
  content/zh/docs/setup/install/external-controlplane/index.md
  content/zh/docs/setup/install/multicluster/verify/index.md
  content/zh/docs/setup/install/multiple-controlplanes/index.md
Labels: kind/docs, translation/chinese, size/L

#15793 [zh] Sync replace "sleep" to “curl” for setup and task docs into Chinese
  content/zh/docs/setup/upgrade/canary/index.md
  content/zh/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
  content/zh/docs/tasks/observability/distributed-tracing/sampling/index.md
  content/zh/docs/tasks/observability/logs/access-log/index.md
  content/zh/docs/tasks/observability/logs/otel-provider/index.md
  content/zh/docs/tasks/observability/logs/telemetry-api/index.md
  content/zh/docs/tasks/security/authentication/authn-policy/index.md
Labels: kind/docs, translation/chinese, size/L

#15794 [zh] Sync replace "sleep" to “curl” for sucurity docs into Chinese
  content/zh/docs/tasks/security/authentication/claim-to-header/index.md
  content/zh/docs/tasks/security/authentication/mtls-migration/index.md
  content/zh/docs/tasks/security/authorization/authz-custom/index.md
  content/zh/docs/tasks/security/authorization/authz-deny/index.md
  content/zh/docs/tasks/security/authorization/authz-dry-run/index.md
  content/zh/docs/tasks/security/authorization/authz-jwt/index.md
  content/zh/docs/tasks/security/authorization/authz-tcp/index.md
  content/zh/docs/tasks/security/authorization/authz-td-migration/index.md
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
  content/zh/docs/tasks/security/cert-management/plugin-ca-cert/index.md
  content/zh/docs/tasks/security/tls-configuration/workload-min-tls-version/index.md
Labels: kind/docs, translation/chinese, size/L

#15795 [zh] Replace sleep with curl in tasks/traffic-management/
  content/zh/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-tls-origination/index.md
  content/zh/docs/tasks/traffic-management/egress/http-proxy/index.md
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/before-you-begin/index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/distribute/index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: kind/docs, translation/chinese, size/L

#15797 [zh] Fix wrong replace for sleep to curl Chinese docs
  content/zh/docs/tasks/traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/tcp-traffic-shifting/index.md
Labels: kind/docs, translation/chinese, size/S

#15134 Opa blog post
  .spelling
  content/en/blog/2024/l7-policy-with-opa/index.md
  content/en/blog/2024/l7-policy-with-opa/opa1.png
  content/en/blog/2024/l7-policy-with-opa/opa2.png
  content/en/blog/2024/l7-policy-with-opa/opa3.png
Labels: area/extensions and telemetry, size/L, lifecycle/staleproof, lifecycle/automatically-closed, cherrypick/release-1.23

#15799 manual cherry-pick of OPA blog post (#15134)
  .spelling
  content/en/blog/2024/l7-policy-with-opa/index.md
  content/en/blog/2024/l7-policy-with-opa/opa1.png
  content/en/blog/2024/l7-policy-with-opa/opa2.png
  content/en/blog/2024/l7-policy-with-opa/opa3.png
Labels: size/L

#15801 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15800 [zh] Sync blog L7 policy with OPA into Chinese
  content/zh/blog/2024/l7-policy-with-opa/index.md
  content/zh/blog/2024/l7-policy-with-opa/opa1.png
  content/zh/blog/2024/l7-policy-with-opa/opa2.png
  content/zh/blog/2024/l7-policy-with-opa/opa3.png
Labels: kind/docs, translation/chinese, size/L

#15803 [release-1.23] [zh] Sync blog L7 policy with OPA into Chinese
  content/zh/blog/2024/l7-policy-with-opa/index.md
  content/zh/blog/2024/l7-policy-with-opa/opa1.png
  content/zh/blog/2024/l7-policy-with-opa/opa2.png
  content/zh/blog/2024/l7-policy-with-opa/opa3.png
Labels: size/L, release-notes-none

#15786 [release-1.23] Mention `ip_set` kmods in requirements
  content/en/docs/ops/deployment/platform-requirements/index.md
Labels: size/XS, release-notes-none

#15806 Add TOC election blog
  .spelling
  content/en/blog/2024/toc-charter-elections/index.md
Labels: size/M

#15807 [release-1.23] Add TOC election blog
  .spelling
  content/en/blog/2024/toc-charter-elections/index.md
Labels: size/M, release-notes-none

#15808 [zh] Sync TOC election blog and ext-linked blog into Chinese
  content/zh/blog/2024/link-the-istio-service-mesh-for-people-who-have-stuff-to-do.md
  content/zh/blog/2024/toc-charter-elections/index.md
Labels: kind/docs, translation/chinese, size/L

#15809 [release-1.23] [zh] Sync TOC election blog and ext-linked blog into Chinese
  content/zh/blog/2024/link-the-istio-service-mesh-for-people-who-have-stuff-to-do.md
  content/zh/blog/2024/toc-charter-elections/index.md
Labels: size/L, release-notes-none

#15796 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#15812 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#15804 Remove global.externalIstiod from remote examples
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
Labels: size/XS, ok-to-test

#15802 scale test blog
  .spelling
  content/en/blog/2024/ambient-vs-cilium/index.md
  content/en/blog/2024/ambient-vs-cilium/scale-scenario.png
  content/en/blog/2024/ambient-vs-cilium/scale-scorecard.png
Labels: size/M

#15814 [release-1.23] scale test blog
  .spelling
  content/en/blog/2024/ambient-vs-cilium/index.md
  content/en/blog/2024/ambient-vs-cilium/scale-scenario.png
  content/en/blog/2024/ambient-vs-cilium/scale-scorecard.png
Labels: size/M, release-notes-none

#15708 [zh] improve kubernetes-ingress secure-ingress ingress-control
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/index.md
  content/zh/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: kind/docs, translation/chinese, size/L

#15815 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  data/features.yaml
Labels: size/S, auto-merge, release-notes-none

#15816 [zh] Sync Scale test blog into Chinese
  content/zh/blog/2024/ambient-vs-cilium/index.md
  content/zh/blog/2024/ambient-vs-cilium/scale-scenario.png
  content/zh/blog/2024/ambient-vs-cilium/scale-scorecard.png
Labels: kind/docs, translation/chinese, size/L

#15817 [zh] Update text in egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: kind/docs, translation/chinese, size/L

#15818 [release-1.23] [zh] Sync Scale test blog into Chinese
  content/zh/blog/2024/ambient-vs-cilium/index.md
  content/zh/blog/2024/ambient-vs-cilium/scale-scenario.png
  content/zh/blog/2024/ambient-vs-cilium/scale-scorecard.png
Labels: size/L, release-notes-none

#15820 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#15813 Announcing Istio 1.22.6
  content/en/news/releases/1.22.x/announcing-1.22.6/index.md
Labels: size/S, cherrypick/release-1.23

#15821 [release-1.23] Announcing Istio 1.22.6
  content/en/news/releases/1.22.x/announcing-1.22.6/index.md
Labels: size/S, release-notes-none

#15826 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15822 [zh] Sync 1.22.6 release note into Chinese
  content/zh/news/releases/1.22.x/announcing-1.22.6/index.md
Labels: kind/docs, translation/chinese, size/S

#15823 [zh] Fix missed translation for 1.22.5 and 1.23.2 release notes
  content/zh/news/releases/1.22.x/announcing-1.22.5/index.md
  content/zh/news/releases/1.23.x/announcing-1.23.2/index.md
Labels: kind/docs, translation/chinese, size/S

#15824 fix zh version top blank
  content/zh/_index.html
Labels: size/XS

#15805 Use `global.externalIstiod` instead of `pilot.env.EXTERNAL_ISTIOD`
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: size/S, ok-to-test

#15830 [release-1.23] fix zh version top blank
  content/zh/_index.html
Labels: size/XS, release-notes-none

#15825 Remove note for preview DNS proxying
  content/en/docs/ops/deployment/deployment-models/index.md
Labels: area/networking, size/XS, cherrypick/release-1.23

#15831 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#15836 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/S, auto-merge, release-notes-none

#15833 [zh] Sync #15825 remove note for preview DNS proxying into Chinese
  content/zh/docs/ops/deployment/deployment-models/index.md
Labels: kind/docs, translation/chinese, size/XS

#15842 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15840 Add Istio Day North America Banner
  content/en/events/banners/istio-day-na-2024.md
Labels: size/XS, cherrypick/release-1.23

#15843 [release-1.23] Add Istio Day North America Banner
  content/en/events/banners/istio-day-na-2024.md
Labels: size/XS, release-notes-none

#15844 [zh] Sync #15840 Istio Day North America Banner into Chinese
  content/zh/events/banners/istio-day-na-2024.md
Labels: translation/chinese, size/XS

#15845 Dual-stack is experimental on 1.23
  content/en/docs/setup/additional-setup/dual-stack/index.md
Labels: kind/docs, size/XS

#15849 Update supported versions for 1.24
  .spelling
  content/en/docs/releases/supported-releases/index.md
  data/compatibility/supportStatus.yml
Labels: size/S, release-notes-none

#15848 Prepare for v1.24
  Makefile.core.mk
  content/en/docs/ambient/getting-started/deploy-sample-app/snips.sh
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/zh/docs/reference/commands/istioctl/index.html
  data/args.yml
  go.mod
  go.sum
Labels: size/M, release-notes-none

#15850 Change my blog attribution
  content/en/blog/2024/ambient-vs-cilium/index.md
Labels: size/XS, cherrypick/release-1.23

#15832 [release-1.23] Remove note for preview DNS proxying
  content/en/docs/ops/deployment/deployment-models/index.md
Labels: size/XS, auto-merge, release-notes-none

#15852 [release-1.23] Change my blog attribution
  content/en/blog/2024/ambient-vs-cilium/index.md
Labels: size/XS, release-notes-none
