Repository istio/istio.io, pull requests merged in 2024-08, with the labels that each got.

#15493 [zh] Sync #15436 remove old page and update all links into Chinese
  content/zh/blog/2024/v1-apis/index.md
  content/zh/docs/ops/diagnostic-tools/istioctl/index.md
  content/zh/docs/ops/integrations/spire/index.md
  content/zh/docs/setup/additional-setup/customize-installation-helm/index.md
  content/zh/docs/setup/additional-setup/customize-installation/index.md
  content/zh/docs/setup/additional-setup/download-istio-release/index.md
  content/zh/docs/setup/additional-setup/getting-started/index.md
  content/zh/docs/setup/additional-setup/getting-started/kiali-example2.png
  content/zh/docs/setup/install/istioctl/index.md
  content/zh/docs/setup/install/operator/index.md
  content/zh/docs/setup/install/virtual-machine/index.md
  content/zh/docs/setup/platform-setup/kind/index.md
  content/zh/docs/setup/upgrade/in-place/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/zh/news/releases/1.16.x/announcing-1.16/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15508 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/operator/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/operator/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/XL, auto-merge, release-notes-none

#15507 [zh] Sync ambient/usage/extend-waypoint-wasm/index.md
  content/zh/docs/ambient/usage/extend-waypoint-wasm/index.md
Labels: kind/docs, translation/chinese, size/L

#15502 [zh] update a task: traffic-management/mirroring/index.md
  content/zh/docs/tasks/traffic-management/mirroring/index.md
Labels: kind/docs, translation/chinese, size/M

#15501 Fix snip generator
  scripts/snip.py
Labels: size/XS

#15514 Remove manual injection step from Bookinfo etc
  content/en/docs/examples/bookinfo/index.md
  content/en/docs/examples/bookinfo/snips.sh
  content/en/docs/examples/bookinfo/test.sh
  content/en/docs/examples/microservices-istio/add-istio/index.md
  content/en/docs/tasks/observability/metrics/tcp-metrics/index.md
  content/en/docs/tasks/observability/metrics/tcp-metrics/snips.sh
  content/en/docs/tasks/observability/metrics/tcp-metrics/test.sh
Labels: size/L

#15516 [zh] Update 2 docs: data-plane and cni setup
  content/zh/docs/ambient/architecture/data-plane/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, translation/chinese, size/M

#15512 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#15518 Adjust fonts for code snippets
  src/sass/misc/_code-blocks.scss
Labels: size/XS

#15517 [zh] Sync #15514 update into Chinese
  content/zh/docs/examples/bookinfo/index.md
  content/zh/docs/examples/microservices-istio/add-istio/index.md
  content/zh/docs/tasks/observability/metrics/tcp-metrics/index.md
Labels: kind/docs, translation/chinese, size/M

#15496 [release-1.21] Update istio.io test reference to 1.21.5
  go.mod
  go.sum
Labels: size/S

#15520 [zh] Sync task custom-ca-k8s into Chinese
  content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
Labels: size/M, ok-to-test

#15526 [release-1.22] Adjust fonts for code snippets
  src/sass/misc/_code-blocks.scss
Labels: size/XS, release-notes-none

#15527 [release-1.22] docs: ambient documentation update issue #15522
  content/en/docs/ambient/install/helm-installation/index.md
Labels: size/XS, release-notes-none

#15247 Expand Ambient Canary Upgrade Instructions
  .spelling
  content/en/docs/ambient/upgrade/helm-upgrade/index.md
  content/en/docs/ambient/upgrade/helm-upgrade/snips.sh
  content/en/docs/ambient/upgrade/helm-upgrade/test.sh
  prow/config/k8s1-30.yaml
Labels: area/environments, kind/docs, size/L, auto-merge, area/ambient

#15521 Some minor fixes to the troubleshooting doc
  content/en/docs/ops/common-problems/injection/index.md
Labels: size/M

#15525 [zh] Sync #15523 update ambient install doc link into Chinese
  content/zh/docs/ambient/install/helm-installation/index.md
Labels: kind/docs, translation/chinese, size/XS

#15529 [zh] Sync #15521 troubleshooting doc update into Chinese
  content/zh/docs/ops/common-problems/injection/index.md
Labels: kind/docs, translation/chinese, size/M

#15528 [zh] Sync #15247 ambient upgrade doc changes into Chinese
  content/zh/docs/ambient/upgrade/helm-upgrade/index.md
Labels: kind/docs, translation/chinese, size/L

#15531 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15533 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15530 [zh] Sync task rate-limit into Chinese
  content/zh/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: size/XS, ok-to-test

#15534 Automator: update common-files@release-1.22 in istio/istio.io@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15532 bump hugo to match tools
  netlify.toml
Labels: kind/docs, size/XS

#15535 [zh] update some zh text in /policy-enforcement/rate-limit/index.md
  content/zh/docs/tasks/policy-enforcement/rate-limit/index.md
Labels: kind/docs, size/S

#15543 Add note to eBPF blog about not being supported any more
  content/en/blog/2023/ambient-ebpf-redirection/index.md
Labels: size/L, cherrypick/release-1.22

#15547 Add note to eBPF blog about not being supported any more
  content/en/blog/2023/ambient-ebpf-redirection/index.md
Labels: size/L

#15541 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#15542 Fix typo
  content/en/docs/ambient/usage/add-workloads/index.md
Labels: size/XS, ok-to-test

#15550 [release-1.22] Fix typo
  content/en/docs/ambient/usage/add-workloads/index.md
Labels: size/XS, release-notes-none

#15551 Add note on Cilium's bpf masquerading
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: area/environments, kind/docs, size/XS, area/ambient, cherrypick/release-1.22

#15552 [release-1.22] Add note on Cilium's bpf masquerading
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: size/XS, release-notes-none

#15554 [zh] Sync #15551 add note on Cilium's bpf masquerading into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/XS

#15546 [zh] Sync #15543 add note for Ambient eBPF blog into Chinese
  content/zh/blog/2023/ambient-ebpf-redirection/index.md
Labels: kind/docs, translation/chinese, size/L

#15538 Istio 1.23 release notes
  .spelling
  content/en/blog/2024/in-cluster-operator-deprecation-announcement/index.md
  content/en/news/releases/1.23.x/_index.md
  content/en/news/releases/1.23.x/announcing-1.23/_index.md
  content/en/news/releases/1.23.x/announcing-1.23/change-notes/index.md
  content/en/news/releases/1.23.x/announcing-1.23/upgrade-notes/index.md
Labels: size/L

#15556 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15557 Add support status for 1.23 release
  .spelling
  content/en/docs/releases/supported-releases/index.md
  data/compatibility/supportStatus.yml
Labels: size/XS

#15561 [master] Add support status for 1.23 release
  .spelling
  content/en/docs/releases/supported-releases/index.md
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#15539 adjusted toc height
  src/sass/misc/_toc.scss
Labels: area/user experience, size/XS, ok-to-test

#15560 [zh] Sync deprecated its In-Cluster Operator blog into Chinese
  content/zh/blog/2024/in-cluster-operator-deprecation-announcement/index.md
Labels: kind/docs, translation/chinese, size/L

#15564 [zh] Sync #15557 add support status for 1.23 release into Chinese
  content/zh/docs/releases/supported-releases/index.md
Labels: kind/docs, translation/chinese, size/XS

#15566 [release-1.23] adjusted toc height
  src/sass/misc/_toc.scss
Labels: size/XS, release-notes-none

#15558 [zh] Sync 1.23 release notes and upgrade notes into Chinese
  content/zh/news/releases/1.23.x/_index.md
  content/zh/news/releases/1.23.x/announcing-1.23/_index.md
  content/zh/news/releases/1.23.x/announcing-1.23/upgrade-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15563 [zh] Sync 1.23.0 change notes into Chinese
  content/zh/news/releases/1.23.x/announcing-1.23/change-notes/index.md
Labels: kind/docs, translation/chinese, size/L

#15549 Sail Operator blog
  content/en/blog/2024/introducing-sail-operator/index.md
Labels: kind/docs, size/M, ok-to-test, cherrypick/release-1.23

#15571 [release-1.23] Sail Operator blog
  content/en/blog/2024/introducing-sail-operator/index.md
Labels: size/M, release-notes-none

#15570 1.22.4 Release Notes
  content/en/news/releases/1.22.x/announcing-1.22.4/index.md
Labels: size/M, cherrypick/release-1.23

#15573 [release-1.23] 1.22.4 Release Notes
  content/en/news/releases/1.22.x/announcing-1.22.4/index.md
Labels: size/M, release-notes-none

#15572 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15575 [zh] Sync Sail Operator blog and 1.22.4 release note into Chinese
  content/zh/blog/2024/introducing-sail-operator/index.md
  content/zh/news/releases/1.22.x/announcing-1.22.4/index.md
Labels: kind/docs, translation/chinese, size/M

#15569 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#15577 [zh] fix typo and format for release note 1.22.4 and Sail Operator blog
  content/zh/blog/2024/introducing-sail-operator/index.md
  content/zh/news/releases/1.22.x/announcing-1.22.4/index.md
Labels: kind/docs, translation/chinese, size/S

#15553 update hugo to v0.133.0
  netlify.toml
Labels: size/XS

#15579 Automator: update common-files@release-1.23 in istio/istio.io@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15581 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15580 Mention need to allowlist port 15008 in existing network policy
  content/en/docs/ambient/usage/add-workloads/index.md
Labels: area/networking, kind/docs, size/M, area/ambient, cherrypick/release-1.23

#15582 [release-1.23] Mention need to allowlist port 15008 in existing network policy
  content/en/docs/ambient/usage/add-workloads/index.md
Labels: size/M, release-notes-none

#15586 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/install-cni/index.html
Labels: size/L, auto-merge, release-notes-none

#15588 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#15587 [zh] Sync #15580 mention need to allowlist port 15008 in existing networkpolicy into Chinese
  content/zh/docs/ambient/usage/add-workloads/index.md
Labels: kind/docs, translation/chinese, size/M

#15591 [zh] update locality-load-balancing/failover and its SVG
  content/zh/docs/tasks/traffic-management/locality-load-balancing/failover/index.md
  content/zh/docs/tasks/traffic-management/locality-load-balancing/failover/sequence.svg
Labels: kind/docs, translation/chinese, size/XXL

#15590 remove istioctl --set from dualstack installation
  content/en/docs/setup/additional-setup/dual-stack/index.md
  content/zh/docs/setup/additional-setup/dual-stack/index.md
Labels: kind/docs, size/S, cherrypick/release-1.23

#15483 add istioctl install page for ambient and improve install docs experience
  .spelling
  content/en/docs/ambient/install/_index.md
  content/en/docs/ambient/install/helm/index.md
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/ambient/install/helm/test.sh
  content/en/docs/ambient/install/istioctl/index.md
  content/en/docs/ambient/install/istioctl/snips.sh
  content/en/docs/ambient/install/istioctl/test.sh
  content/en/docs/ambient/install/platform-prerequisites/index.md
  content/en/docs/ambient/upgrade/_index.md
  content/en/docs/ambient/upgrade/helm/common.sh
  content/en/docs/ambient/upgrade/helm/index.md
  content/en/docs/ambient/upgrade/helm/snips.sh
  content/en/docs/ambient/upgrade/helm/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  scripts/snip.py
  tests/util/samples.sh
Labels: kind/docs, size/XL, area/ambient

#15594 Add doc for verify mtls among apps in ambient
  .spelling
  content/en/docs/ambient/usage/verify-mtls-enabled/index.md
  content/en/docs/ambient/usage/verify-mtls-enabled/kiali-mtls.png
Labels: size/M, cherrypick/release-1.23

#15596 [release-1.23] Add doc for verify mtls among apps in ambient
  .spelling
  content/en/docs/ambient/usage/verify-mtls-enabled/index.md
  content/en/docs/ambient/usage/verify-mtls-enabled/kiali-mtls.png
Labels: size/M, release-notes-none

#15598 [zh] Add ambient/usage/verify-mtls-enabled to sync #15594
  content/zh/docs/ambient/usage/verify-mtls-enabled/index.md
  content/zh/docs/ambient/usage/verify-mtls-enabled/kiali-mtls.png
Labels: kind/docs, translation/chinese, size/L

#15599 [zh] Sync #15483 add istioctl install page and improve part of install docs into Chinese
  content/zh/docs/ambient/install/_index.md
  content/zh/docs/ambient/install/helm/index.md
  content/zh/docs/ambient/install/istioctl/index.md
Labels: kind/docs, translation/chinese, size/L

#15600 [zh] Sync #15483 part of improve ambient docs into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
  content/zh/docs/ambient/upgrade/_index.md
  content/zh/docs/ambient/upgrade/helm/index.md
  content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
Labels: kind/docs, translation/chinese, size/L

#15601 Fix links and grammar in the recent ambient docs
  content/en/docs/ambient/upgrade/helm/index.md
  content/en/docs/ambient/usage/extend-waypoint-wasm/index.md
  content/en/docs/ambient/usage/verify-mtls-enabled/index.md
Labels: kind/docs, size/S, area/ambient

#15593 [release-1.23] remove istioctl --set from dualstack installation
  content/en/docs/setup/additional-setup/dual-stack/index.md
  content/zh/docs/setup/additional-setup/dual-stack/index.md
Labels: size/S, release-notes-none

#15597 [release-1.23] add istioctl install page for ambient and improve install docs experience
  .spelling
  content/en/docs/ambient/install/_index.md
  content/en/docs/ambient/install/helm/index.md
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/ambient/install/helm/test.sh
  content/en/docs/ambient/install/istioctl/index.md
  content/en/docs/ambient/install/istioctl/snips.sh
  content/en/docs/ambient/install/istioctl/test.sh
  content/en/docs/ambient/install/platform-prerequisites/index.md
  content/en/docs/ambient/upgrade/_index.md
  content/en/docs/ambient/upgrade/helm/common.sh
  content/en/docs/ambient/upgrade/helm/index.md
  content/en/docs/ambient/upgrade/helm/snips.sh
  content/en/docs/ambient/upgrade/helm/test.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/index.md
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/snips.sh
  scripts/snip.py
  tests/util/samples.sh
Labels: size/XL, release-notes-none

#15545 Update index.md : Changed an oversight in localizing a Chinese word
  content/zh/docs/ops/integrations/prometheus/index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#15574 Attempt at modernizing the sidecar SPIRE integration doc
  content/en/docs/ops/integrations/spire/automatic_registration_test.sh
  content/en/docs/ops/integrations/spire/index.md
  content/en/docs/ops/integrations/spire/snips.sh
  tests/util/helpers.sh
Labels: area/environments, kind/docs, size/XL

#15604 [release-1.23] Attempt at modernizing the sidecar SPIRE integration doc
  content/en/docs/ops/integrations/spire/automatic_registration_test.sh
  content/en/docs/ops/integrations/spire/index.md
  content/en/docs/ops/integrations/spire/snips.sh
  tests/util/helpers.sh
Labels: size/XL, release-notes-none

#15605 [zh] Sync #15574 Attempt at modernizing the sidecar SPIRE integration doc into Chinese
  content/zh/docs/ops/integrations/spire/index.md
Labels: translation/chinese, size/XL

#15609 add notes about traffic addressing for waypoint proxies
  content/en/docs/ambient/usage/waypoint/index.md
Labels: area/networking, size/S, area/ambient, cherrypick/release-1.23

#15610 [release-1.23] add notes about traffic addressing for waypoint proxies
  content/en/docs/ambient/usage/waypoint/index.md
Labels: size/S, release-notes-none

#15612 [zh] Sync #15609 add notes about traffic addressing for waypoint proxies into Chinese
  content/zh/docs/ambient/usage/waypoint/index.md
Labels: kind/docs, translation/chinese, size/S

#15583 Actually, maybe separate ambient NetworkPolicy doc into its own thing
  .spelling
  content/en/docs/ambient/usage/add-workloads/index.md
  content/en/docs/ambient/usage/networkpolicy/index.md
Labels: area/networking, size/L, area/ambient

#15615 Drop obsolete feature flag
  content/en/docs/setup/install/multiple-controlplanes/index.md
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
Labels: size/S, release-notes-none, cherrypick/release-1.23

#15616 [release-1.23] Drop obsolete feature flag
  content/en/docs/setup/install/multiple-controlplanes/index.md
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
Labels: size/S, release-notes-none

#15619 #15583 typo/nit followup
  content/en/docs/ambient/usage/networkpolicy/index.md
Labels: kind/docs, size/XS, area/ambient, cherrypick/release-1.23

#15618 [release-1.23] Actually, maybe separate ambient NetworkPolicy doc into its own thing
  .spelling
  content/en/docs/ambient/usage/add-workloads/index.md
  content/en/docs/ambient/usage/networkpolicy/index.md
Labels: size/L, release-notes-none

#15621 [release-1.23] #15583 typo/nit followup
  content/en/docs/ambient/usage/networkpolicy/index.md
Labels: kind/docs, size/XS, area/ambient

#15614 [zh] Sync #15583 separate ambient NetworkPolicy doc into Chinese
  content/zh/docs/ambient/usage/add-workloads/index.md
  content/zh/docs/ambient/usage/networkpolicy/index.md
Labels: kind/docs, translation/chinese, size/L

#15617 [zh] Sync #15615 drop obsolete feature flag into Chinese
  content/zh/docs/setup/install/multiple-controlplanes/index.md
Labels: kind/docs, translation/chinese, size/S

#15623 [zh] Sync #15619 fix typo into Chinese
  content/zh/docs/ambient/usage/networkpolicy/index.md
Labels: kind/docs, translation/chinese, size/XS

#15625 Bump k8s versions for master
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#15626 [release-1.23] Bump k8s versions for master
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#15627 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15628 Announce upcoming 1.21 EOL
  content/en/news/support/announcing-1.21-eol/index.md
Labels: size/S, cherrypick/release-1.23

#15629 [release-1.23] Announce upcoming 1.21 EOL
  content/en/news/support/announcing-1.21-eol/index.md
Labels: size/S, release-notes-none

#15631 [zh] Sync Announce upcoming 1.21 EOL into Chinese
  content/zh/news/support/announcing-1.21-eol/index.md
Labels: kind/docs, translation/chinese, size/S

#15632 Fix tcpdump ports
  content/en/docs/ambient/usage/verify-mtls-enabled/index.md
  content/zh/docs/ambient/usage/verify-mtls-enabled/index.md
Labels: size/XS, cherrypick/release-1.23

#15634 [release-1.23] Fix tcpdump ports (#15632)
  content/en/docs/ambient/usage/verify-mtls-enabled/index.md
Labels: size/XS
