Repository istio/istio.io, pull requests merged in 2024-02, with the labels that each got.

#14564 [zh] Translate Ambient in-Pod blog into Chinese
  content/zh/blog/2024/inpod-traffic-redirection-ambient/index.md
  content/zh/blog/2024/inpod-traffic-redirection-ambient/pod-added-to-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-between-pods-in-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-plaintext.svg
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.20

#14572 [release-1.20] [zh] Translate Ambient in-Pod blog into Chinese
  content/zh/blog/2024/inpod-traffic-redirection-ambient/index.md
  content/zh/blog/2024/inpod-traffic-redirection-ambient/pod-added-to-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-between-pods-in-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-plaintext.svg
Labels: size/L, release-notes-none

#14562 Slightly tweak upgrade guide in the wake of inpod merge
  content/en/docs/ops/ambient/upgrade/helm-upgrade/index.md
Labels: size/S

#14578 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14576 [zh] Translate all in-Pod blog flow images into Chinese
  content/zh/blog/2024/inpod-traffic-redirection-ambient/pod-added-to-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-between-pods-in-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-plaintext.svg
Labels: kind/docs, translation/chinese, size/XL

#14579 [zh] Sync #14562 into Chinese
  content/zh/docs/ops/ambient/upgrade/helm-upgrade/index.md
Labels: kind/docs, translation/chinese, size/M

#14580 [release-1.20] [zh] Translate all in-Pod blog flow images into Chinese
  content/zh/blog/2024/inpod-traffic-redirection-ambient/pod-added-to-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-between-pods-in-ambient.svg
  content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-plaintext.svg
Labels: size/XL, release-notes-none

#14581 small enhancements to ambient install tests
  content/en/docs/ops/ambient/install/helm-installation/index.md
  content/en/docs/ops/ambient/install/helm-installation/snips.sh
  content/en/docs/ops/ambient/install/helm-installation/test.sh
Labels: size/M

#14571 fix: Multi-cluster installation with revision istiod vs
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: area/environments, kind/docs, size/M, ok-to-test

#14583 Update test reference to 1.21.0-beta.1 commit
  go.mod
  go.sum
Labels: size/S

#14586 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#14589 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14591 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14577 [Egress Gateway task] Remove troubleshooting section and add tip for cert verification
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh
Labels: area/networking, kind/docs, size/L

#14592 Current supported release is empty
  data/compatibility/supportStatus.yml
Labels: size/XS

#14594 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/XS, auto-merge, release-notes-none

#14596 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14599 [release-1.20] fix: Multi-cluster installation with revision istiod vs
  content/en/docs/setup/install/multicluster/primary-remote/index.md
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/index.md
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: size/M, release-notes-none

#14600 Automator: update common-files@release-1.19 in istio/istio.io@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14598 Istio Security Bulletin 2024-0001
  .spelling
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/releases/supported-releases/index.md
  content/en/docs/setup/additional-setup/getting-started/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.19.x/announcing-1.19.7/index.md
  content/en/news/releases/1.20.x/announcing-1.20.3/index.md
  content/en/news/security/istio-security-2024-001/index.md
  data/args.yml
Labels: kind/docs, size/L

#14602 Manual cherry-pick of #14598 [Security Bulletin 2024-0001]
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.19.x/announcing-1.19.7/index.md
  content/en/news/releases/1.20.x/announcing-1.20.3/index.md
  content/en/news/security/istio-security-2024-001/index.md
Labels: kind/docs, size/L

#14601 fix broken FAQ link
  content/en/about/faq/distributed-tracing/minimal-requirements.md
Labels: area/extensions and telemetry, area/environments, kind/docs, size/XS, ok-to-test

#14604 [release-1.20] fix broken FAQ link
  content/en/about/faq/distributed-tracing/minimal-requirements.md
Labels: size/XS, release-notes-none

#14593 [zh] Sync #14577 into Chinese
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: kind/docs, translation/chinese, size/M

#14603 [zh] Sync #14598 into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.19.x/announcing-1.19.7/index.md
  content/zh/news/releases/1.20.x/announcing-1.20.3/index.md
  content/zh/news/security/istio-security-2024-001/index.md
Labels: kind/docs, translation/chinese, size/L

#14607 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#14608 Automator: update common-files@master in istio/istio.io@master
  SUPPORT.md
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#14610 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#14614 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#14606 Blog post for Istio 2024-25 Steering Committee
  .spelling
  content/en/blog/2024/steering-results/index.md
Labels: size/M, cherrypick/release-1.20

#14616 [release-1.20] Blog post for Istio 2024-25 Steering Committee
  .spelling
  content/en/blog/2024/steering-results/index.md
Labels: size/M, release-notes-none

#14587 [zh] Update 2 multicluster primary-remote files
  content/zh/docs/setup/install/multicluster/primary-remote/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: kind/docs, translation/chinese, size/S

#14588 [zh] Sync /observability/kiali/
  content/zh/docs/tasks/observability/kiali/index.md
Labels: kind/docs, translation/chinese, size/L

#14612 [zh] Translate Istio 2024-25 Steering Committee blog into Chinese
  content/zh/blog/2024/steering-results/index.md
Labels: kind/docs, translation/chinese, size/L

#14618 [release-1.20] [zh] Translate Istio 2024-25 Steering Committee blog into Chinese
  content/zh/blog/2024/steering-results/index.md
Labels: size/L, release-notes-none

#14622 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14620 [zh] Fix a missed translation for Steering Committee blog
  content/zh/blog/2024/steering-results/index.md
Labels: kind/docs, translation/chinese, size/XS

#14623 Fix broken gateway-api links
  content/en/blog/2022/getting-started-gtwapi/index.md
  content/en/docs/ops/ambient/getting-started/index.md
  content/zh/blog/2022/getting-started-gtwapi/index.md
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: size/XS

#14624 [release-1.20] Fix broken gateway-api links
  content/en/blog/2022/getting-started-gtwapi/index.md
  content/en/docs/ops/ambient/getting-started/index.md
  content/zh/blog/2022/getting-started-gtwapi/index.md
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: size/XS, release-notes-none

#14626 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#14625 make image lines prettier in kiali telemetry
  content/en/docs/tasks/observability/kiali/index.md
Labels: kind/docs, size/L

#14629 [zh] Sync a task: observability/gateways/
  content/zh/docs/tasks/observability/gateways/index.md
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.20

#14630 [release-1.20] [zh] Sync a task: observability/gateways/
  content/zh/docs/tasks/observability/gateways/index.md
Labels: size/L, release-notes-none

#14631 [zh] Update a task: distributed-tracing/opencensusagent/
  content/zh/docs/tasks/observability/distributed-tracing/opencensusagent/index.md
Labels: kind/docs, translation/chinese, size/S

#14627 Add Control Plane to ecosystem page
  data/companies.yml
  static/logos/controlplane.svg
Labels: size/S, ok-to-test

#14632 Egress Gateway, istioctl command wrap with dquotes
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
Labels: size/XS, ok-to-test

#14635 gateway-api: istio.io/gateway-name -> gateway.networking.k8s.io/gatew…
  content/en/docs/reference/config/analysis/ist0166/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/index.md
  content/en/docs/tasks/security/authorization/authz-ingress/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/zh/docs/reference/config/analysis/ist0166/index.md
  content/zh/docs/tasks/security/authorization/authz-ingress/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-gateway/index.md
  content/zh/docs/tasks/traffic-management/ingress/gateway-api/index.md
Labels: size/M

#14638 Correct httpbin URL
  content/en/blog/2018/traffic-mirroring/index.md
  content/en/blog/2019/proxy/index.md
  content/zh/blog/2018/traffic-mirroring/index.md
  content/zh/blog/2019/proxy/index.md
Labels: size/XS, cherrypick/release-1.20

#14639 [release-1.20] Correct httpbin URL
  content/en/blog/2018/traffic-mirroring/index.md
  content/en/blog/2019/proxy/index.md
  content/zh/blog/2018/traffic-mirroring/index.md
  content/zh/blog/2019/proxy/index.md
Labels: size/XS, release-notes-none

#14640 [release-1.20] [zh] Sync #14421 into Chinese
  content/zh/docs/releases/supported-releases/index.md
Labels: size/S, release-notes-none

#14641 [zh] Manually fix cherrypick issue #14619
  content/zh/docs/releases/supported-releases/index.md
Labels: translation/chinese, size/S

#14643 Fix make server failure after hugo update
  content/zh/blog/2023/istio-graduates-within-cncf/index.md
Labels: size/XS

#14636 adding an Istio day banner for 2024
  content/en/events/banners/istio-day-eu-2024.md
Labels: kind/docs, size/XS, ok-to-test

#14637 Remove ambient alpha banner in light of beta next week
  content/en/events/banners/ambient-release.md
Labels: size/XS, cherrypick/release-1.20

#14646 [release-1.20] Remove ambient alpha banner in light of beta next week
  content/en/events/banners/ambient-release.md
Labels: size/XS, release-notes-none

#14648 [release-1.20] [zh] Sync #14598 into Chinese
  content/zh/news/releases/1.19.x/announcing-1.19.7/index.md
  content/zh/news/releases/1.20.x/announcing-1.20.3/index.md
  content/zh/news/security/istio-security-2024-001/index.md
Labels: size/L, release-notes-none

#14644 [zh] Sync #14636 into Chinese
  content/zh/events/banners/istio-day-eu-2024.md
Labels: translation/chinese, size/XS

#14649 [zh] Sync #14637 into Chinese
  content/zh/events/banners/ambient-release.md
Labels: kind/docs, translation/chinese, size/XS

#14650 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14651 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb-native.yaml
Labels: size/L, auto-merge, release-notes-none

#14652 Automator: update common-files@release-1.20 in istio/istio.io@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14653 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/XS, release-notes-none

#14656 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14657 Improve ambient uninstall section
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
Labels: kind/docs, size/S, area/ambient, cherrypick/release-1.20

#14658 [release-1.20] Improve ambient uninstall section
  content/en/docs/ops/ambient/getting-started/index.md
  content/en/docs/ops/ambient/getting-started/snips.sh
Labels: size/S, release-notes-none

#14659 [zh] Sync #14657 into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: kind/docs, translation/chinese, size/XS

#14628 [zh] Sync task: observability/kiali/
  content/zh/docs/tasks/observability/kiali/index.md
Labels: kind/docs, translation/chinese, size/L

#14660 [release-1.20] [zh] Sync #14657 into Chinese
  content/zh/docs/ops/ambient/getting-started/index.md
Labels: size/XS, release-notes-none

#14661 [zh] improve mesh-and-proxy-config
  content/zh/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/index.md
Labels: translation/chinese

#14654 gateway-api: add Gateway API instructions to wildcard egress doc
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/gtwapi_test.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh
Labels: size/L

#14663 [zh] Sync a task: egress/wildcard-egress-hosts/
  content/zh/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
Labels: kind/docs, translation/chinese, size/L

#14634 release note for 1.21
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.21.x/_index.md
  content/en/news/releases/1.21.x/announcing-1.21/_index.md
  content/en/news/releases/1.21.x/announcing-1.21/change-notes/index.md
  content/en/news/releases/1.21.x/announcing-1.21/upgrade-notes/index.md
  data/compatibility/supportStatus.yml
Labels: size/L

#14664 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#14668 [zh-cn] improve skywalking telemetry-api
  content/zh/docs/tasks/observability/distributed-tracing/skywalking/index.md
  content/zh/docs/tasks/observability/distributed-tracing/telemetry-api/index.md
Labels: size/L
