Repository istio/istio.io, pull requests merged in 2024-09, with the labels that each got.

#15635 in-doc header links broken under <tip>
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.23

#15637 [zh] Update zh text in ambient/install pages
  content/zh/docs/ambient/install/helm/index.md
  content/zh/docs/ambient/install/istioctl/index.md
  content/zh/docs/ambient/install/platform-prerequisites/index.md
  content/zh/docs/ambient/upgrade/helm/index.md
Labels: translation/chinese, size/L

#15639 [zh] Sync #15635 to fix in-doc header links broken under <tip>
  content/zh/docs/ops/best-practices/observability/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, translation/chinese, size/XS

#15638 [release-1.23] in-doc header links broken under <tip>
  content/en/docs/ops/best-practices/observability/index.md
  content/en/docs/setup/additional-setup/cni/index.md
Labels: size/XS, release-notes-none

#15641 updated the link for uninstallation of VM
  content/en/docs/examples/virtual-machines/index.md
Labels: size/XS, cherrypick/release-1.23

#15642 [release-1.23] updated the link for uninstallation of VM
  content/en/docs/examples/virtual-machines/index.md
Labels: size/XS, release-notes-none

#15611 further clarifications, addressing comments from previous PR
  content/en/docs/ambient/usage/waypoint/index.md
Labels: area/networking, size/S, area/ambient, cherrypick/release-1.23

#15643 [release-1.23] further clarifications, addressing comments from previous PR
  content/en/docs/ambient/usage/waypoint/index.md
Labels: size/S, release-notes-none

#15640 fix additional broken in-doc header links
  content/en/docs/ops/configuration/traffic-management/traffic-routing/index.md
  content/en/docs/ops/diagnostic-tools/cni/index.md
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/ops/configuration/traffic-management/traffic-routing/index.md
  content/zh/docs/ops/diagnostic-tools/cni/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: kind/docs, size/S, cherrypick/release-1.23

#15644 [release-1.23] fix additional broken in-doc header links
  content/en/docs/ops/configuration/traffic-management/traffic-routing/index.md
  content/en/docs/ops/diagnostic-tools/cni/index.md
  content/en/docs/setup/additional-setup/cni/index.md
  content/en/docs/setup/additional-setup/customize-installation/index.md
  content/en/docs/tasks/traffic-management/egress/egress-control/index.md
  content/zh/docs/ops/configuration/traffic-management/traffic-routing/index.md
  content/zh/docs/ops/diagnostic-tools/cni/index.md
  content/zh/docs/setup/additional-setup/cni/index.md
Labels: size/S, release-notes-none

#15645 [zh] Sync #15641 updated the link for uninstallation of VM into Chinese
  content/zh/docs/examples/virtual-machines/index.md
Labels: kind/docs, translation/chinese, size/XS

#15646 [zh] Sync #15611 clarifications, addressing comments into Chinese
  content/zh/docs/ambient/usage/waypoint/index.md
Labels: kind/docs, translation/chinese, size/S

#15650 Fix ports used by Istio
  content/en/docs/ops/deployment/application-requirements/index.md
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#15653 [release-1.23] Fix ports used by Istio
  content/en/docs/ops/deployment/application-requirements/index.md
Labels: size/XS, release-notes-none

#15654 [zh] Sync deployment/application-requirements and include #15650
  content/zh/docs/ops/deployment/application-requirements/index.md
Labels: kind/docs, translation/chinese, size/M

#15651 Update platform prereqs to use platform helm values
  content/en/docs/ambient/install/platform-prerequisites/index.md
  content/en/docs/setup/additional-setup/gateway/index.md
  content/en/docs/setup/additional-setup/gateway/snips.sh
  content/en/docs/setup/platform-setup/openshift/index.md
Labels: area/environments, kind/docs, size/M, area/ambient

#15655 [zh] update zh text in ops/deployment/deployment-models/
  content/zh/docs/ops/deployment/deployment-models/index.md
Labels: kind/docs, translation/chinese, size/L

#15658 [zh] Sync #15651 update platform prereqs to use platform helm values into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
  content/zh/docs/setup/additional-setup/gateway/index.md
  content/zh/docs/setup/platform-setup/openshift/index.md
Labels: kind/docs, translation/chinese, size/L

#15660 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15662 [multicluster] gateway api tests need not install istio gateways
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: kind/docs, size/S

#15661 add gtwapi install boilerplate to ambient helm install doc
  content/en/docs/ambient/install/helm/index.md
  content/en/docs/ambient/install/helm/snips.sh
Labels: area/environments, kind/docs, size/XS, area/ambient, cherrypick/release-1.23

#15663 [release-1.23] add gtwapi install boilerplate to ambient helm install doc
  content/en/docs/ambient/install/helm/index.md
  content/en/docs/ambient/install/helm/snips.sh
Labels: size/XS, release-notes-none

#15664 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
Labels: size/S, auto-merge, release-notes-none

#15665 Sync #15661 add gtwapi install boilerplate to ambient helm install doc into Chinese
  content/zh/docs/ambient/install/helm/index.md
Labels: kind/docs, translation/chinese, size/XS

#15669 [external-control-plane] - Use uniform mode for ingress/egress install
  content/en/docs/setup/install/external-controlplane/index.md
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/external-controlplane/test.sh
Labels: size/S

#15649 Document cross-namespace waypoints
  content/en/docs/ambient/usage/waypoint/index.md
  content/en/docs/ambient/usage/waypoint/snips.sh
Labels: area/networking, size/M, area/ambient, cherrypick/release-1.23

#15673 [release-1.23] Document cross-namespace waypoints
  content/en/docs/ambient/usage/waypoint/index.md
  content/en/docs/ambient/usage/waypoint/snips.sh
Labels: size/M, release-notes-none

#15676 Remove obsolete PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING from tests
  content/en/boilerplates/snips/gateway-api-gamma-experimental.sh
  content/en/docs/ambient/getting-started/snips.sh
  content/en/docs/ambient/install/istioctl/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/network-topologies/snips.sh
  content/en/docs/ops/diagnostic-tools/istioctl-analyze/snips.sh
  content/en/docs/ops/integrations/spire/snips.sh
  content/en/docs/setup/additional-setup/cni/snips.sh
  content/en/docs/setup/additional-setup/gateway/snips.sh
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/additional-setup/pod-security-admission/snips.sh
  content/en/docs/setup/getting-started/snips.sh
  content/en/docs/setup/install/external-controlplane/snips.sh
  content/en/docs/setup/install/multicluster/multi-primary/snips.sh
  content/en/docs/setup/install/multicluster/multi-primary_multi-network/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote/snips.sh
  content/en/docs/setup/install/multicluster/primary-remote_multi-network/snips.sh
  content/en/docs/setup/install/multiple-controlplanes/snips.sh
  content/en/docs/setup/install/virtual-machine/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/opentelemetry/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/sampling/snips.sh
  content/en/docs/tasks/observability/distributed-tracing/telemetry-api/snips.sh
  content/en/docs/tasks/observability/logs/access-log/snips.sh
  content/en/docs/tasks/observability/logs/otel-provider/snips.sh
  content/en/docs/tasks/observability/logs/telemetry-api/snips.sh
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authorization/authz-td-migration/snips.sh
  content/en/docs/tasks/security/cert-management/custom-ca-k8s/snips.sh
  content/en/docs/tasks/security/cert-management/plugin-ca-cert/snips.sh
  content/en/docs/tasks/security/tls-configuration/workload-min-tls-version/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/snips.sh
  content/en/docs/tasks/traffic-management/egress/egress-gateway/snips.sh
  content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh
  content/en/docs/tasks/traffic-management/ingress/gateway-api/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-control/snips.sh
  content/en/docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination/snips.sh
  scripts/snip.py
  tests/setup/dualstack/doc_test.go
  tests/setup/profile-ambient/doc_test.go
  tests/setup/profile-default/doc_test.go
  tests/setup/profile-demo/doc_test.go
  tests/setup/profile-minimal/doc_test.go
Labels: size/L, release-notes-none

#15671 [release-1.23] 1.23.1 Release Notes
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.23.x/announcing-1.23.1/index.md
  data/args.yml
Labels: size/L

#15674 [zh] Sync #15649 document cross-namespace waypoints into Chinese
  content/zh/docs/ambient/usage/waypoint/index.md
Labels: kind/docs, translation/chinese, size/M

#15678 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15682 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15683 add skip-cleanup for prow test script
  prow/integ-suite-kind.sh
Labels: kind/docs, size/XS

#15675 Update dualstack validation commands
  content/en/docs/setup/additional-setup/dual-stack/index.md
  content/zh/docs/setup/additional-setup/dual-stack/index.md
Labels: size/S

#15679 updated the link for installing istio
  content/en/docs/tasks/security/authorization/authz-dry-run/index.md
Labels: size/XS

#15685 [zh] Sync #15679 updated the link for installing istio into Chinese
  content/zh/docs/tasks/security/authorization/authz-dry-run/index.md
Labels: kind/docs, translation/chinese, size/XS

#15681 [zh] Sync #15595 bump master to next version into Chinese
  content/zh/about/faq/setup/install-method-selection.md
  content/zh/blog/2019/introducing-istio-operator/index.md
  content/zh/blog/2024/in-cluster-operator-deprecation-announcement/index.md
  content/zh/boilerplates/helm-preamble.md
  content/zh/docs/ambient/usage/waypoint/index.md
  content/zh/docs/ops/integrations/spire/index.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/install/external-controlplane/index.md
  content/zh/docs/setup/install/helm/index.md
  content/zh/docs/setup/install/multiple-controlplanes/index.md
  content/zh/docs/setup/install/operator/index.md
  content/zh/docs/tasks/traffic-management/egress/egress-kubernetes-services/index.md
  content/zh/news/releases/1.23.x/announcing-1.23/_index.md
  content/zh/news/releases/1.4.x/announcing-1.4/change-notes/index.md
  content/zh/news/releases/1.5.x/announcing-1.5/_index.md
Labels: kind/docs, translation/chinese, size/L

#15659 1.23.1 Release Notes
  content/en/news/releases/1.23.x/announcing-1.23.1/index.md
Labels: size/M

#15688 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#15684 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/istio.analysis.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/labels/index.html
  content/zh/docs/reference/config/meta/v1beta1/istio-status/index.html
  content/zh/docs/reference/config/networking/destination-rule/index.html
  content/zh/docs/reference/config/networking/envoy-filter/index.html
  content/zh/docs/reference/config/networking/gateway/index.html
  content/zh/docs/reference/config/networking/proxy-config/index.html
  content/zh/docs/reference/config/networking/service-entry/index.html
  content/zh/docs/reference/config/networking/sidecar/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/networking/workload-entry/index.html
  content/zh/docs/reference/config/networking/workload-group/index.html
  content/zh/docs/reference/config/proxy_extensions/stats/index.html
  content/zh/docs/reference/config/proxy_extensions/wasm-plugin/index.html
  content/zh/docs/reference/config/security/authorization-policy/index.html
  content/zh/docs/reference/config/security/peer_authentication/index.html
  content/zh/docs/reference/config/security/request_authentication/index.html
  content/zh/docs/reference/config/telemetry/index.html
  content/zh/docs/reference/config/type/workload-selector/index.html
  data/features.yaml
Labels: size/XXL, auto-merge, release-notes-none

#15691 edited base64 decode command
  content/en/docs/tasks/security/authorization/authz-jwt/index.md
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
Labels: kind/docs, size/XS, cherrypick/release-1.23

#15694 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#15690 [zh] Sync 1.23.1 release note into Chinese
  content/zh/news/releases/1.23.x/announcing-1.23.1/index.md
Labels: kind/docs, translation/chinese, size/M

#15697 renenable-skywalking-test
  content/en/docs/tasks/observability/distributed-tracing/skywalking/test.sh
Labels: size/XS

#15696 Add KUBEFLEX to the list of professional services providers
  data/companies.yml
  static/logos/kubeflex.png
Labels: kind/docs, size/XS, ok-to-test

#15699 chore: revert nit
  content/en/docs/tasks/observability/distributed-tracing/skywalking/test.sh
Labels: size/XS

#15672 Initial draft of a new security model doc
  .spelling
  content/en/docs/ops/deployment/security-model/index.md
Labels: size/L

#15702 [release-1.23] Initial draft of a new security model doc
  .spelling
  content/en/docs/ops/deployment/security-model/index.md
Labels: size/L, release-notes-none

#15695 [zh] Sync #15691 edited base64 decode command into Chinese
  content/zh/docs/tasks/security/authorization/authz-jwt/index.md
Labels: kind/docs, translation/chinese, size/XS

#15698 [zh] Manually cherry pick Chinese version blogs into release 1.23
  content/zh/blog/2024/in-cluster-operator-deprecation-announcement/index.md
  content/zh/blog/2024/introducing-sail-operator/index.md
Labels: translation/chinese, size/L

#15703 [zh] Sync Security Model deployment doc into Chinese
  content/zh/docs/ops/deployment/security-model/index.md
Labels: kind/docs, translation/chinese, size/L

#15704 Fix wrong links for security mode doc
  content/en/docs/ops/deployment/security-model/index.md
Labels: kind/docs, size/XS

#15707 [release-1.23] Fix wrong links for security mode doc
  content/en/docs/ops/deployment/security-model/index.md
Labels: size/XS, release-notes-none

#15693 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#15710 [release-1.23] security adv 2024-006
  .spelling
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/releases/supported-releases/index.md
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/install/operator/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.22.x/announcing-1.22.5/index.md
  content/en/news/releases/1.23.x/announcing-1.23.2/index.md
  content/en/news/security/istio-security-2024-006/index.md
  data/args.yml
Labels: size/L

#15711 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/M, auto-merge, release-notes-none

#15712 [release-1.23] fixes for sec adv 2024-006
  content/en/news/security/istio-security-2024-006/index.md
Labels: size/XS

#15714 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15713 Fix publish date for 1.22.5
  content/en/news/releases/1.22.x/announcing-1.22.5/index.md
Labels: kind/docs, size/XS, cherrypick/release-1.23

#15717 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#15720 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/XS, auto-merge, release-notes-none

#15716 [release-1.23] announce 1.21.6
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.21.x/announcing-1.21.6/index.md
Labels: size/S

#15721 Cherry pick of Istio Sec 2024-006 related PRs [1.23.2, 1.22.5, 1.21.6]
  .spelling
  content/en/docs/releases/supported-releases/index.md
  content/en/news/releases/1.21.x/announcing-1.21.6/index.md
  content/en/news/releases/1.22.x/announcing-1.22.5/index.md
  content/en/news/releases/1.23.x/announcing-1.23.2/index.md
  content/en/news/security/istio-security-2024-006/index.md
Labels: kind/docs, size/L

#15722 Fix year for 1.23.2 release
  content/en/news/releases/1.23.x/announcing-1.23.2/index.md
Labels: size/XS, cherrypick/release-1.23

#15723 [release-1.23] Fix year for 1.23.2 release
  content/en/news/releases/1.23.x/announcing-1.23.2/index.md
Labels: size/XS, release-notes-none

#15724 [zh] Sync 1.21.6, 1.22.5, 1.23.2 release notes with security update into Chinese
  content/zh/docs/releases/supported-releases/index.md
  content/zh/news/releases/1.21.x/announcing-1.21.6/index.md
  content/zh/news/releases/1.22.x/announcing-1.22.5/index.md
  content/zh/news/releases/1.23.x/announcing-1.23.2/index.md
  content/zh/news/security/istio-security-2024-006/index.md
Labels: kind/docs, translation/chinese, size/L

#15730 [zh] update primary-remote_multi-network/index.md
  content/zh/docs/setup/install/multicluster/primary-remote_multi-network/index.md
Labels: kind/docs, translation/chinese, size/S

#15731 Automator: update common-files@release-1.21 in istio/istio.io@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#15732 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/S, auto-merge, release-notes-none

#15735 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/S, auto-merge, release-notes-none

#15737 Announce 1.21 final EOL
  content/en/news/support/announcing-1.21-eol-final/index.md
Labels: size/S, cherrypick/release-1.23

#15738 [release-1.23] Announce 1.21 final EOL
  content/en/news/support/announcing-1.21-eol-final/index.md
Labels: size/S, release-notes-none

#15742 Fixup ambient cilium platform prerequisites - CCWNP default-deny + wording
  content/en/docs/ambient/install/platform-prerequisites/index.md
Labels: size/XS

#15745 [zh] Sync #15742 fixup ambient cilium platform prerequisites into Chinese
  content/zh/docs/ambient/install/platform-prerequisites/index.md
Labels: kind/docs, translation/chinese, size/S

#15739 [zh] Sync EOL 1.21 announcement into Chinese
  content/zh/news/support/announcing-1.21-eol-final/index.md
Labels: kind/docs, translation/chinese, size/S

#15741 add ifood to the list of users
  data/companies.yml
  static/logos/ifood.svg
Labels: size/S, ok-to-test

#15746 [release-1.23] add ifood to the list of users
  data/companies.yml
  static/logos/ifood.svg
Labels: size/S, release-notes-none
