Repository istio/istio.io, pull requests merged in 2025-02, with the labels that each got.

#16185 remove unnecessary semicolon which breaks zsh on mac
  content/en/boilerplates/gateway-api-install-crds.md
  content/en/boilerplates/snips/gateway-api-install-crds.sh
  content/uk/boilerplates/gateway-api-install-crds.md
  content/zh/boilerplates/gateway-api-install-crds.md
Labels: size/XS

#16218 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16220 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16219 add more socials
  i18n/en.toml
  layouts/partials/footer.html
  src/icons/bluesky.svg
  src/icons/linkedin.svg
  src/icons/mastodon.svg
Labels: size/M, cherrypick/release-1.24

#16221 [release-1.24] add more socials
  i18n/en.toml
  layouts/partials/footer.html
  src/icons/bluesky.svg
  src/icons/linkedin.svg
  src/icons/mastodon.svg
Labels: size/M, release-notes-none

#16216 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/S, release-notes-none

#16215 [zh] Sync Istio Day EU 2025 banner into Chinese
  content/zh/events/banners/istio-day-eu-2025.md
Labels: kind/docs, translation/chinese, size/XS

#16198 [zh] Sync #16193 15002 port in application-requirements into Chinese
  content/zh/docs/ops/deployment/application-requirements/index.md
Labels: kind/docs, translation/chinese, size/XS

#16213 [zh] Sync #16211 update attributegen doc into Chinese
  content/zh/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: kind/docs, translation/chinese, size/XS

#16222 [zh] Sync i18n for more socials into Chinese
  i18n/zh.toml
Labels: kind/docs, translation/chinese, size/XS

#16181 [zh] Sync #16178 fix typos in Ambient docs into Chinese
  content/zh/docs/ambient/usage/networkpolicy/index.md
Labels: kind/docs, translation/chinese, size/S

#16197 [zh] Sync 1.22.8 release notes and eol into Chinese
  content/zh/news/releases/1.22.x/announcing-1.22.8/index.md
  content/zh/news/support/announcing-1.22-eol-final/index.md
Labels: kind/docs, translation/chinese, size/M

#16223 docs: modify network policy doc note
  content/en/docs/ambient/usage/networkpolicy/index.md
Labels: kind/docs, size/XS, ok-to-test

#16225 docs: Change Platform Setup for Amazon EKS to more recent and refined instructions: Istio on EKS
  content/en/docs/setup/platform-setup/amazon-eks/index.md
Labels: kind/docs, size/XS, ok-to-test

#16227 [zh] Sync #16225 AWS EKS setup doc into Chinese
  content/zh/docs/setup/platform-setup/amazon-eks/index.md
Labels: kind/docs, translation/chinese, size/XS

#16226 [zh] Sync #16223 Ambient network policy update into Chinese
  content/zh/docs/ambient/usage/networkpolicy/index.md
Labels: kind/docs, translation/chinese, size/XS

#16229 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#16235 update attributegen doc with new wasm attribute format
  content/en/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: kind/docs, size/XS, ok-to-test

#16239 Bump support Kubernetes versions for 1.25+
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#16234 1.23.5 release notes
  content/en/news/releases/1.23.x/announcing-1.23.5/index.md
Labels: size/M, cherrypick/release-1.23

#16241 announce 2025 election
  content/en/blog/2025/steering-election/index.md
Labels: size/M, cherrypick/release-1.24

#16243 [release-1.24] announce 2025 election
  content/en/blog/2025/steering-election/index.md
Labels: size/M, release-notes-none

#16245 [zh] Sync announce 2025 election into Chinese
  content/zh/blog/2025/steering-election/index.md
Labels: kind/docs, translation/chinese, size/L

#16246 [release-1.24] [zh] Sync announce 2025 election into Chinese
  content/zh/blog/2025/steering-election/index.md
Labels: size/L, release-notes-none

#16237 [release-1.24] release 1.24.3 note
  content/en/boilerplates/snips/args.sh
  content/en/boilerplates/snips/revision-tags-middle.sh
  content/en/docs/ambient/install/helm/snips.sh
  content/en/docs/setup/additional-setup/getting-started-istio-apis/snips.sh
  content/en/docs/setup/install/helm/snips.sh
  content/en/docs/setup/upgrade/canary/snips.sh
  content/en/docs/setup/upgrade/helm/snips.sh
  content/en/news/releases/1.24.x/announcing-1.24.3/index.md
  data/args.yml
  tests/util/verify.sh
Labels: size/L

#16242 1.23.5 release notes (#16234)
  content/en/news/releases/1.23.x/announcing-1.23.5/index.md
Labels: size/M

#16248 Automator: update istio.io@ reference docs
  data/analysis.yaml
Labels: size/S, auto-merge, release-notes-none

#16250 Automator: update istio@ test reference
  go.mod
  go.sum
Labels: size/M, release-notes-none

#16238 [zh] Sync #16235 update new wasm attribute format for attributegen doc into Chinese
  content/zh/docs/tasks/observability/metrics/classify-metrics/index.md
Labels: kind/docs, translation/chinese, size/XS

#16230 clarify ambient mode installation required for dns-proxy
  content/en/docs/ops/configuration/traffic-management/dns-proxy/index.md
  content/en/docs/ops/configuration/traffic-management/dns-proxy/snips.sh
  content/en/docs/ops/configuration/traffic-management/dns-proxy/test.sh
Labels: kind/docs, size/M, area/ambient, cherrypick/release-1.24, cherrypick/release-1.25

#16254 [zh] Translate dns-proxy/index.md into Chinese by syncing with pr#16230
  content/zh/docs/ops/configuration/traffic-management/dns-proxy/index.md
Labels: kind/docs, translation/chinese, size/M, cherrypick/release-1.24

#16256 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16252 Update `UPSTREAM_CLUSTER` to `UPSTREAM_CLUSTER_RAW`
  content/en/docs/tasks/observability/logs/access-log/index.md
  content/en/docs/tasks/observability/logs/access-log/snips.sh
Labels: kind/docs, size/M, ok-to-test

#16258 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/M, auto-merge, release-notes-none

#16259 [zh] Sync #16252 Update UPSTREAM_CLUSTER to UPSTREAM_CLUSTER_RAW into Chinese
  content/zh/docs/tasks/observability/logs/access-log/index.md
Labels: kind/docs, translation/chinese, size/M

#16260 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/M, auto-merge, release-notes-none

#16263 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#16265 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
Labels: size/S, auto-merge, release-notes-none

#16266 Update index.md for GKE Autopilot
  content/en/docs/setup/platform-setup/gke/index.md
Labels: size/XS, ok-to-test, cherrypick/release-1.24

#16261 prepare for v1.25 as istio source is already branched
  Makefile.core.mk
  content/en/docs/examples/virtual-machines/snips.sh
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/en/docs/tasks/security/authentication/authn-policy/snips.sh
  content/en/docs/tasks/security/authentication/claim-to-header/snips.sh
  content/en/docs/tasks/security/authentication/jwt-route/snips.sh
  content/en/docs/tasks/security/authorization/authz-custom/snips.sh
  content/en/docs/tasks/security/authorization/authz-jwt/snips.sh
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
  data/args.yml
  go.mod
  go.sum
Labels: size/L

#16268 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16269 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/en/docs/reference/config/networking/virtual-service/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/config/networking/virtual-service/index.html
Labels: size/L, auto-merge, release-notes-none

#16267 Update companies.yml
  data/companies.yml
  static/logos/it-schulungen.png
Labels: size/XS, ok-to-test

#16273 [release-1.24] [zh] Sync #16266 GKE Autopilot doc update into Chinese
  content/zh/docs/setup/platform-setup/gke/index.md
Labels: size/XS, release-notes-none

#16262 docs: fix istiooperator upgrade guide
  content/en/blog/2024/in-cluster-operator-deprecation-announcement/index.md
Labels: kind/docs, size/XS, ok-to-test, cherrypick/release-1.24

#16275 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#16274 [zh] Sync #16262 istiooperator upgrade guide fix into Chinese
  content/zh/blog/2024/in-cluster-operator-deprecation-announcement/index.md
Labels: kind/docs, translation/chinese, size/S

#16278 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
