Repository istio/istio.io, pull requests merged in 2025-07, with the labels that each got.

#16625 docs: update zh punctuation
  content/zh/docs/_index.md
Labels: kind/docs, translation/chinese, size/XS, ok-to-test

#16631 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/M, auto-merge, release-notes-none

#16629 Add Kmesh Integration
  data/companies.yml
  static/logos/kmesh.png
Labels: size/XS

#16634 [zh] Sync #16632 add a concrete example of an allow-nothing binding to istio-waypoint into Chinese
  content/zh/docs/ops/best-practices/security/index.md
Labels: kind/docs, translation/chinese, size/S

#16637 LFX'25:Update the pipeline to achieve clean build without any errors
  Makefile.core.mk
  scripts/gen_site.sh
  src/ts/callToAction.ts
  src/ts/codeBlocks.ts
  src/ts/constants.ts
  src/ts/entrypoint.ts
  src/ts/events.ts
  src/ts/faq.ts
  src/ts/feedback.ts
  src/ts/header.ts
  src/ts/kbdnav.ts
  src/ts/lang.ts
  src/ts/links.ts
  src/ts/menu.ts
  src/ts/overlays.ts
  src/ts/resizeObserver.js
  src/ts/scroll.ts
  src/ts/sidebar.ts
  src/ts/tabset.ts
  src/ts/themes.ts
  src/ts/themes_init.ts
  src/ts/utils.ts
Labels: area/test and release, kind/docs, size/L

#16641 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#16642 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16643 [uk] Sync Ukrainian translation with upstream documentation
  content/uk/_index.html
  content/uk/docs/ambient/usage/l7-features/index.md
  content/uk/docs/ambient/usage/waypoint/index.md
  content/uk/docs/ops/best-practices/security/index.md
  content/uk/docs/ops/diagnostic-tools/istioctl-analyze/index.md
  content/uk/docs/overview/dataplane-modes/index.md
  content/uk/docs/overview/quickstart/index.md
  content/uk/docs/releases/supported-releases/index.md
  content/uk/docs/tasks/security/authorization/authz-custom/index.md
  content/uk/docs/tasks/security/cert-management/plugin-ca-cert/index.md
  content/uk/docs/tasks/traffic-management/ingress/gateway-api/index.md
  content/uk/news/releases/1.24.x/announcing-1.24.6/index.md
  content/uk/news/releases/1.25.x/announcing-1.25.3/index.md
  content/uk/news/releases/1.26.x/announcing-1.26.1/index.md
  content/uk/news/releases/1.26.x/announcing-1.26/_index.md
  content/uk/news/support/announcing-1.24-eol-final/index.md
  content/uk/news/support/announcing-1.24-eol/index.md
Labels: size/L

#16646 Add Kubernetes 1.33 support to 1.26 and master
  data/compatibility/supportStatus.yml
Labels: area/test and release, size/XS, cherrypick/release-1.26

#16647 [release-1.26] Add Kubernetes 1.33 support to 1.26 and master
  data/compatibility/supportStatus.yml
Labels: size/XS, release-notes-none

#16650 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16653 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/install-cni/index.html
  content/en/docs/reference/commands/istioctl/index.html
  content/en/docs/reference/commands/pilot-agent/index.html
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/install-cni/index.html
  content/zh/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/L, auto-merge, release-notes-none

#16654 Fix: typescript errors
  src/ts/resizeObserver.js
  src/ts/sidebar.ts
Labels: area/test and release, kind/docs, size/XS

#16657 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/istioctl/index.html
  content/zh/docs/reference/commands/istioctl/index.html
Labels: size/M, auto-merge, release-notes-none

#16656 fix: update cloudnative.to link, ref #16655
  content/en/get-involved/_index.md
  content/uk/get-involved/_index.md
  content/zh/get-involved/_index.md
Labels: kind/docs, size/XS, ok-to-test

#16658 [release-1.26] fix: update cloudnative.to link, ref #16655
  content/en/get-involved/_index.md
  content/uk/get-involved/_index.md
  content/zh/get-involved/_index.md
Labels: size/XS, release-notes-none

#16665 Add Documentation for ClusterTrustBundle
  .spelling
  content/en/docs/concepts/security/index.md
Labels: area/test and release, kind/docs, size/M

#16671 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-agent/index.html
  content/zh/docs/reference/commands/pilot-agent/index.html
Labels: size/S, auto-merge, release-notes-none

#16674 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16675 Automator: update common-files@master in istio/istio.io@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#16540 [release-1.26] Redirect any "v.XX" not including docs to "latest" using a netlify edge function
  .gitignore
  netlify.toml
  netlify/edge-functions/redirect-to-latest.ts
  scripts/test_netlify_redirects.sh
Labels: size/L, lifecycle/staleproof, release-notes-none

#16526 Add override for redirects
  netlify/edge-functions/redirect-to-latest.ts
Labels: size/XS, lifecycle/staleproof, cherrypick/release-1.26

#16676 [release-1.26] Add override for redirects
  netlify/edge-functions/redirect-to-latest.ts
Labels: size/XS, release-notes-none

#16678 docs(zh): fix zh docs error
  content/zh/docs/overview/dataplane-modes/index.md
Labels: kind/docs, size/XS, ok-to-test

#16682 [release-1.26] make /latest the latest
  content/en/_index.html
  layouts/index.redir
  layouts/partials/header.html
Labels: size/S, release-notes-none

#16683 cherrypick 1.26.2 relnote
  content/en/news/releases/1.26.x/announcing-1.26.2/index.md
Labels: size/S

#16687 Automator: update common-files@master in istio/istio.io@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#16690 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/istio.mesh.v1alpha1/index.html
  content/zh/docs/reference/config/istio.mesh.v1alpha1/index.html
Labels: size/L, auto-merge, release-notes-none

#16694 Automator: update istio.io@ reference docs
  content/en/docs/reference/commands/pilot-discovery/index.html
  content/zh/docs/reference/commands/pilot-discovery/index.html
Labels: size/S, auto-merge, release-notes-none

#16698 Automator: update istio.io@ reference docs
  content/en/docs/reference/config/annotations/index.html
  content/zh/docs/reference/config/annotations/index.html
Labels: size/M, auto-merge, release-notes-none

#16672 [zh] Sync #16665 ClusterTrustBundle Documentation with some improvement into Chinese
  content/zh/docs/concepts/security/index.md
Labels: kind/docs, translation/chinese, size/L

#16699 [zh] Sync install/external-controlplane/ and its images
  content/zh/docs/setup/install/external-controlplane/external-controlplane.svg
  content/zh/docs/setup/install/external-controlplane/external-multicluster.svg
  content/zh/docs/setup/install/external-controlplane/index.md
Labels: kind/docs, translation/chinese, size/L

#16695 [ES] broken links
  content/es/_index.html
  content/es/news/_index.md
  content/es/news/releases/_index.md
  content/es/news/security/_index.md
  content/es/news/support/_index.md
  hugo.toml
  i18n/en.toml
  i18n/es.toml
  layouts/404.html
  layouts/partials/footer.html
Labels: kind/docs, size/M, ok-to-test

#16667 add roadmap
  .spelling
  content/en/blog/2025/roadmap/index.md
Labels: size/M

#16706 [release-1.26] add istio inference support blog
  .spelling
  content/en/blog/2025/inference-extension-support/index.md
  content/en/blog/2025/inference-extension-support/inference-request-flow.svg
Labels: size/L, release-notes-none

#16712 [release-1.26] fix year of release for 1.26.3
  content/en/news/releases/1.26.x/announcing-1.26.3/index.md
Labels: kind/docs, size/XS

#16710 [zh] Sync inference extension support blog into Chinese
  content/zh/blog/2025/inference-extension-support/index.md
  content/zh/blog/2025/inference-extension-support/inference-request-flow.svg
Labels: kind/docs, translation/chinese, size/L, cherrypick/release-1.26

#16716 [release-1.26] [zh] Sync 1.26.3 release notes into Chinese
  content/zh/news/releases/1.26.x/announcing-1.26.3/index.md
Labels: size/M, release-notes-none

#16717 [release-1.26] [zh] Sync roadmap blog into Chinese
  content/zh/blog/2025/roadmap/index.md
Labels: size/L, release-notes-none

#16718 [release-1.26] [zh] Sync inference extension support blog into Chinese
  content/zh/blog/2025/inference-extension-support/index.md
  content/zh/blog/2025/inference-extension-support/inference-request-flow.svg
Labels: size/L, release-notes-none

#16270 Add Jar as a user of istio
  data/companies.yml
  static/logos/jar_bimi_compliant.svg
Labels: kind/docs, size/XS, ok-to-test

#16720 [zh] Localize Inference extension blog image into Chinese
  content/zh/blog/2025/inference-extension-support/inference-request-flow.svg
Labels: kind/docs, translation/chinese, size/XXL, cherrypick/release-1.26

#16726 remove 1.24 as it's EOL
  content/en/docs/releases/supported-releases/index.md
Labels: size/XS

#16569 bump:Hugo to v0.147.8
  netlify.toml
Labels: kind/docs, size/XS, ok-to-test

#16731 [zh] Sync #16719 support cacert in tls.credentialNames into Chinese
  content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
Labels: kind/docs, translation/chinese, size/XS
